pub mod constant_table;
mod constant_table_builder;
pub mod exception_handlers;
pub mod function;
pub mod generator;
pub mod instruction;
mod operand;
mod register_allocator;
mod stack_frame;
pub mod vm;
mod width;
mod writer;
