[BytecodeFunction: <module>] {
  Parameters: 0, Registers: 3
     0: Mov r0, a0
     3: LoadImmediate r1, 1
     6: LoadImmediate r2, 2
     9: Add r1, r1, r2, fb0
    14: LoadImmediate r1, 3
    17: Await r1, r2, r0, r1
    22: JumpTrue r2, 5 (.L0)
    25: Throw r1
  .L0:
    27: LoadImmediate r1, 4
    30: LoadImmediate r2, 5
    33: Add r1, r1, r2, fb1
    38: LoadUndefined r1
    40: ResolvePromise r0, r1
    43: Ret r0
    45: RejectPromise r0, r1
    48: LoadUndefined r0
    50: Ret r0
  Exception Handlers:
    3-45 -> 45 (r1)
}
