{
  type: "Program",
  loc: "1:1-42:18",
  body: [
    {
      type: "EmptyStatement",
      loc: "3:1-3:2",
    },
    {
      type: "EmptyStatement",
      loc: "5:1-5:2",
    },
    {
      type: "EmptyStatement",
      loc: "5:2-5:3",
    },
    {
      type: "EmptyStatement",
      loc: "5:3-5:4",
    },
    {
      type: "DebuggerStatement",
      loc: "7:1-7:10",
    },
    {
      type: "Block",
      loc: "11:1-11:3",
      body: [],
    },
    {
      type: "Block",
      loc: "13:1-16:2",
      body: [
        {
          type: "ExpressionStatement",
          loc: "14:3-14:5",
          kind: {
            type: "Identifier",
            loc: "14:3-14:4",
            name: "a",
          },
        },
        {
          type: "ExpressionStatement",
          loc: "15:3-15:5",
          kind: {
            type: "Identifier",
            loc: "15:3-15:4",
            name: "b",
          },
        },
      ],
    },
    {
      type: "WithStatement",
      loc: "20:1-20:12",
      object: {
        type: "Identifier",
        loc: "20:7-20:8",
        name: "a",
      },
      body: {
        type: "ExpressionStatement",
        loc: "20:10-20:12",
        kind: {
          type: "Identifier",
          loc: "20:10-20:11",
          name: "b",
        },
      },
    },
    {
      type: "WithStatement",
      loc: "22:1-22:16",
      object: {
        type: "Identifier",
        loc: "22:7-22:8",
        name: "a",
      },
      body: {
        type: "Block",
        loc: "22:10-22:16",
        body: [
          {
            type: "ExpressionStatement",
            loc: "22:12-22:14",
            kind: {
              type: "Identifier",
              loc: "22:12-22:13",
              name: "b",
            },
          },
        ],
      },
    },
    {
      type: "ReturnStatement",
      loc: "26:1-26:8",
      argument: null,
    },
    {
      type: "ReturnStatement",
      loc: "28:1-28:10",
      argument: {
        type: "Identifier",
        loc: "28:8-28:9",
        name: "a",
      },
    },
    {
      type: "BreakStatement",
      loc: "30:1-30:7",
      label: null,
    },
    {
      type: "BreakStatement",
      loc: "32:1-32:9",
      label: {
        type: "Identifier",
        loc: "32:7-32:8",
        name: "a",
      },
    },
    {
      type: "ContinueStatement",
      loc: "34:1-34:10",
      label: null,
    },
    {
      type: "ContinueStatement",
      loc: "36:1-36:12",
      label: {
        type: "Identifier",
        loc: "36:10-36:11",
        name: "a",
      },
    },
    {
      type: "LabeledStatement",
      loc: "40:1-40:13",
      label: {
        type: "Identifier",
        loc: "40:1-40:4",
        name: "foo",
      },
      body: {
        type: "ReturnStatement",
        loc: "40:6-40:13",
        argument: null,
      },
    },
    {
      type: "LabeledStatement",
      loc: "42:1-42:18",
      label: {
        type: "Identifier",
        loc: "42:1-42:4",
        name: "foo",
      },
      body: {
        type: "LabeledStatement",
        loc: "42:6-42:18",
        label: {
          type: "Identifier",
          loc: "42:6-42:9",
          name: "bar",
        },
        body: {
          type: "ReturnStatement",
          loc: "42:11-42:18",
          argument: null,
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}