{
  type: "Program",
  loc: "1:0-42:17",
  body: [
    {
      type: "EmptyStatement",
      loc: "3:0-3:1",
    },
    {
      type: "EmptyStatement",
      loc: "5:0-5:1",
    },
    {
      type: "EmptyStatement",
      loc: "5:1-5:2",
    },
    {
      type: "EmptyStatement",
      loc: "5:2-5:3",
    },
    {
      type: "DebuggerStatement",
      loc: "7:0-7:9",
    },
    {
      type: "Block",
      loc: "11:0-11:2",
      body: [],
    },
    {
      type: "Block",
      loc: "13:0-16:1",
      body: [
        {
          type: "ExpressionStatement",
          loc: "14:2-14:4",
          kind: {
            type: "Identifier",
            loc: "14:2-14:3",
            name: "a",
          },
        },
        {
          type: "ExpressionStatement",
          loc: "15:2-15:4",
          kind: {
            type: "Identifier",
            loc: "15:2-15:3",
            name: "b",
          },
        },
      ],
    },
    {
      type: "WithStatement",
      loc: "20:0-20:11",
      object: {
        type: "Identifier",
        loc: "20:6-20:7",
        name: "a",
      },
      body: {
        type: "ExpressionStatement",
        loc: "20:9-20:11",
        kind: {
          type: "Identifier",
          loc: "20:9-20:10",
          name: "b",
        },
      },
    },
    {
      type: "WithStatement",
      loc: "22:0-22:15",
      object: {
        type: "Identifier",
        loc: "22:6-22:7",
        name: "a",
      },
      body: {
        type: "Block",
        loc: "22:9-22:15",
        body: [
          {
            type: "ExpressionStatement",
            loc: "22:11-22:13",
            kind: {
              type: "Identifier",
              loc: "22:11-22:12",
              name: "b",
            },
          },
        ],
      },
    },
    {
      type: "ReturnStatement",
      loc: "26:0-26:7",
      argument: null,
    },
    {
      type: "ReturnStatement",
      loc: "28:0-28:9",
      argument: {
        type: "Identifier",
        loc: "28:7-28:8",
        name: "a",
      },
    },
    {
      type: "BreakStatement",
      loc: "30:0-30:6",
      label: null,
    },
    {
      type: "BreakStatement",
      loc: "32:0-32:8",
      label: {
        type: "Identifier",
        loc: "32:6-32:7",
        name: "a",
      },
    },
    {
      type: "ContinueStatement",
      loc: "34:0-34:9",
      label: null,
    },
    {
      type: "ContinueStatement",
      loc: "36:0-36:11",
      label: {
        type: "Identifier",
        loc: "36:9-36:10",
        name: "a",
      },
    },
    {
      type: "LabeledStatement",
      loc: "40:0-40:12",
      label: {
        type: "Identifier",
        loc: "40:0-40:3",
        name: "foo",
      },
      body: {
        type: "ReturnStatement",
        loc: "40:5-40:12",
        argument: null,
      },
    },
    {
      type: "LabeledStatement",
      loc: "42:0-42:17",
      label: {
        type: "Identifier",
        loc: "42:0-42:3",
        name: "foo",
      },
      body: {
        type: "LabeledStatement",
        loc: "42:5-42:17",
        label: {
          type: "Identifier",
          loc: "42:5-42:8",
          name: "bar",
        },
        body: {
          type: "ReturnStatement",
          loc: "42:10-42:17",
          argument: null,
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}