{
  type: "Program",
  loc: "1:0-12:1",
  body: [
    {
      type: "EmptyStatement",
      loc: "1:0-1:1",
    },
    {
      type: "EmptyStatement",
      loc: "3:0-3:1",
    },
    {
      type: "EmptyStatement",
      loc: "3:1-3:2",
    },
    {
      type: "EmptyStatement",
      loc: "3:2-3:3",
    },
    {
      type: "DebuggerStatement",
      loc: "5:0-5:9",
    },
    {
      type: "Block",
      loc: "7:0-7:2",
      body: [],
    },
    {
      type: "Block",
      loc: "9:0-12:1",
      body: [
        {
          type: "ExpressionStatement",
          loc: "10:2-10:4",
          kind: {
            type: "Identifier",
            loc: "10:2-10:3",
            name: "a",
          },
        },
        {
          type: "ExpressionStatement",
          loc: "11:2-11:4",
          kind: {
            type: "Identifier",
            loc: "11:2-11:3",
            name: "b",
          },
        },
      ],
    },
  ],
}