{
  type: "Program",
  loc: "1:0-19:25",
  body: [
    {
      type: "ForOfStatement",
      loc: "1:0-1:19",
      left: {
        type: "VariableDeclaration",
        loc: "1:5-1:10",
        kind: "var",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "1:9-1:10",
            id: {
              type: "Identifier",
              loc: "1:9-1:10",
              name: "a",
            },
            init: null,
          },
        ],
      },
      right: {
        type: "Identifier",
        loc: "1:14-1:15",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "1:17-1:19",
        body: [],
      },
      await: false,
    },
    {
      type: "ForInStatement",
      loc: "3:0-3:19",
      left: {
        type: "VariableDeclaration",
        loc: "3:5-3:10",
        kind: "var",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "3:9-3:10",
            id: {
              type: "Identifier",
              loc: "3:9-3:10",
              name: "a",
            },
            init: null,
          },
        ],
      },
      right: {
        type: "Identifier",
        loc: "3:14-3:15",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "3:17-3:19",
        body: [],
      },
    },
    {
      type: "ForOfStatement",
      loc: "5:0-5:19",
      left: {
        type: "VariableDeclaration",
        loc: "5:5-5:10",
        kind: "let",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "5:9-5:10",
            id: {
              type: "Identifier",
              loc: "5:9-5:10",
              name: "a",
            },
            init: null,
          },
        ],
      },
      right: {
        type: "Identifier",
        loc: "5:14-5:15",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "5:17-5:19",
        body: [],
      },
      await: false,
    },
    {
      type: "ForOfStatement",
      loc: "7:0-7:21",
      left: {
        type: "VariableDeclaration",
        loc: "7:5-7:12",
        kind: "const",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "7:11-7:12",
            id: {
              type: "Identifier",
              loc: "7:11-7:12",
              name: "a",
            },
            init: null,
          },
        ],
      },
      right: {
        type: "Identifier",
        loc: "7:16-7:17",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "7:19-7:21",
        body: [],
      },
      await: false,
    },
    {
      type: "ForOfStatement",
      loc: "9:0-9:15",
      left: {
        type: "Identifier",
        loc: "9:5-9:6",
        name: "a",
      },
      right: {
        type: "Identifier",
        loc: "9:10-9:11",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "9:13-9:15",
        body: [],
      },
      await: false,
    },
    {
      type: "ForInStatement",
      loc: "11:0-11:15",
      left: {
        type: "Identifier",
        loc: "11:5-11:6",
        name: "a",
      },
      right: {
        type: "Identifier",
        loc: "11:10-11:11",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "11:13-11:15",
        body: [],
      },
    },
    {
      type: "FunctionDeclaration",
      loc: "13:0-16:1",
      id: {
        type: "Identifier",
        loc: "13:15-13:18",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "13:21-16:1",
        body: [
          {
            type: "ForOfStatement",
            loc: "14:2-14:23",
            left: {
              type: "Identifier",
              loc: "14:13-14:14",
              name: "a",
            },
            right: {
              type: "Identifier",
              loc: "14:18-14:19",
              name: "b",
            },
            body: {
              type: "Block",
              loc: "14:21-14:23",
              body: [],
            },
            await: true,
          },
          {
            type: "ForOfStatement",
            loc: "15:2-15:27",
            left: {
              type: "Identifier",
              loc: "15:13-15:18",
              name: "async",
            },
            right: {
              type: "Identifier",
              loc: "15:22-15:23",
              name: "b",
            },
            body: {
              type: "Block",
              loc: "15:25-15:27",
              body: [],
            },
            await: true,
          },
        ],
      },
      async: true,
      generator: false,
      has_use_strict_directive: false,
    },
    {
      type: "ForInStatement",
      loc: "19:0-19:25",
      left: {
        type: "VariableDeclaration",
        loc: "19:5-19:10",
        kind: "var",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "19:9-19:10",
            id: {
              type: "Identifier",
              loc: "19:9-19:10",
              name: "a",
            },
            init: null,
          },
        ],
      },
      right: {
        type: "SequenceExpression",
        loc: "19:14-19:21",
        expressions: [
          {
            type: "Literal",
            loc: "19:14-19:15",
            value: 1,
          },
          {
            type: "Literal",
            loc: "19:17-19:18",
            value: 2,
          },
          {
            type: "Literal",
            loc: "19:20-19:21",
            value: 3,
          },
        ],
      },
      body: {
        type: "Block",
        loc: "19:23-19:25",
        body: [],
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}