{
  type: "Program",
  loc: "1:1-19:26",
  body: [
    {
      type: "ForOfStatement",
      loc: "1:1-1:20",
      left: {
        type: "VariableDeclaration",
        loc: "1:6-1:11",
        kind: "var",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "1:10-1:11",
            id: {
              type: "Identifier",
              loc: "1:10-1:11",
              name: "a",
            },
            init: null,
          },
        ],
      },
      right: {
        type: "Identifier",
        loc: "1:15-1:16",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "1:18-1:20",
        body: [],
      },
      await: false,
    },
    {
      type: "ForInStatement",
      loc: "3:1-3:20",
      left: {
        type: "VariableDeclaration",
        loc: "3:6-3:11",
        kind: "var",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "3:10-3:11",
            id: {
              type: "Identifier",
              loc: "3:10-3:11",
              name: "a",
            },
            init: null,
          },
        ],
      },
      right: {
        type: "Identifier",
        loc: "3:15-3:16",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "3:18-3:20",
        body: [],
      },
    },
    {
      type: "ForOfStatement",
      loc: "5:1-5:20",
      left: {
        type: "VariableDeclaration",
        loc: "5:6-5:11",
        kind: "let",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "5:10-5:11",
            id: {
              type: "Identifier",
              loc: "5:10-5:11",
              name: "a",
            },
            init: null,
          },
        ],
      },
      right: {
        type: "Identifier",
        loc: "5:15-5:16",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "5:18-5:20",
        body: [],
      },
      await: false,
    },
    {
      type: "ForOfStatement",
      loc: "7:1-7:22",
      left: {
        type: "VariableDeclaration",
        loc: "7:6-7:13",
        kind: "const",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "7:12-7:13",
            id: {
              type: "Identifier",
              loc: "7:12-7:13",
              name: "a",
            },
            init: null,
          },
        ],
      },
      right: {
        type: "Identifier",
        loc: "7:17-7:18",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "7:20-7:22",
        body: [],
      },
      await: false,
    },
    {
      type: "ForOfStatement",
      loc: "9:1-9:16",
      left: {
        type: "Identifier",
        loc: "9:6-9:7",
        name: "a",
      },
      right: {
        type: "Identifier",
        loc: "9:11-9:12",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "9:14-9:16",
        body: [],
      },
      await: false,
    },
    {
      type: "ForInStatement",
      loc: "11:1-11:16",
      left: {
        type: "Identifier",
        loc: "11:6-11:7",
        name: "a",
      },
      right: {
        type: "Identifier",
        loc: "11:11-11:12",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "11:14-11:16",
        body: [],
      },
    },
    {
      type: "FunctionDeclaration",
      loc: "13:1-16:2",
      id: {
        type: "Identifier",
        loc: "13:16-13:19",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "13:22-16:2",
        body: [
          {
            type: "ForOfStatement",
            loc: "14:3-14:24",
            left: {
              type: "Identifier",
              loc: "14:14-14:15",
              name: "a",
            },
            right: {
              type: "Identifier",
              loc: "14:19-14:20",
              name: "b",
            },
            body: {
              type: "Block",
              loc: "14:22-14:24",
              body: [],
            },
            await: true,
          },
          {
            type: "ForOfStatement",
            loc: "15:3-15:28",
            left: {
              type: "Identifier",
              loc: "15:14-15:19",
              name: "async",
            },
            right: {
              type: "Identifier",
              loc: "15:23-15:24",
              name: "b",
            },
            body: {
              type: "Block",
              loc: "15:26-15:28",
              body: [],
            },
            await: true,
          },
        ],
      },
      async: true,
      generator: false,
      has_use_strict_directive: false,
    },
    {
      type: "ForInStatement",
      loc: "19:1-19:26",
      left: {
        type: "VariableDeclaration",
        loc: "19:6-19:11",
        kind: "var",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "19:10-19:11",
            id: {
              type: "Identifier",
              loc: "19:10-19:11",
              name: "a",
            },
            init: null,
          },
        ],
      },
      right: {
        type: "SequenceExpression",
        loc: "19:15-19:22",
        expressions: [
          {
            type: "Literal",
            loc: "19:15-19:16",
            value: 1,
          },
          {
            type: "Literal",
            loc: "19:18-19:19",
            value: 2,
          },
          {
            type: "Literal",
            loc: "19:21-19:22",
            value: 3,
          },
        ],
      },
      body: {
        type: "Block",
        loc: "19:24-19:26",
        body: [],
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}