{
  type: "Program",
  loc: "1:1-29:2",
  body: [
    {
      type: "IfStatement",
      loc: "1:1-1:10",
      test: {
        type: "Identifier",
        loc: "1:5-1:6",
        name: "a",
      },
      consequent: {
        type: "ExpressionStatement",
        loc: "1:8-1:10",
        kind: {
          type: "Identifier",
          loc: "1:8-1:9",
          name: "b",
        },
      },
      alternate: null,
    },
    {
      type: "IfStatement",
      loc: "3:1-3:18",
      test: {
        type: "Identifier",
        loc: "3:5-3:6",
        name: "a",
      },
      consequent: {
        type: "ExpressionStatement",
        loc: "3:8-3:10",
        kind: {
          type: "Identifier",
          loc: "3:8-3:9",
          name: "b",
        },
      },
      alternate: {
        type: "ExpressionStatement",
        loc: "3:16-3:18",
        kind: {
          type: "Identifier",
          loc: "3:16-3:17",
          name: "c",
        },
      },
    },
    {
      type: "IfStatement",
      loc: "5:1-5:14",
      test: {
        type: "Identifier",
        loc: "5:5-5:6",
        name: "a",
      },
      consequent: {
        type: "Block",
        loc: "5:8-5:14",
        body: [
          {
            type: "ExpressionStatement",
            loc: "5:10-5:12",
            kind: {
              type: "Identifier",
              loc: "5:10-5:11",
              name: "b",
            },
          },
        ],
      },
      alternate: null,
    },
    {
      type: "IfStatement",
      loc: "7:1-7:26",
      test: {
        type: "Identifier",
        loc: "7:5-7:6",
        name: "a",
      },
      consequent: {
        type: "Block",
        loc: "7:8-7:14",
        body: [
          {
            type: "ExpressionStatement",
            loc: "7:10-7:12",
            kind: {
              type: "Identifier",
              loc: "7:10-7:11",
              name: "b",
            },
          },
        ],
      },
      alternate: {
        type: "Block",
        loc: "7:20-7:26",
        body: [
          {
            type: "ExpressionStatement",
            loc: "7:22-7:24",
            kind: {
              type: "Identifier",
              loc: "7:22-7:23",
              name: "c",
            },
          },
        ],
      },
    },
    {
      type: "IfStatement",
      loc: "9:1-15:2",
      test: {
        type: "Identifier",
        loc: "9:5-9:6",
        name: "a",
      },
      consequent: {
        type: "Block",
        loc: "9:8-15:2",
        body: [
          {
            type: "IfStatement",
            loc: "10:3-14:4",
            test: {
              type: "Identifier",
              loc: "10:7-10:8",
              name: "b",
            },
            consequent: {
              type: "Block",
              loc: "10:10-12:4",
              body: [
                {
                  type: "ExpressionStatement",
                  loc: "11:5-11:7",
                  kind: {
                    type: "Identifier",
                    loc: "11:5-11:6",
                    name: "c",
                  },
                },
              ],
            },
            alternate: {
              type: "Block",
              loc: "12:10-14:4",
              body: [
                {
                  type: "ExpressionStatement",
                  loc: "13:5-13:7",
                  kind: {
                    type: "Identifier",
                    loc: "13:5-13:6",
                    name: "d",
                  },
                },
              ],
            },
          },
        ],
      },
      alternate: null,
    },
    {
      type: "IfStatement",
      loc: "17:1-21:7",
      test: {
        type: "Identifier",
        loc: "17:5-17:6",
        name: "a",
      },
      consequent: {
        type: "IfStatement",
        loc: "18:3-21:7",
        test: {
          type: "Identifier",
          loc: "18:7-18:8",
          name: "b",
        },
        consequent: {
          type: "ExpressionStatement",
          loc: "19:5-19:7",
          kind: {
            type: "Identifier",
            loc: "19:5-19:6",
            name: "c",
          },
        },
        alternate: {
          type: "ExpressionStatement",
          loc: "21:5-21:7",
          kind: {
            type: "Identifier",
            loc: "21:5-21:6",
            name: "d",
          },
        },
      },
      alternate: null,
    },
    {
      type: "IfStatement",
      loc: "23:1-29:2",
      test: {
        type: "Identifier",
        loc: "23:5-23:6",
        name: "a",
      },
      consequent: {
        type: "Block",
        loc: "23:8-25:2",
        body: [
          {
            type: "ExpressionStatement",
            loc: "24:3-24:5",
            kind: {
              type: "Identifier",
              loc: "24:3-24:4",
              name: "b",
            },
          },
        ],
      },
      alternate: {
        type: "IfStatement",
        loc: "25:8-29:2",
        test: {
          type: "Identifier",
          loc: "25:12-25:13",
          name: "c",
        },
        consequent: {
          type: "Block",
          loc: "25:15-27:2",
          body: [
            {
              type: "ExpressionStatement",
              loc: "26:3-26:5",
              kind: {
                type: "Identifier",
                loc: "26:3-26:4",
                name: "d",
              },
            },
          ],
        },
        alternate: {
          type: "Block",
          loc: "27:8-29:2",
          body: [
            {
              type: "ExpressionStatement",
              loc: "28:3-28:5",
              kind: {
                type: "Identifier",
                loc: "28:3-28:4",
                name: "e",
              },
            },
          ],
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}