{
  type: "Program",
  loc: "1:1-7:21",
  body: [
    {
      type: "WhileStatement",
      loc: "1:1-1:13",
      test: {
        type: "Identifier",
        loc: "1:8-1:9",
        name: "a",
      },
      body: {
        type: "ExpressionStatement",
        loc: "1:11-1:13",
        kind: {
          type: "Identifier",
          loc: "1:11-1:12",
          name: "b",
        },
      },
    },
    {
      type: "WhileStatement",
      loc: "3:1-3:17",
      test: {
        type: "Identifier",
        loc: "3:8-3:9",
        name: "a",
      },
      body: {
        type: "Block",
        loc: "3:11-3:17",
        body: [
          {
            type: "ExpressionStatement",
            loc: "3:13-3:15",
            kind: {
              type: "Identifier",
              loc: "3:13-3:14",
              name: "b",
            },
          },
        ],
      },
    },
    {
      type: "DoWhileStatement",
      loc: "5:1-5:17",
      test: {
        type: "Identifier",
        loc: "5:14-5:15",
        name: "b",
      },
      body: {
        type: "ExpressionStatement",
        loc: "5:4-5:6",
        kind: {
          type: "Identifier",
          loc: "5:4-5:5",
          name: "a",
        },
      },
    },
    {
      type: "DoWhileStatement",
      loc: "7:1-7:21",
      test: {
        type: "Identifier",
        loc: "7:18-7:19",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "7:4-7:10",
        body: [
          {
            type: "ExpressionStatement",
            loc: "7:6-7:8",
            kind: {
              type: "Identifier",
              loc: "7:6-7:7",
              name: "a",
            },
          },
        ],
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}