{
  type: "Program",
  loc: "1:0-13:1",
  body: [
    {
      type: "ThrowStatement",
      loc: "1:0-1:8",
      argument: {
        type: "Identifier",
        loc: "1:6-1:7",
        name: "a",
      },
    },
    {
      type: "TryStatement",
      loc: "3:0-7:1",
      block: {
        type: "Block",
        loc: "3:4-5:1",
        body: [
          {
            type: "ExpressionStatement",
            loc: "4:2-4:4",
            kind: {
              type: "Identifier",
              loc: "4:2-4:3",
              name: "a",
            },
          },
        ],
      },
      handler: {
        type: "CatchClause",
        loc: "5:2-7:1",
        param: null,
        body: {
          type: "Block",
          loc: "5:8-7:1",
          body: [
            {
              type: "ExpressionStatement",
              loc: "6:2-6:4",
              kind: {
                type: "Identifier",
                loc: "6:2-6:3",
                name: "b",
              },
            },
          ],
        },
      },
      finalizer: null,
    },
    {
      type: "TryStatement",
      loc: "9:0-13:1",
      block: {
        type: "Block",
        loc: "9:4-11:1",
        body: [
          {
            type: "ExpressionStatement",
            loc: "10:2-10:4",
            kind: {
              type: "Identifier",
              loc: "10:2-10:3",
              name: "a",
            },
          },
        ],
      },
      handler: {
        type: "CatchClause",
        loc: "11:2-13:1",
        param: {
          type: "Identifier",
          loc: "11:9-11:10",
          name: "b",
        },
        body: {
          type: "Block",
          loc: "11:12-13:1",
          body: [
            {
              type: "ExpressionStatement",
              loc: "12:2-12:4",
              kind: {
                type: "Identifier",
                loc: "12:2-12:3",
                name: "c",
              },
            },
          ],
        },
      },
      finalizer: null,
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}