{
  type: "Program",
  loc: "1:0-27:1",
  body: [
    {
      type: "ThrowStatement",
      loc: "1:0-1:8",
      argument: {
        type: "Identifier",
        loc: "1:6-1:7",
        name: "a",
      },
    },
    {
      type: "TryStatement",
      loc: "3:0-7:1",
      block: {
        type: "Block",
        loc: "3:4-5:1",
        body: [
          {
            type: "ExpressionStatement",
            loc: "4:2-4:4",
            kind: {
              type: "Identifier",
              loc: "4:2-4:3",
              name: "a",
            },
          },
        ],
      },
      handler: {
        type: "CatchClause",
        loc: "5:2-7:1",
        param: null,
        body: {
          type: "Block",
          loc: "5:8-7:1",
          body: [
            {
              type: "ExpressionStatement",
              loc: "6:2-6:4",
              kind: {
                type: "Identifier",
                loc: "6:2-6:3",
                name: "b",
              },
            },
          ],
        },
      },
      finalizer: null,
    },
    {
      type: "TryStatement",
      loc: "9:0-13:1",
      block: {
        type: "Block",
        loc: "9:4-11:1",
        body: [
          {
            type: "ExpressionStatement",
            loc: "10:2-10:4",
            kind: {
              type: "Identifier",
              loc: "10:2-10:3",
              name: "a",
            },
          },
        ],
      },
      handler: {
        type: "CatchClause",
        loc: "11:2-13:1",
        param: {
          type: "Identifier",
          loc: "11:9-11:10",
          name: "b",
        },
        body: {
          type: "Block",
          loc: "11:12-13:1",
          body: [
            {
              type: "ExpressionStatement",
              loc: "12:2-12:4",
              kind: {
                type: "Identifier",
                loc: "12:2-12:3",
                name: "c",
              },
            },
          ],
        },
      },
      finalizer: null,
    },
    {
      type: "TryStatement",
      loc: "15:0-19:1",
      block: {
        type: "Block",
        loc: "15:4-17:1",
        body: [
          {
            type: "ExpressionStatement",
            loc: "16:2-16:4",
            kind: {
              type: "Identifier",
              loc: "16:2-16:3",
              name: "a",
            },
          },
        ],
      },
      handler: null,
      finalizer: {
        type: "Block",
        loc: "17:10-19:1",
        body: [
          {
            type: "ExpressionStatement",
            loc: "18:2-18:4",
            kind: {
              type: "Identifier",
              loc: "18:2-18:3",
              name: "b",
            },
          },
        ],
      },
    },
    {
      type: "TryStatement",
      loc: "21:0-27:1",
      block: {
        type: "Block",
        loc: "21:4-23:1",
        body: [
          {
            type: "ExpressionStatement",
            loc: "22:2-22:4",
            kind: {
              type: "Identifier",
              loc: "22:2-22:3",
              name: "a",
            },
          },
        ],
      },
      handler: {
        type: "CatchClause",
        loc: "23:2-25:1",
        param: null,
        body: {
          type: "Block",
          loc: "23:8-25:1",
          body: [
            {
              type: "ExpressionStatement",
              loc: "24:2-24:4",
              kind: {
                type: "Identifier",
                loc: "24:2-24:3",
                name: "b",
              },
            },
          ],
        },
      },
      finalizer: {
        type: "Block",
        loc: "25:10-27:1",
        body: [
          {
            type: "ExpressionStatement",
            loc: "26:2-26:4",
            kind: {
              type: "Identifier",
              loc: "26:2-26:3",
              name: "c",
            },
          },
        ],
      },
    },
  ],
}