[CompiledRegExp: /a(x)?b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: Branch(6, 4)
     4: CodePointLiteral(b)
     5: Accept
     6: MarkCapturePoint(2)
     8: CodePointLiteral(x)
     9: MarkCapturePoint(3)
    11: Jump(4)
}

[CompiledRegExp: /a(x)+b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: MarkCapturePoint(2)
     3: CodePointLiteral(x)
     4: MarkCapturePoint(3)
     6: Branch(9, 19)
     9: ClearCapture(1)
    11: MarkCapturePoint(2)
    13: CodePointLiteral(x)
    14: MarkCapturePoint(3)
    16: Branch(9, 19)
    19: CodePointLiteral(b)
    20: Accept
}

[CompiledRegExp: /a(x)*b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: Branch(4, 14)
     4: ClearCapture(1)
     6: MarkCapturePoint(2)
     8: CodePointLiteral(x)
     9: MarkCapturePoint(3)
    11: Branch(4, 14)
    14: CodePointLiteral(b)
    15: Accept
}

[CompiledRegExp: /a(x){3,4}b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: MarkCapturePoint(2)
     3: CodePointLiteral(x)
     4: MarkCapturePoint(3)
     6: ClearCapture(1)
     8: MarkCapturePoint(2)
    10: CodePointLiteral(x)
    11: MarkCapturePoint(3)
    13: ClearCapture(1)
    15: MarkCapturePoint(2)
    17: CodePointLiteral(x)
    18: MarkCapturePoint(3)
    20: Branch(25, 23)
    23: CodePointLiteral(b)
    24: Accept
    25: ClearCapture(1)
    27: MarkCapturePoint(2)
    29: CodePointLiteral(x)
    30: MarkCapturePoint(3)
    32: Jump(23)
}

[CompiledRegExp: /a(x){100,101}b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: Loop(0, 100, 14)
     5: ClearCapture(1)
     7: MarkCapturePoint(2)
     9: CodePointLiteral(x)
    10: MarkCapturePoint(3)
    12: Jump(1)
    14: Branch(19, 17)
    17: CodePointLiteral(b)
    18: Accept
    19: ClearCapture(1)
    21: MarkCapturePoint(2)
    23: CodePointLiteral(x)
    24: MarkCapturePoint(3)
    26: Jump(17)
}

[CompiledRegExp: /a(x){1,4}b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: MarkCapturePoint(2)
     3: CodePointLiteral(x)
     4: MarkCapturePoint(3)
     6: Branch(11, 9)
     9: CodePointLiteral(b)
    10: Accept
    11: ClearCapture(1)
    13: MarkCapturePoint(2)
    15: CodePointLiteral(x)
    16: MarkCapturePoint(3)
    18: Branch(21, 9)
    21: ClearCapture(1)
    23: MarkCapturePoint(2)
    25: CodePointLiteral(x)
    26: MarkCapturePoint(3)
    28: Branch(31, 9)
    31: ClearCapture(1)
    33: MarkCapturePoint(2)
    35: CodePointLiteral(x)
    36: MarkCapturePoint(3)
    38: Jump(9)
}

[CompiledRegExp: /a(x){1,100}b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: MarkCapturePoint(2)
     3: CodePointLiteral(x)
     4: MarkCapturePoint(3)
     6: Branch(11, 9)
     9: CodePointLiteral(b)
    10: Accept
    11: Loop(0, 99, 9)
    15: ClearCapture(1)
    17: MarkCapturePoint(2)
    19: CodePointLiteral(x)
    20: MarkCapturePoint(3)
    22: Branch(11, 9)
}

[CompiledRegExp: /a(x){2,}b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: MarkCapturePoint(2)
     3: CodePointLiteral(x)
     4: MarkCapturePoint(3)
     6: ClearCapture(1)
     8: MarkCapturePoint(2)
    10: CodePointLiteral(x)
    11: MarkCapturePoint(3)
    13: Branch(16, 26)
    16: ClearCapture(1)
    18: MarkCapturePoint(2)
    20: CodePointLiteral(x)
    21: MarkCapturePoint(3)
    23: Branch(16, 26)
    26: CodePointLiteral(b)
    27: Accept
}

[CompiledRegExp: /a(x){3}b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: MarkCapturePoint(2)
     3: CodePointLiteral(x)
     4: MarkCapturePoint(3)
     6: ClearCapture(1)
     8: MarkCapturePoint(2)
    10: CodePointLiteral(x)
    11: MarkCapturePoint(3)
    13: ClearCapture(1)
    15: MarkCapturePoint(2)
    17: CodePointLiteral(x)
    18: MarkCapturePoint(3)
    20: CodePointLiteral(b)
    21: Accept
}

[CompiledRegExp: /a(x){100}b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: Loop(0, 100, 14)
     5: ClearCapture(1)
     7: MarkCapturePoint(2)
     9: CodePointLiteral(x)
    10: MarkCapturePoint(3)
    12: Jump(1)
    14: CodePointLiteral(b)
    15: Accept
}
