[CompiledRegExp: /((a)(b)){3}/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(2)
     2: MarkCapturePoint(4)
     4: CodePointLiteral(a)
     5: MarkCapturePoint(5)
     7: MarkCapturePoint(6)
     9: CodePointLiteral(b)
    10: MarkCapturePoint(7)
    12: MarkCapturePoint(3)
    14: ClearCapture(1)
    16: ClearCapture(2)
    18: ClearCapture(3)
    20: MarkCapturePoint(2)
    22: MarkCapturePoint(4)
    24: CodePointLiteral(a)
    25: MarkCapturePoint(5)
    27: MarkCapturePoint(6)
    29: CodePointLiteral(b)
    30: MarkCapturePoint(7)
    32: MarkCapturePoint(3)
    34: ClearCapture(1)
    36: ClearCapture(2)
    38: ClearCapture(3)
    40: MarkCapturePoint(2)
    42: MarkCapturePoint(4)
    44: CodePointLiteral(a)
    45: MarkCapturePoint(5)
    47: MarkCapturePoint(6)
    49: CodePointLiteral(b)
    50: MarkCapturePoint(7)
    52: MarkCapturePoint(3)
    54: Accept
}

[CompiledRegExp: /((a)(b)){100}/] {
  Flags: ""
  Match Start: Code Points("a")
     0: Loop(0, 100, 26)
     4: ClearCapture(1)
     6: ClearCapture(2)
     8: ClearCapture(3)
    10: MarkCapturePoint(2)
    12: MarkCapturePoint(4)
    14: CodePointLiteral(a)
    15: MarkCapturePoint(5)
    17: MarkCapturePoint(6)
    19: CodePointLiteral(b)
    20: MarkCapturePoint(7)
    22: MarkCapturePoint(3)
    24: Jump(0)
    26: Accept
}

[CompiledRegExp: /((a)(b)){1,2}/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(2)
     2: MarkCapturePoint(4)
     4: CodePointLiteral(a)
     5: MarkCapturePoint(5)
     7: MarkCapturePoint(6)
     9: CodePointLiteral(b)
    10: MarkCapturePoint(7)
    12: MarkCapturePoint(3)
    14: Branch(18, 17)
    17: Accept
    18: ClearCapture(1)
    20: ClearCapture(2)
    22: ClearCapture(3)
    24: MarkCapturePoint(2)
    26: MarkCapturePoint(4)
    28: CodePointLiteral(a)
    29: MarkCapturePoint(5)
    31: MarkCapturePoint(6)
    33: CodePointLiteral(b)
    34: MarkCapturePoint(7)
    36: MarkCapturePoint(3)
    38: Jump(17)
}

[CompiledRegExp: /((a)(b)){1,100}/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(2)
     2: MarkCapturePoint(4)
     4: CodePointLiteral(a)
     5: MarkCapturePoint(5)
     7: MarkCapturePoint(6)
     9: CodePointLiteral(b)
    10: MarkCapturePoint(7)
    12: MarkCapturePoint(3)
    14: Branch(18, 17)
    17: Accept
    18: Loop(0, 99, 17)
    22: ClearCapture(1)
    24: ClearCapture(2)
    26: ClearCapture(3)
    28: MarkCapturePoint(2)
    30: MarkCapturePoint(4)
    32: CodePointLiteral(a)
    33: MarkCapturePoint(5)
    35: MarkCapturePoint(6)
    37: CodePointLiteral(b)
    38: MarkCapturePoint(7)
    40: MarkCapturePoint(3)
    42: Branch(18, 17)
}

[CompiledRegExp: /((a)(b)){1,}/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(2)
     2: MarkCapturePoint(4)
     4: CodePointLiteral(a)
     5: MarkCapturePoint(5)
     7: MarkCapturePoint(6)
     9: CodePointLiteral(b)
    10: MarkCapturePoint(7)
    12: MarkCapturePoint(3)
    14: Branch(17, 40)
    17: ClearCapture(1)
    19: ClearCapture(2)
    21: ClearCapture(3)
    23: MarkCapturePoint(2)
    25: MarkCapturePoint(4)
    27: CodePointLiteral(a)
    28: MarkCapturePoint(5)
    30: MarkCapturePoint(6)
    32: CodePointLiteral(b)
    33: MarkCapturePoint(7)
    35: MarkCapturePoint(3)
    37: Branch(17, 40)
    40: Accept
}

[CompiledRegExp: /((a)(b)){0,1}/] {
  Flags: ""
  Match Start: Unknown
     0: Branch(4, 3)
     3: Accept
     4: MarkCapturePoint(2)
     6: MarkCapturePoint(4)
     8: CodePointLiteral(a)
     9: MarkCapturePoint(5)
    11: MarkCapturePoint(6)
    13: CodePointLiteral(b)
    14: MarkCapturePoint(7)
    16: MarkCapturePoint(3)
    18: Jump(3)
}

[CompiledRegExp: /((a)(b)){1,1}/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(2)
     2: MarkCapturePoint(4)
     4: CodePointLiteral(a)
     5: MarkCapturePoint(5)
     7: MarkCapturePoint(6)
     9: CodePointLiteral(b)
    10: MarkCapturePoint(7)
    12: MarkCapturePoint(3)
    14: Accept
}

[CompiledRegExp: /((a)(b)){0,0}/] {
  Flags: ""
  Match Start: Unknown
     0: Accept
}
