[CompiledRegExp: /((a)(b)){3}/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: MarkCapturePoint(2)
     4: MarkCapturePoint(4)
     6: Literal(a)
     7: MarkCapturePoint(5)
     9: MarkCapturePoint(6)
    11: Literal(b)
    12: MarkCapturePoint(7)
    14: MarkCapturePoint(3)
    16: ClearCapture(1)
    18: ClearCapture(2)
    20: ClearCapture(3)
    22: MarkCapturePoint(2)
    24: MarkCapturePoint(4)
    26: Literal(a)
    27: MarkCapturePoint(5)
    29: MarkCapturePoint(6)
    31: Literal(b)
    32: MarkCapturePoint(7)
    34: MarkCapturePoint(3)
    36: ClearCapture(1)
    38: ClearCapture(2)
    40: ClearCapture(3)
    42: MarkCapturePoint(2)
    44: MarkCapturePoint(4)
    46: Literal(a)
    47: MarkCapturePoint(5)
    49: MarkCapturePoint(6)
    51: Literal(b)
    52: MarkCapturePoint(7)
    54: MarkCapturePoint(3)
    56: MarkCapturePoint(1)
    58: Accept
}

[CompiledRegExp: /((a)(b)){100}/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: Loop(0, 100, 28)
     6: ClearCapture(1)
     8: ClearCapture(2)
    10: ClearCapture(3)
    12: MarkCapturePoint(2)
    14: MarkCapturePoint(4)
    16: Literal(a)
    17: MarkCapturePoint(5)
    19: MarkCapturePoint(6)
    21: Literal(b)
    22: MarkCapturePoint(7)
    24: MarkCapturePoint(3)
    26: Jump(2)
    28: MarkCapturePoint(1)
    30: Accept
}

[CompiledRegExp: /((a)(b)){1,2}/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: MarkCapturePoint(2)
     4: MarkCapturePoint(4)
     6: Literal(a)
     7: MarkCapturePoint(5)
     9: MarkCapturePoint(6)
    11: Literal(b)
    12: MarkCapturePoint(7)
    14: MarkCapturePoint(3)
    16: Branch(22, 19)
    19: MarkCapturePoint(1)
    21: Accept
    22: ClearCapture(1)
    24: ClearCapture(2)
    26: ClearCapture(3)
    28: MarkCapturePoint(2)
    30: MarkCapturePoint(4)
    32: Literal(a)
    33: MarkCapturePoint(5)
    35: MarkCapturePoint(6)
    37: Literal(b)
    38: MarkCapturePoint(7)
    40: MarkCapturePoint(3)
    42: Jump(19)
}

[CompiledRegExp: /((a)(b)){1,100}/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: MarkCapturePoint(2)
     4: MarkCapturePoint(4)
     6: Literal(a)
     7: MarkCapturePoint(5)
     9: MarkCapturePoint(6)
    11: Literal(b)
    12: MarkCapturePoint(7)
    14: MarkCapturePoint(3)
    16: Branch(22, 19)
    19: MarkCapturePoint(1)
    21: Accept
    22: Loop(0, 99, 19)
    26: ClearCapture(1)
    28: ClearCapture(2)
    30: ClearCapture(3)
    32: MarkCapturePoint(2)
    34: MarkCapturePoint(4)
    36: Literal(a)
    37: MarkCapturePoint(5)
    39: MarkCapturePoint(6)
    41: Literal(b)
    42: MarkCapturePoint(7)
    44: MarkCapturePoint(3)
    46: Branch(22, 19)
}

[CompiledRegExp: /((a)(b)){1,}/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: MarkCapturePoint(2)
     4: MarkCapturePoint(4)
     6: Literal(a)
     7: MarkCapturePoint(5)
     9: MarkCapturePoint(6)
    11: Literal(b)
    12: MarkCapturePoint(7)
    14: MarkCapturePoint(3)
    16: Branch(19, 42)
    19: ClearCapture(1)
    21: ClearCapture(2)
    23: ClearCapture(3)
    25: MarkCapturePoint(2)
    27: MarkCapturePoint(4)
    29: Literal(a)
    30: MarkCapturePoint(5)
    32: MarkCapturePoint(6)
    34: Literal(b)
    35: MarkCapturePoint(7)
    37: MarkCapturePoint(3)
    39: Branch(19, 42)
    42: MarkCapturePoint(1)
    44: Accept
}

[CompiledRegExp: /((a)(b)){0,1}/] {
  Flags: ""
  Match Start: Unknown
     0: MarkCapturePoint(0)
     2: Branch(8, 5)
     5: MarkCapturePoint(1)
     7: Accept
     8: MarkCapturePoint(2)
    10: MarkCapturePoint(4)
    12: Literal(a)
    13: MarkCapturePoint(5)
    15: MarkCapturePoint(6)
    17: Literal(b)
    18: MarkCapturePoint(7)
    20: MarkCapturePoint(3)
    22: Jump(5)
}

[CompiledRegExp: /((a)(b)){1,1}/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: MarkCapturePoint(2)
     4: MarkCapturePoint(4)
     6: Literal(a)
     7: MarkCapturePoint(5)
     9: MarkCapturePoint(6)
    11: Literal(b)
    12: MarkCapturePoint(7)
    14: MarkCapturePoint(3)
    16: MarkCapturePoint(1)
    18: Accept
}

[CompiledRegExp: /((a)(b)){0,0}/] {
  Flags: ""
  Match Start: Unknown
     0: MarkCapturePoint(0)
     2: MarkCapturePoint(1)
     4: Accept
}
