[CompiledRegExpObject: /(x)?/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Progress(0)
    11: Branch(20, 14)
    14: ClearCaptureIfNoProgress(1, 0)
    17: MarkCapturePoint(1)
    19: Accept
    20: MarkCapturePoint(2)
    22: Literal(x)
    23: MarkCapturePoint(3)
    25: Jump(14)
}

[CompiledRegExpObject: /((x)(y)(z))?/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Progress(0)
    11: Branch(29, 14)
    14: ClearCaptureIfNoProgress(1, 0)
    17: ClearCaptureIfNoProgress(2, 0)
    20: ClearCaptureIfNoProgress(3, 0)
    23: ClearCaptureIfNoProgress(4, 0)
    26: MarkCapturePoint(1)
    28: Accept
    29: MarkCapturePoint(2)
    31: MarkCapturePoint(4)
    33: Literal(x)
    34: MarkCapturePoint(5)
    36: MarkCapturePoint(6)
    38: Literal(y)
    39: MarkCapturePoint(7)
    41: MarkCapturePoint(8)
    43: Literal(z)
    44: MarkCapturePoint(9)
    46: MarkCapturePoint(3)
    48: Jump(14)
}

[CompiledRegExpObject: /x?/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Branch(15, 12)
    12: MarkCapturePoint(1)
    14: Accept
    15: Literal(x)
    16: Jump(12)
}
