[CompiledRegExp: /ax*b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: GreedyLoop("x")
     3: CodePointLiteral(b)
     4: Accept
}

[CompiledRegExp: /ax*b/] {
  Flags: "i"
  Match Start: Code Points("A", "a")
     0: CodePointSet("A", "a")
     2: GreedyLoop("X", "x")
     4: CodePointSet("B", "b")
     6: Accept
}

[CompiledRegExp: /a[a-z]*b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: GreedyLoop("a"-"z")
     3: CodePointLiteral(b)
     4: Accept
}

[CompiledRegExp: /a[^a-z]*b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: GreedyLoop(inverted, "a"-"z")
     3: CodePointLiteral(b)
     4: Accept
}

[CompiledRegExp: /a[^a-z]*b/] {
  Flags: "v"
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: GreedyLoop(inverted, "a"-"z")
     3: CodePointLiteral(b)
     4: Accept
}

[CompiledRegExp: /a.*b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: GreedyLoop(inverted, "\n", "\r", "\u{2028}"-"\u{2029}")
     3: CodePointLiteral(b)
     4: Accept
}

[CompiledRegExp: /a.*b/] {
  Flags: "s"
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: GreedyLoop(inverted, )
     3: CodePointLiteral(b)
     4: Accept
}

[CompiledRegExp: /a(?:x)*b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: GreedyLoop("x")
     3: CodePointLiteral(b)
     4: Accept
}

[CompiledRegExp: /a(?:(?:(?:x)))*b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: GreedyLoop("x")
     3: CodePointLiteral(b)
     4: Accept
}

[CompiledRegExp: /ax+/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: CodePointLiteral(x)
     2: GreedyLoop("x")
     4: Accept
}

[CompiledRegExp: /ax{100,}b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: Loop(0, 100, 8)
     5: CodePointLiteral(x)
     6: Jump(1)
     8: GreedyLoop("x")
    10: CodePointLiteral(b)
    11: Accept
}

[CompiledRegExp: /ax*?b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: Branch(8, 4)
     4: CodePointLiteral(x)
     5: Branch(8, 4)
     8: CodePointLiteral(b)
     9: Accept
}

[CompiledRegExp: /a(?:xy)*b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: Branch(4, 9)
     4: OneByteStringLiteral("xy")
     6: Branch(4, 9)
     9: CodePointLiteral(b)
    10: Accept
}

[CompiledRegExp: /a(x)*b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: Branch(4, 14)
     4: ClearCapture(1)
     6: MarkCapturePoint(2)
     8: CodePointLiteral(x)
     9: MarkCapturePoint(3)
    11: Branch(4, 14)
    14: CodePointLiteral(b)
    15: Accept
}

[CompiledRegExp: /a(?i:x)*b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: Branch(4, 9)
     4: CodePointSet("X", "x")
     6: Branch(4, 9)
     9: CodePointLiteral(b)
    10: Accept
}
