[CompiledRegExp: /ax?b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: Branch(17, 13)
    13: Literal(b)
    14: MarkCapturePoint(1)
    16: Accept
    17: Literal(x)
    18: Jump(13)
}

[CompiledRegExp: /ax+b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: Literal(x)
    11: Branch(14, 18)
    14: Literal(x)
    15: Branch(14, 18)
    18: Literal(b)
    19: MarkCapturePoint(1)
    21: Accept
}

[CompiledRegExp: /ax*b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: Branch(13, 17)
    13: Literal(x)
    14: Branch(13, 17)
    17: Literal(b)
    18: MarkCapturePoint(1)
    20: Accept
}

[CompiledRegExp: /ax{3,4}b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: Literal(x)
    11: Literal(x)
    12: Literal(x)
    13: Branch(20, 16)
    16: Literal(b)
    17: MarkCapturePoint(1)
    19: Accept
    20: Literal(x)
    21: Jump(16)
}

[CompiledRegExp: /ax{100,101}b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: Loop(0, 100, 17)
    14: Literal(x)
    15: Jump(10)
    17: Branch(24, 20)
    20: Literal(b)
    21: MarkCapturePoint(1)
    23: Accept
    24: Literal(x)
    25: Jump(20)
}

[CompiledRegExp: /ax{1,4}b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: Literal(x)
    11: Branch(18, 14)
    14: Literal(b)
    15: MarkCapturePoint(1)
    17: Accept
    18: Literal(x)
    19: Branch(22, 14)
    22: Literal(x)
    23: Branch(26, 14)
    26: Literal(x)
    27: Jump(14)
}

[CompiledRegExp: /ax{1,100}b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: Literal(x)
    11: Branch(18, 14)
    14: Literal(b)
    15: MarkCapturePoint(1)
    17: Accept
    18: Loop(0, 99, 14)
    22: Literal(x)
    23: Branch(18, 14)
}

[CompiledRegExp: /ax{2,}b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: Literal(x)
    11: Literal(x)
    12: Branch(15, 19)
    15: Literal(x)
    16: Branch(15, 19)
    19: Literal(b)
    20: MarkCapturePoint(1)
    22: Accept
}

[CompiledRegExp: /ax{3}b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: Literal(x)
    11: Literal(x)
    12: Literal(x)
    13: Literal(b)
    14: MarkCapturePoint(1)
    16: Accept
}

[CompiledRegExp: /ax{100}b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: Loop(0, 100, 17)
    14: Literal(x)
    15: Jump(10)
    17: Literal(b)
    18: MarkCapturePoint(1)
    20: Accept
}

[CompiledRegExp: /ax{0,1000000000000}b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: Branch(17, 13)
    13: Literal(b)
    14: MarkCapturePoint(1)
    16: Accept
    17: Loop(0, 4294967295, 13)
    21: Literal(x)
    22: Branch(17, 13)
}

[CompiledRegExp: /a(?:x|){0,1000000000000}b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: SetProgress(0)
    12: Branch(19, 15)
    15: Literal(b)
    16: MarkCapturePoint(1)
    18: Accept
    19: Loop(0, 4294967295, 15)
    23: Branch(31, 34)
    26: Progress(0)
    28: Branch(19, 15)
    31: Literal(x)
    32: Jump(26)
    34: Jump(26)
}

[CompiledRegExp: /ax{1000000000000,1000000000001}b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: Fail
    11: Branch(18, 14)
    14: Literal(b)
    15: MarkCapturePoint(1)
    17: Accept
    18: Literal(x)
    19: Jump(14)
}

[CompiledRegExp: /a(?:x|){1000000000000,1000000000001}b/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: Loop(0, 4294967295, 17)
    14: Branch(24, 27)
    17: SetProgress(0)
    19: Branch(33, 29)
    22: Jump(10)
    24: Literal(x)
    25: Jump(22)
    27: Jump(22)
    29: Literal(b)
    30: MarkCapturePoint(1)
    32: Accept
    33: Branch(40, 43)
    36: Progress(0)
    38: Jump(29)
    40: Literal(x)
    41: Jump(36)
    43: Jump(36)
}
