{
  type: "Program",
  loc: "1:0-21:25",
  body: [
    {
      type: "FunctionDeclaration",
      loc: "1:0-1:21",
      id: {
        type: "Identifier",
        loc: "1:9-1:12",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "1:15-1:21",
        body: [
          {
            type: "ExpressionStatement",
            loc: "1:17-1:19",
            kind: {
              type: "Identifier",
              loc: "1:17-1:18",
              name: "a",
            },
          },
        ],
      },
      async: false,
      generator: false,
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:24",
      kind: {
        type: "FunctionExpression",
        loc: "3:1-3:22",
        id: {
          type: "Identifier",
          loc: "3:10-3:13",
          name: "foo",
        },
        params: [],
        body: {
          type: "Block",
          loc: "3:16-3:22",
          body: [
            {
              type: "ExpressionStatement",
              loc: "3:18-3:20",
              kind: {
                type: "Identifier",
                loc: "3:18-3:19",
                name: "a",
              },
            },
          ],
        },
        async: false,
        generator: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:17",
      kind: {
        type: "FunctionExpression",
        loc: "5:1-5:15",
        id: null,
        params: [],
        body: {
          type: "Block",
          loc: "5:13-5:15",
          body: [],
        },
        async: false,
        generator: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:0-7:22",
      kind: {
        type: "FunctionExpression",
        loc: "7:1-7:20",
        id: null,
        params: [
          {
            type: "Identifier",
            loc: "7:11-7:16",
            name: "param",
          },
        ],
        body: {
          type: "Block",
          loc: "7:18-7:20",
          body: [],
        },
        async: false,
        generator: false,
      },
    },
    {
      type: "FunctionDeclaration",
      loc: "9:0-9:23",
      id: {
        type: "Identifier",
        loc: "9:15-9:18",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "9:21-9:23",
        body: [],
      },
      async: true,
      generator: false,
    },
    {
      type: "FunctionDeclaration",
      loc: "11:0-11:18",
      id: {
        type: "Identifier",
        loc: "11:10-11:13",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "11:16-11:18",
        body: [],
      },
      async: false,
      generator: true,
    },
    {
      type: "FunctionDeclaration",
      loc: "13:0-13:24",
      id: {
        type: "Identifier",
        loc: "13:16-13:19",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "13:22-13:24",
        body: [],
      },
      async: true,
      generator: true,
    },
    {
      type: "ExpressionStatement",
      loc: "15:0-15:27",
      kind: {
        type: "FunctionExpression",
        loc: "15:1-15:25",
        id: {
          type: "Identifier",
          loc: "15:17-15:20",
          name: "foo",
        },
        params: [],
        body: {
          type: "Block",
          loc: "15:23-15:25",
          body: [],
        },
        async: true,
        generator: true,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:0-17:24",
      kind: {
        type: "FunctionExpression",
        loc: "17:1-17:22",
        id: null,
        params: [],
        body: {
          type: "Block",
          loc: "17:20-17:22",
          body: [],
        },
        async: true,
        generator: true,
      },
    },
    {
      type: "FunctionDeclaration",
      loc: "19:0-19:24",
      id: {
        type: "Identifier",
        loc: "19:9-19:12",
        name: "foo",
      },
      params: [
        {
          type: "Identifier",
          loc: "19:13-19:14",
          name: "a",
        },
        {
          type: "Identifier",
          loc: "19:16-19:17",
          name: "b",
        },
        {
          type: "Identifier",
          loc: "19:19-19:20",
          name: "c",
        },
      ],
      body: {
        type: "Block",
        loc: "19:22-19:24",
        body: [],
      },
      async: false,
      generator: false,
    },
    {
      type: "FunctionDeclaration",
      loc: "21:0-21:25",
      id: {
        type: "Identifier",
        loc: "21:9-21:12",
        name: "foo",
      },
      params: [
        {
          type: "Identifier",
          loc: "21:13-21:14",
          name: "a",
        },
        {
          type: "Identifier",
          loc: "21:16-21:17",
          name: "b",
        },
        {
          type: "Identifier",
          loc: "21:19-21:20",
          name: "c",
        },
      ],
      body: {
        type: "Block",
        loc: "21:23-21:25",
        body: [],
      },
      async: false,
      generator: false,
    },
  ],
}