{
  type: "Program",
  loc: "1:0-14:16",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:4",
      kind: {
        type: "Identifier",
        loc: "1:0-1:3",
        name: "abc",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:8",
      kind: {
        type: "Identifier",
        loc: "3:0-3:7",
        name: "ab",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:14",
      kind: {
        type: "Identifier",
        loc: "5:0-5:13",
        name: "abc",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "8:0-8:9",
      kind: {
        type: "Identifier",
        loc: "8:0-8:8",
        name: "aÿF",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "10:0-10:24",
      kind: {
        type: "Identifier",
        loc: "10:0-10:23",
        name: "abcჿ",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "12:0-12:7",
      kind: {
        type: "Identifier",
        loc: "12:0-12:6",
        name: "b",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "14:0-14:16",
      kind: {
        type: "Identifier",
        loc: "14:0-14:15",
        name: "bcd",
      },
    },
  ],
  has_use_strict_directive: false,
}