{
  type: "Program",
  loc: "1:0-26:17",
  body: [
    {
      type: "VariableDeclaration",
      loc: "2:0-2:10",
      kind: "let",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "2:4-2:9",
          id: {
            type: "Identifier",
            loc: "2:4-2:5",
            name: "a",
          },
          init: {
            type: "Literal",
            loc: "2:8-2:9",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "3:0-3:12",
      kind: "let",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "3:4-3:11",
          id: {
            type: "ArrayPattern",
            loc: "3:4-3:7",
            elements: [
              {
                type: "Identifier",
                loc: "3:5-3:6",
                name: "a",
              },
            ],
          },
          init: {
            type: "Literal",
            loc: "3:10-3:11",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "4:0-4:12",
      kind: "let",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "4:4-4:11",
          id: {
            type: "ObjectPattern",
            loc: "4:4-4:7",
            properties: [
              {
                type: "Property",
                loc: "4:5-4:6",
                key: null,
                value: {
                  type: "Identifier",
                  loc: "4:5-4:6",
                  name: "a",
                },
                computed: false,
              },
            ],
          },
          init: {
            type: "Literal",
            loc: "4:10-4:11",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "5:0-5:15",
      kind: "let",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "5:4-5:14",
          id: {
            type: "Identifier",
            loc: "5:4-5:10",
            name: "static",
          },
          init: {
            type: "Literal",
            loc: "5:13-5:14",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "6:0-6:14",
      kind: "let",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "6:4-6:13",
          id: {
            type: "Identifier",
            loc: "6:4-6:9",
            name: "async",
          },
          init: {
            type: "Literal",
            loc: "6:12-6:13",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "7:0-7:14",
      kind: "let",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "7:4-7:13",
          id: {
            type: "Identifier",
            loc: "7:4-7:9",
            name: "await",
          },
          init: {
            type: "Literal",
            loc: "7:12-7:13",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "8:0-8:14",
      kind: "let",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "8:4-8:13",
          id: {
            type: "Identifier",
            loc: "8:4-8:9",
            name: "yield",
          },
          init: {
            type: "Literal",
            loc: "8:12-8:13",
            value: 1,
          },
        },
      ],
    },
    {
      type: "ExpressionStatement",
      loc: "11:0-11:4",
      kind: {
        type: "Identifier",
        loc: "11:0-11:3",
        name: "let",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "12:0-12:8",
      kind: {
        type: "BinaryExpression",
        loc: "12:0-12:7",
        operator: "+",
        left: {
          type: "Identifier",
          loc: "12:0-12:3",
          name: "let",
        },
        right: {
          type: "Literal",
          loc: "12:6-12:7",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:0-13:7",
      kind: {
        type: "CallExpression",
        loc: "13:0-13:6",
        callee: {
          type: "Identifier",
          loc: "13:0-13:3",
          name: "let",
        },
        arguments: [
          {
            type: "Literal",
            loc: "13:4-13:5",
            value: 1,
          },
        ],
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "16:0-16:3",
      kind: {
        type: "Identifier",
        loc: "16:0-16:3",
        name: "let",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:0-17:2",
      kind: {
        type: "Literal",
        loc: "17:0-17:1",
        value: 1,
      },
    },
    {
      type: "ForStatement",
      loc: "20:0-20:20",
      init: {
        type: "VariableDeclaration",
        loc: "20:5-20:14",
        kind: "let",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "20:9-20:14",
            id: {
              type: "Identifier",
              loc: "20:9-20:10",
              name: "a",
            },
            init: {
              type: "Literal",
              loc: "20:13-20:14",
              value: 1,
            },
          },
        ],
      },
      test: null,
      update: null,
      body: {
        type: "Block",
        loc: "20:18-20:20",
        body: [],
      },
    },
    {
      type: "ForInStatement",
      loc: "21:0-21:19",
      left: {
        type: "VariableDeclaration",
        loc: "21:5-21:10",
        kind: "let",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "21:9-21:10",
            id: {
              type: "Identifier",
              loc: "21:9-21:10",
              name: "a",
            },
            init: null,
          },
        ],
      },
      right: {
        type: "Identifier",
        loc: "21:14-21:15",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "21:17-21:19",
        body: [],
      },
    },
    {
      type: "ForStatement",
      loc: "24:0-24:14",
      init: {
        type: "Identifier",
        loc: "24:5-24:8",
        name: "let",
      },
      test: null,
      update: null,
      body: {
        type: "Block",
        loc: "24:12-24:14",
        body: [],
      },
    },
    {
      type: "ForStatement",
      loc: "25:0-25:18",
      init: {
        type: "BinaryExpression",
        loc: "25:5-25:12",
        operator: "+",
        left: {
          type: "Identifier",
          loc: "25:5-25:8",
          name: "let",
        },
        right: {
          type: "Literal",
          loc: "25:11-25:12",
          value: 1,
        },
      },
      test: null,
      update: null,
      body: {
        type: "Block",
        loc: "25:16-25:18",
        body: [],
      },
    },
    {
      type: "ForInStatement",
      loc: "26:0-26:17",
      left: {
        type: "Identifier",
        loc: "26:5-26:8",
        name: "let",
      },
      right: {
        type: "Identifier",
        loc: "26:12-26:13",
        name: "b",
      },
      body: {
        type: "Block",
        loc: "26:15-26:17",
        body: [],
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}