{
  type: "Program",
  loc: "1:0-7:11",
  body: [
    {
      type: "VariableDeclaration",
      loc: "1:0-1:9",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "1:4-1:9",
          id: {
            type: "Identifier",
            loc: "1:4-1:5",
            name: "x",
          },
          id: {
            type: "Identifier",
            loc: "1:8-1:9",
            name: "a",
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "3:0-3:23",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "3:4-3:23",
          id: {
            type: "Identifier",
            loc: "3:4-3:5",
            name: "x",
          },
          id: {
            type: "SequenceExpression",
            loc: "3:8-3:23",
            expressions: [
              {
                type: "Identifier",
                loc: "3:8-3:9",
                name: "a",
              },
              {
                type: "AssignmentExpression",
                loc: "3:11-3:16",
                operator: "=",
                left: {
                  type: "Identifier",
                  loc: "3:11-3:12",
                  name: "y",
                },
                right: {
                  type: "Identifier",
                  loc: "3:15-3:16",
                  name: "b",
                },
              },
              {
                type: "AssignmentExpression",
                loc: "3:18-3:23",
                operator: "=",
                left: {
                  type: "Identifier",
                  loc: "3:18-3:19",
                  name: "z",
                },
                right: {
                  type: "Identifier",
                  loc: "3:22-3:23",
                  name: "c",
                },
              },
            ],
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "5:0-5:9",
      kind: "let",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "5:4-5:9",
          id: {
            type: "Identifier",
            loc: "5:4-5:5",
            name: "x",
          },
          id: {
            type: "Identifier",
            loc: "5:8-5:9",
            name: "a",
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "7:0-7:11",
      kind: "const",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "7:6-7:11",
          id: {
            type: "Identifier",
            loc: "7:6-7:7",
            name: "x",
          },
          id: {
            type: "Identifier",
            loc: "7:10-7:11",
            name: "a",
          },
        },
      ],
    },
  ],
}