[BytecodeFunction: <module>] {
  Parameters: 0, Registers: 2
    0: NewClosure r0, c0
    3: LoadUndefined r1
    5: Ret r1
  Constant Table:
    0: [BytecodeFunction: testAccess]
}

[BytecodeFunction: testAccess] {
  Parameters: 0, Registers: 3
     0: LoadFromModule r1, 1, 0
     4: LoadFromModule r2, 2, 0
     8: Add r1, r1, r2, fb0
    13: LoadFromModule r2, 3, 0
    17: Add r1, r1, r2, fb1
    22: LoadFromModule r2, 4, 0
    26: Add r1, r1, r2, fb2
    31: PushLexicalScope c0
    33: LoadEmpty r1
    35: StoreToScope r1, 0, 0
    39: NewClosure r0, c1
    42: LoadImmediate r1, 0
    45: StoreToScope r1, 0, 0
    49: LoadFromModule r1, 1, 1
    53: Call r1, r0, r1, 1
    58: PopScope 
    59: LoadUndefined r1
    61: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: capturing]
}

[BytecodeFunction: capturing] {
  Parameters: 0, Registers: 2
     0: LoadFromModule r0, 1, 1
     4: LoadFromScope r1, 0, 0
     8: CheckTdz r1, c0
    11: Add r0, r0, r1, fb0
    16: LoadUndefined r0
    18: Ret r0
  Constant Table:
    0: [String: c]
}
