{
  type: "Program",
  loc: "1:1-14:2",
  body: [
    {
      type: "SwitchStatement",
      loc: "1:1-1:14",
      discriminant: {
        type: "Identifier",
        loc: "1:9-1:10",
        name: "a",
      },
      cases: [],
    },
    {
      type: "SwitchStatement",
      loc: "3:1-7:2",
      discriminant: {
        type: "Identifier",
        loc: "3:9-3:10",
        name: "a",
      },
      cases: [
        {
          type: "SwitchCase",
          loc: "4:3-4:16",
          test: {
            type: "Literal",
            loc: "4:8-4:9",
            value: 1,
          },
          body: [
            {
              type: "ExpressionStatement",
              loc: "4:11-4:13",
              kind: {
                type: "Identifier",
                loc: "4:11-4:12",
                name: "a",
              },
            },
            {
              type: "ExpressionStatement",
              loc: "4:14-4:16",
              kind: {
                type: "Identifier",
                loc: "4:14-4:15",
                name: "b",
              },
            },
          ],
        },
        {
          type: "SwitchCase",
          loc: "5:3-5:16",
          test: {
            type: "Literal",
            loc: "5:8-5:9",
            value: 2,
          },
          body: [
            {
              type: "ExpressionStatement",
              loc: "5:11-5:13",
              kind: {
                type: "Identifier",
                loc: "5:11-5:12",
                name: "c",
              },
            },
            {
              type: "ExpressionStatement",
              loc: "5:14-5:16",
              kind: {
                type: "Identifier",
                loc: "5:14-5:15",
                name: "d",
              },
            },
          ],
        },
        {
          type: "SwitchCase",
          loc: "6:3-6:17",
          test: null,
          body: [
            {
              type: "ExpressionStatement",
              loc: "6:12-6:14",
              kind: {
                type: "Identifier",
                loc: "6:12-6:13",
                name: "e",
              },
            },
            {
              type: "ExpressionStatement",
              loc: "6:15-6:17",
              kind: {
                type: "Identifier",
                loc: "6:15-6:16",
                name: "f",
              },
            },
          ],
        },
      ],
    },
    {
      type: "SwitchStatement",
      loc: "9:1-14:2",
      discriminant: {
        type: "Identifier",
        loc: "9:9-9:10",
        name: "a",
      },
      cases: [
        {
          type: "SwitchCase",
          loc: "10:3-10:10",
          test: {
            type: "Identifier",
            loc: "10:8-10:9",
            name: "a",
          },
          body: [],
        },
        {
          type: "SwitchCase",
          loc: "11:3-11:10",
          test: {
            type: "Identifier",
            loc: "11:8-11:9",
            name: "b",
          },
          body: [],
        },
        {
          type: "SwitchCase",
          loc: "12:3-12:11",
          test: null,
          body: [],
        },
        {
          type: "SwitchCase",
          loc: "13:3-13:13",
          test: {
            type: "Identifier",
            loc: "13:8-13:9",
            name: "c",
          },
          body: [
            {
              type: "ExpressionStatement",
              loc: "13:11-13:13",
              kind: {
                type: "Identifier",
                loc: "13:11-13:12",
                name: "d",
              },
            },
          ],
        },
      ],
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}