{
  type: "Program",
  loc: "1:1-17:10",
  body: [
    {
      type: "VariableDeclaration",
      loc: "1:1-1:11",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "1:5-1:10",
          id: {
            type: "Identifier",
            loc: "1:5-1:6",
            name: "x",
          },
          init: {
            type: "Identifier",
            loc: "1:9-1:10",
            name: "a",
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "3:1-3:25",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "3:5-3:10",
          id: {
            type: "Identifier",
            loc: "3:5-3:6",
            name: "x",
          },
          init: {
            type: "Identifier",
            loc: "3:9-3:10",
            name: "a",
          },
        },
        {
          type: "VariableDeclarator",
          loc: "3:12-3:17",
          id: {
            type: "Identifier",
            loc: "3:12-3:13",
            name: "y",
          },
          init: {
            type: "Identifier",
            loc: "3:16-3:17",
            name: "b",
          },
        },
        {
          type: "VariableDeclarator",
          loc: "3:19-3:24",
          id: {
            type: "Identifier",
            loc: "3:19-3:20",
            name: "z",
          },
          init: {
            type: "Identifier",
            loc: "3:23-3:24",
            name: "c",
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "5:1-5:12",
      kind: "let",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "5:5-5:11",
          id: {
            type: "Identifier",
            loc: "5:5-5:7",
            name: "x2",
          },
          init: {
            type: "Identifier",
            loc: "5:10-5:11",
            name: "a",
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "7:1-7:14",
      kind: "const",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "7:7-7:13",
          id: {
            type: "Identifier",
            loc: "7:7-7:9",
            name: "x3",
          },
          init: {
            type: "Identifier",
            loc: "7:12-7:13",
            name: "a",
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "9:1-9:7",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "9:5-9:6",
          id: {
            type: "Identifier",
            loc: "9:5-9:6",
            name: "x",
          },
          init: null,
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "11:1-11:13",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "11:5-11:6",
          id: {
            type: "Identifier",
            loc: "11:5-11:6",
            name: "x",
          },
          init: null,
        },
        {
          type: "VariableDeclarator",
          loc: "11:8-11:9",
          id: {
            type: "Identifier",
            loc: "11:8-11:9",
            name: "y",
          },
          init: null,
        },
        {
          type: "VariableDeclarator",
          loc: "11:11-11:12",
          id: {
            type: "Identifier",
            loc: "11:11-11:12",
            name: "z",
          },
          init: null,
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "13:1-13:21",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "13:5-13:10",
          id: {
            type: "Identifier",
            loc: "13:5-13:6",
            name: "x",
          },
          init: {
            type: "Literal",
            loc: "13:9-13:10",
            value: 1,
          },
        },
        {
          type: "VariableDeclarator",
          loc: "13:12-13:13",
          id: {
            type: "Identifier",
            loc: "13:12-13:13",
            name: "y",
          },
          init: null,
        },
        {
          type: "VariableDeclarator",
          loc: "13:15-13:20",
          id: {
            type: "Identifier",
            loc: "13:15-13:16",
            name: "z",
          },
          init: {
            type: "Literal",
            loc: "13:19-13:20",
            value: 3,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "15:1-15:8",
      kind: "let",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "15:5-15:7",
          id: {
            type: "Identifier",
            loc: "15:5-15:7",
            name: "x4",
          },
          init: null,
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "17:1-17:10",
      kind: "const",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "17:7-17:9",
          id: {
            type: "Identifier",
            loc: "17:7-17:9",
            name: "x5",
          },
          init: null,
        },
      ],
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}