[package]
name = "brimstone"
version = "0.1.0"
authors = ["hanshalverson <hansghalverson@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
wrap_ordinary_object = { path = "src/js/runtime/wrap_ordinary_object" }