[package]
name = "brimstone"
version = "0.1.0"
authors = ["hanshalverson <hansghalverson@gmail.com>"]
edition = "2018"

[[bin]]
name = "bs"
path = "src/main.rs"

[dependencies]
bitflags = "2.1.0"
clap = { version = "4.0.29", features = ["derive"] }
indexmap = "2.1.0"
match_u32 = { path = "src/js/parser/match_u32" }
num-bigint = "0.4.3"
num-traits = "0.2.16"
rand = "0.8.5"
ryu-js = "0.2.2"
wrap_ordinary_object = { path = "src/js/runtime/wrap_ordinary_object" }

# ICU4X crates must all be the same version
icu_casemap = "1.5.0"
icu_collator = "1.5.0"
icu_collections = "1.5.0"
icu_locid = "1.5.0"
icu_locid_transform = "1.5.0"
icu_normalizer = "1.5.0"
icu_properties = "1.5.0"
icu_provider = { version = "1.5.0", features = ["sync"] }
icu_provider_adapters = "1.5.0"
zerovec = "0.10.2"

[features]
# Run the garbage collector in stress test mode
gc_stress_test = []

[lib]
doctest = false

[lints.clippy]
collapsible_else_if = "allow"
collapsible_if = "allow"
comparison_chain = "allow"
len_without_is_empty = "allow"
new_ret_no_self = "allow"
new_without_default = "allow"
too_many_arguments = "allow"
