[package]
name = "brimstone"
version = "0.1.0"
authors = ["hanshalverson <hansghalverson@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "2.1.0"
clap = { version = "4.0.29", features = ["derive"] }
match_u32 = { path = "src/js/parser/match_u32" }
num-bigint = "0.4.3"
rand = "0.8.5"
ryu-js = "0.2.2"
ucd-trie = { version = "0.1.5", default-features = false }
wrap_ordinary_object = { path = "src/js/runtime/wrap_ordinary_object" }