[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: NewClosure r0, c14
    45: StoreGlobal r0, c15
    48: NewClosure r0, c16
    51: StoreGlobal r0, c17
    54: LoadUndefined r0
    56: Ret r0
  Constant Table:
    0: [BytecodeFunction: simpleAssignHazard]
    1: [String: simpleAssignHazard]
    2: [BytecodeFunction: inOuterExpr]
    3: [String: inOuterExpr]
    4: [BytecodeFunction: inRegularParam]
    5: [String: inRegularParam]
    6: [BytecodeFunction: inRestParam]
    7: [String: inRestParam]
    8: [BytecodeFunction: inVarDeclarator]
    9: [String: inVarDeclarator]
    10: [BytecodeFunction: inCatchParam]
    11: [String: inCatchParam]
    12: [BytecodeFunction: inForEachInit]
    13: [String: inForEachInit]
    14: [BytecodeFunction: toplevelAssignExpressions]
    15: [String: toplevelAssignExpressions]
    16: [BytecodeFunction: nestedFunctionOrClass]
    17: [String: nestedFunctionOrClass]
}

[BytecodeFunction: simpleAssignHazard] {
  Parameters: 1, Registers: 1
     0: Mov r0, a0
     3: LoadImmediate a0, 2
     6: Add r0, r0, a0, fb0
    11: Ret r0
}

[BytecodeFunction: inOuterExpr] {
  Parameters: 1, Registers: 1
     0: Mov r0, a0
     3: LoadImmediate a0, 2
     6: Add r0, r0, a0, fb0
    11: JumpToBooleanFalse r0, 3 (.L0)
  .L0:
    14: LoadUndefined r0
    16: Ret r0
}

[BytecodeFunction: inRegularParam] {
  Parameters: 2, Registers: 1
     0: JumpNotUndefined a1, 14 (.L0)
     3: Mov r0, a0
     6: LoadImmediate a0, 2
     9: Add a1, r0, a0, fb0
  .L0:
    14: LoadUndefined r0
    16: Ret r0
}

[BytecodeFunction: inRestParam] {
  Parameters: 1, Registers: 3
     0: RestParameter r1
     2: Mov r2, a0
     5: LoadImmediate a0, 2
     8: Add r2, r2, a0, fb0
    13: GetProperty r0, r1, r2
    17: LoadUndefined r1
    19: Ret r1
}

[BytecodeFunction: inVarDeclarator] {
  Parameters: 1, Registers: 4
     0: NewObject r1
     2: GetNamedProperty r2, r1, c0
     6: JumpNotUndefined r2, 14 (.L0)
     9: Mov r3, a0
    12: LoadImmediate a0, 2
    15: Add r2, r3, a0, fb0
  .L0:
    20: Mov r0, r2
    23: LoadUndefined r1
    25: Ret r1
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: inCatchParam] {
  Parameters: 1, Registers: 4
     0: Mov r1, <scope>
     3: LoadImmediate r2, 1
     6: Jump 23 (.L0)
     8: Mov <scope>, r1
    11: Mov r3, a0
    14: LoadImmediate a0, 2
    17: Add r3, r3, a0, fb0
    22: GetProperty r0, r2, r3
    26: LoadImmediate r2, 3
  .L0:
    29: LoadUndefined r1
    31: Ret r1
  Exception Handlers:
    3-6 -> 8 (r2)
}

[BytecodeFunction: inForEachInit] {
  Parameters: 2, Registers: 3
     0: NewObject r0
     2: JumpNullish r0, 29 (.L1)
     5: NewForInIterator r0, r0
  .L0:
     8: ForInNext r1, r0
    11: JumpNullish r1, 20 (.L1)
    14: Mov r2, a0
    17: LoadImmediate a0, 2
    20: Add r2, r2, a0, fb0
    25: GetProperty a1, r1, r2
    29: Jump -21 (.L0)
  .L1:
    31: LoadUndefined r0
    33: Ret r0
}

[BytecodeFunction: toplevelAssignExpressions] {
  Parameters: 2, Registers: 1
     0: LoadImmediate r0, 1
     3: Add a0, a0, r0, fb0
     8: Mov r0, a0
    11: LoadImmediate a0, 2
    14: Add a1, r0, a0, fb1
    19: LoadImmediate a0, 3
    22: Mov a1, a0
    25: LoadUndefined r0
    27: Ret r0
}

[BytecodeFunction: nestedFunctionOrClass] {
  Parameters: 2, Registers: 2
     0: NewClosure r0, c0
     3: Add a0, a1, r0, fb0
     8: NewClosure r0, c1
    11: Add a0, a1, r0, fb1
    16: NewObject r0
    18: NewClosure r1, c3
    21: DefineNamedProperty r0, c2, r1
    25: Add a0, a1, r0, fb2
    30: LoadUndefined r0
    32: Ret r0
  Constant Table:
    0: [BytecodeFunction: <anonymous>]
    1: [BytecodeFunction: <anonymous>]
    2: [String: f]
    3: [BytecodeFunction: f]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 1, Registers: 1
    0: LoadImmediate a0, 1
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 1, Registers: 1
    0: LoadImmediate a0, 2
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: f] {
  Parameters: 1, Registers: 1
    0: LoadImmediate a0, 3
    3: LoadUndefined r0
    5: Ret r0
}
