[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: NewClosure r0, c11
    35: StoreGlobal r0, c12
    38: NewClosure r0, c13
    41: StoreGlobal r0, c14
    44: NewClosure r0, c15
    47: StoreGlobal r0, c16
    50: NewClosure r0, c17
    53: StoreGlobal r0, c18
    56: LoadUndefined r0
    58: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: simpleAssignHazard]
    2: [String: simpleAssignHazard]
    3: [BytecodeFunction: inOuterExpr]
    4: [String: inOuterExpr]
    5: [BytecodeFunction: inRegularParam]
    6: [String: inRegularParam]
    7: [BytecodeFunction: inRestParam]
    8: [String: inRestParam]
    9: [BytecodeFunction: inVarDeclarator]
    10: [String: inVarDeclarator]
    11: [BytecodeFunction: inCatchParam]
    12: [String: inCatchParam]
    13: [BytecodeFunction: inForEachInit]
    14: [String: inForEachInit]
    15: [BytecodeFunction: toplevelAssignExpressions]
    16: [String: toplevelAssignExpressions]
    17: [BytecodeFunction: nestedFunctionOrClass]
    18: [String: nestedFunctionOrClass]
}

[BytecodeFunction: simpleAssignHazard] {
  Parameters: 1, Registers: 1
     0: Mov r0, a0
     3: LoadImmediate a0, 2
     6: Add r0, r0, a0
    10: Ret r0
}

[BytecodeFunction: inOuterExpr] {
  Parameters: 1, Registers: 1
     0: Mov r0, a0
     3: LoadImmediate a0, 2
     6: Add r0, r0, a0
    10: JumpToBooleanFalse r0, 3 (.L0)
  .L0:
    13: LoadUndefined r0
    15: Ret r0
}

[BytecodeFunction: inRegularParam] {
  Parameters: 2, Registers: 1
     0: JumpNotUndefined a0, 13 (.L0)
     3: Mov r0, a1
     6: LoadImmediate a1, 2
     9: Add a0, r0, a1
  .L0:
    13: LoadUndefined r0
    15: Ret r0
}

[BytecodeFunction: inRestParam] {
  Parameters: 1, Registers: 3
     0: RestParameter r1
     2: Mov r2, a0
     5: LoadImmediate a0, 2
     8: Add r2, r2, a0
    12: GetProperty r0, r1, r2
    16: LoadUndefined r1
    18: Ret r1
}

[BytecodeFunction: inVarDeclarator] {
  Parameters: 1, Registers: 4
     0: NewObject r1
     2: GetNamedProperty r2, r1, c0
     6: JumpNotUndefined r2, 13 (.L0)
     9: Mov r3, a0
    12: LoadImmediate a0, 2
    15: Add r2, r3, a0
  .L0:
    19: Mov r0, r2
    22: LoadUndefined r1
    24: Ret r1
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: inCatchParam] {
  Parameters: 1, Registers: 4
     0: Mov r1, <scope>
     3: LoadImmediate r2, 1
     6: Jump 22 (.L0)
     8: Mov <scope>, r1
    11: Mov r3, a0
    14: LoadImmediate a0, 2
    17: Add r3, r3, a0
    21: GetProperty r0, r2, r3
    25: LoadImmediate r2, 3
  .L0:
    28: LoadUndefined r1
    30: Ret r1
  Exception Handlers:
    3-6 -> 8 (r2)
}

[BytecodeFunction: inForEachInit] {
  Parameters: 2, Registers: 3
     0: NewObject r0
     2: JumpNullish r0, 28 (.L1)
     5: NewForInIterator r0, r0
  .L0:
     8: ForInNext r1, r0
    11: JumpNullish r1, 19 (.L1)
    14: Mov r2, a0
    17: LoadImmediate a0, 2
    20: Add r2, r2, a0
    24: GetProperty a1, r1, r2
    28: Jump -20 (.L0)
  .L1:
    30: LoadUndefined r0
    32: Ret r0
}

[BytecodeFunction: toplevelAssignExpressions] {
  Parameters: 2, Registers: 1
     0: LoadImmediate r0, 1
     3: Add a0, a0, r0
     7: Mov r0, a0
    10: LoadImmediate a0, 2
    13: Add a1, r0, a0
    17: LoadImmediate a0, 3
    20: Mov a1, a0
    23: LoadUndefined r0
    25: Ret r0
}

[BytecodeFunction: nestedFunctionOrClass] {
  Parameters: 2, Registers: 2
     0: NewClosure r0, c0
     3: Add a0, a1, r0
     7: NewClosure r0, c1
    10: Add a0, a1, r0
    14: NewObject r0
    16: NewClosure r1, c3
    19: DefineNamedProperty r0, c2, r1
    23: Add a0, a1, r0
    27: LoadUndefined r0
    29: Ret r0
  Constant Table:
    0: [BytecodeFunction: <anonymous>]
    1: [BytecodeFunction: <anonymous>]
    2: [String: f]
    3: [BytecodeFunction: f]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 1, Registers: 1
    0: LoadImmediate a0, 1
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 1, Registers: 1
    0: LoadImmediate a0, 2
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: f] {
  Parameters: 1, Registers: 1
    0: LoadImmediate a0, 3
    3: LoadUndefined r0
    5: Ret r0
}
