[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: 14 ff 00   NewClosure r0, c0
     3: 0a ff 01   StoreGlobal r0, c1
     6: 14 ff 02   NewClosure r0, c2
     9: 0a ff 03   StoreGlobal r0, c3
    12: 14 ff 04   NewClosure r0, c4
    15: 0a ff 05   StoreGlobal r0, c5
    18: 14 ff 06   NewClosure r0, c6
    21: 0a ff 07   StoreGlobal r0, c7
    24: 14 ff 08   NewClosure r0, c8
    27: 0a ff 07   StoreGlobal r0, c7
    30: 05 ff      LoadUndefined r0
    32: 0c ff      Ret r0
  Constant Table:
    0: [BytecodeFunction: f]
    1: [String: f]
    2: [BytecodeFunction: testShortPatchCondJump]
    3: [String: testShortPatchCondJump]
    4: [BytecodeFunction: testLongPatchCondJump]
    5: [String: testLongPatchCondJump]
    6: [BytecodeFunction: testShortPatchJump]
    7: [String: testShortPatchJump]
    8: [BytecodeFunction: testShortPatchJump]
}

[BytecodeFunction: f] {
  Parameters: 0, Registers: 1
    0: 05 ff   LoadUndefined r0
    2: 0c ff   Ret r0
}

[BytecodeFunction: testShortPatchCondJump] {
  Parameters: 1, Registers: 1
     0: 12 05 08   JumpFalse a0, 8 (.L0)
     3: 03 ff 01   LoadImmediate r0, 1
     6: 0c ff      Ret r0
  .L0:
     8: 03 ff 02   LoadImmediate r0, 2
    11: 0c ff      Ret r0
}

[BytecodeFunction: testLongPatchCondJump] {
  Parameters: 1, Registers: 11
      0: 13 05 01         JumpFalseConstant a0, c1 (.L0)
      3: 09 ff 00         LoadGlobal r0, c0
      6: 03 fe 01         LoadImmediate r1, 1
      9: 03 fd 02         LoadImmediate r2, 2
     12: 03 fc 03         LoadImmediate r3, 3
     15: 03 fb 04         LoadImmediate r4, 4
     18: 03 fa 05         LoadImmediate r5, 5
     21: 03 f9 06         LoadImmediate r6, 6
     24: 03 f8 07         LoadImmediate r7, 7
     27: 03 f7 08         LoadImmediate r8, 8
     30: 03 f6 09         LoadImmediate r9, 9
     33: 03 f5 0a         LoadImmediate r10, 10
     36: 0b ff ff fe 0a   Call r0, r0, r1, 10
     41: 09 ff 00         LoadGlobal r0, c0
     44: 03 fe 01         LoadImmediate r1, 1
     47: 03 fd 02         LoadImmediate r2, 2
     50: 03 fc 03         LoadImmediate r3, 3
     53: 03 fb 04         LoadImmediate r4, 4
     56: 03 fa 05         LoadImmediate r5, 5
     59: 03 f9 06         LoadImmediate r6, 6
     62: 03 f8 07         LoadImmediate r7, 7
     65: 03 f7 08         LoadImmediate r8, 8
     68: 03 f6 09         LoadImmediate r9, 9
     71: 03 f5 0a         LoadImmediate r10, 10
     74: 0b ff ff fe 0a   Call r0, r0, r1, 10
     79: 09 ff 00         LoadGlobal r0, c0
     82: 03 fe 01         LoadImmediate r1, 1
     85: 03 fd 02         LoadImmediate r2, 2
     88: 03 fc 03         LoadImmediate r3, 3
     91: 03 fb 04         LoadImmediate r4, 4
     94: 03 fa 05         LoadImmediate r5, 5
     97: 03 f9 06         LoadImmediate r6, 6
    100: 03 f8 07         LoadImmediate r7, 7
    103: 03 f7 08         LoadImmediate r8, 8
    106: 03 f6 09         LoadImmediate r9, 9
    109: 03 f5 0a         LoadImmediate r10, 10
    112: 0b ff ff fe 0a   Call r0, r0, r1, 10
    117: 09 ff 00         LoadGlobal r0, c0
    120: 03 fe 01         LoadImmediate r1, 1
    123: 03 fd 02         LoadImmediate r2, 2
    126: 03 fc 03         LoadImmediate r3, 3
    129: 03 fb 04         LoadImmediate r4, 4
    132: 03 fa 05         LoadImmediate r5, 5
    135: 03 f9 06         LoadImmediate r6, 6
    138: 03 f8 07         LoadImmediate r7, 7
    141: 03 f7 08         LoadImmediate r8, 8
    144: 03 f6 09         LoadImmediate r9, 9
    147: 03 f5 0a         LoadImmediate r10, 10
    150: 0b ff ff fe 0a   Call r0, r0, r1, 10
    155: 09 ff 00         LoadGlobal r0, c0
    158: 03 fe 01         LoadImmediate r1, 1
    161: 03 fd 02         LoadImmediate r2, 2
    164: 03 fc 03         LoadImmediate r3, 3
    167: 03 fb 04         LoadImmediate r4, 4
    170: 03 fa 05         LoadImmediate r5, 5
    173: 03 f9 06         LoadImmediate r6, 6
    176: 03 f8 07         LoadImmediate r7, 7
    179: 03 f7 08         LoadImmediate r8, 8
    182: 03 f6 09         LoadImmediate r9, 9
    185: 03 f5 0a         LoadImmediate r10, 10
    188: 0b ff ff fe 0a   Call r0, r0, r1, 10
    193: 09 ff 00         LoadGlobal r0, c0
    196: 03 fe 01         LoadImmediate r1, 1
    199: 03 fd 02         LoadImmediate r2, 2
    202: 03 fc 03         LoadImmediate r3, 3
    205: 03 fb 04         LoadImmediate r4, 4
    208: 03 fa 05         LoadImmediate r5, 5
    211: 03 f9 06         LoadImmediate r6, 6
    214: 03 f8 07         LoadImmediate r7, 7
    217: 03 f7 08         LoadImmediate r8, 8
    220: 03 f6 09         LoadImmediate r9, 9
    223: 03 f5 0a         LoadImmediate r10, 10
    226: 0b ff ff fe 0a   Call r0, r0, r1, 10
    231: 09 ff 00         LoadGlobal r0, c0
    234: 03 fe 01         LoadImmediate r1, 1
    237: 03 fd 02         LoadImmediate r2, 2
    240: 03 fc 03         LoadImmediate r3, 3
    243: 03 fb 04         LoadImmediate r4, 4
    246: 03 fa 05         LoadImmediate r5, 5
    249: 03 f9 06         LoadImmediate r6, 6
    252: 03 f8 07         LoadImmediate r7, 7
    255: 03 f7 08         LoadImmediate r8, 8
    258: 03 f6 09         LoadImmediate r9, 9
    261: 03 f5 0a         LoadImmediate r10, 10
    264: 0b ff ff fe 0a   Call r0, r0, r1, 10
    269: 03 ff 01         LoadImmediate r0, 1
    272: 0c ff            Ret r0
    274: 03 ff 02         LoadImmediate r0, 2
    277: 0c ff            Ret r0
  Constant Table:
    0: [String: f]
    1: 274
}

[BytecodeFunction: testShortPatchJump] {
  Parameters: 1, Registers: 1
     0: 12 05 08   JumpFalse a0, 8 (.L0)
     3: 03 ff 01   LoadImmediate r0, 1
     6: 10 05      Jump 5 (.L1)
  .L0:
     8: 03 ff 02   LoadImmediate r0, 2
  .L1:
    11: 03 ff 03   LoadImmediate r0, 3
    14: 0c ff      Ret r0
}

[BytecodeFunction: testShortPatchJump] {
  Parameters: 1, Registers: 11
      0: 12 05 08         JumpFalse a0, 8 (.L1)
      3: 03 ff 01         LoadImmediate r0, 1
      6: 11 01            JumpConstant c1 (.L0)
  .L1:
      8: 09 ff 00         LoadGlobal r0, c0
     11: 03 fe 01         LoadImmediate r1, 1
     14: 03 fd 02         LoadImmediate r2, 2
     17: 03 fc 03         LoadImmediate r3, 3
     20: 03 fb 04         LoadImmediate r4, 4
     23: 03 fa 05         LoadImmediate r5, 5
     26: 03 f9 06         LoadImmediate r6, 6
     29: 03 f8 07         LoadImmediate r7, 7
     32: 03 f7 08         LoadImmediate r8, 8
     35: 03 f6 09         LoadImmediate r9, 9
     38: 03 f5 0a         LoadImmediate r10, 10
     41: 0b ff ff fe 0a   Call r0, r0, r1, 10
     46: 09 ff 00         LoadGlobal r0, c0
     49: 03 fe 01         LoadImmediate r1, 1
     52: 03 fd 02         LoadImmediate r2, 2
     55: 03 fc 03         LoadImmediate r3, 3
     58: 03 fb 04         LoadImmediate r4, 4
     61: 03 fa 05         LoadImmediate r5, 5
     64: 03 f9 06         LoadImmediate r6, 6
     67: 03 f8 07         LoadImmediate r7, 7
     70: 03 f7 08         LoadImmediate r8, 8
     73: 03 f6 09         LoadImmediate r9, 9
     76: 03 f5 0a         LoadImmediate r10, 10
     79: 0b ff ff fe 0a   Call r0, r0, r1, 10
     84: 09 ff 00         LoadGlobal r0, c0
     87: 03 fe 01         LoadImmediate r1, 1
     90: 03 fd 02         LoadImmediate r2, 2
     93: 03 fc 03         LoadImmediate r3, 3
     96: 03 fb 04         LoadImmediate r4, 4
     99: 03 fa 05         LoadImmediate r5, 5
    102: 03 f9 06         LoadImmediate r6, 6
    105: 03 f8 07         LoadImmediate r7, 7
    108: 03 f7 08         LoadImmediate r8, 8
    111: 03 f6 09         LoadImmediate r9, 9
    114: 03 f5 0a         LoadImmediate r10, 10
    117: 0b ff ff fe 0a   Call r0, r0, r1, 10
    122: 09 ff 00         LoadGlobal r0, c0
    125: 03 fe 01         LoadImmediate r1, 1
    128: 03 fd 02         LoadImmediate r2, 2
    131: 03 fc 03         LoadImmediate r3, 3
    134: 03 fb 04         LoadImmediate r4, 4
    137: 03 fa 05         LoadImmediate r5, 5
    140: 03 f9 06         LoadImmediate r6, 6
    143: 03 f8 07         LoadImmediate r7, 7
    146: 03 f7 08         LoadImmediate r8, 8
    149: 03 f6 09         LoadImmediate r9, 9
    152: 03 f5 0a         LoadImmediate r10, 10
    155: 0b ff ff fe 0a   Call r0, r0, r1, 10
    160: 09 ff 00         LoadGlobal r0, c0
    163: 03 fe 01         LoadImmediate r1, 1
    166: 03 fd 02         LoadImmediate r2, 2
    169: 03 fc 03         LoadImmediate r3, 3
    172: 03 fb 04         LoadImmediate r4, 4
    175: 03 fa 05         LoadImmediate r5, 5
    178: 03 f9 06         LoadImmediate r6, 6
    181: 03 f8 07         LoadImmediate r7, 7
    184: 03 f7 08         LoadImmediate r8, 8
    187: 03 f6 09         LoadImmediate r9, 9
    190: 03 f5 0a         LoadImmediate r10, 10
    193: 0b ff ff fe 0a   Call r0, r0, r1, 10
    198: 09 ff 00         LoadGlobal r0, c0
    201: 03 fe 01         LoadImmediate r1, 1
    204: 03 fd 02         LoadImmediate r2, 2
    207: 03 fc 03         LoadImmediate r3, 3
    210: 03 fb 04         LoadImmediate r4, 4
    213: 03 fa 05         LoadImmediate r5, 5
    216: 03 f9 06         LoadImmediate r6, 6
    219: 03 f8 07         LoadImmediate r7, 7
    222: 03 f7 08         LoadImmediate r8, 8
    225: 03 f6 09         LoadImmediate r9, 9
    228: 03 f5 0a         LoadImmediate r10, 10
    231: 0b ff ff fe 0a   Call r0, r0, r1, 10
    236: 09 ff 00         LoadGlobal r0, c0
    239: 03 fe 01         LoadImmediate r1, 1
    242: 03 fd 02         LoadImmediate r2, 2
    245: 03 fc 03         LoadImmediate r3, 3
    248: 03 fb 04         LoadImmediate r4, 4
    251: 03 fa 05         LoadImmediate r5, 5
    254: 03 f9 06         LoadImmediate r6, 6
    257: 03 f8 07         LoadImmediate r7, 7
    260: 03 f7 08         LoadImmediate r8, 8
    263: 03 f6 09         LoadImmediate r9, 9
    266: 03 f5 0a         LoadImmediate r10, 10
    269: 0b ff ff fe 0a   Call r0, r0, r1, 10
    274: 03 ff 02         LoadImmediate r0, 2
    277: 0c ff            Ret r0
  Constant Table:
    0: [String: f]
    1: 268
}
