[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: LoadImmediate r0, 1
    11: LoadGlobal r0, c3
    14: LoadConstant r1, c4
    17: CallMaybeEval r0, r0, r1, 1
    22: LoadUndefined r0
    24: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: func]
    2: [String: func]
    3: [String: eval]
    4: [String: "use strict"; 3;]
}

[BytecodeFunction: func] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 2
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: <eval>] {
  Parameters: 0, Registers: 1
    0: 03 ff 03   LoadImmediate r0, 3
    3: 12 ff      Ret r0
}

