[BytecodeFunction: <module>] {
  Parameters: 0, Registers: 2
    0: NewClosure r0, c0
    3: LoadUndefined r1
    5: Ret r1
  Constant Table:
    0: [BytecodeFunction: testAccessImportedBindings]
}

[BytecodeFunction: testAccessImportedBindings] {
  Parameters: 0, Registers: 2
     0: LoadFromModule r0, 1, 0
     4: LoadFromModule r1, 2, 0
     8: Add r0, r0, r1, ic0
    13: LoadFromModule r1, 3, 0
    17: Add r0, r0, r1, ic1
    22: LoadUndefined r0
    24: Ret r0
}
