[BytecodeFunction: <module>] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: RetUndefined 
  Constant Table:
    0: [BytecodeFunction: testAccessImportedBindings]
}

[BytecodeFunction: testAccessImportedBindings] {
  Parameters: 0, Registers: 2
     0: LoadFromModule r0, 1, 0
     4: LoadFromModule r1, 2, 0
     8: Add r0, r0, r1
    12: LoadFromModule r1, 3, 0
    16: Add r0, r0, r1
    20: RetUndefined 
}
