[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: StoreGlobal r0, c1, k0
    7: LoadUndefined r0
    9: Ret r0
  Constant Table:
    0: [BytecodeFunction: testComputedKeyNotClobbered]
    1: [String: testComputedKeyNotClobbered]
}

[BytecodeFunction: testComputedKeyNotClobbered] {
  Parameters: 1, Registers: 4
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: ToPropertyKey r2, a0
     7: StoreToScope r2, 0, 0
    11: NewClass r0, c2, c1, r1, r0
    17: NewClosure r2, c3
    20: LoadConstant r3, c4
    23: DefinePrivateProperty r0, r3, r2, 0
    28: PopScope 
    29: LoadUndefined r1
    31: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: C1]
    2: [ClassNames]
    3: [BytecodeFunction: fieldsInitializer]
    4: [SymbolValue: fieldsInitializer]
}

[BytecodeFunction: C1] {
  Parameters: 0, Registers: 1
     0: GetNamedProperty r0, <closure>, c0, k0
     5: CallWithReceiver r0, r0, <this>, r0, 0
    11: LoadUndefined r0
    13: Ret r0
  Constant Table:
    0: [SymbolValue: fieldsInitializer]
}

[BytecodeFunction: fieldsInitializer] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadFromScope r1, 0, 0
     7: DefineProperty <this>, r1, r0, 0
    12: LoadUndefined r0
    14: Ret r0
}
