[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
      0: LoadEmpty r1
      2: NewClass r0, c1, c0, r1, r0
      8: StoreToScope r0, 1, 0
     12: LoadEmpty r1
     14: NewClass r0, c3, c2, r1, r0
     20: StoreToScope r0, 2, 0
     24: LoadEmpty r1
     26: NewClass r0, c5, c4, r1, r0
     32: StoreToScope r0, 3, 0
     36: LoadGlobal r1, c6, k0
     40: NewClass r0, c8, c7, r1, r0
     46: StoreToScope r0, 4, 0
     50: LoadGlobal r1, c6, k1
     54: NewClass r0, c10, c9, r1, r0
     60: StoreToScope r0, 5, 0
     64: LoadGlobal r1, c6, k2
     68: NewClass r0, c12, c11, r1, r0
     74: StoreToScope r0, 6, 0
     78: LoadGlobal r1, c6, k3
     82: NewClass r0, c14, c13, r1, r0
     88: StoreToScope r0, 7, 0
     92: LoadGlobal r1, c6, k4
     96: NewClass r0, c16, c15, r1, r0
    102: StoreToScope r0, 8, 0
    106: LoadGlobal r1, c6, k5
    110: NewClass r0, c18, c17, r1, r0
    116: StoreToScope r0, 9, 0
    120: LoadGlobal r1, c6, k6
    124: NewClass r0, c20, c19, r1, r0
    130: StoreToScope r0, 10, 0
    134: LoadGlobal r1, c6, k7
    138: NewClass r0, c22, c21, r1, r0
    144: StoreToScope r0, 11, 0
    148: LoadUndefined r0
    150: Ret r0
  Constant Table:
    0: [BytecodeFunction: ExplicitConstructor]
    1: [ClassNames]
    2: [BytecodeFunction: BaseDefaultConstructor]
    3: [ClassNames]
    4: [BytecodeFunction: ThisInBaseConstructor]
    5: [ClassNames]
    6: [String: String]
    7: [BytecodeFunction: ThisInDerivedConstructor]
    8: [ClassNames]
    9: [BytecodeFunction: DerivedConstructorWithReturnValue]
    10: [ClassNames]
    11: [BytecodeFunction: DerivedConstructorWithNoArgReturn]
    12: [ClassNames]
    13: [BytecodeFunction: CapturedThisInDerivedConstructor]
    14: [ClassNames]
    15: [BytecodeFunction: CapturedThisInDerivedConstructorWithReturnValue]
    16: [ClassNames]
    17: [BytecodeFunction: CapturedThisInDerivedConstructorWithNoArgReturn]
    18: [ClassNames]
    19: [BytecodeFunction: FinallyWithDerivedReturn]
    20: [ClassNames]
    21: [BytecodeFunction: FinallyWithDerivedReturnCapturedThis]
    22: [ClassNames]
}

[BytecodeFunction: ExplicitConstructor] {
  Parameters: 1, Registers: 0
    0: Ret a0
}

[BytecodeFunction: BaseDefaultConstructor] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: ThisInBaseConstructor] {
  Parameters: 0, Registers: 1
     0: GetNamedProperty r0, <this>, c0, k0
     5: LoadImmediate r0, 1
     8: SetNamedProperty <this>, c0, r0, k1
    13: LoadUndefined r0
    15: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: ThisInDerivedConstructor] {
  Parameters: 0, Registers: 4
     0: LoadEmpty <this>
     2: Mov r0, <closure>
     5: GetSuperConstructor r3, r0
     8: Construct r2, r3, r1, r1, 0, k0
    15: CheckSuperAlreadyCalled <this>
    17: Mov <this>, r2
    20: CheckThisInitialized <this>
    22: GetNamedProperty r2, <this>, c0, k1
    27: CheckThisInitialized <this>
    29: LoadImmediate r2, 1
    32: SetNamedProperty <this>, c0, r2, k2
    37: CheckThisInitialized <this>
    39: Ret <this>
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: DerivedConstructorWithReturnValue] {
  Parameters: 0, Registers: 4
     0: LoadEmpty <this>
     2: Mov r0, <closure>
     5: GetSuperConstructor r3, r0
     8: Construct r2, r3, r1, r1, 0, k0
    15: CheckSuperAlreadyCalled <this>
    17: Mov <this>, r2
    20: LoadImmediate r2, 1
    23: Mov r3, r2
    26: JumpNotUndefined r2, 8 (.L0)
    29: CheckThisInitialized <this>
    31: Mov r3, <this>
  .L0:
    34: Ret r3
}

[BytecodeFunction: DerivedConstructorWithNoArgReturn] {
  Parameters: 0, Registers: 4
     0: LoadEmpty <this>
     2: Mov r0, <closure>
     5: GetSuperConstructor r3, r0
     8: Construct r2, r3, r1, r1, 0, k0
    15: CheckSuperAlreadyCalled <this>
    17: Mov <this>, r2
    20: CheckThisInitialized <this>
    22: Ret <this>
}

[BytecodeFunction: CapturedThisInDerivedConstructor] {
  Parameters: 0, Registers: 4
     0: PushFunctionScope c0
     2: LoadEmpty <this>
     4: StoreToScope <this>, 0, 0
     8: Mov r0, <closure>
    11: GetSuperConstructor r3, r0
    14: Construct r2, r3, r1, r1, 0, k0
    21: LoadFromScope r3, 0, 0
    25: CheckSuperAlreadyCalled r3
    27: StoreToScope r2, 0, 0
    31: NewClosure r2, c1
    34: LoadFromScope r2, 0, 0
    38: CheckThisInitialized r2
    40: GetNamedProperty r2, r2, c2, k1
    45: LoadFromScope r3, 0, 0
    49: CheckThisInitialized r3
    51: LoadImmediate r2, 1
    54: SetNamedProperty r3, c2, r2, k2
    59: LoadFromScope r2, 0, 0
    63: CheckThisInitialized r2
    65: Ret r2
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
    2: [String: x]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckThisInitialized r0
    6: LoadUndefined r0
    8: Ret r0
}

[BytecodeFunction: CapturedThisInDerivedConstructorWithReturnValue] {
  Parameters: 0, Registers: 4
     0: PushFunctionScope c0
     2: LoadEmpty <this>
     4: StoreToScope <this>, 0, 0
     8: Mov r0, <closure>
    11: GetSuperConstructor r3, r0
    14: Construct r2, r3, r1, r1, 0, k0
    21: LoadFromScope r3, 0, 0
    25: CheckSuperAlreadyCalled r3
    27: StoreToScope r2, 0, 0
    31: NewClosure r2, c1
    34: LoadImmediate r2, 1
    37: Mov r3, r2
    40: JumpNotUndefined r2, 9 (.L0)
    43: LoadFromScope r3, 0, 0
    47: CheckThisInitialized r3
  .L0:
    49: Ret r3
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckThisInitialized r0
    6: LoadUndefined r0
    8: Ret r0
}

[BytecodeFunction: CapturedThisInDerivedConstructorWithNoArgReturn] {
  Parameters: 0, Registers: 4
     0: PushFunctionScope c0
     2: LoadEmpty <this>
     4: StoreToScope <this>, 0, 0
     8: Mov r0, <closure>
    11: GetSuperConstructor r3, r0
    14: Construct r2, r3, r1, r1, 0, k0
    21: LoadFromScope r3, 0, 0
    25: CheckSuperAlreadyCalled r3
    27: StoreToScope r2, 0, 0
    31: NewClosure r2, c1
    34: LoadFromScope r2, 0, 0
    38: CheckThisInitialized r2
    40: Ret r2
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckThisInitialized r0
    6: LoadUndefined r0
    8: Ret r0
}

[BytecodeFunction: FinallyWithDerivedReturn] {
  Parameters: 0, Registers: 6
     0: LoadEmpty <this>
     2: Mov r0, <closure>
     5: GetSuperConstructor r3, r0
     8: Construct r2, r3, r1, r1, 0, k0
    15: CheckSuperAlreadyCalled <this>
    17: Mov <this>, r2
    20: Mov r4, <scope>
    23: LoadImmediate r5, 1
    26: LoadImmediate r2, 1
    29: LoadUndefined r3
    31: Jump 5 (.L0)
    33: LoadImmediate r2, 0
  .L0:
    36: Mov <scope>, r4
    39: LoadImmediate r4, 2
    42: LoadImmediate r4, 0
    45: StrictEqual r4, r2, r4
    49: JumpFalse r4, 5 (.L1)
    52: Rethrow r3
  .L1:
    54: Mov r5, r3
    57: JumpNotUndefined r3, 8 (.L2)
    60: CheckThisInitialized <this>
    62: Mov r5, <this>
  .L2:
    65: Ret r5
    67: CheckThisInitialized <this>
    69: Ret <this>
  Exception Handlers:
    23-33 -> 33 (r3)
}

[BytecodeFunction: FinallyWithDerivedReturnCapturedThis] {
  Parameters: 0, Registers: 6
     0: PushFunctionScope c0
     2: LoadEmpty <this>
     4: StoreToScope <this>, 0, 0
     8: Mov r0, <closure>
    11: GetSuperConstructor r3, r0
    14: Construct r2, r3, r1, r1, 0, k0
    21: LoadFromScope r3, 0, 0
    25: CheckSuperAlreadyCalled r3
    27: StoreToScope r2, 0, 0
    31: NewClosure r2, c1
    34: Mov r4, <scope>
    37: LoadImmediate r5, 1
    40: LoadImmediate r2, 1
    43: LoadUndefined r3
    45: Jump 5 (.L0)
    47: LoadImmediate r2, 0
  .L0:
    50: Mov <scope>, r4
    53: LoadImmediate r4, 2
    56: LoadImmediate r4, 0
    59: StrictEqual r4, r2, r4
    63: JumpFalse r4, 5 (.L1)
    66: Rethrow r3
  .L1:
    68: Mov r5, r3
    71: JumpNotUndefined r3, 9 (.L2)
    74: LoadFromScope r5, 0, 0
    78: CheckThisInitialized r5
  .L2:
    80: Ret r5
    82: LoadFromScope r2, 0, 0
    86: CheckThisInitialized r2
    88: Ret r2
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
  Exception Handlers:
    37-47 -> 47 (r3)
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckThisInitialized r0
    6: Ret r0
}
