[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: LoadUndefined r0
    38: Ret r0
  Constant Table:
    0: [BytecodeFunction: notCaptured]
    1: [String: notCaptured]
    2: [BytecodeFunction: capturedByMethod]
    3: [String: capturedByMethod]
    4: [BytecodeFunction: capturedByStaticInitializer]
    5: [String: capturedByStaticInitializer]
    6: [BytecodeFunction: classExpressionCaptured]
    7: [String: classExpressionCaptured]
    8: [BytecodeFunction: capturedByEval]
    9: [String: capturedByEval]
    10: [BytecodeFunction: canReassignOutsideBodyButNotInside]
    11: [String: canReassignOutsideBodyButNotInside]
}

[BytecodeFunction: notCaptured] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r1
     2: NewClosure r2, c0
     5: NewClass r0, c2, c1, r1, r2
    11: LoadUndefined r1
    13: Ret r1
  Constant Table:
    0: [BytecodeFunction: method]
    1: [BytecodeFunction: C]
    2: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: capturedByMethod] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: LoadEmpty r1
    10: NewClosure r2, c1
    13: NewClass r0, c3, c2, r1, r2
    19: StoreToScope r0, 0, 0
    23: PopScope 
    24: LoadUndefined r1
    26: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: method]
    2: [BytecodeFunction: C]
    3: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: LoadUndefined r0
    9: Ret r0
  Constant Table:
    0: [String: C]
}

[BytecodeFunction: capturedByStaticInitializer] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: LoadEmpty r1
    10: NewClass r0, c2, c1, r1, r0
    16: StoreToScope r0, 0, 0
    20: NewClosure r2, c3
    23: CallWithReceiver r2, r2, r0, r2, 0
    29: PopScope 
    30: LoadUndefined r1
    32: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: C]
    2: [ClassNames]
    3: [BytecodeFunction: staticInitializer]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: staticInitializer] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: LoadUndefined r0
    9: Ret r0
  Constant Table:
    0: [String: C]
}

[BytecodeFunction: classExpressionCaptured] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: LoadEmpty r1
    10: NewClosure r2, c1
    13: NewClass r0, c3, c2, r1, r2
    19: StoreToScope r0, 0, 0
    23: PopScope 
    24: LoadUndefined r0
    26: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: method]
    2: [BytecodeFunction: C]
    3: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: LoadUndefined r0
    9: Ret r0
  Constant Table:
    0: [String: C]
}

[BytecodeFunction: capturedByEval] {
  Parameters: 0, Registers: 3
     0: PushFunctionScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 1, 0
     8: StoreToScope <this>, 0, 0
    12: StoreToScope r0, 3, 0
    16: NewMappedArguments r0
    18: StoreToScope r0, 2, 0
    22: PushLexicalScope c1
    24: LoadEmpty r1
    26: StoreToScope r1, 0, 0
    30: LoadEmpty r1
    32: NewClosure r2, c2
    35: NewClass r0, c4, c3, r1, r2
    41: StoreToScope r0, 0, 0
    45: PopScope 
    46: StoreToScope r0, 1, 0
    50: LoadUndefined r0
    52: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [BytecodeFunction: method]
    3: [BytecodeFunction: C]
    4: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 2
     0: PushFunctionScope c0
     2: StoreToScope <this>, 0, 0
     6: StoreToScope r0, 2, 0
    10: NewUnmappedArguments r0
    12: StoreToScope r0, 1, 0
    16: LoadGlobal r0, c1
    19: LoadConstant r1, c2
    22: CallMaybeEval r0, r0, r1, 1, 3
    28: LoadUndefined r0
    30: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [String: eval]
    2: [String: ]
}

[BytecodeFunction: canReassignOutsideBodyButNotInside] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: LoadEmpty r1
    10: NewClosure r2, c1
    13: NewClass r0, c3, c2, r1, r2
    19: StoreToScope r0, 0, 0
    23: PopScope 
    24: LoadImmediate r0, 2
    27: LoadUndefined r1
    29: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: method]
    2: [BytecodeFunction: C]
    3: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: ErrorConst c0
     5: LoadFromScope r1, 0, 0
     9: CheckTdz r1, c0
    12: StoreToScope r0, 0, 0
    16: LoadUndefined r0
    18: Ret r0
  Constant Table:
    0: [String: C]
}
