[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: StoreGlobal r0, c1, k0
    7: LoadUndefined r0
    9: Ret r0
  Constant Table:
    0: [BytecodeFunction: superClass]
    1: [String: superClass]
}

[BytecodeFunction: superClass] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r1, 1
     3: AddImm r1, r1, 2
     7: NewClass r0, c1, c0, r1, r0
    13: LoadUndefined r1
    15: Ret r1
  Constant Table:
    0: [BytecodeFunction: C]
    1: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: DefaultSuperCall 
    1: CheckThisInitialized <this>
    3: Ret <this>
}
