[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 4
      0: PushLexicalScope c0
      2: LoadGlobal r1, c1
      5: NewClosure r2, c2
      8: NewClosure r3, c3
     11: NewClass r0, c5, c4, r1, r2
     17: PopScope 
     18: StoreToScope r0, 1, 0
     22: PushLexicalScope c6
     24: LoadGlobal r1, c1
     27: NewClass r0, c8, c7, r1, r0
     33: PopScope 
     34: StoreToScope r0, 2, 0
     38: PushLexicalScope c9
     40: LoadGlobal r1, c10
     43: NewClosure r2, c11
     46: NewClass r0, c13, c12, r1, r2
     52: PopScope 
     53: StoreToScope r0, 3, 0
     57: PushLexicalScope c14
     59: LoadGlobal r1, c10
     62: NewClosure r2, c15
     65: NewClass r0, c17, c16, r1, r2
     71: PopScope 
     72: StoreToScope r0, 4, 0
     76: PushLexicalScope c18
     78: LoadGlobal r1, c10
     81: NewClosure r2, c19
     84: NewClass r0, c21, c20, r1, r2
     90: PopScope 
     91: StoreToScope r0, 5, 0
     95: PushLexicalScope c22
     97: NewObject r0
     99: StoreToScope r0, 0, 0
    103: NewClosure r1, c24
    106: DefineNamedProperty r0, c23, r1
    110: PopScope 
    111: StoreToScope r0, 6, 0
    115: LoadUndefined r0
    117: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [String: String]
    2: [BytecodeFunction: instanceSuperMember]
    3: [BytecodeFunction: staticSuperMember]
    4: [BytecodeFunction: C1]
    5: [ClassNames]
    6: [ScopeNames]
    7: [BytecodeFunction: C2]
    8: [ClassNames]
    9: [ScopeNames]
    10: [String: Object]
    11: [BytecodeFunction: method]
    12: [BytecodeFunction: C3]
    13: [ClassNames]
    14: [ScopeNames]
    15: [BytecodeFunction: method]
    16: [BytecodeFunction: C4]
    17: [ClassNames]
    18: [ScopeNames]
    19: [BytecodeFunction: method]
    20: [BytecodeFunction: C5]
    21: [ClassNames]
    22: [ScopeNames]
    23: [String: method]
    24: [BytecodeFunction: method]
}

[BytecodeFunction: C1] {
  Parameters: 0, Registers: 3
     0: LoadEmpty <this>
     2: Mov r0, <closure>
     5: GetSuperConstructor r2, r0
     8: Construct r2, r2, r1, r1, 0
    14: CheckSuperAlreadyCalled <this>
    16: Mov <this>, r2
    19: CheckThisInitialized <this>
    21: LoadFromScope r2, 0, 0
    25: GetNamedSuperProperty r2, r2, <this>, c0
    30: CheckThisInitialized <this>
    32: Ret <this>
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: instanceSuperMember] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: GetNamedSuperProperty r0, r0, <this>, c0
    9: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: staticSuperMember] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 1, 0
    4: GetNamedSuperProperty r0, r0, <this>, c0
    9: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: C2] {
  Parameters: 0, Registers: 2
     0: PushFunctionScope c0
     2: LoadEmpty <this>
     4: StoreToScope <this>, 0, 0
     8: StoreToScope r0, 2, 0
    12: StoreToScope <closure>, 1, 0
    16: NewClosure r0, c1
    19: LoadFromScope r0, 0, 0
    23: CheckThisInitialized r0
    25: LoadFromScope r1, 0, 1
    29: GetNamedSuperProperty r0, r1, r0, c2
    34: LoadFromScope r0, 0, 0
    38: CheckThisInitialized r0
    40: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
    2: [String: x]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 1, 0
     4: GetSuperConstructor r0, r0
     7: LoadFromScope r1, 2, 0
    11: Construct r0, r0, r1, r1, 0
    17: LoadFromScope r1, 0, 0
    21: CheckSuperAlreadyCalled r1
    23: StoreToScope r0, 0, 0
    27: Ret r0
}

[BytecodeFunction: C3] {
  Parameters: 0, Registers: 1
    0: DefaultSuperCall 
    1: CheckThisInitialized <this>
    3: Ret <this>
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r1, 0, 0
     4: GetNamedSuperProperty r1, r1, <this>, c0
     9: NewClass r0, c2, c1, r1, r0
    15: LoadUndefined r1
    17: Ret r1
  Constant Table:
    0: [String: foo]
    1: [BytecodeFunction: Inner]
    2: [ClassNames]
}

[BytecodeFunction: Inner] {
  Parameters: 0, Registers: 1
    0: DefaultSuperCall 
    1: CheckThisInitialized <this>
    3: Ret <this>
}

[BytecodeFunction: C4] {
  Parameters: 0, Registers: 1
    0: DefaultSuperCall 
    1: CheckThisInitialized <this>
    3: Ret <this>
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 2
     0: PushFunctionScope c0
     2: StoreToScope <this>, 0, 0
     6: NewClosure r1, c1
     9: Call r1, r1, r1, 0
    14: NewClass r0, c3, c2, r1, r0
    20: LoadUndefined r1
    22: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
    2: [BytecodeFunction: Inner]
    3: [ClassNames]
}

[BytecodeFunction: Inner] {
  Parameters: 0, Registers: 1
    0: DefaultSuperCall 
    1: CheckThisInitialized <this>
    3: Ret <this>
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 0
     4: LoadFromScope r1, 0, 1
     8: GetNamedSuperProperty r0, r1, r0, c0
    13: Ret r0
  Constant Table:
    0: [String: foo]
}

[BytecodeFunction: C5] {
  Parameters: 0, Registers: 1
    0: DefaultSuperCall 
    1: CheckThisInitialized <this>
    3: Ret <this>
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r1, 0, 0
     4: GetNamedSuperProperty r1, r1, <this>, c0
     9: NewClass r0, c2, c1, r1, r0
    15: LoadUndefined r1
    17: Ret r1
  Constant Table:
    0: [String: foo]
    1: [BytecodeFunction: Inner]
    2: [ClassNames]
}

[BytecodeFunction: Inner] {
  Parameters: 0, Registers: 1
    0: DefaultSuperCall 
    1: CheckThisInitialized <this>
    3: Ret <this>
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r1, 0, 0
     4: GetNamedSuperProperty r1, r1, <this>, c0
     9: NewClass r0, c2, c1, r1, r0
    15: LoadUndefined r1
    17: Ret r1
  Constant Table:
    0: [String: foo]
    1: [BytecodeFunction: Inner]
    2: [ClassNames]
}

[BytecodeFunction: Inner] {
  Parameters: 0, Registers: 1
    0: DefaultSuperCall 
    1: CheckThisInitialized <this>
    3: Ret <this>
}
