[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: LoadUndefined r0
    38: Ret r0
  Constant Table:
    0: [BytecodeFunction: basicTryFinally]
    1: [String: basicTryFinally]
    2: [BytecodeFunction: basicTryCatchNoParamFinally]
    3: [String: basicTryCatchNoParamFinally]
    4: [BytecodeFunction: basicTryCatchWithSimpleParamFinally]
    5: [String: basicTryCatchWithSimpleParamFinally]
    6: [BytecodeFunction: basicTryCatchWithComplexParamFinally]
    7: [String: basicTryCatchWithComplexParamFinally]
    8: [BytecodeFunction: nested]
    9: [String: nested]
    10: [BytecodeFunction: allBranches]
    11: [String: allBranches]
}

[BytecodeFunction: basicTryFinally] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r0, 1
     3: Mov r2, <scope>
     6: LoadImmediate r3, 2
     9: LoadImmediate r0, 1
    12: Jump 5 (.L0)
    14: LoadImmediate r0, 0
  .L0:
    17: Mov <scope>, r2
    20: LoadImmediate r2, 3
    23: LoadImmediate r2, 0
    26: StrictEqual r2, r0, r2, ic0
    31: JumpFalse r2, 5 (.L1)
    34: Throw r1
  .L1:
    36: Jump 2 (.L2)
  .L2:
    38: LoadImmediate r0, 4
    41: LoadUndefined r0
    43: Ret r0
  Exception Handlers:
    6-9 -> 14 (r1)
}

[BytecodeFunction: basicTryCatchNoParamFinally] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r0, 1
     3: Mov r2, <scope>
     6: LoadImmediate r3, 2
     9: LoadImmediate r0, 1
    12: Jump 16 (.L0)
    14: Mov <scope>, r2
    17: LoadImmediate r3, 3
    20: LoadImmediate r0, 1
    23: Jump 5 (.L0)
    25: LoadImmediate r0, 0
  .L0:
    28: Mov <scope>, r2
    31: LoadImmediate r2, 4
    34: LoadImmediate r2, 0
    37: StrictEqual r2, r0, r2, ic0
    42: JumpFalse r2, 5 (.L1)
    45: Throw r1
  .L1:
    47: Jump 2 (.L2)
  .L2:
    49: LoadImmediate r0, 5
    52: LoadUndefined r0
    54: Ret r0
  Exception Handlers:
    6-9 -> 14
    14-20 -> 25 (r1)
}

[BytecodeFunction: basicTryCatchWithSimpleParamFinally] {
  Parameters: 0, Registers: 5
     0: LoadImmediate r1, 1
     3: Mov r3, <scope>
     6: LoadImmediate r4, 2
     9: LoadImmediate r1, 1
    12: Jump 16 (.L0)
    14: Mov <scope>, r3
    17: LoadImmediate r4, 3
    20: LoadImmediate r1, 1
    23: Jump 5 (.L0)
    25: LoadImmediate r1, 0
  .L0:
    28: Mov <scope>, r3
    31: LoadImmediate r3, 4
    34: LoadImmediate r3, 0
    37: StrictEqual r3, r1, r3, ic0
    42: JumpFalse r3, 5 (.L1)
    45: Throw r2
  .L1:
    47: Jump 2 (.L2)
  .L2:
    49: LoadImmediate r1, 5
    52: LoadUndefined r1
    54: Ret r1
  Exception Handlers:
    6-9 -> 14 (r0)
    14-20 -> 25 (r2)
}

[BytecodeFunction: basicTryCatchWithComplexParamFinally] {
  Parameters: 0, Registers: 5
     0: LoadImmediate r1, 1
     3: Mov r3, <scope>
     6: LoadImmediate r4, 2
     9: LoadImmediate r1, 1
    12: Jump 20 (.L0)
    14: Mov <scope>, r3
    17: GetNamedProperty r0, r4, c0
    21: LoadImmediate r4, 3
    24: LoadImmediate r1, 1
    27: Jump 5 (.L0)
    29: LoadImmediate r1, 0
  .L0:
    32: Mov <scope>, r3
    35: LoadImmediate r3, 4
    38: LoadImmediate r3, 0
    41: StrictEqual r3, r1, r3, ic0
    46: JumpFalse r3, 5 (.L1)
    49: Throw r2
  .L1:
    51: Jump 2 (.L2)
  .L2:
    53: LoadImmediate r1, 5
    56: LoadUndefined r1
    58: Ret r1
  Constant Table:
    0: [String: e]
  Exception Handlers:
    6-9 -> 14 (r4)
    14-24 -> 29 (r2)
}

[BytecodeFunction: nested] {
  Parameters: 0, Registers: 7
     0: LoadImmediate r0, 1
     3: Mov r2, <scope>
     6: LoadImmediate r3, 2
     9: Mov r5, <scope>
    12: LoadImmediate r6, 3
    15: LoadImmediate r3, 1
    18: Jump 5 (.L0)
    20: LoadImmediate r3, 0
  .L0:
    23: Mov <scope>, r5
    26: LoadImmediate r5, 4
    29: LoadImmediate r5, 0
    32: StrictEqual r5, r3, r5, ic0
    37: JumpFalse r5, 5 (.L1)
    40: Throw r4
  .L1:
    42: Jump 2 (.L2)
  .L2:
    44: LoadImmediate r0, 1
    47: Jump 5 (.L3)
    49: LoadImmediate r0, 0
  .L3:
    52: Mov <scope>, r2
    55: LoadImmediate r2, 5
    58: LoadImmediate r2, 0
    61: StrictEqual r2, r0, r2, ic1
    66: JumpFalse r2, 5 (.L4)
    69: Throw r1
  .L4:
    71: Jump 2 (.L5)
  .L5:
    73: LoadImmediate r0, 6
    76: LoadUndefined r0
    78: Ret r0
  Exception Handlers:
    12-15 -> 20 (r4)
    6-44 -> 49 (r1)
}

[BytecodeFunction: allBranches] {
  Parameters: 3, Registers: 4
  .L0:
      0: LoadTrue r0
      2: JumpFalse r0, 109 (.L10)
      5: Mov r2, <scope>
      8: JumpToBooleanFalse a0, 8 (.L1)
     11: LoadImmediate r0, 1
     14: Jump 32 (.L4)
  .L1:
     16: JumpToBooleanFalse a1, 8 (.L2)
     19: LoadImmediate r0, 2
     22: Jump 24 (.L4)
  .L2:
     24: JumpToBooleanFalse a2, 14 (.L3)
     27: LoadImmediate r3, 1
     30: LoadImmediate r0, 3
     33: Mov r1, r3
     36: Jump 10 (.L4)
  .L3:
     38: LoadImmediate r0, 4
     41: Jump 5 (.L4)
     43: LoadImmediate r0, 0
  .L4:
     46: Mov <scope>, r2
     49: LoadImmediate r2, 2
     52: LoadImmediate r2, 0
     55: StrictEqual r2, r0, r2, ic0
     60: JumpFalse r2, 5 (.L5)
     63: Throw r1
  .L5:
     65: LoadImmediate r2, 4
     68: StrictEqual r2, r0, r2, ic1
     73: JumpFalse r2, 5 (.L6)
     76: Jump 30 (.L9)
  .L6:
     78: LoadImmediate r2, 3
     81: StrictEqual r2, r0, r2, ic2
     86: JumpFalse r2, 5 (.L7)
     89: Ret r1
  .L7:
     91: LoadImmediate r2, 1
     94: StrictEqual r2, r0, r2, ic3
     99: JumpFalse r2, 5 (.L8)
    102: Jump 9 (.L10)
  .L8:
    104: Jump -104 (.L0)
  .L9:
    106: LoadImmediate r0, 3
    109: Jump -109 (.L0)
  .L10:
    111: LoadUndefined r0
    113: Ret r0
  Exception Handlers:
    8-38 -> 43 (r1)
}
