[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: LoadUndefined r0
    44: Ret r0
  Constant Table:
    0: [BytecodeFunction: breakInTry]
    1: [String: breakInTry]
    2: [BytecodeFunction: breakInCatch]
    3: [String: breakInCatch]
    4: [BytecodeFunction: breakInTryAndCatch]
    5: [String: breakInTryAndCatch]
    6: [BytecodeFunction: singleFinallyBreak]
    7: [String: singleFinallyBreak]
    8: [BytecodeFunction: unwindsBreak]
    9: [String: unwindsBreak]
    10: [BytecodeFunction: breakDoesNotLeaveFinally]
    11: [String: breakDoesNotLeaveFinally]
    12: [BytecodeFunction: leavesNested]
    13: [String: leavesNested]
}

[BytecodeFunction: breakInTry] {
  Parameters: 1, Registers: 3
  .L0:
     0: LoadTrue r0
     2: JumpFalse r0, 61 (.L6)
     5: Mov r2, <scope>
     8: JumpToBooleanFalse a0, 8 (.L1)
    11: LoadImmediate r0, 1
    14: Jump 10 (.L2)
  .L1:
    16: LoadImmediate r0, 2
    19: Jump 5 (.L2)
    21: LoadImmediate r0, 0
  .L2:
    24: Mov <scope>, r2
    27: LoadImmediate r2, 1
    30: LoadImmediate r2, 0
    33: StrictEqual r2, r0, r2, ic0
    38: JumpFalse r2, 5 (.L3)
    41: Throw r1
  .L3:
    43: LoadImmediate r2, 2
    46: StrictEqual r2, r0, r2, ic1
    51: JumpFalse r2, 5 (.L4)
    54: Jump 4 (.L5)
  .L4:
    56: Jump 7 (.L6)
  .L5:
    58: LoadImmediate r0, 2
    61: Jump -61 (.L0)
  .L6:
    63: LoadUndefined r0
    65: Ret r0
  Exception Handlers:
    8-16 -> 21 (r1)
}

[BytecodeFunction: breakInCatch] {
  Parameters: 1, Registers: 4
  .L0:
     0: LoadTrue r0
     2: JumpFalse r0, 72 (.L6)
     5: Mov r2, <scope>
     8: LoadImmediate r3, 1
    11: LoadImmediate r0, 1
    14: Jump 21 (.L2)
    16: Mov <scope>, r2
    19: JumpToBooleanFalse a0, 8 (.L1)
    22: LoadImmediate r0, 2
    25: Jump 10 (.L2)
  .L1:
    27: LoadImmediate r0, 1
    30: Jump 5 (.L2)
    32: LoadImmediate r0, 0
  .L2:
    35: Mov <scope>, r2
    38: LoadImmediate r2, 2
    41: LoadImmediate r2, 0
    44: StrictEqual r2, r0, r2, ic0
    49: JumpFalse r2, 5 (.L3)
    52: Throw r1
  .L3:
    54: LoadImmediate r2, 1
    57: StrictEqual r2, r0, r2, ic1
    62: JumpFalse r2, 5 (.L4)
    65: Jump 4 (.L5)
  .L4:
    67: Jump 7 (.L6)
  .L5:
    69: LoadImmediate r0, 3
    72: Jump -72 (.L0)
  .L6:
    74: LoadUndefined r0
    76: Ret r0
  Exception Handlers:
    8-11 -> 16
    16-27 -> 32 (r1)
}

[BytecodeFunction: breakInTryAndCatch] {
  Parameters: 2, Registers: 3
  .L0:
     0: LoadTrue r0
     2: JumpFalse r0, 77 (.L7)
     5: Mov r2, <scope>
     8: JumpToBooleanFalse a0, 8 (.L1)
    11: LoadImmediate r0, 1
    14: Jump 26 (.L3)
  .L1:
    16: LoadImmediate r0, 2
    19: Jump 21 (.L3)
    21: Mov <scope>, r2
    24: JumpToBooleanFalse a1, 8 (.L2)
    27: LoadImmediate r0, 1
    30: Jump 10 (.L3)
  .L2:
    32: LoadImmediate r0, 2
    35: Jump 5 (.L3)
    37: LoadImmediate r0, 0
  .L3:
    40: Mov <scope>, r2
    43: LoadImmediate r2, 1
    46: LoadImmediate r2, 0
    49: StrictEqual r2, r0, r2, ic0
    54: JumpFalse r2, 5 (.L4)
    57: Throw r1
  .L4:
    59: LoadImmediate r2, 2
    62: StrictEqual r2, r0, r2, ic1
    67: JumpFalse r2, 5 (.L5)
    70: Jump 4 (.L6)
  .L5:
    72: Jump 7 (.L7)
  .L6:
    74: LoadImmediate r0, 4
    77: Jump -77 (.L0)
  .L7:
    79: LoadUndefined r0
    81: Ret r0
  Exception Handlers:
    8-16 -> 21
    21-32 -> 37 (r1)
}

[BytecodeFunction: singleFinallyBreak] {
  Parameters: 1, Registers: 4
  .L0:
     0: LoadTrue r0
     2: JumpFalse r0, 56 (.L5)
     5: Mov r2, <scope>
     8: LoadImmediate r3, 1
    11: LoadImmediate r0, 1
    14: Jump 16 (.L1)
    16: Mov <scope>, r2
    19: LoadImmediate r3, 2
    22: LoadImmediate r0, 1
    25: Jump 5 (.L1)
    27: LoadImmediate r0, 0
  .L1:
    30: Mov <scope>, r2
    33: JumpToBooleanFalse a0, 5 (.L2)
    36: Jump 22 (.L5)
  .L2:
    38: LoadImmediate r2, 0
    41: StrictEqual r2, r0, r2, ic0
    46: JumpFalse r2, 5 (.L3)
    49: Throw r1
  .L3:
    51: Jump 2 (.L4)
  .L4:
    53: LoadImmediate r0, 5
    56: Jump -56 (.L0)
  .L5:
    58: LoadUndefined r0
    60: Ret r0
  Exception Handlers:
    8-11 -> 16
    16-22 -> 27 (r1)
}

[BytecodeFunction: unwindsBreak] {
  Parameters: 1, Registers: 5
  .L0:
      0: LoadTrue r1
      2: JumpFalse r1, 114 (.L6)
      5: PushLexicalScope c0
      7: LoadEmpty r1
      9: StoreToScope r1, 0, 0
     13: LoadImmediate r1, 1
     16: StoreToScope r1, 0, 0
     20: PushLexicalScope c1
     22: LoadEmpty r1
     24: StoreToScope r1, 0, 0
     28: LoadImmediate r1, 2
     31: StoreToScope r1, 0, 0
     35: Mov r3, <scope>
     38: PushLexicalScope c2
     40: LoadEmpty r4
     42: StoreToScope r4, 0, 0
     46: NewClosure r0, c3
     49: LoadImmediate r4, 3
     52: StoreToScope r4, 0, 0
     56: JumpToBooleanFalse a0, 8 (.L1)
     59: LoadImmediate r1, 1
     62: Jump 11 (.L2)
  .L1:
     64: PopScope 
     65: LoadImmediate r1, 2
     68: Jump 5 (.L2)
     70: LoadImmediate r1, 0
  .L2:
     73: Mov <scope>, r3
     76: LoadImmediate r3, 4
     79: LoadImmediate r3, 0
     82: StrictEqual r3, r1, r3, ic0
     87: JumpFalse r3, 5 (.L3)
     90: Throw r2
  .L3:
     92: LoadImmediate r3, 2
     95: StrictEqual r3, r1, r3, ic1
    100: JumpFalse r3, 5 (.L4)
    103: Jump 6 (.L5)
  .L4:
    105: PopScope 
    106: PopScope 
    107: Jump 9 (.L6)
  .L5:
    109: PopScope 
    110: LoadImmediate r1, 5
    113: PopScope 
    114: Jump -114 (.L0)
  .L6:
    116: LoadUndefined r1
    118: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
  Exception Handlers:
    38-65 -> 70 (r2)
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 1
    11: CheckTdz r1, c1
    14: Add r0, r0, r1, ic0
    19: LoadFromScope r1, 0, 0
    23: CheckTdz r1, c2
    26: Add r0, r0, r1, ic1
    31: Ret r0
  Constant Table:
    0: [String: s1]
    1: [String: s2]
    2: [String: s3]
}

[BytecodeFunction: breakDoesNotLeaveFinally] {
  Parameters: 1, Registers: 4
     0: Mov r2, <scope>
  .L0:
     3: LoadTrue r3
     5: JumpFalse r3, 13 (.L2)
     8: JumpToBooleanFalse a0, 5 (.L1)
    11: Jump 7 (.L2)
  .L1:
    13: LoadImmediate r3, 1
    16: Jump -13 (.L0)
  .L2:
    18: LoadImmediate r0, 1
    21: Jump 5 (.L3)
    23: LoadImmediate r0, 0
  .L3:
    26: Mov <scope>, r2
    29: LoadImmediate r2, 2
    32: LoadImmediate r2, 0
    35: StrictEqual r2, r0, r2, ic0
    40: JumpFalse r2, 5 (.L4)
    43: Throw r1
  .L4:
    45: Jump 2 (.L5)
  .L5:
    47: LoadUndefined r0
    49: Ret r0
  Exception Handlers:
    3-18 -> 23 (r1)
}

[BytecodeFunction: leavesNested] {
  Parameters: 1, Registers: 6
  .L0:
      0: LoadTrue r0
      2: JumpFalse r0, 119 (.L12)
      5: Mov r2, <scope>
  .L1:
      8: LoadTrue r3
     10: JumpFalse r3, 64 (.L7)
     13: Mov r5, <scope>
     16: JumpToBooleanFalse a0, 8 (.L2)
     19: LoadImmediate r3, 1
     22: Jump 10 (.L3)
  .L2:
     24: LoadImmediate r3, 2
     27: Jump 5 (.L3)
     29: LoadImmediate r3, 0
  .L3:
     32: Mov <scope>, r5
     35: LoadImmediate r5, 1
     38: LoadImmediate r5, 0
     41: StrictEqual r5, r3, r5, ic0
     46: JumpFalse r5, 5 (.L4)
     49: Throw r4
  .L4:
     51: LoadImmediate r5, 2
     54: StrictEqual r5, r3, r5, ic1
     59: JumpFalse r5, 5 (.L5)
     62: Jump 7 (.L6)
  .L5:
     64: LoadImmediate r0, 1
     67: Jump 15 (.L8)
  .L6:
     69: LoadImmediate r3, 2
     72: Jump -64 (.L1)
  .L7:
     74: LoadImmediate r0, 2
     77: Jump 5 (.L8)
     79: LoadImmediate r0, 0
  .L8:
     82: Mov <scope>, r2
     85: LoadImmediate r2, 3
     88: LoadImmediate r2, 0
     91: StrictEqual r2, r0, r2, ic2
     96: JumpFalse r2, 5 (.L9)
     99: Throw r1
  .L9:
    101: LoadImmediate r2, 2
    104: StrictEqual r2, r0, r2, ic3
    109: JumpFalse r2, 5 (.L10)
    112: Jump 4 (.L11)
  .L10:
    114: Jump 7 (.L12)
  .L11:
    116: LoadImmediate r0, 4
    119: Jump -119 (.L0)
  .L12:
    121: LoadUndefined r0
    123: Ret r0
  Exception Handlers:
    16-24 -> 29 (r4)
    8-74 -> 79 (r1)
}
