[CompiledRegExp: /abc/] {
  Flags: ""
  Match Start: Code Points("a")
  Required Literal: "abc" at 0-0
     0: MarkCapturePoint(0)
     2: OneByteStringLiteral("abc")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /foobar/] {
  Flags: ""
  Match Start: Code Points("f")
  Required Literal: "foobar" at 0-0
     0: MarkCapturePoint(0)
     2: OneByteStringLiteral("foobar")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /café123/] {
  Flags: ""
  Match Start: Code Points("c")
  Required Literal: "café123" at 0-0
     0: MarkCapturePoint(0)
     2: OneByteStringLiteral("café123")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /ab/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: OneByteStringLiteral("ab")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /abcdefghijklmnopqrstuvwxyz/] {
  Flags: ""
  Match Start: Code Points("a")
  Required Literal: "abcdefghijklmnop" at 0-0
     0: MarkCapturePoint(0)
     2: OneByteStringLiteral("abcdefghijklmnopqrstuvwxyz")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /abcdefghijklmnopqrstĀuvwxyz/] {
  Flags: ""
  Match Start: Code Points("a")
  Required Literal: "abcdefghijklmnop" at 0-0
     0: MarkCapturePoint(0)
     2: TwoByteStringLiteral("abcdefghijklmnopqrstĀuvwxyz")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /Āabcdefgh/] {
  Flags: ""
  Match Start: Code Points("Ā")
  Required Literal: "abcdefgh" at 1-1
     0: MarkCapturePoint(0)
     2: TwoByteStringLiteral("Āabcdefgh")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /abcĀdefgh/] {
  Flags: ""
  Match Start: Code Points("a")
  Required Literal: "defgh" at 4-4
     0: MarkCapturePoint(0)
     2: TwoByteStringLiteral("abcĀdefgh")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /abcdefĀghijkl/] {
  Flags: ""
  Match Start: Code Points("a")
  Required Literal: "abcdef" at 0-0
     0: MarkCapturePoint(0)
     2: TwoByteStringLiteral("abcdefĀghijkl")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /aĀĀbbbĀcccc/] {
  Flags: ""
  Match Start: Code Points("a")
  Required Literal: "cccc" at 7-7
     0: MarkCapturePoint(0)
     2: TwoByteStringLiteral("aĀĀbbbĀcccc")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /abĀcd/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: TwoByteStringLiteral("abĀcd")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /😀foobar/] {
  Flags: "u"
  Match Start: Code Points("😀")
  Required Literal: "foobar" at 1-1
     0: MarkCapturePoint(0)
     2: TwoByteStringLiteral("😀foobar")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /😀foobar/] {
  Flags: ""
  Match Start: Code Points("\uD83D")
  Required Literal: "foobar" at 2-2
     0: MarkCapturePoint(0)
     2: TwoByteStringLiteral("😀foobar")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /Āabcdefgh.*xyz/] {
  Flags: ""
  Match Start: Code Points("Ā")
  Required Literal: "abcdefgh" at 1-1
     0: MarkCapturePoint(0)
     2: TwoByteStringLiteral("Āabcdefgh")
     4: GreedyLoop(inverted, "\n", "\r", "\u{2028}"-"\u{2029}")
     6: OneByteStringLiteral("xyz")
     8: MarkCapturePoint(1)
    10: Accept
}

[CompiledRegExp: /Āabc.*uvwxyz/] {
  Flags: ""
  Match Start: Code Points("Ā")
  Required Literal: "uvwxyz" at 4-any
     0: MarkCapturePoint(0)
     2: TwoByteStringLiteral("Āabc")
     4: GreedyLoop(inverted, "\n", "\r", "\u{2028}"-"\u{2029}")
     6: OneByteStringLiteral("uvwxyz")
     8: MarkCapturePoint(1)
    10: Accept
}

[CompiledRegExp: /a(?:bcdef)g/] {
  Flags: ""
  Match Start: Code Points("a")
  Required Literal: "bcdef" at 1-1
     0: MarkCapturePoint(0)
     2: CodePointLiteral(a)
     3: OneByteStringLiteral("bcdef")
     5: CodePointLiteral(g)
     6: MarkCapturePoint(1)
     8: Accept
}

[CompiledRegExp: /abc.def.ghij/] {
  Flags: ""
  Match Start: Code Points("a")
  Required Literal: "ghij" at 8-8
     0: MarkCapturePoint(0)
     2: OneByteStringLiteral("abc")
     4: WildcardNoNewline
     5: OneByteStringLiteral("def")
     7: WildcardNoNewline
     8: OneByteStringLiteral("ghij")
    10: MarkCapturePoint(1)
    12: Accept
}

[CompiledRegExp: /(abc)+def/] {
  Flags: ""
  Match Start: Code Points("a")
  Required Literal: "abc" at 0-0
     0: MarkCapturePoint(0)
     2: MarkCapturePoint(2)
     4: OneByteStringLiteral("abc")
     6: MarkCapturePoint(3)
     8: Branch(11, 22)
    11: ClearCapture(1)
    13: MarkCapturePoint(2)
    15: OneByteStringLiteral("abc")
    17: MarkCapturePoint(3)
    19: Branch(11, 22)
    22: OneByteStringLiteral("def")
    24: MarkCapturePoint(1)
    26: Accept
}

[CompiledRegExp: /(abcd)+xy/] {
  Flags: ""
  Match Start: Code Points("a")
  Required Literal: "abcd" at 0-0
     0: MarkCapturePoint(0)
     2: MarkCapturePoint(2)
     4: OneByteStringLiteral("abcd")
     6: MarkCapturePoint(3)
     8: Branch(11, 22)
    11: ClearCapture(1)
    13: MarkCapturePoint(2)
    15: OneByteStringLiteral("abcd")
    17: MarkCapturePoint(3)
    19: Branch(11, 22)
    22: OneByteStringLiteral("xy")
    24: MarkCapturePoint(1)
    26: Accept
}

[CompiledRegExp: /(abcde)?xyz/] {
  Flags: ""
  Match Start: Code Points("a", "x")
  Required Literal: "xyz" at 0-5
     0: MarkCapturePoint(0)
     2: Branch(10, 5)
     5: OneByteStringLiteral("xyz")
     7: MarkCapturePoint(1)
     9: Accept
    10: MarkCapturePoint(2)
    12: OneByteStringLiteral("abcde")
    14: MarkCapturePoint(3)
    16: Jump(5)
}

[CompiledRegExp: /x{3}foobar/] {
  Flags: ""
  Match Start: Code Points("x")
  Required Literal: "foobar" at 3-3
     0: MarkCapturePoint(0)
     2: CodePointLiteral(x)
     3: CodePointLiteral(x)
     4: CodePointLiteral(x)
     5: OneByteStringLiteral("foobar")
     7: MarkCapturePoint(1)
     9: Accept
}

[CompiledRegExp: /x{2,5}foobar/] {
  Flags: ""
  Match Start: Code Points("x")
  Required Literal: "foobar" at 2-5
     0: MarkCapturePoint(0)
     2: CodePointLiteral(x)
     3: CodePointLiteral(x)
     4: Branch(12, 7)
     7: OneByteStringLiteral("foobar")
     9: MarkCapturePoint(1)
    11: Accept
    12: CodePointLiteral(x)
    13: Branch(16, 7)
    16: CodePointLiteral(x)
    17: Branch(20, 7)
    20: CodePointLiteral(x)
    21: Jump(7)
}

[CompiledRegExp: /x+foobar/] {
  Flags: ""
  Match Start: Code Points("x")
  Required Literal: "foobar" at 1-any
     0: MarkCapturePoint(0)
     2: CodePointLiteral(x)
     3: GreedyLoop("x")
     5: OneByteStringLiteral("foobar")
     7: MarkCapturePoint(1)
     9: Accept
}

[CompiledRegExp: /.*foobar/] {
  Flags: ""
  Match Start: Unknown
  Required Literal: "foobar" at 0-any
     0: MarkCapturePoint(0)
     2: GreedyLoop(inverted, "\n", "\r", "\u{2028}"-"\u{2029}")
     4: OneByteStringLiteral("foobar")
     6: MarkCapturePoint(1)
     8: Accept
}

[CompiledRegExp: /x{2,5}abĀvwxyz/] {
  Flags: ""
  Match Start: Code Points("x")
  Required Literal: "vwxyz" at 5-8
     0: MarkCapturePoint(0)
     2: CodePointLiteral(x)
     3: CodePointLiteral(x)
     4: Branch(12, 7)
     7: TwoByteStringLiteral("abĀvwxyz")
     9: MarkCapturePoint(1)
    11: Accept
    12: CodePointLiteral(x)
    13: Branch(16, 7)
    16: CodePointLiteral(x)
    17: Branch(20, 7)
    20: CodePointLiteral(x)
    21: Jump(7)
}

[CompiledRegExp: /[xy]foobar/] {
  Flags: ""
  Match Start: Code Points("x"-"y")
  Required Literal: "foobar" at 1-1
     0: MarkCapturePoint(0)
     2: CodePointSet("x"-"y")
     4: OneByteStringLiteral("foobar")
     6: MarkCapturePoint(1)
     8: Accept
}

[CompiledRegExp: /[xy]foobar/] {
  Flags: "v"
  Match Start: Code Points("x"-"y")
  Required Literal: "foobar" at 1-1
     0: MarkCapturePoint(0)
     2: CodePointSet("x"-"y")
     4: OneByteStringLiteral("foobar")
     6: MarkCapturePoint(1)
     8: Accept
}

[CompiledRegExp: /[xy\q{zz}]foobar/] {
  Flags: "v"
  Match Start: Code Points("x"-"z")
  Required Literal: "foobar" at 0-any
     0: MarkCapturePoint(0)
     2: Branch(10, 14)
     5: OneByteStringLiteral("foobar")
     7: MarkCapturePoint(1)
     9: Accept
    10: OneByteStringLiteral("zz")
    12: Jump(5)
    14: CodePointSet("x"-"y")
    16: Jump(5)
}

[CompiledRegExp: /\p{ASCII_Hex_Digit}foobar/] {
  Flags: "v"
  Match Start: Code Points("0"-"9", "A"-"F", "a"-"f")
  Required Literal: "foobar" at 1-1
     0: MarkCapturePoint(0)
     2: CodePointSet("0"-"9", "A"-"F", "a"-"f")
     4: OneByteStringLiteral("foobar")
     6: MarkCapturePoint(1)
     8: Accept
}

[CompiledRegExp: /\p{Emoji_Keycap_Sequence}foobar/] {
  Flags: "v"
  Match Start: Code Points("#", "*", "0"-"9")
  Required Literal: "foobar" at 0-any
     0: MarkCapturePoint(0)
     2: Branch(43, 10)
     5: OneByteStringLiteral("foobar")
     7: MarkCapturePoint(1)
     9: Accept
    10: Branch(47, 13)
    13: Branch(51, 16)
    16: Branch(55, 19)
    19: Branch(59, 22)
    22: Branch(63, 25)
    25: Branch(67, 28)
    28: Branch(71, 31)
    31: Branch(75, 34)
    34: Branch(79, 37)
    37: Branch(83, 40)
    40: Branch(87, 91)
    43: TwoByteStringLiteral("#️⃣")
    45: Jump(5)
    47: TwoByteStringLiteral("*️⃣")
    49: Jump(5)
    51: TwoByteStringLiteral("0️⃣")
    53: Jump(5)
    55: TwoByteStringLiteral("1️⃣")
    57: Jump(5)
    59: TwoByteStringLiteral("2️⃣")
    61: Jump(5)
    63: TwoByteStringLiteral("3️⃣")
    65: Jump(5)
    67: TwoByteStringLiteral("4️⃣")
    69: Jump(5)
    71: TwoByteStringLiteral("5️⃣")
    73: Jump(5)
    75: TwoByteStringLiteral("6️⃣")
    77: Jump(5)
    79: TwoByteStringLiteral("7️⃣")
    81: Jump(5)
    83: TwoByteStringLiteral("8️⃣")
    85: Jump(5)
    87: TwoByteStringLiteral("9️⃣")
    89: Jump(5)
    91: CodePointSet()
    93: Jump(5)
}

[CompiledRegExp: /.foobar/] {
  Flags: ""
  Match Start: Unknown
  Required Literal: "foobar" at 1-1
     0: MarkCapturePoint(0)
     2: WildcardNoNewline
     3: OneByteStringLiteral("foobar")
     5: MarkCapturePoint(1)
     7: Accept
}

[CompiledRegExp: /^foobar$/] {
  Flags: ""
  Match Start: Input Start
  Required Literal: "foobar" at 0-0
     0: MarkCapturePoint(0)
     2: AssertStart
     3: OneByteStringLiteral("foobar")
     5: AssertEnd
     6: MarkCapturePoint(1)
     8: Accept
}

[CompiledRegExp: /(?=abcdef)xyz/] {
  Flags: ""
  Match Start: Code Points("x")
  Required Literal: "xyz" at 0-0
     0: MarkCapturePoint(0)
     2: Lookaround(true, true, 9)
     4: OneByteStringLiteral("xyz")
     6: MarkCapturePoint(1)
     8: Accept
     9: OneByteStringLiteral("abcdef")
    11: Accept
}

[CompiledRegExp: /(\w{3})\1foobar/] {
  Flags: ""
  Match Start: Code Points("0"-"9", "A"-"Z", "_", "a"-"z")
  Required Literal: "foobar" at 3-any
     0: MarkCapturePoint(0)
     2: MarkCapturePoint(2)
     4: CodePointSet("0"-"9", "A"-"Z", "_", "a"-"z")
     6: CodePointSet("0"-"9", "A"-"Z", "_", "a"-"z")
     8: CodePointSet("0"-"9", "A"-"Z", "_", "a"-"z")
    10: MarkCapturePoint(3)
    12: Backreference(1, false)
    14: OneByteStringLiteral("foobar")
    16: MarkCapturePoint(1)
    18: Accept
}

[CompiledRegExp: /foobar|bazqux/] {
  Flags: ""
  Match Start: Code Points("b", "f")
     0: MarkCapturePoint(0)
     2: Branch(8, 12)
     5: MarkCapturePoint(1)
     7: Accept
     8: OneByteStringLiteral("foobar")
    10: Jump(5)
    12: OneByteStringLiteral("bazqux")
    14: Jump(5)
}

[CompiledRegExp: /(?:foo|bar)abcdef/] {
  Flags: ""
  Match Start: Code Points("b", "f")
  Required Literal: "abcdef" at 3-3
     0: MarkCapturePoint(0)
     2: Branch(10, 14)
     5: OneByteStringLiteral("abcdef")
     7: MarkCapturePoint(1)
     9: Accept
    10: OneByteStringLiteral("foo")
    12: Jump(5)
    14: OneByteStringLiteral("bar")
    16: Jump(5)
}

[CompiledRegExp: /(?:ab|cde)foobar/] {
  Flags: ""
  Match Start: Code Points("a", "c")
  Required Literal: "foobar" at 2-3
     0: MarkCapturePoint(0)
     2: Branch(10, 14)
     5: OneByteStringLiteral("foobar")
     7: MarkCapturePoint(1)
     9: Accept
    10: OneByteStringLiteral("ab")
    12: Jump(5)
    14: OneByteStringLiteral("cde")
    16: Jump(5)
}

[CompiledRegExp: /foobar/] {
  Flags: "i"
  Match Start: Code Points("F", "f")
     0: MarkCapturePoint(0)
     2: CodePointSet("F", "f")
     4: CodePointSet("O", "o")
     6: CodePointSet("O", "o")
     8: CodePointSet("B", "b")
    10: CodePointSet("A", "a")
    12: CodePointSet("R", "r")
    14: MarkCapturePoint(1)
    16: Accept
}

[CompiledRegExp: /123456/] {
  Flags: "i"
  Match Start: Code Points("1")
  Required Literal: "123456" at 0-0
     0: MarkCapturePoint(0)
     2: OneByteStringLiteral("123456")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /foo_123_bar/] {
  Flags: "i"
  Match Start: Code Points("F", "f")
  Required Literal: "_123_" at 3-3
     0: MarkCapturePoint(0)
     2: CodePointSet("F", "f")
     4: CodePointSet("O", "o")
     6: CodePointSet("O", "o")
     8: OneByteStringLiteral("_123_")
    10: CodePointSet("B", "b")
    12: CodePointSet("A", "a")
    14: CodePointSet("R", "r")
    16: MarkCapturePoint(1)
    18: Accept
}

[CompiledRegExp: /é12345/] {
  Flags: "i"
  Match Start: Code Points("É", "é")
  Required Literal: "12345" at 1-1
     0: MarkCapturePoint(0)
     2: CodePointSet("É", "é")
     4: OneByteStringLiteral("12345")
     6: MarkCapturePoint(1)
     8: Accept
}

[CompiledRegExp: /×12345/] {
  Flags: "i"
  Match Start: Code Points("×")
  Required Literal: "×12345" at 0-0
     0: MarkCapturePoint(0)
     2: OneByteStringLiteral("×12345")
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /(?i:foobar)xyz/] {
  Flags: ""
  Match Start: Code Points("F", "f")
  Required Literal: "xyz" at 6-6
     0: MarkCapturePoint(0)
     2: CodePointSet("F", "f")
     4: CodePointSet("O", "o")
     6: CodePointSet("O", "o")
     8: CodePointSet("B", "b")
    10: CodePointSet("A", "a")
    12: CodePointSet("R", "r")
    14: OneByteStringLiteral("xyz")
    16: MarkCapturePoint(1)
    18: Accept
}

[CompiledRegExp: /(?-i:foobar)xyz/] {
  Flags: "i"
  Match Start: Code Points("f")
  Required Literal: "foobar" at 0-0
     0: MarkCapturePoint(0)
     2: OneByteStringLiteral("foobar")
     4: CodePointSet("X", "x")
     6: CodePointSet("Y", "y")
     8: CodePointSet("Z", "z")
    10: MarkCapturePoint(1)
    12: Accept
}

[CompiledRegExp: /(?i:error404)xyz/] {
  Flags: ""
  Match Start: Code Points("E", "e")
  Required Literal: "404" at 5-5
     0: MarkCapturePoint(0)
     2: CodePointSet("E", "e")
     4: CodePointSet("R", "r")
     6: CodePointSet("R", "r")
     8: CodePointSet("O", "o")
    10: CodePointSet("R", "r")
    12: OneByteStringLiteral("404")
    14: OneByteStringLiteral("xyz")
    16: MarkCapturePoint(1)
    18: Accept
}

[CompiledRegExp: /\u0000\u0000\u0000/] {
  Flags: ""
  Match Start: Code Points("\x00")
  Required Literal: "\x00\x00\x00" at 0-0
     0: MarkCapturePoint(0)
     2: OneByteStringLiteral("\x00\x00\x00")
     4: MarkCapturePoint(1)
     6: Accept
}
