[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: LoadUndefined r0
    32: Ret r0
  Constant Table:
    0: [BytecodeFunction: f]
    1: [String: f]
    2: [BytecodeFunction: assignmentExpression]
    3: [String: assignmentExpression]
    4: [BytecodeFunction: updateExpression]
    5: [String: updateExpression]
    6: [BytecodeFunction: forInInitializer]
    7: [String: forInInitializer]
    8: [BytecodeFunction: forOfInitializer]
    9: [String: forOfInitializer]
}

[BytecodeFunction: f] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: assignmentExpression] {
  Parameters: 0, Registers: 1
     0: LoadGlobal r0, c0
     3: Call r0, r0, r0, 0
     8: ThrowNewError 0, c1
    11: LoadUndefined r0
    13: Ret r0
  Constant Table:
    0: [String: f]
    1: [String: cannot assign to call expression]
}

[BytecodeFunction: updateExpression] {
  Parameters: 0, Registers: 1
     0: LoadGlobal r0, c0
     3: Call r0, r0, r0, 0
     8: ThrowNewError 0, c1
    11: LoadGlobal r0, c0
    14: Call r0, r0, r0, 0
    19: ThrowNewError 0, c1
    22: LoadGlobal r0, c0
    25: Call r0, r0, r0, 0
    30: ThrowNewError 0, c1
    33: LoadGlobal r0, c0
    36: Call r0, r0, r0, 0
    41: ThrowNewError 0, c1
    44: LoadUndefined r0
    46: Ret r0
  Constant Table:
    0: [String: f]
    1: [String: cannot assign to call expression]
}

[BytecodeFunction: forInInitializer] {
  Parameters: 0, Registers: 3
     0: NewObject r0
     2: JumpNullish r0, 25 (.L1)
     5: NewForInIterator r0, r0
  .L0:
     8: ForInNext r1, r0
    11: JumpNullish r1, 16 (.L1)
    14: LoadGlobal r2, c0
    17: Call r2, r2, r2, 0
    22: ThrowNewError 0, c1
    25: Jump -17 (.L0)
  .L1:
    27: LoadUndefined r0
    29: Ret r0
  Constant Table:
    0: [String: f]
    1: [String: cannot assign to call expression]
}

[BytecodeFunction: forOfInitializer] {
  Parameters: 0, Registers: 5
     0: NewArray r2
     2: GetIterator r0, r1, r2
  .L0:
     6: IteratorNext r2, r3, r0, r1
    11: JumpTrue r3, 31 (.L2)
    14: LoadGlobal r3, c0
    17: Call r3, r3, r3, 0
    22: ThrowNewError 0, c1
    25: Mov r4, <scope>
    28: Jump 12 (.L1)
    30: LoadImmediate r2, 0
    33: Mov <scope>, r4
    36: IteratorClose r0
    38: Rethrow r3
  .L1:
    40: Jump -34 (.L0)
  .L2:
    42: LoadUndefined r0
    44: Ret r0
  Constant Table:
    0: [String: f]
    1: [String: cannot assign to call expression]
  Exception Handlers:
    14-28 -> 30 (r3)
    36-38 -> 38
}
