[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
      0: NewClosure r0, c0
      3: StoreGlobal r0, c1, k0
      7: NewClosure r0, c2
     10: StoreGlobal r0, c3, k1
     14: NewClosure r0, c4
     17: StoreGlobal r0, c5, k2
     21: NewClosure r0, c6
     24: StoreGlobal r0, c7, k3
     28: NewClosure r0, c8
     31: StoreGlobal r0, c9, k4
     35: NewClosure r0, c10
     38: StoreGlobal r0, c11, k5
     42: NewClosure r0, c12
     45: StoreGlobal r0, c13, k6
     49: NewClosure r0, c14
     52: StoreGlobal r0, c15, k7
     56: NewClosure r0, c16
     59: StoreGlobal r0, c17, k8
     63: NewClosure r0, c18
     66: StoreGlobal r0, c19, k9
     70: NewClosure r0, c20
     73: StoreGlobal r0, c21, k10
     77: NewClosure r0, c22
     80: StoreGlobal r0, c23, k11
     84: NewClosure r0, c24
     87: StoreGlobal r0, c25, k12
     91: NewClosure r0, c26
     94: StoreGlobal r0, c27, k13
     98: LoadUndefined r0
    100: Ret r0
  Constant Table:
    0: [BytecodeFunction: simpleAssignHazard]
    1: [String: simpleAssignHazard]
    2: [BytecodeFunction: inOuterExpr]
    3: [String: inOuterExpr]
    4: [BytecodeFunction: inRegularParam]
    5: [String: inRegularParam]
    6: [BytecodeFunction: inRestParam]
    7: [String: inRestParam]
    8: [BytecodeFunction: inVarDeclarator]
    9: [String: inVarDeclarator]
    10: [BytecodeFunction: inCatchParam]
    11: [String: inCatchParam]
    12: [BytecodeFunction: inForEachInit]
    13: [String: inForEachInit]
    14: [BytecodeFunction: toplevelAssignExpressions]
    15: [String: toplevelAssignExpressions]
    16: [BytecodeFunction: nestedFunctionOrClass]
    17: [String: nestedFunctionOrClass]
    18: [BytecodeFunction: prefixIncHazard]
    19: [String: prefixIncHazard]
    20: [BytecodeFunction: prefixDecHazard]
    21: [String: prefixDecHazard]
    22: [BytecodeFunction: postfixIncHazard]
    23: [String: postfixIncHazard]
    24: [BytecodeFunction: postfixDecHazard]
    25: [String: postfixDecHazard]
    26: [BytecodeFunction: toplevelUpdateExpressions]
    27: [String: toplevelUpdateExpressions]
}

[BytecodeFunction: simpleAssignHazard] {
  Parameters: 1, Registers: 1
     0: Mov r0, a0
     3: LoadImmediate a0, 2
     6: Add r0, r0, a0
    10: Ret r0
}

[BytecodeFunction: inOuterExpr] {
  Parameters: 1, Registers: 1
     0: Mov r0, a0
     3: LoadImmediate a0, 2
     6: Add r0, r0, a0
    10: JumpToBooleanFalse r0, 3 (.L0)
  .L0:
    13: LoadUndefined r0
    15: Ret r0
}

[BytecodeFunction: inRegularParam] {
  Parameters: 2, Registers: 1
     0: JumpNotUndefined a1, 13 (.L0)
     3: Mov r0, a0
     6: LoadImmediate a0, 2
     9: Add a1, r0, a0
  .L0:
    13: LoadUndefined r0
    15: Ret r0
}

[BytecodeFunction: inRestParam] {
  Parameters: 1, Registers: 3
     0: RestParameter r1
     2: Mov r2, a0
     5: LoadImmediate a0, 2
     8: Add r2, r2, a0
    12: GetProperty r0, r1, r2
    16: LoadUndefined r1
    18: Ret r1
}

[BytecodeFunction: inVarDeclarator] {
  Parameters: 1, Registers: 4
     0: NewObject r1
     2: GetNamedProperty r2, r1, c0, k0
     7: JumpNotUndefined r2, 13 (.L0)
    10: Mov r3, a0
    13: LoadImmediate a0, 2
    16: Add r2, r3, a0
  .L0:
    20: Mov r0, r2
    23: LoadUndefined r1
    25: Ret r1
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: inCatchParam] {
  Parameters: 1, Registers: 4
     0: Mov r1, <scope>
     3: LoadImmediate r2, 1
     6: Jump 22 (.L0)
     8: Mov <scope>, r1
    11: Mov r3, a0
    14: LoadImmediate a0, 2
    17: Add r3, r3, a0
    21: GetProperty r0, r2, r3
    25: LoadImmediate r2, 3
  .L0:
    28: LoadUndefined r1
    30: Ret r1
  Exception Handlers:
    3-6 -> 8 (r2)
}

[BytecodeFunction: inForEachInit] {
  Parameters: 2, Registers: 3
     0: NewObject r0
     2: JumpNullish r0, 28 (.L1)
     5: NewForInIterator r0, r0
  .L0:
     8: ForInNext r1, r0
    11: JumpNullish r1, 19 (.L1)
    14: Mov r2, a0
    17: LoadImmediate a0, 2
    20: Add r2, r2, a0
    24: GetProperty a1, r1, r2
    28: Jump -20 (.L0)
  .L1:
    30: LoadUndefined r0
    32: Ret r0
}

[BytecodeFunction: toplevelAssignExpressions] {
  Parameters: 2, Registers: 1
     0: LoadImmediate r0, 1
     3: Add a0, a0, r0
     7: Mov r0, a0
    10: LoadImmediate a0, 2
    13: Add a1, r0, a0
    17: LoadImmediate a0, 3
    20: Mov a1, a0
    23: LoadUndefined r0
    25: Ret r0
}

[BytecodeFunction: nestedFunctionOrClass] {
  Parameters: 2, Registers: 2
     0: NewClosure r0, c0
     3: Add a0, a1, r0
     7: NewClosure r0, c1
    10: Add a0, a1, r0
    14: NewObject r0
    16: NewClosure r1, c3
    19: DefineNamedProperty r0, c2, r1
    23: Add a0, a1, r0
    27: LoadUndefined r0
    29: Ret r0
  Constant Table:
    0: [BytecodeFunction: <anonymous>]
    1: [BytecodeFunction: <anonymous>]
    2: [String: f]
    3: [BytecodeFunction: f]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 1, Registers: 1
    0: LoadImmediate a0, 1
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 1, Registers: 1
    0: LoadImmediate a0, 2
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: f] {
  Parameters: 1, Registers: 1
    0: LoadImmediate a0, 3
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: prefixIncHazard] {
  Parameters: 1, Registers: 2
     0: Mov r0, a0
     3: Mov r1, a0
     6: ToNumeric r1, r1
     9: Inc r1
    11: Mov a0, r1
    14: Add r0, r0, r1
    18: Ret r0
}

[BytecodeFunction: prefixDecHazard] {
  Parameters: 1, Registers: 2
     0: Mov r0, a0
     3: Mov r1, a0
     6: ToNumeric r1, r1
     9: Dec r1
    11: Mov a0, r1
    14: Add r0, r0, r1
    18: Ret r0
}

[BytecodeFunction: postfixIncHazard] {
  Parameters: 1, Registers: 3
     0: Mov r0, a0
     3: Mov r2, a0
     6: ToNumeric r2, r2
     9: Mov r1, r2
    12: Inc r2
    14: Mov a0, r2
    17: Add r0, r0, r1
    21: Ret r0
}

[BytecodeFunction: postfixDecHazard] {
  Parameters: 1, Registers: 3
     0: Mov r0, a0
     3: Mov r2, a0
     6: ToNumeric r2, r2
     9: Mov r1, r2
    12: Dec r2
    14: Mov a0, r2
    17: Add r0, r0, r1
    21: Ret r0
}

[BytecodeFunction: toplevelUpdateExpressions] {
  Parameters: 2, Registers: 4
     0: ToNumeric a0, a0
     3: Mov r0, a0
     6: Inc a0
     8: Mov r1, a1
    11: Mov r3, a1
    14: ToNumeric r3, r3
    17: Mov r2, r3
    20: Inc r3
    22: Mov a1, r3
    25: GetProperty r0, r1, r2
    29: ToNumeric r0, r0
    32: Mov r3, r0
    35: Inc r3
    37: SetProperty r1, r2, r3
    41: LoadUndefined r0
    43: Ret r0
}
