[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
      0: NewClosure r0, c0
      3: StoreGlobal r0, c1, k0
      7: NewClosure r0, c2
     10: StoreGlobal r0, c3, k1
     14: NewClosure r0, c4
     17: StoreGlobal r0, c5, k2
     21: NewClosure r0, c6
     24: StoreGlobal r0, c7, k3
     28: NewClosure r0, c8
     31: StoreGlobal r0, c9, k4
     35: NewClosure r0, c10
     38: StoreGlobal r0, c11, k5
     42: NewClosure r0, c12
     45: StoreGlobal r0, c13, k6
     49: NewClosure r0, c14
     52: StoreGlobal r0, c15, k7
     56: NewClosure r0, c16
     59: StoreGlobal r0, c17, k8
     63: NewClosure r0, c18
     66: StoreGlobal r0, c19, k9
     70: NewClosure r0, c20
     73: StoreGlobal r0, c21, k10
     77: NewClosure r0, c22
     80: StoreGlobal r0, c23, k11
     84: NewClosure r0, c24
     87: StoreGlobal r0, c25, k12
     91: NewClosure r0, c26
     94: StoreGlobal r0, c27, k13
     98: NewClosure r0, c28
    101: StoreGlobal r0, c29, k14
    105: NewClosure r0, c30
    108: StoreGlobal r0, c31, k15
    112: NewClosure r0, c32
    115: StoreGlobal r0, c33, k16
    119: LoadUndefined r0
    121: Ret r0
  Constant Table:
    0: [BytecodeFunction: simpleAssignHazard]
    1: [String: simpleAssignHazard]
    2: [BytecodeFunction: inOuterExpr]
    3: [String: inOuterExpr]
    4: [BytecodeFunction: inRegularParam]
    5: [String: inRegularParam]
    6: [BytecodeFunction: inRestParam]
    7: [String: inRestParam]
    8: [BytecodeFunction: inVarDeclarator]
    9: [String: inVarDeclarator]
    10: [BytecodeFunction: inCatchParam]
    11: [String: inCatchParam]
    12: [BytecodeFunction: inForEachInit]
    13: [String: inForEachInit]
    14: [BytecodeFunction: toplevelAssignExpressions]
    15: [String: toplevelAssignExpressions]
    16: [BytecodeFunction: nestedFunctionOrClass]
    17: [String: nestedFunctionOrClass]
    18: [BytecodeFunction: prefixIncHazard]
    19: [String: prefixIncHazard]
    20: [BytecodeFunction: prefixDecHazard]
    21: [String: prefixDecHazard]
    22: [BytecodeFunction: postfixIncHazard]
    23: [String: postfixIncHazard]
    24: [BytecodeFunction: postfixDecHazard]
    25: [String: postfixDecHazard]
    26: [BytecodeFunction: toplevelUpdateExpressions]
    27: [String: toplevelUpdateExpressions]
    28: [BytecodeFunction: onlyReassignedBindingsAffected]
    29: [String: onlyReassignedBindingsAffected]
    30: [BytecodeFunction: classDeclarationExpressionHazard]
    31: [String: classDeclarationExpressionHazard]
    32: [BytecodeFunction: switchDiscriminantTestsHazard]
    33: [String: switchDiscriminantTestsHazard]
}

[BytecodeFunction: simpleAssignHazard] {
  Parameters: 1, Registers: 2
     0: Mov r0, a0
     3: LoadImmediate a0, 2
     6: Mov r1, a0
     9: Add r0, r0, r1
    13: Ret r0
}

[BytecodeFunction: inOuterExpr] {
  Parameters: 1, Registers: 2
     0: Mov r0, a0
     3: LoadImmediate a0, 2
     6: Mov r1, a0
     9: Add r0, r0, r1
    13: JumpToBooleanFalse r0, 3 (.L0)
  .L0:
    16: LoadUndefined r0
    18: Ret r0
}

[BytecodeFunction: inRegularParam] {
  Parameters: 2, Registers: 2
     0: JumpNotUndefined a1, 16 (.L0)
     3: Mov r0, a0
     6: LoadImmediate a0, 2
     9: Mov r1, a0
    12: Add a1, r0, r1
  .L0:
    16: LoadUndefined r0
    18: Ret r0
}

[BytecodeFunction: inRestParam] {
  Parameters: 1, Registers: 4
     0: RestParameter r1
     2: Mov r2, a0
     5: LoadImmediate a0, 2
     8: Mov r3, a0
    11: Add r2, r2, r3
    15: GetProperty r0, r1, r2
    19: LoadUndefined r1
    21: Ret r1
}

[BytecodeFunction: inVarDeclarator] {
  Parameters: 1, Registers: 5
     0: NewObject r1, 4
     3: GetNamedProperty r2, r1, c0, k0
     8: JumpNotUndefined r2, 16 (.L0)
    11: Mov r3, a0
    14: LoadImmediate a0, 2
    17: Mov r4, a0
    20: Add r2, r3, r4
  .L0:
    24: Mov r0, r2
    27: LoadUndefined r1
    29: Ret r1
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: inCatchParam] {
  Parameters: 1, Registers: 5
     0: Mov r1, <scope>
     3: LoadImmediate r2, 1
     6: Jump 25 (.L0)
     8: Mov <scope>, r1
    11: Mov r3, a0
    14: LoadImmediate a0, 2
    17: Mov r4, a0
    20: Add r3, r3, r4
    24: GetProperty r0, r2, r3
    28: LoadImmediate r2, 3
  .L0:
    31: LoadUndefined r1
    33: Ret r1
  Exception Handlers:
    3-6 -> 8 (r2)
}

[BytecodeFunction: inForEachInit] {
  Parameters: 2, Registers: 4
     0: NewObject r0, 4
     3: JumpNullish r0, 31 (.L1)
     6: NewForInIterator r0, r0
  .L0:
     9: ForInNext r1, r0
    12: JumpNullish r1, 22 (.L1)
    15: Mov r2, a0
    18: LoadImmediate a0, 2
    21: Mov r3, a0
    24: Add r2, r2, r3
    28: GetProperty a1, r1, r2
    32: Jump -23 (.L0)
  .L1:
    34: LoadUndefined r0
    36: Ret r0
}

[BytecodeFunction: toplevelAssignExpressions] {
  Parameters: 2, Registers: 2
     0: AddImm a0, a0, 1
     4: Mov r0, a0
     7: LoadImmediate a0, 2
    10: Mov r1, a0
    13: Add a1, r0, r1
    17: LoadImmediate a0, 3
    20: Mov a1, a0
    23: LoadUndefined r0
    25: Ret r0
}

[BytecodeFunction: nestedFunctionOrClass] {
  Parameters: 2, Registers: 2
     0: NewClosure r0, c0
     3: Add a0, a1, r0
     7: NewClosure r0, c1
    10: Add a0, a1, r0
    14: NewObject r0, 1
    17: NewClosure r1, c3
    20: DefineNamedProperty r0, c2, r1, k0
    25: Add a0, a1, r0
    29: LoadUndefined r0
    31: Ret r0
  Constant Table:
    0: [BytecodeFunction: <anonymous>]
    1: [BytecodeFunction: <anonymous>]
    2: [String: f]
    3: [BytecodeFunction: f]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 1, Registers: 1
    0: LoadImmediate a0, 1
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 1, Registers: 1
    0: LoadImmediate a0, 2
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: f] {
  Parameters: 1, Registers: 1
    0: LoadImmediate a0, 3
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: prefixIncHazard] {
  Parameters: 1, Registers: 2
     0: Mov r0, a0
     3: Inc a0
     5: Mov r1, a0
     8: Add r0, r0, r1
    12: Ret r0
}

[BytecodeFunction: prefixDecHazard] {
  Parameters: 1, Registers: 2
     0: Mov r0, a0
     3: Dec a0
     5: Mov r1, a0
     8: Add r0, r0, r1
    12: Ret r0
}

[BytecodeFunction: postfixIncHazard] {
  Parameters: 1, Registers: 2
     0: Mov r0, a0
     3: ToNumeric a0, a0
     6: Mov r1, a0
     9: Inc a0
    11: Add r0, r0, r1
    15: Ret r0
}

[BytecodeFunction: postfixDecHazard] {
  Parameters: 1, Registers: 2
     0: Mov r0, a0
     3: ToNumeric a0, a0
     6: Mov r1, a0
     9: Dec a0
    11: Add r0, r0, r1
    15: Ret r0
}

[BytecodeFunction: toplevelUpdateExpressions] {
  Parameters: 2, Registers: 3
     0: Inc a0
     2: Mov r1, a1
     5: ToNumeric a1, a1
     8: Mov r2, a1
    11: Inc a1
    13: GetProperty r0, r1, r2
    17: Inc r0
    19: SetProperty r1, r2, r0
    23: LoadUndefined r0
    25: Ret r0
}

[BytecodeFunction: onlyReassignedBindingsAffected] {
  Parameters: 4, Registers: 2
     0: LoadImmediate a0, 1
     3: LoadImmediate a1, 2
     6: Mov r0, a1
     9: Neg r0, r0
    12: Mov r0, a1
    15: Add r0, a0, r0
    19: Add r0, r0, a2
    23: Mov r1, a3
    26: Add r0, r0, r1
    30: LoadImmediate a3, 3
    33: Mov r1, a3
    36: Add r0, r0, r1
    40: LoadUndefined r0
    42: Ret r0
}

[BytecodeFunction: classDeclarationExpressionHazard] {
  Parameters: 1, Registers: 4
     0: Mov r1, a0
     3: LoadImmediate a0, 1
     6: Mov r2, a0
     9: ToPropertyKey r2, r2
    12: NewClosure r3, c0
    15: NewClass r0, c2, c1, r1, r2
    21: LoadUndefined r1
    23: Ret r1
  Constant Table:
    0: [BytecodeFunction: <anonymous>]
    1: [BytecodeFunction: C]
    2: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: DefaultSuperCall 
    1: CheckThisInitialized <this>
    3: Ret <this>
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: switchDiscriminantTestsHazard] {
  Parameters: 1, Registers: 2
     0: Mov r0, a0
     3: LoadImmediate a0, 1
     6: Mov r1, a0
     9: StrictEqual r1, r0, r1
    13: JumpTrue r1, 5 (.L0)
    16: Jump 5 (.L1)
  .L0:
    18: LoadImmediate r0, 2
  .L1:
    21: LoadUndefined r0
    23: Ret r0
}
