[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: NewClosure r0, c14
    45: StoreGlobal r0, c15
    48: LoadUndefined r0
    50: Ret r0
  Constant Table:
    0: [BytecodeFunction: named]
    1: [String: named]
    2: [BytecodeFunction: computed]
    3: [String: computed]
    4: [BytecodeFunction: noInitializer]
    5: [String: noInitializer]
    6: [BytecodeFunction: withConstructor]
    7: [String: withConstructor]
    8: [BytecodeFunction: withMethods]
    9: [String: withMethods]
    10: [BytecodeFunction: withCapturedName]
    11: [String: withCapturedName]
    12: [BytecodeFunction: withStaticInitializers]
    13: [String: withStaticInitializers]
    14: [BytecodeFunction: namedEvaluation]
    15: [String: namedEvaluation]
}

[BytecodeFunction: named] {
  Parameters: 0, Registers: 2
     0: NewClass r0, c1, c0, r0
     5: LoadImmediate r1, 3
     8: DefineNamedProperty r0, c2, r1
    12: LoadUndefined r1
    14: Ret r1
  Constant Table:
    0: [BytecodeFunction: C]
    1: [ClassNames]
    2: [String: named2]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 2
    3: DefineNamedProperty <this>, c0, r0
    7: LoadUndefined r0
    9: Ret r0
  Constant Table:
    0: [String: named1]
}

[BytecodeFunction: computed] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadImmediate r1, 1
     5: LoadImmediate r2, 2
     8: Add r1, r1, r2
    12: ToPropertyKey r1, r1
    15: StoreToScope r1, 0, 0
    19: LoadConstant r1, c1
    22: StoreToScope r1, 1, 0
    26: LoadImmediate r1, 3
    29: LoadImmediate r2, 4
    32: Add r1, r1, r2
    36: ToPropertyKey r1, r1
    39: StoreToScope r1, 2, 0
    43: LoadConstant r1, c2
    46: StoreToScope r1, 3, 0
    50: NewClass r0, c4, c3, r0
    55: LoadImmediate r1, 4
    58: LoadFromScope r2, 2, 0
    62: DefineProperty r0, r2, r1, 0
    67: LoadImmediate r1, 5
    70: LoadFromScope r2, 3, 0
    74: DefineProperty r0, r2, r1, 0
    79: PopScope 
    80: LoadUndefined r1
    82: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [Symbol: private1]
    2: [Symbol: private2]
    3: [BytecodeFunction: C]
    4: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 2
     3: LoadFromScope r1, 0, 0
     7: DefineProperty <this>, r1, r0, 0
    12: LoadImmediate r0, 3
    15: LoadFromScope r1, 1, 0
    19: DefineProperty <this>, r1, r0, 0
    24: LoadUndefined r0
    26: Ret r0
}

[BytecodeFunction: noInitializer] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadImmediate r1, 1
     5: LoadImmediate r2, 2
     8: Add r1, r1, r2
    12: ToPropertyKey r1, r1
    15: StoreToScope r1, 0, 0
    19: LoadConstant r1, c1
    22: StoreToScope r1, 1, 0
    26: LoadImmediate r1, 3
    29: LoadImmediate r2, 4
    32: Add r1, r1, r2
    36: ToPropertyKey r1, r1
    39: StoreToScope r1, 2, 0
    43: LoadConstant r1, c2
    46: StoreToScope r1, 3, 0
    50: NewClass r0, c4, c3, r0
    55: LoadUndefined r1
    57: DefineNamedProperty r0, c5, r1
    61: LoadUndefined r1
    63: LoadFromScope r2, 2, 0
    67: DefineProperty r0, r2, r1, 0
    72: LoadUndefined r1
    74: LoadFromScope r2, 3, 0
    78: DefineProperty r0, r2, r1, 0
    83: PopScope 
    84: LoadUndefined r1
    86: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [Symbol: private1]
    2: [Symbol: private2]
    3: [BytecodeFunction: C]
    4: [ClassNames]
    5: [String: named2]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadUndefined r0
     2: DefineNamedProperty <this>, c0, r0
     6: LoadUndefined r0
     8: LoadFromScope r1, 0, 0
    12: DefineProperty <this>, r1, r0, 0
    17: LoadUndefined r0
    19: LoadFromScope r1, 1, 0
    23: DefineProperty <this>, r1, r0, 0
    28: LoadUndefined r0
    30: Ret r0
  Constant Table:
    0: [String: named1]
}

[BytecodeFunction: withConstructor] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadImmediate r1, 1
     5: LoadImmediate r2, 2
     8: Add r1, r1, r2
    12: ToPropertyKey r1, r1
    15: StoreToScope r1, 0, 0
    19: NewClass r0, c2, c1, r0
    24: PopScope 
    25: LoadUndefined r1
    27: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: C]
    2: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: DefineNamedProperty <this>, c0, r0
     7: LoadImmediate r0, 2
    10: LoadFromScope r1, 0, 0
    14: DefineProperty <this>, r1, r0, 0
    19: PushFunctionScope c1
    21: LoadImmediate r0, 1
    24: StoreToScope r0, 0, 0
    28: NewClosure r0, c2
    31: LoadUndefined r0
    33: Ret r0
  Constant Table:
    0: [String: named]
    1: [ScopeNames]
    2: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: Ret r0
}

[BytecodeFunction: withMethods] {
  Parameters: 0, Registers: 6
     0: PushLexicalScope c0
     2: NewClosure r1, c1
     5: LoadImmediate r2, 1
     8: LoadImmediate r3, 2
    11: Add r2, r2, r3
    15: ToPropertyKey r2, r2
    18: StoreToScope r2, 0, 0
    22: LoadImmediate r2, 3
    25: LoadImmediate r3, 4
    28: Add r2, r2, r3
    32: ToPropertyKey r2, r2
    35: NewClosure r3, c2
    38: LoadConstant r4, c3
    41: StoreToScope r4, 1, 0
    45: LoadConstant r4, c4
    48: NewClosure r5, c5
    51: NewClass r0, c7, c6, r1
    56: PopScope 
    57: LoadUndefined r1
    59: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: namedMethod]
    2: [BytecodeFunction: <anonymous>]
    3: [Symbol: private1]
    4: [Symbol: private2]
    5: [BytecodeFunction: <anonymous>]
    6: [BytecodeFunction: C]
    7: [ClassNames]
}

[BytecodeFunction: namedMethod] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: DefineNamedProperty <this>, c0, r0
     7: LoadImmediate r0, 2
    10: LoadFromScope r1, 0, 0
    14: DefineProperty <this>, r1, r0, 0
    19: LoadImmediate r0, 3
    22: LoadFromScope r1, 1, 0
    26: DefineProperty <this>, r1, r0, 0
    31: LoadUndefined r0
    33: Ret r0
  Constant Table:
    0: [String: namedField]
}

[BytecodeFunction: withCapturedName] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 2, 0
     8: LoadImmediate r1, 1
    11: LoadImmediate r2, 2
    14: Add r1, r1, r2
    18: ToPropertyKey r1, r1
    21: StoreToScope r1, 0, 0
    25: LoadConstant r1, c1
    28: StoreToScope r1, 1, 0
    32: NewClosure r1, c2
    35: NewClass r0, c4, c3, r1
    40: StoreToScope r0, 2, 0
    44: PopScope 
    45: LoadUndefined r1
    47: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [Symbol: private1]
    2: [BytecodeFunction: method]
    3: [BytecodeFunction: C]
    4: [ClassNames]
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 2, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: C]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 2
     3: LoadFromScope r1, 0, 0
     7: DefineProperty <this>, r1, r0, 0
    12: LoadImmediate r0, 3
    15: LoadFromScope r1, 1, 0
    19: DefineProperty <this>, r1, r0, 0
    24: LoadUndefined r0
    26: Ret r0
}

[BytecodeFunction: withStaticInitializers] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadImmediate r1, 1
     5: LoadImmediate r2, 2
     8: Add r1, r1, r2
    12: ToPropertyKey r1, r1
    15: StoreToScope r1, 0, 0
    19: LoadConstant r1, c1
    22: StoreToScope r1, 1, 0
    26: NewClass r0, c3, c2, r0
    31: LoadImmediate r1, 2
    34: LoadFromScope r2, 0, 0
    38: DefineProperty r0, r2, r1, 0
    43: LoadImmediate r1, 3
    46: LoadImmediate r1, 4
    49: LoadFromScope r2, 1, 0
    53: DefineProperty r0, r2, r1, 0
    58: LoadImmediate r1, 5
    61: PopScope 
    62: LoadUndefined r1
    64: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [Symbol: private]
    2: [BytecodeFunction: C]
    3: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: namedEvaluation] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadImmediate r1, 1
     5: LoadImmediate r2, 2
     8: Add r1, r1, r2
    12: ToPropertyKey r1, r1
    15: StoreToScope r1, 0, 0
    19: LoadImmediate r1, 3
    22: LoadImmediate r2, 4
    25: Add r1, r1, r2
    29: ToPropertyKey r1, r1
    32: StoreToScope r1, 1, 0
    36: LoadConstant r1, c1
    39: StoreToScope r1, 2, 0
    43: LoadConstant r1, c2
    46: StoreToScope r1, 3, 0
    50: NewClass r0, c4, c3, r0
    55: NewClosure r1, c5
    58: DefineNamedProperty r0, c6, r1
    62: NewClosure r1, c7
    65: LoadFromScope r2, 1, 0
    69: DefineProperty r0, r2, r1, 1
    74: NewClosure r1, c8
    77: LoadFromScope r2, 3, 0
    81: DefineProperty r0, r2, r1, 1
    86: PopScope 
    87: LoadUndefined r1
    89: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [Symbol: private1]
    2: [Symbol: private2]
    3: [BytecodeFunction: C]
    4: [ClassNames]
    5: [BytecodeFunction: named2]
    6: [String: named2]
    7: [BytecodeFunction: <anonymous>]
    8: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: NewClosure r0, c0
     3: DefineNamedProperty <this>, c1, r0
     7: NewClosure r0, c2
    10: LoadFromScope r1, 0, 0
    14: DefineProperty <this>, r1, r0, 1
    19: NewClosure r0, c3
    22: LoadFromScope r1, 2, 0
    26: DefineProperty <this>, r1, r0, 1
    31: LoadUndefined r0
    33: Ret r0
  Constant Table:
    0: [BytecodeFunction: named1]
    1: [String: named1]
    2: [BytecodeFunction: <anonymous>]
    3: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: named1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: named2] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
