[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: NewClosure r0, c14
    45: StoreGlobal r0, c15
    48: NewClosure r0, c16
    51: StoreGlobal r0, c17
    54: NewClosure r0, c18
    57: StoreGlobal r0, c19
    60: NewClosure r0, c20
    63: StoreGlobal r0, c21
    66: NewClosure r0, c22
    69: StoreGlobal r0, c23
    72: LoadUndefined r0
    74: Ret r0
  Constant Table:
    0: [BytecodeFunction: named]
    1: [String: named]
    2: [BytecodeFunction: computed]
    3: [String: computed]
    4: [BytecodeFunction: private]
    5: [String: private]
    6: [BytecodeFunction: noInitializer]
    7: [String: noInitializer]
    8: [BytecodeFunction: withConstructor]
    9: [String: withConstructor]
    10: [BytecodeFunction: withImplicitDerivedConstructor]
    11: [String: withImplicitDerivedConstructor]
    12: [BytecodeFunction: withDerivedConstructor]
    13: [String: withDerivedConstructor]
    14: [BytecodeFunction: withMethods]
    15: [String: withMethods]
    16: [BytecodeFunction: withCapturedName]
    17: [String: withCapturedName]
    18: [BytecodeFunction: withStaticInitializers]
    19: [String: withStaticInitializers]
    20: [BytecodeFunction: namedEvaluation]
    21: [String: namedEvaluation]
    22: [BytecodeFunction: superMemberInFields]
    23: [String: superMemberInFields]
}

[BytecodeFunction: named] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r1
     2: NewClass r0, c1, c0, r1, r0
     8: LoadImmediate r2, 3
    11: DefineNamedProperty r0, c2, r2
    15: LoadUndefined r1
    17: Ret r1
  Constant Table:
    0: [BytecodeFunction: C]
    1: [ClassNames]
    2: [String: named2]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 2
    3: DefineNamedProperty <this>, c0, r0
    7: LoadUndefined r0
    9: Ret r0
  Constant Table:
    0: [String: named1]
}

[BytecodeFunction: computed] {
  Parameters: 0, Registers: 4
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: LoadImmediate r2, 1
     7: LoadImmediate r3, 2
    10: Add r2, r2, r3
    14: ToPropertyKey r2, r2
    17: StoreToScope r2, 0, 0
    21: LoadImmediate r2, 3
    24: LoadImmediate r3, 4
    27: Add r2, r2, r3
    31: ToPropertyKey r2, r2
    34: StoreToScope r2, 1, 0
    38: NewClass r0, c2, c1, r1, r0
    44: LoadImmediate r2, 4
    47: LoadFromScope r3, 1, 0
    51: DefineProperty r0, r3, r2, 0
    56: PopScope 
    57: LoadUndefined r1
    59: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: C]
    2: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 2
     3: LoadFromScope r1, 0, 0
     7: DefineProperty <this>, r1, r0, 0
    12: LoadUndefined r0
    14: Ret r0
}

[BytecodeFunction: private] {
  Parameters: 0, Registers: 4
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: NewPrivateSymbol r2, c1
     7: StoreToScope r2, 2, 0
    11: NewPrivateSymbol r2, c2
    14: StoreToScope r2, 3, 0
    18: NewClass r0, c4, c3, r1, r0
    24: LoadImmediate r2, 2
    27: LoadFromScope r3, 3, 0
    31: DefinePrivateProperty r0, r3, r2, 0
    36: PopScope 
    37: LoadUndefined r1
    39: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: private1]
    2: [String: private2]
    3: [BytecodeFunction: C]
    4: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadFromScope r1, 2, 0
     7: DefinePrivateProperty <this>, r1, r0, 0
    12: LoadUndefined r0
    14: Ret r0
}

[BytecodeFunction: noInitializer] {
  Parameters: 0, Registers: 4
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: NewPrivateSymbol r2, c1
     7: StoreToScope r2, 4, 0
    11: NewPrivateSymbol r2, c2
    14: StoreToScope r2, 5, 0
    18: LoadImmediate r2, 1
    21: LoadImmediate r3, 2
    24: Add r2, r2, r3
    28: ToPropertyKey r2, r2
    31: StoreToScope r2, 0, 0
    35: LoadImmediate r2, 3
    38: LoadImmediate r3, 4
    41: Add r2, r2, r3
    45: ToPropertyKey r2, r2
    48: StoreToScope r2, 1, 0
    52: NewClass r0, c4, c3, r1, r0
    58: LoadUndefined r2
    60: DefineNamedProperty r0, c5, r2
    64: LoadUndefined r2
    66: LoadFromScope r3, 1, 0
    70: DefineProperty r0, r3, r2, 0
    75: LoadUndefined r2
    77: LoadFromScope r3, 5, 0
    81: DefinePrivateProperty r0, r3, r2, 0
    86: PopScope 
    87: LoadUndefined r1
    89: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: private1]
    2: [String: private2]
    3: [BytecodeFunction: C]
    4: [ClassNames]
    5: [String: named2]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadUndefined r0
     2: DefineNamedProperty <this>, c0, r0
     6: LoadUndefined r0
     8: LoadFromScope r1, 0, 0
    12: DefineProperty <this>, r1, r0, 0
    17: LoadUndefined r0
    19: LoadFromScope r1, 4, 0
    23: DefinePrivateProperty <this>, r1, r0, 0
    28: LoadUndefined r0
    30: Ret r0
  Constant Table:
    0: [String: named1]
}

[BytecodeFunction: withConstructor] {
  Parameters: 0, Registers: 4
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: LoadImmediate r2, 1
     7: LoadImmediate r3, 2
    10: Add r2, r2, r3
    14: ToPropertyKey r2, r2
    17: StoreToScope r2, 0, 0
    21: NewClass r0, c2, c1, r1, r0
    27: PopScope 
    28: LoadUndefined r1
    30: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: C]
    2: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: DefineNamedProperty <this>, c0, r0
     7: LoadImmediate r0, 2
    10: LoadFromScope r1, 0, 0
    14: DefineProperty <this>, r1, r0, 0
    19: PushFunctionScope c1
    21: LoadImmediate r0, 1
    24: StoreToScope r0, 0, 0
    28: NewClosure r0, c2
    31: LoadUndefined r0
    33: Ret r0
  Constant Table:
    0: [String: named]
    1: [ScopeNames]
    2: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: Ret r0
}

[BytecodeFunction: withImplicitDerivedConstructor] {
  Parameters: 0, Registers: 2
     0: LoadGlobal r1, c0
     3: NewClass r0, c2, c1, r1, r0
     9: LoadUndefined r1
    11: Ret r1
  Constant Table:
    0: [String: String]
    1: [BytecodeFunction: C]
    2: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: DefaultSuperCall 
     1: LoadImmediate r1, 1
     4: DefineNamedProperty <this>, c0, r1
     8: CheckThisInitialized <this>
    10: Ret <this>
  Constant Table:
    0: [String: named]
}

[BytecodeFunction: withDerivedConstructor] {
  Parameters: 0, Registers: 2
     0: LoadGlobal r1, c0
     3: NewClass r0, c2, c1, r1, r0
     9: LoadUndefined r1
    11: Ret r1
  Constant Table:
    0: [String: String]
    1: [BytecodeFunction: C]
    2: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 4
     0: LoadEmpty <this>
     2: Mov r0, <closure>
     5: LoadImmediate r2, 2
     8: GetSuperConstructor r2, r0
    11: Construct r2, r2, r1, r1, 0
    17: CheckSuperAlreadyCalled <this>
    19: Mov <this>, r2
    22: LoadImmediate r3, 1
    25: DefineNamedProperty <this>, c0, r3
    29: LoadImmediate r2, 3
    32: CheckThisInitialized <this>
    34: Ret <this>
  Constant Table:
    0: [String: named]
}

[BytecodeFunction: withMethods] {
  Parameters: 0, Registers: 6
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: NewPrivateSymbol r2, c1
     7: StoreToScope r2, 3, 0
    11: NewPrivateSymbol r2, c2
    14: StoreToScope r2, 4, 0
    18: NewClosure r2, c3
    21: LoadImmediate r3, 1
    24: LoadImmediate r4, 2
    27: Add r3, r3, r4
    31: ToPropertyKey r3, r3
    34: StoreToScope r3, 0, 0
    38: LoadImmediate r3, 3
    41: LoadImmediate r4, 4
    44: Add r3, r3, r4
    48: ToPropertyKey r3, r3
    51: NewClosure r4, c4
    54: NewClosure r5, c5
    57: StoreToScope r5, 1, 0
    61: NewClass r0, c7, c6, r1, r2
    67: PopScope 
    68: LoadUndefined r1
    70: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: private1]
    2: [String: private2]
    3: [BytecodeFunction: namedMethod]
    4: [BytecodeFunction: <anonymous>]
    5: [BytecodeFunction: #private2]
    6: [BytecodeFunction: C]
    7: [ClassNames]
}

[BytecodeFunction: namedMethod] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: #private2] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 4, 0
     4: LoadFromScope r1, 1, 0
     8: DefinePrivateProperty <this>, r0, r1, 1
    13: LoadImmediate r0, 1
    16: DefineNamedProperty <this>, c0, r0
    20: LoadImmediate r0, 2
    23: LoadFromScope r1, 0, 0
    27: DefineProperty <this>, r1, r0, 0
    32: LoadImmediate r0, 3
    35: LoadFromScope r1, 3, 0
    39: DefinePrivateProperty <this>, r1, r0, 0
    44: LoadUndefined r0
    46: Ret r0
  Constant Table:
    0: [String: namedField]
}

[BytecodeFunction: withCapturedName] {
  Parameters: 0, Registers: 4
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 2, 0
     8: LoadEmpty r1
    10: NewPrivateSymbol r2, c1
    13: StoreToScope r2, 3, 0
    17: LoadImmediate r2, 1
    20: LoadImmediate r3, 2
    23: Add r2, r2, r3
    27: ToPropertyKey r2, r2
    30: StoreToScope r2, 0, 0
    34: NewClosure r2, c2
    37: StoreToScope r2, 1, 0
    41: NewClosure r2, c3
    44: NewClass r0, c5, c4, r1, r2
    50: StoreToScope r0, 2, 0
    54: PopScope 
    55: LoadUndefined r1
    57: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: private1]
    2: [BytecodeFunction: #private1]
    3: [BytecodeFunction: method]
    4: [BytecodeFunction: C]
    5: [ClassNames]
}

[BytecodeFunction: #private1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 2, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: C]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 3, 0
     4: LoadFromScope r1, 1, 0
     8: DefinePrivateProperty <this>, r0, r1, 1
    13: LoadImmediate r0, 2
    16: LoadFromScope r1, 0, 0
    20: DefineProperty <this>, r1, r0, 0
    25: LoadUndefined r0
    27: Ret r0
}

[BytecodeFunction: withStaticInitializers] {
  Parameters: 0, Registers: 4
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: NewPrivateSymbol r2, c1
     7: StoreToScope r2, 2, 0
    11: LoadImmediate r2, 1
    14: LoadImmediate r3, 2
    17: Add r2, r2, r3
    21: ToPropertyKey r2, r2
    24: StoreToScope r2, 0, 0
    28: NewClass r0, c3, c2, r1, r0
    34: LoadImmediate r2, 2
    37: LoadFromScope r3, 0, 0
    41: DefineProperty r0, r3, r2, 0
    46: LoadImmediate r2, 3
    49: LoadImmediate r2, 4
    52: LoadFromScope r3, 2, 0
    56: DefinePrivateProperty r0, r3, r2, 0
    61: LoadImmediate r2, 5
    64: PopScope 
    65: LoadUndefined r1
    67: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: private]
    2: [BytecodeFunction: C]
    3: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: namedEvaluation] {
  Parameters: 0, Registers: 4
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: NewPrivateSymbol r2, c1
     7: StoreToScope r2, 4, 0
    11: NewPrivateSymbol r2, c2
    14: StoreToScope r2, 5, 0
    18: LoadImmediate r2, 1
    21: LoadImmediate r3, 2
    24: Add r2, r2, r3
    28: ToPropertyKey r2, r2
    31: StoreToScope r2, 0, 0
    35: LoadImmediate r2, 3
    38: LoadImmediate r3, 4
    41: Add r2, r2, r3
    45: ToPropertyKey r2, r2
    48: StoreToScope r2, 1, 0
    52: NewClass r0, c4, c3, r1, r0
    58: NewClosure r2, c5
    61: DefineNamedProperty r0, c6, r2
    65: NewClosure r2, c7
    68: LoadFromScope r3, 1, 0
    72: DefineProperty r0, r3, r2, 1
    77: NewClosure r2, c8
    80: LoadFromScope r3, 5, 0
    84: DefinePrivateProperty r0, r3, r2, 0
    89: PopScope 
    90: LoadUndefined r1
    92: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: private1]
    2: [String: private2]
    3: [BytecodeFunction: C]
    4: [ClassNames]
    5: [BytecodeFunction: named2]
    6: [String: named2]
    7: [BytecodeFunction: <anonymous>]
    8: [BytecodeFunction: #private2]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: NewClosure r0, c0
     3: DefineNamedProperty <this>, c1, r0
     7: NewClosure r0, c2
    10: LoadFromScope r1, 0, 0
    14: DefineProperty <this>, r1, r0, 1
    19: NewClosure r0, c3
    22: LoadFromScope r1, 4, 0
    26: DefinePrivateProperty <this>, r1, r0, 0
    31: LoadUndefined r0
    33: Ret r0
  Constant Table:
    0: [BytecodeFunction: named1]
    1: [String: named1]
    2: [BytecodeFunction: <anonymous>]
    3: [BytecodeFunction: #private1]
}

[BytecodeFunction: named1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: #private1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: named2] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: #private2] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: superMemberInFields] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: NewClass r0, c2, c1, r1, r0
    10: LoadFromScope r2, 1, 0
    14: GetNamedSuperProperty r2, r2, <this>, c3
    19: DefineNamedProperty r0, c4, r2
    23: PopScope 
    24: LoadUndefined r1
    26: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: C]
    2: [ClassNames]
    3: [String: foo]
    4: [String: field2]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
     0: LoadFromScope r0, 0, 0
     4: GetNamedSuperProperty r0, r0, <this>, c0
     9: DefineNamedProperty <this>, c1, r0
    13: LoadUndefined r0
    15: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: field1]
}
