[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: NewClosure r0, c14
    45: StoreGlobal r0, c15
    48: LoadUndefined r0
    50: Ret r0
  Constant Table:
    0: [BytecodeFunction: named]
    1: [String: named]
    2: [BytecodeFunction: computed]
    3: [String: computed]
    4: [BytecodeFunction: noInitializer]
    5: [String: noInitializer]
    6: [BytecodeFunction: withConstructor]
    7: [String: withConstructor]
    8: [BytecodeFunction: withMethods]
    9: [String: withMethods]
    10: [BytecodeFunction: withCapturedName]
    11: [String: withCapturedName]
    12: [BytecodeFunction: withStaticInitializers]
    13: [String: withStaticInitializers]
    14: [BytecodeFunction: namedEvaluation]
    15: [String: namedEvaluation]
}

[BytecodeFunction: named] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r1
     2: NewClass r0, c1, c0, r1, r0
     8: LoadImmediate r2, 3
    11: DefineNamedProperty r0, c2, r2
    15: LoadUndefined r1
    17: Ret r1
  Constant Table:
    0: [BytecodeFunction: C]
    1: [ClassNames]
    2: [String: named2]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 2
    3: DefineNamedProperty <this>, c0, r0
    7: LoadUndefined r0
    9: Ret r0
  Constant Table:
    0: [String: named1]
}

[BytecodeFunction: computed] {
  Parameters: 0, Registers: 4
     0: LoadEmpty r1
     2: PushLexicalScope c0
     4: LoadImmediate r2, 1
     7: LoadImmediate r3, 2
    10: Add r2, r2, r3
    14: ToPropertyKey r2, r2
    17: StoreToScope r2, 0, 0
    21: LoadConstant r2, c1
    24: StoreToScope r2, 1, 0
    28: LoadImmediate r2, 3
    31: LoadImmediate r3, 4
    34: Add r2, r2, r3
    38: ToPropertyKey r2, r2
    41: StoreToScope r2, 2, 0
    45: LoadConstant r2, c2
    48: StoreToScope r2, 3, 0
    52: NewClass r0, c4, c3, r1, r0
    58: LoadImmediate r2, 4
    61: LoadFromScope r3, 2, 0
    65: DefineProperty r0, r3, r2, 0
    70: LoadImmediate r2, 5
    73: LoadFromScope r3, 3, 0
    77: DefineProperty r0, r3, r2, 0
    82: PopScope 
    83: LoadUndefined r1
    85: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [Symbol: private1]
    2: [Symbol: private2]
    3: [BytecodeFunction: C]
    4: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 2
     3: LoadFromScope r1, 0, 0
     7: DefineProperty <this>, r1, r0, 0
    12: LoadImmediate r0, 3
    15: LoadFromScope r1, 1, 0
    19: DefineProperty <this>, r1, r0, 0
    24: LoadUndefined r0
    26: Ret r0
}

[BytecodeFunction: noInitializer] {
  Parameters: 0, Registers: 4
     0: LoadEmpty r1
     2: PushLexicalScope c0
     4: LoadImmediate r2, 1
     7: LoadImmediate r3, 2
    10: Add r2, r2, r3
    14: ToPropertyKey r2, r2
    17: StoreToScope r2, 0, 0
    21: LoadConstant r2, c1
    24: StoreToScope r2, 1, 0
    28: LoadImmediate r2, 3
    31: LoadImmediate r3, 4
    34: Add r2, r2, r3
    38: ToPropertyKey r2, r2
    41: StoreToScope r2, 2, 0
    45: LoadConstant r2, c2
    48: StoreToScope r2, 3, 0
    52: NewClass r0, c4, c3, r1, r0
    58: LoadUndefined r2
    60: DefineNamedProperty r0, c5, r2
    64: LoadUndefined r2
    66: LoadFromScope r3, 2, 0
    70: DefineProperty r0, r3, r2, 0
    75: LoadUndefined r2
    77: LoadFromScope r3, 3, 0
    81: DefineProperty r0, r3, r2, 0
    86: PopScope 
    87: LoadUndefined r1
    89: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [Symbol: private1]
    2: [Symbol: private2]
    3: [BytecodeFunction: C]
    4: [ClassNames]
    5: [String: named2]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadUndefined r0
     2: DefineNamedProperty <this>, c0, r0
     6: LoadUndefined r0
     8: LoadFromScope r1, 0, 0
    12: DefineProperty <this>, r1, r0, 0
    17: LoadUndefined r0
    19: LoadFromScope r1, 1, 0
    23: DefineProperty <this>, r1, r0, 0
    28: LoadUndefined r0
    30: Ret r0
  Constant Table:
    0: [String: named1]
}

[BytecodeFunction: withConstructor] {
  Parameters: 0, Registers: 4
     0: LoadEmpty r1
     2: PushLexicalScope c0
     4: LoadImmediate r2, 1
     7: LoadImmediate r3, 2
    10: Add r2, r2, r3
    14: ToPropertyKey r2, r2
    17: StoreToScope r2, 0, 0
    21: NewClass r0, c2, c1, r1, r0
    27: PopScope 
    28: LoadUndefined r1
    30: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: C]
    2: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: DefineNamedProperty <this>, c0, r0
     7: LoadImmediate r0, 2
    10: LoadFromScope r1, 0, 0
    14: DefineProperty <this>, r1, r0, 0
    19: PushFunctionScope c1
    21: LoadImmediate r0, 1
    24: StoreToScope r0, 0, 0
    28: NewClosure r0, c2
    31: LoadUndefined r0
    33: Ret r0
  Constant Table:
    0: [String: named]
    1: [ScopeNames]
    2: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: Ret r0
}

[BytecodeFunction: withMethods] {
  Parameters: 0, Registers: 7
     0: LoadEmpty r1
     2: PushLexicalScope c0
     4: NewClosure r2, c1
     7: LoadImmediate r3, 1
    10: LoadImmediate r4, 2
    13: Add r3, r3, r4
    17: ToPropertyKey r3, r3
    20: StoreToScope r3, 0, 0
    24: LoadImmediate r3, 3
    27: LoadImmediate r4, 4
    30: Add r3, r3, r4
    34: ToPropertyKey r3, r3
    37: NewClosure r4, c2
    40: LoadConstant r5, c3
    43: StoreToScope r5, 1, 0
    47: LoadConstant r5, c4
    50: NewClosure r6, c5
    53: NewClass r0, c7, c6, r1, r2
    59: PopScope 
    60: LoadUndefined r1
    62: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: namedMethod]
    2: [BytecodeFunction: <anonymous>]
    3: [Symbol: private1]
    4: [Symbol: private2]
    5: [BytecodeFunction: <anonymous>]
    6: [BytecodeFunction: C]
    7: [ClassNames]
}

[BytecodeFunction: namedMethod] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: DefineNamedProperty <this>, c0, r0
     7: LoadImmediate r0, 2
    10: LoadFromScope r1, 0, 0
    14: DefineProperty <this>, r1, r0, 0
    19: LoadImmediate r0, 3
    22: LoadFromScope r1, 1, 0
    26: DefineProperty <this>, r1, r0, 0
    31: LoadUndefined r0
    33: Ret r0
  Constant Table:
    0: [String: namedField]
}

[BytecodeFunction: withCapturedName] {
  Parameters: 0, Registers: 4
     0: LoadEmpty r1
     2: PushLexicalScope c0
     4: LoadEmpty r2
     6: StoreToScope r2, 2, 0
    10: LoadImmediate r2, 1
    13: LoadImmediate r3, 2
    16: Add r2, r2, r3
    20: ToPropertyKey r2, r2
    23: StoreToScope r2, 0, 0
    27: LoadConstant r2, c1
    30: StoreToScope r2, 1, 0
    34: NewClosure r2, c2
    37: NewClass r0, c4, c3, r1, r2
    43: StoreToScope r0, 2, 0
    47: PopScope 
    48: LoadUndefined r1
    50: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [Symbol: private1]
    2: [BytecodeFunction: method]
    3: [BytecodeFunction: C]
    4: [ClassNames]
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 2, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: C]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 2
     3: LoadFromScope r1, 0, 0
     7: DefineProperty <this>, r1, r0, 0
    12: LoadImmediate r0, 3
    15: LoadFromScope r1, 1, 0
    19: DefineProperty <this>, r1, r0, 0
    24: LoadUndefined r0
    26: Ret r0
}

[BytecodeFunction: withStaticInitializers] {
  Parameters: 0, Registers: 4
     0: LoadEmpty r1
     2: PushLexicalScope c0
     4: LoadImmediate r2, 1
     7: LoadImmediate r3, 2
    10: Add r2, r2, r3
    14: ToPropertyKey r2, r2
    17: StoreToScope r2, 0, 0
    21: LoadConstant r2, c1
    24: StoreToScope r2, 1, 0
    28: NewClass r0, c3, c2, r1, r0
    34: LoadImmediate r2, 2
    37: LoadFromScope r3, 0, 0
    41: DefineProperty r0, r3, r2, 0
    46: LoadImmediate r2, 3
    49: LoadImmediate r2, 4
    52: LoadFromScope r3, 1, 0
    56: DefineProperty r0, r3, r2, 0
    61: LoadImmediate r2, 5
    64: PopScope 
    65: LoadUndefined r1
    67: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [Symbol: private]
    2: [BytecodeFunction: C]
    3: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: namedEvaluation] {
  Parameters: 0, Registers: 4
     0: LoadEmpty r1
     2: PushLexicalScope c0
     4: LoadImmediate r2, 1
     7: LoadImmediate r3, 2
    10: Add r2, r2, r3
    14: ToPropertyKey r2, r2
    17: StoreToScope r2, 0, 0
    21: LoadImmediate r2, 3
    24: LoadImmediate r3, 4
    27: Add r2, r2, r3
    31: ToPropertyKey r2, r2
    34: StoreToScope r2, 1, 0
    38: LoadConstant r2, c1
    41: StoreToScope r2, 2, 0
    45: LoadConstant r2, c2
    48: StoreToScope r2, 3, 0
    52: NewClass r0, c4, c3, r1, r0
    58: NewClosure r2, c5
    61: DefineNamedProperty r0, c6, r2
    65: NewClosure r2, c7
    68: LoadFromScope r3, 1, 0
    72: DefineProperty r0, r3, r2, 1
    77: NewClosure r2, c8
    80: LoadFromScope r3, 3, 0
    84: DefineProperty r0, r3, r2, 1
    89: PopScope 
    90: LoadUndefined r1
    92: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [Symbol: private1]
    2: [Symbol: private2]
    3: [BytecodeFunction: C]
    4: [ClassNames]
    5: [BytecodeFunction: named2]
    6: [String: named2]
    7: [BytecodeFunction: <anonymous>]
    8: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 2
     0: NewClosure r0, c0
     3: DefineNamedProperty <this>, c1, r0
     7: NewClosure r0, c2
    10: LoadFromScope r1, 0, 0
    14: DefineProperty <this>, r1, r0, 1
    19: NewClosure r0, c3
    22: LoadFromScope r1, 2, 0
    26: DefineProperty <this>, r1, r0, 1
    31: LoadUndefined r0
    33: Ret r0
  Constant Table:
    0: [BytecodeFunction: named1]
    1: [String: named1]
    2: [BytecodeFunction: <anonymous>]
    3: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: named1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: named2] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
