[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 21
      0: LoadEmpty r1
      2: NewClosure r2, c0
      5: NewClosure r3, c1
      8: LoadImmediate r4, 1
     11: ToPropertyKey r4, r4
     14: NewClosure r5, c2
     17: LoadConstant r6, c3
     20: ToPropertyKey r6, r6
     23: NewClosure r7, c4
     26: LoadImmediate r8, 1
     29: LoadImmediate r9, 2
     32: Add r8, r8, r9
     36: ToPropertyKey r8, r8
     39: NewClosure r9, c5
     42: NewClosure r10, c6
     45: NewClosure r11, c7
     48: LoadImmediate r12, 3
     51: LoadImmediate r13, 4
     54: Add r12, r12, r13
     58: ToPropertyKey r12, r12
     61: NewClosure r13, c8
     64: LoadImmediate r14, 5
     67: LoadImmediate r15, 6
     70: Add r14, r14, r15
     74: ToPropertyKey r14, r14
     77: NewClosure r15, c9
     80: NewClosure r16, c10
     83: NewClosure r17, c11
     86: NewClosure r18, c12
     89: LoadImmediate r19, 1
     92: LoadImmediate r20, 2
     95: Add r19, r19, r20
     99: ToPropertyKey r19, r19
    102: NewClosure r20, c13
    105: NewClass r0, c15, c14, r1, r2
    111: StoreToScope r0, 1, 0
    115: LoadUndefined r0
    117: Ret r0
  Constant Table:
    0: [BytecodeFunction: named1]
    1: [BytecodeFunction: named2]
    2: [BytecodeFunction: <anonymous>]
    3: [BigInt: 1]
    4: [BytecodeFunction: <anonymous>]
    5: [BytecodeFunction: <anonymous>]
    6: [BytecodeFunction: get getter]
    7: [BytecodeFunction: set setter]
    8: [BytecodeFunction: <anonymous>]
    9: [BytecodeFunction: <anonymous>]
    10: [BytecodeFunction: staticMethod]
    11: [BytecodeFunction: get getter]
    12: [BytecodeFunction: set setter]
    13: [BytecodeFunction: <anonymous>]
    14: [BytecodeFunction: C]
    15: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: named1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: named2] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: get getter] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: set setter] {
  Parameters: 1, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 1, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: staticMethod] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: get getter] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: set setter] {
  Parameters: 1, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
