[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: LoadUndefined r0
    20: Ret r0
  Constant Table:
    0: [BytecodeFunction: methods]
    1: [String: methods]
    2: [BytecodeFunction: individualAccessors]
    3: [String: individualAccessors]
    4: [BytecodeFunction: accessorPairs]
    5: [String: accessorPairs]
}

[BytecodeFunction: methods] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: NewPrivateSymbol r2, c1
     7: StoreToScope r2, 2, 0
    11: NewPrivateSymbol r2, c2
    14: StoreToScope r2, 3, 0
    18: NewClosure r2, c3
    21: StoreToScope r2, 0, 0
    25: NewClosure r2, c4
    28: StoreToScope r2, 1, 0
    32: NewClass r0, c6, c5, r1, r0
    38: NewClosure r2, c7
    41: CallWithReceiver r2, r2, r0, r2, 0
    47: PopScope 
    48: LoadUndefined r1
    50: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: method1]
    2: [String: method2]
    3: [BytecodeFunction: #method1]
    4: [BytecodeFunction: #method2]
    5: [BytecodeFunction: C]
    6: [ClassNames]
    7: [BytecodeFunction: staticInitializer]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: CallWithReceiver r0, r0, <this>, r0, 0
     9: LoadUndefined r0
    11: Ret r0
  Constant Table:
    0: [BytecodeFunction: fieldsInitializer]
}

[BytecodeFunction: staticInitializer] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 3, 0
     4: LoadFromScope r1, 1, 0
     8: DefinePrivateProperty <this>, r0, r1, 1
    13: LoadUndefined r0
    15: Ret r0
}

[BytecodeFunction: fieldsInitializer] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 2, 0
     4: LoadFromScope r1, 0, 0
     8: DefinePrivateProperty <this>, r0, r1, 1
    13: LoadUndefined r0
    15: Ret r0
}

[BytecodeFunction: #method1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: #method2] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: individualAccessors] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: NewPrivateSymbol r2, c1
     7: StoreToScope r2, 4, 0
    11: NewPrivateSymbol r2, c2
    14: StoreToScope r2, 5, 0
    18: NewPrivateSymbol r2, c3
    21: StoreToScope r2, 6, 0
    25: NewPrivateSymbol r2, c4
    28: StoreToScope r2, 7, 0
    32: NewClosure r2, c5
    35: StoreToScope r2, 0, 0
    39: NewClosure r2, c6
    42: StoreToScope r2, 1, 0
    46: NewClosure r2, c7
    49: StoreToScope r2, 2, 0
    53: NewClosure r2, c8
    56: StoreToScope r2, 3, 0
    60: NewClass r0, c10, c9, r1, r0
    66: NewClosure r2, c11
    69: CallWithReceiver r2, r2, r0, r2, 0
    75: PopScope 
    76: LoadUndefined r1
    78: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: getter1]
    2: [String: setter1]
    3: [String: getter2]
    4: [String: setter2]
    5: [BytecodeFunction: get #getter1]
    6: [BytecodeFunction: set #setter1]
    7: [BytecodeFunction: get #getter2]
    8: [BytecodeFunction: set #setter2]
    9: [BytecodeFunction: C]
    10: [ClassNames]
    11: [BytecodeFunction: staticInitializer]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: CallWithReceiver r0, r0, <this>, r0, 0
     9: LoadUndefined r0
    11: Ret r0
  Constant Table:
    0: [BytecodeFunction: fieldsInitializer]
}

[BytecodeFunction: staticInitializer] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 6, 0
     4: LoadFromScope r1, 2, 0
     8: DefinePrivateProperty <this>, r0, r1, 2
    13: LoadFromScope r0, 7, 0
    17: LoadFromScope r1, 3, 0
    21: DefinePrivateProperty <this>, r0, r1, 4
    26: LoadUndefined r0
    28: Ret r0
}

[BytecodeFunction: fieldsInitializer] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 4, 0
     4: LoadFromScope r1, 0, 0
     8: DefinePrivateProperty <this>, r0, r1, 2
    13: LoadFromScope r0, 5, 0
    17: LoadFromScope r1, 1, 0
    21: DefinePrivateProperty <this>, r0, r1, 4
    26: LoadUndefined r0
    28: Ret r0
}

[BytecodeFunction: get #getter1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: set #setter1] {
  Parameters: 1, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: get #getter2] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: set #setter2] {
  Parameters: 1, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: accessorPairs] {
  Parameters: 0, Registers: 6
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: NewPrivateSymbol r2, c1
     7: StoreToScope r2, 3, 0
    11: NewPrivateSymbol r2, c2
    14: StoreToScope r2, 4, 0
    18: NewPrivateSymbol r2, c3
    21: StoreToScope r2, 5, 0
    25: NewClosure r2, c4
    28: NewClosure r3, c5
    31: NewAccessor r2, r3, r2
    35: StoreToScope r2, 0, 0
    39: NewClosure r2, c6
    42: NewClosure r3, c7
    45: NewAccessor r2, r2, r3
    49: StoreToScope r2, 1, 0
    53: NewClosure r2, c8
    56: NewClosure r3, c9
    59: NewClosure r4, c10
    62: NewClosure r5, c11
    65: NewAccessor r4, r5, r4
    69: StoreToScope r4, 2, 0
    73: NewClosure r4, c12
    76: NewClass r0, c14, c13, r1, r2
    82: NewClosure r5, c15
    85: CallWithReceiver r5, r5, r0, r5, 0
    91: PopScope 
    92: LoadUndefined r1
    94: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: acc1]
    2: [String: acc2]
    3: [String: acc3]
    4: [BytecodeFunction: set #acc1]
    5: [BytecodeFunction: get #acc1]
    6: [BytecodeFunction: get #acc2]
    7: [BytecodeFunction: set #acc2]
    8: [BytecodeFunction: method1]
    9: [BytecodeFunction: method2]
    10: [BytecodeFunction: set #acc3]
    11: [BytecodeFunction: get #acc3]
    12: [BytecodeFunction: method3]
    13: [BytecodeFunction: C]
    14: [ClassNames]
    15: [BytecodeFunction: staticInitializer]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: CallWithReceiver r0, r0, <this>, r0, 0
     9: LoadUndefined r0
    11: Ret r0
  Constant Table:
    0: [BytecodeFunction: fieldsInitializer]
}

[BytecodeFunction: staticInitializer] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 4, 0
     4: LoadFromScope r1, 1, 0
     8: DefinePrivateProperty <this>, r0, r1, 6
    13: LoadUndefined r0
    15: Ret r0
}

[BytecodeFunction: fieldsInitializer] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 3, 0
     4: LoadFromScope r1, 0, 0
     8: DefinePrivateProperty <this>, r0, r1, 6
    13: LoadFromScope r0, 5, 0
    17: LoadFromScope r1, 2, 0
    21: DefinePrivateProperty <this>, r0, r1, 6
    26: LoadUndefined r0
    28: Ret r0
}

[BytecodeFunction: get #acc1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: set #acc1] {
  Parameters: 1, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: set #acc2] {
  Parameters: 1, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: get #acc2] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: method1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: get #acc3] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: method2] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: set #acc3] {
  Parameters: 1, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: method3] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
