[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 10
     0: LoadConstant r1, c0
     3: NewClosure r2, c1
     6: NewClosure r3, c2
     9: NewClosure r4, c3
    12: NewClosure r5, c4
    15: NewClosure r6, c5
    18: NewClosure r7, c6
    21: NewClosure r8, c7
    24: NewClosure r9, c8
    27: NewClass r0, c10, c9, r1
    32: StoreToScope r0, 1, 0
    36: LoadUndefined r0
    38: Ret r0
  Constant Table:
    0: [Symbol: method]
    1: [BytecodeFunction: <anonymous>]
    2: [BytecodeFunction: privateMember]
    3: [BytecodeFunction: privateCall]
    4: [BytecodeFunction: privateOptionalMember]
    5: [BytecodeFunction: privateOptionalCall]
    6: [BytecodeFunction: privateAssignment]
    7: [BytecodeFunction: privateUpdate]
    8: [BytecodeFunction: privateDestructure]
    9: [BytecodeFunction: C]
    10: [ClassNames]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: privateMember] {
  Parameters: 0, Registers: 1
    0: LoadConstant r0, c0
    3: GetProperty r0, <this>, r0
    7: Ret r0
  Constant Table:
    0: [Symbol: method]
}

[BytecodeFunction: privateCall] {
  Parameters: 0, Registers: 1
     0: LoadConstant r0, c0
     3: GetProperty r0, <this>, r0
     7: CallWithReceiver r0, r0, <this>, r0, 0
    13: Ret r0
  Constant Table:
    0: [Symbol: method]
}

[BytecodeFunction: privateOptionalMember] {
  Parameters: 0, Registers: 1
     0: LoadConstant r0, c0
     3: GetProperty r0, <this>, r0
     7: JumpNullish r0, 11 (.L0)
    10: CallWithReceiver r0, r0, <this>, r0, 0
    16: Jump 4 (.L1)
  .L0:
    18: LoadUndefined r0
  .L1:
    20: Ret r0
  Constant Table:
    0: [Symbol: method]
}

[BytecodeFunction: privateOptionalCall] {
  Parameters: 0, Registers: 1
     0: LoadConstant r0, c0
     3: GetProperty r0, <this>, r0
     7: JumpNullish r0, 11 (.L0)
    10: CallWithReceiver r0, r0, <this>, r0, 0
    16: Jump 4 (.L1)
  .L0:
    18: LoadUndefined r0
  .L1:
    20: Ret r0
  Constant Table:
    0: [Symbol: method]
}

[BytecodeFunction: privateAssignment] {
  Parameters: 1, Registers: 2
     0: LoadConstant r1, c0
     3: Mov r0, a0
     6: SetProperty <this>, r1, r0
    10: LoadUndefined r0
    12: Ret r0
  Constant Table:
    0: [Symbol: method]
}

[BytecodeFunction: privateUpdate] {
  Parameters: 0, Registers: 3
     0: LoadConstant r1, c0
     3: GetProperty r0, <this>, r1
     7: ToNumeric r0, r0
    10: Mov r2, r0
    13: Inc r2
    15: SetProperty <this>, r1, r2
    19: LoadUndefined r0
    21: Ret r0
  Constant Table:
    0: [Symbol: method]
}

[BytecodeFunction: privateDestructure] {
  Parameters: 1, Registers: 2
     0: LoadConstant r1, c0
     3: GetNamedProperty r0, a0, c1
     7: SetProperty <this>, r1, r0
    11: LoadUndefined r0
    13: Ret r0
  Constant Table:
    0: [Symbol: method]
    1: [String: x]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
