[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 5
      0: LoadEmpty r1
      2: NewClass r0, c1, c0, r1, r0
      8: LoadImmediate r2, 1
     11: LoadImmediate r3, 2
     14: Add r2, r2, r3
     18: LoadImmediate r2, 3
     21: LoadImmediate r3, 4
     24: Add r2, r2, r3
     28: StoreToScope r0, 1, 0
     32: LoadEmpty r1
     34: NewClosure r2, c2
     37: NewClass r0, c4, c3, r1, r2
     43: LoadImmediate r3, 1
     46: LoadImmediate r4, 2
     49: Add r3, r3, r4
     53: StoreToScope r0, 2, 0
     57: LoadEmpty r1
     59: NewClass r0, c6, c5, r1, r0
     65: LoadImmediate r2, 1
     68: LoadImmediate r3, 2
     71: Add r2, r2, r3
     75: LoadImmediate r2, 3
     78: LoadImmediate r3, 4
     81: Add r2, r2, r3
     85: LoadImmediate r2, 5
     88: LoadImmediate r3, 6
     91: Add r2, r2, r3
     95: StoreToScope r0, 3, 0
     99: LoadUndefined r0
    101: Ret r0
  Constant Table:
    0: [BytecodeFunction: OnlyStaticInitializer]
    1: [ClassNames]
    2: [BytecodeFunction: method1]
    3: [BytecodeFunction: StaticInitializerAfterCreateClass]
    4: [ClassNames]
    5: [BytecodeFunction: MultipleStaticInitializers]
    6: [ClassNames]
}

[BytecodeFunction: OnlyStaticInitializer] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: method1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: StaticInitializerAfterCreateClass] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: MultipleStaticInitializers] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
