[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: StoreGlobal r0, c1
    6: LoadUndefined r0
    8: Ret r0
  Constant Table:
    0: [BytecodeFunction: superClass]
    1: [String: superClass]
}

[BytecodeFunction: superClass] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r1, 1
     3: LoadImmediate r2, 2
     6: Add r1, r1, r2
    10: NewClass r0, c1, c0, r1, r0
    16: LoadUndefined r1
    18: Ret r1
  Constant Table:
    0: [BytecodeFunction: C]
    1: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: DefaultSuperCall 
    1: CheckThisInitialized <this>
    3: Ret <this>
}
