{
  type: "Program",
  loc: "1:0-11:6",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:4",
      kind: {
        type: "Literal",
        loc: "1:0-1:3",
        raw: "/a/",
        value: {
          pattern: "a",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "2:0-2:7",
      kind: {
        type: "Literal",
        loc: "2:0-2:6",
        raw: "/a/bcd",
        value: {
          pattern: "a",
          flags: "bcd",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:7",
      kind: {
        type: "Literal",
        loc: "5:0-5:6",
        raw: "/=abc/",
        value: {
          pattern: "=abc",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "=abc",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "8:0-8:6",
      kind: {
        type: "Literal",
        loc: "8:0-8:5",
        raw: "/a|b/",
        value: {
          pattern: "a|b",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a",
                },
              ],
            },
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "b",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:0-9:11",
      kind: {
        type: "Literal",
        loc: "9:0-9:10",
        raw: "/ab|ba|cd/",
        value: {
          pattern: "ab|ba|cd",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "ab",
                },
              ],
            },
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "ba",
                },
              ],
            },
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "cd",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "10:0-10:6",
      kind: {
        type: "Literal",
        loc: "10:0-10:5",
        raw: "/|a|/",
        value: {
          pattern: "|a|",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [],
            },
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a",
                },
              ],
            },
            {
              type: "Alternative",
              terms: [],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:0-11:6",
      kind: {
        type: "Literal",
        loc: "11:0-11:5",
        raw: "/|||/",
        value: {
          pattern: "|||",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [],
            },
            {
              type: "Alternative",
              terms: [],
            },
            {
              type: "Alternative",
              terms: [],
            },
            {
              type: "Alternative",
              terms: [],
            },
          ],
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}