{
  type: "Program",
  loc: "1:0-19:20",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:4",
      kind: {
        type: "Literal",
        loc: "1:0-1:3",
        raw: "/a/",
        value: {
          pattern: "a",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "2:0-2:7",
      kind: {
        type: "Literal",
        loc: "2:0-2:6",
        raw: "/a/img",
        value: {
          pattern: "a",
          flags: "img",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:7",
      kind: {
        type: "Literal",
        loc: "5:0-5:6",
        raw: "/=abc/",
        value: {
          pattern: "=abc",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "=abc",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "8:0-8:6",
      kind: {
        type: "Literal",
        loc: "8:0-8:5",
        raw: "/a|b/",
        value: {
          pattern: "a|b",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a",
                },
              ],
            },
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "b",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:0-9:11",
      kind: {
        type: "Literal",
        loc: "9:0-9:10",
        raw: "/ab|ba|cd/",
        value: {
          pattern: "ab|ba|cd",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "ab",
                },
              ],
            },
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "ba",
                },
              ],
            },
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "cd",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "10:0-10:6",
      kind: {
        type: "Literal",
        loc: "10:0-10:5",
        raw: "/|a|/",
        value: {
          pattern: "|a|",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [],
            },
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a",
                },
              ],
            },
            {
              type: "Alternative",
              terms: [],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:0-11:6",
      kind: {
        type: "Literal",
        loc: "11:0-11:5",
        raw: "/|||/",
        value: {
          pattern: "|||",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [],
            },
            {
              type: "Alternative",
              terms: [],
            },
            {
              type: "Alternative",
              terms: [],
            },
            {
              type: "Alternative",
              terms: [],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "14:0-14:7",
      kind: {
        type: "Literal",
        loc: "14:0-14:6",
        raw: "/\b\B/",
        value: {
          pattern: "\b\B",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Assertion",
                  kind: "\b",
                },
                {
                  type: "Assertion",
                  kind: "\B",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "15:0-15:15",
      kind: {
        type: "Literal",
        loc: "15:0-15:14",
        raw: "/\w\W\s\S\d\D/",
        value: {
          pattern: "\w\W\s\S\d\D",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "CharacterClass",
                  is_inverted: false,
                  ranges: [
                    "\w",
                  ],
                },
                {
                  type: "CharacterClass",
                  is_inverted: true,
                  ranges: [
                    "\W",
                  ],
                },
                {
                  type: "CharacterClass",
                  is_inverted: false,
                  ranges: [
                    "\s",
                  ],
                },
                {
                  type: "CharacterClass",
                  is_inverted: true,
                  ranges: [
                    "\S",
                  ],
                },
                {
                  type: "CharacterClass",
                  is_inverted: false,
                  ranges: [
                    "\d",
                  ],
                },
                {
                  type: "CharacterClass",
                  is_inverted: true,
                  ranges: [
                    "\D",
                  ],
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "18:0-18:27",
      kind: {
        type: "Literal",
        loc: "18:0-18:26",
        raw: "/\1\2\3\4\5\6\7\8\9\10023/",
        value: {
          pattern: "\1\2\3\4\5\6\7\8\9\10023",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Backreference",
                  index: 1,
                },
                {
                  type: "Backreference",
                  index: 2,
                },
                {
                  type: "Backreference",
                  index: 3,
                },
                {
                  type: "Backreference",
                  index: 4,
                },
                {
                  type: "Backreference",
                  index: 5,
                },
                {
                  type: "Backreference",
                  index: 6,
                },
                {
                  type: "Backreference",
                  index: 7,
                },
                {
                  type: "Backreference",
                  index: 8,
                },
                {
                  type: "Backreference",
                  index: 9,
                },
                {
                  type: "Backreference",
                  index: 10023,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "19:0-19:20",
      kind: {
        type: "Literal",
        loc: "19:0-19:19",
        raw: "/\k<foo>\k<\u0061>/",
        value: {
          pattern: "\k<foo>\k<\u0061>",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Backreference",
                  name: "foo",
                },
                {
                  type: "Backreference",
                  name: "a",
                },
              ],
            },
          ],
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}