[CompiledRegExp: /(a)\1/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: MarkCapturePoint(2)
     4: Literal(a)
     5: MarkCapturePoint(3)
     7: Backreference(1, false)
     9: MarkCapturePoint(1)
    11: Accept
}

[CompiledRegExp: /(a)(b)(c)\3\1\2/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: MarkCapturePoint(2)
     4: Literal(a)
     5: MarkCapturePoint(3)
     7: MarkCapturePoint(4)
     9: Literal(b)
    10: MarkCapturePoint(5)
    12: MarkCapturePoint(6)
    14: Literal(c)
    15: MarkCapturePoint(7)
    17: Backreference(3, false)
    19: Backreference(1, false)
    21: Backreference(2, false)
    23: MarkCapturePoint(1)
    25: Accept
}

[CompiledRegExp: /(a)\1/] {
  Flags: "i"
  Match Start: Code Points("A", "a")
     0: MarkCapturePoint(0)
     2: MarkCapturePoint(2)
     4: CompareEquals(A)
     5: CompareEquals(a)
     6: ConsumeIfTrue
     7: MarkCapturePoint(3)
     9: Backreference(1, true)
    11: MarkCapturePoint(1)
    13: Accept
}
