[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewClosure r0, c8
    31: StoreGlobal r0, c9, k4
    35: NewClosure r0, c10
    38: StoreGlobal r0, c11, k5
    42: NewClosure r0, c12
    45: StoreGlobal r0, c13, k6
    49: NewClosure r0, c14
    52: StoreGlobal r0, c15, k7
    56: NewClosure r0, c16
    59: StoreGlobal r0, c17, k8
    63: LoadUndefined r0
    65: Ret r0
  Constant Table:
    0: [BytecodeFunction: notNeededDueToParameterName]
    1: [String: notNeededDueToParameterName]
    2: [BytecodeFunction: notNeededDueToLexicalName]
    3: [String: notNeededDueToLexicalName]
    4: [BytecodeFunction: notNeededDueToLexicalNameAndParameterExpressionsNoUse]
    5: [String: notNeededDueToLexicalNameAndParameterExpressionsNoUse]
    6: [BytecodeFunction: neededDueToLexicalNameAndParameterExpressionsWithUse]
    7: [String: neededDueToLexicalNameAndParameterExpressionsWithUse]
    8: [BytecodeFunction: neededWithVarName]
    9: [String: neededWithVarName]
    10: [BytecodeFunction: neededWithVarFunctionName]
    11: [String: neededWithVarFunctionName]
    12: [BytecodeFunction: notNeededSinceUseCaught]
    13: [String: notNeededSinceUseCaught]
    14: [BytecodeFunction: neededDueToDirectEval]
    15: [String: neededDueToDirectEval]
    16: [BytecodeFunction: notNeededDueToIndirectEval]
    17: [String: notNeededDueToIndirectEval]
}

[BytecodeFunction: notNeededDueToParameterName] {
  Parameters: 1, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: notNeededDueToLexicalName] {
  Parameters: 0, Registers: 2
    0: LoadImmediate r0, 1
    3: LoadUndefined r1
    5: Ret r1
}

[BytecodeFunction: notNeededDueToLexicalNameAndParameterExpressionsNoUse] {
  Parameters: 1, Registers: 2
     0: JumpNotUndefined a0, 6 (.L0)
     3: LoadImmediate a0, 1
  .L0:
     6: LoadEmpty r0
     8: CheckTdz r0, c0
    11: LoadImmediate r0, 1
    14: LoadUndefined r1
    16: Ret r1
  Constant Table:
    0: [String: arguments]
}

[BytecodeFunction: neededDueToLexicalNameAndParameterExpressionsWithUse] {
  Parameters: 1, Registers: 3
     0: NewUnmappedArguments r0
     2: JumpNotUndefined a0, 6 (.L0)
     5: Mov a0, r0
  .L0:
     8: LoadImmediate r1, 1
    11: LoadUndefined r2
    13: Ret r2
}

[BytecodeFunction: neededWithVarName] {
  Parameters: 0, Registers: 2
    0: NewMappedArguments r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: neededWithVarFunctionName] {
  Parameters: 0, Registers: 2
    0: NewMappedArguments r0
    2: NewClosure r0, c0
    5: LoadUndefined r1
    7: Ret r1
  Constant Table:
    0: [BytecodeFunction: arguments]
}

[BytecodeFunction: arguments] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: notNeededSinceUseCaught] {
  Parameters: 0, Registers: 2
    0: LoadImmediate r0, 1
    3: LoadUndefined r1
    5: Ret r1
}

[BytecodeFunction: neededDueToDirectEval] {
  Parameters: 0, Registers: 2
     0: PushFunctionScope c0
     2: StoreToScope <this>, 0, 0
     6: StoreToScope r0, 2, 0
    10: NewUnmappedArguments r0
    12: StoreToScope r0, 1, 0
    16: LoadGlobal r0, c1, k0
    20: LoadConstant r1, c2
    23: CallMaybeEval r0, r0, r1, 1, 1
    29: LoadUndefined r0
    31: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [String: eval]
    2: [String: ]
}

[BytecodeFunction: notNeededDueToIndirectEval] {
  Parameters: 0, Registers: 2
     0: LoadGlobal r0, c0, k0
     4: JumpNullish r0, 13 (.L0)
     7: LoadConstant r1, c1
    10: Call r0, r0, r1, 1
    15: Jump 4 (.L1)
  .L0:
    17: LoadUndefined r0
  .L1:
    19: LoadUndefined r0
    21: Ret r0
  Constant Table:
    0: [String: eval]
    1: [String: ]
}
