[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewClosure r0, c8
    31: StoreGlobal r0, c9, k4
    35: RetUndefined 
  Constant Table:
    0: [BytecodeFunction: strictForcesUnmapped]
    1: [String: strictForcesUnmapped]
    2: [BytecodeFunction: defaultForcesUnmapped]
    3: [String: defaultForcesUnmapped]
    4: [BytecodeFunction: destructuringForcesUnmapped]
    5: [String: destructuringForcesUnmapped]
    6: [BytecodeFunction: restForcesUnmapped]
    7: [String: restForcesUnmapped]
    8: [BytecodeFunction: withArguments]
    9: [String: withArguments]
}

[BytecodeFunction: strictForcesUnmapped] {
  Parameters: 0, Registers: 1
    0: NewUnmappedArguments r0
    2: RetUndefined 
}

[BytecodeFunction: defaultForcesUnmapped] {
  Parameters: 1, Registers: 1
    0: NewUnmappedArguments r0
    2: JumpNotUndefined a0, 6 (.L0)
    5: LoadImmediate a0, 1
  .L0:
    8: RetUndefined 
}

[BytecodeFunction: destructuringForcesUnmapped] {
  Parameters: 1, Registers: 2
    0: NewUnmappedArguments r1
    2: GetNamedProperty r0, a0, c0, k0
    7: RetUndefined 
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: restForcesUnmapped] {
  Parameters: 0, Registers: 2
    0: NewUnmappedArguments r1
    2: RestParameter r0
    4: RetUndefined 
}

[BytecodeFunction: withArguments] {
  Parameters: 3, Registers: 1
    0: NewUnmappedArguments r0
    2: RetUndefined 
}
