[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewClosure r0, c8
    31: StoreGlobal r0, c9, k4
    35: NewClosure r0, c10
    38: StoreGlobal r0, c11, k5
    42: NewClosure r0, c12
    45: StoreGlobal r0, c13, k6
    49: NewClosure r0, c14
    52: StoreGlobal r0, c15, k7
    56: NewClosure r0, c16
    59: StoreGlobal r0, c17, k8
    63: NewClosure r0, c18
    66: StoreGlobal r0, c19, k9
    70: LoadImmediate r0, 0
    73: StoreGlobal r0, c20, k10
    77: LoadUndefined r0
    79: Ret r0
  Constant Table:
    0: [BytecodeFunction: emptyObject]
    1: [String: emptyObject]
    2: [BytecodeFunction: shorthandProperties]
    3: [String: shorthandProperties]
    4: [BytecodeFunction: initializedProperties]
    5: [String: initializedProperties]
    6: [BytecodeFunction: stringPropertyKeys]
    7: [String: stringPropertyKeys]
    8: [BytecodeFunction: computedPropertyKeys]
    9: [String: computedPropertyKeys]
    10: [BytecodeFunction: spread]
    11: [String: spread]
    12: [BytecodeFunction: proto]
    13: [String: proto]
    14: [BytecodeFunction: propertyNamesNotResolved]
    15: [String: propertyNamesNotResolved]
    16: [BytecodeFunction: temporaryRegisterToAvoidClobbering]
    17: [String: temporaryRegisterToAvoidClobbering]
    18: [BytecodeFunction: noTemporaryRegisterNeededForEmptyObject]
    19: [String: noTemporaryRegisterNeededForEmptyObject]
    20: [String: global]
}

[BytecodeFunction: emptyObject] {
  Parameters: 0, Registers: 1
    0: NewObject r0, 4
    3: Ret r0
}

[BytecodeFunction: shorthandProperties] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 1
     3: NewObject r1, 3
     6: LoadGlobal r2, c0, k0
    10: DefineNamedProperty r1, c0, r2
    14: DefineNamedProperty r1, c1, r0
    18: DefineNamedProperty r1, c2, a0
    22: Ret r1
  Constant Table:
    0: [String: global]
    1: [String: local]
    2: [String: param]
}

[BytecodeFunction: initializedProperties] {
  Parameters: 0, Registers: 3
     0: NewObject r0, 2
     3: LoadImmediate r1, 1
     6: DefineNamedProperty r0, c0, r1
    10: LoadImmediate r1, 2
    13: LoadImmediate r2, 3
    16: Add r1, r1, r2
    20: DefineNamedProperty r0, c1, r1
    24: Ret r0
  Constant Table:
    0: [String: a]
    1: [String: global]
}

[BytecodeFunction: stringPropertyKeys] {
  Parameters: 0, Registers: 2
     0: NewObject r0, 2
     3: LoadImmediate r1, 1
     6: DefineNamedProperty r0, c0, r1
    10: LoadImmediate r1, 2
    13: DefineNamedProperty r0, c1, r1
    17: Ret r0
  Constant Table:
    0: [String: a]
    1: [String: b]
}

[BytecodeFunction: computedPropertyKeys] {
  Parameters: 0, Registers: 3
     0: NewObject r0, 3
     3: LoadConstant r1, c0
     6: LoadImmediate r2, 1
     9: DefineProperty r0, r1, r2, 0
    14: LoadImmediate r1, 2
    17: LoadImmediate r2, 3
    20: DefineProperty r0, r1, r2, 0
    25: LoadImmediate r1, 4
    28: LoadImmediate r2, 5
    31: Add r1, r1, r2
    35: LoadImmediate r2, 6
    38: DefineProperty r0, r1, r2, 0
    43: Ret r0
  Constant Table:
    0: [String: a]
}

[BytecodeFunction: spread] {
  Parameters: 1, Registers: 3
     0: NewObject r0, 4
     3: CopyDataProperties r0, a0, a0, 0
     8: LoadImmediate r1, 1
    11: LoadImmediate r2, 2
    14: Add r1, r1, r2
    18: CopyDataProperties r0, r1, r1, 0
    23: Ret r0
}

[BytecodeFunction: proto] {
  Parameters: 1, Registers: 3
     0: NewObject r0, 4
     3: LoadImmediate r1, 1
     6: LoadImmediate r2, 2
     9: Add r1, r1, r2
    13: SetPrototypeOf r0, r1
    16: Ret r0
}

[BytecodeFunction: propertyNamesNotResolved] {
  Parameters: 0, Registers: 5
     0: LoadEmpty r1
     2: LoadEmpty r2
     4: NewObject r3, 1
     7: LoadImmediate r4, 1
    10: DefineNamedProperty r3, c0, r4
    14: GetNamedProperty r0, r3, c0, k0
    19: NewObject r3, 2
    22: CheckTdz r1, c1
    25: DefineNamedProperty r3, c1, r1
    29: CheckTdz r2, c3
    32: DefineNamedProperty r3, c2, r2
    36: GetNamedProperty r1, r3, c1, k1
    41: GetNamedProperty r2, r3, c3, k2
    46: LoadUndefined r3
    48: Ret r3
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: d]
    3: [String: c]
}

[BytecodeFunction: temporaryRegisterToAvoidClobbering] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r0, 1
     3: NewObject r1, 1
     6: LoadImmediate r2, 2
     9: DefineNamedProperty r1, c0, r2
    13: Mov r0, r1
    16: LoadUndefined r1
    18: Ret r1
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: noTemporaryRegisterNeededForEmptyObject] {
  Parameters: 0, Registers: 2
    0: LoadImmediate r0, 1
    3: NewObject r0, 4
    6: LoadUndefined r1
    8: Ret r1
}
