[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewClosure r0, c8
    31: StoreGlobal r0, c9, k4
    35: NewClosure r0, c10
    38: StoreGlobal r0, c11, k5
    42: LoadUndefined r0
    44: Ret r0
  Constant Table:
    0: [BytecodeFunction: distinctNames]
    1: [String: distinctNames]
    2: [BytecodeFunction: duplicateNames]
    3: [String: duplicateNames]
    4: [BytecodeFunction: gettersAndSettersOvercounted]
    5: [String: gettersAndSettersOvercounted]
    6: [BytecodeFunction: computedPropertiesCounted]
    7: [String: computedPropertiesCounted]
    8: [BytecodeFunction: spreadIgnored]
    9: [String: spreadIgnored]
    10: [BytecodeFunction: prototypeSetterIgnored]
    11: [String: prototypeSetterIgnored]
}

[BytecodeFunction: distinctNames] {
  Parameters: 0, Registers: 2
     0: NewObject r0, 4
     3: LoadImmediate r1, 1
     6: DefineNamedProperty r0, c0, r1, k0
    11: LoadImmediate r1, 2
    14: DefineNamedProperty r0, c1, r1, k1
    19: NewClosure r1, c3
    22: DefineNamedProperty r0, c2, r1, k2
    27: LoadImmediate r1, 4
    30: DefineNamedProperty r0, c4, r1, k3
    35: LoadUndefined r0
    37: Ret r0
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: c]
    3: [BytecodeFunction: c]
    4: [String: d]
}

[BytecodeFunction: c] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: duplicateNames] {
  Parameters: 0, Registers: 2
     0: NewObject r0, 4
     3: LoadImmediate r1, 1
     6: DefineNamedProperty r0, c0, r1, k0
    11: LoadImmediate r1, 2
    14: DefineNamedProperty r0, c1, r1, k1
    19: LoadImmediate r1, 3
    22: DefineNamedProperty r0, c0, r1, k2
    27: LoadImmediate r1, 4
    30: DefineNamedProperty r0, c0, r1, k3
    35: LoadUndefined r0
    37: Ret r0
  Constant Table:
    0: [String: a]
    1: [String: b]
}

[BytecodeFunction: gettersAndSettersOvercounted] {
  Parameters: 0, Registers: 3
     0: NewObject r0, 3
     3: LoadConstant r1, c0
     6: NewClosure r2, c1
     9: DefineProperty r0, r1, r2, 2
    14: LoadConstant r1, c0
    17: NewClosure r2, c2
    20: DefineProperty r0, r1, r2, 4
    25: LoadImmediate r1, 2
    28: DefineNamedProperty r0, c3, r1, k0
    33: LoadUndefined r0
    35: Ret r0
  Constant Table:
    0: [String: a]
    1: [BytecodeFunction: get a]
    2: [BytecodeFunction: set a]
    3: [String: b]
}

[BytecodeFunction: get a] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: set a] {
  Parameters: 1, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: computedPropertiesCounted] {
  Parameters: 0, Registers: 3
     0: NewObject r0, 2
     3: LoadImmediate r1, 1
     6: LoadImmediate r2, 1
     9: DefineProperty r0, r1, r2, 0
    14: LoadImmediate r1, 2
    17: LoadImmediate r2, 2
    20: DefineProperty r0, r1, r2, 0
    25: LoadUndefined r0
    27: Ret r0
}

[BytecodeFunction: spreadIgnored] {
  Parameters: 0, Registers: 2
     0: NewObject r0, 1
     3: LoadGlobal r1, c0, k0
     7: CopyDataProperties r0, r1, r1, 0
    12: LoadImmediate r1, 2
    15: DefineNamedProperty r0, c1, r1, k1
    20: LoadUndefined r0
    22: Ret r0
  Constant Table:
    0: [String: a]
    1: [String: b]
}

[BytecodeFunction: prototypeSetterIgnored] {
  Parameters: 0, Registers: 2
     0: NewObject r0, 1
     3: LoadNull r1
     5: SetPrototypeOf r0, r1
     8: LoadImmediate r1, 2
    11: DefineNamedProperty r0, c0, r1, k0
    16: NewObject r0, 1
    19: LoadNull r1
    21: SetPrototypeOf r0, r1
    24: LoadImmediate r1, 2
    27: DefineNamedProperty r0, c0, r1, k1
    32: LoadUndefined r0
    34: Ret r0
  Constant Table:
    0: [String: b]
}
