[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: LoadUndefined r0
    16: Ret r0
  Constant Table:
    0: [BytecodeFunction: namedMethod]
    1: [String: namedMethod]
    2: [BytecodeFunction: computedMethod]
    3: [String: computedMethod]
}

[BytecodeFunction: namedMethod] {
  Parameters: 0, Registers: 2
     0: NewObject r0, 2
     3: NewClosure r1, c1
     6: DefineNamedProperty r0, c0, r1
    10: NewClosure r1, c3
    13: DefineNamedProperty r0, c2, r1
    17: Ret r0
  Constant Table:
    0: [String: a]
    1: [BytecodeFunction: a]
    2: [String: b]
    3: [BytecodeFunction: b]
}

[BytecodeFunction: a] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: b] {
  Parameters: 1, Registers: 1
    0: LoadImmediate r0, 2
    3: Ret r0
}

[BytecodeFunction: computedMethod] {
  Parameters: 0, Registers: 3
     0: NewObject r0, 1
     3: LoadImmediate r1, 1
     6: NewClosure r2, c0
     9: DefineProperty r0, r1, r2, 1
    14: Ret r0
  Constant Table:
    0: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
