[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: LoadUndefined r0
    30: Ret r0
  Constant Table:
    0: [BytecodeFunction: allNamedExpressions]
    1: [String: allNamedExpressions]
    2: [BytecodeFunction: stringKey]
    3: [String: stringKey]
    4: [BytecodeFunction: computedNeedsName]
    5: [String: computedNeedsName]
    6: [BytecodeFunction: computedAlreadyNamed]
    7: [String: computedAlreadyNamed]
}

[BytecodeFunction: allNamedExpressions] {
  Parameters: 0, Registers: 2
     0: NewObject r0, 3
     3: NewClosure r1, c1
     6: DefineNamedProperty r0, c0, r1
    10: NewClosure r1, c3
    13: DefineNamedProperty r0, c2, r1
    17: NewClosure r1, c5
    20: DefineNamedProperty r0, c4, r1
    24: Ret r0
  Constant Table:
    0: [String: a]
    1: [BytecodeFunction: a]
    2: [String: b]
    3: [BytecodeFunction: b]
    4: [String: c]
    5: [BytecodeFunction: alreadyNamed]
}

[BytecodeFunction: a] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: b] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: alreadyNamed] {
  Parameters: 0, Registers: 2
    0: Mov r0, <closure>
    3: LoadUndefined r1
    5: Ret r1
}

[BytecodeFunction: stringKey] {
  Parameters: 0, Registers: 2
     0: NewObject r0, 1
     3: NewClosure r1, c1
     6: DefineNamedProperty r0, c0, r1
    10: Ret r0
  Constant Table:
    0: [String: test]
    1: [BytecodeFunction: test]
}

[BytecodeFunction: test] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: computedNeedsName] {
  Parameters: 0, Registers: 3
     0: NewObject r0, 2
     3: LoadImmediate r1, 1
     6: LoadImmediate r2, 2
     9: Add r1, r1, r2
    13: NewClosure r2, c0
    16: DefineProperty r0, r1, r2, 1
    21: LoadImmediate r1, 3
    24: NewClosure r2, c1
    27: DefineProperty r0, r1, r2, 1
    32: Ret r0
  Constant Table:
    0: [BytecodeFunction: <anonymous>]
    1: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: computedAlreadyNamed] {
  Parameters: 0, Registers: 3
     0: NewObject r0, 1
     3: LoadImmediate r1, 1
     6: NewClosure r2, c0
     9: DefineProperty r0, r1, r2, 0
    14: Ret r0
  Constant Table:
    0: [BytecodeFunction: alreadyNamed]
}

[BytecodeFunction: alreadyNamed] {
  Parameters: 0, Registers: 2
    0: Mov r0, <closure>
    3: LoadUndefined r1
    5: Ret r1
}
