[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 5
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: LoadImmediate r0, 1
    15: LoadConstant r1, c4
    18: GetNamedProperty r2, r0, c4
    22: StoreGlobal r2, c4
    25: LoadConstant r2, c5
    28: GetNamedProperty r3, r0, c5
    32: StoreGlobal r3, c6
    35: LoadImmediate r3, 2
    38: ToPropertyKey r3, r3
    41: GetProperty r4, r0, r3
    45: StoreGlobal r4, c7
    48: NewObject r4
    50: CopyDataProperties r4, r0, r1, 3
    55: StoreGlobal r4, c8
    58: LoadUndefined r0
    60: Ret r0
  Constant Table:
    0: [BytecodeFunction: constants]
    1: [String: constants]
    2: [BytecodeFunction: nestedMember]
    3: [String: nestedMember]
    4: [String: v1]
    5: [String: z]
    6: [String: v2]
    7: [String: v3]
    8: [String: v4]
}

[BytecodeFunction: constants] {
  Parameters: 0, Registers: 8
     0: LoadImmediate r4, 1
     3: LoadConstant r5, c0
     6: GetNamedProperty r0, r4, c0
    10: LoadConstant r6, c1
    13: GetNamedProperty r1, r4, c1
    17: LoadImmediate r7, 2
    20: ToPropertyKey r7, r7
    23: GetProperty r2, r4, r7
    27: NewObject r3
    29: CopyDataProperties r3, r4, r5, 3
    34: LoadUndefined r4
    36: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: z]
}

[BytecodeFunction: nestedMember] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: GetNamedProperty r1, r0, c0
     7: SetNamedProperty a0, c1, r1
    11: LoadUndefined r0
    13: Ret r0
  Constant Table:
    0: [String: a]
    1: [String: b]
}
