[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 6
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: LoadImmediate r0, 1
    17: LoadConstant r1, c5
    20: GetNamedProperty r2, r0, c5
    24: StoreGlobal r2, c5
    27: LoadConstant r2, c6
    30: GetNamedProperty r3, r0, c6
    34: StoreGlobal r3, c7
    37: LoadImmediate r3, 2
    40: ToPropertyKey r3, r3
    43: GetProperty r4, r0, r3
    47: StoreGlobal r4, c8
    50: ToObject r5, r0
    53: NewObject r4
    55: CopyDataProperties r4, r0, r1, 3
    60: StoreGlobal r4, c9
    63: LoadUndefined r0
    65: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: constants]
    2: [String: constants]
    3: [BytecodeFunction: nestedMember]
    4: [String: nestedMember]
    5: [String: v1]
    6: [String: z]
    7: [String: v2]
    8: [String: v3]
    9: [String: v4]
}

[BytecodeFunction: constants] {
  Parameters: 0, Registers: 9
     0: LoadImmediate r4, 1
     3: LoadConstant r5, c0
     6: GetNamedProperty r0, r4, c0
    10: LoadConstant r6, c1
    13: GetNamedProperty r1, r4, c1
    17: LoadImmediate r7, 2
    20: ToPropertyKey r7, r7
    23: GetProperty r2, r4, r7
    27: ToObject r8, r4
    30: NewObject r3
    32: CopyDataProperties r3, r4, r5, 3
    37: LoadUndefined r4
    39: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: z]
}

[BytecodeFunction: nestedMember] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: GetNamedProperty r1, r0, c0
     7: SetNamedProperty a0, c1, r1
    11: LoadUndefined r0
    13: Ret r0
  Constant Table:
    0: [String: a]
    1: [String: b]
}
