[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: NewClosure r0, c11
    35: StoreGlobal r0, c12
    38: NewClosure r0, c13
    41: StoreGlobal r0, c14
    44: NewClosure r0, c15
    47: StoreGlobal r0, c16
    50: NewClosure r0, c17
    53: StoreGlobal r0, c18
    56: NewClosure r0, c19
    59: StoreGlobal r0, c20
    62: NewClosure r0, c21
    65: StoreGlobal r0, c22
    68: LoadUndefined r0
    70: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: empty]
    2: [String: empty]
    3: [BytecodeFunction: single]
    4: [String: single]
    5: [BytecodeFunction: multiple]
    6: [String: multiple]
    7: [BytecodeFunction: singleHole]
    8: [String: singleHole]
    9: [BytecodeFunction: multipleHoles]
    10: [String: multipleHoles]
    11: [BytecodeFunction: mixedHolesAndValues1]
    12: [String: mixedHolesAndValues1]
    13: [BytecodeFunction: mixedHolesAndValues2]
    14: [String: mixedHolesAndValues2]
    15: [BytecodeFunction: destructuring]
    16: [String: destructuring]
    17: [BytecodeFunction: onlyRest]
    18: [String: onlyRest]
    19: [BytecodeFunction: valuesAndRest]
    20: [String: valuesAndRest]
    21: [BytecodeFunction: restDestructuring]
    22: [String: restDestructuring]
}

[BytecodeFunction: empty] {
  Parameters: 1, Registers: 4
    0: GetIterator r0, r1, a0
    4: IteratorClose r0
    6: LoadUndefined r0
    8: Ret r0
}

[BytecodeFunction: single] {
  Parameters: 1, Registers: 5
     0: GetIterator r1, r2, a0
     4: IteratorNext r3, r4, r1, r2
     9: JumpFalse r4, 5 (.L0)
    12: LoadUndefined r3
  .L0:
    14: Mov r0, r3
    17: JumpTrue r4, 26 (.L4)
    20: LoadTrue r2
    22: Jump 4 (.L1)
    24: LoadFalse r2
  .L1:
    26: IteratorClose r1
    28: Jump 10 (.L3)
    30: JumpTrue r2, 6 (.L2)
    33: Mov r4, r3
  .L2:
    36: Throw r4
  .L3:
    38: JumpTrue r2, 5 (.L4)
    41: Throw r3
  .L4:
    43: LoadUndefined r1
    45: Ret r1
  Exception Handlers:
    14-17 -> 24 (r3)
    26-28 -> 30 (r4)
}

[BytecodeFunction: multiple] {
  Parameters: 1, Registers: 7
     0: GetIterator r3, r4, a0
     4: IteratorNext r5, r6, r3, r4
     9: JumpFalse r6, 5 (.L0)
    12: LoadUndefined r5
  .L0:
    14: Mov r0, r5
    17: JumpTrue r6, 11 (.L1)
    20: IteratorNext r5, r6, r3, r4
    25: JumpFalse r6, 5 (.L2)
  .L1:
    28: LoadUndefined r5
  .L2:
    30: Mov r1, r5
    33: JumpTrue r6, 11 (.L3)
    36: IteratorNext r5, r6, r3, r4
    41: JumpFalse r6, 5 (.L4)
  .L3:
    44: LoadUndefined r5
  .L4:
    46: Mov r2, r5
    49: JumpTrue r6, 26 (.L8)
    52: LoadTrue r4
    54: Jump 4 (.L5)
    56: LoadFalse r4
  .L5:
    58: IteratorClose r3
    60: Jump 10 (.L7)
    62: JumpTrue r4, 6 (.L6)
    65: Mov r6, r5
  .L6:
    68: Throw r6
  .L7:
    70: JumpTrue r4, 5 (.L8)
    73: Throw r5
  .L8:
    75: LoadUndefined r3
    77: Ret r3
  Exception Handlers:
    14-17 -> 56 (r5)
    30-33 -> 56 (r5)
    46-49 -> 56 (r5)
    58-60 -> 62 (r6)
}

[BytecodeFunction: singleHole] {
  Parameters: 1, Registers: 4
     0: GetIterator r0, r1, a0
     4: IteratorNext r2, r3, r0, r1
     9: JumpTrue r3, 5 (.L0)
    12: IteratorClose r0
  .L0:
    14: LoadUndefined r0
    16: Ret r0
}

[BytecodeFunction: multipleHoles] {
  Parameters: 1, Registers: 4
     0: GetIterator r0, r1, a0
     4: IteratorNext r2, r3, r0, r1
     9: JumpTrue r3, 8 (.L0)
    12: IteratorNext r2, r3, r0, r1
  .L0:
    17: JumpTrue r3, 8 (.L1)
    20: IteratorNext r2, r3, r0, r1
  .L1:
    25: JumpTrue r3, 5 (.L2)
    28: IteratorClose r0
  .L2:
    30: LoadUndefined r0
    32: Ret r0
}

[BytecodeFunction: mixedHolesAndValues1] {
  Parameters: 1, Registers: 6
     0: GetIterator r2, r3, a0
     4: IteratorNext r4, r5, r2, r3
     9: JumpFalse r5, 5 (.L0)
    12: LoadUndefined r4
  .L0:
    14: Mov r0, r4
    17: JumpTrue r5, 8 (.L1)
    20: IteratorNext r4, r5, r2, r3
  .L1:
    25: JumpTrue r5, 11 (.L2)
    28: IteratorNext r4, r5, r2, r3
    33: JumpFalse r5, 5 (.L3)
  .L2:
    36: LoadUndefined r4
  .L3:
    38: Mov r1, r4
    41: JumpTrue r5, 26 (.L7)
    44: LoadTrue r3
    46: Jump 4 (.L4)
    48: LoadFalse r3
  .L4:
    50: IteratorClose r2
    52: Jump 10 (.L6)
    54: JumpTrue r3, 6 (.L5)
    57: Mov r5, r4
  .L5:
    60: Throw r5
  .L6:
    62: JumpTrue r3, 5 (.L7)
    65: Throw r4
  .L7:
    67: LoadUndefined r2
    69: Ret r2
  Exception Handlers:
    14-17 -> 48 (r4)
    38-41 -> 48 (r4)
    50-52 -> 54 (r5)
}

[BytecodeFunction: mixedHolesAndValues2] {
  Parameters: 1, Registers: 5
     0: GetIterator r1, r2, a0
     4: IteratorNext r3, r4, r1, r2
     9: JumpTrue r4, 11 (.L0)
    12: IteratorNext r3, r4, r1, r2
    17: JumpFalse r4, 5 (.L1)
  .L0:
    20: LoadUndefined r3
  .L1:
    22: Mov r0, r3
    25: JumpTrue r4, 8 (.L2)
    28: IteratorNext r3, r4, r1, r2
  .L2:
    33: JumpTrue r4, 26 (.L6)
    36: LoadTrue r2
    38: Jump 4 (.L3)
    40: LoadFalse r2
  .L3:
    42: IteratorClose r1
    44: Jump 10 (.L5)
    46: JumpTrue r2, 6 (.L4)
    49: Mov r4, r3
  .L4:
    52: Throw r4
  .L5:
    54: JumpTrue r2, 5 (.L6)
    57: Throw r3
  .L6:
    59: LoadUndefined r1
    61: Ret r1
  Exception Handlers:
    22-25 -> 40 (r3)
    42-44 -> 46 (r4)
}

[BytecodeFunction: destructuring] {
  Parameters: 1, Registers: 6
     0: GetIterator r2, r3, a0
     4: IteratorNext r4, r5, r2, r3
     9: JumpFalse r5, 5 (.L0)
    12: LoadUndefined r4
  .L0:
    14: JumpNotUndefined r4, 6 (.L1)
    17: LoadImmediate r4, 1
  .L1:
    20: Mov r0, r4
    23: JumpTrue r5, 11 (.L2)
    26: IteratorNext r4, r5, r2, r3
    31: JumpFalse r5, 5 (.L3)
  .L2:
    34: LoadUndefined r4
  .L3:
    36: GetNamedProperty r1, r4, c0
    40: JumpTrue r5, 26 (.L7)
    43: LoadTrue r3
    45: Jump 4 (.L4)
    47: LoadFalse r3
  .L4:
    49: IteratorClose r2
    51: Jump 10 (.L6)
    53: JumpTrue r3, 6 (.L5)
    56: Mov r5, r4
  .L5:
    59: Throw r5
  .L6:
    61: JumpTrue r3, 5 (.L7)
    64: Throw r4
  .L7:
    66: LoadUndefined r2
    68: Ret r2
  Constant Table:
    0: [String: b]
  Exception Handlers:
    14-23 -> 47 (r4)
    36-40 -> 47 (r4)
    49-51 -> 53 (r5)
}

[BytecodeFunction: onlyRest] {
  Parameters: 1, Registers: 7
     0: GetIterator r1, r2, a0
     4: NewArray r5
     6: LoadImmediate r6, 0
  .L0:
     9: IteratorNext r3, r4, r1, r2
    14: JumpTrue r4, 11 (.L1)
    17: SetArrayProperty r5, r6, r3
    21: Inc r6
    23: Jump -14 (.L0)
  .L1:
    25: Mov r0, r5
    28: JumpTrue r4, 26 (.L5)
    31: LoadTrue r2
    33: Jump 4 (.L2)
    35: LoadFalse r2
  .L2:
    37: IteratorClose r1
    39: Jump 10 (.L4)
    41: JumpTrue r2, 6 (.L3)
    44: Mov r4, r3
  .L3:
    47: Throw r4
  .L4:
    49: JumpTrue r2, 5 (.L5)
    52: Throw r3
  .L5:
    54: LoadUndefined r1
    56: Ret r1
  Exception Handlers:
    25-28 -> 35 (r3)
    37-39 -> 41 (r4)
}

[BytecodeFunction: valuesAndRest] {
  Parameters: 1, Registers: 9
     0: GetIterator r3, r4, a0
     4: IteratorNext r5, r6, r3, r4
     9: JumpFalse r6, 5 (.L0)
    12: LoadUndefined r5
  .L0:
    14: Mov r0, r5
    17: JumpTrue r6, 11 (.L1)
    20: IteratorNext r5, r6, r3, r4
    25: JumpFalse r6, 5 (.L2)
  .L1:
    28: LoadUndefined r5
  .L2:
    30: Mov r1, r5
    33: NewArray r7
    35: LoadImmediate r8, 0
    38: JumpTrue r6, 19 (.L4)
  .L3:
    41: IteratorNext r5, r6, r3, r4
    46: JumpTrue r6, 11 (.L4)
    49: SetArrayProperty r7, r8, r5
    53: Inc r8
    55: Jump -14 (.L3)
  .L4:
    57: Mov r2, r7
    60: JumpTrue r6, 26 (.L8)
    63: LoadTrue r4
    65: Jump 4 (.L5)
    67: LoadFalse r4
  .L5:
    69: IteratorClose r3
    71: Jump 10 (.L7)
    73: JumpTrue r4, 6 (.L6)
    76: Mov r6, r5
  .L6:
    79: Throw r6
  .L7:
    81: JumpTrue r4, 5 (.L8)
    84: Throw r5
  .L8:
    86: LoadUndefined r3
    88: Ret r3
  Exception Handlers:
    14-17 -> 67 (r5)
    30-33 -> 67 (r5)
    57-60 -> 67 (r5)
    69-71 -> 73 (r6)
}

[BytecodeFunction: restDestructuring] {
  Parameters: 1, Registers: 7
     0: GetIterator r1, r2, a0
     4: NewArray r5
     6: LoadImmediate r6, 0
  .L0:
     9: IteratorNext r3, r4, r1, r2
    14: JumpTrue r4, 11 (.L1)
    17: SetArrayProperty r5, r6, r3
    21: Inc r6
    23: Jump -14 (.L0)
  .L1:
    25: GetNamedProperty r0, r5, c0
    29: JumpTrue r4, 26 (.L5)
    32: LoadTrue r2
    34: Jump 4 (.L2)
    36: LoadFalse r2
  .L2:
    38: IteratorClose r1
    40: Jump 10 (.L4)
    42: JumpTrue r2, 6 (.L3)
    45: Mov r4, r3
  .L3:
    48: Throw r4
  .L4:
    50: JumpTrue r2, 5 (.L5)
    53: Throw r3
  .L5:
    55: LoadUndefined r1
    57: Ret r1
  Constant Table:
    0: [String: b]
  Exception Handlers:
    25-29 -> 36 (r3)
    38-40 -> 42 (r4)
}
