[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: NewClosure r0, c11
    35: StoreGlobal r0, c12
    38: NewClosure r0, c13
    41: StoreGlobal r0, c14
    44: NewClosure r0, c15
    47: StoreGlobal r0, c16
    50: NewClosure r0, c17
    53: StoreGlobal r0, c18
    56: NewClosure r0, c19
    59: StoreGlobal r0, c20
    62: LoadUndefined r0
    64: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: shorthand]
    2: [String: shorthand]
    3: [BytecodeFunction: empty]
    4: [String: empty]
    5: [BytecodeFunction: propertyAliases]
    6: [String: propertyAliases]
    7: [BytecodeFunction: nested]
    8: [String: nested]
    9: [BytecodeFunction: computed]
    10: [String: computed]
    11: [BytecodeFunction: defaultValue]
    12: [String: defaultValue]
    13: [BytecodeFunction: namedExpression]
    14: [String: namedExpression]
    15: [BytecodeFunction: rest]
    16: [String: rest]
    17: [BytecodeFunction: propertyNamesNotResolved]
    18: [String: propertyNamesNotResolved]
    19: [BytecodeFunction: tdzWithinDestructuring]
    20: [String: tdzWithinDestructuring]
}

[BytecodeFunction: shorthand] {
  Parameters: 1, Registers: 5
     0: LoadImmediate r4, 1
     3: GetNamedProperty r0, r4, c0
     7: GetNamedProperty r1, a0, c1
    11: GetNamedProperty r2, a0, c2
    15: GetNamedProperty r3, a0, c3
    19: LoadUndefined r4
    21: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: c]
    3: [String: d]
}

[BytecodeFunction: empty] {
  Parameters: 1, Registers: 1
    0: ToObject r0, a0
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: propertyAliases] {
  Parameters: 1, Registers: 5
     0: GetNamedProperty r0, a0, c0
     4: GetNamedProperty r1, a0, c1
     8: GetNamedProperty r2, a0, c2
    12: GetNamedProperty r3, a0, c3
    16: LoadUndefined r4
    18: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: d]
    3: [String: f]
}

[BytecodeFunction: nested] {
  Parameters: 1, Registers: 5
     0: GetNamedProperty r3, a0, c0
     4: GetNamedProperty r0, r3, c1
     8: GetNamedProperty r3, a0, c2
    12: GetNamedProperty r1, r3, c3
    16: GetNamedProperty r4, r3, c4
    20: GetNamedProperty r2, r4, c5
    24: LoadUndefined r3
    26: Ret r3
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: c]
    3: [String: d]
    4: [String: e]
    5: [String: f]
}

[BytecodeFunction: computed] {
  Parameters: 1, Registers: 4
     0: LoadImmediate r2, 1
     3: GetProperty r0, a0, r2
     7: LoadImmediate r2, 2
    10: GetProperty r2, a0, r2
    14: LoadImmediate r3, 3
    17: GetProperty r1, r2, r3
    21: LoadUndefined r2
    23: Ret r2
}

[BytecodeFunction: defaultValue] {
  Parameters: 2, Registers: 5
     0: GetNamedProperty r4, a0, c0
     4: JumpNotUndefined r4, 6 (.L0)
     7: LoadImmediate r4, 1
  .L0:
    10: Mov r0, r4
    13: GetNamedProperty r4, a0, c0
    17: JumpNotUndefined r4, 6 (.L1)
    20: LoadImmediate r4, 1
  .L1:
    23: Mov r1, r4
    26: GetNamedProperty r4, a0, c1
    30: JumpNotUndefined r4, 6 (.L2)
    33: Mov r4, a1
  .L2:
    36: Mov r2, r4
    39: GetNamedProperty r4, a0, c0
    43: JumpNotUndefined r4, 6 (.L3)
    46: Mov r4, a1
  .L3:
    49: Mov r3, r4
    52: LoadImmediate r4, 1
    55: GetProperty r4, a0, r4
    59: JumpNotUndefined r4, 6 (.L4)
    62: LoadImmediate r4, 2
  .L4:
    65: Mov r0, r4
    68: LoadUndefined r4
    70: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: c]
}

[BytecodeFunction: namedExpression] {
  Parameters: 0, Registers: 4
     0: NewClosure r2, c0
     3: GetNamedProperty r0, r2, c1
     7: LoadImmediate r2, 1
    10: GetNamedProperty r3, r2, c1
    14: JumpNotUndefined r3, 6 (.L0)
    17: NewClosure r3, c2
  .L0:
    20: Mov r0, r3
    23: LoadImmediate r2, 1
    26: GetNamedProperty r3, r2, c1
    30: JumpNotUndefined r3, 6 (.L1)
    33: NewClosure r3, c3
  .L1:
    36: Mov r1, r3
    39: LoadUndefined r2
    41: Ret r2
  Constant Table:
    0: [BytecodeFunction: <anonymous>]
    1: [String: a]
    2: [BytecodeFunction: a]
    3: [BytecodeFunction: b]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: a] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: b] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: rest] {
  Parameters: 1, Registers: 8
     0: NewObject r0
     2: CopyDataProperties r0, a0, a0, 0
     7: LoadConstant r5, c0
    10: GetNamedProperty r0, a0, c0
    14: LoadConstant r6, c1
    17: GetNamedProperty r1, a0, c1
    21: NewObject r2
    23: CopyDataProperties r2, a0, r5, 2
    28: LoadConstant r5, c0
    31: GetNamedProperty r0, a0, c0
    35: LoadImmediate r6, 1
    38: ToPropertyKey r6, r6
    41: GetProperty r1, a0, r6
    45: LoadImmediate r7, 2
    48: ToPropertyKey r7, r7
    51: GetProperty r3, a0, r7
    55: NewObject r4
    57: CopyDataProperties r4, a0, r5, 3
    62: LoadUndefined r5
    64: Ret r5
  Constant Table:
    0: [String: a]
    1: [String: b]
}

[BytecodeFunction: propertyNamesNotResolved] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 1
     3: GetNamedProperty r0, r2, c0
     7: GetNamedProperty r3, r2, c1
    11: GetNamedProperty r1, r3, c0
    15: LoadUndefined r2
    17: Ret r2
  Constant Table:
    0: [String: a]
    1: [String: b]
}

[BytecodeFunction: tdzWithinDestructuring] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r0
     2: LoadImmediate r2, 1
     5: GetNamedProperty r0, r2, c0
     9: CheckTdz r0, c0
    12: GetProperty r1, r2, r0
    16: LoadUndefined r2
    18: Ret r2
  Constant Table:
    0: [String: a]
}
