{
  type: "Program",
  loc: "1:1-26:2",
  body: [
    {
      type: "ClassDeclaration",
      loc: "1:1-1:11",
      id: {
        type: "Identifier",
        loc: "1:7-1:8",
        name: "A",
      },
      superClass: null,
      body: {
        type: "ClassBody",
        loc: "1:1-1:11",
        body: [],
      },
    },
    {
      type: "ClassDeclaration",
      loc: "3:1-3:22",
      id: {
        type: "Identifier",
        loc: "3:7-3:9",
        name: "A2",
      },
      superClass: {
        type: "Identifier",
        loc: "3:18-3:19",
        name: "B",
      },
      body: {
        type: "ClassBody",
        loc: "3:1-3:22",
        body: [],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:14",
      kind: {
        type: "ClassExpression",
        loc: "5:2-5:12",
        id: {
          type: "Identifier",
          loc: "5:8-5:9",
          name: "A",
        },
        superClass: null,
        body: {
          type: "ClassBody",
          loc: "5:2-5:12",
          body: [],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:24",
      kind: {
        type: "ClassExpression",
        loc: "7:2-7:22",
        id: {
          type: "Identifier",
          loc: "7:8-7:9",
          name: "A",
        },
        superClass: {
          type: "Identifier",
          loc: "7:18-7:19",
          name: "B",
        },
        body: {
          type: "ClassBody",
          loc: "7:2-7:22",
          body: [],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:12",
      kind: {
        type: "ClassExpression",
        loc: "9:2-9:10",
        id: null,
        superClass: null,
        body: {
          type: "ClassBody",
          loc: "9:2-9:10",
          body: [],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:1-11:22",
      kind: {
        type: "ClassExpression",
        loc: "11:2-11:20",
        id: null,
        superClass: {
          type: "Identifier",
          loc: "11:16-11:17",
          name: "B",
        },
        body: {
          type: "ClassBody",
          loc: "11:2-11:20",
          body: [],
        },
      },
    },
    {
      type: "ClassDeclaration",
      loc: "13:1-15:2",
      id: {
        type: "Identifier",
        loc: "13:7-13:8",
        name: "C",
      },
      superClass: null,
      body: {
        type: "ClassBody",
        loc: "13:1-15:2",
        body: [],
      },
    },
    {
      type: "ClassDeclaration",
      loc: "19:1-26:2",
      id: {
        type: "Identifier",
        loc: "19:7-19:9",
        name: "C2",
      },
      superClass: null,
      body: {
        type: "ClassBody",
        loc: "19:1-26:2",
        body: [
          {
            type: "StaticBlock",
            loc: "20:3-20:12",
            body: [],
          },
          {
            type: "StaticBlock",
            loc: "22:3-25:4",
            body: [
              {
                type: "VariableDeclaration",
                loc: "23:5-23:15",
                kind: "let",
                declarations: [
                  {
                    type: "VariableDeclarator",
                    loc: "23:9-23:14",
                    id: {
                      type: "Identifier",
                      loc: "23:9-23:10",
                      name: "i",
                    },
                    init: {
                      type: "Literal",
                      loc: "23:13-23:14",
                      value: 0,
                    },
                  },
                ],
              },
              {
                type: "ExpressionStatement",
                loc: "24:5-24:7",
                kind: {
                  type: "Identifier",
                  loc: "24:5-24:6",
                  name: "b",
                },
              },
            ],
          },
        ],
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}