{
  type: "Program",
  loc: "1:1-3:22",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:9",
      kind: {
        type: "AwaitExpression",
        loc: "1:1-1:8",
        argument: {
          type: "Literal",
          loc: "1:7-1:8",
          value: 1,
        },
      },
    },
    {
      type: "ForOfStatement",
      loc: "3:1-3:22",
      left: {
        type: "Identifier",
        loc: "3:12-3:13",
        name: "x",
      },
      right: {
        type: "Identifier",
        loc: "3:17-3:18",
        name: "y",
      },
      body: {
        type: "Block",
        loc: "3:20-3:22",
        body: [],
      },
      await: true,
    },
  ],
  sourceType: "module",
  has_use_strict_directive: false,
}