{
  type: "Program",
  loc: "1:1-1:39",
  body: [
    {
      type: "ExportDefaultDeclaration",
      loc: "1:1-1:39",
      declaration: {
        type: "FunctionDeclaration",
        loc: "1:16-1:39",
        id: {
          type: "Identifier",
          loc: "1:31-1:34",
          name: "foo",
        },
        params: [],
        body: {
          type: "Block",
          loc: "1:37-1:39",
          body: [],
        },
        async: true,
        generator: false,
        has_use_strict_directive: false,
      },
    },
  ],
  sourceType: "module",
  has_use_strict_directive: false,
}