{
  type: "Program",
  loc: "1:1-27:12",
  body: [
    {
      type: "ImportDeclaration",
      loc: "1:1-1:12",
      specifiers: [],
      source: {
        type: "Literal",
        loc: "1:8-1:11",
        value: "a",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "3:1-3:25",
      specifiers: [
        {
          type: "ImportNamespaceSpecifier",
          loc: "3:8-3:15",
          local: {
            type: "Identifier",
            loc: "3:13-3:15",
            name: "a1",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "3:21-3:24",
        value: "b",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "6:1-6:20",
      specifiers: [
        {
          type: "ImportDefaultSpecifier",
          loc: "6:8-6:10",
          local: {
            type: "Identifier",
            loc: "6:8-6:10",
            name: "a2",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "6:16-6:19",
        value: "b",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "8:1-8:29",
      specifiers: [
        {
          type: "ImportDefaultSpecifier",
          loc: "8:8-8:10",
          local: {
            type: "Identifier",
            loc: "8:8-8:10",
            name: "a3",
          },
        },
        {
          type: "ImportNamespaceSpecifier",
          loc: "8:12-8:19",
          local: {
            type: "Identifier",
            loc: "8:17-8:19",
            name: "b1",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "8:25-8:28",
        value: "c",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "10:1-10:28",
      specifiers: [
        {
          type: "ImportDefaultSpecifier",
          loc: "10:8-10:10",
          local: {
            type: "Identifier",
            loc: "10:8-10:10",
            name: "a4",
          },
        },
        {
          type: "ImportSpecifier",
          loc: "10:14-10:16",
          imported: null,
          local: {
            type: "Identifier",
            loc: "10:14-10:16",
            name: "b2",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "10:24-10:27",
        value: "c",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "13:1-13:20",
      specifiers: [],
      source: {
        type: "Literal",
        loc: "13:16-13:19",
        value: "a",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "15:1-15:22",
      specifiers: [
        {
          type: "ImportSpecifier",
          loc: "15:9-15:11",
          imported: null,
          local: {
            type: "Identifier",
            loc: "15:9-15:11",
            name: "a5",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "15:18-15:21",
        value: "b",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "17:1-17:23",
      specifiers: [
        {
          type: "ImportSpecifier",
          loc: "17:9-17:11",
          imported: null,
          local: {
            type: "Identifier",
            loc: "17:9-17:11",
            name: "a6",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "17:19-17:22",
        value: "b",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "19:1-19:30",
      specifiers: [
        {
          type: "ImportSpecifier",
          loc: "19:9-19:11",
          imported: null,
          local: {
            type: "Identifier",
            loc: "19:9-19:11",
            name: "a7",
          },
        },
        {
          type: "ImportSpecifier",
          loc: "19:13-19:15",
          imported: null,
          local: {
            type: "Identifier",
            loc: "19:13-19:15",
            name: "b3",
          },
        },
        {
          type: "ImportSpecifier",
          loc: "19:17-19:19",
          imported: null,
          local: {
            type: "Identifier",
            loc: "19:17-19:19",
            name: "c1",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "19:26-19:29",
        value: "d",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "21:1-21:42",
      specifiers: [
        {
          type: "ImportSpecifier",
          loc: "21:9-21:17",
          imported: {
            type: "Identifier",
            loc: "21:9-21:11",
            name: "a8",
          },
          local: {
            type: "Identifier",
            loc: "21:15-21:17",
            name: "b4",
          },
        },
        {
          type: "ImportSpecifier",
          loc: "21:19-21:21",
          imported: null,
          local: {
            type: "Identifier",
            loc: "21:19-21:21",
            name: "c2",
          },
        },
        {
          type: "ImportSpecifier",
          loc: "21:23-21:31",
          imported: {
            type: "Identifier",
            loc: "21:23-21:25",
            name: "d1",
          },
          local: {
            type: "Identifier",
            loc: "21:29-21:31",
            name: "e1",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "21:38-21:41",
        value: "f",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "23:1-23:40",
      specifiers: [
        {
          type: "ImportSpecifier",
          loc: "23:9-23:18",
          imported: {
            type: "Literal",
            loc: "23:9-23:12",
            value: "a",
          },
          local: {
            type: "Identifier",
            loc: "23:16-23:18",
            name: "b5",
          },
        },
        {
          type: "ImportSpecifier",
          loc: "23:20-23:29",
          imported: {
            type: "Literal",
            loc: "23:20-23:23",
            value: "c",
          },
          local: {
            type: "Identifier",
            loc: "23:27-23:29",
            name: "d2",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "23:36-23:39",
        value: "e",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "25:1-25:11",
      kind: {
        type: "ImportExpression",
        loc: "25:1-25:11",
        source: {
          type: "Identifier",
          loc: "25:8-25:10",
          name: "a1",
        },
        options: null,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "27:1-27:12",
      kind: {
        type: "ImportExpression",
        loc: "27:1-27:11",
        source: {
          type: "Identifier",
          loc: "27:8-27:10",
          name: "a1",
        },
        options: null,
      },
    },
  ],
  sourceType: "module",
  has_use_strict_directive: false,
}