{
  type: "Program",
  loc: "1:1-5:7",
  body: [
    {
      type: "ImportDeclaration",
      loc: "1:1-1:12",
      specifiers: [],
      source: {
        type: "Literal",
        loc: "1:8-1:11",
        value: "a",
      },
    },
    {
      type: "FunctionDeclaration",
      loc: "3:1-3:18",
      id: {
        type: "Identifier",
        loc: "3:10-3:13",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "3:16-3:18",
        body: [],
      },
      async: false,
      generator: false,
      has_use_strict_directive: false,
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:7",
      kind: {
        type: "BinaryExpression",
        loc: "5:1-5:6",
        operator: "+",
        left: {
          type: "Literal",
          loc: "5:1-5:2",
          value: 1,
        },
        right: {
          type: "Literal",
          loc: "5:5-5:6",
          value: 2,
        },
      },
    },
  ],
  sourceType: "module",
  has_use_strict_directive: false,
}