[CompiledRegExp: /[a]/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: Literal(a)
     3: MarkCapturePoint(1)
     5: Accept
}

[CompiledRegExp: /[^a]/] {
  Flags: ""
  Match Start: Code Points("\x00"-"`", "b"-"\u{10FFFF}")
     0: MarkCapturePoint(0)
     2: CompareEquals(a)
     3: ConsumeIfFalse
     4: MarkCapturePoint(1)
     6: Accept
}

[CompiledRegExp: /[ac]/] {
  Flags: ""
  Match Start: Code Points("a", "c")
     0: MarkCapturePoint(0)
     2: CompareEquals(a)
     3: CompareEquals(c)
     4: ConsumeIfTrue
     5: MarkCapturePoint(1)
     7: Accept
}

[CompiledRegExp: /[a-z]/] {
  Flags: ""
  Match Start: Code Points("a"-"z")
     0: MarkCapturePoint(0)
     2: CompareBetween(a, z)
     4: ConsumeIfTrue
     5: MarkCapturePoint(1)
     7: Accept
}

[CompiledRegExp: /[a-z0-9AC]/] {
  Flags: ""
  Match Start: Code Points("0"-"9", "A", "C", "a"-"z")
     0: MarkCapturePoint(0)
     2: CompareBetween(0, 9)
     4: CompareEquals(A)
     5: CompareEquals(C)
     6: CompareBetween(a, z)
     8: ConsumeIfTrue
     9: MarkCapturePoint(1)
    11: Accept
}
