[CompiledRegExp: /[a]/] {
  Flags: ""
  Match Start: Code Points("a")
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(a)
    10: MarkCapturePoint(1)
    12: Accept
}

[CompiledRegExp: /[^a]/] {
  Flags: ""
  Match Start: Code Points("\x00"-"`", "b"-"\u{10FFFF}")
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: CompareEquals(a)
    10: ConsumeIfFalse
    11: MarkCapturePoint(1)
    13: Accept
}

[CompiledRegExp: /[ac]/] {
  Flags: ""
  Match Start: Code Points("a", "c")
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: CompareEquals(a)
    10: CompareEquals(c)
    11: ConsumeIfTrue
    12: MarkCapturePoint(1)
    14: Accept
}

[CompiledRegExp: /[a-z]/] {
  Flags: ""
  Match Start: Code Points("a"-"z")
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: CompareBetween(a, z)
    11: ConsumeIfTrue
    12: MarkCapturePoint(1)
    14: Accept
}

[CompiledRegExp: /[a-z0-9AC]/] {
  Flags: ""
  Match Start: Code Points("0"-"9", "A", "C", "a"-"z")
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: CompareBetween(0, 9)
    11: CompareEquals(A)
    12: CompareEquals(C)
    13: CompareBetween(a, z)
    15: ConsumeIfTrue
    16: MarkCapturePoint(1)
    18: Accept
}
