[CompiledRegExp: /\d\D/] {
  Flags: ""
  Match Start: Code Points("0"-"9")
     0: MarkCapturePoint(0)
     2: CodePointSet("0"-"9")
     4: CodePointSet(inverted, "0"-"9")
     6: MarkCapturePoint(1)
     8: Accept
}

[CompiledRegExp: /[\d][\D]/] {
  Flags: ""
  Match Start: Code Points("0"-"9")
     0: MarkCapturePoint(0)
     2: CodePointSet("0"-"9")
     4: CodePointSet(inverted, "0"-"9")
     6: MarkCapturePoint(1)
     8: Accept
}

[CompiledRegExp: /[\da][\D4]/] {
  Flags: ""
  Match Start: Code Points("0"-"9", "a")
     0: MarkCapturePoint(0)
     2: CodePointSet("0"-"9", "a")
     4: CodePointSet(inverted, "0"-"3", "5"-"9")
     6: MarkCapturePoint(1)
     8: Accept
}

[CompiledRegExp: /[\da-z][\D4-6]/] {
  Flags: ""
  Match Start: Code Points("0"-"9", "a"-"z")
     0: MarkCapturePoint(0)
     2: CodePointSet("0"-"9", "a"-"z")
     4: CodePointSet(inverted, "0"-"3", "7"-"9")
     6: MarkCapturePoint(1)
     8: Accept
}

[CompiledRegExp: /[\d\D]/] {
  Flags: ""
  Match Start: Code Points("\x00"-"\u{10FFFF}")
     0: MarkCapturePoint(0)
     2: CodePointSet(inverted, )
     4: MarkCapturePoint(1)
     6: Accept
}
