[CompiledRegExp: /\d\D/] {
  Flags: ""
  Match Start: Code Points("0"-"9")
     0: CodePointSet("0"-"9")
     2: CodePointSet(inverted, "0"-"9")
     4: Accept
}

[CompiledRegExp: /[\d][\D]/] {
  Flags: ""
  Match Start: Code Points("0"-"9")
     0: CodePointSet("0"-"9")
     2: CodePointSet(inverted, "0"-"9")
     4: Accept
}

[CompiledRegExp: /[\da][\D4]/] {
  Flags: ""
  Match Start: Code Points("0"-"9", "a")
     0: CodePointSet("0"-"9", "a")
     2: CodePointSet(inverted, "0"-"3", "5"-"9")
     4: Accept
}

[CompiledRegExp: /[\da-z][\D4-6]/] {
  Flags: ""
  Match Start: Code Points("0"-"9", "a"-"z")
     0: CodePointSet("0"-"9", "a"-"z")
     2: CodePointSet(inverted, "0"-"3", "7"-"9")
     4: Accept
}

[CompiledRegExp: /[\d\D]/] {
  Flags: ""
  Match Start: Code Points("\x00"-"\u{10FFFF}")
     0: CodePointSet(inverted, )
     2: Accept
}
