[CompiledRegExp: /[\q{ab}c]/] {
  Flags: "v"
  Match Start: Code Points("a", "c")
     0: Branch(4, 8)
     3: Accept
     4: OneByteStringLiteral("ab")
     6: Jump(3)
     8: CodePointLiteral(c)
     9: Jump(3)
}

[CompiledRegExp: /[\q{ab|abcde|abc}]/] {
  Flags: "v"
  Match Start: Code Points("a")
     0: Branch(10, 4)
     3: Accept
     4: Branch(14, 7)
     7: Branch(18, 22)
    10: OneByteStringLiteral("abcde")
    12: Jump(3)
    14: OneByteStringLiteral("abc")
    16: Jump(3)
    18: OneByteStringLiteral("ab")
    20: Jump(3)
    22: CodePointSet()
    24: Jump(3)
}

[CompiledRegExp: /[\q{a|b|c|de}]/] {
  Flags: "v"
  Match Start: Code Points("a"-"d")
     0: Branch(4, 8)
     3: Accept
     4: OneByteStringLiteral("de")
     6: Jump(3)
     8: CodePointSet("a"-"c")
    10: Jump(3)
}

[CompiledRegExp: /[\q{aa|bb}\q{cc}[\q{dd}]]/] {
  Flags: "v"
  Match Start: Code Points("a"-"d")
     0: Branch(13, 4)
     3: Accept
     4: Branch(17, 7)
     7: Branch(21, 10)
    10: Branch(25, 29)
    13: OneByteStringLiteral("aa")
    15: Jump(3)
    17: OneByteStringLiteral("bb")
    19: Jump(3)
    21: OneByteStringLiteral("cc")
    23: Jump(3)
    25: OneByteStringLiteral("dd")
    27: Jump(3)
    29: CodePointSet()
    31: Jump(3)
}

[CompiledRegExp: /[\q{aa|bb}&&\q{bb|cc}]/] {
  Flags: "v"
  Match Start: Code Points("b")
     0: Branch(4, 8)
     3: Accept
     4: OneByteStringLiteral("bb")
     6: Jump(3)
     8: CodePointSet()
    10: Jump(3)
}

[CompiledRegExp: /[\q{aa|bb}--\q{aa}]/] {
  Flags: "v"
  Match Start: Code Points("b")
     0: Branch(4, 8)
     3: Accept
     4: OneByteStringLiteral("bb")
     6: Jump(3)
     8: CodePointSet()
    10: Jump(3)
}

[CompiledRegExp: /[\q{}]/] {
  Flags: "v"
  Match Start: Unknown
     0: Branch(4, 3)
     3: Accept
     4: CodePointSet()
     6: Jump(3)
}

[CompiledRegExp: /x[\q{|}]y/] {
  Flags: "v"
  Match Start: Code Points("x")
     0: CodePointLiteral(x)
     1: Branch(6, 4)
     4: CodePointLiteral(y)
     5: Accept
     6: CodePointSet()
     8: Jump(4)
}

[CompiledRegExp: /x[\q{abc|}]y/] {
  Flags: "v"
  Match Start: Code Points("x")
     0: CodePointLiteral(x)
     1: Branch(6, 10)
     4: CodePointLiteral(y)
     5: Accept
     6: OneByteStringLiteral("abc")
     8: Jump(4)
    10: Branch(13, 4)
    13: CodePointSet()
    15: Jump(4)
}

[CompiledRegExp: /x[\q{|abc}]y/] {
  Flags: "v"
  Match Start: Code Points("x")
     0: CodePointLiteral(x)
     1: Branch(6, 10)
     4: CodePointLiteral(y)
     5: Accept
     6: OneByteStringLiteral("abc")
     8: Jump(4)
    10: Branch(13, 4)
    13: CodePointSet()
    15: Jump(4)
}

[CompiledRegExp: /x[\q{a|}]y/] {
  Flags: "v"
  Match Start: Code Points("x")
     0: CodePointLiteral(x)
     1: Branch(6, 4)
     4: CodePointLiteral(y)
     5: Accept
     6: CodePointLiteral(a)
     7: Jump(4)
}

[CompiledRegExp: /x[\q{|a}]y/] {
  Flags: "v"
  Match Start: Code Points("x")
     0: CodePointLiteral(x)
     1: Branch(6, 4)
     4: CodePointLiteral(y)
     5: Accept
     6: CodePointLiteral(a)
     7: Jump(4)
}

[CompiledRegExp: /x[\q{|a|abc}]y/] {
  Flags: "v"
  Match Start: Code Points("x")
     0: CodePointLiteral(x)
     1: Branch(6, 10)
     4: CodePointLiteral(y)
     5: Accept
     6: OneByteStringLiteral("abc")
     8: Jump(4)
    10: Branch(13, 4)
    13: CodePointLiteral(a)
    14: Jump(4)
}
