[CompiledRegExpObject: /[\q{ab}c]/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Branch(15, 19)
    12: MarkCapturePoint(1)
    14: Accept
    15: Literal(a)
    16: Literal(b)
    17: Jump(12)
    19: Literal(c)
    20: Jump(12)
}

[CompiledRegExpObject: /[\q{ab|abcde|abc}]/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Branch(21, 15)
    12: MarkCapturePoint(1)
    14: Accept
    15: Branch(28, 18)
    18: Branch(33, 37)
    21: Literal(a)
    22: Literal(b)
    23: Literal(c)
    24: Literal(d)
    25: Literal(e)
    26: Jump(12)
    28: Literal(a)
    29: Literal(b)
    30: Literal(c)
    31: Jump(12)
    33: Literal(a)
    34: Literal(b)
    35: Jump(12)
    37: ConsumeIfTrue
    38: Jump(12)
}

[CompiledRegExpObject: /[\q{a|b|c|de}]/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Branch(15, 19)
    12: MarkCapturePoint(1)
    14: Accept
    15: Literal(d)
    16: Literal(e)
    17: Jump(12)
    19: CompareBetween(a, d)
    21: ConsumeIfTrue
    22: Jump(12)
}

[CompiledRegExpObject: /[\q{aa|bb}\q{cc}[\q{dd}]]/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Branch(24, 15)
    12: MarkCapturePoint(1)
    14: Accept
    15: Branch(28, 18)
    18: Branch(32, 21)
    21: Branch(36, 40)
    24: Literal(a)
    25: Literal(a)
    26: Jump(12)
    28: Literal(b)
    29: Literal(b)
    30: Jump(12)
    32: Literal(c)
    33: Literal(c)
    34: Jump(12)
    36: Literal(d)
    37: Literal(d)
    38: Jump(12)
    40: ConsumeIfTrue
    41: Jump(12)
}

[CompiledRegExpObject: /[\q{aa|bb}&&\q{bb|cc}]/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Branch(15, 19)
    12: MarkCapturePoint(1)
    14: Accept
    15: Literal(b)
    16: Literal(b)
    17: Jump(12)
    19: ConsumeIfTrue
    20: Jump(12)
}

[CompiledRegExpObject: /[\q{aa|bb}--\q{aa}]/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Branch(15, 19)
    12: MarkCapturePoint(1)
    14: Accept
    15: Literal(b)
    16: Literal(b)
    17: Jump(12)
    19: ConsumeIfTrue
    20: Jump(12)
}

[CompiledRegExpObject: /[\q{}]/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Branch(15, 12)
    12: MarkCapturePoint(1)
    14: Accept
    15: ConsumeIfTrue
    16: Jump(12)
}

[CompiledRegExpObject: /x[\q{|}]y/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(x)
    10: Branch(17, 13)
    13: Literal(y)
    14: MarkCapturePoint(1)
    16: Accept
    17: ConsumeIfTrue
    18: Jump(13)
}

[CompiledRegExpObject: /x[\q{abc|}]y/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(x)
    10: Branch(17, 22)
    13: Literal(y)
    14: MarkCapturePoint(1)
    16: Accept
    17: Literal(a)
    18: Literal(b)
    19: Literal(c)
    20: Jump(13)
    22: Branch(25, 13)
    25: ConsumeIfTrue
    26: Jump(13)
}

[CompiledRegExpObject: /x[\q{|abc}]y/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(x)
    10: Branch(17, 22)
    13: Literal(y)
    14: MarkCapturePoint(1)
    16: Accept
    17: Literal(a)
    18: Literal(b)
    19: Literal(c)
    20: Jump(13)
    22: Branch(25, 13)
    25: ConsumeIfTrue
    26: Jump(13)
}

[CompiledRegExpObject: /x[\q{a|}]y/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(x)
    10: Branch(17, 13)
    13: Literal(y)
    14: MarkCapturePoint(1)
    16: Accept
    17: Literal(a)
    18: Jump(13)
}

[CompiledRegExpObject: /x[\q{|a}]y/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(x)
    10: Branch(17, 13)
    13: Literal(y)
    14: MarkCapturePoint(1)
    16: Accept
    17: Literal(a)
    18: Jump(13)
}

[CompiledRegExpObject: /x[\q{|a|abc}]y/] {
     0: Branch(7, 3)
     3: Wildcard
     4: Branch(7, 3)
     7: MarkCapturePoint(0)
     9: Literal(x)
    10: Branch(17, 22)
    13: Literal(y)
    14: MarkCapturePoint(1)
    16: Accept
    17: Literal(a)
    18: Literal(b)
    19: Literal(c)
    20: Jump(13)
    22: Branch(25, 13)
    25: Literal(a)
    26: Jump(13)
}
