[CompiledRegExp: /[\q{ab}c]/] {
  Flags: "v"
  Match Start: Code Points("a", "c")
     0: MarkCapturePoint(0)
     2: Branch(8, 12)
     5: MarkCapturePoint(1)
     7: Accept
     8: OneByteStringLiteral("ab")
    10: Jump(5)
    12: CodePointLiteral(c)
    13: Jump(5)
}

[CompiledRegExp: /[\q{ab|abcde|abc}]/] {
  Flags: "v"
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: Branch(14, 8)
     5: MarkCapturePoint(1)
     7: Accept
     8: Branch(18, 11)
    11: Branch(22, 26)
    14: OneByteStringLiteral("abcde")
    16: Jump(5)
    18: OneByteStringLiteral("abc")
    20: Jump(5)
    22: OneByteStringLiteral("ab")
    24: Jump(5)
    26: CodePointSet()
    28: Jump(5)
}

[CompiledRegExp: /[\q{a|b|c|de}]/] {
  Flags: "v"
  Match Start: Code Points("a"-"d")
     0: MarkCapturePoint(0)
     2: Branch(8, 12)
     5: MarkCapturePoint(1)
     7: Accept
     8: OneByteStringLiteral("de")
    10: Jump(5)
    12: CodePointSet("a"-"c")
    14: Jump(5)
}

[CompiledRegExp: /[\q{aa|bb}\q{cc}[\q{dd}]]/] {
  Flags: "v"
  Match Start: Code Points("a"-"d")
     0: MarkCapturePoint(0)
     2: Branch(17, 8)
     5: MarkCapturePoint(1)
     7: Accept
     8: Branch(21, 11)
    11: Branch(25, 14)
    14: Branch(29, 33)
    17: OneByteStringLiteral("aa")
    19: Jump(5)
    21: OneByteStringLiteral("bb")
    23: Jump(5)
    25: OneByteStringLiteral("cc")
    27: Jump(5)
    29: OneByteStringLiteral("dd")
    31: Jump(5)
    33: CodePointSet()
    35: Jump(5)
}

[CompiledRegExp: /[\q{aa|bb}&&\q{bb|cc}]/] {
  Flags: "v"
  Match Start: Code Points("b")
     0: MarkCapturePoint(0)
     2: Branch(8, 12)
     5: MarkCapturePoint(1)
     7: Accept
     8: OneByteStringLiteral("bb")
    10: Jump(5)
    12: CodePointSet()
    14: Jump(5)
}

[CompiledRegExp: /[\q{aa|bb}--\q{aa}]/] {
  Flags: "v"
  Match Start: Code Points("b")
     0: MarkCapturePoint(0)
     2: Branch(8, 12)
     5: MarkCapturePoint(1)
     7: Accept
     8: OneByteStringLiteral("bb")
    10: Jump(5)
    12: CodePointSet()
    14: Jump(5)
}

[CompiledRegExp: /[\q{}]/] {
  Flags: "v"
  Match Start: Unknown
     0: MarkCapturePoint(0)
     2: Branch(8, 5)
     5: MarkCapturePoint(1)
     7: Accept
     8: CodePointSet()
    10: Jump(5)
}

[CompiledRegExp: /x[\q{|}]y/] {
  Flags: "v"
  Match Start: Code Points("x")
     0: MarkCapturePoint(0)
     2: CodePointLiteral(x)
     3: Branch(10, 6)
     6: CodePointLiteral(y)
     7: MarkCapturePoint(1)
     9: Accept
    10: CodePointSet()
    12: Jump(6)
}

[CompiledRegExp: /x[\q{abc|}]y/] {
  Flags: "v"
  Match Start: Code Points("x")
     0: MarkCapturePoint(0)
     2: CodePointLiteral(x)
     3: Branch(10, 14)
     6: CodePointLiteral(y)
     7: MarkCapturePoint(1)
     9: Accept
    10: OneByteStringLiteral("abc")
    12: Jump(6)
    14: Branch(17, 6)
    17: CodePointSet()
    19: Jump(6)
}

[CompiledRegExp: /x[\q{|abc}]y/] {
  Flags: "v"
  Match Start: Code Points("x")
     0: MarkCapturePoint(0)
     2: CodePointLiteral(x)
     3: Branch(10, 14)
     6: CodePointLiteral(y)
     7: MarkCapturePoint(1)
     9: Accept
    10: OneByteStringLiteral("abc")
    12: Jump(6)
    14: Branch(17, 6)
    17: CodePointSet()
    19: Jump(6)
}

[CompiledRegExp: /x[\q{a|}]y/] {
  Flags: "v"
  Match Start: Code Points("x")
     0: MarkCapturePoint(0)
     2: CodePointLiteral(x)
     3: Branch(10, 6)
     6: CodePointLiteral(y)
     7: MarkCapturePoint(1)
     9: Accept
    10: CodePointLiteral(a)
    11: Jump(6)
}

[CompiledRegExp: /x[\q{|a}]y/] {
  Flags: "v"
  Match Start: Code Points("x")
     0: MarkCapturePoint(0)
     2: CodePointLiteral(x)
     3: Branch(10, 6)
     6: CodePointLiteral(y)
     7: MarkCapturePoint(1)
     9: Accept
    10: CodePointLiteral(a)
    11: Jump(6)
}

[CompiledRegExp: /x[\q{|a|abc}]y/] {
  Flags: "v"
  Match Start: Code Points("x")
     0: MarkCapturePoint(0)
     2: CodePointLiteral(x)
     3: Branch(10, 14)
     6: CodePointLiteral(y)
     7: MarkCapturePoint(1)
     9: Accept
    10: OneByteStringLiteral("abc")
    12: Jump(6)
    14: Branch(17, 6)
    17: CodePointLiteral(a)
    18: Jump(6)
}
