[CompiledRegExp: /\p{ASCII_Hex_Digit}/] {
  Flags: "u"
  Match Start: Code Points("0"-"9", "A"-"F", "a"-"f")
     0: MarkCapturePoint(0)
     2: CompareBetween(0, 9)
     4: CompareBetween(A, F)
     6: CompareBetween(a, f)
     8: ConsumeIfTrue
     9: MarkCapturePoint(1)
    11: Accept
}

[CompiledRegExp: /[\p{ASCII_Hex_Digit}]/] {
  Flags: "u"
  Match Start: Code Points("0"-"9", "A"-"F", "a"-"f")
     0: MarkCapturePoint(0)
     2: CompareBetween(0, 9)
     4: CompareBetween(A, F)
     6: CompareBetween(a, f)
     8: ConsumeIfTrue
     9: MarkCapturePoint(1)
    11: Accept
}

[CompiledRegExp: /[\p{ASCII_Hex_Digit}1]/] {
  Flags: "u"
  Match Start: Code Points("0"-"9", "A"-"F", "a"-"f")
     0: MarkCapturePoint(0)
     2: CompareBetween(0, 9)
     4: CompareBetween(A, F)
     6: CompareBetween(a, f)
     8: ConsumeIfTrue
     9: MarkCapturePoint(1)
    11: Accept
}

[CompiledRegExp: /[\p{ASCII_Hex_Digit}1-9]/] {
  Flags: "u"
  Match Start: Code Points("0"-"9", "A"-"F", "a"-"f")
     0: MarkCapturePoint(0)
     2: CompareBetween(0, 9)
     4: CompareBetween(A, F)
     6: CompareBetween(a, f)
     8: ConsumeIfTrue
     9: MarkCapturePoint(1)
    11: Accept
}

[CompiledRegExp: /\P{ASCII_Hex_Digit}/] {
  Flags: "u"
  Match Start: Code Points("\x00"-"/", ":"-"@", "G"-"`", "g"-"\u{10FFFF}")
     0: MarkCapturePoint(0)
     2: CompareBetween(\x00, /)
     4: CompareBetween(:, @)
     6: CompareBetween(G, `)
     8: CompareBetween(g, \u{10FFFF})
    10: ConsumeIfTrue
    11: MarkCapturePoint(1)
    13: Accept
}

[CompiledRegExp: /[\P{ASCII_Hex_Digit}C]/] {
  Flags: "u"
  Match Start: Code Points("\x00"-"/", ":"-"@", "C", "G"-"`", "g"-"\u{10FFFF}")
     0: MarkCapturePoint(0)
     2: CompareBetween(\x00, /)
     4: CompareBetween(:, @)
     6: CompareEquals(C)
     7: CompareBetween(G, `)
     9: CompareBetween(g, \u{10FFFF})
    11: ConsumeIfTrue
    12: MarkCapturePoint(1)
    14: Accept
}

[CompiledRegExp: /\p{Script=Latin}/] {
  Flags: "u"
  Match Start: Code Points("A"-"Z", "a"-"z", "ª", "º", "À"-"Ö", "Ø"-"ö", "ø"-"ʸ", "ˠ"-"ˤ", "ᴀ"-"ᴥ", "ᴬ"-"ᵜ", "ᵢ"-"ᵥ", "ᵫ"-"ᵷ", "ᵹ"-"ᶾ", "Ḁ"-"ỿ", "ⁱ", "ⁿ", "ₐ"-"ₜ", "K"-"Å", "Ⅎ", "ⅎ", "Ⅰ"-"ↈ", "Ⱡ"-"Ɀ", "Ꜣ"-"ꞇ", "Ꞌ"-"Ƛ", "꟱"-"ꟿ", "ꬰ"-"ꭚ", "ꭜ"-"ꭤ", "ꭦ"-"ꭩ", "ﬀ"-"ﬆ", "Ａ"-"Ｚ", "ａ"-"ｚ", "𐞀"-"𐞅", "𐞇"-"𐞰", "𐞲"-"𐞺", "𝼀"-"𝼞", "𝼥"-"𝼪")
     0: MarkCapturePoint(0)
     2: CompareBetween(A, Z)
     4: CompareBetween(a, z)
     6: CompareEquals(ª)
     7: CompareEquals(º)
     8: CompareBetween(À, Ö)
    10: CompareBetween(Ø, ö)
    12: CompareBetween(ø, ʸ)
    14: CompareBetween(ˠ, ˤ)
    16: CompareBetween(ᴀ, ᴥ)
    18: CompareBetween(ᴬ, ᵜ)
    20: CompareBetween(ᵢ, ᵥ)
    22: CompareBetween(ᵫ, ᵷ)
    24: CompareBetween(ᵹ, ᶾ)
    26: CompareBetween(Ḁ, ỿ)
    28: CompareEquals(ⁱ)
    29: CompareEquals(ⁿ)
    30: CompareBetween(ₐ, ₜ)
    32: CompareBetween(K, Å)
    34: CompareEquals(Ⅎ)
    35: CompareEquals(ⅎ)
    36: CompareBetween(Ⅰ, ↈ)
    38: CompareBetween(Ⱡ, Ɀ)
    40: CompareBetween(Ꜣ, ꞇ)
    42: CompareBetween(Ꞌ, Ƛ)
    44: CompareBetween(꟱, ꟿ)
    46: CompareBetween(ꬰ, ꭚ)
    48: CompareBetween(ꭜ, ꭤ)
    50: CompareBetween(ꭦ, ꭩ)
    52: CompareBetween(ﬀ, ﬆ)
    54: CompareBetween(Ａ, Ｚ)
    56: CompareBetween(ａ, ｚ)
    58: CompareBetween(𐞀, 𐞅)
    60: CompareBetween(𐞇, 𐞰)
    62: CompareBetween(𐞲, 𐞺)
    64: CompareBetween(𝼀, 𝼞)
    66: CompareBetween(𝼥, 𝼪)
    68: ConsumeIfTrue
    69: MarkCapturePoint(1)
    71: Accept
}

[CompiledRegExp: /\p{General_Category=Separator}/] {
  Flags: "u"
  Match Start: Code Points("\u{20}", "\u{A0}", "\u{1680}", "\u{2000}"-"\u{200A}", "\u{2028}"-"\u{2029}", "\u{202F}", "\u{205F}", "\u{3000}")
     0: MarkCapturePoint(0)
     2: CompareEquals(\u{20})
     3: CompareEquals(\u{A0})
     4: CompareEquals(\u{1680})
     5: CompareBetween(\u{2000}, \u{200A})
     7: CompareBetween(\u{2028}, \u{2029})
     9: CompareEquals(\u{202F})
    10: CompareEquals(\u{205F})
    11: CompareEquals(\u{3000})
    12: ConsumeIfTrue
    13: MarkCapturePoint(1)
    15: Accept
}

[CompiledRegExp: /[^\p{ASCII_Hex_Digit}]/] {
  Flags: "u"
  Match Start: Code Points("\x00"-"/", ":"-"@", "G"-"`", "g"-"\u{10FFFF}")
     0: MarkCapturePoint(0)
     2: CompareBetween(0, 9)
     4: CompareBetween(A, F)
     6: CompareBetween(a, f)
     8: ConsumeIfFalse
     9: MarkCapturePoint(1)
    11: Accept
}
