[CompiledRegExp: /\w/] {
  Flags: ""
  Match Start: Code Points("0"-"9", "A"-"Z", "_", "a"-"z")
     0: CodePointSet("0"-"9", "A"-"Z", "_", "a"-"z")
     2: Accept
}

[CompiledRegExp: /\W/] {
  Flags: ""
  Match Start: Code Points("\x00"-"/", ":"-"@", "["-"^", "`", "{"-"\u{10FFFF}")
     0: CodePointSet(inverted, "0"-"9", "A"-"Z", "_", "a"-"z")
     2: Accept
}

[CompiledRegExp: /[\w][\W]/] {
  Flags: ""
  Match Start: Code Points("0"-"9", "A"-"Z", "_", "a"-"z")
     0: CodePointSet("0"-"9", "A"-"Z", "_", "a"-"z")
     2: CodePointSet(inverted, "0"-"9", "A"-"Z", "_", "a"-"z")
     4: Accept
}

[CompiledRegExp: /[\wa][\Wa]/] {
  Flags: ""
  Match Start: Code Points("0"-"9", "A"-"Z", "_", "a"-"z")
     0: CodePointSet("0"-"9", "A"-"Z", "_", "a"-"z")
     2: CodePointSet(inverted, "0"-"9", "A"-"Z", "_", "b"-"z")
     4: Accept
}

[CompiledRegExp: /[\wa-z][\Wa-z]/] {
  Flags: ""
  Match Start: Code Points("0"-"9", "A"-"Z", "_", "a"-"z")
     0: CodePointSet("0"-"9", "A"-"Z", "_", "a"-"z")
     2: CodePointSet(inverted, "0"-"9", "A"-"Z", "_")
     4: Accept
}

[CompiledRegExp: /[\w\W]/] {
  Flags: ""
  Match Start: Code Points("\x00"-"\u{10FFFF}")
     0: CodePointSet(inverted, )
     2: Accept
}
