[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: LoadUndefined r0
    16: Ret r0
  Constant Table:
    0: [BytecodeFunction: foo]
    1: [String: foo]
    2: [BytecodeFunction: assignToCall]
    3: [String: assignToCall]
}

[BytecodeFunction: foo] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: assignToCall] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadGlobal r1, c0, k0
     7: Call r1, r1, r1, 0
    12: ThrowNewError 0, c1
    15: Mov r0, r1
    18: LoadGlobal r1, c0, k1
    22: Call r1, r1, r1, 0
    27: ThrowNewError 0, c1
    30: Mov a0, r1
    33: LoadGlobal r1, c0, k2
    37: Call r1, r1, r1, 0
    42: ThrowNewError 0, c1
    45: Mov a0, r1
    48: LoadUndefined r1
    50: Ret r1
  Constant Table:
    0: [String: f]
    1: [String: cannot assign to call expression]
}
