[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: LoadUndefined r0
    30: Ret r0
  Constant Table:
    0: [BytecodeFunction: testNamedMemberCall]
    1: [String: testNamedMemberCall]
    2: [BytecodeFunction: testComputedMemberCall]
    3: [String: testComputedMemberCall]
    4: [BytecodeFunction: testOptionalNamedMemberCall]
    5: [String: testOptionalNamedMemberCall]
    6: [BytecodeFunction: testOptionalComputedMemberCall]
    7: [String: testOptionalComputedMemberCall]
}

[BytecodeFunction: testNamedMemberCall] {
  Parameters: 1, Registers: 5
     0: GetNamedProperty r1, a0, c0, k0
     5: CallWithReceiver r1, r1, a0, r1, 0
    11: GetNamedProperty r1, a0, c0, k1
    16: LoadImmediate r2, 1
    19: LoadImmediate r3, 2
    22: LoadImmediate r4, 3
    25: CallWithReceiver r1, r1, a0, r2, 3
    31: LoadImmediate r1, 1
    34: LoadImmediate r2, 2
    37: Add r0, r1, r2
    41: GetNamedProperty r1, r0, c0, k2
    46: LoadImmediate r2, 4
    49: CallWithReceiver r1, r1, r0, r2, 1
    55: LoadUndefined r1
    57: Ret r1
  Constant Table:
    0: [String: foo]
}

[BytecodeFunction: testComputedMemberCall] {
  Parameters: 1, Registers: 6
     0: LoadConstant r1, c0
     3: GetProperty r1, a0, r1
     7: CallWithReceiver r1, r1, a0, r1, 0
    13: LoadImmediate r1, 0
    16: LoadImmediate r2, 9
    19: Add r1, r1, r2
    23: LoadConstant r2, c0
    26: GetProperty r2, r1, r2
    30: LoadImmediate r3, 1
    33: LoadImmediate r4, 2
    36: LoadImmediate r5, 3
    39: CallWithReceiver r1, r2, r1, r3, 3
    45: LoadImmediate r1, 1
    48: LoadImmediate r2, 2
    51: Add r0, r1, r2
    55: LoadConstant r1, c0
    58: GetProperty r1, r0, r1
    62: LoadImmediate r2, 4
    65: CallWithReceiver r1, r1, r0, r2, 1
    71: LoadUndefined r1
    73: Ret r1
  Constant Table:
    0: [String: foo]
}

[BytecodeFunction: testOptionalNamedMemberCall] {
  Parameters: 1, Registers: 2
     0: Mov r0, a0
     3: JumpNullish r0, 10 (.L0)
     6: GetNamedProperty r1, r0, c0, k0
    11: Jump 6 (.L1)
  .L0:
    13: LoadUndefined r1
    15: LoadUndefined r0
  .L1:
    17: CallWithReceiver r0, r1, r0, r1, 0
    23: JumpNullish a0, 15 (.L2)
    26: GetNamedProperty r0, a0, c1, k1
    31: GetNamedProperty r1, r0, c2, k2
    36: Jump 6 (.L3)
  .L2:
    38: LoadUndefined r1
    40: LoadUndefined r0
  .L3:
    42: CallWithReceiver r0, r1, r0, r1, 0
    48: LoadUndefined r0
    50: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: a]
    2: [String: b]
}

[BytecodeFunction: testOptionalComputedMemberCall] {
  Parameters: 1, Registers: 2
     0: Mov r0, a0
     3: JumpNullish r0, 12 (.L0)
     6: LoadImmediate r1, 1
     9: GetProperty r1, r0, r1
    13: Jump 6 (.L1)
  .L0:
    15: LoadUndefined r1
    17: LoadUndefined r0
  .L1:
    19: CallWithReceiver r0, r1, r0, r1, 0
    25: JumpNullish a0, 19 (.L2)
    28: LoadImmediate r0, 1
    31: GetProperty r0, a0, r0
    35: LoadImmediate r1, 2
    38: GetProperty r1, r0, r1
    42: Jump 6 (.L3)
  .L2:
    44: LoadUndefined r1
    46: LoadUndefined r0
  .L3:
    48: CallWithReceiver r0, r1, r0, r1, 0
    54: LoadUndefined r0
    56: Ret r0
}
