[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewClosure r0, c8
    31: StoreGlobal r0, c9, k4
    35: LoadUndefined r0
    37: Ret r0
  Constant Table:
    0: [BytecodeFunction: simpleSpread]
    1: [String: simpleSpread]
    2: [BytecodeFunction: spreadWithArgs]
    3: [String: spreadWithArgs]
    4: [BytecodeFunction: complexSpread]
    5: [String: complexSpread]
    6: [BytecodeFunction: spreadWithReceiver]
    7: [String: spreadWithReceiver]
    8: [BytecodeFunction: maybeEvalSpread]
    9: [String: maybeEvalSpread]
}

[BytecodeFunction: simpleSpread] {
  Parameters: 1, Registers: 7
     0: LoadGlobal r0, c0, k0
     4: NewArray r1, 0
     7: LoadImmediate r2, 0
    10: GetIterator r3, r4, a0
  .L0:
    14: IteratorNext r5, r6, r3, r4
    19: JumpTrue r6, 11 (.L1)
    22: SetArrayProperty r1, r2, r5
    26: Inc r2
    28: Jump -14 (.L0)
  .L1:
    30: LoadUndefined r2
    32: CallVarargs r0, r0, r2, r1
    37: Ret r0
  Constant Table:
    0: [String: f]
}

[BytecodeFunction: spreadWithArgs] {
  Parameters: 1, Registers: 7
     0: LoadGlobal r0, c0, k0
     4: NewArray r1, 1
     7: LoadImmediate r2, 0
    10: LoadImmediate r3, 1
    13: SetArrayProperty r1, r2, r3
    17: Inc r2
    19: GetIterator r3, r4, a0
  .L0:
    23: IteratorNext r5, r6, r3, r4
    28: JumpTrue r6, 11 (.L1)
    31: SetArrayProperty r1, r2, r5
    35: Inc r2
    37: Jump -14 (.L0)
  .L1:
    39: LoadUndefined r2
    41: CallVarargs r0, r0, r2, r1
    46: Ret r0
  Constant Table:
    0: [String: f]
}

[BytecodeFunction: complexSpread] {
  Parameters: 0, Registers: 8
     0: LoadGlobal r0, c0, k0
     4: NewArray r1, 2
     7: LoadImmediate r2, 0
    10: LoadImmediate r3, 1
    13: SetArrayProperty r1, r2, r3
    17: Inc r2
    19: LoadImmediate r3, 2
    22: GetIterator r4, r5, r3
  .L0:
    26: IteratorNext r6, r7, r4, r5
    31: JumpTrue r7, 11 (.L1)
    34: SetArrayProperty r1, r2, r6
    38: Inc r2
    40: Jump -14 (.L0)
  .L1:
    42: LoadImmediate r3, 3
    45: SetArrayProperty r1, r2, r3
    49: Inc r2
    51: LoadImmediate r3, 4
    54: GetIterator r4, r5, r3
  .L2:
    58: IteratorNext r6, r7, r4, r5
    63: JumpTrue r7, 11 (.L3)
    66: SetArrayProperty r1, r2, r6
    70: Inc r2
    72: Jump -14 (.L2)
  .L3:
    74: LoadUndefined r2
    76: CallVarargs r0, r0, r2, r1
    81: Ret r0
  Constant Table:
    0: [String: f]
}

[BytecodeFunction: spreadWithReceiver] {
  Parameters: 2, Registers: 7
     0: GetNamedProperty r0, a0, c0, k0
     5: NewArray r1, 0
     8: LoadImmediate r2, 0
    11: GetIterator r3, r4, a1
  .L0:
    15: IteratorNext r5, r6, r3, r4
    20: JumpTrue r6, 11 (.L1)
    23: SetArrayProperty r1, r2, r5
    27: Inc r2
    29: Jump -14 (.L0)
  .L1:
    31: CallVarargs r0, r0, a0, r1
    36: Ret r0
  Constant Table:
    0: [String: f]
}

[BytecodeFunction: maybeEvalSpread] {
  Parameters: 1, Registers: 8
     0: PushFunctionScope c0
     2: StoreToScope <this>, 1, 0
     6: StoreToScope r0, 3, 0
    10: StoreToScope a0, 0, 0
    14: NewMappedArguments r0
    16: StoreToScope r0, 2, 0
    20: LoadDynamic r0, c1
    23: NewArray r1, 0
    26: LoadImmediate r2, 0
    29: LoadFromScope r3, 0, 0
    33: GetIterator r4, r5, r3
  .L0:
    37: IteratorNext r6, r7, r4, r5
    42: JumpTrue r7, 11 (.L1)
    45: SetArrayProperty r1, r2, r6
    49: Inc r2
    51: Jump -14 (.L0)
  .L1:
    53: CallMaybeEvalVarargs r0, r0, r1, 1
    58: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [String: eval]
}
