[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewClosure r0, c8
    31: StoreGlobal r0, c9, k4
    35: LoadUndefined r0
    37: Ret r0
  Constant Table:
    0: [BytecodeFunction: simpleSpread]
    1: [String: simpleSpread]
    2: [BytecodeFunction: spreadWithArgs]
    3: [String: spreadWithArgs]
    4: [BytecodeFunction: complexSpread]
    5: [String: complexSpread]
    6: [BytecodeFunction: spreadWithReceiver]
    7: [String: spreadWithReceiver]
    8: [BytecodeFunction: maybeEvalSpread]
    9: [String: maybeEvalSpread]
}

[BytecodeFunction: simpleSpread] {
  Parameters: 1, Registers: 7
     0: LoadGlobal r0, c0, k0
     4: NewArray r1
     6: LoadImmediate r2, 0
     9: GetIterator r3, r4, a0
  .L0:
    13: IteratorNext r5, r6, r3, r4
    18: JumpTrue r6, 11 (.L1)
    21: SetArrayProperty r1, r2, r5
    25: Inc r2
    27: Jump -14 (.L0)
  .L1:
    29: LoadUndefined r2
    31: CallVarargs r0, r0, r2, r1
    36: Ret r0
  Constant Table:
    0: [String: f]
}

[BytecodeFunction: spreadWithArgs] {
  Parameters: 1, Registers: 7
     0: LoadGlobal r0, c0, k0
     4: NewArray r1
     6: LoadImmediate r2, 0
     9: LoadImmediate r3, 1
    12: SetArrayProperty r1, r2, r3
    16: Inc r2
    18: GetIterator r3, r4, a0
  .L0:
    22: IteratorNext r5, r6, r3, r4
    27: JumpTrue r6, 11 (.L1)
    30: SetArrayProperty r1, r2, r5
    34: Inc r2
    36: Jump -14 (.L0)
  .L1:
    38: LoadUndefined r2
    40: CallVarargs r0, r0, r2, r1
    45: Ret r0
  Constant Table:
    0: [String: f]
}

[BytecodeFunction: complexSpread] {
  Parameters: 0, Registers: 8
     0: LoadGlobal r0, c0, k0
     4: NewArray r1
     6: LoadImmediate r2, 0
     9: LoadImmediate r3, 1
    12: SetArrayProperty r1, r2, r3
    16: Inc r2
    18: LoadImmediate r3, 2
    21: GetIterator r4, r5, r3
  .L0:
    25: IteratorNext r6, r7, r4, r5
    30: JumpTrue r7, 11 (.L1)
    33: SetArrayProperty r1, r2, r6
    37: Inc r2
    39: Jump -14 (.L0)
  .L1:
    41: LoadImmediate r3, 3
    44: SetArrayProperty r1, r2, r3
    48: Inc r2
    50: LoadImmediate r3, 4
    53: GetIterator r4, r5, r3
  .L2:
    57: IteratorNext r6, r7, r4, r5
    62: JumpTrue r7, 11 (.L3)
    65: SetArrayProperty r1, r2, r6
    69: Inc r2
    71: Jump -14 (.L2)
  .L3:
    73: LoadUndefined r2
    75: CallVarargs r0, r0, r2, r1
    80: Ret r0
  Constant Table:
    0: [String: f]
}

[BytecodeFunction: spreadWithReceiver] {
  Parameters: 2, Registers: 7
     0: GetNamedProperty r0, a0, c0, k0
     5: NewArray r1
     7: LoadImmediate r2, 0
    10: GetIterator r3, r4, a1
  .L0:
    14: IteratorNext r5, r6, r3, r4
    19: JumpTrue r6, 11 (.L1)
    22: SetArrayProperty r1, r2, r5
    26: Inc r2
    28: Jump -14 (.L0)
  .L1:
    30: CallVarargs r0, r0, a0, r1
    35: Ret r0
  Constant Table:
    0: [String: f]
}

[BytecodeFunction: maybeEvalSpread] {
  Parameters: 1, Registers: 8
     0: PushFunctionScope c0
     2: StoreToScope <this>, 1, 0
     6: StoreToScope r0, 3, 0
    10: StoreToScope a0, 0, 0
    14: NewMappedArguments r0
    16: StoreToScope r0, 2, 0
    20: LoadDynamic r0, c1
    23: NewArray r1
    25: LoadImmediate r2, 0
    28: LoadFromScope r3, 0, 0
    32: GetIterator r4, r5, r3
  .L0:
    36: IteratorNext r6, r7, r4, r5
    41: JumpTrue r7, 11 (.L1)
    44: SetArrayProperty r1, r2, r6
    48: Inc r2
    50: Jump -14 (.L0)
  .L1:
    52: CallMaybeEvalVarargs r0, r0, r1, 1
    57: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [String: eval]
}
