{
  type: "Program",
  loc: "1:0-34:29",
  body: [
    {
      type: "ExportNamedDeclaration",
      loc: "1:0-1:10",
      declaration: null,
      specifiers: [],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "2:0-2:19",
      declaration: null,
      specifiers: [],
      source: {
        type: "Literal",
        loc: "2:15-2:18",
        value: "a",
      },
    },
    {
      type: "ExportNamedDeclaration",
      loc: "4:0-4:10",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "4:8-4:9",
          exported: null,
          local: {
            type: "Identifier",
            loc: "4:8-4:9",
            name: "a",
          },
        },
      ],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "5:0-5:11",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "5:8-5:9",
          exported: null,
          local: {
            type: "Identifier",
            loc: "5:8-5:9",
            name: "a",
          },
        },
      ],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "6:0-6:16",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "6:8-6:9",
          exported: null,
          local: {
            type: "Identifier",
            loc: "6:8-6:9",
            name: "a",
          },
        },
        {
          type: "ExportSpecifier",
          loc: "6:11-6:12",
          exported: null,
          local: {
            type: "Identifier",
            loc: "6:11-6:12",
            name: "b",
          },
        },
        {
          type: "ExportSpecifier",
          loc: "6:14-6:15",
          exported: null,
          local: {
            type: "Identifier",
            loc: "6:14-6:15",
            name: "c",
          },
        },
      ],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "7:0-7:17",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "7:8-7:9",
          exported: null,
          local: {
            type: "Identifier",
            loc: "7:8-7:9",
            name: "a",
          },
        },
        {
          type: "ExportSpecifier",
          loc: "7:11-7:12",
          exported: null,
          local: {
            type: "Identifier",
            loc: "7:11-7:12",
            name: "b",
          },
        },
        {
          type: "ExportSpecifier",
          loc: "7:14-7:15",
          exported: null,
          local: {
            type: "Identifier",
            loc: "7:14-7:15",
            name: "c",
          },
        },
      ],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "8:0-8:19",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "8:8-8:9",
          exported: null,
          local: {
            type: "Identifier",
            loc: "8:8-8:9",
            name: "a",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "8:16-8:19",
        value: "b",
      },
    },
    {
      type: "ExportNamedDeclaration",
      loc: "10:0-10:26",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "10:8-10:14",
          exported: {
            type: "Identifier",
            loc: "10:13-10:14",
            name: "b",
          },
          local: {
            type: "Identifier",
            loc: "10:8-10:9",
            name: "a",
          },
        },
        {
          type: "ExportSpecifier",
          loc: "10:16-10:17",
          exported: null,
          local: {
            type: "Identifier",
            loc: "10:16-10:17",
            name: "c",
          },
        },
        {
          type: "ExportSpecifier",
          loc: "10:19-10:25",
          exported: {
            type: "Identifier",
            loc: "10:24-10:25",
            name: "e",
          },
          local: {
            type: "Identifier",
            loc: "10:19-10:20",
            name: "d",
          },
        },
      ],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "13:0-13:18",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "13:8-13:16",
          exported: {
            type: "Literal",
            loc: "13:13-13:16",
            value: "b",
          },
          local: {
            type: "Identifier",
            loc: "13:8-13:9",
            name: "a",
          },
        },
      ],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "14:0-14:17",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "14:8-14:15",
          exported: {
            type: "Identifier",
            loc: "14:13-14:15",
            name: "if",
          },
          local: {
            type: "Identifier",
            loc: "14:8-14:9",
            name: "a",
          },
        },
      ],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "17:0-17:33",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "17:8-17:18",
          exported: {
            type: "Literal",
            loc: "17:15-17:18",
            value: "b",
          },
          local: {
            type: "Literal",
            loc: "17:8-17:11",
            value: "a",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "17:25-17:32",
        value: "other",
      },
    },
    {
      type: "ExportNamedDeclaration",
      loc: "18:0-18:31",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "18:8-18:16",
          exported: {
            type: "Identifier",
            loc: "18:14-18:16",
            name: "if",
          },
          local: {
            type: "Identifier",
            loc: "18:8-18:10",
            name: "if",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "18:23-18:30",
        value: "other",
      },
    },
    {
      type: "ExportNamedDeclaration",
      loc: "20:0-20:17",
      declaration: {
        type: "VariableDeclaration",
        loc: "20:7-20:17",
        kind: "var",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "20:11-20:16",
            id: {
              type: "Identifier",
              loc: "20:11-20:12",
              name: "a",
            },
            init: {
              type: "Literal",
              loc: "20:15-20:16",
              value: 1,
            },
          },
        ],
      },
      specifiers: [],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "21:0-21:18",
      declaration: {
        type: "VariableDeclaration",
        loc: "21:7-21:18",
        kind: "let",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "21:11-21:17",
            id: {
              type: "Identifier",
              loc: "21:11-21:13",
              name: "a2",
            },
            init: {
              type: "Literal",
              loc: "21:16-21:17",
              value: 1,
            },
          },
        ],
      },
      specifiers: [],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "22:0-22:20",
      declaration: {
        type: "VariableDeclaration",
        loc: "22:7-22:20",
        kind: "const",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "22:13-22:19",
            id: {
              type: "Identifier",
              loc: "22:13-22:15",
              name: "a3",
            },
            init: {
              type: "Literal",
              loc: "22:18-22:19",
              value: 1,
            },
          },
        ],
      },
      specifiers: [],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "23:0-23:26",
      declaration: {
        type: "VariableDeclaration",
        loc: "23:7-23:26",
        kind: "const",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "23:13-23:25",
            id: {
              type: "ArrayPattern",
              loc: "23:13-23:21",
              elements: [
                {
                  type: "Identifier",
                  loc: "23:14-23:16",
                  name: "a4",
                },
                {
                  type: "Identifier",
                  loc: "23:18-23:20",
                  name: "b5",
                },
              ],
            },
            init: {
              type: "Literal",
              loc: "23:24-23:25",
              value: 1,
            },
          },
        ],
      },
      specifiers: [],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "25:0-25:17",
      declaration: {
        type: "ClassDeclaration",
        loc: "25:7-25:17",
        id: {
          type: "Identifier",
          loc: "25:13-25:14",
          name: "C",
        },
        superClass: null,
        body: {
          type: "ClassBody",
          loc: "25:7-25:17",
          body: [],
        },
      },
      specifiers: [],
      source: null,
    },
    {
      type: "EmptyStatement",
      loc: "25:17-25:18",
    },
    {
      type: "ExportNamedDeclaration",
      loc: "27:0-27:24",
      declaration: {
        type: "FunctionDeclaration",
        loc: "27:7-27:24",
        id: {
          type: "Identifier",
          loc: "27:16-27:19",
          name: "foo",
        },
        params: [],
        body: {
          type: "Block",
          loc: "27:22-27:24",
          body: [],
        },
        async: false,
        generator: false,
        has_use_strict_directive: false,
      },
      specifiers: [],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "28:0-28:31",
      declaration: {
        type: "FunctionDeclaration",
        loc: "28:7-28:31",
        id: {
          type: "Identifier",
          loc: "28:22-28:26",
          name: "foo2",
        },
        params: [],
        body: {
          type: "Block",
          loc: "28:29-28:31",
          body: [],
        },
        async: true,
        generator: false,
        has_use_strict_directive: false,
      },
      specifiers: [],
      source: null,
    },
    {
      type: "ExportDefaultDeclaration",
      loc: "30:0-30:18",
      declaration: {
        type: "Identifier",
        loc: "30:15-30:17",
        name: "a6",
      },
    },
    {
      type: "ExportAllDeclaration",
      loc: "32:0-32:22",
      exported: null,
      source: {
        type: "Literal",
        loc: "32:14-32:21",
        value: "other",
      },
    },
    {
      type: "ExportAllDeclaration",
      loc: "33:0-33:27",
      exported: {
        type: "Identifier",
        loc: "33:12-33:13",
        name: "a",
      },
      source: {
        type: "Literal",
        loc: "33:19-33:26",
        value: "other",
      },
    },
    {
      type: "ExportAllDeclaration",
      loc: "34:0-34:29",
      exported: {
        type: "Literal",
        loc: "34:12-34:15",
        value: "a",
      },
      source: {
        type: "Literal",
        loc: "34:21-34:28",
        value: "other",
      },
    },
  ],
  sourceType: "module",
  has_use_strict_directive: false,
}