{
  type: "Program",
  loc: "1:1-1:22",
  body: [
    {
      type: "ExportDefaultDeclaration",
      loc: "1:1-1:22",
      declaration: {
        type: "BinaryExpression",
        loc: "1:16-1:21",
        operator: "+",
        left: {
          type: "Literal",
          loc: "1:16-1:17",
          value: 1,
        },
        right: {
          type: "Literal",
          loc: "1:20-1:21",
          value: 2,
        },
      },
    },
  ],
  sourceType: "module",
  has_use_strict_directive: false,
}