{
  type: "Program",
  loc: "1:1-1:30",
  body: [
    {
      type: "ExportDefaultDeclaration",
      loc: "1:1-1:30",
      declaration: {
        type: "FunctionDeclaration",
        loc: "1:16-1:30",
        id: null,
        params: [],
        body: {
          type: "Block",
          loc: "1:28-1:30",
          body: [],
        },
        async: false,
        generator: false,
        has_use_strict_directive: false,
      },
    },
  ],
  sourceType: "module",
  has_use_strict_directive: false,
}