{
  type: "Program",
  loc: "1:0-37:29",
  body: [
    {
      type: "ExportNamedDeclaration",
      loc: "1:0-1:10",
      declaration: null,
      specifiers: [],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "2:0-2:19",
      declaration: null,
      specifiers: [],
      source: {
        type: "Literal",
        loc: "2:15-2:18",
        value: "a",
      },
    },
    {
      type: "ExportNamedDeclaration",
      loc: "4:0-4:10",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "4:8-4:9",
          exported: null,
          local: {
            type: "Identifier",
            loc: "4:8-4:9",
            name: "a",
          },
        },
      ],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "5:0-5:11",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "5:8-5:9",
          exported: null,
          local: {
            type: "Identifier",
            loc: "5:8-5:9",
            name: "a",
          },
        },
      ],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "6:0-6:16",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "6:8-6:9",
          exported: null,
          local: {
            type: "Identifier",
            loc: "6:8-6:9",
            name: "a",
          },
        },
        {
          type: "ExportSpecifier",
          loc: "6:11-6:12",
          exported: null,
          local: {
            type: "Identifier",
            loc: "6:11-6:12",
            name: "b",
          },
        },
        {
          type: "ExportSpecifier",
          loc: "6:14-6:15",
          exported: null,
          local: {
            type: "Identifier",
            loc: "6:14-6:15",
            name: "c",
          },
        },
      ],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "7:0-7:17",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "7:8-7:9",
          exported: null,
          local: {
            type: "Identifier",
            loc: "7:8-7:9",
            name: "a",
          },
        },
        {
          type: "ExportSpecifier",
          loc: "7:11-7:12",
          exported: null,
          local: {
            type: "Identifier",
            loc: "7:11-7:12",
            name: "b",
          },
        },
        {
          type: "ExportSpecifier",
          loc: "7:14-7:15",
          exported: null,
          local: {
            type: "Identifier",
            loc: "7:14-7:15",
            name: "c",
          },
        },
      ],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "8:0-8:19",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "8:8-8:9",
          exported: null,
          local: {
            type: "Identifier",
            loc: "8:8-8:9",
            name: "a",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "8:16-8:19",
        value: "b",
      },
    },
    {
      type: "ExportNamedDeclaration",
      loc: "10:0-10:26",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "10:8-10:14",
          exported: {
            type: "Identifier",
            loc: "10:13-10:14",
            name: "b",
          },
          local: {
            type: "Identifier",
            loc: "10:8-10:9",
            name: "a",
          },
        },
        {
          type: "ExportSpecifier",
          loc: "10:16-10:17",
          exported: null,
          local: {
            type: "Identifier",
            loc: "10:16-10:17",
            name: "c",
          },
        },
        {
          type: "ExportSpecifier",
          loc: "10:19-10:25",
          exported: {
            type: "Identifier",
            loc: "10:24-10:25",
            name: "e",
          },
          local: {
            type: "Identifier",
            loc: "10:19-10:20",
            name: "d",
          },
        },
      ],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "12:0-12:18",
      declaration: null,
      specifiers: [
        {
          type: "ExportSpecifier",
          loc: "12:8-12:16",
          exported: {
            type: "Literal",
            loc: "12:13-12:16",
            value: "b",
          },
          local: {
            type: "Identifier",
            loc: "12:8-12:9",
            name: "a",
          },
        },
      ],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "14:0-14:17",
      declaration: {
        type: "VariableDeclaration",
        loc: "14:7-14:17",
        kind: "var",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "14:11-14:16",
            id: {
              type: "Identifier",
              loc: "14:11-14:12",
              name: "a",
            },
            init: {
              type: "Literal",
              loc: "14:15-14:16",
              value: 1,
            },
          },
        ],
      },
      specifiers: [],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "15:0-15:18",
      declaration: {
        type: "VariableDeclaration",
        loc: "15:7-15:18",
        kind: "let",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "15:11-15:17",
            id: {
              type: "Identifier",
              loc: "15:11-15:13",
              name: "a2",
            },
            init: {
              type: "Literal",
              loc: "15:16-15:17",
              value: 1,
            },
          },
        ],
      },
      specifiers: [],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "16:0-16:20",
      declaration: {
        type: "VariableDeclaration",
        loc: "16:7-16:20",
        kind: "const",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "16:13-16:19",
            id: {
              type: "Identifier",
              loc: "16:13-16:15",
              name: "a3",
            },
            init: {
              type: "Literal",
              loc: "16:18-16:19",
              value: 1,
            },
          },
        ],
      },
      specifiers: [],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "17:0-17:26",
      declaration: {
        type: "VariableDeclaration",
        loc: "17:7-17:26",
        kind: "const",
        declarations: [
          {
            type: "VariableDeclarator",
            loc: "17:13-17:25",
            id: {
              type: "ArrayPattern",
              loc: "17:13-17:21",
              elements: [
                {
                  type: "Identifier",
                  loc: "17:14-17:16",
                  name: "a4",
                },
                {
                  type: "Identifier",
                  loc: "17:18-17:20",
                  name: "b5",
                },
              ],
            },
            init: {
              type: "Literal",
              loc: "17:24-17:25",
              value: 1,
            },
          },
        ],
      },
      specifiers: [],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "19:0-19:17",
      declaration: {
        type: "ClassDeclaration",
        loc: "19:7-19:17",
        id: {
          type: "Identifier",
          loc: "19:13-19:14",
          name: "C",
        },
        superClass: null,
        body: {
          type: "ClassBody",
          loc: "19:7-19:17",
          body: [],
        },
      },
      specifiers: [],
      source: null,
    },
    {
      type: "EmptyStatement",
      loc: "19:17-19:18",
    },
    {
      type: "ExportNamedDeclaration",
      loc: "21:0-21:24",
      declaration: {
        type: "FunctionDeclaration",
        loc: "21:7-21:24",
        id: {
          type: "Identifier",
          loc: "21:16-21:19",
          name: "foo",
        },
        params: [],
        body: {
          type: "Block",
          loc: "21:22-21:24",
          body: [],
        },
        async: false,
        generator: false,
        has_use_strict_directive: false,
      },
      specifiers: [],
      source: null,
    },
    {
      type: "ExportNamedDeclaration",
      loc: "22:0-22:31",
      declaration: {
        type: "FunctionDeclaration",
        loc: "22:7-22:31",
        id: {
          type: "Identifier",
          loc: "22:22-22:26",
          name: "foo2",
        },
        params: [],
        body: {
          type: "Block",
          loc: "22:29-22:31",
          body: [],
        },
        async: true,
        generator: false,
        has_use_strict_directive: false,
      },
      specifiers: [],
      source: null,
    },
    {
      type: "ExportDefaultDeclaration",
      loc: "24:0-24:33",
      declaration: {
        type: "FunctionDeclaration",
        loc: "24:15-24:33",
        id: {
          type: "Identifier",
          loc: "24:24-24:28",
          name: "foo3",
        },
        params: [],
        body: {
          type: "Block",
          loc: "24:31-24:33",
          body: [],
        },
        async: false,
        generator: false,
        has_use_strict_directive: false,
      },
    },
    {
      type: "ExportDefaultDeclaration",
      loc: "25:0-25:29",
      declaration: {
        type: "FunctionDeclaration",
        loc: "25:15-25:29",
        id: null,
        params: [],
        body: {
          type: "Block",
          loc: "25:27-25:29",
          body: [],
        },
        async: false,
        generator: false,
        has_use_strict_directive: false,
      },
    },
    {
      type: "ExportDefaultDeclaration",
      loc: "26:0-26:39",
      declaration: {
        type: "FunctionDeclaration",
        loc: "26:15-26:39",
        id: {
          type: "Identifier",
          loc: "26:30-26:34",
          name: "foo4",
        },
        params: [],
        body: {
          type: "Block",
          loc: "26:37-26:39",
          body: [],
        },
        async: true,
        generator: false,
        has_use_strict_directive: false,
      },
    },
    {
      type: "ExportDefaultDeclaration",
      loc: "27:0-27:35",
      declaration: {
        type: "FunctionDeclaration",
        loc: "27:15-27:35",
        id: null,
        params: [],
        body: {
          type: "Block",
          loc: "27:33-27:35",
          body: [],
        },
        async: true,
        generator: false,
        has_use_strict_directive: false,
      },
    },
    {
      type: "ExportDefaultDeclaration",
      loc: "29:0-29:26",
      declaration: {
        type: "ClassDeclaration",
        loc: "29:15-29:26",
        id: {
          type: "Identifier",
          loc: "29:21-29:23",
          name: "C2",
        },
        superClass: null,
        body: {
          type: "ClassBody",
          loc: "29:15-29:26",
          body: [],
        },
      },
    },
    {
      type: "ExportDefaultDeclaration",
      loc: "30:0-30:23",
      declaration: {
        type: "ClassDeclaration",
        loc: "30:15-30:23",
        id: null,
        superClass: null,
        body: {
          type: "ClassBody",
          loc: "30:15-30:23",
          body: [],
        },
      },
    },
    {
      type: "ExportDefaultDeclaration",
      loc: "32:0-32:18",
      declaration: {
        type: "ExpressionStatement",
        loc: "32:15-32:18",
        kind: {
          type: "Identifier",
          loc: "32:15-32:17",
          name: "a6",
        },
      },
    },
    {
      type: "ExportDefaultDeclaration",
      loc: "33:0-33:21",
      declaration: {
        type: "ExpressionStatement",
        loc: "33:15-33:21",
        kind: {
          type: "BinaryExpression",
          loc: "33:15-33:20",
          operator: "+",
          left: {
            type: "Literal",
            loc: "33:15-33:16",
            value: 1,
          },
          right: {
            type: "Literal",
            loc: "33:19-33:20",
            value: 2,
          },
        },
      },
    },
    {
      type: "ExportAllDeclaration",
      loc: "35:0-35:22",
      exported: null,
      source: {
        type: "Literal",
        loc: "35:14-35:21",
        value: "other",
      },
    },
    {
      type: "ExportAllDeclaration",
      loc: "36:0-36:27",
      exported: {
        type: "Identifier",
        loc: "36:12-36:13",
        name: "a",
      },
      source: {
        type: "Literal",
        loc: "36:19-36:26",
        value: "other",
      },
    },
    {
      type: "ExportAllDeclaration",
      loc: "37:0-37:29",
      exported: {
        type: "Literal",
        loc: "37:12-37:15",
        value: "a",
      },
      source: {
        type: "Literal",
        loc: "37:21-37:28",
        value: "other",
      },
    },
  ],
  sourceType: "module",
  has_use_strict_directive: false,
}