{
  type: "Program",
  loc: "1:0-1:32",
  body: [
    {
      type: "ExportDefaultDeclaration",
      loc: "1:0-1:32",
      declaration: {
        type: "FunctionDeclaration",
        loc: "1:15-1:32",
        id: {
          type: "Identifier",
          loc: "1:24-1:27",
          name: "foo",
        },
        params: [],
        body: {
          type: "Block",
          loc: "1:30-1:32",
          body: [],
        },
        async: false,
        generator: false,
        has_use_strict_directive: false,
      },
    },
  ],
  sourceType: "module",
  has_use_strict_directive: false,
}