{
  type: "Program",
  loc: "1:0-1:38",
  body: [
    {
      type: "ExportDefaultDeclaration",
      loc: "1:0-1:38",
      declaration: {
        type: "FunctionDeclaration",
        loc: "1:15-1:38",
        id: {
          type: "Identifier",
          loc: "1:30-1:33",
          name: "foo",
        },
        params: [],
        body: {
          type: "Block",
          loc: "1:36-1:38",
          body: [],
        },
        async: true,
        generator: false,
        has_use_strict_directive: false,
      },
    },
  ],
  sourceType: "module",
  has_use_strict_directive: false,
}