{
  type: "Program",
  loc: "1:1-16:2",
  body: [
    {
      type: "ExpressionStatement",
      loc: "2:1-2:13",
      kind: {
        type: "MetaProperty",
        loc: "2:1-2:12",
        meta: {
          type: "Identifier",
          loc: "2:1-2:12",
          name: "import",
        },
        property: {
          type: "Identifier",
          loc: "2:1-2:12",
          name: "meta",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:12",
      kind: {
        type: "MetaProperty",
        loc: "3:1-3:12",
        meta: {
          type: "Identifier",
          loc: "3:1-3:12",
          name: "import",
        },
        property: {
          type: "Identifier",
          loc: "3:1-3:12",
          name: "meta",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "6:1-6:16",
      kind: {
        type: "CallExpression",
        loc: "6:1-6:15",
        callee: {
          type: "MetaProperty",
          loc: "6:1-6:12",
          meta: {
            type: "Identifier",
            loc: "6:1-6:12",
            name: "import",
          },
          property: {
            type: "Identifier",
            loc: "6:1-6:12",
            name: "meta",
          },
        },
        arguments: [
          {
            type: "Literal",
            loc: "6:13-6:14",
            value: 1,
          },
        ],
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:17",
      kind: {
        type: "BinaryExpression",
        loc: "7:1-7:16",
        operator: "+",
        left: {
          type: "MetaProperty",
          loc: "7:1-7:12",
          meta: {
            type: "Identifier",
            loc: "7:1-7:12",
            name: "import",
          },
          property: {
            type: "Identifier",
            loc: "7:1-7:12",
            name: "meta",
          },
        },
        right: {
          type: "Literal",
          loc: "7:15-7:16",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "8:1-8:17",
      kind: {
        type: "MemberExpression",
        loc: "8:1-8:16",
        object: {
          type: "MetaProperty",
          loc: "8:1-8:12",
          meta: {
            type: "Identifier",
            loc: "8:1-8:12",
            name: "import",
          },
          property: {
            type: "Identifier",
            loc: "8:1-8:12",
            name: "meta",
          },
        },
        property: {
          type: "Identifier",
          loc: "8:13-8:16",
          name: "foo",
        },
        computed: false,
        optional: false,
      },
    },
    {
      type: "FunctionDeclaration",
      loc: "10:1-16:2",
      id: {
        type: "Identifier",
        loc: "10:10-10:14",
        name: "test",
      },
      params: [],
      body: {
        type: "Block",
        loc: "10:17-16:2",
        body: [
          {
            type: "ExpressionStatement",
            loc: "12:3-12:15",
            kind: {
              type: "MetaProperty",
              loc: "12:3-12:14",
              meta: {
                type: "Identifier",
                loc: "12:3-12:14",
                name: "import",
              },
              property: {
                type: "Identifier",
                loc: "12:3-12:14",
                name: "meta",
              },
            },
          },
          {
            type: "ExpressionStatement",
            loc: "15:3-15:19",
            kind: {
              type: "NewExpression",
              loc: "15:3-15:18",
              callee: {
                type: "MetaProperty",
                loc: "15:7-15:18",
                meta: {
                  type: "Identifier",
                  loc: "15:7-15:18",
                  name: "import",
                },
                property: {
                  type: "Identifier",
                  loc: "15:7-15:18",
                  name: "meta",
                },
              },
              arguments: [],
            },
          },
        ],
      },
      async: false,
      generator: false,
      has_use_strict_directive: false,
    },
  ],
  sourceType: "module",
  has_use_strict_directive: false,
}