{
  type: "Program",
  loc: "1:0-27:11",
  body: [
    {
      type: "ImportDeclaration",
      loc: "1:0-1:11",
      specifiers: [],
      source: {
        type: "Literal",
        loc: "1:7-1:10",
        value: "a",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "3:0-3:24",
      specifiers: [
        {
          type: "ImportNamespaceSpecifier",
          loc: "3:7-3:14",
          local: {
            type: "Identifier",
            loc: "3:12-3:14",
            name: "a1",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "3:20-3:23",
        value: "b",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "6:0-6:19",
      specifiers: [
        {
          type: "ImportDefaultSpecifier",
          loc: "6:7-6:9",
          local: {
            type: "Identifier",
            loc: "6:7-6:9",
            name: "a2",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "6:15-6:18",
        value: "b",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "8:0-8:28",
      specifiers: [
        {
          type: "ImportDefaultSpecifier",
          loc: "8:7-8:9",
          local: {
            type: "Identifier",
            loc: "8:7-8:9",
            name: "a3",
          },
        },
        {
          type: "ImportNamespaceSpecifier",
          loc: "8:11-8:18",
          local: {
            type: "Identifier",
            loc: "8:16-8:18",
            name: "b1",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "8:24-8:27",
        value: "c",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "10:0-10:27",
      specifiers: [
        {
          type: "ImportDefaultSpecifier",
          loc: "10:7-10:9",
          local: {
            type: "Identifier",
            loc: "10:7-10:9",
            name: "a4",
          },
        },
        {
          type: "ImportSpecifier",
          loc: "10:13-10:15",
          imported: null,
          local: {
            type: "Identifier",
            loc: "10:13-10:15",
            name: "b2",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "10:23-10:26",
        value: "c",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "13:0-13:19",
      specifiers: [],
      source: {
        type: "Literal",
        loc: "13:15-13:18",
        value: "a",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "15:0-15:21",
      specifiers: [
        {
          type: "ImportSpecifier",
          loc: "15:8-15:10",
          imported: null,
          local: {
            type: "Identifier",
            loc: "15:8-15:10",
            name: "a5",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "15:17-15:20",
        value: "b",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "17:0-17:22",
      specifiers: [
        {
          type: "ImportSpecifier",
          loc: "17:8-17:10",
          imported: null,
          local: {
            type: "Identifier",
            loc: "17:8-17:10",
            name: "a6",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "17:18-17:21",
        value: "b",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "19:0-19:29",
      specifiers: [
        {
          type: "ImportSpecifier",
          loc: "19:8-19:10",
          imported: null,
          local: {
            type: "Identifier",
            loc: "19:8-19:10",
            name: "a7",
          },
        },
        {
          type: "ImportSpecifier",
          loc: "19:12-19:14",
          imported: null,
          local: {
            type: "Identifier",
            loc: "19:12-19:14",
            name: "b3",
          },
        },
        {
          type: "ImportSpecifier",
          loc: "19:16-19:18",
          imported: null,
          local: {
            type: "Identifier",
            loc: "19:16-19:18",
            name: "c1",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "19:25-19:28",
        value: "d",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "21:0-21:41",
      specifiers: [
        {
          type: "ImportSpecifier",
          loc: "21:8-21:16",
          imported: {
            type: "Identifier",
            loc: "21:8-21:10",
            name: "a8",
          },
          local: {
            type: "Identifier",
            loc: "21:14-21:16",
            name: "b4",
          },
        },
        {
          type: "ImportSpecifier",
          loc: "21:18-21:20",
          imported: null,
          local: {
            type: "Identifier",
            loc: "21:18-21:20",
            name: "c2",
          },
        },
        {
          type: "ImportSpecifier",
          loc: "21:22-21:30",
          imported: {
            type: "Identifier",
            loc: "21:22-21:24",
            name: "d1",
          },
          local: {
            type: "Identifier",
            loc: "21:28-21:30",
            name: "e1",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "21:37-21:40",
        value: "f",
      },
    },
    {
      type: "ImportDeclaration",
      loc: "23:0-23:39",
      specifiers: [
        {
          type: "ImportSpecifier",
          loc: "23:8-23:17",
          imported: {
            type: "Literal",
            loc: "23:8-23:11",
            value: "a",
          },
          local: {
            type: "Identifier",
            loc: "23:15-23:17",
            name: "b5",
          },
        },
        {
          type: "ImportSpecifier",
          loc: "23:19-23:28",
          imported: {
            type: "Literal",
            loc: "23:19-23:22",
            value: "c",
          },
          local: {
            type: "Identifier",
            loc: "23:26-23:28",
            name: "d2",
          },
        },
      ],
      source: {
        type: "Literal",
        loc: "23:35-23:38",
        value: "e",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "25:0-25:10",
      kind: {
        type: "ImportExpression",
        loc: "25:0-25:10",
        source: {
          type: "Identifier",
          loc: "25:7-25:9",
          name: "a1",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "27:0-27:11",
      kind: {
        type: "ImportExpression",
        loc: "27:0-27:10",
        source: {
          type: "Identifier",
          loc: "27:7-27:9",
          name: "a1",
        },
      },
    },
  ],
  sourceType: "module",
  has_use_strict_directive: false,
}