{
  type: "Program",
  loc: "1:0-5:6",
  body: [
    {
      type: "ImportDeclaration",
      loc: "1:0-1:11",
      specifiers: [],
      source: {
        type: "Literal",
        loc: "1:7-1:10",
        value: "a",
      },
    },
    {
      type: "FunctionDeclaration",
      loc: "3:0-3:17",
      id: {
        type: "Identifier",
        loc: "3:9-3:12",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "3:15-3:17",
        body: [],
      },
      async: false,
      generator: false,
      has_use_strict_directive: false,
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:6",
      kind: {
        type: "BinaryExpression",
        loc: "5:0-5:5",
        operator: "+",
        left: {
          type: "Literal",
          loc: "5:0-5:1",
          value: 1,
        },
        right: {
          type: "Literal",
          loc: "5:4-5:5",
          value: 2,
        },
      },
    },
  ],
  sourceType: "module",
  has_use_strict_directive: false,
}