[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 4
     0: 11 ff 00         NewClosure r0, c0
     3: 07 ff 01         StoreGlobal r0, c1
     6: 06 ff 01         LoadGlobal r0, c1
     9: 08 ff ff ff 00   Call r0, r0, r0, 0
    14: 06 ff 01         LoadGlobal r0, c1
    17: 03 fe 01         LoadImmediate r1, 1
    20: 03 fd 02         LoadImmediate r2, 2
    23: 03 fc 03         LoadImmediate r3, 3
    26: 08 ff ff fe 03   Call r0, r0, r1, 3
    31: 11 ff 02         NewClosure r0, c2
    34: 07 ff 03         StoreGlobal r0, c3
    37: 05 ff            LoadUndefined r0
    39: 09 ff            Ret r0
  Constant Table:
    0: [BytecodeFunction: foo]
    1: [String: foo]
    2: [BytecodeFunction: bar]
    3: [String: bar]
}

[BytecodeFunction: foo] {
  Parameters: 3, Registers: 1
    0: 05 ff   LoadUndefined r0
    2: 09 ff   Ret r0
}

[BytecodeFunction: bar] {
  Parameters: 1, Registers: 5
     0: 03 ff 02         LoadImmediate r0, 2
     3: 06 fe 00         LoadGlobal r1, c0
     6: 03 fd 01         LoadImmediate r2, 1
     9: 02 fc 05         Mov r3, a0
    12: 06 fb 00         LoadGlobal r4, c0
    15: 08 fe fe fd 03   Call r1, r1, r2, 3
    20: 0a ff ff fe      Add r0, r0, r1
  Constant Table:
    0: [String: foo]
}
