[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: StoreGlobal r0, c1
    6: LoadUndefined r0
    8: Ret r0
  Constant Table:
    0: [BytecodeFunction: testMemberCall]
    1: [String: testMemberCall]
}

[BytecodeFunction: testMemberCall] {
  Parameters: 1, Registers: 5
     0: GetNamedProperty r1, a0, c0
     4: CallWithReceiver r1, r1, a0, r1, 0
    10: GetNamedProperty r1, a0, c0
    14: LoadImmediate r2, 1
    17: LoadImmediate r3, 2
    20: LoadImmediate r4, 3
    23: CallWithReceiver r1, r1, a0, r2, 3
    29: LoadImmediate r1, 1
    32: LoadImmediate r2, 2
    35: Add r0, r1, r2
    39: GetNamedProperty r1, r0, c0
    43: LoadImmediate r2, 4
    46: CallWithReceiver r1, r1, r0, r2, 1
    52: LoadUndefined r1
    54: Ret r1
  Constant Table:
    0: [String: foo]
}
