[package]
name = "brimstone_macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full", "visit-mut"] }
quote.workspace = true