[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewClosure r0, c8
    31: StoreGlobal r0, c9, k4
    35: NewClosure r0, c10
    38: StoreGlobal r0, c11, k5
    42: NewClosure r0, c12
    45: StoreGlobal r0, c13, k6
    49: NewClosure r0, c14
    52: StoreGlobal r0, c15, k7
    56: NewClosure r0, c16
    59: StoreGlobal r0, c17, k8
    63: LoadUndefined r0
    65: Ret r0
  Constant Table:
    0: [BytecodeFunction: testEmptyArray]
    1: [String: testEmptyArray]
    2: [BytecodeFunction: testArrayWithOneElement]
    3: [String: testArrayWithOneElement]
    4: [BytecodeFunction: testArrayWithElements]
    5: [String: testArrayWithElements]
    6: [BytecodeFunction: testArrayWithHolesAndElements]
    7: [String: testArrayWithHolesAndElements]
    8: [BytecodeFunction: testArrayWithOnlyHoles]
    9: [String: testArrayWithOnlyHoles]
    10: [BytecodeFunction: onlySpread]
    11: [String: onlySpread]
    12: [BytecodeFunction: multipleSpreads]
    13: [String: multipleSpreads]
    14: [BytecodeFunction: temporaryRegisterToAvoidClobbering]
    15: [String: temporaryRegisterToAvoidClobbering]
    16: [BytecodeFunction: noTemporaryRegisterNeededForEmptyObject]
    17: [String: noTemporaryRegisterNeededForEmptyObject]
}

[BytecodeFunction: testEmptyArray] {
  Parameters: 0, Registers: 1
    0: NewArray r0, 0
    3: Ret r0
}

[BytecodeFunction: testArrayWithOneElement] {
  Parameters: 0, Registers: 3
     0: NewArray r0, 1
     3: LoadImmediate r1, 0
     6: LoadImmediate r2, 1
     9: SetArrayProperty r0, r1, r2
    13: Ret r0
}

[BytecodeFunction: testArrayWithElements] {
  Parameters: 0, Registers: 3
     0: NewArray r0, 3
     3: LoadImmediate r1, 0
     6: LoadImmediate r2, 1
     9: SetArrayProperty r0, r1, r2
    13: Inc r1
    15: LoadImmediate r2, 2
    18: SetArrayProperty r0, r1, r2
    22: Inc r1
    24: LoadImmediate r2, 3
    27: SetArrayProperty r0, r1, r2
    31: Ret r0
}

[BytecodeFunction: testArrayWithHolesAndElements] {
  Parameters: 0, Registers: 3
     0: NewArray r0, 7
     3: LoadImmediate r1, 0
     6: LoadImmediate r2, 1
     9: SetArrayProperty r0, r1, r2
    13: Inc r1
    15: LoadEmpty r2
    17: SetArrayProperty r0, r1, r2
    21: Inc r1
    23: LoadImmediate r2, 2
    26: SetArrayProperty r0, r1, r2
    30: Inc r1
    32: LoadEmpty r2
    34: SetArrayProperty r0, r1, r2
    38: Inc r1
    40: LoadEmpty r2
    42: SetArrayProperty r0, r1, r2
    46: Inc r1
    48: LoadImmediate r2, 3
    51: SetArrayProperty r0, r1, r2
    55: Inc r1
    57: LoadEmpty r2
    59: SetArrayProperty r0, r1, r2
    63: Ret r0
}

[BytecodeFunction: testArrayWithOnlyHoles] {
  Parameters: 0, Registers: 3
     0: NewArray r0, 3
     3: LoadImmediate r1, 0
     6: LoadEmpty r2
     8: SetArrayProperty r0, r1, r2
    12: Inc r1
    14: LoadEmpty r2
    16: SetArrayProperty r0, r1, r2
    20: Inc r1
    22: LoadEmpty r2
    24: SetArrayProperty r0, r1, r2
    28: Ret r0
}

[BytecodeFunction: onlySpread] {
  Parameters: 1, Registers: 6
     0: NewArray r0, 0
     3: LoadImmediate r1, 0
     6: GetIterator r2, r3, a0
  .L0:
    10: IteratorNext r4, r5, r2, r3
    15: JumpTrue r5, 11 (.L1)
    18: SetArrayProperty r0, r1, r4
    22: Inc r1
    24: Jump -14 (.L0)
  .L1:
    26: Ret r0
}

[BytecodeFunction: multipleSpreads] {
  Parameters: 3, Registers: 6
     0: NewArray r0, 1
     3: LoadImmediate r1, 0
     6: GetIterator r2, r3, a0
  .L0:
    10: IteratorNext r4, r5, r2, r3
    15: JumpTrue r5, 11 (.L1)
    18: SetArrayProperty r0, r1, r4
    22: Inc r1
    24: Jump -14 (.L0)
  .L1:
    26: GetIterator r2, r3, a1
  .L2:
    30: IteratorNext r4, r5, r2, r3
    35: JumpTrue r5, 11 (.L3)
    38: SetArrayProperty r0, r1, r4
    42: Inc r1
    44: Jump -14 (.L2)
  .L3:
    46: LoadImmediate r2, 1
    49: SetArrayProperty r0, r1, r2
    53: Inc r1
    55: GetIterator r2, r3, a2
  .L4:
    59: IteratorNext r4, r5, r2, r3
    64: JumpTrue r5, 11 (.L5)
    67: SetArrayProperty r0, r1, r4
    71: Inc r1
    73: Jump -14 (.L4)
  .L5:
    75: Ret r0
}

[BytecodeFunction: temporaryRegisterToAvoidClobbering] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r0, 1
     3: NewArray r1, 1
     6: LoadImmediate r2, 0
     9: LoadImmediate r3, 2
    12: SetArrayProperty r1, r2, r3
    16: Mov r0, r1
    19: LoadUndefined r1
    21: Ret r1
}

[BytecodeFunction: noTemporaryRegisterNeededForEmptyObject] {
  Parameters: 0, Registers: 2
    0: LoadImmediate r0, 1
    3: NewArray r0, 0
    6: LoadUndefined r1
    8: Ret r1
}
