[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
      0: NewClosure r0, c0
      3: StoreGlobal r0, c1, k0
      7: NewClosure r0, c2
     10: StoreGlobal r0, c3, k1
     14: NewClosure r0, c4
     17: StoreGlobal r0, c5, k2
     21: NewClosure r0, c6
     24: StoreGlobal r0, c7, k3
     28: NewClosure r0, c8
     31: StoreGlobal r0, c9, k4
     35: NewClosure r0, c10
     38: StoreGlobal r0, c11, k5
     42: NewClosure r0, c12
     45: StoreGlobal r0, c13, k6
     49: NewClosure r0, c14
     52: StoreGlobal r0, c15, k7
     56: NewClosure r0, c16
     59: StoreGlobal r0, c17, k8
     63: NewClosure r0, c18
     66: StoreGlobal r0, c19, k9
     70: NewClosure r0, c20
     73: StoreGlobal r0, c21, k10
     77: NewClosure r0, c22
     80: StoreGlobal r0, c23, k11
     84: NewClosure r0, c24
     87: StoreGlobal r0, c25, k12
     91: LoadImmediate r0, 1
     94: StoreGlobal r0, c26, k13
     98: PushLexicalScope c27
    100: NewObject r0
    102: StoreToScope r0, 0, 0
    106: NewClosure r1, c29
    109: DefineNamedProperty r0, c28, r1
    113: NewClosure r1, c31
    116: DefineNamedProperty r0, c30, r1
    120: PopScope 
    121: LoadUndefined r0
    123: Ret r0
  Constant Table:
    0: [BytecodeFunction: use]
    1: [String: use]
    2: [BytecodeFunction: testIdAssign]
    3: [String: testIdAssign]
    4: [BytecodeFunction: testIdAssignReturnValue]
    5: [String: testIdAssignReturnValue]
    6: [BytecodeFunction: testNamedMemberAssign]
    7: [String: testNamedMemberAssign]
    8: [BytecodeFunction: testComputedMemberAssign]
    9: [String: testComputedMemberAssign]
    10: [BytecodeFunction: named]
    11: [String: named]
    12: [BytecodeFunction: operatorIdAssign]
    13: [String: operatorIdAssign]
    14: [BytecodeFunction: operatorIdAssignReturnValue]
    15: [String: operatorIdAssignReturnValue]
    16: [BytecodeFunction: objectDestructuringAssign]
    17: [String: objectDestructuringAssign]
    18: [BytecodeFunction: operatorIdAllOperators]
    19: [String: operatorIdAllOperators]
    20: [BytecodeFunction: operatorMemberAssign]
    21: [String: operatorMemberAssign]
    22: [BytecodeFunction: operatorMemberAllOperators]
    23: [String: operatorMemberAllOperators]
    24: [BytecodeFunction: tdzCheck]
    25: [String: tdzCheck]
    26: [String: global]
    27: [ScopeNames]
    28: [String: testSuperNamedMemberAssign]
    29: [BytecodeFunction: testSuperNamedMemberAssign]
    30: [String: testSuperComputedMemberAssign]
    31: [BytecodeFunction: testSuperComputedMemberAssign]
}

[BytecodeFunction: use] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: testIdAssign] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 2
     3: LoadImmediate a0, 3
     6: LoadImmediate r0, 4
     9: LoadImmediate r1, 5
    12: StoreGlobal r1, c0, k0
    16: LoadUndefined r1
    18: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: testIdAssignReturnValue] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 2
     3: LoadGlobal r1, c0, k0
     7: LoadImmediate a0, 3
    10: Mov r2, a0
    13: Call r1, r1, r2, 1
    18: LoadGlobal r1, c0, k1
    22: LoadImmediate r0, 4
    25: Mov r2, r0
    28: Call r1, r1, r2, 1
    33: LoadGlobal r1, c0, k2
    37: LoadImmediate r2, 5
    40: StoreGlobal r2, c1, k3
    44: Call r1, r1, r2, 1
    49: LoadImmediate r1, 6
    52: StoreGlobal r1, c1, k4
    56: Mov a0, r1
    59: Mov r0, a0
    62: LoadUndefined r1
    64: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: testNamedMemberAssign] {
  Parameters: 2, Registers: 3
     0: LoadImmediate r0, 1
     3: SetNamedProperty a0, c0, r0, k0
     8: LoadGlobal r0, c1, k1
    12: Mov r2, a0
    15: LoadImmediate r1, 2
    18: SetNamedProperty r2, c0, r1, k2
    23: Call r0, r0, r1, 1
    28: Mov r1, a0
    31: Mov r2, a0
    34: LoadImmediate r0, 3
    37: SetNamedProperty r2, c2, r0, k3
    42: SetNamedProperty r1, c0, r0, k4
    47: LoadGlobal r0, c1, k5
    51: Mov r2, a0
    54: Mov r1, a0
    57: SetNamedProperty r2, c0, r1, k6
    62: Call r0, r0, r1, 1
    67: Mov r1, a0
    70: LoadImmediate r0, 4
    73: SetNamedProperty r1, c0, r0, k7
    78: Mov a1, r0
    81: LoadUndefined r0
    83: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: testComputedMemberAssign] {
  Parameters: 2, Registers: 5
     0: LoadConstant r1, c0
     3: LoadImmediate r0, 1
     6: SetProperty a0, r1, r0
    10: LoadGlobal r0, c1, k0
    14: Mov r2, a0
    17: LoadConstant r3, c0
    20: LoadImmediate r1, 2
    23: SetProperty r2, r3, r1
    27: Call r0, r0, r1, 1
    32: Mov r1, a0
    35: LoadConstant r2, c0
    38: Mov r3, a0
    41: LoadConstant r4, c2
    44: LoadImmediate r0, 3
    47: SetProperty r3, r4, r0
    51: SetProperty r1, r2, r0
    55: LoadGlobal r0, c1, k1
    59: Mov r2, a0
    62: LoadConstant r3, c0
    65: Mov r1, a0
    68: SetProperty r2, r3, r1
    72: Call r0, r0, r1, 1
    77: Mov r1, a0
    80: LoadConstant r2, c0
    83: LoadImmediate r0, 4
    86: SetProperty r1, r2, r0
    90: Mov a1, r0
    93: LoadUndefined r0
    95: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: testSuperNamedMemberAssign] {
  Parameters: 1, Registers: 5
      0: LoadFromScope r1, 0, 0
      4: LoadConstant r2, c0
      7: LoadImmediate r0, 1
     10: SetSuperProperty r1, <this>, r2, r0
     15: LoadGlobal r0, c1, k0
     19: LoadFromScope r2, 0, 0
     23: LoadConstant r3, c0
     26: LoadImmediate r1, 2
     29: SetSuperProperty r2, <this>, r3, r1
     34: Call r0, r0, r1, 1
     39: LoadFromScope r1, 0, 0
     43: LoadConstant r2, c0
     46: LoadFromScope r3, 0, 0
     50: LoadConstant r4, c2
     53: LoadImmediate r0, 3
     56: SetSuperProperty r3, <this>, r4, r0
     61: SetSuperProperty r1, <this>, r2, r0
     66: LoadGlobal r0, c1, k1
     70: LoadFromScope r2, 0, 0
     74: LoadConstant r3, c0
     77: Mov r1, a0
     80: SetSuperProperty r2, <this>, r3, r1
     85: Call r0, r0, r1, 1
     90: LoadFromScope r1, 0, 0
     94: LoadConstant r2, c0
     97: LoadImmediate r0, 4
    100: SetSuperProperty r1, <this>, r2, r0
    105: Mov a0, r0
    108: LoadUndefined r0
    110: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: testSuperComputedMemberAssign] {
  Parameters: 1, Registers: 5
      0: LoadFromScope r1, 0, 0
      4: LoadConstant r2, c0
      7: LoadImmediate r0, 1
     10: SetSuperProperty r1, <this>, r2, r0
     15: LoadGlobal r0, c1, k0
     19: LoadFromScope r2, 0, 0
     23: LoadConstant r3, c0
     26: LoadImmediate r1, 2
     29: SetSuperProperty r2, <this>, r3, r1
     34: Call r0, r0, r1, 1
     39: LoadFromScope r1, 0, 0
     43: LoadConstant r2, c0
     46: LoadFromScope r3, 0, 0
     50: LoadConstant r4, c2
     53: LoadImmediate r0, 3
     56: SetSuperProperty r3, <this>, r4, r0
     61: SetSuperProperty r1, <this>, r2, r0
     66: LoadGlobal r0, c1, k1
     70: LoadFromScope r2, 0, 0
     74: LoadConstant r3, c0
     77: Mov r1, a0
     80: SetSuperProperty r2, <this>, r3, r1
     85: Call r0, r0, r1, 1
     90: LoadFromScope r1, 0, 0
     94: LoadConstant r2, c0
     97: LoadImmediate r0, 4
    100: SetSuperProperty r1, <this>, r2, r0
    105: Mov a0, r0
    108: LoadUndefined r0
    110: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: named] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: NewClosure r0, c0
     6: NewClosure r0, c1
     9: NewClosure r1, c3
    12: SetNamedProperty r0, c2, r1, k0
    17: NewClosure r1, c4
    20: Add r0, r0, r1
    24: LoadUndefined r1
    26: Ret r1
  Constant Table:
    0: [BytecodeFunction: x]
    1: [BytecodeFunction: <anonymous>]
    2: [String: foo]
    3: [BytecodeFunction: <anonymous>]
    4: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: x] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: operatorIdAssign] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 2
     3: LoadImmediate r1, 3
     6: Add a0, a0, r1
    10: LoadImmediate r1, 4
    13: Add r0, r0, r1
    17: LoadGlobal r1, c0, k0
    21: LoadImmediate r2, 5
    24: Add r1, r1, r2
    28: StoreGlobal r1, c0, k1
    32: LoadUndefined r1
    34: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: operatorIdAssignReturnValue] {
  Parameters: 1, Registers: 5
      0: LoadImmediate r0, 2
      3: LoadGlobal r1, c0, k0
      7: Mov r2, a0
     10: LoadImmediate r3, 3
     13: Add a0, r2, r3
     17: Mov r2, a0
     20: Call r1, r1, r2, 1
     25: LoadGlobal r1, c0, k1
     29: Mov r2, r0
     32: LoadImmediate r3, 4
     35: Add r0, r2, r3
     39: Mov r2, r0
     42: Call r1, r1, r2, 1
     47: LoadGlobal r1, c0, k2
     51: LoadGlobal r2, c1, k3
     55: LoadImmediate r3, 5
     58: Add r2, r2, r3
     62: StoreGlobal r2, c1, k4
     66: Call r1, r1, r2, 1
     71: Mov r1, r0
     74: Mov r2, a0
     77: LoadGlobal r3, c1, k5
     81: LoadImmediate r4, 6
     84: Add r3, r3, r4
     88: StoreGlobal r3, c1, k6
     92: Add a0, r2, r3
     96: Add r0, r1, a0
    100: LoadUndefined r1
    102: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: objectDestructuringAssign] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r2, 1
     3: GetNamedProperty r1, r2, c0, k0
     8: LoadImmediate r2, 2
    11: GetNamedProperty r1, r2, c0, k1
    16: Mov a0, r2
    19: LoadImmediate r2, 3
    22: GetNamedProperty r1, r2, c0, k2
    27: Mov r0, r2
    30: LoadImmediate r2, 4
    33: GetNamedProperty r1, r2, c0, k3
    38: StoreGlobal r2, c1, k4
    42: LoadUndefined r2
    44: Ret r2
  Constant Table:
    0: [String: a]
    1: [String: global]
}

[BytecodeFunction: operatorIdAllOperators] {
  Parameters: 1, Registers: 1
     0: LoadImmediate r0, 1
     3: Add a0, a0, r0
     7: LoadImmediate r0, 2
    10: Sub a0, a0, r0
    14: LoadImmediate r0, 3
    17: Mul a0, a0, r0
    21: LoadImmediate r0, 4
    24: Div a0, a0, r0
    28: LoadImmediate r0, 5
    31: Rem a0, a0, r0
    35: LoadImmediate r0, 6
    38: Exp a0, a0, r0
    42: LoadImmediate r0, 7
    45: BitAnd a0, a0, r0
    49: LoadImmediate r0, 8
    52: BitOr a0, a0, r0
    56: LoadImmediate r0, 9
    59: BitXor a0, a0, r0
    63: LoadImmediate r0, 10
    66: ShiftLeft a0, a0, r0
    70: LoadImmediate r0, 11
    73: ShiftRightArithmetic a0, a0, r0
    77: LoadImmediate r0, 12
    80: ShiftRightLogical a0, a0, r0
    84: LoadUndefined r0
    86: Ret r0
}

[BytecodeFunction: operatorMemberAssign] {
  Parameters: 2, Registers: 5
      0: GetNamedProperty r0, a0, c0, k0
      5: LoadImmediate r1, 1
      8: Add r0, r0, r1
     12: SetNamedProperty a0, c0, r0, k1
     17: LoadGlobal r0, c1, k2
     21: Mov r2, a0
     24: GetNamedProperty r1, r2, c0, k3
     29: LoadImmediate r3, 2
     32: Add r1, r1, r3
     36: SetNamedProperty r2, c0, r1, k4
     41: Call r0, r0, r1, 1
     46: Mov r1, a0
     49: GetNamedProperty r0, r1, c0, k5
     54: Mov r3, a0
     57: GetNamedProperty r2, r3, c2, k6
     62: LoadImmediate r4, 3
     65: Add r2, r2, r4
     69: SetNamedProperty r3, c2, r2, k7
     74: Add r0, r0, r2
     78: SetNamedProperty r1, c0, r0, k8
     83: LoadGlobal r0, c1, k9
     87: Mov r2, a0
     90: GetNamedProperty r1, r2, c0, k10
     95: Mov r3, a0
     98: Add r1, r1, r3
    102: SetNamedProperty r2, c0, r1, k11
    107: Call r0, r0, r1, 1
    112: Mov r1, a0
    115: GetNamedProperty r0, r1, c0, k12
    120: LoadImmediate r2, 4
    123: Add r0, r0, r2
    127: SetNamedProperty r1, c0, r0, k13
    132: Mov a1, r0
    135: LoadUndefined r0
    137: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: operatorMemberAllOperators] {
  Parameters: 1, Registers: 2
      0: GetNamedProperty r0, a0, c0, k0
      5: LoadImmediate r1, 1
      8: Add r0, r0, r1
     12: SetNamedProperty a0, c0, r0, k1
     17: GetNamedProperty r0, a0, c0, k2
     22: LoadImmediate r1, 2
     25: Sub r0, r0, r1
     29: SetNamedProperty a0, c0, r0, k3
     34: GetNamedProperty r0, a0, c0, k4
     39: LoadImmediate r1, 3
     42: Mul r0, r0, r1
     46: SetNamedProperty a0, c0, r0, k5
     51: GetNamedProperty r0, a0, c0, k6
     56: LoadImmediate r1, 4
     59: Div r0, r0, r1
     63: SetNamedProperty a0, c0, r0, k7
     68: GetNamedProperty r0, a0, c0, k8
     73: LoadImmediate r1, 5
     76: Rem r0, r0, r1
     80: SetNamedProperty a0, c0, r0, k9
     85: GetNamedProperty r0, a0, c0, k10
     90: LoadImmediate r1, 6
     93: Exp r0, r0, r1
     97: SetNamedProperty a0, c0, r0, k11
    102: GetNamedProperty r0, a0, c0, k12
    107: LoadImmediate r1, 7
    110: BitAnd r0, r0, r1
    114: SetNamedProperty a0, c0, r0, k13
    119: GetNamedProperty r0, a0, c0, k14
    124: LoadImmediate r1, 8
    127: BitOr r0, r0, r1
    131: SetNamedProperty a0, c0, r0, k15
    136: GetNamedProperty r0, a0, c0, k16
    141: LoadImmediate r1, 9
    144: BitXor r0, r0, r1
    148: SetNamedProperty a0, c0, r0, k17
    153: GetNamedProperty r0, a0, c0, k18
    158: LoadImmediate r1, 10
    161: ShiftLeft r0, r0, r1
    165: SetNamedProperty a0, c0, r0, k19
    170: GetNamedProperty r0, a0, c0, k20
    175: LoadImmediate r1, 11
    178: ShiftRightArithmetic r0, r0, r1
    182: SetNamedProperty a0, c0, r0, k21
    187: GetNamedProperty r0, a0, c0, k22
    192: LoadImmediate r1, 12
    195: ShiftRightLogical r0, r0, r1
    199: SetNamedProperty a0, c0, r0, k23
    204: LoadUndefined r0
    206: Ret r0
  Constant Table:
    0: [String: foo]
}

[BytecodeFunction: tdzCheck] {
  Parameters: 0, Registers: 4
     0: PushFunctionScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: NewClosure r0, c1
    11: LoadImmediate r1, 0
    14: StoreToScope r1, 0, 0
    18: LoadImmediate r1, 1
    21: LoadFromScope r2, 0, 0
    25: CheckTdz r2, c2
    28: StoreToScope r1, 0, 0
    32: LoadImmediate r1, 2
    35: GetNamedProperty r2, r1, c2, k0
    40: LoadFromScope r3, 0, 0
    44: CheckTdz r3, c2
    47: StoreToScope r2, 0, 0
    51: LoadUndefined r1
    53: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner]
    2: [String: x]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: LoadUndefined r0
    9: Ret r0
  Constant Table:
    0: [String: x]
}
