[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
      0: NewClosure r0, c0
      3: StoreGlobal r0, c1
      6: NewClosure r0, c2
      9: StoreGlobal r0, c3
     12: NewClosure r0, c4
     15: StoreGlobal r0, c5
     18: NewClosure r0, c6
     21: StoreGlobal r0, c7
     24: NewClosure r0, c8
     27: StoreGlobal r0, c9
     30: NewClosure r0, c10
     33: StoreGlobal r0, c11
     36: NewClosure r0, c12
     39: StoreGlobal r0, c13
     42: NewClosure r0, c14
     45: StoreGlobal r0, c15
     48: NewClosure r0, c16
     51: StoreGlobal r0, c17
     54: NewClosure r0, c18
     57: StoreGlobal r0, c19
     60: NewClosure r0, c20
     63: StoreGlobal r0, c21
     66: NewClosure r0, c22
     69: StoreGlobal r0, c23
     72: NewClosure r0, c24
     75: StoreGlobal r0, c25
     78: LoadImmediate r0, 1
     81: StoreGlobal r0, c26
     84: PushLexicalScope c27
     86: NewObject r0
     88: StoreToScope r0, 0, 0
     92: NewClosure r1, c29
     95: DefineNamedProperty r0, c28, r1
     99: NewClosure r1, c31
    102: DefineNamedProperty r0, c30, r1
    106: PopScope 
    107: LoadUndefined r0
    109: Ret r0
  Constant Table:
    0: [BytecodeFunction: use]
    1: [String: use]
    2: [BytecodeFunction: testIdAssign]
    3: [String: testIdAssign]
    4: [BytecodeFunction: testIdAssignReturnValue]
    5: [String: testIdAssignReturnValue]
    6: [BytecodeFunction: testNamedMemberAssign]
    7: [String: testNamedMemberAssign]
    8: [BytecodeFunction: testComputedMemberAssign]
    9: [String: testComputedMemberAssign]
    10: [BytecodeFunction: named]
    11: [String: named]
    12: [BytecodeFunction: operatorIdAssign]
    13: [String: operatorIdAssign]
    14: [BytecodeFunction: operatorIdAssignReturnValue]
    15: [String: operatorIdAssignReturnValue]
    16: [BytecodeFunction: objectDestructuringAssign]
    17: [String: objectDestructuringAssign]
    18: [BytecodeFunction: operatorIdAllOperators]
    19: [String: operatorIdAllOperators]
    20: [BytecodeFunction: operatorMemberAssign]
    21: [String: operatorMemberAssign]
    22: [BytecodeFunction: operatorMemberAllOperators]
    23: [String: operatorMemberAllOperators]
    24: [BytecodeFunction: tdzCheck]
    25: [String: tdzCheck]
    26: [String: global]
    27: [ScopeNames]
    28: [String: testSuperNamedMemberAssign]
    29: [BytecodeFunction: testSuperNamedMemberAssign]
    30: [String: testSuperComputedMemberAssign]
    31: [BytecodeFunction: testSuperComputedMemberAssign]
}

[BytecodeFunction: use] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: testIdAssign] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 2
     3: LoadImmediate a0, 3
     6: LoadImmediate r0, 4
     9: LoadImmediate r1, 5
    12: StoreGlobal r1, c0
    15: LoadUndefined r1
    17: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: testIdAssignReturnValue] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 2
     3: LoadGlobal r1, c0
     6: LoadImmediate a0, 3
     9: Mov r2, a0
    12: Call r1, r1, r2, 1
    17: LoadGlobal r1, c0
    20: LoadImmediate r0, 4
    23: Mov r2, r0
    26: Call r1, r1, r2, 1
    31: LoadGlobal r1, c0
    34: LoadImmediate r2, 5
    37: StoreGlobal r2, c1
    40: Call r1, r1, r2, 1
    45: LoadImmediate r1, 6
    48: StoreGlobal r1, c1
    51: Mov a0, r1
    54: Mov r0, a0
    57: LoadUndefined r1
    59: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: testNamedMemberAssign] {
  Parameters: 2, Registers: 3
     0: LoadImmediate r0, 1
     3: SetNamedProperty a0, c0, r0, k0
     8: LoadGlobal r0, c1
    11: Mov r2, a0
    14: LoadImmediate r1, 2
    17: SetNamedProperty r2, c0, r1, k1
    22: Call r0, r0, r1, 1
    27: Mov r1, a0
    30: Mov r2, a0
    33: LoadImmediate r0, 3
    36: SetNamedProperty r2, c2, r0, k2
    41: SetNamedProperty r1, c0, r0, k3
    46: LoadGlobal r0, c1
    49: Mov r2, a0
    52: Mov r1, a0
    55: SetNamedProperty r2, c0, r1, k4
    60: Call r0, r0, r1, 1
    65: Mov r1, a0
    68: LoadImmediate r0, 4
    71: SetNamedProperty r1, c0, r0, k5
    76: Mov a1, r0
    79: LoadUndefined r0
    81: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: testComputedMemberAssign] {
  Parameters: 2, Registers: 5
     0: LoadConstant r1, c0
     3: LoadImmediate r0, 1
     6: SetProperty a0, r1, r0
    10: LoadGlobal r0, c1
    13: Mov r2, a0
    16: LoadConstant r3, c0
    19: LoadImmediate r1, 2
    22: SetProperty r2, r3, r1
    26: Call r0, r0, r1, 1
    31: Mov r1, a0
    34: LoadConstant r2, c0
    37: Mov r3, a0
    40: LoadConstant r4, c2
    43: LoadImmediate r0, 3
    46: SetProperty r3, r4, r0
    50: SetProperty r1, r2, r0
    54: LoadGlobal r0, c1
    57: Mov r2, a0
    60: LoadConstant r3, c0
    63: Mov r1, a0
    66: SetProperty r2, r3, r1
    70: Call r0, r0, r1, 1
    75: Mov r1, a0
    78: LoadConstant r2, c0
    81: LoadImmediate r0, 4
    84: SetProperty r1, r2, r0
    88: Mov a1, r0
    91: LoadUndefined r0
    93: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: testSuperNamedMemberAssign] {
  Parameters: 1, Registers: 5
      0: LoadFromScope r1, 0, 0
      4: LoadConstant r2, c0
      7: LoadImmediate r0, 1
     10: SetSuperProperty r1, <this>, r2, r0
     15: LoadGlobal r0, c1
     18: LoadFromScope r2, 0, 0
     22: LoadConstant r3, c0
     25: LoadImmediate r1, 2
     28: SetSuperProperty r2, <this>, r3, r1
     33: Call r0, r0, r1, 1
     38: LoadFromScope r1, 0, 0
     42: LoadConstant r2, c0
     45: LoadFromScope r3, 0, 0
     49: LoadConstant r4, c2
     52: LoadImmediate r0, 3
     55: SetSuperProperty r3, <this>, r4, r0
     60: SetSuperProperty r1, <this>, r2, r0
     65: LoadGlobal r0, c1
     68: LoadFromScope r2, 0, 0
     72: LoadConstant r3, c0
     75: Mov r1, a0
     78: SetSuperProperty r2, <this>, r3, r1
     83: Call r0, r0, r1, 1
     88: LoadFromScope r1, 0, 0
     92: LoadConstant r2, c0
     95: LoadImmediate r0, 4
     98: SetSuperProperty r1, <this>, r2, r0
    103: Mov a0, r0
    106: LoadUndefined r0
    108: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: testSuperComputedMemberAssign] {
  Parameters: 1, Registers: 5
      0: LoadFromScope r1, 0, 0
      4: LoadConstant r2, c0
      7: LoadImmediate r0, 1
     10: SetSuperProperty r1, <this>, r2, r0
     15: LoadGlobal r0, c1
     18: LoadFromScope r2, 0, 0
     22: LoadConstant r3, c0
     25: LoadImmediate r1, 2
     28: SetSuperProperty r2, <this>, r3, r1
     33: Call r0, r0, r1, 1
     38: LoadFromScope r1, 0, 0
     42: LoadConstant r2, c0
     45: LoadFromScope r3, 0, 0
     49: LoadConstant r4, c2
     52: LoadImmediate r0, 3
     55: SetSuperProperty r3, <this>, r4, r0
     60: SetSuperProperty r1, <this>, r2, r0
     65: LoadGlobal r0, c1
     68: LoadFromScope r2, 0, 0
     72: LoadConstant r3, c0
     75: Mov r1, a0
     78: SetSuperProperty r2, <this>, r3, r1
     83: Call r0, r0, r1, 1
     88: LoadFromScope r1, 0, 0
     92: LoadConstant r2, c0
     95: LoadImmediate r0, 4
     98: SetSuperProperty r1, <this>, r2, r0
    103: Mov a0, r0
    106: LoadUndefined r0
    108: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: named] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: NewClosure r0, c0
     6: NewClosure r0, c1
     9: NewClosure r1, c3
    12: SetNamedProperty r0, c2, r1, k0
    17: NewClosure r1, c4
    20: Add r0, r0, r1
    24: LoadUndefined r1
    26: Ret r1
  Constant Table:
    0: [BytecodeFunction: x]
    1: [BytecodeFunction: <anonymous>]
    2: [String: foo]
    3: [BytecodeFunction: <anonymous>]
    4: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: x] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: operatorIdAssign] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 2
     3: LoadImmediate r1, 3
     6: Add a0, a0, r1
    10: LoadImmediate r1, 4
    13: Add r0, r0, r1
    17: LoadGlobal r1, c0
    20: LoadImmediate r2, 5
    23: Add r1, r1, r2
    27: StoreGlobal r1, c0
    30: LoadUndefined r1
    32: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: operatorIdAssignReturnValue] {
  Parameters: 1, Registers: 5
     0: LoadImmediate r0, 2
     3: LoadGlobal r1, c0
     6: Mov r2, a0
     9: LoadImmediate r3, 3
    12: Add a0, r2, r3
    16: Mov r2, a0
    19: Call r1, r1, r2, 1
    24: LoadGlobal r1, c0
    27: Mov r2, r0
    30: LoadImmediate r3, 4
    33: Add r0, r2, r3
    37: Mov r2, r0
    40: Call r1, r1, r2, 1
    45: LoadGlobal r1, c0
    48: LoadGlobal r2, c1
    51: LoadImmediate r3, 5
    54: Add r2, r2, r3
    58: StoreGlobal r2, c1
    61: Call r1, r1, r2, 1
    66: Mov r1, r0
    69: Mov r2, a0
    72: LoadGlobal r3, c1
    75: LoadImmediate r4, 6
    78: Add r3, r3, r4
    82: StoreGlobal r3, c1
    85: Add a0, r2, r3
    89: Add r0, r1, a0
    93: LoadUndefined r1
    95: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: objectDestructuringAssign] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r2, 1
     3: GetNamedProperty r1, r2, c0, k0
     8: LoadImmediate r2, 2
    11: GetNamedProperty r1, r2, c0, k1
    16: Mov a0, r2
    19: LoadImmediate r2, 3
    22: GetNamedProperty r1, r2, c0, k2
    27: Mov r0, r2
    30: LoadImmediate r2, 4
    33: GetNamedProperty r1, r2, c0, k3
    38: StoreGlobal r2, c1
    41: LoadUndefined r2
    43: Ret r2
  Constant Table:
    0: [String: a]
    1: [String: global]
}

[BytecodeFunction: operatorIdAllOperators] {
  Parameters: 1, Registers: 1
     0: LoadImmediate r0, 1
     3: Add a0, a0, r0
     7: LoadImmediate r0, 2
    10: Sub a0, a0, r0
    14: LoadImmediate r0, 3
    17: Mul a0, a0, r0
    21: LoadImmediate r0, 4
    24: Div a0, a0, r0
    28: LoadImmediate r0, 5
    31: Rem a0, a0, r0
    35: LoadImmediate r0, 6
    38: Exp a0, a0, r0
    42: LoadImmediate r0, 7
    45: BitAnd a0, a0, r0
    49: LoadImmediate r0, 8
    52: BitOr a0, a0, r0
    56: LoadImmediate r0, 9
    59: BitXor a0, a0, r0
    63: LoadImmediate r0, 10
    66: ShiftLeft a0, a0, r0
    70: LoadImmediate r0, 11
    73: ShiftRightArithmetic a0, a0, r0
    77: LoadImmediate r0, 12
    80: ShiftRightLogical a0, a0, r0
    84: LoadUndefined r0
    86: Ret r0
}

[BytecodeFunction: operatorMemberAssign] {
  Parameters: 2, Registers: 5
      0: GetNamedProperty r0, a0, c0, k0
      5: LoadImmediate r1, 1
      8: Add r0, r0, r1
     12: SetNamedProperty a0, c0, r0, k1
     17: LoadGlobal r0, c1
     20: Mov r2, a0
     23: GetNamedProperty r1, r2, c0, k2
     28: LoadImmediate r3, 2
     31: Add r1, r1, r3
     35: SetNamedProperty r2, c0, r1, k3
     40: Call r0, r0, r1, 1
     45: Mov r1, a0
     48: GetNamedProperty r0, r1, c0, k4
     53: Mov r3, a0
     56: GetNamedProperty r2, r3, c2, k5
     61: LoadImmediate r4, 3
     64: Add r2, r2, r4
     68: SetNamedProperty r3, c2, r2, k6
     73: Add r0, r0, r2
     77: SetNamedProperty r1, c0, r0, k7
     82: LoadGlobal r0, c1
     85: Mov r2, a0
     88: GetNamedProperty r1, r2, c0, k8
     93: Mov r3, a0
     96: Add r1, r1, r3
    100: SetNamedProperty r2, c0, r1, k9
    105: Call r0, r0, r1, 1
    110: Mov r1, a0
    113: GetNamedProperty r0, r1, c0, k10
    118: LoadImmediate r2, 4
    121: Add r0, r0, r2
    125: SetNamedProperty r1, c0, r0, k11
    130: Mov a1, r0
    133: LoadUndefined r0
    135: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: operatorMemberAllOperators] {
  Parameters: 1, Registers: 2
      0: GetNamedProperty r0, a0, c0, k0
      5: LoadImmediate r1, 1
      8: Add r0, r0, r1
     12: SetNamedProperty a0, c0, r0, k1
     17: GetNamedProperty r0, a0, c0, k2
     22: LoadImmediate r1, 2
     25: Sub r0, r0, r1
     29: SetNamedProperty a0, c0, r0, k3
     34: GetNamedProperty r0, a0, c0, k4
     39: LoadImmediate r1, 3
     42: Mul r0, r0, r1
     46: SetNamedProperty a0, c0, r0, k5
     51: GetNamedProperty r0, a0, c0, k6
     56: LoadImmediate r1, 4
     59: Div r0, r0, r1
     63: SetNamedProperty a0, c0, r0, k7
     68: GetNamedProperty r0, a0, c0, k8
     73: LoadImmediate r1, 5
     76: Rem r0, r0, r1
     80: SetNamedProperty a0, c0, r0, k9
     85: GetNamedProperty r0, a0, c0, k10
     90: LoadImmediate r1, 6
     93: Exp r0, r0, r1
     97: SetNamedProperty a0, c0, r0, k11
    102: GetNamedProperty r0, a0, c0, k12
    107: LoadImmediate r1, 7
    110: BitAnd r0, r0, r1
    114: SetNamedProperty a0, c0, r0, k13
    119: GetNamedProperty r0, a0, c0, k14
    124: LoadImmediate r1, 8
    127: BitOr r0, r0, r1
    131: SetNamedProperty a0, c0, r0, k15
    136: GetNamedProperty r0, a0, c0, k16
    141: LoadImmediate r1, 9
    144: BitXor r0, r0, r1
    148: SetNamedProperty a0, c0, r0, k17
    153: GetNamedProperty r0, a0, c0, k18
    158: LoadImmediate r1, 10
    161: ShiftLeft r0, r0, r1
    165: SetNamedProperty a0, c0, r0, k19
    170: GetNamedProperty r0, a0, c0, k20
    175: LoadImmediate r1, 11
    178: ShiftRightArithmetic r0, r0, r1
    182: SetNamedProperty a0, c0, r0, k21
    187: GetNamedProperty r0, a0, c0, k22
    192: LoadImmediate r1, 12
    195: ShiftRightLogical r0, r0, r1
    199: SetNamedProperty a0, c0, r0, k23
    204: LoadUndefined r0
    206: Ret r0
  Constant Table:
    0: [String: foo]
}

[BytecodeFunction: tdzCheck] {
  Parameters: 0, Registers: 4
     0: PushFunctionScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: NewClosure r0, c1
    11: LoadImmediate r1, 0
    14: StoreToScope r1, 0, 0
    18: LoadImmediate r1, 1
    21: LoadFromScope r2, 0, 0
    25: CheckTdz r2, c2
    28: StoreToScope r1, 0, 0
    32: LoadImmediate r1, 2
    35: GetNamedProperty r2, r1, c2, k0
    40: LoadFromScope r3, 0, 0
    44: CheckTdz r3, c2
    47: StoreToScope r2, 0, 0
    51: LoadUndefined r1
    53: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner]
    2: [String: x]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: LoadUndefined r0
    9: Ret r0
  Constant Table:
    0: [String: x]
}
