[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: LoadUndefined r0
    14: Ret r0
  Constant Table:
    0: [BytecodeFunction: test1]
    1: [String: test1]
    2: [BytecodeFunction: privateIn]
    3: [String: privateIn]
}

[BytecodeFunction: test1] {
  Parameters: 2, Registers: 1
      0: Add r0, a0, a1, ic0
      5: Sub r0, a0, a1, ic1
     10: Mul r0, a0, a1, ic2
     15: Div r0, a0, a1, ic3
     20: Rem r0, a0, a1, ic4
     25: Exp r0, a0, a1, ic5
     30: LooseEqual r0, a0, a1
     34: LooseNotEqual r0, a0, a1
     38: StrictEqual r0, a0, a1
     42: StrictNotEqual r0, a0, a1
     46: LessThan r0, a0, a1
     50: LessThanOrEqual r0, a0, a1
     54: GreaterThan r0, a0, a1
     58: GreaterThanOrEqual r0, a0, a1
     62: BitAnd r0, a0, a1, ic6
     67: BitOr r0, a0, a1, ic7
     72: BitXor r0, a0, a1, ic8
     77: ShiftLeft r0, a0, a1, ic9
     82: ShiftRightArithmetic r0, a0, a1, ic10
     87: ShiftRightLogical r0, a0, a1, ic11
     92: LoadConstant r0, c0
     95: In r0, a1, r0
     99: InstanceOf r0, a0, a1
    103: LoadUndefined r0
    105: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: privateIn] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: NewPrivateSymbol r2, c1
     7: StoreToScope r2, 1, 0
    11: NewClosure r2, c2
    14: NewClass r0, c4, c3, r1, r2
    20: PopScope 
    21: LoadUndefined r1
    23: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: field]
    2: [BytecodeFunction: method]
    3: [BytecodeFunction: C]
    4: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: CallWithReceiver r0, r0, <this>, r0, 0
     9: LoadUndefined r0
    11: Ret r0
  Constant Table:
    0: [BytecodeFunction: fieldsInitializer]
}

[BytecodeFunction: fieldsInitializer] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadFromScope r1, 1, 0
     7: DefinePrivateProperty <this>, r1, r0, 0
    12: LoadUndefined r0
    14: Ret r0
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 1
     0: LoadFromScope r0, 1, 0
     4: In r0, <this>, r0
     8: LoadUndefined r0
    10: Ret r0
}
