[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewClosure r0, c8
    31: StoreGlobal r0, c9, k4
    35: LoadUndefined r0
    37: Ret r0
  Constant Table:
    0: [BytecodeFunction: simpleRhsImmediate]
    1: [String: simpleRhsImmediate]
    2: [BytecodeFunction: simpleLhsImmediate]
    3: [String: simpleLhsImmediate]
    4: [BytecodeFunction: negativeImmediate]
    5: [String: negativeImmediate]
    6: [BytecodeFunction: wideImmediate]
    7: [String: wideImmediate]
    8: [BytecodeFunction: notAnImmediate]
    9: [String: notAnImmediate]
}

[BytecodeFunction: simpleRhsImmediate] {
  Parameters: 1, Registers: 1
     0: AddImm r0, a0, 1
     4: SubImm r0, a0, 2
     8: MulImm r0, a0, 3
    12: DivImm r0, a0, 4
    16: RemImm r0, a0, 5
    20: BitAndImm r0, a0, 6
    24: BitOrImm r0, a0, 7
    28: BitXorImm r0, a0, 8
    32: ShiftLeftImm r0, a0, 9
    36: ShiftRightArithmeticImm r0, a0, 10
    40: ShiftRightLogicalImm r0, a0, 11
    44: LoadUndefined r0
    46: Ret r0
}

[BytecodeFunction: simpleLhsImmediate] {
  Parameters: 1, Registers: 1
     0: MulImm r0, a0, 1
     4: BitAndImm r0, a0, 2
     8: BitOrImm r0, a0, 3
    12: BitXorImm r0, a0, 4
    16: LoadImmediate r0, 5
    19: Add r0, r0, a0
    23: LoadImmediate r0, 6
    26: Sub r0, r0, a0
    30: LoadImmediate r0, 7
    33: Div r0, r0, a0
    37: LoadImmediate r0, 8
    40: Rem r0, r0, a0
    44: LoadImmediate r0, 9
    47: ShiftLeft r0, r0, a0
    51: LoadImmediate r0, 10
    54: ShiftRightArithmetic r0, r0, a0
    58: LoadImmediate r0, 11
    61: ShiftRightLogical r0, r0, a0
    65: LoadUndefined r0
    67: Ret r0
}

[BytecodeFunction: negativeImmediate] {
  Parameters: 1, Registers: 1
     0: AddImm r0, a0, -1
     4: SubImm r0, a0, -2
     8: LoadUndefined r0
    10: Ret r0
}

[BytecodeFunction: wideImmediate] {
  Parameters: 1, Registers: 1
     0: AddImm (Wide) r0, a0, 1000
     8: AddImm (ExtraWide) r0, a0, 100000
    24: LoadUndefined r0
    26: Ret r0
}

[BytecodeFunction: notAnImmediate] {
  Parameters: 1, Registers: 1
     0: LoadImmediate r0, 1
     3: Add r0, r0, a0
     7: LoadImmediate r0, 2
    10: Exp r0, a0, r0
    14: LoadConstant r0, c0
    17: Add r0, a0, r0
    21: LoadConstant r0, c1
    24: Add r0, a0, r0
    28: LoadConstant r0, c2
    31: Sub r0, a0, r0
    35: LoadUndefined r0
    37: Ret r0
  Constant Table:
    0: [double: 1.5]
    1: [double: 2147483648]
    2: [double: -0]
}
