[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: LoadUndefined r0
    38: Ret r0
  Constant Table:
    0: [BytecodeFunction: emptyAnonymous]
    1: [String: emptyAnonymous]
    2: [BytecodeFunction: emptyNamed]
    3: [String: emptyNamed]
    4: [BytecodeFunction: nonEmptyAnonymous]
    5: [String: nonEmptyAnonymous]
    6: [BytecodeFunction: nonEmptyNamed]
    7: [String: nonEmptyNamed]
    8: [BytecodeFunction: storeToParam]
    9: [String: storeToParam]
    10: [BytecodeFunction: namedEvaluation]
    11: [String: namedEvaluation]
}

[BytecodeFunction: emptyAnonymous] {
  Parameters: 0, Registers: 2
    0: LoadEmpty r1
    2: NewClass r0, c1, c0, r1, r0
    8: Ret r0
  Constant Table:
    0: [BytecodeFunction: ]
    1: [ClassNames]
}

[BytecodeFunction: ] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: emptyNamed] {
  Parameters: 0, Registers: 2
    0: LoadEmpty r1
    2: NewClass r0, c1, c0, r1, r0
    8: Ret r0
  Constant Table:
    0: [BytecodeFunction: C]
    1: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: nonEmptyAnonymous] {
  Parameters: 0, Registers: 4
     0: LoadEmpty r1
     2: NewClosure r2, c0
     5: NewClass r0, c2, c1, r1, r2
    11: NewClosure r3, c3
    14: CallWithReceiver r3, r3, r0, r3, 0
    20: Ret r0
  Constant Table:
    0: [BytecodeFunction: method]
    1: [BytecodeFunction: ]
    2: [ClassNames]
    3: [BytecodeFunction: staticInitializer]
}

[BytecodeFunction: ] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: staticInitializer] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 2
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 1
    3: Ret r0
}

[BytecodeFunction: nonEmptyNamed] {
  Parameters: 0, Registers: 4
     0: LoadEmpty r1
     2: NewClosure r2, c0
     5: NewClass r0, c2, c1, r1, r2
    11: NewClosure r3, c3
    14: CallWithReceiver r3, r3, r0, r3, 0
    20: Ret r0
  Constant Table:
    0: [BytecodeFunction: method]
    1: [BytecodeFunction: C]
    2: [ClassNames]
    3: [BytecodeFunction: staticInitializer]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: staticInitializer] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 2
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: method] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 1
    3: Ret r0
}

[BytecodeFunction: storeToParam] {
  Parameters: 1, Registers: 1
     0: LoadEmpty r0
     2: NewClass a0, c1, c0, r0, a0
     8: LoadUndefined r0
    10: Ret r0
  Constant Table:
    0: [BytecodeFunction: C]
    1: [ClassNames]
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: namedEvaluation] {
  Parameters: 0, Registers: 2
     0: LoadEmpty r1
     2: NewClass r0, c1, c0, r1, r0
     8: LoadEmpty r1
    10: NewClass r0, c3, c2, r1, r0
    16: LoadUndefined r1
    18: Ret r1
  Constant Table:
    0: [BytecodeFunction: x]
    1: [ClassNames]
    2: [BytecodeFunction: C]
    3: [ClassNames]
}

[BytecodeFunction: x] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
