[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: LoadUndefined r0
    16: Ret r0
  Constant Table:
    0: [BytecodeFunction: testBasic]
    1: [String: testBasic]
    2: [BytecodeFunction: testBooleanCondition]
    3: [String: testBooleanCondition]
}

[BytecodeFunction: testBasic] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r0, 1
     3: JumpToBooleanFalse r0, 8 (.L0)
     6: LoadImmediate r0, 2
     9: Jump 5 (.L1)
  .L0:
    11: LoadImmediate r0, 3
  .L1:
    14: LoadImmediate r0, 1
    17: AddImm r0, r0, 2
    21: JumpToBooleanFalse r0, 12 (.L2)
    24: LoadImmediate r1, 3
    27: AddImm r0, r1, 4
    31: Jump 9 (.L3)
  .L2:
    33: LoadImmediate r1, 5
    36: AddImm r0, r1, 6
  .L3:
    40: LoadGlobal r0, c0, k0
    44: LoadImmediate r1, 1
    47: JumpToBooleanFalse r1, 12 (.L4)
    50: LoadImmediate r2, 2
    53: AddImm r1, r2, 3
    57: Jump 13 (.L5)
  .L4:
    59: LoadImmediate r2, 4
    62: AddImm r2, r2, 5
    66: AddImm r1, r2, 6
  .L5:
    70: Call r0, r0, r1, 1
    75: LoadUndefined r0
    77: Ret r0
  Constant Table:
    0: [String: use]
}

[BytecodeFunction: testBooleanCondition] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 8 (.L0)
     5: LoadImmediate r0, 1
     8: Jump 5 (.L1)
  .L0:
    10: LoadImmediate r0, 2
  .L1:
    13: LoadUndefined r0
    15: Ret r0
}
