[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: StoreGlobal r0, c1
    6: LoadUndefined r0
    8: Ret r0
  Constant Table:
    0: [BytecodeFunction: test]
    1: [String: test]
}

[BytecodeFunction: test] {
  Parameters: 2, Registers: 1
      0: LoadFalse r0
      2: JumpFalse r0, 8 (.L0)
      5: LoadImmediate r0, 1
      8: Ret r0
  .L0:
     10: LooseEqual r0, a0, a1, ic0
     15: JumpFalse r0, 8 (.L1)
     18: LoadImmediate r0, 2
     21: Ret r0
  .L1:
     23: LooseNotEqual r0, a0, a1, ic1
     28: JumpFalse r0, 8 (.L2)
     31: LoadImmediate r0, 3
     34: Ret r0
  .L2:
     36: StrictEqual r0, a0, a1, ic2
     41: JumpFalse r0, 8 (.L3)
     44: LoadImmediate r0, 4
     47: Ret r0
  .L3:
     49: StrictNotEqual r0, a0, a1, ic3
     54: JumpFalse r0, 8 (.L4)
     57: LoadImmediate r0, 5
     60: Ret r0
  .L4:
     62: LessThan r0, a0, a1, ic4
     67: JumpFalse r0, 8 (.L5)
     70: LoadImmediate r0, 6
     73: Ret r0
  .L5:
     75: LoadImmediate r0, 2
     78: LessThanOrEqual r0, a0, r0, ic5
     83: JumpFalse r0, 8 (.L6)
     86: LoadImmediate r0, 7
     89: Ret r0
  .L6:
     91: LoadImmediate r0, 3
     94: GreaterThan r0, a0, r0, ic6
     99: JumpFalse r0, 8 (.L7)
    102: LoadImmediate r0, 8
    105: Ret r0
  .L7:
    107: LoadImmediate r0, 4
    110: GreaterThanOrEqual r0, a0, r0, ic7
    115: JumpFalse r0, 8 (.L8)
    118: LoadImmediate r0, 9
    121: Ret r0
  .L8:
    123: LoadImmediate r0, 1
    126: LogNot r0, r0
    129: JumpFalse r0, 8 (.L9)
    132: LoadImmediate r0, 10
    135: Ret r0
  .L9:
    137: LoadUndefined r0
    139: Ret r0
}
