[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: LoadImmediate r0, 1
    33: StoreGlobal r0, c10
    36: LoadUndefined r0
    38: Ret r0
  Constant Table:
    0: [BytecodeFunction: logicalAnd]
    1: [String: logicalAnd]
    2: [BytecodeFunction: localOr]
    3: [String: localOr]
    4: [BytecodeFunction: nullishCoalesce]
    5: [String: nullishCoalesce]
    6: [BytecodeFunction: testAssignDest]
    7: [String: testAssignDest]
    8: [BytecodeFunction: named]
    9: [String: named]
    10: [String: global]
}

[BytecodeFunction: logicalAnd] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 0
     3: JumpToBooleanFalse a0, 6 (.L0)
     6: LoadImmediate a0, 1
  .L0:
     9: JumpToBooleanFalse r0, 6 (.L1)
    12: LoadImmediate r0, 2
  .L1:
    15: LoadGlobal r1, c0
    18: JumpToBooleanFalse r1, 9 (.L2)
    21: LoadImmediate r1, 3
    24: StoreGlobal r1, c0
  .L2:
    27: GetNamedProperty r1, a0, c1, k0
    32: JumpToBooleanFalse r1, 11 (.L3)
    35: LoadImmediate r1, 4
    38: SetNamedProperty a0, c1, r1, k1
  .L3:
    43: LoadGlobal r1, c2
    46: Mov r2, a0
    49: JumpToBooleanFalse r2, 6 (.L4)
    52: LoadImmediate a0, 5
  .L4:
    55: Mov r2, a0
    58: Call r1, r1, r2, 1
    63: LoadUndefined r1
    65: Ret r1
  Constant Table:
    0: [String: global]
    1: [String: foo]
    2: [String: use]
}

[BytecodeFunction: localOr] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 0
     3: JumpToBooleanTrue a0, 6 (.L0)
     6: LoadImmediate a0, 1
  .L0:
     9: JumpToBooleanTrue r0, 6 (.L1)
    12: LoadImmediate r0, 2
  .L1:
    15: LoadGlobal r1, c0
    18: JumpToBooleanTrue r1, 9 (.L2)
    21: LoadImmediate r1, 3
    24: StoreGlobal r1, c0
  .L2:
    27: GetNamedProperty r1, a0, c1, k0
    32: JumpToBooleanTrue r1, 11 (.L3)
    35: LoadImmediate r1, 4
    38: SetNamedProperty a0, c1, r1, k1
  .L3:
    43: LoadGlobal r1, c2
    46: Mov r2, a0
    49: JumpToBooleanTrue r2, 6 (.L4)
    52: LoadImmediate a0, 5
  .L4:
    55: Mov r2, a0
    58: Call r1, r1, r2, 1
    63: LoadUndefined r1
    65: Ret r1
  Constant Table:
    0: [String: global]
    1: [String: foo]
    2: [String: use]
}

[BytecodeFunction: nullishCoalesce] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 0
     3: JumpNotNullish a0, 6 (.L0)
     6: LoadImmediate a0, 1
  .L0:
     9: JumpNotNullish r0, 6 (.L1)
    12: LoadImmediate r0, 2
  .L1:
    15: LoadGlobal r1, c0
    18: JumpNotNullish r1, 9 (.L2)
    21: LoadImmediate r1, 3
    24: StoreGlobal r1, c0
  .L2:
    27: GetNamedProperty r1, a0, c1, k0
    32: JumpNotNullish r1, 11 (.L3)
    35: LoadImmediate r1, 4
    38: SetNamedProperty a0, c1, r1, k1
  .L3:
    43: LoadGlobal r1, c2
    46: Mov r2, a0
    49: JumpNotNullish r2, 6 (.L4)
    52: LoadImmediate a0, 5
  .L4:
    55: Mov r2, a0
    58: Call r1, r1, r2, 1
    63: LoadUndefined r1
    65: Ret r1
  Constant Table:
    0: [String: global]
    1: [String: foo]
    2: [String: use]
}

[BytecodeFunction: testAssignDest] {
  Parameters: 1, Registers: 4
     0: LoadImmediate r0, 0
     3: Mov r1, a0
     6: JumpToBooleanFalse r1, 6 (.L0)
     9: LoadImmediate a0, 1
  .L0:
    12: Mov r0, a0
    15: Mov r2, r0
    18: Mov r3, a0
    21: JumpToBooleanFalse r3, 6 (.L1)
    24: LoadImmediate a0, 2
  .L1:
    27: Mov r1, a0
    30: SetNamedProperty r2, c0, r1, k0
    35: LoadUndefined r1
    37: Ret r1
  Constant Table:
    0: [String: foo]
}

[BytecodeFunction: named] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: JumpToBooleanFalse r0, 6 (.L0)
     6: NewClosure r0, c0
  .L0:
     9: JumpToBooleanTrue r0, 6 (.L1)
    12: NewClosure r0, c1
  .L1:
    15: JumpNotNullish r0, 6 (.L2)
    18: NewClosure r0, c2
  .L2:
    21: LoadUndefined r1
    23: Ret r1
  Constant Table:
    0: [BytecodeFunction: x]
    1: [BytecodeFunction: x]
    2: [BytecodeFunction: x]
}

[BytecodeFunction: x] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: x] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: x] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
