[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: LoadUndefined r0
    23: Ret r0
  Constant Table:
    0: [BytecodeFunction: simpleNewTarget]
    1: [String: simpleNewTarget]
    2: [BytecodeFunction: captured]
    3: [String: captured]
    4: [BytecodeFunction: usesInner]
    5: [String: usesInner]
}

[BytecodeFunction: simpleNewTarget] {
  Parameters: 0, Registers: 2
    0: AddImm r1, r0, 1
    4: Ret r1
}

[BytecodeFunction: captured] {
  Parameters: 0, Registers: 1
     0: PushFunctionScope c0
     2: StoreToScope r0, 0, 0
     6: NewClosure r0, c1
     9: LoadFromScope r0, 0, 0
    13: AddImm r0, r0, 1
    17: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: LoadUndefined r0
    6: Ret r0
}

[BytecodeFunction: usesInner] {
  Parameters: 0, Registers: 3
    0: NewClosure r0, c0
    3: AddImm r2, r1, 3
    7: Ret r2
  Constant Table:
    0: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 3
    0: LoadImmediate r0, 1
    3: AddImm r2, r1, 2
    7: Ret r2
}
