[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: LoadUndefined r0
    23: Ret r0
  Constant Table:
    0: [BytecodeFunction: use]
    1: [String: use]
    2: [BytecodeFunction: testAllExpressionsEvaluated]
    3: [String: testAllExpressionsEvaluated]
    4: [BytecodeFunction: tesLastExpressionIsReturned]
    5: [String: tesLastExpressionIsReturned]
}

[BytecodeFunction: use] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: testAllExpressionsEvaluated] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
     6: LoadImmediate r0, 3
     9: LoadUndefined r0
    11: Ret r0
}

[BytecodeFunction: tesLastExpressionIsReturned] {
  Parameters: 0, Registers: 2
     0: LoadGlobal r0, c0, k0
     4: LoadImmediate r1, 1
     7: LoadImmediate r1, 2
    10: LoadImmediate r1, 3
    13: Call r0, r0, r1, 1
    18: LoadImmediate r0, 1
    21: LoadImmediate r0, 2
    24: LoadImmediate r0, 3
    27: Ret r0
  Constant Table:
    0: [String: use]
}
