[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
     0: PushLexicalScope c0
     2: NewObject r0, 3
     5: StoreToScope r0, 0, 0
     9: NewClosure r1, c2
    12: DefineNamedProperty r0, c1, r1
    16: NewClosure r1, c4
    19: DefineNamedProperty r0, c3, r1
    23: NewClosure r1, c6
    26: DefineNamedProperty r0, c5, r1
    30: PopScope 
    31: LoadUndefined r0
    33: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [String: named]
    2: [BytecodeFunction: named]
    3: [String: computed]
    4: [BytecodeFunction: computed]
    5: [String: captured]
    6: [BytecodeFunction: captured]
}

[BytecodeFunction: named] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: GetNamedSuperProperty r0, r0, <this>, c0
    9: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: computed] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 0
     4: LoadImmediate r1, 1
     7: AddImm r1, r1, 2
    11: GetSuperProperty r0, r0, <this>, r1
    16: Ret r0
}

[BytecodeFunction: captured] {
  Parameters: 0, Registers: 1
     0: PushFunctionScope c0
     2: StoreToScope <this>, 0, 0
     6: NewClosure r0, c1
     9: LoadUndefined r0
    11: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 0
     4: LoadFromScope r1, 0, 1
     8: GetNamedSuperProperty r0, r1, r0, c0
    13: Ret r0
  Constant Table:
    0: [String: x]
}
