[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: NewClosure r0, c14
    45: StoreGlobal r0, c15
    48: NewClosure r0, c16
    51: StoreGlobal r0, c17
    54: NewClosure r0, c18
    57: StoreGlobal r0, c19
    60: LoadImmediate r0, 0
    63: StoreGlobal r0, c20
    66: PushLexicalScope c21
    68: NewObject r0
    70: StoreToScope r0, 0, 0
    74: NewClosure r1, c23
    77: DefineNamedProperty r0, c22, r1
    81: NewClosure r1, c25
    84: DefineNamedProperty r0, c24, r1
    88: PopScope 
    89: LoadUndefined r0
    91: Ret r0
  Constant Table:
    0: [BytecodeFunction: use]
    1: [String: use]
    2: [BytecodeFunction: prefixIdAnyDest]
    3: [String: prefixIdAnyDest]
    4: [BytecodeFunction: prefixIdFixedDest]
    5: [String: prefixIdFixedDest]
    6: [BytecodeFunction: prefixIdNewTemporaryDest]
    7: [String: prefixIdNewTemporaryDest]
    8: [BytecodeFunction: postfixIdAnyDest]
    9: [String: postfixIdAnyDest]
    10: [BytecodeFunction: postfixIdFixedDest]
    11: [String: postfixIdFixedDest]
    12: [BytecodeFunction: postfixIdNewTemporaryDest]
    13: [String: postfixIdNewTemporaryDest]
    14: [BytecodeFunction: prefixMember]
    15: [String: prefixMember]
    16: [BytecodeFunction: postfixMember]
    17: [String: postfixMember]
    18: [BytecodeFunction: decrement]
    19: [String: decrement]
    20: [String: global]
    21: [ScopeNames]
    22: [String: prefixSuperMember]
    23: [BytecodeFunction: prefixSuperMember]
    24: [String: postfixSuperMember]
    25: [BytecodeFunction: postfixSuperMember]
}

[BytecodeFunction: use] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: prefixIdAnyDest] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: Mov r1, a0
     6: ToNumeric r1, r1
     9: Inc r1
    11: Mov a0, r1
    14: Neg r1, r1
    17: Mov r1, r0
    20: ToNumeric r1, r1
    23: Inc r1
    25: Mov r0, r1
    28: Neg r1, r1
    31: LoadGlobal r1, c0
    34: ToNumeric r1, r1
    37: Inc r1
    39: StoreGlobal r1, c0
    42: Neg r1, r1
    45: LoadUndefined r1
    47: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: prefixIdFixedDest] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: Mov r1, a0
     6: ToNumeric r0, r1
     9: Inc r0
    11: Mov a0, r0
    14: Mov r1, r0
    17: ToNumeric r0, r1
    20: Inc r0
    22: LoadGlobal r1, c0
    25: ToNumeric r0, r1
    28: Inc r0
    30: StoreGlobal r0, c0
    33: LoadUndefined r1
    35: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: prefixIdNewTemporaryDest] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 1
     3: LoadGlobal r1, c0
     6: Mov r2, a0
     9: ToNumeric r2, r2
    12: Inc r2
    14: Mov a0, r2
    17: Call r1, r1, r2, 1
    22: LoadGlobal r1, c0
    25: Mov r2, r0
    28: ToNumeric r2, r2
    31: Inc r2
    33: Mov r0, r2
    36: Call r1, r1, r2, 1
    41: LoadGlobal r1, c0
    44: LoadGlobal r2, c1
    47: ToNumeric r2, r2
    50: Inc r2
    52: StoreGlobal r2, c1
    55: Call r1, r1, r2, 1
    60: LoadUndefined r1
    62: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: postfixIdAnyDest] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 1
     3: Mov r2, a0
     6: ToNumeric r2, r2
     9: Mov r1, r2
    12: Inc r2
    14: Mov a0, r2
    17: Neg r1, r1
    20: Mov r2, r0
    23: ToNumeric r2, r2
    26: Mov r1, r2
    29: Inc r2
    31: Mov r0, r2
    34: Neg r1, r1
    37: LoadGlobal r2, c0
    40: ToNumeric r2, r2
    43: Mov r1, r2
    46: Inc r2
    48: StoreGlobal r2, c0
    51: Neg r1, r1
    54: LoadUndefined r1
    56: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: postfixIdFixedDest] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: Mov r1, a0
     6: ToNumeric r1, r1
     9: Mov r0, r1
    12: Inc r1
    14: Mov a0, r1
    17: ToNumeric r0, r0
    20: LoadGlobal r1, c0
    23: ToNumeric r1, r1
    26: Mov r0, r1
    29: Inc r1
    31: StoreGlobal r1, c0
    34: LoadUndefined r1
    36: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: postfixIdNewTemporaryDest] {
  Parameters: 1, Registers: 4
     0: LoadImmediate r0, 1
     3: LoadGlobal r1, c0
     6: Mov r3, a0
     9: ToNumeric r3, r3
    12: Mov r2, r3
    15: Inc r3
    17: Mov a0, r3
    20: Call r1, r1, r2, 1
    25: LoadGlobal r1, c0
    28: Mov r3, r0
    31: ToNumeric r3, r3
    34: Mov r2, r3
    37: Inc r3
    39: Mov r0, r3
    42: Call r1, r1, r2, 1
    47: LoadGlobal r1, c0
    50: LoadGlobal r3, c1
    53: ToNumeric r3, r3
    56: Mov r2, r3
    59: Inc r3
    61: StoreGlobal r3, c1
    64: Call r1, r1, r2, 1
    69: LoadUndefined r1
    71: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: prefixMember] {
  Parameters: 2, Registers: 3
     0: Mov r1, a0
     3: GetNamedProperty r0, r1, c0, k0
     8: ToNumeric r0, r0
    11: Inc r0
    13: SetNamedProperty r1, c0, r0
    17: Neg r0, r0
    20: Mov r1, a0
    23: LoadImmediate r2, 0
    26: GetProperty r0, r1, r2
    30: ToNumeric r0, r0
    33: Inc r0
    35: SetProperty r1, r2, r0
    39: Neg r0, r0
    42: Mov r1, a0
    45: GetNamedProperty r0, r1, c0, k1
    50: ToNumeric r0, r0
    53: Inc r0
    55: SetNamedProperty r1, c0, r0
    59: Mov a1, r0
    62: LoadUndefined r0
    64: Ret r0
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: postfixMember] {
  Parameters: 2, Registers: 4
     0: Mov r1, a0
     3: GetNamedProperty r0, r1, c0, k0
     8: ToNumeric r0, r0
    11: Mov r2, r0
    14: Inc r2
    16: SetNamedProperty r1, c0, r2
    20: Neg r0, r0
    23: Mov r1, a0
    26: LoadImmediate r2, 0
    29: GetProperty r0, r1, r2
    33: ToNumeric r0, r0
    36: Mov r3, r0
    39: Inc r3
    41: SetProperty r1, r2, r3
    45: Neg r0, r0
    48: Mov r1, a0
    51: GetNamedProperty r0, r1, c0, k1
    56: ToNumeric r0, r0
    59: Mov r2, r0
    62: Inc r2
    64: SetNamedProperty r1, c0, r2
    68: Mov a1, r0
    71: LoadUndefined r0
    73: Ret r0
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: prefixSuperMember] {
  Parameters: 1, Registers: 3
     0: LoadFromScope r1, 0, 0
     4: LoadConstant r2, c0
     7: ToNumeric r0, r0
    10: Inc r0
    12: SetSuperProperty r1, <this>, r2, r0
    17: Neg r0, r0
    20: LoadFromScope r1, 0, 0
    24: LoadImmediate r2, 0
    27: ToNumeric r0, r0
    30: Inc r0
    32: SetSuperProperty r1, <this>, r2, r0
    37: Neg r0, r0
    40: LoadFromScope r1, 0, 0
    44: LoadConstant r2, c0
    47: ToNumeric r0, r0
    50: Inc r0
    52: SetSuperProperty r1, <this>, r2, r0
    57: Mov a0, r0
    60: LoadUndefined r0
    62: Ret r0
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: postfixSuperMember] {
  Parameters: 1, Registers: 4
     0: LoadFromScope r1, 0, 0
     4: LoadConstant r2, c0
     7: ToNumeric r0, r0
    10: Mov r3, r0
    13: Inc r3
    15: SetSuperProperty r1, <this>, r2, r3
    20: Neg r0, r0
    23: LoadFromScope r1, 0, 0
    27: LoadImmediate r2, 0
    30: ToNumeric r0, r0
    33: Mov r3, r0
    36: Inc r3
    38: SetSuperProperty r1, <this>, r2, r3
    43: Neg r0, r0
    46: LoadFromScope r1, 0, 0
    50: LoadConstant r2, c0
    53: ToNumeric r0, r0
    56: Mov r3, r0
    59: Inc r3
    61: SetSuperProperty r1, <this>, r2, r3
    66: Mov a0, r0
    69: LoadUndefined r0
    71: Ret r0
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: decrement] {
  Parameters: 1, Registers: 2
     0: ToNumeric a0, a0
     3: Dec a0
     5: ToNumeric a0, a0
     8: Mov r0, a0
    11: Dec a0
    13: GetNamedProperty r0, a0, c0, k0
    18: ToNumeric r0, r0
    21: Dec r0
    23: SetNamedProperty a0, c0, r0
    27: GetNamedProperty r0, a0, c0, k1
    32: ToNumeric r0, r0
    35: Mov r1, r0
    38: Dec r1
    40: SetNamedProperty a0, c0, r1
    44: LoadUndefined r0
    46: Ret r0
  Constant Table:
    0: [String: prop]
}
