[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
      0: NewClosure r0, c0
      3: StoreGlobal r0, c1, k0
      7: NewClosure r0, c2
     10: StoreGlobal r0, c3, k1
     14: NewClosure r0, c4
     17: StoreGlobal r0, c5, k2
     21: NewClosure r0, c6
     24: StoreGlobal r0, c7, k3
     28: NewClosure r0, c8
     31: StoreGlobal r0, c9, k4
     35: NewClosure r0, c10
     38: StoreGlobal r0, c11, k5
     42: NewClosure r0, c12
     45: StoreGlobal r0, c13, k6
     49: NewClosure r0, c14
     52: StoreGlobal r0, c15, k7
     56: NewClosure r0, c16
     59: StoreGlobal r0, c17, k8
     63: NewClosure r0, c18
     66: StoreGlobal r0, c19, k9
     70: NewClosure r0, c20
     73: StoreGlobal r0, c21, k10
     77: NewClosure r0, c22
     80: StoreGlobal r0, c23, k11
     84: LoadImmediate r0, 0
     87: StoreGlobal r0, c24, k12
     91: PushLexicalScope c25
     93: NewObject r0, 2
     96: StoreToScope r0, 0, 0
    100: NewClosure r1, c27
    103: DefineNamedProperty r0, c26, r1, k13
    108: NewClosure r1, c29
    111: DefineNamedProperty r0, c28, r1, k14
    116: PopScope 
    117: LoadUndefined r0
    119: Ret r0
  Constant Table:
    0: [BytecodeFunction: use]
    1: [String: use]
    2: [BytecodeFunction: prefixIdAnyDest]
    3: [String: prefixIdAnyDest]
    4: [BytecodeFunction: prefixIdFixedDest]
    5: [String: prefixIdFixedDest]
    6: [BytecodeFunction: prefixIdNewTemporaryDest]
    7: [String: prefixIdNewTemporaryDest]
    8: [BytecodeFunction: postfixIdAnyDest]
    9: [String: postfixIdAnyDest]
    10: [BytecodeFunction: postfixIdFixedDest]
    11: [String: postfixIdFixedDest]
    12: [BytecodeFunction: postfixIdNewTemporaryDest]
    13: [String: postfixIdNewTemporaryDest]
    14: [BytecodeFunction: postfixIdUnused]
    15: [String: postfixIdUnused]
    16: [BytecodeFunction: prefixMember]
    17: [String: prefixMember]
    18: [BytecodeFunction: postfixMember]
    19: [String: postfixMember]
    20: [BytecodeFunction: postfixMemberUnused]
    21: [String: postfixMemberUnused]
    22: [BytecodeFunction: decrement]
    23: [String: decrement]
    24: [String: global]
    25: [ScopeNames]
    26: [String: prefixSuperMember]
    27: [BytecodeFunction: prefixSuperMember]
    28: [String: postfixSuperMember]
    29: [BytecodeFunction: postfixSuperMember]
}

[BytecodeFunction: use] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: prefixIdAnyDest] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: Mov r1, a0
     6: Inc r1
     8: Mov a0, r1
    11: Neg r1, r1
    14: Mov r1, r0
    17: Inc r1
    19: Mov r0, r1
    22: Neg r1, r1
    25: LoadGlobal r1, c0, k0
    29: Inc r1
    31: StoreGlobal r1, c0, k1
    35: Neg r1, r1
    38: LoadUndefined r1
    40: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: prefixIdFixedDest] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: Mov r1, a0
     6: Inc r1
     8: Mov a0, r1
    11: Mov r0, r1
    14: Mov r1, r0
    17: Inc r1
    19: Mov r0, r1
    22: Mov r0, r1
    25: LoadGlobal r1, c0, k0
    29: Inc r1
    31: StoreGlobal r1, c0, k1
    35: Mov r0, r1
    38: LoadUndefined r1
    40: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: prefixIdNewTemporaryDest] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 1
     3: LoadGlobal r1, c0, k0
     7: Mov r2, a0
    10: Inc r2
    12: Mov a0, r2
    15: Call r1, r1, r2, 1
    20: LoadGlobal r1, c0, k1
    24: Mov r2, r0
    27: Inc r2
    29: Mov r0, r2
    32: Call r1, r1, r2, 1
    37: LoadGlobal r1, c0, k2
    41: LoadGlobal r2, c1, k3
    45: Inc r2
    47: StoreGlobal r2, c1, k4
    51: Call r1, r1, r2, 1
    56: LoadUndefined r1
    58: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: postfixIdAnyDest] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 1
     3: Mov r2, a0
     6: ToNumeric r2, r2
     9: Mov r1, r2
    12: Inc r2
    14: Mov a0, r2
    17: Neg r1, r1
    20: Mov r2, r0
    23: ToNumeric r2, r2
    26: Mov r1, r2
    29: Inc r2
    31: Mov r0, r2
    34: Neg r1, r1
    37: LoadGlobal r2, c0, k0
    41: ToNumeric r2, r2
    44: Mov r1, r2
    47: Inc r2
    49: StoreGlobal r2, c0, k1
    53: Neg r1, r1
    56: LoadUndefined r1
    58: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: postfixIdFixedDest] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: Mov r1, a0
     6: ToNumeric r1, r1
     9: Mov r0, r1
    12: Inc r1
    14: Mov a0, r1
    17: ToNumeric r0, r0
    20: LoadGlobal r1, c0, k0
    24: ToNumeric r1, r1
    27: Mov r0, r1
    30: Inc r1
    32: StoreGlobal r1, c0, k1
    36: LoadUndefined r1
    38: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: postfixIdNewTemporaryDest] {
  Parameters: 1, Registers: 4
     0: LoadImmediate r0, 1
     3: LoadGlobal r1, c0, k0
     7: Mov r3, a0
    10: ToNumeric r3, r3
    13: Mov r2, r3
    16: Inc r3
    18: Mov a0, r3
    21: Call r1, r1, r2, 1
    26: LoadGlobal r1, c0, k1
    30: Mov r3, r0
    33: ToNumeric r3, r3
    36: Mov r2, r3
    39: Inc r3
    41: Mov r0, r3
    44: Call r1, r1, r2, 1
    49: LoadGlobal r1, c0, k2
    53: LoadGlobal r3, c1, k3
    57: ToNumeric r3, r3
    60: Mov r2, r3
    63: Inc r3
    65: StoreGlobal r3, c1, k4
    69: Call r1, r1, r2, 1
    74: LoadUndefined r1
    76: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: postfixIdUnused] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: Inc a0
     5: Inc r0
     7: LoadGlobal r1, c0, k0
    11: Inc r1
    13: StoreGlobal r1, c0, k1
    17: LoadUndefined r1
    19: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: prefixMember] {
  Parameters: 2, Registers: 3
      0: Mov r1, a0
      3: GetNamedProperty r0, r1, c0, k0
      8: Inc r0
     10: SetNamedProperty r1, c0, r0, k1
     15: Neg r0, r0
     18: Mov r1, a0
     21: LoadImmediate r2, 0
     24: ToPropertyKey r2, r2
     27: GetProperty r0, r1, r2
     31: Inc r0
     33: SetProperty r1, r2, r0
     37: Neg r0, r0
     40: Mov r1, a0
     43: GetNamedProperty r0, r1, c0, k2
     48: Inc r0
     50: SetNamedProperty r1, c0, r0, k3
     55: Mov a1, r0
     58: GetNamedProperty r0, a0, c0, k4
     63: Inc r0
     65: SetNamedProperty a0, c0, r0, k5
     70: LoadImmediate r1, 0
     73: ToPropertyKey r1, r1
     76: GetProperty r0, a0, r1
     80: Inc r0
     82: SetProperty a0, r1, r0
     86: ToPropertyKey r1, a1
     89: GetProperty r0, a0, r1
     93: Inc r0
     95: SetProperty a0, r1, r0
     99: LoadUndefined r0
    101: Ret r0
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: postfixMember] {
  Parameters: 2, Registers: 4
      0: Mov r1, a0
      3: GetNamedProperty r0, r1, c0, k0
      8: ToNumeric r0, r0
     11: Mov r2, r0
     14: Inc r2
     16: SetNamedProperty r1, c0, r2, k1
     21: Neg r0, r0
     24: Mov r1, a0
     27: LoadImmediate r2, 0
     30: ToPropertyKey r2, r2
     33: GetProperty r0, r1, r2
     37: ToNumeric r0, r0
     40: Mov r3, r0
     43: Inc r3
     45: SetProperty r1, r2, r3
     49: Neg r0, r0
     52: Mov r1, a0
     55: GetNamedProperty r0, r1, c0, k2
     60: ToNumeric r0, r0
     63: Mov r2, r0
     66: Inc r2
     68: SetNamedProperty r1, c0, r2, k3
     73: Mov a1, r0
     76: GetNamedProperty r0, a0, c0, k4
     81: Inc r0
     83: SetNamedProperty a0, c0, r0, k5
     88: LoadImmediate r1, 0
     91: ToPropertyKey r1, r1
     94: GetProperty r0, a0, r1
     98: Inc r0
    100: SetProperty a0, r1, r0
    104: ToPropertyKey r1, a1
    107: GetProperty r0, a0, r1
    111: Inc r0
    113: SetProperty a0, r1, r0
    117: LoadUndefined r0
    119: Ret r0
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: postfixMemberUnused] {
  Parameters: 2, Registers: 2
     0: GetNamedProperty r0, a0, c0, k0
     5: Inc r0
     7: SetNamedProperty a0, c0, r0, k1
    12: LoadImmediate r1, 0
    15: ToPropertyKey r1, r1
    18: GetProperty r0, a0, r1
    22: Inc r0
    24: SetProperty a0, r1, r0
    28: ToPropertyKey r1, a1
    31: GetProperty r0, a0, r1
    35: Inc r0
    37: SetProperty a0, r1, r0
    41: LoadUndefined r0
    43: Ret r0
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: prefixSuperMember] {
  Parameters: 2, Registers: 3
      0: LoadFromScope r1, 0, 0
      4: LoadConstant r2, c0
      7: GetNamedSuperProperty r0, r1, <this>, c0
     12: Inc r0
     14: SetSuperProperty r1, <this>, r2, r0
     19: Neg r0, r0
     22: LoadFromScope r1, 0, 0
     26: LoadImmediate r2, 0
     29: ToPropertyKey r2, r2
     32: GetSuperProperty r0, r1, <this>, r2
     37: Inc r0
     39: SetSuperProperty r1, <this>, r2, r0
     44: Neg r0, r0
     47: LoadFromScope r1, 0, 0
     51: LoadConstant r2, c0
     54: GetNamedSuperProperty r0, r1, <this>, c0
     59: Inc r0
     61: SetSuperProperty r1, <this>, r2, r0
     66: Mov a0, r0
     69: LoadFromScope r1, 0, 0
     73: LoadConstant r2, c0
     76: GetNamedSuperProperty r0, r1, <this>, c0
     81: Inc r0
     83: SetSuperProperty r1, <this>, r2, r0
     88: LoadFromScope r1, 0, 0
     92: LoadImmediate r2, 0
     95: ToPropertyKey r2, r2
     98: GetSuperProperty r0, r1, <this>, r2
    103: Inc r0
    105: SetSuperProperty r1, <this>, r2, r0
    110: LoadFromScope r1, 0, 0
    114: ToPropertyKey r2, a1
    117: GetSuperProperty r0, r1, <this>, r2
    122: Inc r0
    124: SetSuperProperty r1, <this>, r2, r0
    129: LoadUndefined r0
    131: Ret r0
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: postfixSuperMember] {
  Parameters: 2, Registers: 4
      0: LoadFromScope r1, 0, 0
      4: LoadConstant r2, c0
      7: GetNamedSuperProperty r0, r1, <this>, c0
     12: ToNumeric r0, r0
     15: Mov r3, r0
     18: Inc r3
     20: SetSuperProperty r1, <this>, r2, r3
     25: Neg r0, r0
     28: LoadFromScope r1, 0, 0
     32: LoadImmediate r2, 0
     35: ToPropertyKey r2, r2
     38: GetSuperProperty r0, r1, <this>, r2
     43: ToNumeric r0, r0
     46: Mov r3, r0
     49: Inc r3
     51: SetSuperProperty r1, <this>, r2, r3
     56: Neg r0, r0
     59: LoadFromScope r1, 0, 0
     63: LoadConstant r2, c0
     66: GetNamedSuperProperty r0, r1, <this>, c0
     71: ToNumeric r0, r0
     74: Mov r3, r0
     77: Inc r3
     79: SetSuperProperty r1, <this>, r2, r3
     84: Mov a0, r0
     87: LoadFromScope r1, 0, 0
     91: LoadConstant r2, c0
     94: GetNamedSuperProperty r0, r1, <this>, c0
     99: Inc r0
    101: SetSuperProperty r1, <this>, r2, r0
    106: LoadFromScope r1, 0, 0
    110: LoadImmediate r2, 0
    113: ToPropertyKey r2, r2
    116: GetSuperProperty r0, r1, <this>, r2
    121: Inc r0
    123: SetSuperProperty r1, <this>, r2, r0
    128: LoadFromScope r1, 0, 0
    132: ToPropertyKey r2, a1
    135: GetSuperProperty r0, r1, <this>, r2
    140: Inc r0
    142: SetSuperProperty r1, <this>, r2, r0
    147: LoadUndefined r0
    149: Ret r0
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: decrement] {
  Parameters: 1, Registers: 3
     0: Dec a0
     2: Mov r1, a0
     5: ToNumeric r1, r1
     8: Mov r0, r1
    11: Dec r1
    13: Mov a0, r1
    16: Neg r0, r0
    19: GetNamedProperty r0, a0, c0, k0
    24: Dec r0
    26: SetNamedProperty a0, c0, r0, k1
    31: Mov r1, a0
    34: GetNamedProperty r0, r1, c0, k2
    39: ToNumeric r0, r0
    42: Mov r2, r0
    45: Dec r2
    47: SetNamedProperty r1, c0, r2, k3
    52: Neg r0, r0
    55: LoadUndefined r0
    57: Ret r0
  Constant Table:
    0: [String: prop]
}
