[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewGenerator r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewAsyncGenerator r0, c2
    10: StoreGlobal r0, c3, k1
    14: LoadUndefined r0
    16: Ret r0
  Constant Table:
    0: [BytecodeFunction: syncYieldStar]
    1: [String: syncYieldStar]
    2: [BytecodeFunction: asyncYieldStar]
    3: [String: asyncYieldStar]
}

[BytecodeFunction: syncYieldStar] {
  Parameters: 1, Registers: 9
      0: GeneratorStart r0
      2: GetIterator r2, r3, a0
      6: LoadUndefined r4
      8: LoadTrue r5
  .L0:
     10: JumpNullish r5, 28 (.L2)
     13: CallWithReceiver r6, r3, r2, r4, 1
     19: CheckIteratorResultObject r6
     21: GetNamedProperty r7, r6, c0, k0
     26: JumpTrue r7, 5 (.L1)
     29: Jump 83 (.L8)
  .L1:
     31: GetNamedProperty r1, r6, c1, k1
     36: Jump 83 (.L9)
  .L2:
     38: JumpNotUndefined r5, 37 (.L5)
     41: GetMethod r8, r2, c3
     45: JumpNotUndefined r8, 5 (.L3)
     48: Ret r4
  .L3:
     50: CallWithReceiver r6, r8, r2, r4, 1
     56: CheckIteratorResultObject r6
     58: GetNamedProperty r7, r6, c0, k2
     63: JumpTrue r7, 5 (.L4)
     66: Jump 46 (.L8)
  .L4:
     68: GetNamedProperty r8, r6, c1, k3
     73: Ret r8
  .L5:
     75: GetMethod r8, r2, c2
     79: JumpNotUndefined r8, 8 (.L6)
     82: IteratorClose r2
     84: ThrowNewError 1, c4
  .L6:
     87: CallWithReceiver r6, r8, r2, r4, 1
     93: CheckIteratorResultObject r6
     95: GetNamedProperty r7, r6, c0, k4
    100: JumpTrue r7, 5 (.L7)
    103: Jump 9 (.L8)
  .L7:
    105: GetNamedProperty r1, r6, c1, k5
    110: Jump 9 (.L9)
  .L8:
    112: Yield r4, r5, r0, r6
    117: Jump -107 (.L0)
  .L9:
    119: Ret r1
  Constant Table:
    0: [String: done]
    1: [String: value]
    2: [String: throw]
    3: [String: return]
    4: [String: iterator does not have a throw method]
}

[BytecodeFunction: asyncYieldStar] {
  Parameters: 1, Registers: 12
      0: GeneratorStart r0
      2: GetAsyncIterator r2, r3, a0
      6: LoadUndefined r4
      8: LoadTrue r5
  .L0:
     10: JumpNullish r5, 38 (.L3)
     13: CallWithReceiver r6, r3, r2, r4, 1
     19: Await r6, r8, r0, r6
     24: JumpTrue r8, 5 (.L1)
     27: Throw r6
  .L1:
     29: CheckIteratorResultObject r6
     31: GetNamedProperty r7, r6, c0, k0
     36: JumpTrue r7, 5 (.L2)
     39: JumpConstant c5 (.L14)
  .L2:
     41: GetNamedProperty r1, r6, c1, k1
     46: JumpConstant c6 (.L15)
  .L3:
     48: JumpNotUndefined r5, 57 (.L8)
     51: GetMethod r8, r2, c3
     55: JumpNotUndefined r8, 15 (.L5)
     58: Await r4, r9, r0, r4
     63: JumpTrue r9, 5 (.L4)
     66: Throw r4
  .L4:
     68: Ret r4
  .L5:
     70: CallWithReceiver r6, r8, r2, r4, 1
     76: Await r6, r8, r0, r6
     81: JumpTrue r8, 5 (.L6)
     84: Throw r6
  .L6:
     86: CheckIteratorResultObject r6
     88: GetNamedProperty r7, r6, c0, k2
     93: JumpTrue r7, 5 (.L7)
     96: Jump 73 (.L14)
  .L7:
     98: GetNamedProperty r8, r6, c1, k3
    103: Ret r8
  .L8:
    105: GetMethod r8, r2, c2
    109: JumpNotUndefined r8, 25 (.L11)
    112: AsyncIteratorCloseStart r10, r9, r2
    116: JumpFalse r9, 15 (.L10)
    119: Await r10, r11, r0, r10
    124: JumpTrue r11, 5 (.L9)
    127: Throw r10
  .L9:
    129: AsyncIteratorCloseFinish r10
  .L10:
    131: ThrowNewError 1, c4
  .L11:
    134: CallWithReceiver r6, r8, r2, r4, 1
    140: Await r6, r8, r0, r6
    145: JumpTrue r8, 5 (.L12)
    148: Throw r6
  .L12:
    150: CheckIteratorResultObject r6
    152: GetNamedProperty r7, r6, c0, k4
    157: JumpTrue r7, 5 (.L13)
    160: Jump 9 (.L14)
  .L13:
    162: GetNamedProperty r1, r6, c1, k5
    167: Jump 37 (.L15)
  .L14:
    169: GetNamedProperty r8, r6, c1, k6
    174: Yield r4, r5, r0, r8
    179: JumpNotUndefined (Wide) r5, -169 (.L0)
    186: Await r4, r5, r0, r4
    191: JumpNullish (Wide) r5, -181 (.L0)
    198: LoadUndefined r5
    200: Jump (Wide) -190 (.L0)
  .L15:
    204: Await r1, r2, r0, r1
    209: JumpTrue r2, 5 (.L16)
    212: Throw r1
  .L16:
    214: Ret r1
  Constant Table:
    0: [String: done]
    1: [String: value]
    2: [String: throw]
    3: [String: return]
    4: [String: iterator does not have a throw method]
    5: 130
    6: 158
}
