[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewAsyncGenerator r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewAsyncGenerator r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewAsyncGenerator r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewAsyncGenerator r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewAsyncGenerator r0, c8
    31: StoreGlobal r0, c9, k4
    35: NewAsyncGenerator r0, c10
    38: StoreGlobal r0, c11, k5
    42: NewAsyncGenerator r0, c12
    45: StoreGlobal r0, c13, k6
    49: LoadImmediate r0, 0
    52: StoreGlobal r0, c14, k7
    56: LoadUndefined r0
    58: Ret r0
  Constant Table:
    0: [BytecodeFunction: empty]
    1: [String: empty]
    2: [BytecodeFunction: withArgsAndBody]
    3: [String: withArgsAndBody]
    4: [BytecodeFunction: simpleYield]
    5: [String: simpleYield]
    6: [BytecodeFunction: yieldWithArg]
    7: [String: yieldWithArg]
    8: [BytecodeFunction: withReturn]
    9: [String: withReturn]
    10: [BytecodeFunction: withAwait]
    11: [String: withAwait]
    12: [BytecodeFunction: yieldDestination]
    13: [String: yieldDestination]
    14: [String: global]
}

[BytecodeFunction: empty] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: withArgsAndBody] {
  Parameters: 3, Registers: 2
     0: JumpNotUndefined a1, 6 (.L0)
     3: LoadImmediate a1, 1
  .L0:
     6: JumpNotUndefined a2, 6 (.L1)
     9: LoadImmediate a2, 2
  .L1:
    12: GeneratorStart r0
    14: LoadImmediate r1, 3
    17: LoadUndefined r1
    19: Ret r1
}

[BytecodeFunction: simpleYield] {
  Parameters: 0, Registers: 3
     0: GeneratorStart r0
     2: LoadImmediate r1, 1
     5: LoadUndefined r1
     7: Await r1, r2, r0, r1
    12: JumpTrue r2, 5 (.L0)
    15: Throw r1
  .L0:
    17: Yield r1, r2, r0, r1
    22: JumpNotNullish r2, 20 (.L3)
    25: JumpNotUndefined r2, 15 (.L2)
    28: Await r1, r2, r0, r1
    33: JumpTrue r2, 5 (.L1)
    36: Throw r1
  .L1:
    38: Ret r1
  .L2:
    40: Throw r1
  .L3:
    42: LoadImmediate r1, 2
    45: LoadUndefined r1
    47: Ret r1
}

[BytecodeFunction: yieldWithArg] {
  Parameters: 0, Registers: 3
     0: GeneratorStart r0
     2: LoadImmediate r1, 1
     5: LoadImmediate r1, 2
     8: Await r1, r2, r0, r1
    13: JumpTrue r2, 5 (.L0)
    16: Throw r1
  .L0:
    18: Yield r1, r2, r0, r1
    23: JumpNotNullish r2, 20 (.L3)
    26: JumpNotUndefined r2, 15 (.L2)
    29: Await r1, r2, r0, r1
    34: JumpTrue r2, 5 (.L1)
    37: Throw r1
  .L1:
    39: Ret r1
  .L2:
    41: Throw r1
  .L3:
    43: LoadImmediate r1, 3
    46: LoadUndefined r1
    48: Ret r1
}

[BytecodeFunction: withReturn] {
  Parameters: 0, Registers: 3
     0: GeneratorStart r0
     2: LoadTrue r1
     4: JumpFalse r1, 7 (.L0)
     7: LoadUndefined r1
     9: Ret r1
  .L0:
    11: LoadImmediate r1, 1
    14: Await r1, r2, r0, r1
    19: JumpTrue r2, 5 (.L1)
    22: Throw r1
  .L1:
    24: Ret r1
}

[BytecodeFunction: withAwait] {
  Parameters: 0, Registers: 3
     0: GeneratorStart r0
     2: LoadImmediate r1, 1
     5: LoadImmediate r1, 2
     8: Await r1, r2, r0, r1
    13: JumpTrue r2, 5 (.L0)
    16: Throw r1
  .L0:
    18: LoadImmediate r1, 3
    21: LoadUndefined r1
    23: Ret r1
}

[BytecodeFunction: yieldDestination] {
  Parameters: 0, Registers: 4
      0: GeneratorStart r1
      2: LoadImmediate r0, 1
      5: LoadUndefined r2
      7: Await r2, r3, r1, r2
     12: JumpTrue r3, 5 (.L0)
     15: Throw r2
  .L0:
     17: Yield r2, r3, r1, r2
     22: JumpNotNullish r3, 20 (.L3)
     25: JumpNotUndefined r3, 15 (.L2)
     28: Await r2, r3, r1, r2
     33: JumpTrue r3, 5 (.L1)
     36: Throw r2
  .L1:
     38: Ret r2
  .L2:
     40: Throw r2
  .L3:
     42: Mov r0, r2
     45: LoadUndefined r2
     47: Await r2, r3, r1, r2
     52: JumpTrue r3, 5 (.L4)
     55: Throw r2
  .L4:
     57: Yield r2, r3, r1, r2
     62: JumpNotNullish r3, 20 (.L7)
     65: JumpNotUndefined r3, 15 (.L6)
     68: Await r2, r3, r1, r2
     73: JumpTrue r3, 5 (.L5)
     76: Throw r2
  .L5:
     78: Ret r2
  .L6:
     80: Throw r2
  .L7:
     82: StoreGlobal r2, c0, k0
     86: LoadUndefined r2
     88: Await r2, r3, r1, r2
     93: JumpTrue r3, 5 (.L8)
     96: Throw r2
  .L8:
     98: Yield r2, r3, r1, r2
    103: JumpNotNullish r3, 20 (.L11)
    106: JumpNotUndefined r3, 15 (.L10)
    109: Await r2, r3, r1, r2
    114: JumpTrue r3, 5 (.L9)
    117: Throw r2
  .L9:
    119: Ret r2
  .L10:
    121: Throw r2
  .L11:
    123: Neg r2, r2
    126: LoadUndefined r2
    128: Await r2, r3, r1, r2
    133: JumpTrue r3, 5 (.L12)
    136: Throw r2
  .L12:
    138: Yield r2, r3, r1, r2
    143: JumpNotNullish r3, 20 (.L15)
    146: JumpNotUndefined r3, 15 (.L14)
    149: Await r2, r3, r1, r2
    154: JumpTrue r3, 5 (.L13)
    157: Throw r2
  .L13:
    159: Ret r2
  .L14:
    161: Throw r2
  .L15:
    163: Await r2, r3, r1, r2
    168: JumpTrue r3, 5 (.L16)
    171: Throw r2
  .L16:
    173: Ret r2
  Constant Table:
    0: [String: global]
}
