[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: LoadUndefined r0
    26: Ret r0
  Constant Table:
    0: [BytecodeFunction: test1]
    1: [String: test1]
    2: [BytecodeFunction: test2]
    3: [String: test2]
    4: [BytecodeFunction: test3]
    5: [String: test3]
    6: [BytecodeFunction: test4]
    7: [String: test4]
}

[BytecodeFunction: test1] {
  Parameters: 2, Registers: 1
    0: Add r0, a0, a1
    4: Ret r0
}

[BytecodeFunction: test2] {
  Parameters: 1, Registers: 1
     0: JumpToBooleanFalse a0, 7 (.L0)
     3: LoadUndefined r0
     5: Ret r0
  .L0:
     7: JumpToBooleanFalse a0, 5 (.L1)
    10: Ret a0
  .L1:
    12: LoadImmediate r0, 2
    15: Ret r0
}

[BytecodeFunction: test3] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 1
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: test4] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
