[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: RetUndefined 
  Constant Table:
    0: [BytecodeFunction: test1]
    1: [String: test1]
    2: [BytecodeFunction: test2]
    3: [String: test2]
    4: [BytecodeFunction: test3]
    5: [String: test3]
    6: [BytecodeFunction: test4]
    7: [String: test4]
}

[BytecodeFunction: test1] {
  Parameters: 2, Registers: 1
    0: Add r0, a0, a1
    4: Ret r0
}

[BytecodeFunction: test2] {
  Parameters: 1, Registers: 1
     0: JumpToBooleanFalse a0, 4 (.L0)
     3: RetUndefined 
  .L0:
     4: JumpToBooleanFalse a0, 5 (.L1)
     7: Ret a0
  .L1:
     9: LoadImmediate r0, 2
    12: Ret r0
}

[BytecodeFunction: test3] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 1
    3: RetUndefined 
}

[BytecodeFunction: test4] {
  Parameters: 0, Registers: 0
    0: RetUndefined 
}
