[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 3
     0: NewGenerator r0, c0
     3: StoreGlobal r0, c1
     6: NewGenerator r0, c2
     9: StoreGlobal r0, c3
    12: NewGenerator r0, c4
    15: StoreGlobal r0, c5
    18: NewGenerator r0, c6
    21: StoreGlobal r0, c7
    24: NewGenerator r0, c8
    27: StoreGlobal r0, c9
    30: NewGenerator r0, c10
    33: StoreGlobal r0, c11
    36: NewGenerator r0, c12
    39: StoreGlobal r0, c13
    42: NewGenerator r0, c14
    45: NewGenerator r0, c15
    48: NewObject r0
    50: NewGenerator r1, c17
    53: DefineNamedProperty r0, c16, r1
    57: LoadEmpty r1
    59: NewGenerator r2, c18
    62: NewClass r0, c20, c19, r1, r2
    68: StoreToScope r0, 1, 0
    72: LoadUndefined r0
    74: Ret r0
  Constant Table:
    0: [BytecodeFunction: empty]
    1: [String: empty]
    2: [BytecodeFunction: withArgsAndBody]
    3: [String: withArgsAndBody]
    4: [BytecodeFunction: simpleYield]
    5: [String: simpleYield]
    6: [BytecodeFunction: yieldWithArg]
    7: [String: yieldWithArg]
    8: [BytecodeFunction: multipleYields]
    9: [String: multipleYields]
    10: [BytecodeFunction: yieldReturnValue]
    11: [String: yieldReturnValue]
    12: [BytecodeFunction: yieldInFinally]
    13: [String: yieldInFinally]
    14: [BytecodeFunction: generatorExpression]
    15: [BytecodeFunction: <anonymous>]
    16: [String: generatorMethod]
    17: [BytecodeFunction: generatorMethod]
    18: [BytecodeFunction: generatorMethod]
    19: [BytecodeFunction: C]
    20: [ClassNames]
}

[BytecodeFunction: empty] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: withArgsAndBody] {
  Parameters: 3, Registers: 2
     0: JumpNotUndefined a1, 6 (.L0)
     3: LoadImmediate a1, 1
  .L0:
     6: JumpNotUndefined a2, 6 (.L1)
     9: LoadImmediate a2, 2
  .L1:
    12: GeneratorStart r0
    14: LoadImmediate r1, 3
    17: LoadUndefined r1
    19: Ret r1
}

[BytecodeFunction: simpleYield] {
  Parameters: 0, Registers: 4
     0: GeneratorStart r0
     2: LoadImmediate r1, 1
     5: LoadUndefined r1
     7: Mov r2, r1
    10: NewObject r3
    12: SetNamedProperty r3, c0, r2, k0
    17: LoadFalse r2
    19: SetNamedProperty r3, c1, r2, k1
    24: Yield r1, r2, r0, r3
    29: JumpNotNullish r2, 10 (.L1)
    32: JumpNotUndefined r2, 5 (.L0)
    35: Ret r1
  .L0:
    37: Throw r1
  .L1:
    39: LoadImmediate r1, 2
    42: LoadUndefined r1
    44: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
}

[BytecodeFunction: yieldWithArg] {
  Parameters: 0, Registers: 4
     0: GeneratorStart r0
     2: LoadImmediate r1, 1
     5: LoadImmediate r1, 2
     8: Mov r2, r1
    11: NewObject r3
    13: SetNamedProperty r3, c0, r2, k0
    18: LoadFalse r2
    20: SetNamedProperty r3, c1, r2, k1
    25: Yield r1, r2, r0, r3
    30: JumpNotNullish r2, 10 (.L1)
    33: JumpNotUndefined r2, 5 (.L0)
    36: Ret r1
  .L0:
    38: Throw r1
  .L1:
    40: LoadImmediate r1, 3
    43: LoadUndefined r1
    45: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
}

[BytecodeFunction: multipleYields] {
  Parameters: 0, Registers: 4
      0: GeneratorStart r0
      2: LoadUndefined r1
      4: Mov r2, r1
      7: NewObject r3
      9: SetNamedProperty r3, c0, r2, k0
     14: LoadFalse r2
     16: SetNamedProperty r3, c1, r2, k1
     21: Yield r1, r2, r0, r3
     26: JumpNotNullish r2, 10 (.L1)
     29: JumpNotUndefined r2, 5 (.L0)
     32: Ret r1
  .L0:
     34: Throw r1
  .L1:
     36: LoadImmediate r1, 1
     39: Mov r2, r1
     42: NewObject r3
     44: SetNamedProperty r3, c0, r2, k2
     49: LoadFalse r2
     51: SetNamedProperty r3, c1, r2, k3
     56: Yield r1, r2, r0, r3
     61: JumpNotNullish r2, 10 (.L3)
     64: JumpNotUndefined r2, 5 (.L2)
     67: Ret r1
  .L2:
     69: Throw r1
  .L3:
     71: LoadUndefined r1
     73: Mov r2, r1
     76: NewObject r3
     78: SetNamedProperty r3, c0, r2, k4
     83: LoadFalse r2
     85: SetNamedProperty r3, c1, r2, k5
     90: Yield r1, r2, r0, r3
     95: JumpNotNullish r2, 10 (.L5)
     98: JumpNotUndefined r2, 5 (.L4)
    101: Ret r1
  .L4:
    103: Throw r1
  .L5:
    105: LoadImmediate r1, 2
    108: Mov r2, r1
    111: NewObject r3
    113: SetNamedProperty r3, c0, r2, k6
    118: LoadFalse r2
    120: SetNamedProperty r3, c1, r2, k7
    125: Yield r1, r2, r0, r3
    130: JumpNotNullish r2, 10 (.L7)
    133: JumpNotUndefined r2, 5 (.L6)
    136: Ret r1
  .L6:
    138: Throw r1
  .L7:
    140: LoadUndefined r1
    142: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
}

[BytecodeFunction: yieldReturnValue] {
  Parameters: 0, Registers: 5
     0: GeneratorStart r0
     2: LoadUndefined r1
     4: Mov r2, r1
     7: NewObject r3
     9: SetNamedProperty r3, c0, r2, k0
    14: LoadFalse r2
    16: SetNamedProperty r3, c1, r2, k1
    21: Yield r1, r2, r0, r3
    26: JumpNotNullish r2, 10 (.L1)
    29: JumpNotUndefined r2, 5 (.L0)
    32: Ret r1
  .L0:
    34: Throw r1
  .L1:
    36: LoadImmediate r2, 1
    39: Mov r3, r2
    42: NewObject r4
    44: SetNamedProperty r4, c0, r3, k2
    49: LoadFalse r3
    51: SetNamedProperty r4, c1, r3, k3
    56: Yield r2, r3, r0, r4
    61: JumpNotNullish r3, 10 (.L3)
    64: JumpNotUndefined r3, 5 (.L2)
    67: Ret r2
  .L2:
    69: Throw r2
  .L3:
    71: Add r1, r1, r2
    75: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
}

[BytecodeFunction: yieldInFinally] {
  Parameters: 0, Registers: 7
     0: GeneratorStart r0
     2: Mov r3, <scope>
     5: LoadUndefined r4
     7: Mov r5, r4
    10: NewObject r6
    12: SetNamedProperty r6, c0, r5, k0
    17: LoadFalse r5
    19: SetNamedProperty r6, c1, r5, k1
    24: Yield r4, r5, r0, r6
    29: JumpNotNullish r5, 16 (.L1)
    32: JumpNotUndefined r5, 11 (.L0)
    35: LoadImmediate r1, 1
    38: Mov r2, r4
    41: Jump 12 (.L2)
  .L0:
    43: Throw r4
  .L1:
    45: LoadImmediate r1, 2
    48: Jump 5 (.L2)
    50: LoadImmediate r1, 0
  .L2:
    53: Mov <scope>, r3
    56: LoadImmediate r3, 1
    59: LoadImmediate r3, 0
    62: StrictEqual r3, r1, r3
    66: JumpFalse r3, 5 (.L3)
    69: Rethrow r2
  .L3:
    71: LoadImmediate r3, 2
    74: StrictEqual r3, r1, r3
    78: JumpFalse r3, 5 (.L4)
    81: Jump 4 (.L5)
  .L4:
    83: Ret r2
  .L5:
    85: LoadUndefined r1
    87: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
  Exception Handlers:
    5-45 -> 50 (r2)
}

[BytecodeFunction: generatorExpression] {
  Parameters: 0, Registers: 3
    0: Mov r0, <closure>
    3: GeneratorStart r1
    5: LoadUndefined r2
    7: Ret r2
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: generatorMethod] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: generatorMethod] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}
