[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 3
     0: NewGenerator r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewGenerator r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewGenerator r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewGenerator r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewGenerator r0, c8
    31: StoreGlobal r0, c9, k4
    35: NewGenerator r0, c10
    38: StoreGlobal r0, c11, k5
    42: NewGenerator r0, c12
    45: StoreGlobal r0, c13, k6
    49: NewGenerator r0, c14
    52: StoreGlobal r0, c15, k7
    56: LoadImmediate r0, 1
    59: StoreGlobal r0, c16, k8
    63: NewGenerator r0, c17
    66: NewGenerator r0, c18
    69: NewObject r0, 1
    72: NewGenerator r1, c20
    75: DefineNamedProperty r0, c19, r1, k9
    80: LoadEmpty r1
    82: NewGenerator r2, c21
    85: NewClass r0, c23, c22, r1, r2
    91: StoreToScope r0, 1, 0
    95: LoadUndefined r0
    97: Ret r0
  Constant Table:
    0: [BytecodeFunction: empty]
    1: [String: empty]
    2: [BytecodeFunction: withArgsAndBody]
    3: [String: withArgsAndBody]
    4: [BytecodeFunction: simpleYield]
    5: [String: simpleYield]
    6: [BytecodeFunction: yieldWithArg]
    7: [String: yieldWithArg]
    8: [BytecodeFunction: multipleYields]
    9: [String: multipleYields]
    10: [BytecodeFunction: yieldReturnValue]
    11: [String: yieldReturnValue]
    12: [BytecodeFunction: yieldDestination]
    13: [String: yieldDestination]
    14: [BytecodeFunction: yieldInFinally]
    15: [String: yieldInFinally]
    16: [String: global]
    17: [BytecodeFunction: generatorExpression]
    18: [BytecodeFunction: <anonymous>]
    19: [String: generatorMethod]
    20: [BytecodeFunction: generatorMethod]
    21: [BytecodeFunction: generatorMethod]
    22: [BytecodeFunction: C]
    23: [ClassNames]
}

[BytecodeFunction: empty] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: withArgsAndBody] {
  Parameters: 3, Registers: 2
     0: JumpNotUndefined a1, 6 (.L0)
     3: LoadImmediate a1, 1
  .L0:
     6: JumpNotUndefined a2, 6 (.L1)
     9: LoadImmediate a2, 2
  .L1:
    12: GeneratorStart r0
    14: LoadImmediate r1, 3
    17: LoadUndefined r1
    19: Ret r1
}

[BytecodeFunction: simpleYield] {
  Parameters: 0, Registers: 4
     0: GeneratorStart r0
     2: LoadImmediate r1, 1
     5: LoadUndefined r1
     7: Mov r2, r1
    10: NewObject r3, 2
    13: SetNamedProperty r3, c0, r2, k0
    18: LoadFalse r2
    20: SetNamedProperty r3, c1, r2, k1
    25: Yield r1, r2, r0, r3
    30: JumpNotNullish r2, 10 (.L1)
    33: JumpNotUndefined r2, 5 (.L0)
    36: Ret r1
  .L0:
    38: Throw r1
  .L1:
    40: LoadImmediate r1, 2
    43: LoadUndefined r1
    45: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
}

[BytecodeFunction: yieldWithArg] {
  Parameters: 0, Registers: 4
     0: GeneratorStart r0
     2: LoadImmediate r1, 1
     5: LoadImmediate r1, 2
     8: Mov r2, r1
    11: NewObject r3, 2
    14: SetNamedProperty r3, c0, r2, k0
    19: LoadFalse r2
    21: SetNamedProperty r3, c1, r2, k1
    26: Yield r1, r2, r0, r3
    31: JumpNotNullish r2, 10 (.L1)
    34: JumpNotUndefined r2, 5 (.L0)
    37: Ret r1
  .L0:
    39: Throw r1
  .L1:
    41: LoadImmediate r1, 3
    44: LoadUndefined r1
    46: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
}

[BytecodeFunction: multipleYields] {
  Parameters: 0, Registers: 4
      0: GeneratorStart r0
      2: LoadUndefined r1
      4: Mov r2, r1
      7: NewObject r3, 2
     10: SetNamedProperty r3, c0, r2, k0
     15: LoadFalse r2
     17: SetNamedProperty r3, c1, r2, k1
     22: Yield r1, r2, r0, r3
     27: JumpNotNullish r2, 10 (.L1)
     30: JumpNotUndefined r2, 5 (.L0)
     33: Ret r1
  .L0:
     35: Throw r1
  .L1:
     37: LoadImmediate r1, 1
     40: Mov r2, r1
     43: NewObject r3, 2
     46: SetNamedProperty r3, c0, r2, k2
     51: LoadFalse r2
     53: SetNamedProperty r3, c1, r2, k3
     58: Yield r1, r2, r0, r3
     63: JumpNotNullish r2, 10 (.L3)
     66: JumpNotUndefined r2, 5 (.L2)
     69: Ret r1
  .L2:
     71: Throw r1
  .L3:
     73: LoadUndefined r1
     75: Mov r2, r1
     78: NewObject r3, 2
     81: SetNamedProperty r3, c0, r2, k4
     86: LoadFalse r2
     88: SetNamedProperty r3, c1, r2, k5
     93: Yield r1, r2, r0, r3
     98: JumpNotNullish r2, 10 (.L5)
    101: JumpNotUndefined r2, 5 (.L4)
    104: Ret r1
  .L4:
    106: Throw r1
  .L5:
    108: LoadImmediate r1, 2
    111: Mov r2, r1
    114: NewObject r3, 2
    117: SetNamedProperty r3, c0, r2, k6
    122: LoadFalse r2
    124: SetNamedProperty r3, c1, r2, k7
    129: Yield r1, r2, r0, r3
    134: JumpNotNullish r2, 10 (.L7)
    137: JumpNotUndefined r2, 5 (.L6)
    140: Ret r1
  .L6:
    142: Throw r1
  .L7:
    144: LoadUndefined r1
    146: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
}

[BytecodeFunction: yieldReturnValue] {
  Parameters: 0, Registers: 5
     0: GeneratorStart r0
     2: LoadUndefined r1
     4: Mov r2, r1
     7: NewObject r3, 2
    10: SetNamedProperty r3, c0, r2, k0
    15: LoadFalse r2
    17: SetNamedProperty r3, c1, r2, k1
    22: Yield r1, r2, r0, r3
    27: JumpNotNullish r2, 10 (.L1)
    30: JumpNotUndefined r2, 5 (.L0)
    33: Ret r1
  .L0:
    35: Throw r1
  .L1:
    37: LoadImmediate r2, 1
    40: Mov r3, r2
    43: NewObject r4, 2
    46: SetNamedProperty r4, c0, r3, k2
    51: LoadFalse r3
    53: SetNamedProperty r4, c1, r3, k3
    58: Yield r2, r3, r0, r4
    63: JumpNotNullish r3, 10 (.L3)
    66: JumpNotUndefined r3, 5 (.L2)
    69: Ret r2
  .L2:
    71: Throw r2
  .L3:
    73: Add r1, r1, r2
    77: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
}

[BytecodeFunction: yieldDestination] {
  Parameters: 0, Registers: 5
      0: GeneratorStart r1
      2: LoadImmediate r0, 1
      5: LoadUndefined r2
      7: Mov r3, r2
     10: NewObject r4, 2
     13: SetNamedProperty r4, c0, r3, k0
     18: LoadFalse r3
     20: SetNamedProperty r4, c1, r3, k1
     25: Yield r2, r3, r1, r4
     30: JumpNotNullish r3, 10 (.L1)
     33: JumpNotUndefined r3, 5 (.L0)
     36: Ret r2
  .L0:
     38: Throw r2
  .L1:
     40: Mov r0, r2
     43: LoadUndefined r2
     45: Mov r3, r2
     48: NewObject r4, 2
     51: SetNamedProperty r4, c0, r3, k2
     56: LoadFalse r3
     58: SetNamedProperty r4, c1, r3, k3
     63: Yield r2, r3, r1, r4
     68: JumpNotNullish r3, 10 (.L3)
     71: JumpNotUndefined r3, 5 (.L2)
     74: Ret r2
  .L2:
     76: Throw r2
  .L3:
     78: StoreGlobal r2, c2, k4
     82: LoadUndefined r2
     84: Mov r3, r2
     87: NewObject r4, 2
     90: SetNamedProperty r4, c0, r3, k5
     95: LoadFalse r3
     97: SetNamedProperty r4, c1, r3, k6
    102: Yield r2, r3, r1, r4
    107: JumpNotNullish r3, 10 (.L5)
    110: JumpNotUndefined r3, 5 (.L4)
    113: Ret r2
  .L4:
    115: Throw r2
  .L5:
    117: Ret r2
  Constant Table:
    0: [String: value]
    1: [String: done]
    2: [String: global]
}

[BytecodeFunction: yieldInFinally] {
  Parameters: 0, Registers: 7
     0: GeneratorStart r0
     2: Mov r3, <scope>
     5: LoadUndefined r4
     7: Mov r5, r4
    10: NewObject r6, 2
    13: SetNamedProperty r6, c0, r5, k0
    18: LoadFalse r5
    20: SetNamedProperty r6, c1, r5, k1
    25: Yield r4, r5, r0, r6
    30: JumpNotNullish r5, 16 (.L1)
    33: JumpNotUndefined r5, 11 (.L0)
    36: LoadImmediate r1, 1
    39: Mov r2, r4
    42: Jump 12 (.L2)
  .L0:
    44: Throw r4
  .L1:
    46: LoadImmediate r1, 2
    49: Jump 5 (.L2)
    51: LoadImmediate r1, 0
  .L2:
    54: Mov <scope>, r3
    57: LoadImmediate r3, 1
    60: LoadImmediate r3, 0
    63: StrictEqual r3, r1, r3
    67: JumpFalse r3, 5 (.L3)
    70: Rethrow r2
  .L3:
    72: LoadImmediate r3, 2
    75: StrictEqual r3, r1, r3
    79: JumpFalse r3, 5 (.L4)
    82: Jump 4 (.L5)
  .L4:
    84: Ret r2
  .L5:
    86: LoadUndefined r1
    88: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
  Exception Handlers:
    5-46 -> 51 (r2)
}

[BytecodeFunction: generatorExpression] {
  Parameters: 0, Registers: 3
    0: Mov r0, <closure>
    3: GeneratorStart r1
    5: LoadUndefined r2
    7: Ret r2
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: generatorMethod] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: generatorMethod] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}
