[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: LoadUndefined r0
    10: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: testAbruptMiddle]
    2: [String: testAbruptMiddle]
}

[BytecodeFunction: testAbruptMiddle] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 1
    3: LoadImmediate r0, 2
    6: LoadImmediate r0, 3
    9: Ret r0
}
