[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
    0: 16 ff 00   NewClosure r0, c0
    3: 0a ff 01   StoreGlobal r0, c1
    6: 05 ff      LoadUndefined r0
    8: 0c ff      Ret r0
  Constant Table:
    0: [BytecodeFunction: testAbruptMiddle]
    1: [String: testAbruptMiddle]
}

[BytecodeFunction: testAbruptMiddle] {
  Parameters: 0, Registers: 1
    0: 03 ff 01   LoadImmediate r0, 1
    3: 03 ff 02   LoadImmediate r0, 2
    6: 03 ff 03   LoadImmediate r0, 3
    9: 0c ff      Ret r0
}
