[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
      0: GlobalInit c0
      2: NewClosure r0, c1
      5: StoreGlobal r0, c2
      8: NewClosure r0, c3
     11: StoreGlobal r0, c4
     14: NewClosure r0, c5
     17: StoreGlobal r0, c6
     20: NewClosure r0, c7
     23: StoreGlobal r0, c8
     26: NewClosure r0, c9
     29: StoreGlobal r0, c10
     32: NewClosure r0, c11
     35: StoreGlobal r0, c12
     38: NewClosure r0, c13
     41: StoreGlobal r0, c14
     44: NewClosure r0, c15
     47: StoreGlobal r0, c16
     50: LoadImmediate r0, 1
     53: StoreToScope r0, 1, 0
     57: LoadImmediate r0, 1
     60: StoreToScope r0, 2, 0
     64: LoadImmediate r0, 2
     67: StoreToScope r0, 3, 0
     71: LoadImmediate r0, 3
     74: StoreToScope r0, 4, 0
     78: LoadImmediate r0, 1
     81: StoreToScope r0, 5, 0
     85: LoadImmediate r0, 1
     88: StoreToScope r0, 6, 0
     92: LoadImmediate r0, 2
     95: StoreToScope r0, 7, 0
     99: LoadImmediate r0, 3
    102: StoreToScope r0, 8, 0
    106: LoadFromScope r0, 1, 0
    110: CheckTdz r0, c17
    113: LoadFromScope r1, 5, 0
    117: CheckTdz r1, c18
    120: Add r0, r0, r1
    124: StoreToScope r0, 9, 0
    128: LoadFromScope r0, 11, 0
    132: CheckTdz r0, c19
    135: StoreToScope r0, 10, 0
    139: LoadImmediate r0, 1
    142: StoreToScope r0, 11, 0
    146: LoadUndefined r0
    148: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: tdzGlobals]
    2: [String: tdzGlobals]
    3: [BytecodeFunction: noTdzLocals]
    4: [String: noTdzLocals]
    5: [BytecodeFunction: tdzLocals]
    6: [String: tdzLocals]
    7: [BytecodeFunction: tdzUseInInitializer]
    8: [String: tdzUseInInitializer]
    9: [BytecodeFunction: letNoInitializer]
    10: [String: letNoInitializer]
    11: [BytecodeFunction: assigningConst]
    12: [String: assigningConst]
    13: [BytecodeFunction: prefixUpdateConst]
    14: [String: prefixUpdateConst]
    15: [BytecodeFunction: postfixUpdateConst]
    16: [String: postfixUpdateConst]
    17: [String: c1]
    18: [String: l1]
    19: [String: c4]
}

[BytecodeFunction: tdzGlobals] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r1, 1, 0
     4: CheckTdz r1, c0
     7: Neg r1, r1
    10: LoadFromScope r1, 5, 0
    14: CheckTdz r1, c1
    17: Neg r1, r1
    20: LoadFromScope r1, 1, 0
    24: CheckTdz r1, c0
    27: Mov r0, r1
    30: LoadUndefined r1
    32: Ret r1
  Constant Table:
    0: [String: c1]
    1: [String: l1]
}

[BytecodeFunction: noTdzLocals] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r2, 3
     3: LoadImmediate r0, 1
     6: LoadImmediate r1, 2
     9: Add r2, r0, r1
    13: Ret r2
}

[BytecodeFunction: tdzLocals] {
  Parameters: 0, Registers: 6
     0: LoadEmpty r1
     2: LoadEmpty r2
     4: LoadEmpty r4
     6: LoadImmediate r5, 3
     9: CheckTdz r1, c0
    12: CheckTdz r2, c1
    15: Add r0, r1, r2
    19: LoadImmediate r1, 1
    22: LoadImmediate r2, 1
    25: CheckTdz r4, c2
    28: Mov r3, r4
    31: LoadImmediate r4, 2
    34: CheckTdz r1, c0
    37: CheckTdz r2, c1
    40: Add r5, r1, r2
    44: Ret r5
  Constant Table:
    0: [String: c1]
    1: [String: l1]
    2: [String: c4]
}

[BytecodeFunction: tdzUseInInitializer] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r0
     2: LoadEmpty r1
     4: LoadImmediate r2, 3
     7: CheckTdz r0, c0
    10: CheckTdz r1, c1
    13: LoadUndefined r2
    15: Ret r2
  Constant Table:
    0: [String: c1]
    1: [String: l1]
}

[BytecodeFunction: letNoInitializer] {
  Parameters: 0, Registers: 2
     0: LoadUndefined r0
     2: LoadImmediate r1, 2
     5: Add r1, r0, r1
     9: LoadUndefined r1
    11: Ret r1
}

[BytecodeFunction: assigningConst] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r0, 1
     3: LoadImmediate r1, 2
     6: ErrorConst c0
     8: LoadFromScope r2, 1, 0
    12: CheckTdz r2, c0
    15: StoreToScope r1, 1, 0
    19: LoadImmediate r1, 3
    22: ErrorConst c1
    24: Mov r0, r1
    27: LoadUndefined r1
    29: Ret r1
  Constant Table:
    0: [String: c1]
    1: [String: c2]
}

[BytecodeFunction: prefixUpdateConst] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: ErrorConst c0
     5: LoadFromScope r1, 1, 0
     9: CheckTdz r1, c0
    12: ToNumeric r1, r1
    15: Inc r1
    17: ErrorConst c0
    19: StoreToScope r1, 1, 0
    23: ErrorConst c1
    25: ToNumeric r0, r0
    28: Inc r0
    30: LoadUndefined r1
    32: Ret r1
  Constant Table:
    0: [String: c1]
    1: [String: c2]
}

[BytecodeFunction: postfixUpdateConst] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r0, 1
     3: ErrorConst c0
     5: LoadFromScope r2, 1, 0
     9: CheckTdz r2, c0
    12: ToNumeric r2, r2
    15: Mov r1, r2
    18: Inc r2
    20: ErrorConst c0
    22: StoreToScope r2, 1, 0
    26: ErrorConst c1
    28: ToNumeric r0, r0
    31: Mov r1, r0
    34: Inc r0
    36: ErrorConst c1
    38: LoadUndefined r1
    40: Ret r1
  Constant Table:
    0: [String: c1]
    1: [String: c2]
}
