[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
      0: GlobalInit c0
      2: NewClosure r0, c1
      5: StoreGlobal r0, c2
      8: NewClosure r0, c3
     11: StoreGlobal r0, c4
     14: NewClosure r0, c5
     17: StoreGlobal r0, c6
     20: NewClosure r0, c7
     23: StoreGlobal r0, c8
     26: NewClosure r0, c9
     29: StoreGlobal r0, c10
     32: NewClosure r0, c11
     35: StoreGlobal r0, c12
     38: LoadImmediate r0, 1
     41: StoreToScope r0, 1, 0
     45: LoadImmediate r0, 1
     48: StoreToScope r0, 2, 0
     52: LoadImmediate r0, 2
     55: StoreToScope r0, 3, 0
     59: LoadImmediate r0, 3
     62: StoreToScope r0, 4, 0
     66: LoadImmediate r0, 1
     69: StoreToScope r0, 5, 0
     73: LoadImmediate r0, 1
     76: StoreToScope r0, 6, 0
     80: LoadImmediate r0, 2
     83: StoreToScope r0, 7, 0
     87: LoadImmediate r0, 3
     90: StoreToScope r0, 8, 0
     94: LoadFromScope r0, 1, 0
     98: CheckTdz r0, c13
    101: LoadFromScope r1, 5, 0
    105: CheckTdz r1, c14
    108: Add r0, r0, r1
    112: StoreToScope r0, 9, 0
    116: LoadFromScope r0, 11, 0
    120: CheckTdz r0, c15
    123: StoreToScope r0, 10, 0
    127: LoadImmediate r0, 1
    130: StoreToScope r0, 11, 0
    134: LoadUndefined r0
    136: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: tdzGlobals]
    2: [String: tdzGlobals]
    3: [BytecodeFunction: noTdzLocals]
    4: [String: noTdzLocals]
    5: [BytecodeFunction: tdzLocals]
    6: [String: tdzLocals]
    7: [BytecodeFunction: tdzUseInInitializer]
    8: [String: tdzUseInInitializer]
    9: [BytecodeFunction: letNoInitializer]
    10: [String: letNoInitializer]
    11: [BytecodeFunction: assigningConst]
    12: [String: assigningConst]
    13: [String: c1]
    14: [String: l1]
    15: [String: c4]
}

[BytecodeFunction: tdzGlobals] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r1, 1, 0
     4: CheckTdz r1, c0
     7: Neg r1, r1
    10: LoadFromScope r1, 5, 0
    14: CheckTdz r1, c1
    17: Neg r1, r1
    20: LoadFromScope r1, 1, 0
    24: CheckTdz r1, c0
    27: Mov r0, r1
    30: LoadUndefined r1
    32: Ret r1
  Constant Table:
    0: [String: c1]
    1: [String: l1]
}

[BytecodeFunction: noTdzLocals] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r2, 3
     3: LoadImmediate r0, 1
     6: LoadImmediate r1, 2
     9: Add r2, r0, r1
    13: Ret r2
}

[BytecodeFunction: tdzLocals] {
  Parameters: 0, Registers: 6
     0: LoadEmpty r1
     2: LoadEmpty r2
     4: LoadEmpty r4
     6: LoadImmediate r5, 3
     9: CheckTdz r1, c0
    12: CheckTdz r2, c1
    15: Add r0, r1, r2
    19: LoadImmediate r1, 1
    22: LoadImmediate r2, 1
    25: CheckTdz r4, c2
    28: Mov r3, r4
    31: LoadImmediate r4, 2
    34: CheckTdz r1, c0
    37: CheckTdz r2, c1
    40: Add r5, r1, r2
    44: Ret r5
  Constant Table:
    0: [String: c1]
    1: [String: l1]
    2: [String: c4]
}

[BytecodeFunction: tdzUseInInitializer] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r0
     2: LoadEmpty r1
     4: LoadImmediate r2, 3
     7: CheckTdz r0, c0
    10: CheckTdz r1, c1
    13: LoadUndefined r2
    15: Ret r2
  Constant Table:
    0: [String: c1]
    1: [String: l1]
}

[BytecodeFunction: letNoInitializer] {
  Parameters: 0, Registers: 2
     0: LoadUndefined r0
     2: LoadImmediate r1, 2
     5: Add r1, r0, r1
     9: LoadUndefined r1
    11: Ret r1
}

[BytecodeFunction: assigningConst] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r0, 1
     3: LoadImmediate r1, 2
     6: ErrorConst c0
     8: LoadFromScope r2, 1, 0
    12: CheckTdz r2, c0
    15: StoreToScope r1, 1, 0
    19: LoadImmediate r0, 3
    22: ErrorConst c1
    24: ToNumeric r0, r0
    27: Mov r1, r0
    30: Inc r0
    32: ErrorConst c1
    34: LoadUndefined r1
    36: Ret r1
  Constant Table:
    0: [String: c1]
    1: [String: c2]
}
