[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: LoadUndefined r0
    28: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: testBasic]
    2: [String: testBasic]
    3: [BytecodeFunction: testBooleanTest]
    4: [String: testBooleanTest]
    5: [BytecodeFunction: testAbruptBody]
    6: [String: testAbruptBody]
    7: [BytecodeFunction: testBreakAndContinue]
    8: [String: testBreakAndContinue]
}

[BytecodeFunction: testBasic] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: LoadImmediate r0, 3
     9: JumpToBooleanTrue r0, -6 (.L0)
    12: LoadImmediate r0, 4
    15: LoadUndefined r0
    17: Ret r0
}

[BytecodeFunction: testBooleanTest] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: LoadTrue r0
     8: JumpTrue r0, -5 (.L0)
    11: LoadImmediate r0, 3
    14: LoadUndefined r0
    16: Ret r0
}

[BytecodeFunction: testAbruptBody] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: LoadUndefined r0
     8: Ret r0
    10: LoadTrue r0
    12: JumpTrue r0, -9 (.L0)
    15: LoadImmediate r0, 4
    18: LoadUndefined r0
    20: Ret r0
}

[BytecodeFunction: testBreakAndContinue] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: JumpToBooleanFalse r0, 5 (.L1)
     9: Jump 15 (.L3)
  .L1:
    11: LoadImmediate r0, 3
    14: JumpToBooleanFalse r0, 5 (.L2)
    17: Jump 2 (.L2)
  .L2:
    19: LoadTrue r0
    21: JumpTrue r0, -18 (.L0)
  .L3:
    24: LoadImmediate r0, 4
    27: LoadUndefined r0
    29: Ret r0
}
