[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: LoadUndefined r0
    26: Ret r0
  Constant Table:
    0: [BytecodeFunction: testBasic]
    1: [String: testBasic]
    2: [BytecodeFunction: testBooleanTest]
    3: [String: testBooleanTest]
    4: [BytecodeFunction: testAbruptBody]
    5: [String: testAbruptBody]
    6: [BytecodeFunction: testBreakAndContinue]
    7: [String: testBreakAndContinue]
}

[BytecodeFunction: testBasic] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: LoadImmediate r0, 3
     9: JumpToBooleanTrue r0, -6 (.L0)
    12: LoadImmediate r0, 4
    15: LoadUndefined r0
    17: Ret r0
}

[BytecodeFunction: testBooleanTest] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: LoadTrue r0
     8: JumpTrue r0, -5 (.L0)
    11: LoadImmediate r0, 3
    14: LoadUndefined r0
    16: Ret r0
}

[BytecodeFunction: testAbruptBody] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: LoadUndefined r0
     8: Ret r0
    10: LoadTrue r0
    12: JumpTrue r0, -9 (.L0)
    15: LoadImmediate r0, 4
    18: LoadUndefined r0
    20: Ret r0
}

[BytecodeFunction: testBreakAndContinue] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: JumpToBooleanFalse r0, 5 (.L1)
     9: Jump 15 (.L3)
  .L1:
    11: LoadImmediate r0, 3
    14: JumpToBooleanFalse r0, 5 (.L2)
    17: Jump 2 (.L2)
  .L2:
    19: LoadTrue r0
    21: JumpTrue r0, -18 (.L0)
  .L3:
    24: LoadImmediate r0, 4
    27: LoadUndefined r0
    29: Ret r0
}
