[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: LoadUndefined r0
    14: Ret r0
  Constant Table:
    0: [BytecodeFunction: testBasic]
    1: [String: testBasic]
    2: [BytecodeFunction: testBooleanTest]
    3: [String: testBooleanTest]
}

[BytecodeFunction: testBasic] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: LoadImmediate r0, 3
     9: JumpToBooleanTrue r0, -6 (.L0)
    12: LoadImmediate r0, 4
    15: LoadUndefined r0
    17: Ret r0
}

[BytecodeFunction: testBooleanTest] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: LoadTrue r0
     8: JumpTrue r0, -5 (.L0)
    11: LoadImmediate r0, 3
    14: LoadUndefined r0
    16: Ret r0
}
