[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: NewClosure r0, c14
    45: StoreGlobal r0, c15
    48: NewClosure r0, c16
    51: StoreGlobal r0, c17
    54: NewClosure r0, c18
    57: StoreGlobal r0, c19
    60: NewClosure r0, c20
    63: StoreGlobal r0, c21
    66: LoadUndefined r0
    68: Ret r0
  Constant Table:
    0: [BytecodeFunction: testNoInitTestOrUpdate]
    1: [String: testNoInitTestOrUpdate]
    2: [BytecodeFunction: testInitNoTestOrUpdate]
    3: [String: testInitNoTestOrUpdate]
    4: [BytecodeFunction: testNoInitTestNoUpdate]
    5: [String: testNoInitTestNoUpdate]
    6: [BytecodeFunction: testNoInitOrTestUpdate]
    7: [String: testNoInitOrTestUpdate]
    8: [BytecodeFunction: testInitTestNoUpdate]
    9: [String: testInitTestNoUpdate]
    10: [BytecodeFunction: testNoInitTestUpdate]
    11: [String: testNoInitTestUpdate]
    12: [BytecodeFunction: testInitNoTestUpdate]
    13: [String: testInitNoTestUpdate]
    14: [BytecodeFunction: testInitTestUpdate]
    15: [String: testInitTestUpdate]
    16: [BytecodeFunction: testVarDeclInit]
    17: [String: testVarDeclInit]
    18: [BytecodeFunction: testAbruptBody]
    19: [String: testAbruptBody]
    20: [BytecodeFunction: testBreakAndContinue]
    21: [String: testBreakAndContinue]
}

[BytecodeFunction: testNoInitTestOrUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: Jump -3 (.L0)
     8: LoadImmediate r0, 3
    11: LoadUndefined r0
    13: Ret r0
}

[BytecodeFunction: testInitNoTestOrUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: Jump -3 (.L0)
    11: LoadImmediate r0, 4
    14: LoadUndefined r0
    16: Ret r0
}

[BytecodeFunction: testNoInitTestNoUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: JumpToBooleanFalse r0, 8 (.L1)
     9: LoadImmediate r0, 3
    12: Jump -9 (.L0)
  .L1:
    14: LoadImmediate r0, 4
    17: LoadUndefined r0
    19: Ret r0
}

[BytecodeFunction: testNoInitOrTestUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 3
     6: LoadImmediate r0, 2
     9: Jump -6 (.L0)
    11: LoadImmediate r0, 4
    14: LoadUndefined r0
    16: Ret r0
}

[BytecodeFunction: testInitTestNoUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: JumpToBooleanFalse r0, 8 (.L1)
    12: LoadImmediate r0, 4
    15: Jump -9 (.L0)
  .L1:
    17: LoadImmediate r0, 5
    20: LoadUndefined r0
    22: Ret r0
}

[BytecodeFunction: testNoInitTestUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: JumpToBooleanFalse r0, 11 (.L1)
     9: LoadImmediate r0, 4
    12: LoadImmediate r0, 3
    15: Jump -12 (.L0)
  .L1:
    17: LoadImmediate r0, 5
    20: LoadUndefined r0
    22: Ret r0
}

[BytecodeFunction: testInitNoTestUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 4
     9: LoadImmediate r0, 3
    12: Jump -6 (.L0)
    14: LoadImmediate r0, 5
    17: LoadUndefined r0
    19: Ret r0
}

[BytecodeFunction: testInitTestUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: JumpToBooleanFalse r0, 11 (.L1)
    12: LoadImmediate r0, 5
    15: LoadImmediate r0, 4
    18: Jump -12 (.L0)
  .L1:
    20: LoadImmediate r0, 6
    23: LoadUndefined r0
    25: Ret r0
}

[BytecodeFunction: testVarDeclInit] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r1, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r1, 3
     9: JumpToBooleanFalse r1, 11 (.L1)
    12: LoadImmediate r1, 5
    15: LoadImmediate r1, 4
    18: Jump -12 (.L0)
  .L1:
    20: LoadImmediate r1, 6
    23: LoadUndefined r1
    25: Ret r1
}

[BytecodeFunction: testAbruptBody] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: JumpToBooleanFalse r0, 15 (.L1)
    12: LoadImmediate r0, 5
    15: LoadUndefined r0
    17: Ret r0
    19: LoadImmediate r0, 4
    22: Jump -16 (.L0)
  .L1:
    24: LoadImmediate r0, 7
    27: LoadUndefined r0
    29: Ret r0
}

[BytecodeFunction: testBreakAndContinue] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: JumpToBooleanFalse r0, 30 (.L4)
    12: LoadImmediate r0, 5
    15: JumpToBooleanFalse r0, 5 (.L1)
    18: Jump 21 (.L4)
  .L1:
    20: LoadImmediate r0, 6
    23: LoadImmediate r0, 7
    26: JumpToBooleanFalse r0, 5 (.L2)
    29: Jump 5 (.L3)
  .L2:
    31: LoadImmediate r0, 8
  .L3:
    34: LoadImmediate r0, 4
    37: Jump -31 (.L0)
  .L4:
    39: LoadImmediate r0, 7
    42: LoadUndefined r0
    44: Ret r0
}
