[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: NewClosure r0, c11
    35: StoreGlobal r0, c12
    38: NewClosure r0, c13
    41: StoreGlobal r0, c14
    44: NewClosure r0, c15
    47: StoreGlobal r0, c16
    50: NewClosure r0, c17
    53: StoreGlobal r0, c18
    56: NewClosure r0, c19
    59: StoreGlobal r0, c20
    62: NewClosure r0, c21
    65: StoreGlobal r0, c22
    68: LoadUndefined r0
    70: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: testNoInitTestOrUpdate]
    2: [String: testNoInitTestOrUpdate]
    3: [BytecodeFunction: testInitNoTestOrUpdate]
    4: [String: testInitNoTestOrUpdate]
    5: [BytecodeFunction: testNoInitTestNoUpdate]
    6: [String: testNoInitTestNoUpdate]
    7: [BytecodeFunction: testNoInitOrTestUpdate]
    8: [String: testNoInitOrTestUpdate]
    9: [BytecodeFunction: testInitTestNoUpdate]
    10: [String: testInitTestNoUpdate]
    11: [BytecodeFunction: testNoInitTestUpdate]
    12: [String: testNoInitTestUpdate]
    13: [BytecodeFunction: testInitNoTestUpdate]
    14: [String: testInitNoTestUpdate]
    15: [BytecodeFunction: testInitTestUpdate]
    16: [String: testInitTestUpdate]
    17: [BytecodeFunction: testVarDeclInit]
    18: [String: testVarDeclInit]
    19: [BytecodeFunction: testAbruptBody]
    20: [String: testAbruptBody]
    21: [BytecodeFunction: testBreakAndContinue]
    22: [String: testBreakAndContinue]
}

[BytecodeFunction: testNoInitTestOrUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: Jump -3 (.L0)
     8: LoadImmediate r0, 3
    11: LoadUndefined r0
    13: Ret r0
}

[BytecodeFunction: testInitNoTestOrUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: Jump -3 (.L0)
    11: LoadImmediate r0, 4
    14: LoadUndefined r0
    16: Ret r0
}

[BytecodeFunction: testNoInitTestNoUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: JumpToBooleanFalse r0, 8 (.L1)
     9: LoadImmediate r0, 3
    12: Jump -9 (.L0)
  .L1:
    14: LoadImmediate r0, 4
    17: LoadUndefined r0
    19: Ret r0
}

[BytecodeFunction: testNoInitOrTestUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 3
     6: LoadImmediate r0, 2
     9: Jump -6 (.L0)
    11: LoadImmediate r0, 4
    14: LoadUndefined r0
    16: Ret r0
}

[BytecodeFunction: testInitTestNoUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: JumpToBooleanFalse r0, 8 (.L1)
    12: LoadImmediate r0, 4
    15: Jump -9 (.L0)
  .L1:
    17: LoadImmediate r0, 5
    20: LoadUndefined r0
    22: Ret r0
}

[BytecodeFunction: testNoInitTestUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: JumpToBooleanFalse r0, 11 (.L1)
     9: LoadImmediate r0, 4
    12: LoadImmediate r0, 3
    15: Jump -12 (.L0)
  .L1:
    17: LoadImmediate r0, 5
    20: LoadUndefined r0
    22: Ret r0
}

[BytecodeFunction: testInitNoTestUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 4
     9: LoadImmediate r0, 3
    12: Jump -6 (.L0)
    14: LoadImmediate r0, 5
    17: LoadUndefined r0
    19: Ret r0
}

[BytecodeFunction: testInitTestUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: JumpToBooleanFalse r0, 11 (.L1)
    12: LoadImmediate r0, 5
    15: LoadImmediate r0, 4
    18: Jump -12 (.L0)
  .L1:
    20: LoadImmediate r0, 6
    23: LoadUndefined r0
    25: Ret r0
}

[BytecodeFunction: testVarDeclInit] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r1, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r1, 3
     9: JumpToBooleanFalse r1, 11 (.L1)
    12: LoadImmediate r1, 5
    15: LoadImmediate r1, 4
    18: Jump -12 (.L0)
  .L1:
    20: LoadImmediate r1, 6
    23: LoadUndefined r1
    25: Ret r1
}

[BytecodeFunction: testAbruptBody] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: JumpToBooleanFalse r0, 15 (.L1)
    12: LoadImmediate r0, 5
    15: LoadUndefined r0
    17: Ret r0
    19: LoadImmediate r0, 4
    22: Jump -16 (.L0)
  .L1:
    24: LoadImmediate r0, 7
    27: LoadUndefined r0
    29: Ret r0
}

[BytecodeFunction: testBreakAndContinue] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: JumpToBooleanFalse r0, 30 (.L4)
    12: LoadImmediate r0, 5
    15: JumpToBooleanFalse r0, 5 (.L1)
    18: Jump 21 (.L4)
  .L1:
    20: LoadImmediate r0, 6
    23: LoadImmediate r0, 7
    26: JumpToBooleanFalse r0, 5 (.L2)
    29: Jump 5 (.L3)
  .L2:
    31: LoadImmediate r0, 8
  .L3:
    34: LoadImmediate r0, 4
    37: Jump -31 (.L0)
  .L4:
    39: LoadImmediate r0, 7
    42: LoadUndefined r0
    44: Ret r0
}
