[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: NewAsyncClosure r0, c14
    45: StoreGlobal r0, c15
    48: LoadUndefined r0
    50: Ret r0
  Constant Table:
    0: [BytecodeFunction: basicVar]
    1: [String: basicVar]
    2: [BytecodeFunction: basicConstLet]
    3: [String: basicConstLet]
    4: [BytecodeFunction: testAllAbruptPaths]
    5: [String: testAllAbruptPaths]
    6: [BytecodeFunction: lhsIdentifier]
    7: [String: lhsIdentifier]
    8: [BytecodeFunction: lhsMember]
    9: [String: lhsMember]
    10: [BytecodeFunction: lhsDestructuring]
    11: [String: lhsDestructuring]
    12: [BytecodeFunction: lhsTdz]
    13: [String: lhsTdz]
    14: [BytecodeFunction: forAwaitOf]
    15: [String: forAwaitOf]
}

[BytecodeFunction: basicVar] {
  Parameters: 0, Registers: 7
     0: LoadImmediate r1, 1
     3: NewArray r3
     5: GetIterator r1, r2, r3
  .L0:
     9: IteratorNext r3, r4, r1, r2
    14: JumpTrue r4, 26 (.L2)
    17: Mov r0, r3
    20: Mov r5, <scope>
    23: LoadImmediate r6, 2
    26: Jump 12 (.L1)
    28: LoadImmediate r3, 0
    31: Mov <scope>, r5
    34: IteratorClose r1
    36: Throw r4
  .L1:
    38: Jump -29 (.L0)
  .L2:
    40: LoadImmediate r1, 3
    43: LoadUndefined r1
    45: Ret r1
  Exception Handlers:
    17-26 -> 28 (r4)
    34-36 -> 36
}

[BytecodeFunction: basicConstLet] {
  Parameters: 0, Registers: 8
     0: LoadImmediate r2, 1
     3: NewArray r4
     5: GetIterator r2, r3, r4
  .L0:
     9: IteratorNext r4, r5, r2, r3
    14: JumpTrue r5, 26 (.L2)
    17: Mov r1, r4
    20: Mov r6, <scope>
    23: LoadImmediate r7, 2
    26: Jump 12 (.L1)
    28: LoadImmediate r4, 0
    31: Mov <scope>, r6
    34: IteratorClose r2
    36: Throw r5
  .L1:
    38: Jump -29 (.L0)
  .L2:
    40: LoadImmediate r2, 3
    43: NewArray r4
    45: GetIterator r2, r3, r4
  .L3:
    49: IteratorNext r4, r5, r2, r3
    54: JumpTrue r5, 26 (.L5)
    57: Mov r0, r4
    60: Mov r6, <scope>
    63: LoadImmediate r7, 3
    66: Jump 12 (.L4)
    68: LoadImmediate r4, 0
    71: Mov <scope>, r6
    74: IteratorClose r2
    76: Throw r5
  .L4:
    78: Jump -29 (.L3)
  .L5:
    80: LoadImmediate r2, 4
    83: LoadUndefined r2
    85: Ret r2
  Exception Handlers:
    17-26 -> 28 (r5)
    34-36 -> 36
    57-66 -> 68 (r5)
    74-76 -> 76
}

[BytecodeFunction: testAllAbruptPaths] {
  Parameters: 1, Registers: 7
      0: LoadImmediate r1, 1
      3: NewArray r3
      5: GetIterator r1, r2, r3
  .L0:
      9: IteratorNext r3, r4, r1, r2
     14: JumpTrue r4, 97 (.L10)
     17: Mov r0, r3
     20: Mov r5, <scope>
     23: LoadImmediate r6, 2
     26: JumpToBooleanFalse r6, 8 (.L1)
     29: LoadImmediate r3, 1
     32: Jump 29 (.L4)
  .L1:
     34: LoadImmediate r6, 3
     37: JumpToBooleanFalse r6, 5 (.L2)
     40: Jump -31 (.L0)
  .L2:
     42: LoadImmediate r6, 4
     45: JumpToBooleanFalse r6, 11 (.L3)
     48: LoadImmediate r3, 2
     51: Mov r4, a0
     54: Jump 7 (.L4)
  .L3:
     56: Jump 53 (.L9)
     58: LoadImmediate r3, 0
  .L4:
     61: Mov <scope>, r5
     64: IteratorClose r1
     66: Jump 17 (.L6)
     68: LoadImmediate r6, 0
     71: StrictEqual r6, r3, r6
     75: JumpFalse r6, 6 (.L5)
     78: Mov r5, r4
  .L5:
     81: Throw r5
  .L6:
     83: LoadImmediate r5, 0
     86: StrictEqual r5, r3, r5
     90: JumpFalse r5, 5 (.L7)
     93: Throw r4
  .L7:
     95: LoadImmediate r5, 2
     98: StrictEqual r5, r3, r5
    102: JumpFalse r5, 5 (.L8)
    105: Ret r4
  .L8:
    107: Jump 4 (.L10)
  .L9:
    109: Jump -100 (.L0)
  .L10:
    111: LoadImmediate r1, 5
    114: LoadUndefined r1
    116: Ret r1
  Exception Handlers:
    17-56 -> 58 (r4)
    64-66 -> 68 (r5)
}

[BytecodeFunction: lhsIdentifier] {
  Parameters: 1, Registers: 5
     0: LoadImmediate r0, 1
     3: NewArray r2
     5: GetIterator r0, r1, r2
  .L0:
     9: IteratorNext r2, r3, r0, r1
    14: JumpTrue r3, 23 (.L2)
    17: Mov a0, r2
    20: Mov r4, <scope>
    23: Jump 12 (.L1)
    25: LoadImmediate r2, 0
    28: Mov <scope>, r4
    31: IteratorClose r0
    33: Throw r3
  .L1:
    35: Jump -26 (.L0)
  .L2:
    37: LoadImmediate r0, 2
    40: LoadUndefined r0
    42: Ret r0
  Exception Handlers:
    17-23 -> 25 (r3)
    31-33 -> 33
}

[BytecodeFunction: lhsMember] {
  Parameters: 1, Registers: 6
     0: LoadImmediate r0, 1
     3: NewArray r2
     5: GetIterator r0, r1, r2
  .L0:
     9: IteratorNext r2, r3, r0, r1
    14: JumpTrue r3, 27 (.L2)
    17: SetNamedProperty a0, c0, r2
    21: Mov r4, <scope>
    24: LoadImmediate r5, 2
    27: Jump 12 (.L1)
    29: LoadImmediate r2, 0
    32: Mov <scope>, r4
    35: IteratorClose r0
    37: Throw r3
  .L1:
    39: Jump -30 (.L0)
  .L2:
    41: LoadImmediate r0, 3
    44: NewArray r2
    46: GetIterator r0, r1, r2
  .L3:
    50: IteratorNext r2, r3, r0, r1
    55: JumpTrue r3, 30 (.L5)
    58: LoadImmediate r3, 1
    61: SetProperty a0, r3, r2
    65: Mov r4, <scope>
    68: LoadImmediate r5, 4
    71: Jump 12 (.L4)
    73: LoadImmediate r2, 0
    76: Mov <scope>, r4
    79: IteratorClose r0
    81: Throw r3
  .L4:
    83: Jump -33 (.L3)
  .L5:
    85: LoadImmediate r0, 5
    88: LoadUndefined r0
    90: Ret r0
  Constant Table:
    0: [String: foo]
  Exception Handlers:
    17-27 -> 29 (r3)
    35-37 -> 37
    58-71 -> 73 (r3)
    79-81 -> 81
}

[BytecodeFunction: lhsDestructuring] {
  Parameters: 1, Registers: 9
      0: LoadImmediate r3, 1
      3: NewArray r5
      5: GetIterator r3, r4, r5
  .L0:
      9: IteratorNext r5, r6, r3, r4
     14: JumpTrue r6, 44 (.L3)
     17: GetNamedProperty r0, r5, c0
     21: GetNamedProperty r1, r5, c1
     25: GetNamedProperty r6, r5, c2
     29: JumpNotUndefined r6, 6 (.L1)
     32: LoadImmediate r6, 1
  .L1:
     35: Mov r2, r6
     38: Mov r7, <scope>
     41: LoadImmediate r8, 2
     44: Jump 12 (.L2)
     46: LoadImmediate r5, 0
     49: Mov <scope>, r7
     52: IteratorClose r3
     54: Throw r6
  .L2:
     56: Jump -47 (.L0)
  .L3:
     58: LoadImmediate r3, 3
     61: NewArray r5
     63: GetIterator r3, r4, r5
  .L4:
     67: IteratorNext r5, r6, r3, r4
     72: JumpTrue r6, 44 (.L7)
     75: GetNamedProperty r0, r5, c0
     79: GetNamedProperty r1, r5, c1
     83: GetNamedProperty r6, r5, c2
     87: JumpNotUndefined r6, 6 (.L5)
     90: LoadImmediate r6, 1
  .L5:
     93: Mov r2, r6
     96: Mov r7, <scope>
     99: LoadImmediate r8, 4
    102: Jump 12 (.L6)
    104: LoadImmediate r5, 0
    107: Mov <scope>, r7
    110: IteratorClose r3
    112: Throw r6
  .L6:
    114: Jump -47 (.L4)
  .L7:
    116: LoadImmediate r3, 5
    119: LoadUndefined r3
    121: Ret r3
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: d]
  Exception Handlers:
    17-44 -> 46 (r6)
    52-54 -> 54
    75-102 -> 104 (r6)
    110-112 -> 112
}

[BytecodeFunction: lhsTdz] {
  Parameters: 0, Registers: 7
      0: PushFunctionScope c0
      2: LoadEmpty r2
      4: StoreToScope r2, 0, 0
      8: PushLexicalScope c1
     10: LoadEmpty r2
     12: StoreToScope r2, 0, 0
     16: NewArray r4
     18: GetIterator r2, r3, r4
     22: PopScope 
  .L0:
     23: PushLexicalScope c1
     25: LoadEmpty r4
     27: StoreToScope r4, 0, 0
     31: IteratorNext r4, r5, r2, r3
     36: JumpTrue r5, 28 (.L2)
     39: StoreToScope r4, 0, 0
     43: Mov r6, <scope>
     46: NewClosure r1, c2
     49: Jump 12 (.L1)
     51: LoadImmediate r4, 0
     54: Mov <scope>, r6
     57: IteratorClose r2
     59: Throw r5
  .L1:
     61: PopScope 
     62: Jump -39 (.L0)
  .L2:
     64: PopScope 
     65: LoadImmediate r2, 1
     68: StoreToScope r2, 0, 0
     72: NewArray r4
     74: GetIterator r2, r3, r4
  .L3:
     78: IteratorNext r4, r5, r2, r3
     83: JumpTrue r5, 34 (.L5)
     86: LoadFromScope r5, 0, 0
     90: CheckTdz r5, c3
     93: StoreToScope r4, 0, 0
     97: Mov r6, <scope>
    100: NewClosure r0, c4
    103: Jump 12 (.L4)
    105: LoadImmediate r4, 0
    108: Mov <scope>, r6
    111: IteratorClose r2
    113: Throw r5
  .L4:
    115: Jump -37 (.L3)
  .L5:
    117: LoadUndefined r2
    119: Ret r2
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [BytecodeFunction: inner]
    3: [String: y]
    4: [BytecodeFunction: inner]
  Exception Handlers:
    39-49 -> 51 (r5)
    57-59 -> 59
    86-103 -> 105 (r5)
    111-113 -> 113
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: y]
}

[BytecodeFunction: forAwaitOf] {
  Parameters: 0, Registers: 9
     0: NewPromise r1
     2: LoadImmediate r2, 1
     5: NewArray r4
     7: GetAsyncIterator r2, r3, r4
  .L0:
    11: CallWithReceiver r6, r3, r2, r2, 0
    17: Await r6, r7, r1, r6
    22: JumpTrue r7, 5 (.L1)
    25: Throw r6
  .L1:
    27: IteratorUnpackResult r4, r5, r6
    31: JumpTrue r5, 43 (.L5)
    34: Mov r0, r4
    37: Mov r6, <scope>
    40: LoadImmediate r7, 2
    43: Jump 29 (.L4)
    45: LoadImmediate r4, 0
    48: Mov <scope>, r6
    51: AsyncIteratorCloseStart r7, r6, r2
    55: JumpFalse r6, 15 (.L3)
    58: Await r7, r8, r1, r7
    63: JumpTrue r8, 5 (.L2)
    66: Throw r7
  .L2:
    68: AsyncIteratorCloseFinish r7
  .L3:
    70: Throw r5
  .L4:
    72: Jump -61 (.L0)
  .L5:
    74: LoadImmediate r2, 3
    77: LoadUndefined r2
    79: ResolvePromise r1, r2
    82: Ret r1
    84: RejectPromise r1, r2
    87: Ret r1
  Exception Handlers:
    34-43 -> 45 (r5)
    51-70 -> 70
    2-84 -> 84 (r2)
}
