[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: LoadUndefined r0
    44: Ret r0
  Constant Table:
    0: [BytecodeFunction: basicVar]
    1: [String: basicVar]
    2: [BytecodeFunction: basicConstLet]
    3: [String: basicConstLet]
    4: [BytecodeFunction: testBreakAndContinue]
    5: [String: testBreakAndContinue]
    6: [BytecodeFunction: lhsIdentifier]
    7: [String: lhsIdentifier]
    8: [BytecodeFunction: lhsMember]
    9: [String: lhsMember]
    10: [BytecodeFunction: lhsDestructuring]
    11: [String: lhsDestructuring]
    12: [BytecodeFunction: lhsTdz]
    13: [String: lhsTdz]
}

[BytecodeFunction: basicVar] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r1, 1
     3: NewObject r1
     5: JumpNullish r1, 20 (.L1)
     8: NewForInIterator r1, r1
  .L0:
    11: ForInNext r2, r1
    14: JumpNullish r2, 11 (.L1)
    17: Mov r0, r2
    20: LoadImmediate r2, 2
    23: Jump -12 (.L0)
  .L1:
    25: LoadImmediate r1, 3
    28: LoadUndefined r1
    30: Ret r1
}

[BytecodeFunction: basicConstLet] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 1
     3: NewObject r2
     5: JumpNullish r2, 20 (.L1)
     8: NewForInIterator r2, r2
  .L0:
    11: ForInNext r3, r2
    14: JumpNullish r3, 11 (.L1)
    17: Mov r1, r3
    20: LoadImmediate r3, 2
    23: Jump -12 (.L0)
  .L1:
    25: LoadImmediate r2, 3
    28: NewObject r2
    30: JumpNullish r2, 20 (.L3)
    33: NewForInIterator r2, r2
  .L2:
    36: ForInNext r3, r2
    39: JumpNullish r3, 11 (.L3)
    42: Mov r0, r3
    45: LoadImmediate r3, 3
    48: Jump -12 (.L2)
  .L3:
    50: LoadImmediate r2, 4
    53: LoadUndefined r2
    55: Ret r2
}

[BytecodeFunction: testBreakAndContinue] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r1, 1
     3: NewObject r1
     5: JumpNullish r1, 33 (.L3)
     8: NewForInIterator r1, r1
  .L0:
    11: ForInNext r2, r1
    14: JumpNullish r2, 24 (.L3)
    17: Mov r0, r2
    20: LoadImmediate r2, 2
    23: JumpToBooleanFalse r2, 5 (.L1)
    26: Jump 12 (.L3)
  .L1:
    28: LoadImmediate r2, 3
    31: JumpToBooleanFalse r2, 5 (.L2)
    34: Jump -23 (.L0)
  .L2:
    36: Jump -25 (.L0)
  .L3:
    38: LoadImmediate r1, 4
    41: LoadUndefined r1
    43: Ret r1
}

[BytecodeFunction: lhsIdentifier] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: NewObject r0
     5: JumpNullish r0, 17 (.L1)
     8: NewForInIterator r0, r0
  .L0:
    11: ForInNext r1, r0
    14: JumpNullish r1, 8 (.L1)
    17: Mov a0, r1
    20: Jump -9 (.L0)
  .L1:
    22: LoadImmediate r0, 2
    25: LoadUndefined r0
    27: Ret r0
}

[BytecodeFunction: lhsMember] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 1
     3: NewObject r0
     5: JumpNullish r0, 21 (.L1)
     8: NewForInIterator r0, r0
  .L0:
    11: ForInNext r1, r0
    14: JumpNullish r1, 12 (.L1)
    17: SetNamedProperty a0, c0, r1
    21: LoadImmediate r1, 2
    24: Jump -13 (.L0)
  .L1:
    26: LoadImmediate r0, 3
    29: NewObject r0
    31: JumpNullish r0, 24 (.L3)
    34: NewForInIterator r0, r0
  .L2:
    37: ForInNext r1, r0
    40: JumpNullish r1, 15 (.L3)
    43: LoadImmediate r2, 1
    46: SetProperty a0, r2, r1
    50: LoadImmediate r1, 4
    53: Jump -16 (.L2)
  .L3:
    55: LoadImmediate r0, 5
    58: LoadUndefined r0
    60: Ret r0
  Constant Table:
    0: [String: foo]
}

[BytecodeFunction: lhsDestructuring] {
  Parameters: 1, Registers: 6
     0: LoadImmediate r3, 1
     3: NewObject r3
     5: JumpNullish r3, 38 (.L2)
     8: NewForInIterator r3, r3
  .L0:
    11: ForInNext r4, r3
    14: JumpNullish r4, 29 (.L2)
    17: GetNamedProperty r0, r4, c0
    21: GetNamedProperty r1, r4, c1
    25: GetNamedProperty r5, r4, c2
    29: JumpNotUndefined r5, 6 (.L1)
    32: LoadImmediate r5, 1
  .L1:
    35: Mov r2, r5
    38: LoadImmediate r4, 2
    41: Jump -30 (.L0)
  .L2:
    43: LoadImmediate r3, 3
    46: NewObject r3
    48: JumpNullish r3, 38 (.L5)
    51: NewForInIterator r3, r3
  .L3:
    54: ForInNext r4, r3
    57: JumpNullish r4, 29 (.L5)
    60: GetNamedProperty r0, r4, c0
    64: GetNamedProperty r1, r4, c1
    68: GetNamedProperty r5, r4, c2
    72: JumpNotUndefined r5, 6 (.L4)
    75: LoadImmediate r5, 1
  .L4:
    78: Mov r2, r5
    81: LoadImmediate r4, 4
    84: Jump -30 (.L3)
  .L5:
    86: LoadImmediate r3, 5
    89: LoadUndefined r3
    91: Ret r3
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: d]
}

[BytecodeFunction: lhsTdz] {
  Parameters: 0, Registers: 5
     0: PushFunctionScope c0
     2: LoadEmpty r2
     4: StoreToScope r2, 0, 0
     8: PushLexicalScope c1
    10: LoadEmpty r2
    12: StoreToScope r2, 0, 0
    16: NewObject r2
    18: JumpNullish r2, 31 (.L1)
    21: NewForInIterator r2, r2
    24: PopScope 
  .L0:
    25: PushLexicalScope c1
    27: LoadEmpty r3
    29: StoreToScope r3, 0, 0
    33: ForInNext r3, r2
    36: JumpNullish r3, 13 (.L1)
    39: StoreToScope r3, 0, 0
    43: NewClosure r1, c2
    46: PopScope 
    47: Jump -22 (.L0)
  .L1:
    49: PopScope 
    50: LoadImmediate r2, 1
    53: StoreToScope r2, 0, 0
    57: NewObject r2
    59: JumpNullish r2, 28 (.L3)
    62: NewForInIterator r2, r2
  .L2:
    65: ForInNext r3, r2
    68: JumpNullish r3, 19 (.L3)
    71: LoadFromScope r4, 0, 0
    75: CheckTdz r4, c3
    78: StoreToScope r3, 0, 0
    82: NewClosure r0, c4
    85: Jump -20 (.L2)
  .L3:
    87: LoadUndefined r2
    89: Ret r2
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [BytecodeFunction: inner]
    3: [String: y]
    4: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: y]
}
