[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: LoadUndefined r0
    32: Ret r0
  Constant Table:
    0: [BytecodeFunction: basicVar]
    1: [String: basicVar]
    2: [BytecodeFunction: basicConstLet]
    3: [String: basicConstLet]
    4: [BytecodeFunction: testBreakAndContinue]
    5: [String: testBreakAndContinue]
    6: [BytecodeFunction: lhsIdentifier]
    7: [String: lhsIdentifier]
    8: [BytecodeFunction: lhsMember]
    9: [String: lhsMember]
}

[BytecodeFunction: basicVar] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r1, 1
     3: NewObject r1
     5: JumpNullish r1, 17 (.L1)
     8: NewForInIterator r1, r1
  .L0:
    11: ForInNext r0, r1
    14: JumpNullish r0, 8 (.L1)
    17: LoadImmediate r2, 2
    20: Jump -9 (.L0)
  .L1:
    22: LoadImmediate r1, 3
    25: LoadUndefined r1
    27: Ret r1
}

[BytecodeFunction: basicConstLet] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 1
     3: NewObject r2
     5: JumpNullish r2, 17 (.L1)
     8: NewForInIterator r2, r2
  .L0:
    11: ForInNext r1, r2
    14: JumpNullish r1, 8 (.L1)
    17: LoadImmediate r3, 2
    20: Jump -9 (.L0)
  .L1:
    22: LoadImmediate r2, 3
    25: NewObject r2
    27: JumpNullish r2, 17 (.L3)
    30: NewForInIterator r2, r2
  .L2:
    33: ForInNext r0, r2
    36: JumpNullish r0, 8 (.L3)
    39: LoadImmediate r3, 3
    42: Jump -9 (.L2)
  .L3:
    44: LoadImmediate r2, 4
    47: LoadUndefined r2
    49: Ret r2
}

[BytecodeFunction: testBreakAndContinue] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r1, 1
     3: NewObject r1
     5: JumpNullish r1, 30 (.L3)
     8: NewForInIterator r1, r1
  .L0:
    11: ForInNext r0, r1
    14: JumpNullish r0, 21 (.L3)
    17: LoadImmediate r2, 2
    20: JumpToBooleanFalse r2, 5 (.L1)
    23: Jump 12 (.L3)
  .L1:
    25: LoadImmediate r2, 3
    28: JumpToBooleanFalse r2, 5 (.L2)
    31: Jump -20 (.L0)
  .L2:
    33: Jump -22 (.L0)
  .L3:
    35: LoadImmediate r1, 4
    38: LoadUndefined r1
    40: Ret r1
}

[BytecodeFunction: lhsIdentifier] {
  Parameters: 1, Registers: 1
     0: LoadImmediate r0, 1
     3: NewObject r0
     5: JumpNullish r0, 14 (.L1)
     8: NewForInIterator r0, r0
  .L0:
    11: ForInNext a0, r0
    14: JumpNullish a0, 5 (.L1)
    17: Jump -6 (.L0)
  .L1:
    19: LoadImmediate r0, 2
    22: LoadUndefined r0
    24: Ret r0
}

[BytecodeFunction: lhsMember] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 1
     3: NewObject r0
     5: JumpNullish r0, 21 (.L1)
     8: NewForInIterator r0, r0
  .L0:
    11: ForInNext r1, r0
    14: JumpNullish r1, 12 (.L1)
    17: SetNamedProperty a0, c0, r1
    21: LoadImmediate r2, 2
    24: Jump -13 (.L0)
  .L1:
    26: LoadImmediate r0, 3
    29: NewObject r0
    31: JumpNullish r0, 24 (.L3)
    34: NewForInIterator r0, r0
  .L2:
    37: ForInNext r1, r0
    40: JumpNullish r1, 15 (.L3)
    43: LoadImmediate r2, 1
    46: SetProperty a0, r2, r1
    50: LoadImmediate r2, 4
    53: Jump -16 (.L2)
  .L3:
    55: LoadImmediate r0, 5
    58: LoadUndefined r0
    60: Ret r0
  Constant Table:
    0: [String: foo]
}
