[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: 11 ff 00   NewClosure r0, c0
     3: 07 ff 01   StoreGlobal r0, c1
     6: 11 ff 02   NewClosure r0, c2
     9: 07 ff 03   StoreGlobal r0, c3
    12: 11 ff 04   NewClosure r0, c4
    15: 07 ff 05   StoreGlobal r0, c5
    18: 11 ff 06   NewClosure r0, c6
    21: 07 ff 07   StoreGlobal r0, c7
    24: 11 ff 08   NewClosure r0, c8
    27: 07 ff 09   StoreGlobal r0, c9
    30: 05 ff      LoadUndefined r0
    32: 09 ff      Ret r0
  Constant Table:
    0: [BytecodeFunction: testNoAlternate]
    1: [String: testNoAlternate]
    2: [BytecodeFunction: testAlternate]
    3: [String: testAlternate]
    4: [BytecodeFunction: testNested]
    5: [String: testNested]
    6: [BytecodeFunction: testIfElse]
    7: [String: testIfElse]
    8: [BytecodeFunction: testIfElseNoCatchAll]
    9: [String: testIfElseNoCatchAll]
}

[BytecodeFunction: testNoAlternate] {
  Parameters: 1, Registers: 1
     0: 0f 05 08   JumpFalse a0, 8 (.L0)
     3: 03 ff 01   LoadImmediate r0, 1
     6: 09 ff      Ret r0
  .L0:
     8: 03 ff 02   LoadImmediate r0, 2
    11: 09 ff      Ret r0
}

[BytecodeFunction: testAlternate] {
  Parameters: 1, Registers: 1
     0: 0f 05 0a   JumpFalse a0, 10 (.L0)
     3: 03 ff 01   LoadImmediate r0, 1
     6: 09 ff      Ret r0
     8: 0d 07      Jump 7 (.L1)
  .L0:
    10: 03 ff 02   LoadImmediate r0, 2
    13: 09 ff      Ret r0
}

[BytecodeFunction: testNested] {
  Parameters: 2, Registers: 1
     0: 0f 05 14   JumpFalse a0, 20 (.L2)
     3: 0f 06 0a   JumpFalse a1, 10 (.L0)
     6: 03 ff 01   LoadImmediate r0, 1
     9: 09 ff      Ret r0
    11: 0d 07      Jump 7 (.L1)
  .L0:
    13: 03 ff 02   LoadImmediate r0, 2
    16: 09 ff      Ret r0
  .L1:
    18: 0d 11      Jump 17 (.L4)
  .L2:
    20: 0f 06 0a   JumpFalse a1, 10 (.L3)
    23: 03 ff 03   LoadImmediate r0, 3
    26: 09 ff      Ret r0
    28: 0d 07      Jump 7 (.L4)
  .L3:
    30: 03 ff 04   LoadImmediate r0, 4
    33: 09 ff      Ret r0
}

[BytecodeFunction: testIfElse] {
  Parameters: 3, Registers: 1
     0: 0f 05 0a   JumpFalse a0, 10 (.L0)
     3: 03 ff 01   LoadImmediate r0, 1
     6: 09 ff      Ret r0
     8: 0d 1b      Jump 27 (.L3)
  .L0:
    10: 0f 06 0a   JumpFalse a1, 10 (.L1)
    13: 03 ff 02   LoadImmediate r0, 2
    16: 09 ff      Ret r0
    18: 0d 11      Jump 17 (.L3)
  .L1:
    20: 0f 07 0a   JumpFalse a2, 10 (.L2)
    23: 03 ff 03   LoadImmediate r0, 3
    26: 09 ff      Ret r0
    28: 0d 07      Jump 7 (.L3)
  .L2:
    30: 03 ff 04   LoadImmediate r0, 4
    33: 09 ff      Ret r0
}

[BytecodeFunction: testIfElseNoCatchAll] {
  Parameters: 2, Registers: 1
     0: 0f 05 0a   JumpFalse a0, 10 (.L0)
     3: 03 ff 01   LoadImmediate r0, 1
     6: 09 ff      Ret r0
     8: 0d 0a      Jump 10 (.L1)
  .L0:
    10: 0f 06 08   JumpFalse a1, 8 (.L1)
    13: 03 ff 02   LoadImmediate r0, 2
    16: 09 ff      Ret r0
  .L1:
    18: 03 ff 03   LoadImmediate r0, 3
    21: 09 ff      Ret r0
}
