[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: NewClosure r0, c11
    35: StoreGlobal r0, c12
    38: LoadUndefined r0
    40: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: testNoAlternate]
    2: [String: testNoAlternate]
    3: [BytecodeFunction: testAlternate]
    4: [String: testAlternate]
    5: [BytecodeFunction: testNested]
    6: [String: testNested]
    7: [BytecodeFunction: testIfElse]
    8: [String: testIfElse]
    9: [BytecodeFunction: testIfElseNoCatchAll]
    10: [String: testIfElseNoCatchAll]
    11: [BytecodeFunction: testIfNoToBoolean]
    12: [String: testIfNoToBoolean]
}

[BytecodeFunction: testNoAlternate] {
  Parameters: 1, Registers: 1
     0: JumpToBooleanFalse a0, 8 (.L0)
     3: LoadImmediate r0, 1
     6: Ret r0
  .L0:
     8: LoadImmediate r0, 2
    11: Ret r0
}

[BytecodeFunction: testAlternate] {
  Parameters: 1, Registers: 1
     0: JumpToBooleanFalse a0, 8 (.L0)
     3: LoadImmediate r0, 1
     6: Ret r0
  .L0:
     8: LoadImmediate r0, 2
    11: Ret r0
}

[BytecodeFunction: testNested] {
  Parameters: 2, Registers: 1
     0: JumpToBooleanFalse a0, 16 (.L1)
     3: JumpToBooleanFalse a1, 8 (.L0)
     6: LoadImmediate r0, 1
     9: Ret r0
  .L0:
    11: LoadImmediate r0, 2
    14: Ret r0
  .L1:
    16: JumpToBooleanFalse a1, 8 (.L2)
    19: LoadImmediate r0, 3
    22: Ret r0
  .L2:
    24: LoadImmediate r0, 4
    27: Ret r0
}

[BytecodeFunction: testIfElse] {
  Parameters: 3, Registers: 1
     0: JumpToBooleanFalse a0, 8 (.L0)
     3: LoadImmediate r0, 1
     6: Ret r0
  .L0:
     8: JumpToBooleanFalse a1, 8 (.L1)
    11: LoadImmediate r0, 2
    14: Ret r0
  .L1:
    16: JumpToBooleanFalse a2, 8 (.L2)
    19: LoadImmediate r0, 3
    22: Ret r0
  .L2:
    24: LoadImmediate r0, 4
    27: Ret r0
}

[BytecodeFunction: testIfElseNoCatchAll] {
  Parameters: 2, Registers: 1
     0: JumpToBooleanFalse a0, 8 (.L0)
     3: LoadImmediate r0, 1
     6: Ret r0
  .L0:
     8: JumpToBooleanFalse a1, 8 (.L1)
    11: LoadImmediate r0, 2
    14: Ret r0
  .L1:
    16: LoadImmediate r0, 3
    19: Ret r0
}

[BytecodeFunction: testIfNoToBoolean] {
  Parameters: 1, Registers: 1
     0: LessThan r0, a0, a0
     4: JumpFalse r0, 8 (.L0)
     7: LoadImmediate r0, 1
    10: Ret r0
  .L0:
    12: LessThan r0, a0, a0
    16: JumpFalse r0, 8 (.L1)
    19: LoadImmediate r0, 2
    22: Ret r0
  .L1:
    24: LoadImmediate r0, 3
    27: Ret r0
}
