[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: LoadUndefined r0
    10: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: completion]
    2: [String: completion]
}

[BytecodeFunction: completion] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: Throw r0
     5: LoadImmediate r0, 2
     8: LoadUndefined r0
    10: Ret r0
}
