[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: StoreGlobal r0, c1
    6: LoadUndefined r0
    8: Ret r0
  Constant Table:
    0: [BytecodeFunction: completion]
    1: [String: completion]
}

[BytecodeFunction: completion] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: Throw r0
     5: LoadImmediate r0, 2
     8: LoadUndefined r0
    10: Ret r0
}
