[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: NewClosure r0, c11
    35: StoreGlobal r0, c12
    38: NewClosure r0, c13
    41: StoreGlobal r0, c14
    44: NewClosure r0, c15
    47: StoreGlobal r0, c16
    50: LoadUndefined r0
    52: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: empty]
    2: [String: empty]
    3: [BytecodeFunction: singleCaseWithFallthrough]
    4: [String: singleCaseWithFallthrough]
    5: [BytecodeFunction: singleCaseWithBreak]
    6: [String: singleCaseWithBreak]
    7: [BytecodeFunction: multipleCases]
    8: [String: multipleCases]
    9: [BytecodeFunction: singleDefaultCase]
    10: [String: singleDefaultCase]
    11: [BytecodeFunction: multipleCasesWithDefault]
    12: [String: multipleCasesWithDefault]
    13: [BytecodeFunction: multipleCasesWithDefaultInMiddle]
    14: [String: multipleCasesWithDefaultInMiddle]
    15: [BytecodeFunction: multipleCasesWithDefaultInMiddleFallthrough]
    16: [String: multipleCasesWithDefaultInMiddleFallthrough]
}

[BytecodeFunction: empty] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: Jump 2 (.L0)
  .L0:
     7: LoadImmediate r0, 2
    10: LoadUndefined r0
    12: Ret r0
}

[BytecodeFunction: singleCaseWithFallthrough] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r1, 2
     8: StrictEqual r1, r0, r1
    12: JumpTrue r1, 5 (.L0)
    15: Jump 5 (.L1)
  .L0:
    17: LoadImmediate r0, 3
  .L1:
    20: LoadImmediate r0, 4
    23: LoadUndefined r0
    25: Ret r0
}

[BytecodeFunction: singleCaseWithBreak] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r1, 2
     8: StrictEqual r1, r0, r1
    12: JumpTrue r1, 5 (.L0)
    15: Jump 7 (.L1)
  .L0:
    17: LoadImmediate r0, 3
    20: Jump 2 (.L1)
  .L1:
    22: LoadImmediate r0, 4
    25: LoadUndefined r0
    27: Ret r0
}

[BytecodeFunction: multipleCases] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r1, 2
     8: StrictEqual r1, r0, r1
    12: JumpTrue r1, 25 (.L0)
    15: LoadImmediate r1, 4
    18: StrictEqual r1, r0, r1
    22: JumpTrue r1, 20 (.L1)
    25: LoadImmediate r1, 6
    28: StrictEqual r1, r0, r1
    32: JumpTrue r1, 13 (.L2)
    35: Jump 15 (.L3)
  .L0:
    37: LoadImmediate r0, 3
    40: Jump 10 (.L3)
  .L1:
    42: LoadImmediate r0, 5
  .L2:
    45: LoadImmediate r0, 7
    48: Jump 2 (.L3)
  .L3:
    50: LoadImmediate r0, 3
    53: LoadUndefined r0
    55: Ret r0
}

[BytecodeFunction: singleDefaultCase] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: Jump 2 (.L0)
  .L0:
     7: LoadImmediate r0, 2
    10: LoadImmediate r0, 3
    13: LoadUndefined r0
    15: Ret r0
}

[BytecodeFunction: multipleCasesWithDefault] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r1, 2
     8: StrictEqual r1, r0, r1
    12: JumpTrue r1, 15 (.L0)
    15: LoadImmediate r1, 4
    18: StrictEqual r1, r0, r1
    22: JumpTrue r1, 10 (.L1)
    25: Jump 12 (.L2)
  .L0:
    27: LoadImmediate r0, 3
    30: Jump 12 (.L3)
  .L1:
    32: LoadImmediate r0, 5
    35: Jump 7 (.L3)
  .L2:
    37: LoadImmediate r0, 6
    40: Jump 2 (.L3)
  .L3:
    42: LoadImmediate r0, 7
    45: LoadUndefined r0
    47: Ret r0
}

[BytecodeFunction: multipleCasesWithDefaultInMiddle] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r1, 2
     8: StrictEqual r1, r0, r1
    12: JumpTrue r1, 15 (.L0)
    15: LoadImmediate r1, 5
    18: StrictEqual r1, r0, r1
    22: JumpTrue r1, 15 (.L2)
    25: Jump 7 (.L1)
  .L0:
    27: LoadImmediate r0, 3
    30: Jump 12 (.L3)
  .L1:
    32: LoadImmediate r0, 4
    35: Jump 7 (.L3)
  .L2:
    37: LoadImmediate r0, 6
    40: Jump 2 (.L3)
  .L3:
    42: LoadImmediate r0, 7
    45: LoadUndefined r0
    47: Ret r0
}

[BytecodeFunction: multipleCasesWithDefaultInMiddleFallthrough] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r1, 2
     8: StrictEqual r1, r0, r1
    12: JumpTrue r1, 15 (.L0)
    15: LoadImmediate r1, 5
    18: StrictEqual r1, r0, r1
    22: JumpTrue r1, 11 (.L2)
    25: Jump 5 (.L1)
  .L0:
    27: LoadImmediate r0, 3
  .L1:
    30: LoadImmediate r0, 4
  .L2:
    33: LoadImmediate r0, 6
    36: LoadImmediate r0, 7
    39: LoadUndefined r0
    41: Ret r0
}
