[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: LoadUndefined r0
    14: Ret r0
  Constant Table:
    0: [BytecodeFunction: testThrow]
    1: [String: testThrow]
    2: [BytecodeFunction: testAbrupt]
    3: [String: testAbrupt]
}

[BytecodeFunction: testThrow] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 23
    3: Throw r0
}

[BytecodeFunction: testAbrupt] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 1
    3: Throw r0
}
