[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: LoadUndefined r0
    16: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: testThrow]
    2: [String: testThrow]
    3: [BytecodeFunction: testAbrupt]
    4: [String: testAbrupt]
}

[BytecodeFunction: testThrow] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 23
    3: Throw r0
}

[BytecodeFunction: testAbrupt] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 1
    3: Throw r0
}
