[CompiledRegExp: /a\bc/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: Literal(a)
     3: CompareBetween(0, 9)
     5: CompareBetween(A, Z)
     7: CompareEquals(_)
     8: CompareBetween(a, z)
    10: WordBoundaryMoveToPrevious
    11: CompareBetween(0, 9)
    13: CompareBetween(A, Z)
    15: CompareEquals(_)
    16: CompareBetween(a, z)
    18: AssertWordBoundary
    19: Literal(c)
    20: MarkCapturePoint(1)
    22: Accept
}

[CompiledRegExp: /a\Bc/] {
  Flags: ""
  Match Start: Code Points("a")
     0: MarkCapturePoint(0)
     2: Literal(a)
     3: CompareBetween(0, 9)
     5: CompareBetween(A, Z)
     7: CompareEquals(_)
     8: CompareBetween(a, z)
    10: WordBoundaryMoveToPrevious
    11: CompareBetween(0, 9)
    13: CompareBetween(A, Z)
    15: CompareEquals(_)
    16: CompareBetween(a, z)
    18: AssertNotWordBoundary
    19: Literal(c)
    20: MarkCapturePoint(1)
    22: Accept
}
