[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: LoadUndefined r0
    14: Ret r0
  Constant Table:
    0: [BytecodeFunction: startScope]
    1: [String: startScope]
    2: [BytecodeFunction: captures]
    3: [String: captures]
}

[BytecodeFunction: startScope] {
  Parameters: 0, Registers: 5
     0: LoadImmediate r0, 1
     3: LoadImmediate r1, 2
     6: LoadEmpty r2
     8: LoadEmpty r3
    10: CheckTdz r2, c0
    13: CheckTdz r3, c1
    16: LoadUndefined r4
    18: Ret r4
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: captures] {
  Parameters: 0, Registers: 2
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: LoadImmediate r1, 1
    11: StoreToScope r1, 0, 0
    15: NewClosure r0, c1
    18: PopScope 
    19: LoadUndefined r1
    21: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: foo]
}

[BytecodeFunction: foo] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}
