[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: LoadImmediate r0, 1
    33: StoreToScope r0, 1, 0
    37: LoadUndefined r0
    39: Ret r0
  Constant Table:
    0: [BytecodeFunction: startScope]
    1: [String: startScope]
    2: [BytecodeFunction: captures]
    3: [String: captures]
    4: [BytecodeFunction: abruptEndReturn]
    5: [String: abruptEndReturn]
    6: [BytecodeFunction: abruptEndThrow]
    7: [String: abruptEndThrow]
    8: [BytecodeFunction: abruptEndBreak]
    9: [String: abruptEndBreak]
}

[BytecodeFunction: startScope] {
  Parameters: 0, Registers: 5
     0: LoadImmediate r0, 1
     3: LoadImmediate r1, 2
     6: LoadEmpty r2
     8: LoadEmpty r3
    10: CheckTdz r2, c0
    13: CheckTdz r3, c1
    16: LoadUndefined r4
    18: Ret r4
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: captures] {
  Parameters: 0, Registers: 2
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: NewClosure r0, c1
    11: LoadImmediate r1, 1
    14: StoreToScope r1, 0, 0
    18: PopScope 
    19: LoadUndefined r1
    21: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: foo]
}

[BytecodeFunction: foo] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: abruptEndReturn] {
  Parameters: 0, Registers: 1
     0: PushLexicalScope c0
     2: LoadEmpty r0
     4: StoreToScope r0, 0, 0
     8: LoadImmediate r0, 1
    11: StoreToScope r0, 0, 0
    15: NewClosure r0, c1
    18: LoadTrue r0
    20: JumpFalse r0, 6 (.L0)
    23: PopScope 
    24: Jump 6 (.L1)
  .L0:
    26: LoadUndefined r0
    28: Ret r0
  .L1:
    30: LoadFromScope r0, 1, 0
    34: CheckTdz r0, c2
    37: LoadUndefined r0
    39: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
    2: [String: outerScope]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: abruptEndThrow] {
  Parameters: 0, Registers: 1
     0: PushLexicalScope c0
     2: LoadEmpty r0
     4: StoreToScope r0, 0, 0
     8: LoadImmediate r0, 1
    11: StoreToScope r0, 0, 0
    15: NewClosure r0, c1
    18: LoadTrue r0
    20: JumpFalse r0, 6 (.L0)
    23: PopScope 
    24: Jump 7 (.L1)
  .L0:
    26: LoadImmediate r0, 2
    29: Throw r0
  .L1:
    31: LoadFromScope r0, 1, 0
    35: CheckTdz r0, c2
    38: LoadUndefined r0
    40: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
    2: [String: outerScope]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: abruptEndBreak] {
  Parameters: 0, Registers: 1
     0: PushLexicalScope c0
     2: LoadEmpty r0
     4: StoreToScope r0, 0, 0
     8: LoadImmediate r0, 1
    11: StoreToScope r0, 0, 0
    15: NewClosure r0, c1
    18: PopScope 
    19: Jump 2 (.L0)
  .L0:
    21: LoadFromScope r0, 1, 0
    25: CheckTdz r0, c2
    28: LoadUndefined r0
    30: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
    2: [String: outerScope]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}
