[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: StoreGlobal r0, c1
    6: LoadUndefined r0
    8: Ret r0
  Constant Table:
    0: [BytecodeFunction: startScope]
    1: [String: startScope]
}

[BytecodeFunction: startScope] {
  Parameters: 0, Registers: 5
     0: LoadImmediate r0, 1
     3: LoadImmediate r1, 2
     6: LoadEmpty r2
     8: LoadEmpty r3
    10: CheckTdz r2, c0
    13: CheckTdz r3, c1
    16: LoadUndefined r4
    18: Ret r4
  Constant Table:
    0: [String: x]
    1: [String: y]
}
