[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: LoadUndefined r0
    26: Ret r0
  Constant Table:
    0: [BytecodeFunction: startScope]
    1: [String: startScope]
    2: [BytecodeFunction: capturesWithCapturedParam]
    3: [String: capturesWithCapturedParam]
    4: [BytecodeFunction: capturesNoParam]
    5: [String: capturesNoParam]
    6: [BytecodeFunction: capturesWithUncapturedParam]
    7: [String: capturesWithUncapturedParam]
}

[BytecodeFunction: startScope] {
  Parameters: 0, Registers: 5
     0: LoadImmediate r3, 1
     3: Jump 35 (.L1)
     5: LoadEmpty r1
     7: LoadEmpty r2
     9: GetNamedProperty r4, r3, c0
    13: JumpNotUndefined r4, 9 (.L0)
    16: CheckTdz r1, c1
    19: Mov r4, r1
  .L0:
    22: Mov r0, r4
    25: GetNamedProperty r1, r3, c1
    29: LoadImmediate r3, 2
    32: CheckTdz r2, c2
    35: LoadImmediate r2, 1
  .L1:
    38: LoadUndefined r3
    40: Ret r3
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: x]
  Exception Handlers:
    0-3 -> 5 (r3)
}

[BytecodeFunction: capturesWithCapturedParam] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r1, 1
     3: Jump 30 (.L0)
     5: PushLexicalScope c0
     7: LoadEmpty r1
     9: StoreToScope r1, 0, 0
    13: LoadEmpty r1
    15: StoreToScope r1, 1, 0
    19: StoreToScope r1, 0, 0
    23: LoadImmediate r1, 1
    26: StoreToScope r1, 1, 0
    30: NewClosure r0, c1
  .L0:
    33: LoadUndefined r1
    35: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner]
  Exception Handlers:
    0-3 -> 5 (r1)
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 0
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 1, 0
    11: CheckTdz r1, c1
    14: Add r0, r0, r1
    18: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: capturesNoParam] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r1, 1
     3: Jump 20 (.L0)
     5: PushLexicalScope c0
     7: LoadEmpty r1
     9: StoreToScope r1, 0, 0
    13: LoadImmediate r1, 1
    16: StoreToScope r1, 0, 0
    20: NewClosure r0, c1
  .L0:
    23: LoadUndefined r1
    25: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner]
  Exception Handlers:
    0-3 -> 5
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: capturesWithUncapturedParam] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r2, 1
     3: Jump 24 (.L0)
     5: PushLexicalScope c0
     7: LoadEmpty r2
     9: StoreToScope r2, 0, 0
    13: LoadImmediate r2, 1
    16: Add r2, r2, r0
    20: StoreToScope r2, 0, 0
    24: NewClosure r1, c1
  .L0:
    27: LoadUndefined r2
    29: Ret r2
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner]
  Exception Handlers:
    0-3 -> 5 (r0)
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: y]
}
