[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: LoadUndefined r0
    26: Ret r0
  Constant Table:
    0: [BytecodeFunction: forCaptureAndInnerCaptureWithBreak]
    1: [String: forCaptureAndInnerCaptureWithBreak]
    2: [BytecodeFunction: forCaptureNoInnerCaptureWithBreak]
    3: [String: forCaptureNoInnerCaptureWithBreak]
    4: [BytecodeFunction: noForCaptureButInnerCaptureWithBreak]
    5: [String: noForCaptureButInnerCaptureWithBreak]
    6: [BytecodeFunction: noForCaptureOrInnerCaptureWithBreak]
    7: [String: noForCaptureOrInnerCaptureWithBreak]
}

[BytecodeFunction: forCaptureAndInnerCaptureWithBreak] {
  Parameters: 0, Registers: 2
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: LoadImmediate r1, 0
    11: StoreToScope r1, 0, 0
    15: DupScope 
  .L0:
    16: LoadTrue r1
    18: JumpFalse r1, 62 (.L3)
    21: PushLexicalScope c1
    23: LoadEmpty r1
    25: StoreToScope r1, 0, 0
    29: LoadImmediate r1, 1
    32: StoreToScope r1, 0, 0
    36: LoadImmediate r1, 2
    39: JumpToBooleanFalse r1, 7 (.L1)
    42: PopScope 
    43: PopScope 
    44: Jump 37 (.L4)
  .L1:
    46: PushLexicalScope c2
    48: LoadEmpty r1
    50: StoreToScope r1, 0, 0
    54: NewClosure r0, c3
    57: LoadImmediate r1, 3
    60: StoreToScope r1, 0, 0
    64: LoadImmediate r1, 4
    67: JumpToBooleanFalse r1, 8 (.L2)
    70: PopScope 
    71: PopScope 
    72: PopScope 
    73: Jump 8 (.L4)
  .L2:
    75: PopScope 
    76: PopScope 
    77: DupScope 
    78: Jump -62 (.L0)
  .L3:
    80: PopScope 
  .L4:
    81: LoadUndefined r1
    83: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 1
    11: CheckTdz r1, c1
    14: Add r0, r0, r1
    18: LoadFromScope r1, 0, 0
    22: CheckTdz r1, c2
    25: Add r0, r0, r1
    29: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
    2: [String: z]
}

[BytecodeFunction: forCaptureNoInnerCaptureWithBreak] {
  Parameters: 0, Registers: 2
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: LoadImmediate r1, 0
    11: StoreToScope r1, 0, 0
    15: DupScope 
  .L0:
    16: LoadTrue r1
    18: JumpFalse r1, 44 (.L3)
    21: LoadImmediate r1, 2
    24: JumpToBooleanFalse r1, 6 (.L1)
    27: PopScope 
    28: Jump 35 (.L4)
  .L1:
    30: PushLexicalScope c1
    32: LoadEmpty r1
    34: StoreToScope r1, 0, 0
    38: NewClosure r0, c2
    41: LoadImmediate r1, 3
    44: StoreToScope r1, 0, 0
    48: LoadImmediate r1, 4
    51: JumpToBooleanFalse r1, 7 (.L2)
    54: PopScope 
    55: PopScope 
    56: Jump 7 (.L4)
  .L2:
    58: PopScope 
    59: DupScope 
    60: Jump -44 (.L0)
  .L3:
    62: PopScope 
  .L4:
    63: LoadUndefined r1
    65: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 1
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 0
    11: CheckTdz r1, c1
    14: Add r0, r0, r1
    18: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: noForCaptureButInnerCaptureWithBreak] {
  Parameters: 0, Registers: 2
     0: PushFunctionScope c0
     2: LoadImmediate r1, 0
     5: StoreToScope r1, 0, 0
  .L0:
     9: LoadTrue r1
    11: JumpFalse r1, 59 (.L3)
    14: PushLexicalScope c1
    16: LoadEmpty r1
    18: StoreToScope r1, 0, 0
    22: LoadImmediate r1, 1
    25: StoreToScope r1, 0, 0
    29: LoadImmediate r1, 2
    32: JumpToBooleanFalse r1, 6 (.L1)
    35: PopScope 
    36: Jump 34 (.L3)
  .L1:
    38: PushLexicalScope c2
    40: LoadEmpty r1
    42: StoreToScope r1, 0, 0
    46: NewClosure r0, c3
    49: LoadImmediate r1, 3
    52: StoreToScope r1, 0, 0
    56: LoadImmediate r1, 4
    59: JumpToBooleanFalse r1, 7 (.L2)
    62: PopScope 
    63: PopScope 
    64: Jump 6 (.L3)
  .L2:
    66: PopScope 
    67: PopScope 
    68: Jump -59 (.L0)
  .L3:
    70: LoadUndefined r1
    72: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: LoadFromScope r1, 0, 1
     8: CheckTdz r1, c0
    11: Add r0, r0, r1
    15: LoadFromScope r1, 0, 0
    19: CheckTdz r1, c1
    22: Add r0, r0, r1
    26: Ret r0
  Constant Table:
    0: [String: y]
    1: [String: z]
}

[BytecodeFunction: noForCaptureOrInnerCaptureWithBreak] {
  Parameters: 0, Registers: 2
     0: PushFunctionScope c0
     2: LoadImmediate r1, 0
     5: StoreToScope r1, 0, 0
  .L0:
     9: LoadTrue r1
    11: JumpFalse r1, 48 (.L3)
    14: LoadImmediate r1, 1
    17: StoreToScope r1, 1, 0
    21: LoadImmediate r1, 2
    24: JumpToBooleanFalse r1, 5 (.L1)
    27: Jump 32 (.L3)
  .L1:
    29: PushLexicalScope c1
    31: LoadEmpty r1
    33: StoreToScope r1, 0, 0
    37: NewClosure r0, c2
    40: LoadImmediate r1, 3
    43: StoreToScope r1, 0, 0
    47: LoadImmediate r1, 4
    50: JumpToBooleanFalse r1, 6 (.L2)
    53: PopScope 
    54: Jump 5 (.L3)
  .L2:
    56: PopScope 
    57: Jump -48 (.L0)
  .L3:
    59: LoadUndefined r1
    61: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 1
     4: LoadFromScope r1, 1, 1
     8: Add r0, r0, r1
    12: LoadFromScope r1, 0, 0
    16: CheckTdz r1, c0
    19: Add r0, r0, r1
    23: Ret r0
  Constant Table:
    0: [String: z]
}
