[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: LoadUndefined r0
    32: Ret r0
  Constant Table:
    0: [BytecodeFunction: sameNameNoCaptures]
    1: [String: sameNameNoCaptures]
    2: [BytecodeFunction: sameNameCaptureParamOnly]
    3: [String: sameNameCaptureParamOnly]
    4: [BytecodeFunction: sameNameCaptureBodyOnly]
    5: [String: sameNameCaptureBodyOnly]
    6: [BytecodeFunction: sameNameBothCaptures]
    7: [String: sameNameBothCaptures]
    8: [BytecodeFunction: tdzAfterParams]
    9: [String: tdzAfterParams]
}

[BytecodeFunction: sameNameNoCaptures] {
  Parameters: 2, Registers: 2
     0: JumpNotUndefined a0, 6 (.L0)
     3: LoadImmediate a0, 1
  .L0:
     6: JumpNotUndefined a1, 6 (.L1)
     9: Mov a1, a0
  .L1:
    12: LoadImmediate r0, 2
    15: LoadImmediate r1, 3
    18: Add r1, r0, r1
    22: LoadUndefined r1
    24: Ret r1
}

[BytecodeFunction: sameNameCaptureParamOnly] {
  Parameters: 2, Registers: 2
     0: PushLexicalScope c0
     2: JumpNotUndefined a0, 6 (.L0)
     5: LoadImmediate a0, 1
  .L0:
     8: StoreToScope a0, 0, 0
    12: JumpNotUndefined a1, 6 (.L1)
    15: NewClosure a1, c1
  .L1:
    18: LoadImmediate r0, 2
    21: LoadImmediate r1, 3
    24: Add r1, r0, r1
    28: LoadUndefined r1
    30: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: y]
}

[BytecodeFunction: y] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: Ret r0
}

[BytecodeFunction: sameNameCaptureBodyOnly] {
  Parameters: 2, Registers: 2
     0: JumpNotUndefined a0, 6 (.L0)
     3: LoadImmediate a0, 1
  .L0:
     6: JumpNotUndefined a1, 6 (.L1)
     9: Mov a1, a0
  .L1:
    12: PushLexicalScope c0
    14: NewClosure r0, c1
    17: LoadImmediate r1, 2
    20: StoreToScope r1, 0, 0
    24: LoadUndefined r1
    26: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: Ret r0
}

[BytecodeFunction: sameNameBothCaptures] {
  Parameters: 2, Registers: 2
     0: PushLexicalScope c0
     2: JumpNotUndefined a0, 6 (.L0)
     5: LoadImmediate a0, 1
  .L0:
     8: StoreToScope a0, 0, 0
    12: JumpNotUndefined a1, 6 (.L1)
    15: NewClosure a1, c1
  .L1:
    18: PushLexicalScope c2
    20: NewClosure r0, c3
    23: LoadImmediate r1, 2
    26: StoreToScope r1, 0, 0
    30: LoadUndefined r1
    32: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: y]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
}

[BytecodeFunction: y] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: Ret r0
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: Ret r0
}

[BytecodeFunction: tdzAfterParams] {
  Parameters: 1, Registers: 2
     0: JumpNotUndefined a0, 6 (.L0)
     3: LoadImmediate a0, 1
  .L0:
     6: PushLexicalScope c0
     8: LoadEmpty r1
    10: StoreToScope r1, 0, 0
    14: NewClosure r0, c1
    17: LoadImmediate r1, 2
    20: StoreToScope r1, 0, 0
    24: LoadUndefined r1
    26: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: y]
}
