[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: LoadUndefined r0
    14: Ret r0
  Constant Table:
    0: [BytecodeFunction: startScope]
    1: [String: startScope]
    2: [BytecodeFunction: captures]
    3: [String: captures]
}

[BytecodeFunction: startScope] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r0
     2: LoadEmpty r1
     4: CheckTdz r0, c0
     7: CheckTdz r1, c1
    10: Add r2, r0, r1
    14: LoadImmediate r0, 1
    17: LoadImmediate r1, 2
    20: LoadUndefined r2
    22: Ret r2
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: captures] {
  Parameters: 0, Registers: 2
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: NewClosure r0, c1
    11: LoadImmediate r1, 1
    14: StoreToScope r1, 0, 0
    18: LoadUndefined r1
    20: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}
