[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: StoreGlobal r0, c0
     6: NewClosure r0, c1
     9: StoreGlobal r0, c2
    12: LoadUndefined r0
    14: Ret r0
  Constant Table:
    0: [String: x]
    1: [BytecodeFunction: test1]
    2: [String: test1]
}

[BytecodeFunction: test1] {
  Parameters: 0, Registers: 1
     0: LoadGlobal r0, c0
     3: LoadGlobal r0, c1
     6: LoadGlobal r0, c2
     9: LoadUndefined r0
    11: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: test1]
    2: [String: unresolved]
}
