[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
     0: GlobalInit c0
     2: LoadEmpty r1
     4: StoreGlobal r1, c1
     7: LoadEmpty r1
     9: StoreGlobal r1, c2
    12: NewClosure r1, c3
    15: StoreGlobal r1, c4
    18: LoadImmediate r1, 1
    21: StoreGlobal r1, c5
    24: LoadImmediate r1, 2
    27: StoreGlobal r1, c1
    30: LoadImmediate r1, 3
    33: StoreGlobal r1, c2
    36: PushLexicalScope c6
    38: LoadEmpty r1
    40: StoreToScope r1, 0, 0
    44: LoadImmediate r1, 1
    47: StoreToScope r1, 0, 0
    51: NewClosure r0, c7
    54: PopScope 
    55: LoadUndefined r1
    57: Ret r1
  Constant Table:
    0: [GlobalNames]
    1: [String: c1]
    2: [String: l1]
    3: [BytecodeFunction: test1]
    4: [String: test1]
    5: [String: x]
    6: [ScopeNames]
    7: [BytecodeFunction: inner]
}

[BytecodeFunction: test1] {
  Parameters: 0, Registers: 1
     0: LoadGlobal r0, c0
     3: LoadGlobal r0, c1
     6: LoadGlobal r0, c2
     9: LoadUndefined r0
    11: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: test1]
    2: [String: unresolved]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: c1]
}
