[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
     0: GlobalInit c0
     2: NewClosure r1, c1
     5: StoreGlobal r1, c2
     8: LoadImmediate r1, 1
    11: StoreGlobal r1, c3
    14: LoadImmediate r1, 2
    17: StoreToScope r1, 1, 0
    21: LoadImmediate r1, 3
    24: StoreToScope r1, 2, 0
    28: PushLexicalScope c4
    30: LoadEmpty r1
    32: StoreToScope r1, 0, 0
    36: LoadImmediate r1, 1
    39: StoreToScope r1, 0, 0
    43: NewClosure r0, c5
    46: PopScope 
    47: LoadUndefined r1
    49: Ret r1
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: test1]
    2: [String: test1]
    3: [String: x]
    4: [ScopeNames]
    5: [BytecodeFunction: inner]
}

[BytecodeFunction: test1] {
  Parameters: 0, Registers: 1
     0: LoadGlobal r0, c0
     3: LoadGlobal r0, c1
     6: LoadGlobal r0, c2
     9: LoadUndefined r0
    11: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: test1]
    2: [String: unresolved]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: c1]
}
