[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: LoadUndefined r0
    20: Ret r0
  Constant Table:
    0: [BytecodeFunction: simpleBreak]
    1: [String: simpleBreak]
    2: [BytecodeFunction: nestedBreaks]
    3: [String: nestedBreaks]
    4: [BytecodeFunction: noCapturesInBreak]
    5: [String: noCapturesInBreak]
}

[BytecodeFunction: simpleBreak] {
  Parameters: 0, Registers: 2
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: NewClosure r0, c1
    11: LoadImmediate r1, 0
    14: StoreToScope r1, 0, 0
    18: LoadImmediate r1, 1
    21: JumpToBooleanFalse r1, 6 (.L0)
    24: PopScope 
    25: Jump 3 (.L1)
  .L0:
    27: PopScope 
  .L1:
    28: LoadImmediate r1, 2
    31: LoadUndefined r1
    33: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: nestedBreaks] {
  Parameters: 0, Registers: 2
      0: PushLexicalScope c0
      2: LoadEmpty r1
      4: StoreToScope r1, 0, 0
      8: LoadImmediate r1, 0
     11: StoreToScope r1, 0, 0
     15: LoadImmediate r1, 1
     18: JumpToBooleanFalse r1, 6 (.L0)
     21: PopScope 
     22: Jump 87 (.L8)
  .L0:
     24: PushLexicalScope c1
     26: LoadEmpty r1
     28: StoreToScope r1, 0, 0
     32: LoadImmediate r1, 1
     35: StoreToScope r1, 0, 0
     39: LoadImmediate r1, 1
     42: JumpToBooleanFalse r1, 7 (.L1)
     45: PopScope 
     46: PopScope 
     47: Jump 62 (.L8)
  .L1:
     49: LoadImmediate r1, 2
     52: JumpToBooleanFalse r1, 6 (.L2)
     55: PopScope 
     56: Jump 52 (.L7)
  .L2:
     58: PushLexicalScope c2
     60: LoadEmpty r1
     62: StoreToScope r1, 0, 0
     66: NewClosure r0, c3
     69: LoadImmediate r1, 2
     72: StoreToScope r1, 0, 0
     76: LoadImmediate r1, 1
     79: JumpToBooleanFalse r1, 8 (.L3)
     82: PopScope 
     83: PopScope 
     84: PopScope 
     85: Jump 24 (.L8)
  .L3:
     87: LoadImmediate r1, 2
     90: JumpToBooleanFalse r1, 7 (.L4)
     93: PopScope 
     94: PopScope 
     95: Jump 13 (.L7)
  .L4:
     97: LoadImmediate r1, 3
    100: JumpToBooleanFalse r1, 6 (.L5)
    103: PopScope 
    104: Jump 3 (.L6)
  .L5:
    106: PopScope 
  .L6:
    107: PopScope 
  .L7:
    108: PopScope 
  .L8:
    109: LoadUndefined r1
    111: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 1
    11: CheckTdz r1, c1
    14: Add r0, r0, r1
    18: LoadFromScope r1, 0, 0
    22: CheckTdz r1, c2
    25: Add r0, r0, r1
    29: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
    2: [String: z]
}

[BytecodeFunction: noCapturesInBreak] {
  Parameters: 0, Registers: 2
     0: PushFunctionScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: LoadImmediate r1, 0
    11: StoreToScope r1, 0, 0
    15: NewClosure r0, c1
    18: LoadImmediate r1, 1
    21: JumpToBooleanFalse r1, 5 (.L0)
    24: Jump 2 (.L0)
  .L0:
    26: LoadImmediate r1, 2
    29: LoadUndefined r1
    31: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}
