[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: LoadUndefined r0
    26: Ret r0
  Constant Table:
    0: [BytecodeFunction: startScope]
    1: [String: startScope]
    2: [BytecodeFunction: alwaysNeedTdzCheck]
    3: [String: alwaysNeedTdzCheck]
    4: [BytecodeFunction: captures]
    5: [String: captures]
    6: [BytecodeFunction: capturesWithBreak]
    7: [String: capturesWithBreak]
}

[BytecodeFunction: startScope] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 0
     3: LoadEmpty r0
     5: LoadEmpty r1
     7: LoadImmediate r3, 1
    10: StrictEqual r3, r2, r3
    14: JumpTrue r3, 25 (.L0)
    17: LoadImmediate r3, 2
    20: StrictEqual r3, r2, r3
    24: JumpTrue r3, 25 (.L1)
    27: LoadImmediate r3, 3
    30: StrictEqual r3, r2, r3
    34: JumpTrue r3, 17 (.L2)
    37: Jump 16 (.L3)
  .L0:
    39: CheckTdz r0, c0
    42: CheckTdz r1, c1
    45: Add r2, r0, r1
  .L1:
    49: LoadTrue r0
  .L2:
    51: LoadFalse r1
  .L3:
    53: LoadUndefined r2
    55: Ret r2
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: alwaysNeedTdzCheck] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 0
     3: LoadEmpty r1
     5: LoadImmediate r3, 1
     8: StrictEqual r3, r2, r3
    12: JumpTrue r3, 15 (.L0)
    15: LoadImmediate r3, 2
    18: StrictEqual r3, r2, r3
    22: JumpTrue r3, 10 (.L1)
    25: Jump 10 (.L2)
  .L0:
    27: LoadTrue r1
    29: CheckTdz r1, c0
  .L1:
    32: CheckTdz r1, c0
  .L2:
    35: LoadImmediate r2, 3
    38: LoadImmediate r3, 1
    41: StrictEqual r3, r2, r3
    45: JumpTrue r3, 5 (.L3)
    48: Jump 4 (.L4)
  .L3:
    50: LoadTrue r0
  .L4:
    52: LoadUndefined r2
    54: Ret r2
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: captures] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 0
     3: PushLexicalScope c0
     5: LoadEmpty r3
     7: StoreToScope r3, 0, 0
    11: NewClosure r0, c1
    14: LoadImmediate r3, 1
    17: StrictEqual r3, r2, r3
    21: JumpTrue r3, 25 (.L0)
    24: LoadImmediate r3, 2
    27: StrictEqual r3, r2, r3
    31: JumpTrue r3, 22 (.L1)
    34: LoadImmediate r3, 3
    37: StrictEqual r3, r2, r3
    41: JumpTrue r3, 12 (.L1)
    44: Jump 28 (.L2)
  .L0:
    46: LoadImmediate r2, 1
    49: StoreToScope r2, 0, 0
  .L1:
    53: PushLexicalScope c2
    55: LoadEmpty r2
    57: StoreToScope r2, 0, 0
    61: NewClosure r1, c3
    64: LoadImmediate r2, 1
    67: StoreToScope r2, 0, 0
    71: PopScope 
  .L2:
    72: PopScope 
    73: LoadUndefined r2
    75: Ret r2
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner1]
    2: [ScopeNames]
    3: [BytecodeFunction: inner2]
}

[BytecodeFunction: inner1] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: inner2] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 1
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 0
    11: CheckTdz r1, c1
    14: Add r0, r0, r1
    18: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: capturesWithBreak] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r1, 1
     3: PushLexicalScope c0
     5: LoadEmpty r2
     7: StoreToScope r2, 0, 0
    11: NewClosure r0, c1
    14: LoadImmediate r2, 1
    17: StrictEqual r2, r1, r2
    21: JumpTrue r2, 5 (.L0)
    24: Jump 12 (.L1)
  .L0:
    26: LoadImmediate r1, 1
    29: StoreToScope r1, 0, 0
    33: PopScope 
    34: Jump 3 (.L2)
  .L1:
    36: PopScope 
  .L2:
    37: LoadImmediate r1, 2
    40: LoadUndefined r1
    42: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: captures]
}

[BytecodeFunction: captures] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: LoadUndefined r0
    9: Ret r0
  Constant Table:
    0: [String: x]
}
