[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: StoreGlobal r0, c1
    6: LoadUndefined r0
    8: Ret r0
  Constant Table:
    0: [BytecodeFunction: startScope]
    1: [String: startScope]
}

[BytecodeFunction: startScope] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 0
     3: LoadEmpty r0
     5: LoadEmpty r1
     7: LoadImmediate r3, 1
    10: StrictEqual r3, r2, r3
    14: JumpTrue r3, 25 (.L0)
    17: LoadImmediate r3, 2
    20: StrictEqual r3, r2, r3
    24: JumpTrue r3, 25 (.L1)
    27: LoadImmediate r3, 3
    30: StrictEqual r3, r2, r3
    34: JumpTrue r3, 17 (.L2)
    37: Jump 16 (.L3)
  .L0:
    39: CheckTdz r0, c0
    42: CheckTdz r1, c1
    45: Add r2, r0, r1
  .L1:
    49: LoadTrue r0
  .L2:
    51: LoadFalse r1
  .L3:
    53: LoadUndefined r2
    55: Ret r2
  Constant Table:
    0: [String: x]
    1: [String: y]
}
