[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: LoadUndefined r0
    14: Ret r0
  Constant Table:
    0: [BytecodeFunction: startScope]
    1: [String: startScope]
    2: [BytecodeFunction: alwaysNeedTdzCheck]
    3: [String: alwaysNeedTdzCheck]
}

[BytecodeFunction: startScope] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 0
     3: LoadEmpty r0
     5: LoadEmpty r1
     7: LoadImmediate r3, 1
    10: StrictEqual r3, r2, r3
    14: JumpTrue r3, 25 (.L0)
    17: LoadImmediate r3, 2
    20: StrictEqual r3, r2, r3
    24: JumpTrue r3, 25 (.L1)
    27: LoadImmediate r3, 3
    30: StrictEqual r3, r2, r3
    34: JumpTrue r3, 17 (.L2)
    37: Jump 16 (.L3)
  .L0:
    39: CheckTdz r0, c0
    42: CheckTdz r1, c1
    45: Add r2, r0, r1
  .L1:
    49: LoadTrue r0
  .L2:
    51: LoadFalse r1
  .L3:
    53: LoadUndefined r2
    55: Ret r2
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: alwaysNeedTdzCheck] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 0
     3: LoadEmpty r1
     5: LoadImmediate r3, 1
     8: StrictEqual r3, r2, r3
    12: JumpTrue r3, 15 (.L0)
    15: LoadImmediate r3, 2
    18: StrictEqual r3, r2, r3
    22: JumpTrue r3, 10 (.L1)
    25: Jump 10 (.L2)
  .L0:
    27: LoadTrue r1
    29: CheckTdz r1, c0
  .L1:
    32: CheckTdz r1, c0
  .L2:
    35: LoadImmediate r2, 3
    38: LoadImmediate r3, 1
    41: StrictEqual r3, r2, r3
    45: JumpTrue r3, 5 (.L3)
    48: Jump 4 (.L4)
  .L3:
    50: LoadTrue r0
  .L4:
    52: LoadUndefined r2
    54: Ret r2
  Constant Table:
    0: [String: x]
}
