[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: LoadUndefined r0
    22: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: startScope]
    2: [String: startScope]
    3: [BytecodeFunction: dynamicAccessInChildren]
    4: [String: dynamicAccessInChildren]
    5: [BytecodeFunction: forcesParentsToBeCaptured]
    6: [String: forcesParentsToBeCaptured]
}

[BytecodeFunction: startScope] {
  Parameters: 1, Registers: 2
     0: PushFunctionScope c0
     2: StoreToScope <this>, 1, 0
     6: StoreToScope a0, 0, 0
    10: NewMappedArguments r1
    12: StoreToScope r1, 2, 0
    16: LoadFromScope r1, 0, 0
    20: PushWithScope r1, c1
    23: PushLexicalScope c2
    25: LoadEmpty r1
    27: StoreToScope r1, 0, 0
    31: LoadEmpty r1
    33: StoreToScope r1, 1, 0
    37: LoadImmediate r1, 1
    40: StoreToScope r1, 0, 0
    44: LoadImmediate r1, 2
    47: StoreToScope r1, 1, 0
    51: NewClosure r0, c3
    54: PopScope 
    55: PopScope 
    56: LoadUndefined r1
    58: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 0
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 1, 0
    11: CheckTdz r1, c1
    14: Add r0, r0, r1
    18: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: dynamicAccessInChildren] {
  Parameters: 1, Registers: 3
     0: PushFunctionScope c0
     2: StoreToScope <this>, 1, 0
     6: StoreToScope a0, 0, 0
    10: NewMappedArguments r1
    12: StoreToScope r1, 3, 0
    16: LoadImmediate r1, 1
    19: StoreToScope r1, 2, 0
    23: LoadFromScope r1, 0, 0
    27: PushWithScope r1, c1
    30: LoadDynamic r1, c2
    33: LoadImmediate r2, 2
    36: Add r1, r1, r2
    40: LoadImmediate r1, 0
    43: StoreDynamic r1, c2
    46: LoadImmediate r0, 3
    49: LoadImmediate r1, 4
    52: Add r1, r0, r1
    56: LoadDynamic r1, c3
    59: LoadImmediate r2, 5
    62: Add r1, r1, r2
    66: LoadImmediate r1, 6
    69: Add r1, r0, r1
    73: LoadDynamic r1, c3
    76: LoadImmediate r2, 7
    79: Add r1, r1, r2
    83: PopScope 
    84: LoadUndefined r1
    86: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [String: outside]
    3: [String: unresolved]
}

[BytecodeFunction: forcesParentsToBeCaptured] {
  Parameters: 2, Registers: 1
     0: PushFunctionScope c0
     2: StoreToScope <this>, 2, 0
     6: StoreToScope a0, 0, 0
    10: StoreToScope a1, 1, 0
    14: NewMappedArguments r0
    16: StoreToScope r0, 4, 0
    20: LoadImmediate r0, 1
    23: StoreToScope r0, 3, 0
    27: LoadFromScope r0, 4, 0
    31: LoadFromScope r0, 0, 0
    35: PushWithScope r0, c1
    38: PopScope 
    39: LoadUndefined r0
    41: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
}
