[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: LoadUndefined r0
    20: Ret r0
  Constant Table:
    0: [BytecodeFunction: startScope]
    1: [String: startScope]
    2: [BytecodeFunction: dynamicAccessInChildren]
    3: [String: dynamicAccessInChildren]
    4: [BytecodeFunction: forcesParentsToBeCaptured]
    5: [String: forcesParentsToBeCaptured]
}

[BytecodeFunction: startScope] {
  Parameters: 1, Registers: 2
     0: PushFunctionScope c0
     2: StoreToScope <this>, 1, 0
     6: StoreToScope r1, 3, 0
    10: StoreToScope a0, 0, 0
    14: NewMappedArguments r1
    16: StoreToScope r1, 2, 0
    20: LoadFromScope r1, 0, 0
    24: PushWithScope r1, c1
    27: PushLexicalScope c2
    29: LoadEmpty r1
    31: StoreToScope r1, 0, 0
    35: LoadEmpty r1
    37: StoreToScope r1, 1, 0
    41: NewClosure r0, c3
    44: LoadImmediate r1, 1
    47: StoreToScope r1, 0, 0
    51: LoadImmediate r1, 2
    54: StoreToScope r1, 1, 0
    58: PopScope 
    59: PopScope 
    60: LoadUndefined r1
    62: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 0
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 1, 0
    11: CheckTdz r1, c1
    14: Add r0, r0, r1
    18: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: dynamicAccessInChildren] {
  Parameters: 1, Registers: 3
     0: PushFunctionScope c0
     2: StoreToScope <this>, 1, 0
     6: StoreToScope r1, 4, 0
    10: StoreToScope a0, 0, 0
    14: NewMappedArguments r1
    16: StoreToScope r1, 3, 0
    20: LoadImmediate r1, 1
    23: StoreToScope r1, 2, 0
    27: LoadFromScope r1, 0, 0
    31: PushWithScope r1, c1
    34: LoadDynamic r1, c2
    37: LoadImmediate r2, 2
    40: Add r1, r1, r2
    44: LoadImmediate r1, 0
    47: StoreDynamic r1, c2
    50: LoadImmediate r0, 3
    53: LoadImmediate r1, 4
    56: Add r1, r0, r1
    60: LoadDynamic r1, c3
    63: LoadImmediate r2, 5
    66: Add r1, r1, r2
    70: LoadImmediate r1, 6
    73: Add r1, r0, r1
    77: LoadDynamic r1, c3
    80: LoadImmediate r2, 7
    83: Add r1, r1, r2
    87: PopScope 
    88: LoadUndefined r1
    90: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [String: outside]
    3: [String: unresolved]
}

[BytecodeFunction: forcesParentsToBeCaptured] {
  Parameters: 2, Registers: 1
     0: PushFunctionScope c0
     2: StoreToScope <this>, 2, 0
     6: StoreToScope r0, 5, 0
    10: StoreToScope a0, 0, 0
    14: StoreToScope a1, 1, 0
    18: NewMappedArguments r0
    20: StoreToScope r0, 4, 0
    24: LoadImmediate r0, 1
    27: StoreToScope r0, 3, 0
    31: LoadFromScope r0, 4, 0
    35: LoadFromScope r0, 0, 0
    39: PushWithScope r0, c1
    42: PopScope 
    43: LoadUndefined r0
    45: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
}
