[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 6
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: LoadImmediate r0, 1
    15: LoadConstant r1, c4
    18: GetNamedProperty r4, r0, c4, k0
    23: StoreGlobal r4, c4
    26: LoadConstant r2, c5
    29: GetNamedProperty r4, r0, c5, k1
    34: StoreGlobal r4, c6
    37: LoadImmediate r5, 2
    40: ToPropertyKey r3, r5
    43: GetProperty r4, r0, r3
    47: StoreGlobal r4, c7
    50: ToObject r5, r0
    53: NewObject r4
    55: CopyDataProperties r4, r0, r1, 3
    60: StoreGlobal r4, c8
    63: PushLexicalScope c9
    65: NewObject r0
    67: StoreToScope r0, 0, 0
    71: NewClosure r1, c11
    74: DefineNamedProperty r0, c10, r1
    78: PopScope 
    79: LoadUndefined r0
    81: Ret r0
  Constant Table:
    0: [BytecodeFunction: constants]
    1: [String: constants]
    2: [BytecodeFunction: nestedMember]
    3: [String: nestedMember]
    4: [String: v1]
    5: [String: z]
    6: [String: v2]
    7: [String: v3]
    8: [String: v4]
    9: [ScopeNames]
    10: [String: superMember]
    11: [BytecodeFunction: superMember]
}

[BytecodeFunction: constants] {
  Parameters: 0, Registers: 9
     0: LoadImmediate r4, 1
     3: LoadConstant r5, c0
     6: GetNamedProperty r0, r4, c0, k0
    11: LoadConstant r6, c1
    14: GetNamedProperty r1, r4, c1, k1
    19: LoadImmediate r8, 2
    22: ToPropertyKey r7, r8
    25: GetProperty r2, r4, r7
    29: ToObject r8, r4
    32: NewObject r3
    34: CopyDataProperties r3, r4, r5, 3
    39: LoadUndefined r4
    41: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: z]
}

[BytecodeFunction: nestedMember] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: GetNamedProperty r1, r0, c1, k0
     8: SetNamedProperty a0, c0, r1
    12: LoadUndefined r0
    14: Ret r0
  Constant Table:
    0: [String: b]
    1: [String: a]
}

[BytecodeFunction: superMember] {
  Parameters: 1, Registers: 4
     0: LoadImmediate r0, 1
     3: LoadFromScope r2, 0, 0
     7: LoadConstant r3, c0
    10: GetNamedProperty r1, r0, c1, k0
    15: SetSuperProperty r2, <this>, r3, r1
    20: LoadUndefined r0
    22: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: a]
}
