[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 6
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: LoadImmediate r0, 1
    15: LoadConstant r1, c4
    18: GetNamedProperty r4, r0, c4
    22: StoreGlobal r4, c4
    25: LoadConstant r2, c5
    28: GetNamedProperty r4, r0, c5
    32: StoreGlobal r4, c6
    35: LoadImmediate r5, 2
    38: ToPropertyKey r3, r5
    41: GetProperty r4, r0, r5
    45: StoreGlobal r4, c7
    48: ToObject r5, r0
    51: NewObject r4
    53: CopyDataProperties r4, r0, r1, 3
    58: StoreGlobal r4, c8
    61: PushLexicalScope c9
    63: NewObject r0
    65: StoreToScope r0, 0, 0
    69: NewClosure r1, c11
    72: DefineNamedProperty r0, c10, r1
    76: PopScope 
    77: LoadUndefined r0
    79: Ret r0
  Constant Table:
    0: [BytecodeFunction: constants]
    1: [String: constants]
    2: [BytecodeFunction: nestedMember]
    3: [String: nestedMember]
    4: [String: v1]
    5: [String: z]
    6: [String: v2]
    7: [String: v3]
    8: [String: v4]
    9: [ScopeNames]
    10: [String: superMember]
    11: [BytecodeFunction: superMember]
}

[BytecodeFunction: constants] {
  Parameters: 0, Registers: 9
     0: LoadImmediate r4, 1
     3: LoadConstant r5, c0
     6: GetNamedProperty r0, r4, c0
    10: LoadConstant r6, c1
    13: GetNamedProperty r1, r4, c1
    17: LoadImmediate r8, 2
    20: ToPropertyKey r7, r8
    23: GetProperty r2, r4, r8
    27: ToObject r8, r4
    30: NewObject r3
    32: CopyDataProperties r3, r4, r5, 3
    37: LoadUndefined r4
    39: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: z]
}

[BytecodeFunction: nestedMember] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: GetNamedProperty r1, r0, c1
     7: SetNamedProperty a0, c0, r1
    11: LoadUndefined r0
    13: Ret r0
  Constant Table:
    0: [String: b]
    1: [String: a]
}

[BytecodeFunction: superMember] {
  Parameters: 1, Registers: 4
     0: LoadImmediate r0, 1
     3: LoadFromScope r2, 0, 0
     7: LoadConstant r3, c0
    10: GetNamedProperty r1, r0, c1
    14: SetSuperProperty r2, <this>, r3, r1
    19: LoadUndefined r0
    21: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: a]
}
