[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
      0: NewClosure r0, c0
      3: StoreGlobal r0, c1, k0
      7: NewClosure r0, c2
     10: StoreGlobal r0, c3, k1
     14: NewClosure r0, c4
     17: StoreGlobal r0, c5, k2
     21: NewClosure r0, c6
     24: StoreGlobal r0, c7, k3
     28: NewClosure r0, c8
     31: StoreGlobal r0, c9, k4
     35: NewClosure r0, c10
     38: StoreGlobal r0, c11, k5
     42: NewClosure r0, c12
     45: StoreGlobal r0, c13, k6
     49: NewClosure r0, c14
     52: StoreGlobal r0, c15, k7
     56: NewClosure r0, c16
     59: StoreGlobal r0, c17, k8
     63: NewClosure r0, c18
     66: StoreGlobal r0, c19, k9
     70: NewClosure r0, c20
     73: StoreGlobal r0, c21, k10
     77: NewClosure r0, c22
     80: StoreGlobal r0, c23, k11
     84: NewClosure r0, c24
     87: StoreGlobal r0, c25, k12
     91: NewGenerator r0, c26
     94: StoreGlobal r0, c27, k13
     98: LoadUndefined r0
    100: Ret r0
  Constant Table:
    0: [BytecodeFunction: empty]
    1: [String: empty]
    2: [BytecodeFunction: single]
    3: [String: single]
    4: [BytecodeFunction: multiple]
    5: [String: multiple]
    6: [BytecodeFunction: singleHole]
    7: [String: singleHole]
    8: [BytecodeFunction: multipleHoles]
    9: [String: multipleHoles]
    10: [BytecodeFunction: mixedHolesAndValues1]
    11: [String: mixedHolesAndValues1]
    12: [BytecodeFunction: mixedHolesAndValues2]
    13: [String: mixedHolesAndValues2]
    14: [BytecodeFunction: destructuring]
    15: [String: destructuring]
    16: [BytecodeFunction: onlyRest]
    17: [String: onlyRest]
    18: [BytecodeFunction: valuesAndRest]
    19: [String: valuesAndRest]
    20: [BytecodeFunction: restDestructuring]
    21: [String: restDestructuring]
    22: [BytecodeFunction: elementEvaluationOrder]
    23: [String: elementEvaluationOrder]
    24: [BytecodeFunction: restEvaluationOrder]
    25: [String: restEvaluationOrder]
    26: [BytecodeFunction: withYield]
    27: [String: withYield]
}

[BytecodeFunction: empty] {
  Parameters: 1, Registers: 7
     0: Mov r4, <scope>
     3: GetIterator r0, r5, a0
     7: IteratorClose r0
     9: LoadUndefined r0
    11: Ret r0
}

[BytecodeFunction: single] {
  Parameters: 1, Registers: 8
     0: Mov r5, <scope>
     3: GetIterator r1, r6, a0
     7: IteratorNext r7, r2, r1, r6
    12: JumpFalse r2, 5 (.L0)
    15: LoadUndefined r7
  .L0:
    17: Mov r0, r7
    20: JumpTrue r2, 50 (.L5)
    23: LoadImmediate r3, 1
    26: Jump 5 (.L1)
    28: LoadImmediate r3, 0
  .L1:
    31: Mov <scope>, r5
    34: JumpTrue r2, 22 (.L3)
    37: IteratorClose r1
    39: Jump 17 (.L3)
    41: LoadImmediate r6, 0
    44: StrictNotEqual r6, r6, r3
    48: JumpTrue r6, 6 (.L2)
    51: Mov r5, r4
  .L2:
    54: Rethrow r5
  .L3:
    56: LoadImmediate r5, 0
    59: StrictEqual r5, r3, r5
    63: JumpFalse r5, 5 (.L4)
    66: Rethrow r4
  .L4:
    68: Jump 2 (.L5)
  .L5:
    70: LoadUndefined r1
    72: Ret r1
  Exception Handlers:
    17-20 -> 28 (r4)
    37-39 -> 41 (r5)
}

[BytecodeFunction: multiple] {
  Parameters: 1, Registers: 10
      0: Mov r7, <scope>
      3: GetIterator r3, r8, a0
      7: IteratorNext r9, r4, r3, r8
     12: JumpFalse r4, 5 (.L0)
     15: LoadUndefined r9
  .L0:
     17: Mov r0, r9
     20: JumpTrue r4, 11 (.L1)
     23: IteratorNext r9, r4, r3, r8
     28: JumpFalse r4, 5 (.L2)
  .L1:
     31: LoadUndefined r9
  .L2:
     33: Mov r1, r9
     36: JumpTrue r4, 11 (.L3)
     39: IteratorNext r9, r4, r3, r8
     44: JumpFalse r4, 5 (.L4)
  .L3:
     47: LoadUndefined r9
  .L4:
     49: Mov r2, r9
     52: JumpTrue r4, 50 (.L9)
     55: LoadImmediate r5, 1
     58: Jump 5 (.L5)
     60: LoadImmediate r5, 0
  .L5:
     63: Mov <scope>, r7
     66: JumpTrue r4, 22 (.L7)
     69: IteratorClose r3
     71: Jump 17 (.L7)
     73: LoadImmediate r8, 0
     76: StrictNotEqual r8, r8, r5
     80: JumpTrue r8, 6 (.L6)
     83: Mov r7, r6
  .L6:
     86: Rethrow r7
  .L7:
     88: LoadImmediate r7, 0
     91: StrictEqual r7, r5, r7
     95: JumpFalse r7, 5 (.L8)
     98: Rethrow r6
  .L8:
    100: Jump 2 (.L9)
  .L9:
    102: LoadUndefined r3
    104: Ret r3
  Exception Handlers:
    17-20 -> 60 (r6)
    33-36 -> 60 (r6)
    49-52 -> 60 (r6)
    69-71 -> 73 (r7)
}

[BytecodeFunction: singleHole] {
  Parameters: 1, Registers: 7
     0: Mov r4, <scope>
     3: GetIterator r0, r5, a0
     7: IteratorNext r6, r1, r0, r5
    12: JumpTrue r1, 5 (.L0)
    15: IteratorClose r0
  .L0:
    17: LoadUndefined r0
    19: Ret r0
}

[BytecodeFunction: multipleHoles] {
  Parameters: 1, Registers: 7
     0: Mov r4, <scope>
     3: GetIterator r0, r5, a0
     7: IteratorNext r6, r1, r0, r5
    12: JumpTrue r1, 8 (.L0)
    15: IteratorNext r6, r1, r0, r5
  .L0:
    20: JumpTrue r1, 8 (.L1)
    23: IteratorNext r6, r1, r0, r5
  .L1:
    28: JumpTrue r1, 5 (.L2)
    31: IteratorClose r0
  .L2:
    33: LoadUndefined r0
    35: Ret r0
}

[BytecodeFunction: mixedHolesAndValues1] {
  Parameters: 1, Registers: 9
     0: Mov r6, <scope>
     3: GetIterator r2, r7, a0
     7: IteratorNext r8, r3, r2, r7
    12: JumpFalse r3, 5 (.L0)
    15: LoadUndefined r8
  .L0:
    17: Mov r0, r8
    20: JumpTrue r3, 8 (.L1)
    23: IteratorNext r8, r3, r2, r7
  .L1:
    28: JumpTrue r3, 11 (.L2)
    31: IteratorNext r8, r3, r2, r7
    36: JumpFalse r3, 5 (.L3)
  .L2:
    39: LoadUndefined r8
  .L3:
    41: Mov r1, r8
    44: JumpTrue r3, 50 (.L8)
    47: LoadImmediate r4, 1
    50: Jump 5 (.L4)
    52: LoadImmediate r4, 0
  .L4:
    55: Mov <scope>, r6
    58: JumpTrue r3, 22 (.L6)
    61: IteratorClose r2
    63: Jump 17 (.L6)
    65: LoadImmediate r7, 0
    68: StrictNotEqual r7, r7, r4
    72: JumpTrue r7, 6 (.L5)
    75: Mov r6, r5
  .L5:
    78: Rethrow r6
  .L6:
    80: LoadImmediate r6, 0
    83: StrictEqual r6, r4, r6
    87: JumpFalse r6, 5 (.L7)
    90: Rethrow r5
  .L7:
    92: Jump 2 (.L8)
  .L8:
    94: LoadUndefined r2
    96: Ret r2
  Exception Handlers:
    17-20 -> 52 (r5)
    41-44 -> 52 (r5)
    61-63 -> 65 (r6)
}

[BytecodeFunction: mixedHolesAndValues2] {
  Parameters: 1, Registers: 8
     0: Mov r5, <scope>
     3: GetIterator r1, r6, a0
     7: IteratorNext r7, r2, r1, r6
    12: JumpTrue r2, 11 (.L0)
    15: IteratorNext r7, r2, r1, r6
    20: JumpFalse r2, 5 (.L1)
  .L0:
    23: LoadUndefined r7
  .L1:
    25: Mov r0, r7
    28: JumpTrue r2, 8 (.L2)
    31: IteratorNext r7, r2, r1, r6
  .L2:
    36: JumpTrue r2, 50 (.L7)
    39: LoadImmediate r3, 1
    42: Jump 5 (.L3)
    44: LoadImmediate r3, 0
  .L3:
    47: Mov <scope>, r5
    50: JumpTrue r2, 22 (.L5)
    53: IteratorClose r1
    55: Jump 17 (.L5)
    57: LoadImmediate r6, 0
    60: StrictNotEqual r6, r6, r3
    64: JumpTrue r6, 6 (.L4)
    67: Mov r5, r4
  .L4:
    70: Rethrow r5
  .L5:
    72: LoadImmediate r5, 0
    75: StrictEqual r5, r3, r5
    79: JumpFalse r5, 5 (.L6)
    82: Rethrow r4
  .L6:
    84: Jump 2 (.L7)
  .L7:
    86: LoadUndefined r1
    88: Ret r1
  Exception Handlers:
    25-28 -> 44 (r4)
    53-55 -> 57 (r5)
}

[BytecodeFunction: destructuring] {
  Parameters: 1, Registers: 9
     0: Mov r6, <scope>
     3: GetIterator r2, r7, a0
     7: IteratorNext r8, r3, r2, r7
    12: JumpFalse r3, 5 (.L0)
    15: LoadUndefined r8
  .L0:
    17: JumpNotUndefined r8, 6 (.L1)
    20: LoadImmediate r8, 1
  .L1:
    23: Mov r0, r8
    26: JumpTrue r3, 11 (.L2)
    29: IteratorNext r8, r3, r2, r7
    34: JumpFalse r3, 5 (.L3)
  .L2:
    37: LoadUndefined r8
  .L3:
    39: GetNamedProperty r1, r8, c0, k0
    44: JumpTrue r3, 50 (.L8)
    47: LoadImmediate r4, 1
    50: Jump 5 (.L4)
    52: LoadImmediate r4, 0
  .L4:
    55: Mov <scope>, r6
    58: JumpTrue r3, 22 (.L6)
    61: IteratorClose r2
    63: Jump 17 (.L6)
    65: LoadImmediate r7, 0
    68: StrictNotEqual r7, r7, r4
    72: JumpTrue r7, 6 (.L5)
    75: Mov r6, r5
  .L5:
    78: Rethrow r6
  .L6:
    80: LoadImmediate r6, 0
    83: StrictEqual r6, r4, r6
    87: JumpFalse r6, 5 (.L7)
    90: Rethrow r5
  .L7:
    92: Jump 2 (.L8)
  .L8:
    94: LoadUndefined r2
    96: Ret r2
  Constant Table:
    0: [String: b]
  Exception Handlers:
    17-26 -> 52 (r5)
    39-44 -> 52 (r5)
    61-63 -> 65 (r6)
}

[BytecodeFunction: onlyRest] {
  Parameters: 1, Registers: 10
     0: Mov r5, <scope>
     3: GetIterator r1, r6, a0
     7: NewArray r8
     9: LoadImmediate r9, 0
  .L0:
    12: IteratorNext r7, r2, r1, r6
    17: JumpTrue r2, 11 (.L1)
    20: SetArrayProperty r8, r9, r7
    24: Inc r9
    26: Jump -14 (.L0)
  .L1:
    28: Mov r0, r8
    31: JumpTrue r2, 50 (.L6)
    34: LoadImmediate r3, 1
    37: Jump 5 (.L2)
    39: LoadImmediate r3, 0
  .L2:
    42: Mov <scope>, r5
    45: JumpTrue r2, 22 (.L4)
    48: IteratorClose r1
    50: Jump 17 (.L4)
    52: LoadImmediate r6, 0
    55: StrictNotEqual r6, r6, r3
    59: JumpTrue r6, 6 (.L3)
    62: Mov r5, r4
  .L3:
    65: Rethrow r5
  .L4:
    67: LoadImmediate r5, 0
    70: StrictEqual r5, r3, r5
    74: JumpFalse r5, 5 (.L5)
    77: Rethrow r4
  .L5:
    79: Jump 2 (.L6)
  .L6:
    81: LoadUndefined r1
    83: Ret r1
  Exception Handlers:
    28-31 -> 39 (r4)
    48-50 -> 52 (r5)
}

[BytecodeFunction: valuesAndRest] {
  Parameters: 1, Registers: 12
      0: Mov r7, <scope>
      3: GetIterator r3, r8, a0
      7: IteratorNext r9, r4, r3, r8
     12: JumpFalse r4, 5 (.L0)
     15: LoadUndefined r9
  .L0:
     17: Mov r0, r9
     20: JumpTrue r4, 11 (.L1)
     23: IteratorNext r9, r4, r3, r8
     28: JumpFalse r4, 5 (.L2)
  .L1:
     31: LoadUndefined r9
  .L2:
     33: Mov r1, r9
     36: NewArray r10
     38: LoadImmediate r11, 0
     41: JumpTrue r4, 19 (.L4)
  .L3:
     44: IteratorNext r9, r4, r3, r8
     49: JumpTrue r4, 11 (.L4)
     52: SetArrayProperty r10, r11, r9
     56: Inc r11
     58: Jump -14 (.L3)
  .L4:
     60: Mov r2, r10
     63: JumpTrue r4, 50 (.L9)
     66: LoadImmediate r5, 1
     69: Jump 5 (.L5)
     71: LoadImmediate r5, 0
  .L5:
     74: Mov <scope>, r7
     77: JumpTrue r4, 22 (.L7)
     80: IteratorClose r3
     82: Jump 17 (.L7)
     84: LoadImmediate r8, 0
     87: StrictNotEqual r8, r8, r5
     91: JumpTrue r8, 6 (.L6)
     94: Mov r7, r6
  .L6:
     97: Rethrow r7
  .L7:
     99: LoadImmediate r7, 0
    102: StrictEqual r7, r5, r7
    106: JumpFalse r7, 5 (.L8)
    109: Rethrow r6
  .L8:
    111: Jump 2 (.L9)
  .L9:
    113: LoadUndefined r3
    115: Ret r3
  Exception Handlers:
    17-20 -> 71 (r6)
    33-36 -> 71 (r6)
    60-63 -> 71 (r6)
    80-82 -> 84 (r7)
}

[BytecodeFunction: restDestructuring] {
  Parameters: 1, Registers: 10
     0: Mov r5, <scope>
     3: GetIterator r1, r6, a0
     7: NewArray r8
     9: LoadImmediate r9, 0
  .L0:
    12: IteratorNext r7, r2, r1, r6
    17: JumpTrue r2, 11 (.L1)
    20: SetArrayProperty r8, r9, r7
    24: Inc r9
    26: Jump -14 (.L0)
  .L1:
    28: GetNamedProperty r0, r8, c0, k0
    33: JumpTrue r2, 50 (.L6)
    36: LoadImmediate r3, 1
    39: Jump 5 (.L2)
    41: LoadImmediate r3, 0
  .L2:
    44: Mov <scope>, r5
    47: JumpTrue r2, 22 (.L4)
    50: IteratorClose r1
    52: Jump 17 (.L4)
    54: LoadImmediate r6, 0
    57: StrictNotEqual r6, r6, r3
    61: JumpTrue r6, 6 (.L3)
    64: Mov r5, r4
  .L3:
    67: Rethrow r5
  .L4:
    69: LoadImmediate r5, 0
    72: StrictEqual r5, r3, r5
    76: JumpFalse r5, 5 (.L5)
    79: Rethrow r4
  .L5:
    81: Jump 2 (.L6)
  .L6:
    83: LoadUndefined r1
    85: Ret r1
  Constant Table:
    0: [String: b]
  Exception Handlers:
    28-33 -> 41 (r4)
    50-52 -> 54 (r5)
}

[BytecodeFunction: elementEvaluationOrder] {
  Parameters: 0, Registers: 10
      0: LoadGlobal r0, c0, k0
      4: Call r0, r0, r0, 0
      9: Mov r5, <scope>
     12: GetIterator r1, r6, r0
     16: LoadGlobal r8, c1, k1
     20: Call r8, r8, r8, 0
     25: LoadGlobal r9, c2, k2
     29: Call r9, r9, r9, 0
     34: IteratorNext r7, r2, r1, r6
     39: JumpFalse r2, 5 (.L0)
     42: LoadUndefined r7
  .L0:
     44: SetProperty r8, r9, r7
     48: JumpTrue r2, 50 (.L5)
     51: LoadImmediate r3, 1
     54: Jump 5 (.L1)
     56: LoadImmediate r3, 0
  .L1:
     59: Mov <scope>, r5
     62: JumpTrue r2, 22 (.L3)
     65: IteratorClose r1
     67: Jump 17 (.L3)
     69: LoadImmediate r6, 0
     72: StrictNotEqual r6, r6, r3
     76: JumpTrue r6, 6 (.L2)
     79: Mov r5, r4
  .L2:
     82: Rethrow r5
  .L3:
     84: LoadImmediate r5, 0
     87: StrictEqual r5, r3, r5
     91: JumpFalse r5, 5 (.L4)
     94: Rethrow r4
  .L4:
     96: Jump 2 (.L5)
  .L5:
     98: LoadUndefined r0
    100: Ret r0
  Constant Table:
    0: [String: c]
    1: [String: a]
    2: [String: b]
  Exception Handlers:
    16-34 -> 56 (r4)
    44-48 -> 56 (r4)
    65-67 -> 69 (r5)
}

[BytecodeFunction: restEvaluationOrder] {
  Parameters: 0, Registers: 12
      0: LoadGlobal r0, c0, k0
      4: Call r0, r0, r0, 0
      9: Mov r5, <scope>
     12: GetIterator r1, r6, r0
     16: NewArray r8
     18: LoadGlobal r9, c1, k1
     22: Call r9, r9, r9, 0
     27: LoadGlobal r10, c2, k2
     31: Call r10, r10, r10, 0
     36: LoadImmediate r11, 0
  .L0:
     39: IteratorNext r7, r2, r1, r6
     44: JumpTrue r2, 11 (.L1)
     47: SetArrayProperty r8, r11, r7
     51: Inc r11
     53: Jump -14 (.L0)
  .L1:
     55: SetProperty r9, r10, r8
     59: JumpTrue r2, 50 (.L6)
     62: LoadImmediate r3, 1
     65: Jump 5 (.L2)
     67: LoadImmediate r3, 0
  .L2:
     70: Mov <scope>, r5
     73: JumpTrue r2, 22 (.L4)
     76: IteratorClose r1
     78: Jump 17 (.L4)
     80: LoadImmediate r6, 0
     83: StrictNotEqual r6, r6, r3
     87: JumpTrue r6, 6 (.L3)
     90: Mov r5, r4
  .L3:
     93: Rethrow r5
  .L4:
     95: LoadImmediate r5, 0
     98: StrictEqual r5, r3, r5
    102: JumpFalse r5, 5 (.L5)
    105: Rethrow r4
  .L5:
    107: Jump 2 (.L6)
  .L6:
    109: LoadUndefined r0
    111: Ret r0
  Constant Table:
    0: [String: c]
    1: [String: a]
    2: [String: b]
  Exception Handlers:
    18-36 -> 67 (r4)
    55-59 -> 67 (r4)
    76-78 -> 80 (r5)
}

[BytecodeFunction: withYield] {
  Parameters: 1, Registers: 11
      0: GeneratorStart r1
      2: Mov r6, <scope>
      5: GetIterator r2, r7, a0
      9: IteratorNext r8, r3, r2, r7
     14: JumpFalse r3, 5 (.L0)
     17: LoadUndefined r8
  .L0:
     19: JumpNotUndefined r8, 40 (.L2)
     22: LoadUndefined r9
     24: NewObject r10
     26: SetNamedProperty r10, c0, r9, k0
     31: LoadFalse r9
     33: SetNamedProperty r10, c1, r9, k1
     38: Yield r8, r9, r1, r10
     43: JumpNotNullish r9, 16 (.L2)
     46: JumpNotUndefined r9, 11 (.L1)
     49: LoadImmediate r4, 1
     52: Mov r5, r8
     55: Jump 18 (.L3)
  .L1:
     57: Throw r8
  .L2:
     59: Mov r0, r8
     62: JumpTrue r3, 62 (.L8)
     65: LoadImmediate r4, 2
     68: Jump 5 (.L3)
     70: LoadImmediate r4, 0
  .L3:
     73: Mov <scope>, r6
     76: JumpTrue r3, 22 (.L5)
     79: IteratorClose r2
     81: Jump 17 (.L5)
     83: LoadImmediate r7, 0
     86: StrictNotEqual r7, r7, r4
     90: JumpTrue r7, 6 (.L4)
     93: Mov r6, r5
  .L4:
     96: Rethrow r6
  .L5:
     98: LoadImmediate r6, 0
    101: StrictEqual r6, r4, r6
    105: JumpFalse r6, 5 (.L6)
    108: Rethrow r5
  .L6:
    110: LoadImmediate r6, 2
    113: StrictEqual r6, r4, r6
    117: JumpFalse r6, 5 (.L7)
    120: Jump 4 (.L8)
  .L7:
    122: Ret r5
  .L8:
    124: LoadUndefined r2
    126: Ret r2
  Constant Table:
    0: [String: value]
    1: [String: done]
  Exception Handlers:
    19-62 -> 70 (r5)
    79-81 -> 83 (r6)
}
