[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: NewClosure r0, c14
    45: StoreGlobal r0, c15
    48: NewClosure r0, c16
    51: StoreGlobal r0, c17
    54: NewClosure r0, c18
    57: StoreGlobal r0, c19
    60: NewClosure r0, c20
    63: StoreGlobal r0, c21
    66: NewClosure r0, c22
    69: StoreGlobal r0, c23
    72: LoadUndefined r0
    74: Ret r0
  Constant Table:
    0: [BytecodeFunction: shorthand]
    1: [String: shorthand]
    2: [BytecodeFunction: empty]
    3: [String: empty]
    4: [BytecodeFunction: propertyAliases]
    5: [String: propertyAliases]
    6: [BytecodeFunction: nested]
    7: [String: nested]
    8: [BytecodeFunction: computed]
    9: [String: computed]
    10: [BytecodeFunction: defaultValue]
    11: [String: defaultValue]
    12: [BytecodeFunction: namedExpression]
    13: [String: namedExpression]
    14: [BytecodeFunction: rest]
    15: [String: rest]
    16: [BytecodeFunction: propertyNamesNotResolved]
    17: [String: propertyNamesNotResolved]
    18: [BytecodeFunction: tdzWithinDestructuring]
    19: [String: tdzWithinDestructuring]
    20: [BytecodeFunction: propertyEvaluationOrder]
    21: [String: propertyEvaluationOrder]
    22: [BytecodeFunction: restEvaluationOrder]
    23: [String: restEvaluationOrder]
}

[BytecodeFunction: shorthand] {
  Parameters: 1, Registers: 5
     0: LoadImmediate r4, 1
     3: GetNamedProperty r0, r4, c0, k0
     8: GetNamedProperty r1, a0, c1, k1
    13: GetNamedProperty r2, a0, c2, k2
    18: GetNamedProperty r3, a0, c3, k3
    23: LoadUndefined r4
    25: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: c]
    3: [String: d]
}

[BytecodeFunction: empty] {
  Parameters: 1, Registers: 1
    0: ToObject r0, a0
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: propertyAliases] {
  Parameters: 1, Registers: 5
     0: GetNamedProperty r0, a0, c0, k0
     5: GetNamedProperty r1, a0, c1, k1
    10: GetNamedProperty r2, a0, c2, k2
    15: GetNamedProperty r3, a0, c3, k3
    20: LoadUndefined r4
    22: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: d]
    3: [String: f]
}

[BytecodeFunction: nested] {
  Parameters: 1, Registers: 5
     0: GetNamedProperty r3, a0, c0, k0
     5: GetNamedProperty r0, r3, c1, k1
    10: GetNamedProperty r3, a0, c2, k2
    15: GetNamedProperty r1, r3, c3, k3
    20: GetNamedProperty r4, r3, c4, k4
    25: GetNamedProperty r2, r4, c5, k5
    30: LoadUndefined r3
    32: Ret r3
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: c]
    3: [String: d]
    4: [String: e]
    5: [String: f]
}

[BytecodeFunction: computed] {
  Parameters: 1, Registers: 5
     0: LoadImmediate r2, 1
     3: GetProperty r0, a0, r2
     7: LoadImmediate r3, 2
    10: GetProperty r2, a0, r3
    14: LoadImmediate r4, 3
    17: GetProperty r1, r2, r4
    21: LoadUndefined r2
    23: Ret r2
}

[BytecodeFunction: defaultValue] {
  Parameters: 2, Registers: 6
     0: GetNamedProperty r4, a0, c0, k0
     5: JumpNotUndefined r4, 6 (.L0)
     8: LoadImmediate r4, 1
  .L0:
    11: Mov r0, r4
    14: GetNamedProperty r4, a0, c0, k1
    19: JumpNotUndefined r4, 6 (.L1)
    22: LoadImmediate r4, 1
  .L1:
    25: Mov r1, r4
    28: GetNamedProperty r4, a0, c1, k2
    33: JumpNotUndefined r4, 6 (.L2)
    36: Mov r4, a1
  .L2:
    39: Mov r2, r4
    42: GetNamedProperty r4, a0, c0, k3
    47: JumpNotUndefined r4, 6 (.L3)
    50: Mov r4, a1
  .L3:
    53: Mov r3, r4
    56: LoadImmediate r5, 1
    59: GetProperty r4, a0, r5
    63: JumpNotUndefined r4, 6 (.L4)
    66: LoadImmediate r4, 2
  .L4:
    69: Mov r0, r4
    72: LoadUndefined r4
    74: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: c]
}

[BytecodeFunction: namedExpression] {
  Parameters: 0, Registers: 4
     0: NewClosure r2, c0
     3: GetNamedProperty r0, r2, c1, k0
     8: LoadImmediate r2, 1
    11: GetNamedProperty r3, r2, c1, k1
    16: JumpNotUndefined r3, 6 (.L0)
    19: NewClosure r3, c2
  .L0:
    22: Mov r0, r3
    25: LoadImmediate r2, 1
    28: GetNamedProperty r3, r2, c1, k2
    33: JumpNotUndefined r3, 6 (.L1)
    36: NewClosure r3, c3
  .L1:
    39: Mov r1, r3
    42: LoadUndefined r2
    44: Ret r2
  Constant Table:
    0: [BytecodeFunction: <anonymous>]
    1: [String: a]
    2: [BytecodeFunction: a]
    3: [BytecodeFunction: b]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: a] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: b] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: rest] {
  Parameters: 1, Registers: 9
     0: ToObject r5, a0
     3: NewObject r0
     5: CopyDataProperties r0, a0, a0, 0
    10: LoadConstant r5, c0
    13: GetNamedProperty r0, a0, c0, k0
    18: LoadConstant r6, c1
    21: GetNamedProperty r1, a0, c1, k1
    26: ToObject r7, a0
    29: NewObject r2
    31: CopyDataProperties r2, a0, r5, 2
    36: LoadConstant r5, c0
    39: GetNamedProperty r0, a0, c0, k2
    44: LoadImmediate r8, 1
    47: ToPropertyKey r6, r8
    50: GetProperty r1, a0, r6
    54: LoadImmediate r8, 2
    57: ToPropertyKey r7, r8
    60: GetProperty r3, a0, r7
    64: ToObject r8, a0
    67: NewObject r4
    69: CopyDataProperties r4, a0, r5, 3
    74: LoadUndefined r5
    76: Ret r5
  Constant Table:
    0: [String: a]
    1: [String: b]
}

[BytecodeFunction: propertyNamesNotResolved] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 1
     3: GetNamedProperty r0, r2, c0, k0
     8: GetNamedProperty r3, r2, c1, k1
    13: GetNamedProperty r1, r3, c0, k2
    18: LoadUndefined r2
    20: Ret r2
  Constant Table:
    0: [String: a]
    1: [String: b]
}

[BytecodeFunction: tdzWithinDestructuring] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r0
     2: LoadImmediate r2, 1
     5: GetNamedProperty r0, r2, c0, k0
    10: CheckTdz r0, c0
    13: GetProperty r1, r2, r0
    17: LoadUndefined r2
    19: Ret r2
  Constant Table:
    0: [String: a]
}

[BytecodeFunction: propertyEvaluationOrder] {
  Parameters: 0, Registers: 5
     0: LoadGlobal r0, c0
     3: Call r0, r0, r0, 0
     8: LoadGlobal r2, c1
    11: Call r2, r2, r2, 0
    16: LoadGlobal r3, c2
    19: Call r3, r3, r3, 0
    24: LoadGlobal r4, c3
    27: Call r4, r4, r4, 0
    32: GetProperty r1, r0, r2
    36: SetProperty r3, r4, r1
    40: LoadUndefined r0
    42: Ret r0
  Constant Table:
    0: [String: d]
    1: [String: a]
    2: [String: b]
    3: [String: c]
}

[BytecodeFunction: restEvaluationOrder] {
  Parameters: 0, Registers: 6
     0: LoadGlobal r0, c0
     3: Call r0, r0, r0, 0
     8: LoadConstant r1, c1
    11: GetNamedProperty r2, r0, c1, k0
    16: StoreGlobal r2, c1
    19: LoadGlobal r3, c2
    22: Call r3, r3, r3, 0
    27: LoadGlobal r4, c3
    30: Call r4, r4, r4, 0
    35: ToObject r5, r0
    38: NewObject r2
    40: CopyDataProperties r2, r0, r1, 1
    45: SetProperty r3, r4, r2
    49: LoadUndefined r0
    51: Ret r0
  Constant Table:
    0: [String: d]
    1: [String: a]
    2: [String: b]
    3: [String: c]
}
