[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewClosure r0, c8
    31: StoreGlobal r0, c9, k4
    35: NewClosure r0, c10
    38: StoreGlobal r0, c11, k5
    42: NewClosure r0, c12
    45: StoreGlobal r0, c13, k6
    49: NewClosure r0, c14
    52: StoreGlobal r0, c15, k7
    56: NewClosure r0, c16
    59: StoreGlobal r0, c17, k8
    63: NewClosure r0, c18
    66: StoreGlobal r0, c19, k9
    70: NewClosure r0, c20
    73: StoreGlobal r0, c21, k10
    77: NewClosure r0, c22
    80: StoreGlobal r0, c23, k11
    84: NewClosure r0, c24
    87: StoreGlobal r0, c25, k12
    91: LoadUndefined r0
    93: Ret r0
  Constant Table:
    0: [BytecodeFunction: shorthand]
    1: [String: shorthand]
    2: [BytecodeFunction: empty]
    3: [String: empty]
    4: [BytecodeFunction: propertyAliases]
    5: [String: propertyAliases]
    6: [BytecodeFunction: nested]
    7: [String: nested]
    8: [BytecodeFunction: computed]
    9: [String: computed]
    10: [BytecodeFunction: defaultValue]
    11: [String: defaultValue]
    12: [BytecodeFunction: namedExpression]
    13: [String: namedExpression]
    14: [BytecodeFunction: rest]
    15: [String: rest]
    16: [BytecodeFunction: propertyNamesNotResolved]
    17: [String: propertyNamesNotResolved]
    18: [BytecodeFunction: tdzWithinDestructuring]
    19: [String: tdzWithinDestructuring]
    20: [BytecodeFunction: propertyEvaluationOrder]
    21: [String: propertyEvaluationOrder]
    22: [BytecodeFunction: restEvaluationOrder]
    23: [String: restEvaluationOrder]
    24: [BytecodeFunction: reassignObjectSource]
    25: [String: reassignObjectSource]
}

[BytecodeFunction: shorthand] {
  Parameters: 1, Registers: 5
     0: LoadImmediate r4, 1
     3: GetNamedProperty r0, r4, c0, k0
     8: Mov r4, a0
    11: GetNamedProperty r1, r4, c1, k1
    16: GetNamedProperty r2, r4, c2, k2
    21: GetNamedProperty r3, r4, c3, k3
    26: LoadUndefined r4
    28: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: c]
    3: [String: d]
}

[BytecodeFunction: empty] {
  Parameters: 1, Registers: 2
    0: Mov r0, a0
    3: ToObject r1, r0
    6: LoadUndefined r0
    8: Ret r0
}

[BytecodeFunction: propertyAliases] {
  Parameters: 1, Registers: 5
     0: Mov r4, a0
     3: GetNamedProperty r0, r4, c0, k0
     8: Mov r4, a0
    11: GetNamedProperty r1, r4, c1, k1
    16: GetNamedProperty r2, r4, c2, k2
    21: GetNamedProperty r3, r4, c3, k3
    26: LoadUndefined r4
    28: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: d]
    3: [String: f]
}

[BytecodeFunction: nested] {
  Parameters: 1, Registers: 6
     0: Mov r3, a0
     3: GetNamedProperty r4, r3, c0, k0
     8: GetNamedProperty r0, r4, c1, k1
    13: Mov r3, a0
    16: GetNamedProperty r4, r3, c2, k2
    21: GetNamedProperty r1, r4, c3, k3
    26: GetNamedProperty r5, r4, c4, k4
    31: GetNamedProperty r2, r5, c5, k5
    36: LoadUndefined r3
    38: Ret r3
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: c]
    3: [String: d]
    4: [String: e]
    5: [String: f]
}

[BytecodeFunction: computed] {
  Parameters: 1, Registers: 6
     0: Mov r2, a0
     3: LoadImmediate r3, 1
     6: GetProperty r0, r2, r3
    10: Mov r2, a0
    13: LoadImmediate r4, 2
    16: GetProperty r3, r2, r4
    20: LoadImmediate r5, 3
    23: GetProperty r1, r3, r5
    27: LoadUndefined r2
    29: Ret r2
}

[BytecodeFunction: defaultValue] {
  Parameters: 2, Registers: 7
     0: Mov r4, a0
     3: GetNamedProperty r5, r4, c0, k0
     8: JumpNotUndefined r5, 6 (.L0)
    11: LoadImmediate r5, 1
  .L0:
    14: Mov r0, r5
    17: Mov r4, a0
    20: GetNamedProperty r5, r4, c0, k1
    25: JumpNotUndefined r5, 6 (.L1)
    28: LoadImmediate r5, 1
  .L1:
    31: Mov r1, r5
    34: Mov r4, a0
    37: GetNamedProperty r5, r4, c1, k2
    42: JumpNotUndefined r5, 6 (.L2)
    45: Mov r5, a1
  .L2:
    48: Mov r2, r5
    51: Mov r4, a0
    54: GetNamedProperty r5, r4, c0, k3
    59: JumpNotUndefined r5, 6 (.L3)
    62: Mov r5, a1
  .L3:
    65: Mov r3, r5
    68: Mov r4, a0
    71: LoadImmediate r6, 1
    74: GetProperty r5, r4, r6
    78: JumpNotUndefined r5, 6 (.L4)
    81: LoadImmediate r5, 2
  .L4:
    84: Mov r0, r5
    87: LoadUndefined r4
    89: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: c]
}

[BytecodeFunction: namedExpression] {
  Parameters: 0, Registers: 4
     0: NewClosure r2, c0
     3: GetNamedProperty r0, r2, c1, k0
     8: LoadImmediate r2, 1
    11: GetNamedProperty r3, r2, c1, k1
    16: JumpNotUndefined r3, 6 (.L0)
    19: NewClosure r3, c2
  .L0:
    22: Mov r0, r3
    25: LoadImmediate r2, 1
    28: GetNamedProperty r3, r2, c1, k2
    33: JumpNotUndefined r3, 6 (.L1)
    36: NewClosure r3, c3
  .L1:
    39: Mov r1, r3
    42: LoadUndefined r2
    44: Ret r2
  Constant Table:
    0: [BytecodeFunction: <anonymous>]
    1: [String: a]
    2: [BytecodeFunction: a]
    3: [BytecodeFunction: b]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: a] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: b] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: rest] {
  Parameters: 1, Registers: 10
     0: Mov r5, a0
     3: ToObject r6, r5
     6: NewObject r0
     8: CopyDataProperties r0, r5, r5, 0
    13: Mov r5, a0
    16: LoadConstant r6, c0
    19: GetNamedProperty r0, r5, c0, k0
    24: LoadConstant r7, c1
    27: GetNamedProperty r1, r5, c1, k1
    32: ToObject r8, r5
    35: NewObject r2
    37: CopyDataProperties r2, r5, r6, 2
    42: Mov r5, a0
    45: LoadConstant r6, c0
    48: GetNamedProperty r0, r5, c0, k2
    53: LoadImmediate r9, 1
    56: ToPropertyKey r7, r9
    59: GetProperty r1, r5, r7
    63: LoadImmediate r9, 2
    66: ToPropertyKey r8, r9
    69: GetProperty r3, r5, r8
    73: ToObject r9, r5
    76: NewObject r4
    78: CopyDataProperties r4, r5, r6, 3
    83: LoadUndefined r5
    85: Ret r5
  Constant Table:
    0: [String: a]
    1: [String: b]
}

[BytecodeFunction: propertyNamesNotResolved] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 1
     3: GetNamedProperty r0, r2, c0, k0
     8: GetNamedProperty r3, r2, c1, k1
    13: GetNamedProperty r1, r3, c0, k2
    18: LoadUndefined r2
    20: Ret r2
  Constant Table:
    0: [String: a]
    1: [String: b]
}

[BytecodeFunction: tdzWithinDestructuring] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r0
     2: LoadImmediate r2, 1
     5: GetNamedProperty r0, r2, c0, k0
    10: CheckTdz r0, c0
    13: GetProperty r1, r2, r0
    17: LoadUndefined r2
    19: Ret r2
  Constant Table:
    0: [String: a]
}

[BytecodeFunction: propertyEvaluationOrder] {
  Parameters: 0, Registers: 5
     0: LoadGlobal r0, c0, k0
     4: Call r0, r0, r0, 0
     9: LoadGlobal r2, c1, k1
    13: Call r2, r2, r2, 0
    18: LoadGlobal r3, c2, k2
    22: Call r3, r3, r3, 0
    27: LoadGlobal r4, c3, k3
    31: Call r4, r4, r4, 0
    36: GetProperty r1, r0, r2
    40: SetProperty r3, r4, r1
    44: LoadUndefined r0
    46: Ret r0
  Constant Table:
    0: [String: d]
    1: [String: a]
    2: [String: b]
    3: [String: c]
}

[BytecodeFunction: restEvaluationOrder] {
  Parameters: 0, Registers: 6
     0: LoadGlobal r0, c0, k0
     4: Call r0, r0, r0, 0
     9: LoadConstant r1, c1
    12: GetNamedProperty r2, r0, c1, k1
    17: StoreGlobal r2, c1, k2
    21: LoadGlobal r3, c2, k3
    25: Call r3, r3, r3, 0
    30: LoadGlobal r4, c3, k4
    34: Call r4, r4, r4, 0
    39: ToObject r5, r0
    42: NewObject r2
    44: CopyDataProperties r2, r0, r1, 1
    49: SetProperty r3, r4, r2
    53: LoadUndefined r0
    55: Ret r0
  Constant Table:
    0: [String: d]
    1: [String: a]
    2: [String: b]
    3: [String: c]
}

[BytecodeFunction: reassignObjectSource] {
  Parameters: 1, Registers: 3
     0: Mov r2, r0
     3: GetNamedProperty r0, r2, c0, k0
     8: GetNamedProperty r1, r2, c1, k1
    13: LoadUndefined r2
    15: Ret r2
  Constant Table:
    0: [String: a]
    1: [String: b]
}
