[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: NewClosure r0, c14
    45: StoreGlobal r0, c15
    48: NewClosure r0, c16
    51: StoreGlobal r0, c17
    54: NewClosure r0, c18
    57: StoreGlobal r0, c19
    60: NewClosure r0, c20
    63: StoreGlobal r0, c21
    66: NewClosure r0, c22
    69: StoreGlobal r0, c23
    72: LoadUndefined r0
    74: Ret r0
  Constant Table:
    0: [BytecodeFunction: shorthand]
    1: [String: shorthand]
    2: [BytecodeFunction: empty]
    3: [String: empty]
    4: [BytecodeFunction: propertyAliases]
    5: [String: propertyAliases]
    6: [BytecodeFunction: nested]
    7: [String: nested]
    8: [BytecodeFunction: computed]
    9: [String: computed]
    10: [BytecodeFunction: defaultValue]
    11: [String: defaultValue]
    12: [BytecodeFunction: namedExpression]
    13: [String: namedExpression]
    14: [BytecodeFunction: rest]
    15: [String: rest]
    16: [BytecodeFunction: propertyNamesNotResolved]
    17: [String: propertyNamesNotResolved]
    18: [BytecodeFunction: tdzWithinDestructuring]
    19: [String: tdzWithinDestructuring]
    20: [BytecodeFunction: propertyEvaluationOrder]
    21: [String: propertyEvaluationOrder]
    22: [BytecodeFunction: restEvaluationOrder]
    23: [String: restEvaluationOrder]
}

[BytecodeFunction: shorthand] {
  Parameters: 1, Registers: 5
     0: LoadImmediate r4, 1
     3: GetNamedProperty r0, r4, c0
     7: GetNamedProperty r1, a0, c1
    11: GetNamedProperty r2, a0, c2
    15: GetNamedProperty r3, a0, c3
    19: LoadUndefined r4
    21: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: c]
    3: [String: d]
}

[BytecodeFunction: empty] {
  Parameters: 1, Registers: 1
    0: ToObject r0, a0
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: propertyAliases] {
  Parameters: 1, Registers: 5
     0: GetNamedProperty r0, a0, c0
     4: GetNamedProperty r1, a0, c1
     8: GetNamedProperty r2, a0, c2
    12: GetNamedProperty r3, a0, c3
    16: LoadUndefined r4
    18: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: d]
    3: [String: f]
}

[BytecodeFunction: nested] {
  Parameters: 1, Registers: 5
     0: GetNamedProperty r3, a0, c0
     4: GetNamedProperty r0, r3, c1
     8: GetNamedProperty r3, a0, c2
    12: GetNamedProperty r1, r3, c3
    16: GetNamedProperty r4, r3, c4
    20: GetNamedProperty r2, r4, c5
    24: LoadUndefined r3
    26: Ret r3
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: c]
    3: [String: d]
    4: [String: e]
    5: [String: f]
}

[BytecodeFunction: computed] {
  Parameters: 1, Registers: 5
     0: LoadImmediate r2, 1
     3: GetProperty r0, a0, r2
     7: LoadImmediate r3, 2
    10: GetProperty r2, a0, r3
    14: LoadImmediate r4, 3
    17: GetProperty r1, r2, r4
    21: LoadUndefined r2
    23: Ret r2
}

[BytecodeFunction: defaultValue] {
  Parameters: 2, Registers: 6
     0: GetNamedProperty r4, a0, c0
     4: JumpNotUndefined r4, 6 (.L0)
     7: LoadImmediate r4, 1
  .L0:
    10: Mov r0, r4
    13: GetNamedProperty r4, a0, c0
    17: JumpNotUndefined r4, 6 (.L1)
    20: LoadImmediate r4, 1
  .L1:
    23: Mov r1, r4
    26: GetNamedProperty r4, a0, c1
    30: JumpNotUndefined r4, 6 (.L2)
    33: Mov r4, a1
  .L2:
    36: Mov r2, r4
    39: GetNamedProperty r4, a0, c0
    43: JumpNotUndefined r4, 6 (.L3)
    46: Mov r4, a1
  .L3:
    49: Mov r3, r4
    52: LoadImmediate r5, 1
    55: GetProperty r4, a0, r5
    59: JumpNotUndefined r4, 6 (.L4)
    62: LoadImmediate r4, 2
  .L4:
    65: Mov r0, r4
    68: LoadUndefined r4
    70: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: c]
}

[BytecodeFunction: namedExpression] {
  Parameters: 0, Registers: 4
     0: NewClosure r2, c0
     3: GetNamedProperty r0, r2, c1
     7: LoadImmediate r2, 1
    10: GetNamedProperty r3, r2, c1
    14: JumpNotUndefined r3, 6 (.L0)
    17: NewClosure r3, c2
  .L0:
    20: Mov r0, r3
    23: LoadImmediate r2, 1
    26: GetNamedProperty r3, r2, c1
    30: JumpNotUndefined r3, 6 (.L1)
    33: NewClosure r3, c3
  .L1:
    36: Mov r1, r3
    39: LoadUndefined r2
    41: Ret r2
  Constant Table:
    0: [BytecodeFunction: <anonymous>]
    1: [String: a]
    2: [BytecodeFunction: a]
    3: [BytecodeFunction: b]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: a] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: b] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: rest] {
  Parameters: 1, Registers: 9
     0: ToObject r5, a0
     3: NewObject r0
     5: CopyDataProperties r0, a0, a0, 0
    10: LoadConstant r5, c0
    13: GetNamedProperty r0, a0, c0
    17: LoadConstant r6, c1
    20: GetNamedProperty r1, a0, c1
    24: ToObject r7, a0
    27: NewObject r2
    29: CopyDataProperties r2, a0, r5, 2
    34: LoadConstant r5, c0
    37: GetNamedProperty r0, a0, c0
    41: LoadImmediate r8, 1
    44: ToPropertyKey r6, r8
    47: GetProperty r1, a0, r8
    51: LoadImmediate r8, 2
    54: ToPropertyKey r7, r8
    57: GetProperty r3, a0, r8
    61: ToObject r8, a0
    64: NewObject r4
    66: CopyDataProperties r4, a0, r5, 3
    71: LoadUndefined r5
    73: Ret r5
  Constant Table:
    0: [String: a]
    1: [String: b]
}

[BytecodeFunction: propertyNamesNotResolved] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 1
     3: GetNamedProperty r0, r2, c0
     7: GetNamedProperty r3, r2, c1
    11: GetNamedProperty r1, r3, c0
    15: LoadUndefined r2
    17: Ret r2
  Constant Table:
    0: [String: a]
    1: [String: b]
}

[BytecodeFunction: tdzWithinDestructuring] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r0
     2: LoadImmediate r2, 1
     5: GetNamedProperty r0, r2, c0
     9: CheckTdz r0, c0
    12: GetProperty r1, r2, r0
    16: LoadUndefined r2
    18: Ret r2
  Constant Table:
    0: [String: a]
}

[BytecodeFunction: propertyEvaluationOrder] {
  Parameters: 0, Registers: 5
     0: LoadGlobal r0, c0
     3: Call r0, r0, r0, 0
     8: LoadGlobal r2, c1
    11: Call r2, r2, r2, 0
    16: LoadGlobal r3, c2
    19: Call r3, r3, r3, 0
    24: LoadGlobal r4, c3
    27: Call r4, r4, r4, 0
    32: GetProperty r1, r0, r2
    36: SetProperty r3, r4, r1
    40: LoadUndefined r0
    42: Ret r0
  Constant Table:
    0: [String: d]
    1: [String: a]
    2: [String: b]
    3: [String: c]
}

[BytecodeFunction: restEvaluationOrder] {
  Parameters: 0, Registers: 6
     0: LoadGlobal r0, c0
     3: Call r0, r0, r0, 0
     8: LoadConstant r1, c1
    11: GetNamedProperty r2, r0, c1
    15: StoreGlobal r2, c1
    18: LoadGlobal r3, c2
    21: Call r3, r3, r3, 0
    26: LoadGlobal r4, c3
    29: Call r4, r4, r4, 0
    34: ToObject r5, r0
    37: NewObject r2
    39: CopyDataProperties r2, r0, r1, 1
    44: SetProperty r3, r4, r2
    48: LoadUndefined r0
    50: Ret r0
  Constant Table:
    0: [String: d]
    1: [String: a]
    2: [String: b]
    3: [String: c]
}
