[CompiledRegExp: /^/] {
  Flags: ""
  Match Start: Input Start
     0: AssertStart
     1: Accept
}

[CompiledRegExp: /^/] {
  Flags: "m"
  Match Start: Line
     0: AssertStartOrNewline
     1: Accept
}

[CompiledRegExp: /(?m:^)a/] {
  Flags: ""
  Match Start: Line
     0: AssertStartOrNewline
     1: CodePointLiteral(a)
     2: Accept
}

[CompiledRegExp: /(?-m:^)a/] {
  Flags: "m"
  Match Start: Input Start
     0: AssertStart
     1: CodePointLiteral(a)
     2: Accept
}

[CompiledRegExp: /(?m:(?-m:^))a/] {
  Flags: ""
  Match Start: Input Start
     0: AssertStart
     1: CodePointLiteral(a)
     2: Accept
}

[CompiledRegExp: /^a|(?m:^)b/] {
  Flags: ""
  Match Start: Line
     0: Branch(4, 8)
     3: Accept
     4: AssertStart
     5: CodePointLiteral(a)
     6: Jump(3)
     8: AssertStartOrNewline
     9: CodePointLiteral(b)
    10: Jump(3)
}

[CompiledRegExp: /(?:^a)b/] {
  Flags: ""
  Match Start: Input Start
     0: AssertStart
     1: CodePointLiteral(a)
     2: CodePointLiteral(b)
     3: Accept
}

[CompiledRegExp: /(^)a/] {
  Flags: ""
  Match Start: Input Start
     0: MarkCapturePoint(2)
     2: AssertStart
     3: MarkCapturePoint(3)
     5: CodePointLiteral(a)
     6: Accept
}

[CompiledRegExp: /((?:^))a/] {
  Flags: ""
  Match Start: Input Start
     0: MarkCapturePoint(2)
     2: AssertStart
     3: MarkCapturePoint(3)
     5: CodePointLiteral(a)
     6: Accept
}

[CompiledRegExp: /(?:^)+a/] {
  Flags: ""
  Match Start: Input Start
     0: AssertStart
     1: SetProgress(0)
     3: Branch(6, 12)
     6: AssertStart
     7: Progress(0)
     9: Branch(6, 12)
    12: CodePointLiteral(a)
    13: Accept
}

[CompiledRegExp: /(^a){1,2}b/] {
  Flags: ""
  Match Start: Input Start
     0: MarkCapturePoint(2)
     2: AssertStart
     3: CodePointLiteral(a)
     4: MarkCapturePoint(3)
     6: Branch(11, 9)
     9: CodePointLiteral(b)
    10: Accept
    11: ClearCapture(1)
    13: MarkCapturePoint(2)
    15: AssertStart
    16: CodePointLiteral(a)
    17: MarkCapturePoint(3)
    19: Jump(9)
}

[CompiledRegExp: /(?:^)?a/] {
  Flags: ""
  Match Start: Code Points("a")
     0: SetProgress(0)
     2: Branch(7, 5)
     5: CodePointLiteral(a)
     6: Accept
     7: AssertStart
     8: Progress(0)
    10: Jump(5)
}

[CompiledRegExp: /(?:^)*a/] {
  Flags: ""
  Match Start: Code Points("a")
     0: SetProgress(0)
     2: Branch(5, 11)
     5: AssertStart
     6: Progress(0)
     8: Branch(5, 11)
    11: CodePointLiteral(a)
    12: Accept
}

[CompiledRegExp: /\b^a/] {
  Flags: ""
  Match Start: Input Start
     0: AssertWordBoundary(false)
     2: AssertStart
     3: CodePointLiteral(a)
     4: Accept
}

[CompiledRegExp: /(?=x)^a/] {
  Flags: ""
  Match Start: Input Start
     0: Lookaround(true, true, 5)
     2: AssertStart
     3: CodePointLiteral(a)
     4: Accept
     5: CodePointLiteral(x)
     6: Accept
}

[CompiledRegExp: /(?<=x)^a/] {
  Flags: ""
  Match Start: Input Start
     0: Lookaround(false, true, 5)
     2: AssertStart
     3: CodePointLiteral(a)
     4: Accept
     5: CodePointLiteral(x)
     6: Accept
}

[CompiledRegExp: /a^b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: AssertStart
     2: CodePointLiteral(b)
     3: Accept
}

[CompiledRegExp: /a?^b/] {
  Flags: ""
  Match Start: Code Points("a"-"b")
     0: Branch(6, 3)
     3: AssertStart
     4: CodePointLiteral(b)
     5: Accept
     6: CodePointLiteral(a)
     7: Jump(3)
}

[CompiledRegExp: /(?:a)^b/] {
  Flags: ""
  Match Start: Code Points("a")
     0: CodePointLiteral(a)
     1: AssertStart
     2: CodePointLiteral(b)
     3: Accept
}

[CompiledRegExp: /(?=^)a/] {
  Flags: ""
  Match Start: Code Points("a")
     0: Lookaround(true, true, 4)
     2: CodePointLiteral(a)
     3: Accept
     4: AssertStart
     5: Accept
}

[CompiledRegExp: /^a?/] {
  Flags: ""
  Match Start: Input Start
     0: AssertStart
     1: Branch(5, 4)
     4: Accept
     5: CodePointLiteral(a)
     6: Jump(4)
}

[CompiledRegExp: /^a*/] {
  Flags: ""
  Match Start: Input Start
     0: AssertStart
     1: GreedyLoop("a")
     3: Accept
}

[CompiledRegExp: /^.*a/] {
  Flags: ""
  Match Start: Input Start
     0: AssertStart
     1: GreedyLoop(inverted, "\n", "\r", "\u{2028}"-"\u{2029}")
     3: CodePointLiteral(a)
     4: Accept
}

[CompiledRegExp: /^\1(a)/] {
  Flags: ""
  Match Start: Input Start
     0: AssertStart
     1: Backreference(1, false)
     3: MarkCapturePoint(2)
     5: CodePointLiteral(a)
     6: MarkCapturePoint(3)
     8: Accept
}

[CompiledRegExp: /^a|^b|^c/] {
  Flags: ""
  Match Start: Input Start
     0: Branch(7, 3)
     3: Branch(11, 15)
     6: Accept
     7: AssertStart
     8: CodePointLiteral(a)
     9: Jump(6)
    11: AssertStart
    12: CodePointLiteral(b)
    13: Jump(6)
    15: AssertStart
    16: CodePointLiteral(c)
    17: Jump(6)
}

[CompiledRegExp: /(?m:^a)|b/] {
  Flags: ""
  Match Start: Code Points("a"-"b")
     0: Branch(4, 8)
     3: Accept
     4: AssertStartOrNewline
     5: CodePointLiteral(a)
     6: Jump(3)
     8: CodePointLiteral(b)
     9: Jump(3)
}

[CompiledRegExp: /^a|b^c/] {
  Flags: ""
  Match Start: Code Points("a"-"b")
     0: Branch(4, 8)
     3: Accept
     4: AssertStart
     5: CodePointLiteral(a)
     6: Jump(3)
     8: CodePointLiteral(b)
     9: AssertStart
    10: CodePointLiteral(c)
    11: Jump(3)
}

[CompiledRegExp: /^|a/] {
  Flags: ""
  Match Start: Unknown
     0: Branch(4, 7)
     3: Accept
     4: AssertStart
     5: Jump(3)
     7: CodePointLiteral(a)
     8: Jump(3)
}

[CompiledRegExp: /^a|/] {
  Flags: ""
  Match Start: Unknown
     0: Branch(4, 8)
     3: Accept
     4: AssertStart
     5: CodePointLiteral(a)
     6: Jump(3)
     8: Jump(3)
}
