{
  type: "Program",
  loc: "1:1-31:9",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:11",
      kind: {
        type: "AssignmentExpression",
        loc: "1:1-1:10",
        operator: "=",
        left: {
          type: "Identifier",
          loc: "1:1-1:2",
          name: "a",
        },
        right: {
          type: "AssignmentExpression",
          loc: "1:5-1:10",
          operator: "=",
          left: {
            type: "Identifier",
            loc: "1:5-1:6",
            name: "b",
          },
          right: {
            type: "Identifier",
            loc: "1:9-1:10",
            name: "c",
          },
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:8",
      kind: {
        type: "AssignmentExpression",
        loc: "3:1-3:7",
        operator: "+=",
        left: {
          type: "Identifier",
          loc: "3:1-3:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "3:6-3:7",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:8",
      kind: {
        type: "AssignmentExpression",
        loc: "5:1-5:7",
        operator: "-=",
        left: {
          type: "Identifier",
          loc: "5:1-5:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "5:6-5:7",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:8",
      kind: {
        type: "AssignmentExpression",
        loc: "7:1-7:7",
        operator: "*=",
        left: {
          type: "Identifier",
          loc: "7:1-7:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "7:6-7:7",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:8",
      kind: {
        type: "AssignmentExpression",
        loc: "9:1-9:7",
        operator: "/=",
        left: {
          type: "Identifier",
          loc: "9:1-9:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "9:6-9:7",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:1-11:8",
      kind: {
        type: "AssignmentExpression",
        loc: "11:1-11:7",
        operator: "%=",
        left: {
          type: "Identifier",
          loc: "11:1-11:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "11:6-11:7",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:1-13:9",
      kind: {
        type: "AssignmentExpression",
        loc: "13:1-13:8",
        operator: "**=",
        left: {
          type: "Identifier",
          loc: "13:1-13:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "13:7-13:8",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "15:1-15:8",
      kind: {
        type: "AssignmentExpression",
        loc: "15:1-15:7",
        operator: "&=",
        left: {
          type: "Identifier",
          loc: "15:1-15:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "15:6-15:7",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:1-17:8",
      kind: {
        type: "AssignmentExpression",
        loc: "17:1-17:7",
        operator: "|=",
        left: {
          type: "Identifier",
          loc: "17:1-17:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "17:6-17:7",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "19:1-19:8",
      kind: {
        type: "AssignmentExpression",
        loc: "19:1-19:7",
        operator: "^=",
        left: {
          type: "Identifier",
          loc: "19:1-19:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "19:6-19:7",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "21:1-21:9",
      kind: {
        type: "AssignmentExpression",
        loc: "21:1-21:8",
        operator: "<<=",
        left: {
          type: "Identifier",
          loc: "21:1-21:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "21:7-21:8",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "23:1-23:9",
      kind: {
        type: "AssignmentExpression",
        loc: "23:1-23:8",
        operator: ">>=",
        left: {
          type: "Identifier",
          loc: "23:1-23:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "23:7-23:8",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "25:1-25:10",
      kind: {
        type: "AssignmentExpression",
        loc: "25:1-25:9",
        operator: ">>>=",
        left: {
          type: "Identifier",
          loc: "25:1-25:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "25:8-25:9",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "27:1-27:9",
      kind: {
        type: "AssignmentExpression",
        loc: "27:1-27:8",
        operator: "&&=",
        left: {
          type: "Identifier",
          loc: "27:1-27:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "27:7-27:8",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "29:1-29:9",
      kind: {
        type: "AssignmentExpression",
        loc: "29:1-29:8",
        operator: "||=",
        left: {
          type: "Identifier",
          loc: "29:1-29:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "29:7-29:8",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "31:1-31:9",
      kind: {
        type: "AssignmentExpression",
        loc: "31:1-31:8",
        operator: "??=",
        left: {
          type: "Identifier",
          loc: "31:1-31:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "31:7-31:8",
          name: "b",
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}