{
  type: "Program",
  loc: "1:1-11:37",
  body: [
    {
      type: "ExpressionStatement",
      loc: "2:1-2:5",
      kind: {
        type: "Literal",
        loc: "2:1-2:4",
        raw: "/]/",
        value: {
          pattern: "]",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "]",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:5",
      kind: {
        type: "Literal",
        loc: "3:1-3:4",
        raw: "/{/",
        value: {
          pattern: "{",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "{",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "4:1-4:5",
      kind: {
        type: "Literal",
        loc: "4:1-4:4",
        raw: "/}/",
        value: {
          pattern: "}",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "}",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:6",
      kind: {
        type: "Literal",
        loc: "7:1-7:5",
        raw: "/a{/",
        value: {
          pattern: "a{",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a{",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "8:1-8:7",
      kind: {
        type: "Literal",
        loc: "8:1-8:6",
        raw: "/a{1/",
        value: {
          pattern: "a{1",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a{1",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:8",
      kind: {
        type: "Literal",
        loc: "9:1-9:7",
        raw: "/a{1,/",
        value: {
          pattern: "a{1,",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a{1,",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "10:1-10:9",
      kind: {
        type: "Literal",
        loc: "10:1-10:8",
        raw: "/a{1,2/",
        value: {
          pattern: "a{1,2",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a{1,2",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:1-11:37",
      kind: {
        type: "Literal",
        loc: "11:1-11:36",
        raw: "/a{123456789012345678901234567890}/",
        value: {
          pattern: "a{123456789012345678901234567890}",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a{123456789012345678901234567890}",
                },
              ],
            },
          ],
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}