[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: LoadUndefined r0
    28: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: test1]
    2: [String: test1]
    3: [BytecodeFunction: test2]
    4: [String: test2]
    5: [BytecodeFunction: test3]
    6: [String: test3]
    7: [BytecodeFunction: test4]
    8: [String: test4]
}

[BytecodeFunction: test1] {
  Parameters: 2, Registers: 1
    0: Add r0, a0, a1
    4: Ret r0
}

[BytecodeFunction: test2] {
  Parameters: 1, Registers: 1
     0: JumpToBooleanFalse a0, 7 (.L0)
     3: LoadUndefined r0
     5: Ret r0
  .L0:
     7: JumpToBooleanFalse a0, 5 (.L1)
    10: Ret a0
  .L1:
    12: LoadImmediate r0, 2
    15: Ret r0
}

[BytecodeFunction: test3] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 1
    3: LoadUndefined r0
    5: Ret r0
}

[BytecodeFunction: test4] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
