[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: 16 ff 00   NewClosure r0, c0
     3: 0a ff 01   StoreGlobal r0, c1
     6: 16 ff 02   NewClosure r0, c2
     9: 0a ff 03   StoreGlobal r0, c3
    12: 16 ff 04   NewClosure r0, c4
    15: 0a ff 05   StoreGlobal r0, c5
    18: 16 ff 06   NewClosure r0, c6
    21: 0a ff 07   StoreGlobal r0, c7
    24: 05 ff      LoadUndefined r0
    26: 0c ff      Ret r0
  Constant Table:
    0: [BytecodeFunction: test1]
    1: [String: test1]
    2: [BytecodeFunction: test2]
    3: [String: test2]
    4: [BytecodeFunction: test3]
    5: [String: test3]
    6: [BytecodeFunction: test4]
    7: [String: test4]
}

[BytecodeFunction: test1] {
  Parameters: 2, Registers: 1
    0: 0d ff 05 06   Add r0, a0, a1
    4: 0c ff         Ret r0
}

[BytecodeFunction: test2] {
  Parameters: 1, Registers: 1
     0: 14 05 07   JumpToBooleanFalse a0, 7 (.L0)
     3: 05 ff      LoadUndefined r0
     5: 0c ff      Ret r0
  .L0:
     7: 14 05 05   JumpToBooleanFalse a0, 5 (.L1)
    10: 0c 05      Ret a0
  .L1:
    12: 03 ff 02   LoadImmediate r0, 2
    15: 0c ff      Ret r0
}

[BytecodeFunction: test3] {
  Parameters: 0, Registers: 1
    0: 03 ff 01   LoadImmediate r0, 1
    3: 05 ff      LoadUndefined r0
    5: 0c ff      Ret r0
}

[BytecodeFunction: test4] {
  Parameters: 0, Registers: 1
    0: 05 ff   LoadUndefined r0
    2: 0c ff   Ret r0
}
