[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
     0: NewClosure r1, c0
     3: StoreGlobal r1, c1
     6: NewClosure r0, c2
     9: NewClosure r1, c3
    12: StoreGlobal r1, c4
    15: LoadUndefined r1
    17: Ret r1
  Constant Table:
    0: [BytecodeFunction: test1]
    1: [String: test1]
    2: [BytecodeFunction: test2]
    3: [BytecodeFunction: test3]
    4: [String: test3]
}

[BytecodeFunction: test1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: test2] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: test3] {
  Parameters: 0, Registers: 2
    0: NewClosure r0, c0
    3: LoadUndefined r1
    5: Ret r1
  Constant Table:
    0: [BytecodeFunction: test4]
}

[BytecodeFunction: test4] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
