[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
     0: GlobalInit c0
     2: NewClosure r1, c1
     5: StoreGlobal r1, c2
     8: NewClosure r1, c3
    11: StoreGlobal r1, c4
    14: NewClosure r0, c5
    17: LoadUndefined r1
    19: Ret r1
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: test1]
    2: [String: test1]
    3: [BytecodeFunction: test3]
    4: [String: test3]
    5: [BytecodeFunction: test2]
}

[BytecodeFunction: test1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: test3] {
  Parameters: 0, Registers: 2
    0: NewClosure r0, c0
    3: LoadUndefined r1
    5: Ret r1
  Constant Table:
    0: [BytecodeFunction: test4]
}

[BytecodeFunction: test4] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: test2] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
