[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 3
     0: NewGenerator r0, c0
     3: StoreGlobal r0, c1
     6: NewGenerator r0, c2
     9: StoreGlobal r0, c3
    12: NewGenerator r0, c4
    15: StoreGlobal r0, c5
    18: NewGenerator r0, c6
    21: StoreGlobal r0, c7
    24: NewGenerator r0, c8
    27: StoreGlobal r0, c9
    30: NewGenerator r0, c10
    33: StoreGlobal r0, c11
    36: NewGenerator r0, c12
    39: NewGenerator r0, c13
    42: NewObject r0
    44: NewGenerator r1, c15
    47: DefineNamedProperty r0, c14, r1
    51: LoadEmpty r1
    53: NewGenerator r2, c16
    56: NewClass r0, c18, c17, r1, r2
    62: StoreToScope r0, 1, 0
    66: LoadUndefined r0
    68: Ret r0
  Constant Table:
    0: [BytecodeFunction: empty]
    1: [String: empty]
    2: [BytecodeFunction: withArgsAndBody]
    3: [String: withArgsAndBody]
    4: [BytecodeFunction: simpleYield]
    5: [String: simpleYield]
    6: [BytecodeFunction: yieldWithArg]
    7: [String: yieldWithArg]
    8: [BytecodeFunction: multipleYields]
    9: [String: multipleYields]
    10: [BytecodeFunction: yieldReturnValue]
    11: [String: yieldReturnValue]
    12: [BytecodeFunction: generatorExpression]
    13: [BytecodeFunction: <anonymous>]
    14: [String: generatorMethod]
    15: [BytecodeFunction: generatorMethod]
    16: [BytecodeFunction: generatorMethod]
    17: [BytecodeFunction: C]
    18: [ClassNames]
}

[BytecodeFunction: empty] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: withArgsAndBody] {
  Parameters: 3, Registers: 2
     0: JumpNotUndefined a1, 6 (.L0)
     3: LoadImmediate a1, 1
  .L0:
     6: JumpNotUndefined a2, 6 (.L1)
     9: LoadImmediate a2, 2
  .L1:
    12: GeneratorStart r0
    14: LoadImmediate r1, 3
    17: LoadUndefined r1
    19: Ret r1
}

[BytecodeFunction: simpleYield] {
  Parameters: 0, Registers: 2
     0: GeneratorStart r0
     2: LoadImmediate r1, 1
     5: LoadUndefined r1
     7: Yield r1, r0, r1
    11: LoadImmediate r1, 2
    14: LoadUndefined r1
    16: Ret r1
}

[BytecodeFunction: yieldWithArg] {
  Parameters: 0, Registers: 2
     0: GeneratorStart r0
     2: LoadImmediate r1, 1
     5: LoadImmediate r1, 2
     8: Yield r1, r0, r1
    12: LoadImmediate r1, 3
    15: LoadUndefined r1
    17: Ret r1
}

[BytecodeFunction: multipleYields] {
  Parameters: 0, Registers: 2
     0: GeneratorStart r0
     2: LoadUndefined r1
     4: Yield r1, r0, r1
     8: LoadImmediate r1, 1
    11: Yield r1, r0, r1
    15: LoadUndefined r1
    17: Yield r1, r0, r1
    21: LoadImmediate r1, 2
    24: Yield r1, r0, r1
    28: LoadUndefined r1
    30: Ret r1
}

[BytecodeFunction: yieldReturnValue] {
  Parameters: 0, Registers: 3
     0: GeneratorStart r0
     2: LoadUndefined r1
     4: Yield r1, r0, r1
     8: LoadImmediate r2, 1
    11: Yield r2, r0, r2
    15: Add r1, r1, r2
    19: Ret r1
}

[BytecodeFunction: generatorExpression] {
  Parameters: 0, Registers: 3
    0: Mov r0, <closure>
    3: GeneratorStart r1
    5: LoadUndefined r2
    7: Ret r2
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: generatorMethod] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: generatorMethod] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}
