[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 3
     0: NewGenerator r0, c0
     3: StoreGlobal r0, c1
     6: NewGenerator r0, c2
     9: StoreGlobal r0, c3
    12: NewGenerator r0, c4
    15: StoreGlobal r0, c5
    18: NewGenerator r0, c6
    21: StoreGlobal r0, c7
    24: NewGenerator r0, c8
    27: StoreGlobal r0, c9
    30: NewGenerator r0, c10
    33: StoreGlobal r0, c11
    36: NewGenerator r0, c12
    39: StoreGlobal r0, c13
    42: NewGenerator r0, c14
    45: NewGenerator r0, c15
    48: NewObject r0
    50: NewGenerator r1, c17
    53: DefineNamedProperty r0, c16, r1
    57: LoadEmpty r1
    59: NewGenerator r2, c18
    62: NewClass r0, c20, c19, r1, r2
    68: StoreToScope r0, 1, 0
    72: LoadUndefined r0
    74: Ret r0
  Constant Table:
    0: [BytecodeFunction: empty]
    1: [String: empty]
    2: [BytecodeFunction: withArgsAndBody]
    3: [String: withArgsAndBody]
    4: [BytecodeFunction: simpleYield]
    5: [String: simpleYield]
    6: [BytecodeFunction: yieldWithArg]
    7: [String: yieldWithArg]
    8: [BytecodeFunction: multipleYields]
    9: [String: multipleYields]
    10: [BytecodeFunction: yieldReturnValue]
    11: [String: yieldReturnValue]
    12: [BytecodeFunction: yieldInFinally]
    13: [String: yieldInFinally]
    14: [BytecodeFunction: generatorExpression]
    15: [BytecodeFunction: <anonymous>]
    16: [String: generatorMethod]
    17: [BytecodeFunction: generatorMethod]
    18: [BytecodeFunction: generatorMethod]
    19: [BytecodeFunction: C]
    20: [ClassNames]
}

[BytecodeFunction: empty] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: withArgsAndBody] {
  Parameters: 3, Registers: 2
     0: JumpNotUndefined a1, 6 (.L0)
     3: LoadImmediate a1, 1
  .L0:
     6: JumpNotUndefined a2, 6 (.L1)
     9: LoadImmediate a2, 2
  .L1:
    12: GeneratorStart r0
    14: LoadImmediate r1, 3
    17: LoadUndefined r1
    19: Ret r1
}

[BytecodeFunction: simpleYield] {
  Parameters: 0, Registers: 4
     0: GeneratorStart r0
     2: LoadImmediate r1, 1
     5: LoadUndefined r1
     7: Mov r2, r1
    10: NewObject r3
    12: SetNamedProperty r3, c0, r2
    16: LoadFalse r2
    18: SetNamedProperty r3, c1, r2
    22: Yield r1, r2, r0, r3
    27: JumpNotNullish r2, 10 (.L1)
    30: JumpNotUndefined r2, 5 (.L0)
    33: Ret r1
  .L0:
    35: Throw r1
  .L1:
    37: LoadImmediate r1, 2
    40: LoadUndefined r1
    42: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
}

[BytecodeFunction: yieldWithArg] {
  Parameters: 0, Registers: 4
     0: GeneratorStart r0
     2: LoadImmediate r1, 1
     5: LoadImmediate r1, 2
     8: Mov r2, r1
    11: NewObject r3
    13: SetNamedProperty r3, c0, r2
    17: LoadFalse r2
    19: SetNamedProperty r3, c1, r2
    23: Yield r1, r2, r0, r3
    28: JumpNotNullish r2, 10 (.L1)
    31: JumpNotUndefined r2, 5 (.L0)
    34: Ret r1
  .L0:
    36: Throw r1
  .L1:
    38: LoadImmediate r1, 3
    41: LoadUndefined r1
    43: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
}

[BytecodeFunction: multipleYields] {
  Parameters: 0, Registers: 4
      0: GeneratorStart r0
      2: LoadUndefined r1
      4: Mov r2, r1
      7: NewObject r3
      9: SetNamedProperty r3, c0, r2
     13: LoadFalse r2
     15: SetNamedProperty r3, c1, r2
     19: Yield r1, r2, r0, r3
     24: JumpNotNullish r2, 10 (.L1)
     27: JumpNotUndefined r2, 5 (.L0)
     30: Ret r1
  .L0:
     32: Throw r1
  .L1:
     34: LoadImmediate r1, 1
     37: Mov r2, r1
     40: NewObject r3
     42: SetNamedProperty r3, c0, r2
     46: LoadFalse r2
     48: SetNamedProperty r3, c1, r2
     52: Yield r1, r2, r0, r3
     57: JumpNotNullish r2, 10 (.L3)
     60: JumpNotUndefined r2, 5 (.L2)
     63: Ret r1
  .L2:
     65: Throw r1
  .L3:
     67: LoadUndefined r1
     69: Mov r2, r1
     72: NewObject r3
     74: SetNamedProperty r3, c0, r2
     78: LoadFalse r2
     80: SetNamedProperty r3, c1, r2
     84: Yield r1, r2, r0, r3
     89: JumpNotNullish r2, 10 (.L5)
     92: JumpNotUndefined r2, 5 (.L4)
     95: Ret r1
  .L4:
     97: Throw r1
  .L5:
     99: LoadImmediate r1, 2
    102: Mov r2, r1
    105: NewObject r3
    107: SetNamedProperty r3, c0, r2
    111: LoadFalse r2
    113: SetNamedProperty r3, c1, r2
    117: Yield r1, r2, r0, r3
    122: JumpNotNullish r2, 10 (.L7)
    125: JumpNotUndefined r2, 5 (.L6)
    128: Ret r1
  .L6:
    130: Throw r1
  .L7:
    132: LoadUndefined r1
    134: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
}

[BytecodeFunction: yieldReturnValue] {
  Parameters: 0, Registers: 5
     0: GeneratorStart r0
     2: LoadUndefined r1
     4: Mov r2, r1
     7: NewObject r3
     9: SetNamedProperty r3, c0, r2
    13: LoadFalse r2
    15: SetNamedProperty r3, c1, r2
    19: Yield r1, r2, r0, r3
    24: JumpNotNullish r2, 10 (.L1)
    27: JumpNotUndefined r2, 5 (.L0)
    30: Ret r1
  .L0:
    32: Throw r1
  .L1:
    34: LoadImmediate r2, 1
    37: Mov r3, r2
    40: NewObject r4
    42: SetNamedProperty r4, c0, r3
    46: LoadFalse r3
    48: SetNamedProperty r4, c1, r3
    52: Yield r2, r3, r0, r4
    57: JumpNotNullish r3, 10 (.L3)
    60: JumpNotUndefined r3, 5 (.L2)
    63: Ret r2
  .L2:
    65: Throw r2
  .L3:
    67: Add r1, r1, r2
    71: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
}

[BytecodeFunction: yieldInFinally] {
  Parameters: 0, Registers: 7
     0: GeneratorStart r0
     2: Mov r3, <scope>
     5: LoadUndefined r4
     7: Mov r5, r4
    10: NewObject r6
    12: SetNamedProperty r6, c0, r5
    16: LoadFalse r5
    18: SetNamedProperty r6, c1, r5
    22: Yield r4, r5, r0, r6
    27: JumpNotNullish r5, 16 (.L1)
    30: JumpNotUndefined r5, 11 (.L0)
    33: LoadImmediate r1, 1
    36: Mov r2, r4
    39: Jump 12 (.L2)
  .L0:
    41: Throw r4
  .L1:
    43: LoadImmediate r1, 2
    46: Jump 5 (.L2)
    48: LoadImmediate r1, 0
  .L2:
    51: Mov <scope>, r3
    54: LoadImmediate r3, 1
    57: LoadImmediate r3, 0
    60: StrictEqual r3, r1, r3
    64: JumpFalse r3, 5 (.L3)
    67: Throw r2
  .L3:
    69: LoadImmediate r3, 2
    72: StrictEqual r3, r1, r3
    76: JumpFalse r3, 5 (.L4)
    79: Jump 4 (.L5)
  .L4:
    81: Ret r2
  .L5:
    83: LoadUndefined r1
    85: Ret r1
  Constant Table:
    0: [String: value]
    1: [String: done]
  Exception Handlers:
    5-43 -> 48 (r2)
}

[BytecodeFunction: generatorExpression] {
  Parameters: 0, Registers: 3
    0: Mov r0, <closure>
    3: GeneratorStart r1
    5: LoadUndefined r2
    7: Ret r2
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: generatorMethod] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: C] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: generatorMethod] {
  Parameters: 0, Registers: 2
    0: GeneratorStart r0
    2: LoadUndefined r1
    4: Ret r1
}
