[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: LoadUndefined r0
    14: Ret r0
  Constant Table:
    0: [BytecodeFunction: destructuring]
    1: [String: destructuring]
    2: [BytecodeFunction: defaultValues]
    3: [String: defaultValues]
}

[BytecodeFunction: destructuring] {
  Parameters: 2, Registers: 5
     0: GetNamedProperty r0, a0, c0
     4: GetNamedProperty r1, a0, c1
     8: GetNamedProperty r2, a1, c2
    12: GetNamedProperty r4, a1, c3
    16: JumpNotUndefined r4, 6 (.L0)
    19: LoadImmediate r4, 1
  .L0:
    22: Mov r3, r4
    25: LoadUndefined r4
    27: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: c]
    3: [String: e]
}

[BytecodeFunction: defaultValues] {
  Parameters: 4, Registers: 1
     0: JumpNotUndefined a1, 6 (.L0)
     3: LoadImmediate a1, 1
  .L0:
     6: JumpNotUndefined a2, 6 (.L1)
     9: LoadImmediate a2, 2
  .L1:
    12: JumpNotUndefined a3, 6 (.L2)
    15: Mov a3, a1
  .L2:
    18: LoadUndefined r0
    20: Ret r0
}
