[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: NewClosure r0, c11
    35: StoreGlobal r0, c12
    38: NewClosure r0, c13
    41: StoreGlobal r0, c14
    44: NewClosure r0, c15
    47: StoreGlobal r0, c16
    50: LoadUndefined r0
    52: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: destructuring]
    2: [String: destructuring]
    3: [BytecodeFunction: defaultValues]
    4: [String: defaultValues]
    5: [BytecodeFunction: rest]
    6: [String: rest]
    7: [BytecodeFunction: restDestructuring]
    8: [String: restDestructuring]
    9: [BytecodeFunction: captured]
    10: [String: captured]
    11: [BytecodeFunction: tdz]
    12: [String: tdz]
    13: [BytecodeFunction: tdzCaptured]
    14: [String: tdzCaptured]
    15: [BytecodeFunction: shadowed]
    16: [String: shadowed]
}

[BytecodeFunction: destructuring] {
  Parameters: 2, Registers: 5
     0: GetNamedProperty r0, a0, c0
     4: GetNamedProperty r1, a0, c1
     8: GetNamedProperty r2, a1, c2
    12: GetNamedProperty r4, a1, c3
    16: JumpNotUndefined r4, 6 (.L0)
    19: LoadImmediate r4, 1
  .L0:
    22: Mov r3, r4
    25: LoadUndefined r4
    27: Ret r4
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: c]
    3: [String: e]
}

[BytecodeFunction: defaultValues] {
  Parameters: 4, Registers: 1
     0: JumpNotUndefined a1, 6 (.L0)
     3: LoadImmediate a1, 1
  .L0:
     6: JumpNotUndefined a2, 6 (.L1)
     9: LoadImmediate a2, 2
  .L1:
    12: JumpNotUndefined a3, 6 (.L2)
    15: Mov a3, a1
  .L2:
    18: LoadUndefined r0
    20: Ret r0
}

[BytecodeFunction: rest] {
  Parameters: 2, Registers: 2
     0: JumpNotUndefined a1, 6 (.L0)
     3: LoadImmediate a1, 1
  .L0:
     6: RestParameter r0
     8: LoadUndefined r1
    10: Ret r1
}

[BytecodeFunction: restDestructuring] {
  Parameters: 2, Registers: 2
    0: RestParameter r1
    2: GetNamedProperty r0, r1, c0
    6: LoadUndefined r1
    8: Ret r1
  Constant Table:
    0: [String: c]
}

[BytecodeFunction: captured] {
  Parameters: 2, Registers: 2
     0: PushFunctionScope c0
     2: GetNamedProperty r1, a0, c1
     6: StoreToScope r1, 0, 0
    10: JumpNotUndefined a1, 6 (.L0)
    13: LoadImmediate a1, 1
  .L0:
    16: StoreToScope a1, 1, 0
    20: RestParameter r1
    22: StoreToScope r1, 2, 0
    26: NewClosure r0, c2
    29: LoadUndefined r1
    31: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: a]
    2: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 0
     4: LoadFromScope r1, 1, 0
     8: Add r0, r0, r1
    12: LoadFromScope r1, 2, 0
    16: Add r0, r0, r1
    20: Ret r0
}

[BytecodeFunction: tdz] {
  Parameters: 2, Registers: 2
     0: LoadEmpty r0
     2: JumpNotUndefined a0, 9 (.L0)
     5: CheckTdz r0, c0
     8: Mov a0, r0
  .L0:
    11: Mov r0, a1
    14: CheckTdz r0, c0
    17: Add r1, a0, r0
    21: LoadUndefined r1
    23: Ret r1
  Constant Table:
    0: [String: b]
}

[BytecodeFunction: tdzCaptured] {
  Parameters: 2, Registers: 3
     0: PushFunctionScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 1, 0
     8: JumpNotUndefined a0, 13 (.L0)
    11: LoadFromScope r1, 1, 0
    15: CheckTdz r1, c1
    18: Mov a0, r1
  .L0:
    21: StoreToScope a0, 0, 0
    25: StoreToScope a1, 1, 0
    29: NewClosure r0, c2
    32: LoadFromScope r1, 0, 0
    36: LoadFromScope r2, 1, 0
    40: CheckTdz r2, c1
    43: Add r1, r1, r2
    47: LoadUndefined r1
    49: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: b]
    2: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 0
     4: LoadFromScope r1, 1, 0
     8: CheckTdz r1, c0
    11: Add r0, r0, r1
    15: Ret r0
  Constant Table:
    0: [String: b]
}

[BytecodeFunction: shadowed] {
  Parameters: 3, Registers: 0
    0: Ret a2
}
