[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: NewClosure r0, c11
    35: StoreGlobal r0, c12
    38: LoadUndefined r0
    40: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: testIfNoAlternate]
    2: [String: testIfNoAlternate]
    3: [BytecodeFunction: TestIfNormalAlternate]
    4: [String: TestIfNormalAlternate]
    5: [BytecodeFunction: testIfNormalConseq]
    6: [String: testIfNormalConseq]
    7: [BytecodeFunction: testIfBothAbrupt]
    8: [String: testIfBothAbrupt]
    9: [BytecodeFunction: testIfNestedOneNormalBranch]
    10: [String: testIfNestedOneNormalBranch]
    11: [BytecodeFunction: testIfNestedNoNormalBranches]
    12: [String: testIfNestedNoNormalBranches]
}

[BytecodeFunction: testIfNoAlternate] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 8 (.L0)
     5: LoadImmediate r0, 1
     8: Ret r0
  .L0:
    10: LoadUndefined r0
    12: Ret r0
}

[BytecodeFunction: TestIfNormalAlternate] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 8 (.L0)
     5: LoadImmediate r0, 1
     8: Ret r0
  .L0:
    10: LoadImmediate r0, 2
    13: LoadUndefined r0
    15: Ret r0
}

[BytecodeFunction: testIfNormalConseq] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 8 (.L0)
     5: LoadImmediate r0, 1
     8: Jump 7 (.L1)
  .L0:
    10: LoadImmediate r0, 2
    13: Ret r0
  .L1:
    15: LoadUndefined r0
    17: Ret r0
}

[BytecodeFunction: testIfBothAbrupt] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 8 (.L0)
     5: LoadImmediate r0, 1
     8: Ret r0
  .L0:
    10: LoadImmediate r0, 2
    13: Ret r0
}

[BytecodeFunction: testIfNestedOneNormalBranch] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 28 (.L2)
     5: LoadTrue r0
     7: JumpFalse r0, 8 (.L0)
    10: LoadImmediate r0, 1
    13: Ret r0
  .L0:
    15: LoadTrue r0
    17: JumpFalse r0, 8 (.L1)
    20: LoadImmediate r0, 2
    23: Ret r0
  .L1:
    25: LoadImmediate r0, 3
    28: Jump 7 (.L3)
  .L2:
    30: LoadImmediate r0, 4
    33: Ret r0
  .L3:
    35: LoadUndefined r0
    37: Ret r0
}

[BytecodeFunction: testIfNestedNoNormalBranches] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 28 (.L2)
     5: LoadTrue r0
     7: JumpFalse r0, 8 (.L0)
    10: LoadImmediate r0, 1
    13: Ret r0
  .L0:
    15: LoadTrue r0
    17: JumpFalse r0, 8 (.L1)
    20: LoadImmediate r0, 2
    23: Ret r0
  .L1:
    25: LoadImmediate r0, 3
    28: Ret r0
  .L2:
    30: LoadImmediate r0, 4
    33: Ret r0
}
