[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: LoadUndefined r0
    38: Ret r0
  Constant Table:
    0: [BytecodeFunction: testIfNoAlternate]
    1: [String: testIfNoAlternate]
    2: [BytecodeFunction: TestIfNormalAlternate]
    3: [String: TestIfNormalAlternate]
    4: [BytecodeFunction: testIfNormalConseq]
    5: [String: testIfNormalConseq]
    6: [BytecodeFunction: testIfBothAbrupt]
    7: [String: testIfBothAbrupt]
    8: [BytecodeFunction: testIfNestedOneNormalBranch]
    9: [String: testIfNestedOneNormalBranch]
    10: [BytecodeFunction: testIfNestedNoNormalBranches]
    11: [String: testIfNestedNoNormalBranches]
}

[BytecodeFunction: testIfNoAlternate] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 8 (.L0)
     5: LoadImmediate r0, 1
     8: Ret r0
  .L0:
    10: LoadUndefined r0
    12: Ret r0
}

[BytecodeFunction: TestIfNormalAlternate] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 8 (.L0)
     5: LoadImmediate r0, 1
     8: Ret r0
  .L0:
    10: LoadImmediate r0, 2
    13: LoadUndefined r0
    15: Ret r0
}

[BytecodeFunction: testIfNormalConseq] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 8 (.L0)
     5: LoadImmediate r0, 1
     8: Jump 7 (.L1)
  .L0:
    10: LoadImmediate r0, 2
    13: Ret r0
  .L1:
    15: LoadUndefined r0
    17: Ret r0
}

[BytecodeFunction: testIfBothAbrupt] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 8 (.L0)
     5: LoadImmediate r0, 1
     8: Ret r0
  .L0:
    10: LoadImmediate r0, 2
    13: Ret r0
}

[BytecodeFunction: testIfNestedOneNormalBranch] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 28 (.L2)
     5: LoadTrue r0
     7: JumpFalse r0, 8 (.L0)
    10: LoadImmediate r0, 1
    13: Ret r0
  .L0:
    15: LoadTrue r0
    17: JumpFalse r0, 8 (.L1)
    20: LoadImmediate r0, 2
    23: Ret r0
  .L1:
    25: LoadImmediate r0, 3
    28: Jump 7 (.L3)
  .L2:
    30: LoadImmediate r0, 4
    33: Ret r0
  .L3:
    35: LoadUndefined r0
    37: Ret r0
}

[BytecodeFunction: testIfNestedNoNormalBranches] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 28 (.L2)
     5: LoadTrue r0
     7: JumpFalse r0, 8 (.L0)
    10: LoadImmediate r0, 1
    13: Ret r0
  .L0:
    15: LoadTrue r0
    17: JumpFalse r0, 8 (.L1)
    20: LoadImmediate r0, 2
    23: Ret r0
  .L1:
    25: LoadImmediate r0, 3
    28: Ret r0
  .L2:
    30: LoadImmediate r0, 4
    33: Ret r0
}
