[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: NewClosure r0, c14
    45: StoreGlobal r0, c15
    48: NewClosure r0, c16
    51: StoreGlobal r0, c17
    54: LoadUndefined r0
    56: Ret r0
  Constant Table:
    0: [BytecodeFunction: testEmptyArray]
    1: [String: testEmptyArray]
    2: [BytecodeFunction: testArrayWithOneElement]
    3: [String: testArrayWithOneElement]
    4: [BytecodeFunction: testArrayWithElements]
    5: [String: testArrayWithElements]
    6: [BytecodeFunction: testArrayWithHolesAndElements]
    7: [String: testArrayWithHolesAndElements]
    8: [BytecodeFunction: testArrayWithOnlyHoles]
    9: [String: testArrayWithOnlyHoles]
    10: [BytecodeFunction: onlySpread]
    11: [String: onlySpread]
    12: [BytecodeFunction: multipleSpreads]
    13: [String: multipleSpreads]
    14: [BytecodeFunction: temporaryRegisterToAvoidClobbering]
    15: [String: temporaryRegisterToAvoidClobbering]
    16: [BytecodeFunction: noTemporaryRegisterNeededForEmptyObject]
    17: [String: noTemporaryRegisterNeededForEmptyObject]
}

[BytecodeFunction: testEmptyArray] {
  Parameters: 0, Registers: 1
    0: NewArray r0
    2: Ret r0
}

[BytecodeFunction: testArrayWithOneElement] {
  Parameters: 0, Registers: 3
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: LoadImmediate r2, 1
     8: SetArrayProperty r0, r1, r2
    12: Ret r0
}

[BytecodeFunction: testArrayWithElements] {
  Parameters: 0, Registers: 3
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: LoadImmediate r2, 1
     8: SetArrayProperty r0, r1, r2
    12: Inc r1
    14: LoadImmediate r2, 2
    17: SetArrayProperty r0, r1, r2
    21: Inc r1
    23: LoadImmediate r2, 3
    26: SetArrayProperty r0, r1, r2
    30: Ret r0
}

[BytecodeFunction: testArrayWithHolesAndElements] {
  Parameters: 0, Registers: 3
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: LoadImmediate r2, 1
     8: SetArrayProperty r0, r1, r2
    12: Inc r1
    14: LoadEmpty r2
    16: SetArrayProperty r0, r1, r2
    20: Inc r1
    22: LoadImmediate r2, 2
    25: SetArrayProperty r0, r1, r2
    29: Inc r1
    31: LoadEmpty r2
    33: SetArrayProperty r0, r1, r2
    37: Inc r1
    39: LoadEmpty r2
    41: SetArrayProperty r0, r1, r2
    45: Inc r1
    47: LoadImmediate r2, 3
    50: SetArrayProperty r0, r1, r2
    54: Inc r1
    56: LoadEmpty r2
    58: SetArrayProperty r0, r1, r2
    62: Ret r0
}

[BytecodeFunction: testArrayWithOnlyHoles] {
  Parameters: 0, Registers: 3
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: LoadEmpty r2
     7: SetArrayProperty r0, r1, r2
    11: Inc r1
    13: LoadEmpty r2
    15: SetArrayProperty r0, r1, r2
    19: Inc r1
    21: LoadEmpty r2
    23: SetArrayProperty r0, r1, r2
    27: Ret r0
}

[BytecodeFunction: onlySpread] {
  Parameters: 1, Registers: 6
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: GetIterator r2, r3, a0
  .L0:
     9: IteratorNext r4, r5, r2, r3
    14: JumpTrue r5, 11 (.L1)
    17: SetArrayProperty r0, r1, r4
    21: Inc r1
    23: Jump -14 (.L0)
  .L1:
    25: Ret r0
}

[BytecodeFunction: multipleSpreads] {
  Parameters: 3, Registers: 6
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: GetIterator r2, r3, a0
  .L0:
     9: IteratorNext r4, r5, r2, r3
    14: JumpTrue r5, 11 (.L1)
    17: SetArrayProperty r0, r1, r4
    21: Inc r1
    23: Jump -14 (.L0)
  .L1:
    25: GetIterator r2, r3, a1
  .L2:
    29: IteratorNext r4, r5, r2, r3
    34: JumpTrue r5, 11 (.L3)
    37: SetArrayProperty r0, r1, r4
    41: Inc r1
    43: Jump -14 (.L2)
  .L3:
    45: LoadImmediate r2, 1
    48: SetArrayProperty r0, r1, r2
    52: Inc r1
    54: GetIterator r2, r3, a2
  .L4:
    58: IteratorNext r4, r5, r2, r3
    63: JumpTrue r5, 11 (.L5)
    66: SetArrayProperty r0, r1, r4
    70: Inc r1
    72: Jump -14 (.L4)
  .L5:
    74: Ret r0
}

[BytecodeFunction: temporaryRegisterToAvoidClobbering] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r0, 1
     3: NewArray r1
     5: LoadImmediate r2, 0
     8: LoadImmediate r3, 2
    11: SetArrayProperty r1, r2, r3
    15: Mov r0, r1
    18: LoadUndefined r1
    20: Ret r1
}

[BytecodeFunction: noTemporaryRegisterNeededForEmptyObject] {
  Parameters: 0, Registers: 2
    0: LoadImmediate r0, 1
    3: NewArray r0
    5: LoadUndefined r1
    7: Ret r1
}
