[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: NewClosure r0, c11
    35: StoreGlobal r0, c12
    38: NewClosure r0, c13
    41: StoreGlobal r0, c14
    44: LoadUndefined r0
    46: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: testEmptyArray]
    2: [String: testEmptyArray]
    3: [BytecodeFunction: testArrayWithOneElement]
    4: [String: testArrayWithOneElement]
    5: [BytecodeFunction: testArrayWithElements]
    6: [String: testArrayWithElements]
    7: [BytecodeFunction: testArrayWithHolesAndElements]
    8: [String: testArrayWithHolesAndElements]
    9: [BytecodeFunction: testArrayWithOnlyHoles]
    10: [String: testArrayWithOnlyHoles]
    11: [BytecodeFunction: onlySpread]
    12: [String: onlySpread]
    13: [BytecodeFunction: multipleSpreads]
    14: [String: multipleSpreads]
}

[BytecodeFunction: testEmptyArray] {
  Parameters: 0, Registers: 1
    0: NewArray r0
    2: Ret r0
}

[BytecodeFunction: testArrayWithOneElement] {
  Parameters: 0, Registers: 3
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: LoadImmediate r2, 1
     8: SetArrayProperty r0, r1, r2
    12: Ret r0
}

[BytecodeFunction: testArrayWithElements] {
  Parameters: 0, Registers: 3
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: LoadImmediate r2, 1
     8: SetArrayProperty r0, r1, r2
    12: Inc r1
    14: LoadImmediate r2, 2
    17: SetArrayProperty r0, r1, r2
    21: Inc r1
    23: LoadImmediate r2, 3
    26: SetArrayProperty r0, r1, r2
    30: Ret r0
}

[BytecodeFunction: testArrayWithHolesAndElements] {
  Parameters: 0, Registers: 3
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: LoadImmediate r2, 1
     8: SetArrayProperty r0, r1, r2
    12: Inc r1
    14: LoadEmpty r2
    16: SetArrayProperty r0, r1, r2
    20: Inc r1
    22: LoadImmediate r2, 2
    25: SetArrayProperty r0, r1, r2
    29: Inc r1
    31: LoadEmpty r2
    33: SetArrayProperty r0, r1, r2
    37: Inc r1
    39: LoadEmpty r2
    41: SetArrayProperty r0, r1, r2
    45: Inc r1
    47: LoadImmediate r2, 3
    50: SetArrayProperty r0, r1, r2
    54: Inc r1
    56: LoadEmpty r2
    58: SetArrayProperty r0, r1, r2
    62: Ret r0
}

[BytecodeFunction: testArrayWithOnlyHoles] {
  Parameters: 0, Registers: 3
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: LoadEmpty r2
     7: SetArrayProperty r0, r1, r2
    11: Inc r1
    13: LoadEmpty r2
    15: SetArrayProperty r0, r1, r2
    19: Inc r1
    21: LoadEmpty r2
    23: SetArrayProperty r0, r1, r2
    27: Ret r0
}

[BytecodeFunction: onlySpread] {
  Parameters: 1, Registers: 6
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: GetIterator r2, r3, a0
  .L0:
     9: IteratorNext r4, r5, r2, r3
    14: JumpTrue r5, 11 (.L1)
    17: SetArrayProperty r0, r1, r4
    21: Inc r1
    23: Jump -14 (.L0)
  .L1:
    25: Ret r0
}

[BytecodeFunction: multipleSpreads] {
  Parameters: 3, Registers: 6
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: GetIterator r2, r3, a0
  .L0:
     9: IteratorNext r4, r5, r2, r3
    14: JumpTrue r5, 11 (.L1)
    17: SetArrayProperty r0, r1, r4
    21: Inc r1
    23: Jump -14 (.L0)
  .L1:
    25: GetIterator r2, r3, a1
  .L2:
    29: IteratorNext r4, r5, r2, r3
    34: JumpTrue r5, 11 (.L3)
    37: SetArrayProperty r0, r1, r4
    41: Inc r1
    43: Jump -14 (.L2)
  .L3:
    45: LoadImmediate r2, 1
    48: SetArrayProperty r0, r1, r2
    52: Inc r1
    54: GetIterator r2, r3, a2
  .L4:
    58: IteratorNext r4, r5, r2, r3
    63: JumpTrue r5, 11 (.L5)
    66: SetArrayProperty r0, r1, r4
    70: Inc r1
    72: Jump -14 (.L4)
  .L5:
    74: Ret r0
}
