[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: LoadUndefined r0
    34: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: testEmptyArray]
    2: [String: testEmptyArray]
    3: [BytecodeFunction: testArrayWithOneElement]
    4: [String: testArrayWithOneElement]
    5: [BytecodeFunction: testArrayWithElements]
    6: [String: testArrayWithElements]
    7: [BytecodeFunction: testArrayWithHolesAndElements]
    8: [String: testArrayWithHolesAndElements]
    9: [BytecodeFunction: testArrayWithOnlyHoles]
    10: [String: testArrayWithOnlyHoles]
}

[BytecodeFunction: testEmptyArray] {
  Parameters: 0, Registers: 1
    0: NewArray r0
    2: Ret r0
}

[BytecodeFunction: testArrayWithOneElement] {
  Parameters: 0, Registers: 3
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: LoadImmediate r2, 1
     8: SetArrayProperty r0, r1, r2
    12: Ret r0
}

[BytecodeFunction: testArrayWithElements] {
  Parameters: 0, Registers: 3
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: LoadImmediate r2, 1
     8: SetArrayProperty r0, r1, r2
    12: Inc r1
    14: LoadImmediate r2, 2
    17: SetArrayProperty r0, r1, r2
    21: Inc r1
    23: LoadImmediate r2, 3
    26: SetArrayProperty r0, r1, r2
    30: Ret r0
}

[BytecodeFunction: testArrayWithHolesAndElements] {
  Parameters: 0, Registers: 3
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: LoadImmediate r2, 1
     8: SetArrayProperty r0, r1, r2
    12: Inc r1
    14: LoadEmpty r2
    16: SetArrayProperty r0, r1, r2
    20: Inc r1
    22: LoadImmediate r2, 2
    25: SetArrayProperty r0, r1, r2
    29: Inc r1
    31: LoadEmpty r2
    33: SetArrayProperty r0, r1, r2
    37: Inc r1
    39: LoadEmpty r2
    41: SetArrayProperty r0, r1, r2
    45: Inc r1
    47: LoadImmediate r2, 3
    50: SetArrayProperty r0, r1, r2
    54: Inc r1
    56: LoadEmpty r2
    58: SetArrayProperty r0, r1, r2
    62: Ret r0
}

[BytecodeFunction: testArrayWithOnlyHoles] {
  Parameters: 0, Registers: 3
     0: NewArray r0
     2: LoadImmediate r1, 0
     5: LoadEmpty r2
     7: SetArrayProperty r0, r1, r2
    11: Inc r1
    13: LoadEmpty r2
    15: SetArrayProperty r0, r1, r2
    19: Inc r1
    21: LoadEmpty r2
    23: SetArrayProperty r0, r1, r2
    27: Ret r0
}
