[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
      0: NewClosure r0, c0
      3: StoreGlobal r0, c1
      6: NewClosure r0, c2
      9: StoreGlobal r0, c3
     12: NewClosure r0, c4
     15: StoreGlobal r0, c5
     18: NewClosure r0, c6
     21: StoreGlobal r0, c7
     24: NewClosure r0, c8
     27: StoreGlobal r0, c9
     30: NewClosure r0, c10
     33: StoreGlobal r0, c11
     36: NewClosure r0, c12
     39: StoreGlobal r0, c13
     42: NewClosure r0, c14
     45: StoreGlobal r0, c15
     48: NewClosure r0, c16
     51: StoreGlobal r0, c17
     54: NewClosure r0, c18
     57: StoreGlobal r0, c19
     60: NewClosure r0, c20
     63: StoreGlobal r0, c21
     66: NewClosure r0, c22
     69: StoreGlobal r0, c23
     72: NewClosure r0, c24
     75: StoreGlobal r0, c25
     78: LoadImmediate r0, 1
     81: StoreGlobal r0, c26
     84: PushLexicalScope c27
     86: NewObject r0
     88: StoreToScope r0, 0, 0
     92: NewClosure r1, c29
     95: DefineNamedProperty r0, c28, r1
     99: NewClosure r1, c31
    102: DefineNamedProperty r0, c30, r1
    106: PopScope 
    107: LoadUndefined r0
    109: Ret r0
  Constant Table:
    0: [BytecodeFunction: use]
    1: [String: use]
    2: [BytecodeFunction: testIdAssign]
    3: [String: testIdAssign]
    4: [BytecodeFunction: testIdAssignReturnValue]
    5: [String: testIdAssignReturnValue]
    6: [BytecodeFunction: testNamedMemberAssign]
    7: [String: testNamedMemberAssign]
    8: [BytecodeFunction: testComputedMemberAssign]
    9: [String: testComputedMemberAssign]
    10: [BytecodeFunction: named]
    11: [String: named]
    12: [BytecodeFunction: operatorIdAssign]
    13: [String: operatorIdAssign]
    14: [BytecodeFunction: operatorIdAssignReturnValue]
    15: [String: operatorIdAssignReturnValue]
    16: [BytecodeFunction: objectDestructuringAssign]
    17: [String: objectDestructuringAssign]
    18: [BytecodeFunction: operatorIdAllOperators]
    19: [String: operatorIdAllOperators]
    20: [BytecodeFunction: operatorMemberAssign]
    21: [String: operatorMemberAssign]
    22: [BytecodeFunction: operatorMemberAllOperators]
    23: [String: operatorMemberAllOperators]
    24: [BytecodeFunction: tdzCheck]
    25: [String: tdzCheck]
    26: [String: global]
    27: [ScopeNames]
    28: [String: testSuperNamedMemberAssign]
    29: [BytecodeFunction: testSuperNamedMemberAssign]
    30: [String: testSuperComputedMemberAssign]
    31: [BytecodeFunction: testSuperComputedMemberAssign]
}

[BytecodeFunction: use] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: testIdAssign] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 2
     3: LoadImmediate a0, 3
     6: LoadImmediate r0, 4
     9: LoadImmediate r1, 5
    12: StoreGlobal r1, c0
    15: LoadUndefined r1
    17: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: testIdAssignReturnValue] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 2
     3: LoadGlobal r1, c0
     6: LoadImmediate a0, 3
     9: Mov r2, a0
    12: Call r1, r1, r2, 1
    17: LoadGlobal r1, c0
    20: LoadImmediate r0, 4
    23: Mov r2, r0
    26: Call r1, r1, r2, 1
    31: LoadGlobal r1, c0
    34: LoadImmediate r2, 5
    37: StoreGlobal r2, c1
    40: Call r1, r1, r2, 1
    45: LoadImmediate r1, 6
    48: StoreGlobal r1, c1
    51: Mov a0, r1
    54: Mov r0, a0
    57: LoadUndefined r1
    59: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: testNamedMemberAssign] {
  Parameters: 2, Registers: 3
     0: LoadImmediate r0, 1
     3: SetNamedProperty a0, c0, r0
     7: LoadGlobal r0, c1
    10: Mov r2, a0
    13: LoadImmediate r1, 2
    16: SetNamedProperty r2, c0, r1
    20: Call r0, r0, r1, 1
    25: Mov r1, a0
    28: Mov r2, a0
    31: LoadImmediate r0, 3
    34: SetNamedProperty r2, c2, r0
    38: SetNamedProperty r1, c0, r0
    42: LoadGlobal r0, c1
    45: Mov r2, a0
    48: Mov r1, a0
    51: SetNamedProperty r2, c0, r1
    55: Call r0, r0, r1, 1
    60: Mov r1, a0
    63: LoadImmediate r0, 4
    66: SetNamedProperty r1, c0, r0
    70: Mov a1, r0
    73: LoadUndefined r0
    75: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: testComputedMemberAssign] {
  Parameters: 2, Registers: 5
     0: LoadConstant r1, c0
     3: LoadImmediate r0, 1
     6: SetProperty a0, r1, r0
    10: LoadGlobal r0, c1
    13: Mov r2, a0
    16: LoadConstant r3, c0
    19: LoadImmediate r1, 2
    22: SetProperty r2, r3, r1
    26: Call r0, r0, r1, 1
    31: Mov r1, a0
    34: LoadConstant r2, c0
    37: Mov r3, a0
    40: LoadConstant r4, c2
    43: LoadImmediate r0, 3
    46: SetProperty r3, r4, r0
    50: SetProperty r1, r2, r0
    54: LoadGlobal r0, c1
    57: Mov r2, a0
    60: LoadConstant r3, c0
    63: Mov r1, a0
    66: SetProperty r2, r3, r1
    70: Call r0, r0, r1, 1
    75: Mov r1, a0
    78: LoadConstant r2, c0
    81: LoadImmediate r0, 4
    84: SetProperty r1, r2, r0
    88: Mov a1, r0
    91: LoadUndefined r0
    93: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: testSuperNamedMemberAssign] {
  Parameters: 1, Registers: 5
      0: LoadFromScope r1, 0, 0
      4: LoadConstant r2, c0
      7: LoadImmediate r0, 1
     10: SetSuperProperty r1, <this>, r2, r0
     15: LoadGlobal r0, c1
     18: LoadFromScope r2, 0, 0
     22: LoadConstant r3, c0
     25: LoadImmediate r1, 2
     28: SetSuperProperty r2, <this>, r3, r1
     33: Call r0, r0, r1, 1
     38: LoadFromScope r1, 0, 0
     42: LoadConstant r2, c0
     45: LoadFromScope r3, 0, 0
     49: LoadConstant r4, c2
     52: LoadImmediate r0, 3
     55: SetSuperProperty r3, <this>, r4, r0
     60: SetSuperProperty r1, <this>, r2, r0
     65: LoadGlobal r0, c1
     68: LoadFromScope r2, 0, 0
     72: LoadConstant r3, c0
     75: Mov r1, a0
     78: SetSuperProperty r2, <this>, r3, r1
     83: Call r0, r0, r1, 1
     88: LoadFromScope r1, 0, 0
     92: LoadConstant r2, c0
     95: LoadImmediate r0, 4
     98: SetSuperProperty r1, <this>, r2, r0
    103: Mov a0, r0
    106: LoadUndefined r0
    108: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: testSuperComputedMemberAssign] {
  Parameters: 1, Registers: 5
      0: LoadFromScope r1, 0, 0
      4: LoadConstant r2, c0
      7: LoadImmediate r0, 1
     10: SetSuperProperty r1, <this>, r2, r0
     15: LoadGlobal r0, c1
     18: LoadFromScope r2, 0, 0
     22: LoadConstant r3, c0
     25: LoadImmediate r1, 2
     28: SetSuperProperty r2, <this>, r3, r1
     33: Call r0, r0, r1, 1
     38: LoadFromScope r1, 0, 0
     42: LoadConstant r2, c0
     45: LoadFromScope r3, 0, 0
     49: LoadConstant r4, c2
     52: LoadImmediate r0, 3
     55: SetSuperProperty r3, <this>, r4, r0
     60: SetSuperProperty r1, <this>, r2, r0
     65: LoadGlobal r0, c1
     68: LoadFromScope r2, 0, 0
     72: LoadConstant r3, c0
     75: Mov r1, a0
     78: SetSuperProperty r2, <this>, r3, r1
     83: Call r0, r0, r1, 1
     88: LoadFromScope r1, 0, 0
     92: LoadConstant r2, c0
     95: LoadImmediate r0, 4
     98: SetSuperProperty r1, <this>, r2, r0
    103: Mov a0, r0
    106: LoadUndefined r0
    108: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: named] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: NewClosure r0, c0
     6: NewClosure r0, c1
     9: NewClosure r1, c3
    12: SetNamedProperty r0, c2, r1
    16: NewClosure r1, c4
    19: Add r0, r0, r1, fb0
    24: LoadUndefined r1
    26: Ret r1
  Constant Table:
    0: [BytecodeFunction: x]
    1: [BytecodeFunction: <anonymous>]
    2: [String: foo]
    3: [BytecodeFunction: <anonymous>]
    4: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: x] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: operatorIdAssign] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 2
     3: LoadImmediate r1, 3
     6: Add a0, a0, r1, fb0
    11: LoadImmediate r1, 4
    14: Add r0, r0, r1, fb1
    19: LoadGlobal r1, c0
    22: LoadImmediate r2, 5
    25: Add r1, r1, r2, fb2
    30: StoreGlobal r1, c0
    33: LoadUndefined r1
    35: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: operatorIdAssignReturnValue] {
  Parameters: 1, Registers: 5
      0: LoadImmediate r0, 2
      3: LoadGlobal r1, c0
      6: Mov r2, a0
      9: LoadImmediate r3, 3
     12: Add a0, r2, r3, fb0
     17: Mov r2, a0
     20: Call r1, r1, r2, 1
     25: LoadGlobal r1, c0
     28: Mov r2, r0
     31: LoadImmediate r3, 4
     34: Add r0, r2, r3, fb1
     39: Mov r2, r0
     42: Call r1, r1, r2, 1
     47: LoadGlobal r1, c0
     50: LoadGlobal r2, c1
     53: LoadImmediate r3, 5
     56: Add r2, r2, r3, fb2
     61: StoreGlobal r2, c1
     64: Call r1, r1, r2, 1
     69: Mov r1, r0
     72: Mov r2, a0
     75: LoadGlobal r3, c1
     78: LoadImmediate r4, 6
     81: Add r3, r3, r4, fb3
     86: StoreGlobal r3, c1
     89: Add a0, r2, r3, fb4
     94: Add r0, r1, a0, fb5
     99: LoadUndefined r1
    101: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: objectDestructuringAssign] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r2, 1
     3: GetNamedProperty r1, r2, c0
     7: LoadImmediate r2, 2
    10: GetNamedProperty r1, r2, c0
    14: Mov a0, r2
    17: LoadImmediate r2, 3
    20: GetNamedProperty r1, r2, c0
    24: Mov r0, r2
    27: LoadImmediate r2, 4
    30: GetNamedProperty r1, r2, c0
    34: StoreGlobal r2, c1
    37: LoadUndefined r2
    39: Ret r2
  Constant Table:
    0: [String: a]
    1: [String: global]
}

[BytecodeFunction: operatorIdAllOperators] {
  Parameters: 1, Registers: 1
     0: LoadImmediate r0, 1
     3: Add a0, a0, r0, fb0
     8: LoadImmediate r0, 2
    11: Sub a0, a0, r0
    15: LoadImmediate r0, 3
    18: Mul a0, a0, r0
    22: LoadImmediate r0, 4
    25: Div a0, a0, r0
    29: LoadImmediate r0, 5
    32: Rem a0, a0, r0
    36: LoadImmediate r0, 6
    39: Exp a0, a0, r0
    43: LoadImmediate r0, 7
    46: BitAnd a0, a0, r0
    50: LoadImmediate r0, 8
    53: BitOr a0, a0, r0
    57: LoadImmediate r0, 9
    60: BitXor a0, a0, r0
    64: LoadImmediate r0, 10
    67: ShiftLeft a0, a0, r0
    71: LoadImmediate r0, 11
    74: ShiftRightArithmetic a0, a0, r0
    78: LoadImmediate r0, 12
    81: ShiftRightLogical a0, a0, r0
    85: LoadUndefined r0
    87: Ret r0
}

[BytecodeFunction: operatorMemberAssign] {
  Parameters: 2, Registers: 5
      0: GetNamedProperty r0, a0, c0
      4: LoadImmediate r1, 1
      7: Add r0, r0, r1, fb0
     12: SetNamedProperty a0, c0, r0
     16: LoadGlobal r0, c1
     19: Mov r2, a0
     22: GetNamedProperty r1, r2, c0
     26: LoadImmediate r3, 2
     29: Add r1, r1, r3, fb1
     34: SetNamedProperty r2, c0, r1
     38: Call r0, r0, r1, 1
     43: Mov r1, a0
     46: GetNamedProperty r0, r1, c0
     50: Mov r3, a0
     53: GetNamedProperty r2, r3, c2
     57: LoadImmediate r4, 3
     60: Add r2, r2, r4, fb2
     65: SetNamedProperty r3, c2, r2
     69: Add r0, r0, r2, fb3
     74: SetNamedProperty r1, c0, r0
     78: LoadGlobal r0, c1
     81: Mov r2, a0
     84: GetNamedProperty r1, r2, c0
     88: Mov r3, a0
     91: Add r1, r1, r3, fb4
     96: SetNamedProperty r2, c0, r1
    100: Call r0, r0, r1, 1
    105: Mov r1, a0
    108: GetNamedProperty r0, r1, c0
    112: LoadImmediate r2, 4
    115: Add r0, r0, r2, fb5
    120: SetNamedProperty r1, c0, r0
    124: Mov a1, r0
    127: LoadUndefined r0
    129: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: operatorMemberAllOperators] {
  Parameters: 1, Registers: 2
      0: GetNamedProperty r0, a0, c0
      4: LoadImmediate r1, 1
      7: Add r0, r0, r1, fb0
     12: SetNamedProperty a0, c0, r0
     16: GetNamedProperty r0, a0, c0
     20: LoadImmediate r1, 2
     23: Sub r0, r0, r1
     27: SetNamedProperty a0, c0, r0
     31: GetNamedProperty r0, a0, c0
     35: LoadImmediate r1, 3
     38: Mul r0, r0, r1
     42: SetNamedProperty a0, c0, r0
     46: GetNamedProperty r0, a0, c0
     50: LoadImmediate r1, 4
     53: Div r0, r0, r1
     57: SetNamedProperty a0, c0, r0
     61: GetNamedProperty r0, a0, c0
     65: LoadImmediate r1, 5
     68: Rem r0, r0, r1
     72: SetNamedProperty a0, c0, r0
     76: GetNamedProperty r0, a0, c0
     80: LoadImmediate r1, 6
     83: Exp r0, r0, r1
     87: SetNamedProperty a0, c0, r0
     91: GetNamedProperty r0, a0, c0
     95: LoadImmediate r1, 7
     98: BitAnd r0, r0, r1
    102: SetNamedProperty a0, c0, r0
    106: GetNamedProperty r0, a0, c0
    110: LoadImmediate r1, 8
    113: BitOr r0, r0, r1
    117: SetNamedProperty a0, c0, r0
    121: GetNamedProperty r0, a0, c0
    125: LoadImmediate r1, 9
    128: BitXor r0, r0, r1
    132: SetNamedProperty a0, c0, r0
    136: GetNamedProperty r0, a0, c0
    140: LoadImmediate r1, 10
    143: ShiftLeft r0, r0, r1
    147: SetNamedProperty a0, c0, r0
    151: GetNamedProperty r0, a0, c0
    155: LoadImmediate r1, 11
    158: ShiftRightArithmetic r0, r0, r1
    162: SetNamedProperty a0, c0, r0
    166: GetNamedProperty r0, a0, c0
    170: LoadImmediate r1, 12
    173: ShiftRightLogical r0, r0, r1
    177: SetNamedProperty a0, c0, r0
    181: LoadUndefined r0
    183: Ret r0
  Constant Table:
    0: [String: foo]
}

[BytecodeFunction: tdzCheck] {
  Parameters: 0, Registers: 4
     0: PushFunctionScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: NewClosure r0, c1
    11: LoadImmediate r1, 0
    14: StoreToScope r1, 0, 0
    18: LoadImmediate r1, 1
    21: LoadFromScope r2, 0, 0
    25: CheckTdz r2, c2
    28: StoreToScope r1, 0, 0
    32: LoadImmediate r1, 2
    35: GetNamedProperty r2, r1, c2
    39: LoadFromScope r3, 0, 0
    43: CheckTdz r3, c2
    46: StoreToScope r2, 0, 0
    50: LoadUndefined r1
    52: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner]
    2: [String: x]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: LoadUndefined r0
    9: Ret r0
  Constant Table:
    0: [String: x]
}
