[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: StoreGlobal r0, c0
     6: NewClosure r0, c1
     9: StoreGlobal r0, c2
    12: NewClosure r0, c3
    15: StoreGlobal r0, c4
    18: NewClosure r0, c5
    21: StoreGlobal r0, c6
    24: NewClosure r0, c7
    27: StoreGlobal r0, c8
    30: NewClosure r0, c9
    33: StoreGlobal r0, c10
    36: NewClosure r0, c11
    39: StoreGlobal r0, c12
    42: NewClosure r0, c13
    45: StoreGlobal r0, c14
    48: NewClosure r0, c15
    51: StoreGlobal r0, c16
    54: NewClosure r0, c17
    57: StoreGlobal r0, c18
    60: NewClosure r0, c19
    63: StoreGlobal r0, c20
    66: NewClosure r0, c21
    69: StoreGlobal r0, c22
    72: LoadUndefined r0
    74: Ret r0
  Constant Table:
    0: [String: global]
    1: [BytecodeFunction: use]
    2: [String: use]
    3: [BytecodeFunction: testIdAssign]
    4: [String: testIdAssign]
    5: [BytecodeFunction: testIdAssignReturnValue]
    6: [String: testIdAssignReturnValue]
    7: [BytecodeFunction: testNamedMemberAssign]
    8: [String: testNamedMemberAssign]
    9: [BytecodeFunction: testComputedMemberAssign]
    10: [String: testComputedMemberAssign]
    11: [BytecodeFunction: named]
    12: [String: named]
    13: [BytecodeFunction: operatorIdAssign]
    14: [String: operatorIdAssign]
    15: [BytecodeFunction: operatorIdAssignReturnValue]
    16: [String: operatorIdAssignReturnValue]
    17: [BytecodeFunction: operatorIdAllOperators]
    18: [String: operatorIdAllOperators]
    19: [BytecodeFunction: operatorMemberAssign]
    20: [String: operatorMemberAssign]
    21: [BytecodeFunction: operatorMemberAllOperators]
    22: [String: operatorMemberAllOperators]
}

[BytecodeFunction: use] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: testIdAssign] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 2
     3: LoadImmediate a0, 3
     6: LoadImmediate r0, 4
     9: LoadImmediate r1, 5
    12: StoreGlobal r1, c0
    15: LoadUndefined r1
    17: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: testIdAssignReturnValue] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 2
     3: LoadGlobal r1, c0
     6: LoadImmediate a0, 3
     9: Mov r2, a0
    12: Call r1, r1, r2, 1
    17: LoadGlobal r1, c0
    20: LoadImmediate r0, 4
    23: Mov r2, r0
    26: Call r1, r1, r2, 1
    31: LoadGlobal r1, c0
    34: LoadImmediate r2, 5
    37: StoreGlobal r2, c1
    40: Call r1, r1, r2, 1
    45: LoadImmediate r1, 6
    48: StoreGlobal r1, c1
    51: Mov a0, r1
    54: Mov r0, a0
    57: LoadUndefined r1
    59: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: testNamedMemberAssign] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: SetNamedProperty a0, c0, r0
     7: LoadGlobal r0, c1
    10: LoadImmediate r1, 2
    13: SetNamedProperty a0, c0, r1
    17: Call r0, r0, r1, 1
    22: LoadImmediate r0, 3
    25: SetNamedProperty a0, c2, r0
    29: SetNamedProperty a0, c0, r0
    33: LoadGlobal r0, c1
    36: Mov r1, a0
    39: SetNamedProperty a0, c0, r1
    43: Call r0, r0, r1, 1
    48: LoadUndefined r0
    50: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: testComputedMemberAssign] {
  Parameters: 1, Registers: 3
     0: LoadConstant r1, c0
     3: LoadImmediate r0, 1
     6: SetProperty a0, r1, r0
    10: LoadGlobal r0, c1
    13: LoadConstant r2, c0
    16: LoadImmediate r1, 2
    19: SetProperty a0, r2, r1
    23: Call r0, r0, r1, 1
    28: LoadConstant r1, c0
    31: LoadConstant r2, c2
    34: LoadImmediate r0, 3
    37: SetProperty a0, r2, r0
    41: SetProperty a0, r1, r0
    45: LoadGlobal r0, c1
    48: LoadConstant r2, c0
    51: Mov r1, a0
    54: SetProperty a0, r2, r1
    58: Call r0, r0, r1, 1
    63: LoadUndefined r0
    65: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: named] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: NewClosure r0, c0
     6: NewClosure r0, c1
     9: NewClosure r1, c3
    12: SetNamedProperty r0, c2, r1
    16: NewClosure r1, c4
    19: Add r0, r0, r1
    23: LoadUndefined r1
    25: Ret r1
  Constant Table:
    0: [BytecodeFunction: x]
    1: [BytecodeFunction: <anonymous>]
    2: [String: foo]
    3: [BytecodeFunction: <anonymous>]
    4: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: x] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: operatorIdAssign] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 2
     3: LoadImmediate r1, 3
     6: Add a0, a0, r1
    10: LoadImmediate r1, 4
    13: Add r0, r0, r1
    17: LoadGlobal r1, c0
    20: LoadImmediate r2, 5
    23: Add r1, r1, r2
    27: StoreGlobal r1, c0
    30: LoadUndefined r1
    32: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: operatorIdAssignReturnValue] {
  Parameters: 1, Registers: 4
     0: LoadImmediate r0, 2
     3: LoadGlobal r1, c0
     6: LoadImmediate r2, 3
     9: Add a0, a0, r2
    13: Mov r2, a0
    16: Call r1, r1, r2, 1
    21: LoadGlobal r1, c0
    24: LoadImmediate r2, 4
    27: Add r0, r0, r2
    31: Mov r2, r0
    34: Call r1, r1, r2, 1
    39: LoadGlobal r1, c0
    42: LoadGlobal r2, c1
    45: LoadImmediate r3, 5
    48: Add r2, r2, r3
    52: StoreGlobal r2, c1
    55: Call r1, r1, r2, 1
    60: LoadGlobal r1, c1
    63: LoadImmediate r2, 6
    66: Add r1, r1, r2
    70: StoreGlobal r1, c1
    73: Add a0, a0, r1
    77: Add r0, r0, a0
    81: LoadUndefined r1
    83: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: operatorIdAllOperators] {
  Parameters: 1, Registers: 1
     0: LoadImmediate r0, 1
     3: Add a0, a0, r0
     7: LoadImmediate r0, 2
    10: Sub a0, a0, r0
    14: LoadImmediate r0, 3
    17: Mul a0, a0, r0
    21: LoadImmediate r0, 4
    24: Div a0, a0, r0
    28: LoadImmediate r0, 5
    31: Rem a0, a0, r0
    35: LoadImmediate r0, 6
    38: Exp a0, a0, r0
    42: LoadImmediate r0, 7
    45: BitAnd a0, a0, r0
    49: LoadImmediate r0, 8
    52: BitOr a0, a0, r0
    56: LoadImmediate r0, 9
    59: BitXor a0, a0, r0
    63: LoadImmediate r0, 10
    66: ShiftLeft a0, a0, r0
    70: LoadImmediate r0, 11
    73: ShiftRightArithmetic a0, a0, r0
    77: LoadImmediate r0, 12
    80: ShiftRightLogical a0, a0, r0
    84: LoadUndefined r0
    86: Ret r0
}

[BytecodeFunction: operatorMemberAssign] {
  Parameters: 1, Registers: 3
     0: GetNamedProperty r0, a0, c0
     4: LoadImmediate r1, 1
     7: Add r0, r0, r1
    11: SetNamedProperty a0, c0, r0
    15: LoadGlobal r0, c1
    18: GetNamedProperty r1, a0, c0
    22: LoadImmediate r2, 2
    25: Add r1, r1, r2
    29: SetNamedProperty a0, c0, r1
    33: Call r0, r0, r1, 1
    38: GetNamedProperty r0, a0, c0
    42: GetNamedProperty r1, a0, c2
    46: LoadImmediate r2, 3
    49: Add r1, r1, r2
    53: SetNamedProperty a0, c2, r1
    57: Add r0, r0, r1
    61: SetNamedProperty a0, c0, r0
    65: LoadGlobal r0, c1
    68: GetNamedProperty r1, a0, c0
    72: Add r1, r1, a0
    76: SetNamedProperty a0, c0, r1
    80: Call r0, r0, r1, 1
    85: LoadUndefined r0
    87: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: use]
    2: [String: bar]
}

[BytecodeFunction: operatorMemberAllOperators] {
  Parameters: 1, Registers: 2
      0: GetNamedProperty r0, a0, c0
      4: LoadImmediate r1, 1
      7: Add r0, r0, r1
     11: SetNamedProperty a0, c0, r0
     15: GetNamedProperty r0, a0, c0
     19: LoadImmediate r1, 2
     22: Sub r0, r0, r1
     26: SetNamedProperty a0, c0, r0
     30: GetNamedProperty r0, a0, c0
     34: LoadImmediate r1, 3
     37: Mul r0, r0, r1
     41: SetNamedProperty a0, c0, r0
     45: GetNamedProperty r0, a0, c0
     49: LoadImmediate r1, 4
     52: Div r0, r0, r1
     56: SetNamedProperty a0, c0, r0
     60: GetNamedProperty r0, a0, c0
     64: LoadImmediate r1, 5
     67: Rem r0, r0, r1
     71: SetNamedProperty a0, c0, r0
     75: GetNamedProperty r0, a0, c0
     79: LoadImmediate r1, 6
     82: Exp r0, r0, r1
     86: SetNamedProperty a0, c0, r0
     90: GetNamedProperty r0, a0, c0
     94: LoadImmediate r1, 7
     97: BitAnd r0, r0, r1
    101: SetNamedProperty a0, c0, r0
    105: GetNamedProperty r0, a0, c0
    109: LoadImmediate r1, 8
    112: BitOr r0, r0, r1
    116: SetNamedProperty a0, c0, r0
    120: GetNamedProperty r0, a0, c0
    124: LoadImmediate r1, 9
    127: BitXor r0, r0, r1
    131: SetNamedProperty a0, c0, r0
    135: GetNamedProperty r0, a0, c0
    139: LoadImmediate r1, 10
    142: ShiftLeft r0, r0, r1
    146: SetNamedProperty a0, c0, r0
    150: GetNamedProperty r0, a0, c0
    154: LoadImmediate r1, 11
    157: ShiftRightArithmetic r0, r0, r1
    161: SetNamedProperty a0, c0, r0
    165: GetNamedProperty r0, a0, c0
    169: LoadImmediate r1, 12
    172: ShiftRightLogical r0, r0, r1
    176: SetNamedProperty a0, c0, r0
    180: LoadUndefined r0
    182: Ret r0
  Constant Table:
    0: [String: foo]
}
