[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: GlobalInit c2
     8: LoadUndefined r0
    10: Ret r0
  Constant Table:
    0: [BytecodeFunction: test1]
    1: [String: test1]
    2: [GlobalNames]
}

[BytecodeFunction: test1] {
  Parameters: 2, Registers: 1
     0: Add r0, a0, a1
     4: Sub r0, a0, a1
     8: Mul r0, a0, a1
    12: Div r0, a0, a1
    16: Rem r0, a0, a1
    20: Exp r0, a0, a1
    24: LooseEqual r0, a0, a1
    28: LooseNotEqual r0, a0, a1
    32: StrictEqual r0, a0, a1
    36: StrictNotEqual r0, a0, a1
    40: LessThan r0, a0, a1
    44: LessThanOrEqual r0, a0, a1
    48: GreaterThan r0, a0, a1
    52: GreaterThanOrEqual r0, a0, a1
    56: BitAnd r0, a0, a1
    60: BitOr r0, a0, a1
    64: BitXor r0, a0, a1
    68: ShiftLeft r0, a0, a1
    72: ShiftRightArithmetic r0, a0, a1
    76: ShiftRightLogical r0, a0, a1
    80: LoadConstant r0, c0
    83: In r0, a1, r0
    87: InstanceOf r0, a0, a1
    91: LoadUndefined r0
    93: Ret r0
  Constant Table:
    0: [String: x]
}
