[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: StoreGlobal r0, c1
    6: LoadUndefined r0
    8: Ret r0
  Constant Table:
    0: [BytecodeFunction: test1]
    1: [String: test1]
}

[BytecodeFunction: test1] {
  Parameters: 2, Registers: 1
     0: Add r0, a0, a1
     4: Sub r0, a0, a1
     8: LessThan r0, a0, a1
    12: LoadUndefined r0
    14: Ret r0
}
