[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: LoadUndefined r0
    14: Ret r0
  Constant Table:
    0: [BytecodeFunction: testBasic]
    1: [String: testBasic]
    2: [BytecodeFunction: testBooleanCondition]
    3: [String: testBooleanCondition]
}

[BytecodeFunction: testBasic] {
  Parameters: 0, Registers: 4
      0: LoadImmediate r0, 1
      3: JumpToBooleanFalse r0, 8 (.L0)
      6: LoadImmediate r0, 2
      9: Jump 5 (.L1)
  .L0:
     11: LoadImmediate r0, 3
  .L1:
     14: LoadImmediate r0, 1
     17: LoadImmediate r1, 2
     20: Add r0, r0, r1, fb0
     25: JumpToBooleanFalse r0, 16 (.L2)
     28: LoadImmediate r1, 3
     31: LoadImmediate r2, 4
     34: Add r0, r1, r2, fb1
     39: Jump 13 (.L3)
  .L2:
     41: LoadImmediate r1, 5
     44: LoadImmediate r2, 6
     47: Add r0, r1, r2, fb2
  .L3:
     52: LoadGlobal r0, c0
     55: LoadImmediate r1, 1
     58: JumpToBooleanFalse r1, 16 (.L4)
     61: LoadImmediate r2, 2
     64: LoadImmediate r3, 3
     67: Add r1, r2, r3, fb3
     72: Jump 21 (.L5)
  .L4:
     74: LoadImmediate r2, 4
     77: LoadImmediate r3, 5
     80: Add r2, r2, r3, fb4
     85: LoadImmediate r3, 6
     88: Add r1, r2, r3, fb5
  .L5:
     93: Call r0, r0, r1, 1
     98: LoadUndefined r0
    100: Ret r0
  Constant Table:
    0: [String: use]
}

[BytecodeFunction: testBooleanCondition] {
  Parameters: 0, Registers: 1
     0: LoadTrue r0
     2: JumpFalse r0, 8 (.L0)
     5: LoadImmediate r0, 1
     8: Jump 5 (.L1)
  .L0:
    10: LoadImmediate r0, 2
  .L1:
    13: LoadUndefined r0
    15: Ret r0
}
