[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: NewClosure r0, c14
    45: StoreGlobal r0, c15
    48: NewClosure r0, c16
    51: StoreGlobal r0, c17
    54: NewClosure r0, c18
    57: StoreGlobal r0, c19
    60: NewClosure r0, c20
    63: StoreGlobal r0, c21
    66: LoadImmediate r0, 1
    69: StoreGlobal r0, c22
    72: PushLexicalScope c23
    74: NewObject r0
    76: StoreToScope r0, 0, 0
    80: NewClosure r1, c25
    83: DefineNamedProperty r0, c24, r1
    87: NewClosure r1, c27
    90: DefineNamedProperty r0, c26, r1
    94: PopScope 
    95: LoadUndefined r0
    97: Ret r0
  Constant Table:
    0: [BytecodeFunction: deleteMember]
    1: [String: deleteMember]
    2: [BytecodeFunction: deleteChainMember]
    3: [String: deleteChainMember]
    4: [BytecodeFunction: deleteOtherExpression]
    5: [String: deleteOtherExpression]
    6: [BytecodeFunction: deleteIdVars]
    7: [String: deleteIdVars]
    8: [BytecodeFunction: deleteIdFunctions]
    9: [String: deleteIdFunctions]
    10: [BytecodeFunction: deleteIdLexical]
    11: [String: deleteIdLexical]
    12: [BytecodeFunction: deleteIdParams]
    13: [String: deleteIdParams]
    14: [BytecodeFunction: deleteIdArgments]
    15: [String: deleteIdArgments]
    16: [BytecodeFunction: deleteThis]
    17: [String: deleteThis]
    18: [BytecodeFunction: deleteUnresolvedGlobal]
    19: [String: deleteUnresolvedGlobal]
    20: [BytecodeFunction: deleteUnresolvedDynamic]
    21: [String: deleteUnresolvedDynamic]
    22: [String: globalVar]
    23: [ScopeNames]
    24: [String: deleteNamedSuperProperty]
    25: [BytecodeFunction: deleteNamedSuperProperty]
    26: [String: deleteComputedSuperProperty]
    27: [BytecodeFunction: deleteComputedSuperProperty]
}

[BytecodeFunction: deleteMember] {
  Parameters: 1, Registers: 2
     0: LoadConstant r0, c0
     3: DeleteProperty r0, a0, r0
     7: GetNamedProperty r0, a0, c1
    11: LoadConstant r1, c0
    14: DeleteProperty r0, r0, r1
    18: LoadImmediate r0, 1
    21: DeleteProperty r0, a0, r0
    25: LoadUndefined r0
    27: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: inner]
}

[BytecodeFunction: deleteChainMember] {
  Parameters: 1, Registers: 2
     0: JumpNullish a0, 12 (.L0)
     3: LoadConstant r0, c0
     6: DeleteProperty r0, a0, r0
    10: Jump 4 (.L1)
  .L0:
    12: LoadTrue r0
  .L1:
    14: JumpNullish a0, 12 (.L2)
    17: LoadImmediate r0, 1
    20: DeleteProperty r0, a0, r0
    24: Jump 4 (.L3)
  .L2:
    26: LoadTrue r0
  .L3:
    28: JumpNullish a0, 23 (.L4)
    31: GetNamedProperty r0, a0, c0
    35: GetNamedProperty r0, r0, c1
    39: JumpNullish r0, 12 (.L4)
    42: LoadConstant r1, c2
    45: DeleteProperty r0, r0, r1
    49: Jump 4 (.L5)
  .L4:
    51: LoadTrue r0
  .L5:
    53: LoadUndefined r0
    55: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: bar]
    2: [String: baz]
}

[BytecodeFunction: deleteOtherExpression] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r0, 1
     8: LoadImmediate r1, 2
    11: Add r0, r0, r1
    15: LoadTrue r0
    17: LoadUndefined r0
    19: Ret r0
}

[BytecodeFunction: deleteIdVars] {
  Parameters: 1, Registers: 2
    0: LoadImmediate r0, 1
    3: LoadFalse r1
    5: LoadFalse r1
    7: LoadUndefined r1
    9: Ret r1
}

[BytecodeFunction: deleteIdFunctions] {
  Parameters: 0, Registers: 2
    0: NewClosure r0, c0
    3: LoadFalse r1
    5: LoadFalse r1
    7: LoadUndefined r1
    9: Ret r1
  Constant Table:
    0: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: deleteIdLexical] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r0, 1
     3: LoadImmediate r1, 2
     6: LoadFalse r2
     8: LoadFalse r2
    10: LoadUndefined r2
    12: Ret r2
}

[BytecodeFunction: deleteIdParams] {
  Parameters: 1, Registers: 3
     0: LoadFalse r1
     2: Mov r1, <scope>
     5: LoadImmediate r2, 1
     8: Jump 7 (.L0)
    10: Mov <scope>, r1
    13: LoadFalse r2
  .L0:
    15: LoadUndefined r1
    17: Ret r1
  Exception Handlers:
    5-8 -> 10 (r0)
}

[BytecodeFunction: deleteIdArgments] {
  Parameters: 0, Registers: 2
    0: NewMappedArguments r0
    2: LoadFalse r1
    4: LoadUndefined r1
    6: Ret r1
}

[BytecodeFunction: deleteThis] {
  Parameters: 0, Registers: 1
    0: LoadTrue r0
    2: LoadUndefined r0
    4: Ret r0
}

[BytecodeFunction: deleteUnresolvedGlobal] {
  Parameters: 0, Registers: 1
    0: DeleteBinding r0, c0
    3: LoadUndefined r0
    5: Ret r0
  Constant Table:
    0: [String: unresolved]
}

[BytecodeFunction: deleteUnresolvedDynamic] {
  Parameters: 0, Registers: 2
     0: PushFunctionScope c0
     2: StoreToScope <this>, 0, 0
     6: StoreToScope r0, 2, 0
    10: NewMappedArguments r0
    12: StoreToScope r0, 1, 0
    16: LoadDynamic r0, c1
    19: LoadConstant r1, c2
    22: CallMaybeEval r0, r0, r1, 1, 1
    28: DeleteBinding r0, c3
    31: LoadUndefined r0
    33: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [String: eval]
    2: [String: ]
    3: [String: unresolved]
}

[BytecodeFunction: deleteNamedSuperProperty] {
  Parameters: 0, Registers: 1
    0: ErrorDeleteSuperProperty 
    1: Ret r0
}

[BytecodeFunction: deleteComputedSuperProperty] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadImmediate r1, 2
     6: Add r0, r0, r1
    10: ErrorDeleteSuperProperty 
    11: Ret r0
}
