[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: GlobalInit c6
    20: LoadUndefined r0
    22: Ret r0
  Constant Table:
    0: [BytecodeFunction: deleteMember]
    1: [String: deleteMember]
    2: [BytecodeFunction: deleteChainMember]
    3: [String: deleteChainMember]
    4: [BytecodeFunction: deleteOtherExpression]
    5: [String: deleteOtherExpression]
    6: [GlobalNames]
}

[BytecodeFunction: deleteMember] {
  Parameters: 1, Registers: 2
     0: LoadConstant r0, c0
     3: DeleteProperty r0, a0, r0
     7: GetNamedProperty r0, a0, c1
    11: LoadConstant r1, c0
    14: DeleteProperty r0, r0, r1
    18: LoadImmediate r0, 1
    21: DeleteProperty r0, a0, r0
    25: LoadUndefined r0
    27: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: inner]
}

[BytecodeFunction: deleteChainMember] {
  Parameters: 1, Registers: 2
     0: JumpNullish a0, 12 (.L0)
     3: LoadConstant r0, c0
     6: DeleteProperty r0, a0, r0
    10: Jump 4 (.L1)
  .L0:
    12: LoadTrue r0
  .L1:
    14: JumpNullish a0, 12 (.L2)
    17: LoadImmediate r0, 1
    20: DeleteProperty r0, a0, r0
    24: Jump 4 (.L3)
  .L2:
    26: LoadTrue r0
  .L3:
    28: JumpNullish a0, 23 (.L4)
    31: GetNamedProperty r0, a0, c0
    35: GetNamedProperty r0, r0, c1
    39: JumpNullish r0, 12 (.L4)
    42: LoadConstant r1, c2
    45: DeleteProperty r0, r0, r1
    49: Jump 4 (.L5)
  .L4:
    51: LoadTrue r0
  .L5:
    53: LoadUndefined r0
    55: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: bar]
    2: [String: baz]
}

[BytecodeFunction: deleteOtherExpression] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r0, 1
     8: LoadImmediate r1, 2
    11: Add r0, r0, r1
    15: LoadTrue r0
    17: LoadUndefined r0
    19: Ret r0
}
