[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: StoreGlobal r0, c1
    6: LoadUndefined r0
    8: Ret r0
  Constant Table:
    0: [BytecodeFunction: test]
    1: [String: test]
}

[BytecodeFunction: test] {
  Parameters: 2, Registers: 1
     0: LoadFalse r0
     2: JumpFalse r0, 8 (.L0)
     5: LoadImmediate r0, 1
     8: Ret r0
  .L0:
    10: LessThan r0, a0, a1
    14: JumpFalse r0, 8 (.L1)
    17: LoadImmediate r0, 2
    20: Ret r0
  .L1:
    22: LoadUndefined r0
    24: Ret r0
}
