[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: LoadUndefined r0
    34: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: basic]
    2: [String: basic]
    3: [BytecodeFunction: named]
    4: [String: named]
    5: [BytecodeFunction: namedCaptured]
    6: [String: namedCaptured]
    7: [BytecodeFunction: namedVarOverwrite]
    8: [String: namedVarOverwrite]
    9: [BytecodeFunction: namedLexOverwrite]
    10: [String: namedLexOverwrite]
}

[BytecodeFunction: basic] {
  Parameters: 0, Registers: 3
     0: NewClosure r1, c0
     3: LoadImmediate r2, 2
     6: Add r1, r1, r2
    10: NewClosure r1, c1
    13: LoadImmediate r2, 4
    16: Add r1, r1, r2
    20: NewClosure r0, c2
    23: LoadUndefined r1
    25: Ret r1
  Constant Table:
    0: [BytecodeFunction: foo]
    1: [BytecodeFunction: <anonymous>]
    2: [BytecodeFunction: x]
}

[BytecodeFunction: foo] {
  Parameters: 0, Registers: 2
    0: Mov r0, <closure>
    3: LoadImmediate r1, 1
    6: Ret r1
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 3
    3: Ret r0
}

[BytecodeFunction: x] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 5
    3: Ret r0
}

[BytecodeFunction: named] {
  Parameters: 0, Registers: 4
     0: NewClosure r0, c0
     3: LoadImmediate r1, 1
     6: NewClosure r1, c1
     9: NewClosure r2, c2
    12: LoadUndefined r3
    14: Ret r3
  Constant Table:
    0: [BytecodeFunction: x]
    1: [BytecodeFunction: y]
    2: [BytecodeFunction: fnName]
}

[BytecodeFunction: x] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: y] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: fnName] {
  Parameters: 0, Registers: 2
    0: Mov r0, <closure>
    3: LoadUndefined r1
    5: Ret r1
}

[BytecodeFunction: namedCaptured] {
  Parameters: 0, Registers: 2
    0: NewClosure r0, c0
    3: LoadUndefined r1
    5: Ret r1
  Constant Table:
    0: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
     0: PushFunctionScope c0
     2: StoreToScope <closure>, 0, 0
     6: NewClosure r0, c1
     9: LoadFromScope r0, 0, 0
    13: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: Ret r0
}

[BytecodeFunction: namedVarOverwrite] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: LoadUndefined r0
    5: Ret r0
  Constant Table:
    0: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
    0: LoadUndefined r1
    2: Ret r1
}

[BytecodeFunction: namedLexOverwrite] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: LoadUndefined r0
    5: Ret r0
  Constant Table:
    0: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
    0: LoadUndefined r0
    2: LoadUndefined r1
    4: Ret r1
}
