[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: LoadNull r0
     4: LoadTrue r0
     6: LoadFalse r0
     8: LoadConstant r0, c1
    11: LoadConstant r0, c2
    14: LoadConstant r0, c2
    17: LoadConstant r0, c3
    20: LoadConstant r0, c4
    23: LoadUndefined r0
    25: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [String: ]
    2: [String: hello]
    3: [BigInt: 1]
    4: [BigInt: 1]
}
