[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: LoadImmediate r0, 1
    29: StoreGlobal r0, c9
    32: LoadUndefined r0
    34: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: logicalAnd]
    2: [String: logicalAnd]
    3: [BytecodeFunction: localOr]
    4: [String: localOr]
    5: [BytecodeFunction: nullishCoalesce]
    6: [String: nullishCoalesce]
    7: [BytecodeFunction: testAssignDest]
    8: [String: testAssignDest]
    9: [String: global]
}

[BytecodeFunction: logicalAnd] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 0
     3: JumpToBooleanFalse a0, 6 (.L0)
     6: LoadImmediate a0, 1
  .L0:
     9: JumpToBooleanFalse r0, 6 (.L1)
    12: LoadImmediate r0, 2
  .L1:
    15: LoadGlobal r1, c0
    18: JumpToBooleanFalse r1, 9 (.L2)
    21: LoadImmediate r1, 3
    24: StoreGlobal r1, c0
  .L2:
    27: GetNamedProperty r1, a0, c1
    31: JumpToBooleanFalse r1, 10 (.L3)
    34: LoadImmediate r1, 4
    37: SetNamedProperty a0, c1, r1
  .L3:
    41: LoadGlobal r1, c2
    44: Mov r2, a0
    47: JumpToBooleanFalse r2, 6 (.L4)
    50: LoadImmediate a0, 5
  .L4:
    53: Mov r2, a0
    56: Call r1, r1, r2, 1
    61: LoadUndefined r1
    63: Ret r1
  Constant Table:
    0: [String: global]
    1: [String: foo]
    2: [String: use]
}

[BytecodeFunction: localOr] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 0
     3: JumpToBooleanTrue a0, 6 (.L0)
     6: LoadImmediate a0, 1
  .L0:
     9: JumpToBooleanTrue r0, 6 (.L1)
    12: LoadImmediate r0, 2
  .L1:
    15: LoadGlobal r1, c0
    18: JumpToBooleanTrue r1, 9 (.L2)
    21: LoadImmediate r1, 3
    24: StoreGlobal r1, c0
  .L2:
    27: GetNamedProperty r1, a0, c1
    31: JumpToBooleanTrue r1, 10 (.L3)
    34: LoadImmediate r1, 4
    37: SetNamedProperty a0, c1, r1
  .L3:
    41: LoadGlobal r1, c2
    44: Mov r2, a0
    47: JumpToBooleanTrue r2, 6 (.L4)
    50: LoadImmediate a0, 5
  .L4:
    53: Mov r2, a0
    56: Call r1, r1, r2, 1
    61: LoadUndefined r1
    63: Ret r1
  Constant Table:
    0: [String: global]
    1: [String: foo]
    2: [String: use]
}

[BytecodeFunction: nullishCoalesce] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 0
     3: JumpNotNullish a0, 6 (.L0)
     6: LoadImmediate a0, 1
  .L0:
     9: JumpNotNullish r0, 6 (.L1)
    12: LoadImmediate r0, 2
  .L1:
    15: LoadGlobal r1, c0
    18: JumpNotNullish r1, 9 (.L2)
    21: LoadImmediate r1, 3
    24: StoreGlobal r1, c0
  .L2:
    27: GetNamedProperty r1, a0, c1
    31: JumpNotNullish r1, 10 (.L3)
    34: LoadImmediate r1, 4
    37: SetNamedProperty a0, c1, r1
  .L3:
    41: LoadGlobal r1, c2
    44: Mov r2, a0
    47: JumpNotNullish r2, 6 (.L4)
    50: LoadImmediate a0, 5
  .L4:
    53: Mov r2, a0
    56: Call r1, r1, r2, 1
    61: LoadUndefined r1
    63: Ret r1
  Constant Table:
    0: [String: global]
    1: [String: foo]
    2: [String: use]
}

[BytecodeFunction: testAssignDest] {
  Parameters: 1, Registers: 4
     0: LoadImmediate r0, 0
     3: Mov r1, a0
     6: JumpToBooleanFalse r1, 6 (.L0)
     9: LoadImmediate a0, 1
  .L0:
    12: Mov r0, a0
    15: Mov r2, r0
    18: Mov r3, a0
    21: JumpToBooleanFalse r3, 6 (.L1)
    24: LoadImmediate a0, 2
  .L1:
    27: Mov r1, a0
    30: SetNamedProperty r2, c0, r1
    34: LoadUndefined r1
    36: Ret r1
  Constant Table:
    0: [String: foo]
}
