[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: StoreGlobal r0, c1
    6: LoadUndefined r0
    8: Ret r0
  Constant Table:
    0: [BytecodeFunction: testNamedMember]
    1: [String: testNamedMember]
}

[BytecodeFunction: testNamedMember] {
  Parameters: 1, Registers: 1
     0: GetNamedProperty r0, a0, c0
     4: GetNamedProperty r0, a0, c1
     8: LoadUndefined r0
    10: Ret r0
  Constant Table:
    0: [String: foo]
    1: [String: x]
}
