[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 4
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: LoadGlobal r0, c1
    27: Construct r0, r0, r0, r0, 0
    33: LoadGlobal r0, c1
    36: LoadImmediate r1, 1
    39: LoadImmediate r2, 2
    42: LoadImmediate r3, 3
    45: Construct r0, r0, r0, r1, 3
    51: LoadUndefined r0
    53: Ret r0
  Constant Table:
    0: [BytecodeFunction: foo]
    1: [String: foo]
    2: [BytecodeFunction: bar]
    3: [String: bar]
    4: [BytecodeFunction: spread]
    5: [String: spread]
    6: [BytecodeFunction: argAndSpread]
    7: [String: argAndSpread]
}

[BytecodeFunction: foo] {
  Parameters: 3, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: bar] {
  Parameters: 1, Registers: 5
     0: LoadImmediate r0, 2
     3: LoadGlobal r1, c0
     6: LoadImmediate r2, 1
     9: Mov r3, a0
    12: LoadGlobal r4, c0
    15: Construct r1, r1, r1, r2, 3
    21: Add r0, r0, r1
    25: LoadUndefined r0
    27: Ret r0
  Constant Table:
    0: [String: foo]
}

[BytecodeFunction: spread] {
  Parameters: 1, Registers: 7
     0: LoadGlobal r0, c0
     3: NewArray r1
     5: LoadImmediate r2, 0
     8: GetIterator r3, r4, a0
  .L0:
    12: IteratorNext r5, r6, r3, r4
    17: JumpTrue r6, 11 (.L1)
    20: SetArrayProperty r1, r2, r5
    24: Inc r2
    26: Jump -14 (.L0)
  .L1:
    28: ConstructVarargs r0, r0, r0, r1
    33: Ret r0
  Constant Table:
    0: [String: foo]
}

[BytecodeFunction: argAndSpread] {
  Parameters: 1, Registers: 7
     0: LoadGlobal r0, c0
     3: NewArray r1
     5: LoadImmediate r2, 0
     8: LoadImmediate r3, 1
    11: SetArrayProperty r1, r2, r3
    15: Inc r2
    17: GetIterator r3, r4, a0
  .L0:
    21: IteratorNext r5, r6, r3, r4
    26: JumpTrue r6, 11 (.L1)
    29: SetArrayProperty r1, r2, r5
    33: Inc r2
    35: Jump -14 (.L0)
  .L1:
    37: ConstructVarargs r0, r0, r0, r1
    42: Ret r0
  Constant Table:
    0: [String: foo]
}
