[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 4
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: LoadGlobal r0, c2
    17: Construct r0, r0, r0, r0, 0
    23: LoadGlobal r0, c2
    26: LoadImmediate r1, 1
    29: LoadImmediate r2, 2
    32: LoadImmediate r3, 3
    35: Construct r0, r0, r0, r1, 3
    41: LoadUndefined r0
    43: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: foo]
    2: [String: foo]
    3: [BytecodeFunction: bar]
    4: [String: bar]
}

[BytecodeFunction: foo] {
  Parameters: 3, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: bar] {
  Parameters: 1, Registers: 5
     0: LoadImmediate r0, 2
     3: LoadGlobal r1, c0
     6: LoadImmediate r2, 1
     9: Mov r3, a0
    12: LoadGlobal r4, c0
    15: Construct r1, r1, r1, r2, 3
    21: Add r0, r0, r1
    25: LoadUndefined r0
    27: Ret r0
  Constant Table:
    0: [String: foo]
}
