[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: LoadUndefined r0
    22: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: use]
    2: [String: use]
    3: [BytecodeFunction: testAllExpressionsEvaluated]
    4: [String: testAllExpressionsEvaluated]
    5: [BytecodeFunction: tesLastExpressionIsReturned]
    6: [String: tesLastExpressionIsReturned]
}

[BytecodeFunction: use] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: testAllExpressionsEvaluated] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
     6: LoadImmediate r0, 3
     9: LoadUndefined r0
    11: Ret r0
}

[BytecodeFunction: tesLastExpressionIsReturned] {
  Parameters: 0, Registers: 2
     0: LoadGlobal r0, c0
     3: LoadImmediate r1, 1
     6: LoadImmediate r1, 2
     9: LoadImmediate r1, 3
    12: Call r0, r0, r1, 1
    17: LoadImmediate r0, 1
    20: LoadImmediate r0, 2
    23: LoadImmediate r0, 3
    26: Ret r0
  Constant Table:
    0: [String: use]
}
