[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: LoadUndefined r0
    20: Ret r0
  Constant Table:
    0: [BytecodeFunction: use]
    1: [String: use]
    2: [BytecodeFunction: testAllExpressionsEvaluated]
    3: [String: testAllExpressionsEvaluated]
    4: [BytecodeFunction: tesLastExpressionIsReturned]
    5: [String: tesLastExpressionIsReturned]
}

[BytecodeFunction: use] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: testAllExpressionsEvaluated] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
     6: LoadImmediate r0, 3
     9: LoadUndefined r0
    11: Ret r0
}

[BytecodeFunction: tesLastExpressionIsReturned] {
  Parameters: 0, Registers: 2
     0: LoadGlobal r0, c0
     3: LoadImmediate r1, 1
     6: LoadImmediate r1, 2
     9: LoadImmediate r1, 3
    12: Call r0, r0, r1, 1
    17: LoadImmediate r0, 1
    20: LoadImmediate r0, 2
    23: LoadImmediate r0, 3
    26: Ret r0
  Constant Table:
    0: [String: use]
}
