[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: NewClosure r0, c11
    35: StoreGlobal r0, c12
    38: NewClosure r0, c13
    41: StoreGlobal r0, c14
    44: NewClosure r0, c15
    47: StoreGlobal r0, c16
    50: LoadUndefined r0
    52: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: evaluationOrder]
    2: [String: evaluationOrder]
    3: [BytecodeFunction: noArgs]
    4: [String: noArgs]
    5: [BytecodeFunction: argsInContiguousRegisters]
    6: [String: argsInContiguousRegisters]
    7: [BytecodeFunction: allExpressionTypes]
    8: [String: allExpressionTypes]
    9: [BytecodeFunction: namedMemberTag]
    10: [String: namedMemberTag]
    11: [BytecodeFunction: computedMemberTag]
    12: [String: computedMemberTag]
    13: [BytecodeFunction: optionalNamedMemberTag]
    14: [String: optionalNamedMemberTag]
    15: [BytecodeFunction: optionalComputedMemberTag]
    16: [String: optionalComputedMemberTag]
}

[BytecodeFunction: evaluationOrder] {
  Parameters: 0, Registers: 5
     0: LoadImmediate r0, 1
     3: LoadImmediate r1, 2
     6: Add r0, r0, r1
    10: LoadConstant r1, c0
    13: LoadImmediate r2, 3
    16: LoadImmediate r3, 4
    19: Add r2, r2, r3
    23: LoadImmediate r3, 5
    26: LoadImmediate r4, 6
    29: Add r3, r3, r4
    33: Call r0, r0, r1, 3
    38: Ret r0
  Constant Table:
    0: [ArrayObject]
}

[BytecodeFunction: noArgs] {
  Parameters: 1, Registers: 1
    0: LoadConstant r0, c0
    3: Call r0, a0, r0, 1
    8: Ret r0
  Constant Table:
    0: [ArrayObject]
}

[BytecodeFunction: argsInContiguousRegisters] {
  Parameters: 1, Registers: 4
     0: LoadConstant r0, c0
     3: LoadImmediate r1, 1
     6: LoadImmediate r2, 2
     9: LoadImmediate r3, 3
    12: Call r0, a0, r0, 4
    17: Ret r0
  Constant Table:
    0: [ArrayObject]
}

[BytecodeFunction: allExpressionTypes] {
  Parameters: 2, Registers: 4
     0: LoadConstant r0, c0
     3: LoadImmediate r1, 1
     6: Mov r2, a1
     9: LoadGlobal r3, c1
    12: Call r0, a0, r0, 4
    17: Ret r0
  Constant Table:
    0: [ArrayObject]
    1: [String: allExpressionTypes]
}

[BytecodeFunction: namedMemberTag] {
  Parameters: 1, Registers: 5
     0: GetNamedProperty r1, a0, c0
     4: LoadConstant r2, c1
     7: LoadImmediate r3, 1
    10: LoadImmediate r4, 2
    13: CallWithReceiver r1, r1, a0, r2, 3
    19: LoadImmediate r1, 1
    22: LoadImmediate r2, 2
    25: Add r0, r1, r2
    29: GetNamedProperty r1, r0, c0
    33: LoadConstant r2, c2
    36: LoadImmediate r3, 3
    39: CallWithReceiver r1, r1, r0, r2, 2
    45: LoadUndefined r1
    47: Ret r1
  Constant Table:
    0: [String: foo]
    1: [ArrayObject]
    2: [ArrayObject]
}

[BytecodeFunction: computedMemberTag] {
  Parameters: 1, Registers: 5
     0: LoadConstant r1, c0
     3: GetProperty r1, a0, r1
     7: LoadConstant r2, c1
    10: LoadImmediate r3, 1
    13: LoadImmediate r4, 2
    16: CallWithReceiver r1, r1, a0, r2, 3
    22: LoadImmediate r1, 1
    25: LoadImmediate r2, 2
    28: Add r0, r1, r2
    32: LoadConstant r1, c0
    35: GetProperty r1, r0, r1
    39: LoadConstant r2, c2
    42: LoadImmediate r3, 3
    45: CallWithReceiver r1, r1, r0, r2, 2
    51: LoadUndefined r1
    53: Ret r1
  Constant Table:
    0: [String: foo]
    1: [ArrayObject]
    2: [ArrayObject]
}

[BytecodeFunction: optionalNamedMemberTag] {
  Parameters: 1, Registers: 4
     0: Mov r0, a0
     3: JumpNullish r0, 9 (.L0)
     6: GetNamedProperty r1, r0, c0
    10: Jump 6 (.L1)
  .L0:
    12: LoadUndefined r1
    14: LoadUndefined r0
  .L1:
    16: LoadConstant r2, c1
    19: LoadImmediate r3, 1
    22: CallWithReceiver r0, r1, r0, r2, 2
    28: JumpNullish a0, 13 (.L2)
    31: GetNamedProperty r0, a0, c2
    35: GetNamedProperty r1, r0, c3
    39: Jump 6 (.L3)
  .L2:
    41: LoadUndefined r1
    43: LoadUndefined r0
  .L3:
    45: LoadConstant r2, c4
    48: LoadImmediate r3, 1
    51: CallWithReceiver r0, r1, r0, r2, 2
    57: LoadUndefined r0
    59: Ret r0
  Constant Table:
    0: [String: foo]
    1: [ArrayObject]
    2: [String: a]
    3: [String: b]
    4: [ArrayObject]
}

[BytecodeFunction: optionalComputedMemberTag] {
  Parameters: 1, Registers: 4
     0: Mov r0, a0
     3: JumpNullish r0, 12 (.L0)
     6: LoadImmediate r1, 1
     9: GetProperty r1, r0, r1
    13: Jump 6 (.L1)
  .L0:
    15: LoadUndefined r1
    17: LoadUndefined r0
  .L1:
    19: LoadConstant r2, c0
    22: LoadImmediate r3, 1
    25: CallWithReceiver r0, r1, r0, r2, 2
    31: JumpNullish a0, 19 (.L2)
    34: LoadImmediate r0, 1
    37: GetProperty r0, a0, r0
    41: LoadImmediate r1, 2
    44: GetProperty r1, r0, r1
    48: Jump 6 (.L3)
  .L2:
    50: LoadUndefined r1
    52: LoadUndefined r0
  .L3:
    54: LoadConstant r2, c1
    57: LoadImmediate r3, 1
    60: CallWithReceiver r0, r1, r0, r2, 2
    66: LoadUndefined r0
    68: Ret r0
  Constant Table:
    0: [ArrayObject]
    1: [ArrayObject]
}
