[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: NewClosure r0, c11
    35: StoreGlobal r0, c12
    38: NewClosure r0, c13
    41: StoreGlobal r0, c14
    44: LoadUndefined r0
    46: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: emptySingleQuasi]
    2: [String: emptySingleQuasi]
    3: [BytecodeFunction: emptySingleExpression]
    4: [String: emptySingleExpression]
    5: [BytecodeFunction: emptyFollowedByExpression]
    6: [String: emptyFollowedByExpression]
    7: [BytecodeFunction: expressionFollowedByEmpty]
    8: [String: expressionFollowedByEmpty]
    9: [BytecodeFunction: expressionsAndEmptyLiterals]
    10: [String: expressionsAndEmptyLiterals]
    11: [BytecodeFunction: expressionsAndNonEmptyLiterals]
    12: [String: expressionsAndNonEmptyLiterals]
    13: [BytecodeFunction: fixedRegisterExpressions]
    14: [String: fixedRegisterExpressions]
}

[BytecodeFunction: emptySingleQuasi] {
  Parameters: 1, Registers: 1
    0: LoadConstant a0, c0
    3: LoadConstant r0, c0
    6: Ret r0
  Constant Table:
    0: [String: ]
}

[BytecodeFunction: emptySingleExpression] {
  Parameters: 1, Registers: 1
     0: LoadImmediate r0, 1
     3: ToString a0, r0
     6: LoadImmediate r0, 1
     9: ToString r0, r0
    12: Ret r0
}

[BytecodeFunction: emptyFollowedByExpression] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r1, 1
     3: ToString r0, r1
     6: LoadConstant r1, c0
     9: Add r0, r0, r1
    13: Mov a0, r0
    16: LoadImmediate r1, 1
    19: ToString r0, r1
    22: LoadConstant r1, c0
    25: Add r0, r0, r1
    29: Ret r0
  Constant Table:
    0: [String: test]
}

[BytecodeFunction: expressionFollowedByEmpty] {
  Parameters: 0, Registers: 2
     0: LoadConstant r0, c0
     3: LoadImmediate r1, 1
     6: ToString r1, r1
     9: Add r0, r0, r1
    13: Ret r0
  Constant Table:
    0: [String: test]
}

[BytecodeFunction: expressionsAndEmptyLiterals] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r1, 1
     3: ToString r0, r1
     6: LoadImmediate r1, 2
     9: ToString r1, r1
    12: Add r0, r0, r1
    16: LoadImmediate r1, 3
    19: ToString r1, r1
    22: Add r0, r0, r1
    26: Ret r0
}

[BytecodeFunction: expressionsAndNonEmptyLiterals] {
  Parameters: 0, Registers: 2
     0: LoadConstant r0, c0
     3: LoadImmediate r1, 1
     6: ToString r1, r1
     9: Add r0, r0, r1
    13: LoadConstant r1, c1
    16: Add r0, r0, r1
    20: LoadImmediate r1, 2
    23: ToString r1, r1
    26: Add r0, r0, r1
    30: LoadConstant r1, c2
    33: Add r0, r0, r1
    37: Ret r0
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: c]
}

[BytecodeFunction: fixedRegisterExpressions] {
  Parameters: 2, Registers: 2
     0: ToString a1, a0
     3: ToString a1, a1
     6: LoadConstant r0, c0
     9: ToString r1, a0
    12: Add r0, r0, r1
    16: LoadConstant r1, c1
    19: Add r0, r0, r1
    23: ToString r1, a1
    26: Add r0, r0, r1
    30: LoadConstant r1, c2
    33: Add r0, r0, r1
    37: Ret r0
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: c]
}
