[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, -1
     3: LoadImmediate r0, 1
     6: StoreGlobal r0, c0
     9: LoadGlobal r0, c0
    12: Neg r0, r0
    15: LoadGlobal r0, c0
    18: Neg r0, r0
    21: Neg r0, r0
    24: LoadImmediate r0, 1
    27: LoadGlobal r0, c0
    30: ToNumber r0, r0
    33: LoadGlobal r0, c0
    36: ToNumber r0, r0
    39: ToNumber r0, r0
    42: LoadImmediate r0, 1
    45: LoadUndefined r0
    47: LoadUndefined r0
    49: Ret r0
  Constant Table:
    0: [String: x]
}
