[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: LoadUndefined r0
    34: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: unaryMinus]
    2: [String: unaryMinus]
    3: [BytecodeFunction: unaryPlus]
    4: [String: unaryPlus]
    5: [BytecodeFunction: logicalNot]
    6: [String: logicalNot]
    7: [BytecodeFunction: bitwiseNot]
    8: [String: bitwiseNot]
    9: [BytecodeFunction: _void]
    10: [String: _void]
}

[BytecodeFunction: unaryMinus] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r1, -1
     3: LoadImmediate r0, 1
     6: Neg r1, r0
     9: Neg r1, r0
    12: Neg r1, r1
    15: LoadUndefined r1
    17: Ret r1
}

[BytecodeFunction: unaryPlus] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadGlobal r0, c0
     6: ToNumber r0, r0
     9: LoadGlobal r0, c0
    12: ToNumber r0, r0
    15: ToNumber r0, r0
    18: LoadUndefined r0
    20: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: logicalNot] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LogNot r0, r0
     6: LoadTrue r0
     8: LogNot r0, r0
    11: LoadFalse r0
    13: LogNot r0, r0
    16: LogNot r0, r0
    19: LoadUndefined r0
    21: Ret r0
}

[BytecodeFunction: bitwiseNot] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: BitNot r0, r0
     6: LoadImmediate r0, 2
     9: BitNot r0, r0
    12: BitNot r0, r0
    15: LoadUndefined r0
    17: Ret r0
}

[BytecodeFunction: _void] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 1
    3: LoadUndefined r0
    5: LoadUndefined r0
    7: Ret r0
}
