[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: NewClosure r0, c14
    45: StoreGlobal r0, c15
    48: NewClosure r0, c16
    51: StoreGlobal r0, c17
    54: NewClosure r0, c18
    57: StoreGlobal r0, c19
    60: LoadImmediate r0, 0
    63: StoreGlobal r0, c20
    66: PushLexicalScope c21
    68: NewObject r0
    70: StoreToScope r0, 0, 0
    74: NewClosure r1, c23
    77: DefineNamedProperty r0, c22, r1
    81: NewClosure r1, c25
    84: DefineNamedProperty r0, c24, r1
    88: PopScope 
    89: LoadUndefined r0
    91: Ret r0
  Constant Table:
    0: [BytecodeFunction: use]
    1: [String: use]
    2: [BytecodeFunction: prefixIdAnyDest]
    3: [String: prefixIdAnyDest]
    4: [BytecodeFunction: prefixIdFixedDest]
    5: [String: prefixIdFixedDest]
    6: [BytecodeFunction: prefixIdNewTemporaryDest]
    7: [String: prefixIdNewTemporaryDest]
    8: [BytecodeFunction: postfixIdAnyDest]
    9: [String: postfixIdAnyDest]
    10: [BytecodeFunction: postfixIdFixedDest]
    11: [String: postfixIdFixedDest]
    12: [BytecodeFunction: postfixIdNewTemporaryDest]
    13: [String: postfixIdNewTemporaryDest]
    14: [BytecodeFunction: prefixMember]
    15: [String: prefixMember]
    16: [BytecodeFunction: postfixMember]
    17: [String: postfixMember]
    18: [BytecodeFunction: decrement]
    19: [String: decrement]
    20: [String: global]
    21: [ScopeNames]
    22: [String: prefixSuperMember]
    23: [BytecodeFunction: prefixSuperMember]
    24: [String: postfixSuperMember]
    25: [BytecodeFunction: postfixSuperMember]
}

[BytecodeFunction: use] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: prefixIdAnyDest] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: ToNumeric a0, a0
     6: Inc a0
     8: Neg r1, a0
    11: ToNumeric r0, r0
    14: Inc r0
    16: Neg r1, r0
    19: LoadGlobal r1, c0
    22: ToNumeric r1, r1
    25: Inc r1
    27: StoreGlobal r1, c0
    30: Neg r1, r1
    33: LoadUndefined r1
    35: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: prefixIdFixedDest] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: ToNumeric a0, a0
     6: Inc a0
     8: Mov r0, a0
    11: ToNumeric r0, r0
    14: Inc r0
    16: LoadGlobal r1, c0
    19: ToNumeric r0, r1
    22: Inc r0
    24: StoreGlobal r0, c0
    27: LoadUndefined r1
    29: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: prefixIdNewTemporaryDest] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 1
     3: LoadGlobal r1, c0
     6: ToNumeric a0, a0
     9: Inc a0
    11: Mov r2, a0
    14: Call r1, r1, r2, 1
    19: LoadGlobal r1, c0
    22: ToNumeric r0, r0
    25: Inc r0
    27: Mov r2, r0
    30: Call r1, r1, r2, 1
    35: LoadGlobal r1, c0
    38: LoadGlobal r2, c1
    41: ToNumeric r2, r2
    44: Inc r2
    46: StoreGlobal r2, c1
    49: Call r1, r1, r2, 1
    54: LoadUndefined r1
    56: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: postfixIdAnyDest] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 1
     3: ToNumeric a0, a0
     6: Mov r1, a0
     9: Inc a0
    11: Neg r1, r1
    14: ToNumeric r0, r0
    17: Mov r1, r0
    20: Inc r0
    22: Neg r1, r1
    25: LoadGlobal r2, c0
    28: ToNumeric r2, r2
    31: Mov r1, r2
    34: Inc r2
    36: StoreGlobal r2, c0
    39: Neg r1, r1
    42: LoadUndefined r1
    44: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: postfixIdFixedDest] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: ToNumeric a0, a0
     6: Mov r0, a0
     9: Inc a0
    11: ToNumeric r0, r0
    14: LoadGlobal r1, c0
    17: ToNumeric r1, r1
    20: Mov r0, r1
    23: Inc r1
    25: StoreGlobal r1, c0
    28: LoadUndefined r1
    30: Ret r1
  Constant Table:
    0: [String: global]
}

[BytecodeFunction: postfixIdNewTemporaryDest] {
  Parameters: 1, Registers: 4
     0: LoadImmediate r0, 1
     3: LoadGlobal r1, c0
     6: ToNumeric a0, a0
     9: Mov r2, a0
    12: Inc a0
    14: Call r1, r1, r2, 1
    19: LoadGlobal r1, c0
    22: ToNumeric r0, r0
    25: Mov r2, r0
    28: Inc r0
    30: Call r1, r1, r2, 1
    35: LoadGlobal r1, c0
    38: LoadGlobal r3, c1
    41: ToNumeric r3, r3
    44: Mov r2, r3
    47: Inc r3
    49: StoreGlobal r3, c1
    52: Call r1, r1, r2, 1
    57: LoadUndefined r1
    59: Ret r1
  Constant Table:
    0: [String: use]
    1: [String: global]
}

[BytecodeFunction: prefixMember] {
  Parameters: 2, Registers: 2
     0: GetNamedProperty r0, a0, c0
     4: ToNumeric r0, r0
     7: Inc r0
     9: SetNamedProperty a0, c0, r0
    13: Neg r0, r0
    16: LoadImmediate r1, 0
    19: GetProperty r0, a0, r1
    23: ToNumeric r0, r0
    26: Inc r0
    28: SetProperty a0, r1, r0
    32: Neg r0, r0
    35: GetNamedProperty r0, a0, c0
    39: ToNumeric r0, r0
    42: Inc r0
    44: SetNamedProperty a0, c0, r0
    48: Mov a1, r0
    51: LoadUndefined r0
    53: Ret r0
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: postfixMember] {
  Parameters: 2, Registers: 3
     0: GetNamedProperty r0, a0, c0
     4: ToNumeric r0, r0
     7: Mov r1, r0
    10: Inc r1
    12: SetNamedProperty a0, c0, r1
    16: Neg r0, r0
    19: LoadImmediate r1, 0
    22: GetProperty r0, a0, r1
    26: ToNumeric r0, r0
    29: Mov r2, r0
    32: Inc r2
    34: SetProperty a0, r1, r2
    38: Neg r0, r0
    41: GetNamedProperty r0, a0, c0
    45: ToNumeric r0, r0
    48: Mov r1, r0
    51: Inc r1
    53: SetNamedProperty a0, c0, r1
    57: Mov a1, r0
    60: LoadUndefined r0
    62: Ret r0
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: prefixSuperMember] {
  Parameters: 1, Registers: 3
     0: LoadFromScope r1, 0, 0
     4: LoadConstant r2, c0
     7: ToNumeric r0, r0
    10: Inc r0
    12: SetSuperProperty r1, <this>, r2, r0
    17: Neg r0, r0
    20: LoadFromScope r1, 0, 0
    24: LoadImmediate r2, 0
    27: ToNumeric r0, r0
    30: Inc r0
    32: SetSuperProperty r1, <this>, r2, r0
    37: Neg r0, r0
    40: LoadFromScope r1, 0, 0
    44: LoadConstant r2, c0
    47: ToNumeric r0, r0
    50: Inc r0
    52: SetSuperProperty r1, <this>, r2, r0
    57: Mov a0, r0
    60: LoadUndefined r0
    62: Ret r0
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: postfixSuperMember] {
  Parameters: 1, Registers: 4
     0: LoadFromScope r1, 0, 0
     4: LoadConstant r2, c0
     7: ToNumeric r0, r0
    10: Mov r3, r0
    13: Inc r3
    15: SetSuperProperty r1, <this>, r2, r3
    20: Neg r0, r0
    23: LoadFromScope r1, 0, 0
    27: LoadImmediate r2, 0
    30: ToNumeric r0, r0
    33: Mov r3, r0
    36: Inc r3
    38: SetSuperProperty r1, <this>, r2, r3
    43: Neg r0, r0
    46: LoadFromScope r1, 0, 0
    50: LoadConstant r2, c0
    53: ToNumeric r0, r0
    56: Mov r3, r0
    59: Inc r3
    61: SetSuperProperty r1, <this>, r2, r3
    66: Mov a0, r0
    69: LoadUndefined r0
    71: Ret r0
  Constant Table:
    0: [String: prop]
}

[BytecodeFunction: decrement] {
  Parameters: 1, Registers: 2
     0: ToNumeric a0, a0
     3: Dec a0
     5: ToNumeric a0, a0
     8: Mov r0, a0
    11: Dec a0
    13: GetNamedProperty r0, a0, c0
    17: ToNumeric r0, r0
    20: Dec r0
    22: SetNamedProperty a0, c0, r0
    26: GetNamedProperty r0, a0, c0
    30: ToNumeric r0, r0
    33: Mov r1, r0
    36: Dec r1
    38: SetNamedProperty a0, c0, r1
    42: LoadUndefined r0
    44: Ret r0
  Constant Table:
    0: [String: prop]
}
