[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: LoadUndefined r0
    22: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: testAbruptBodyOnly]
    2: [String: testAbruptBodyOnly]
    3: [BytecodeFunction: testAbruptCatchOnly]
    4: [String: testAbruptCatchOnly]
    5: [BytecodeFunction: testAbruptCatchAndBody]
    6: [String: testAbruptCatchAndBody]
}

[BytecodeFunction: testAbruptBodyOnly] {
  Parameters: 0, Registers: 2
     0: Mov r0, <scope>
     3: LoadUndefined r1
     5: Ret r1
     7: Mov <scope>, r0
    10: LoadImmediate r1, 1
    13: LoadUndefined r0
    15: Ret r0
  Exception Handlers:
    3-7 -> 7
}

[BytecodeFunction: testAbruptCatchOnly] {
  Parameters: 0, Registers: 2
     0: Mov r0, <scope>
     3: LoadImmediate r1, 1
     6: Jump 9 (.L0)
     8: Mov <scope>, r0
    11: LoadUndefined r1
    13: Ret r1
  .L0:
    15: LoadUndefined r0
    17: Ret r0
  Exception Handlers:
    3-6 -> 8
}

[BytecodeFunction: testAbruptCatchAndBody] {
  Parameters: 0, Registers: 2
     0: Mov r0, <scope>
     3: LoadUndefined r1
     5: Ret r1
     7: Mov <scope>, r0
    10: LoadUndefined r1
    12: Ret r1
  Exception Handlers:
    3-7 -> 7
}
