[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: LoadUndefined r0
    26: Ret r0
  Constant Table:
    0: [BytecodeFunction: testAbruptBodyOnly]
    1: [String: testAbruptBodyOnly]
    2: [BytecodeFunction: testAbruptCatchOnly]
    3: [String: testAbruptCatchOnly]
    4: [BytecodeFunction: testAbruptFinallyOnly]
    5: [String: testAbruptFinallyOnly]
    6: [BytecodeFunction: testAbruptCatchAndBody]
    7: [String: testAbruptCatchAndBody]
}

[BytecodeFunction: testAbruptBodyOnly] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
    4: LoadImmediate r0, 1
    7: LoadUndefined r0
    9: Ret r0
  Exception Handlers:
    0-4 -> 4
}

[BytecodeFunction: testAbruptCatchOnly] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: Jump 6 (.L0)
     5: LoadUndefined r0
     7: Ret r0
  .L0:
     9: LoadUndefined r0
    11: Ret r0
  Exception Handlers:
    0-3 -> 5
}

[BytecodeFunction: testAbruptFinallyOnly] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 1
    3: LoadUndefined r0
    5: Ret r0
  Exception Handlers:
    0-3 -> 3
}

[BytecodeFunction: testAbruptCatchAndBody] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
    4: LoadUndefined r0
    6: Ret r0
  Exception Handlers:
    0-4 -> 4
}
