[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: LoadUndefined r0
    26: Ret r0
  Constant Table:
    0: [BytecodeFunction: testCatchNoParameter]
    1: [String: testCatchNoParameter]
    2: [BytecodeFunction: testCatchWithParameter]
    3: [String: testCatchWithParameter]
    4: [BytecodeFunction: testFinallyOnly]
    5: [String: testFinallyOnly]
    6: [BytecodeFunction: testCatchAndFinally]
    7: [String: testCatchAndFinally]
}

[BytecodeFunction: testCatchNoParameter] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
     6: Jump 5 (.L0)
     8: LoadImmediate r0, 3
  .L0:
    11: LoadImmediate r0, 4
    14: LoadUndefined r0
    16: Ret r0
  Exception Handlers:
    3-6 -> 8
}

[BytecodeFunction: testCatchWithParameter] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r1, 1
     3: LoadImmediate r1, 2
     6: Jump 9 (.L0)
     8: LoadImmediate r1, 3
    11: Add r1, r1, r0
  .L0:
    15: LoadImmediate r1, 4
    18: LoadUndefined r1
    20: Ret r1
  Exception Handlers:
    3-6 -> 8 (r0)
}

[BytecodeFunction: testFinallyOnly] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
     6: LoadImmediate r0, 3
     9: LoadImmediate r0, 4
    12: LoadUndefined r0
    14: Ret r0
  Exception Handlers:
    3-6 -> 6
}

[BytecodeFunction: testCatchAndFinally] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r1, 1
     3: LoadImmediate r1, 2
     6: Jump 5 (.L0)
     8: LoadImmediate r1, 3
  .L0:
    11: LoadImmediate r1, 4
    14: LoadImmediate r1, 5
    17: LoadUndefined r1
    19: Ret r1
  Exception Handlers:
    3-6 -> 8 (r0)
    8-11 -> 11
}
