[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: LoadUndefined r0
    20: Ret r0
  Constant Table:
    0: [BytecodeFunction: testCatchNoParameter]
    1: [String: testCatchNoParameter]
    2: [BytecodeFunction: testCatchWithParameter]
    3: [String: testCatchWithParameter]
    4: [BytecodeFunction: testCatchDestructuring]
    5: [String: testCatchDestructuring]
}

[BytecodeFunction: testCatchNoParameter] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: Mov r0, <scope>
     6: LoadImmediate r1, 2
     9: Jump 8 (.L0)
    11: Mov <scope>, r0
    14: LoadImmediate r1, 3
  .L0:
    17: LoadImmediate r0, 4
    20: LoadUndefined r0
    22: Ret r0
  Exception Handlers:
    6-9 -> 11
}

[BytecodeFunction: testCatchWithParameter] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r1, 1
     3: Mov r1, <scope>
     6: LoadImmediate r2, 2
     9: Jump 12 (.L0)
    11: Mov <scope>, r1
    14: LoadImmediate r2, 3
    17: Add r2, r2, r0
  .L0:
    21: LoadImmediate r1, 4
    24: LoadUndefined r1
    26: Ret r1
  Exception Handlers:
    6-9 -> 11 (r0)
}

[BytecodeFunction: testCatchDestructuring] {
  Parameters: 0, Registers: 5
     0: LoadImmediate r2, 1
     3: Mov r2, <scope>
     6: LoadImmediate r3, 2
     9: Jump 25 (.L1)
    11: Mov <scope>, r2
    14: GetNamedProperty r0, r3, c0
    18: GetNamedProperty r4, r3, c1
    22: JumpNotUndefined r4, 6 (.L0)
    25: LoadImmediate r4, 3
  .L0:
    28: Mov r1, r4
    31: LoadImmediate r3, 4
  .L1:
    34: LoadImmediate r2, 5
    37: LoadUndefined r2
    39: Ret r2
  Constant Table:
    0: [String: a]
    1: [String: b]
  Exception Handlers:
    6-9 -> 11 (r3)
}
