[BytecodeFunction: <module>] {
  Parameters: 0, Registers: 4
     0: NewClosure r0, c0
     3: NewClosure r1, c1
     6: LoadImmediate r2, 1
     9: StoreToModule r2, 1, 0
    13: LoadImmediate r2, 2
    16: StoreToModule r2, 2, 0
    20: LoadImmediate r2, 3
    23: StoreToModule r2, 3, 0
    27: LoadEmpty r3
    29: NewClass r2, c3, c2, r3, r2
    35: StoreToModule r2, 4, 0
    39: LoadImmediate r2, 5
    42: StoreToModule r2, 6, 0
    46: LoadImmediate r2, 6
    49: StoreToModule r2, 7, 0
    53: LoadUndefined r2
    55: Ret r2
  Constant Table:
    0: [BytecodeFunction: testAccessSimpleExportedBinding]
    1: [BytecodeFunction: testAccessExportedInSeparateDeclaration]
    2: [BytecodeFunction: Class1]
    3: [ClassNames]
}

[BytecodeFunction: Class1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: func1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: testAccessSimpleExportedBinding] {
  Parameters: 0, Registers: 3
     0: LoadFromModule r1, 1, 0
     4: LoadFromModule r2, 2, 0
     8: Add r1, r1, r2, ic0
    13: LoadFromModule r2, 3, 0
    17: Add r1, r1, r2, ic1
    22: LoadFromModule r2, 4, 0
    26: Add r1, r1, r2, ic2
    31: LoadFromModule r2, 5, 0
    35: Add r1, r1, r2, ic3
    40: PushLexicalScope c0
    42: LoadEmpty r1
    44: StoreToScope r1, 0, 0
    48: NewClosure r0, c1
    51: LoadImmediate r1, 4
    54: StoreToScope r1, 0, 0
    58: LoadFromModule r1, 3, 1
    62: Call r1, r0, r1, 1
    67: PopScope 
    68: LoadUndefined r1
    70: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: capturing]
}

[BytecodeFunction: capturing] {
  Parameters: 0, Registers: 2
     0: LoadFromModule r0, 3, 1
     4: LoadFromScope r1, 0, 0
     8: CheckTdz r1, c0
    11: Add r0, r0, r1, ic0
    16: LoadUndefined r0
    18: Ret r0
  Constant Table:
    0: [String: const2]
}

[BytecodeFunction: testAccessExportedInSeparateDeclaration] {
  Parameters: 0, Registers: 2
     0: LoadFromModule r0, 6, 0
     4: LoadFromModule r1, 7, 0
     8: Add r0, r0, r1, ic0
    13: LoadGlobal r1, c0
    16: Add r0, r0, r1, ic1
    21: LoadUndefined r0
    23: Ret r0
  Constant Table:
    0: [String: renamedVar3]
}
