[BytecodeFunction: <module>] {
  Parameters: 0, Registers: 4
     0: NewClosure r0, c0
     3: NewClosure r1, c1
     6: LoadImmediate r2, 1
     9: StoreToModule r2, 1, 0
    13: LoadImmediate r2, 2
    16: StoreToModule r2, 2, 0
    20: LoadImmediate r2, 3
    23: StoreToModule r2, 3, 0
    27: LoadEmpty r3
    29: NewClass r2, c3, c2, r3, r2
    35: StoreToModule r2, 4, 0
    39: LoadImmediate r2, 5
    42: StoreToModule r2, 6, 0
    46: LoadImmediate r2, 6
    49: StoreToModule r2, 7, 0
    53: LoadUndefined r2
    55: Ret r2
  Constant Table:
    0: [BytecodeFunction: testAccessSimpleExportedBinding]
    1: [BytecodeFunction: testAccessExportedInSeparateDeclaration]
    2: [BytecodeFunction: Class1]
    3: [ClassNames]
}

[BytecodeFunction: Class1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: func1] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: testAccessSimpleExportedBinding] {
  Parameters: 0, Registers: 3
     0: LoadFromModule r1, 1, 0
     4: LoadFromModule r2, 2, 0
     8: Add r1, r1, r2
    12: LoadFromModule r2, 3, 0
    16: Add r1, r1, r2
    20: LoadFromModule r2, 4, 0
    24: Add r1, r1, r2
    28: LoadFromModule r2, 5, 0
    32: Add r1, r1, r2
    36: PushLexicalScope c0
    38: LoadEmpty r1
    40: StoreToScope r1, 0, 0
    44: NewClosure r0, c1
    47: LoadImmediate r1, 4
    50: StoreToScope r1, 0, 0
    54: LoadFromModule r1, 3, 1
    58: Call r1, r0, r1, 1
    63: PopScope 
    64: LoadUndefined r1
    66: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: capturing]
}

[BytecodeFunction: capturing] {
  Parameters: 0, Registers: 2
     0: LoadFromModule r0, 3, 1
     4: LoadFromScope r1, 0, 0
     8: CheckTdz r1, c0
    11: Add r0, r0, r1
    15: LoadUndefined r0
    17: Ret r0
  Constant Table:
    0: [String: const2]
}

[BytecodeFunction: testAccessExportedInSeparateDeclaration] {
  Parameters: 0, Registers: 2
     0: LoadFromModule r0, 6, 0
     4: LoadFromModule r1, 7, 0
     8: Add r0, r0, r1
    12: LoadGlobal r1, c0
    15: Add r0, r0, r1
    19: LoadUndefined r0
    21: Ret r0
  Constant Table:
    0: [String: renamedVar3]
}
