{
  type: "Program",
  loc: "1:1-19:31",
  body: [
    {
      type: "VariableDeclaration",
      loc: "1:1-1:12",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "1:5-1:11",
          id: {
            type: "ArrayPattern",
            loc: "1:5-1:7",
            elements: [],
          },
          init: {
            type: "Literal",
            loc: "1:10-1:11",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "3:1-3:13",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "3:5-3:12",
          id: {
            type: "ArrayPattern",
            loc: "3:5-3:8",
            elements: [
              null,
            ],
          },
          init: {
            type: "Literal",
            loc: "3:11-3:12",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "5:1-5:15",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "5:5-5:14",
          id: {
            type: "ArrayPattern",
            loc: "5:5-5:10",
            elements: [
              null,
              null,
              null,
            ],
          },
          init: {
            type: "Literal",
            loc: "5:13-5:14",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "7:1-7:19",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "7:5-7:18",
          id: {
            type: "ArrayPattern",
            loc: "7:5-7:14",
            elements: [
              {
                type: "Identifier",
                loc: "7:6-7:7",
                name: "a",
              },
              {
                type: "Identifier",
                loc: "7:9-7:10",
                name: "b",
              },
              {
                type: "Identifier",
                loc: "7:12-7:13",
                name: "c",
              },
            ],
          },
          init: {
            type: "Literal",
            loc: "7:17-7:18",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "9:1-9:20",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "9:5-9:19",
          id: {
            type: "ArrayPattern",
            loc: "9:5-9:15",
            elements: [
              {
                type: "Identifier",
                loc: "9:6-9:7",
                name: "a",
              },
              {
                type: "Identifier",
                loc: "9:9-9:10",
                name: "b",
              },
              {
                type: "Identifier",
                loc: "9:12-9:13",
                name: "c",
              },
            ],
          },
          init: {
            type: "Literal",
            loc: "9:18-9:19",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "11:1-11:23",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "11:5-11:22",
          id: {
            type: "ArrayPattern",
            loc: "11:5-11:18",
            elements: [
              null,
              {
                type: "Identifier",
                loc: "11:7-11:8",
                name: "a",
              },
              null,
              {
                type: "Identifier",
                loc: "11:11-11:12",
                name: "b",
              },
              {
                type: "Identifier",
                loc: "11:14-11:15",
                name: "c",
              },
              null,
            ],
          },
          init: {
            type: "Literal",
            loc: "11:21-11:22",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "13:1-13:17",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "13:5-13:16",
          id: {
            type: "ArrayPattern",
            loc: "13:5-13:12",
            elements: [
              {
                type: "AssignmentPattern",
                loc: "13:6-13:11",
                left: {
                  type: "Identifier",
                  loc: "13:6-13:7",
                  name: "a",
                },
                right: {
                  type: "Literal",
                  loc: "13:10-13:11",
                  value: 1,
                },
              },
            ],
          },
          init: {
            type: "Literal",
            loc: "13:15-13:16",
            value: 2,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "15:1-15:23",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "15:5-15:22",
          id: {
            type: "ArrayPattern",
            loc: "15:5-15:18",
            elements: [
              {
                type: "ArrayPattern",
                loc: "15:6-15:14",
                elements: [
                  {
                    type: "Identifier",
                    loc: "15:7-15:8",
                    name: "a",
                  },
                  {
                    type: "ArrayPattern",
                    loc: "15:10-15:13",
                    elements: [
                      {
                        type: "Identifier",
                        loc: "15:11-15:12",
                        name: "b",
                      },
                    ],
                  },
                ],
              },
              {
                type: "Identifier",
                loc: "15:16-15:17",
                name: "c",
              },
            ],
          },
          init: {
            type: "Literal",
            loc: "15:21-15:22",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "17:1-17:22",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "17:5-17:21",
          id: {
            type: "ArrayPattern",
            loc: "17:5-17:17",
            elements: [
              {
                type: "Identifier",
                loc: "17:6-17:7",
                name: "a",
              },
              {
                type: "Identifier",
                loc: "17:9-17:10",
                name: "b",
              },
              {
                type: "RestElement",
                loc: "17:12-17:16",
                argument: {
                  type: "Identifier",
                  loc: "17:15-17:16",
                  name: "c",
                },
              },
            ],
          },
          init: {
            type: "Literal",
            loc: "17:20-17:21",
            value: 1,
          },
        },
      ],
    },
    {
      type: "VariableDeclaration",
      loc: "19:1-19:31",
      kind: "var",
      declarations: [
        {
          type: "VariableDeclarator",
          loc: "19:5-19:30",
          id: {
            type: "ArrayPattern",
            loc: "19:5-19:26",
            elements: [
              {
                type: "RestElement",
                loc: "19:6-19:25",
                argument: {
                  type: "ArrayPattern",
                  loc: "19:9-19:25",
                  elements: [
                    {
                      type: "Identifier",
                      loc: "19:10-19:11",
                      name: "c",
                    },
                    {
                      type: "Identifier",
                      loc: "19:13-19:14",
                      name: "d",
                    },
                    {
                      type: "RestElement",
                      loc: "19:16-19:24",
                      argument: {
                        type: "ArrayPattern",
                        loc: "19:19-19:24",
                        elements: [
                          {
                            type: "ObjectPattern",
                            loc: "19:20-19:23",
                            properties: [
                              {
                                type: "Property",
                                loc: "19:21-19:22",
                                key: null,
                                value: {
                                  type: "Identifier",
                                  loc: "19:21-19:22",
                                  name: "e",
                                },
                                computed: false,
                              },
                            ],
                          },
                        ],
                      },
                    },
                  ],
                },
              },
            ],
          },
          init: {
            type: "Literal",
            loc: "19:29-19:30",
            value: 1,
          },
        },
      ],
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}