{
  type: "Program",
  loc: "1:0-15:17",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:6",
      kind: {
        type: "AssignmentExpression",
        loc: "1:0-1:5",
        operator: "=",
        left: {
          type: "Identifier",
          loc: "1:0-1:1",
          name: "a",
        },
        right: {
          type: "Literal",
          loc: "1:4-1:5",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:8",
      kind: {
        type: "AssignmentExpression",
        loc: "3:0-3:7",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "3:0-3:3",
          elements: [
            {
              type: "Identifier",
              loc: "3:1-3:2",
              name: "a",
            },
          ],
        },
        right: {
          type: "Literal",
          loc: "3:6-3:7",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:14",
      kind: {
        type: "AssignmentExpression",
        loc: "5:0-5:13",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "5:0-5:9",
          elements: [
            {
              type: "Identifier",
              loc: "5:1-5:2",
              name: "a",
            },
            {
              type: "RestElement",
              loc: "5:4-5:8",
              argument: {
                type: "Identifier",
                loc: "5:7-5:8",
                name: "b",
              },
            },
          ],
        },
        right: {
          type: "Literal",
          loc: "5:12-5:13",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:0-7:16",
      kind: {
        type: "AssignmentExpression",
        loc: "7:0-7:15",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "7:0-7:11",
          elements: [
            {
              type: "Identifier",
              loc: "7:1-7:2",
              name: "a",
            },
            {
              type: "RestElement",
              loc: "7:4-7:10",
              argument: {
                type: "ArrayPattern",
                loc: "7:7-7:10",
                elements: [
                  {
                    type: "Identifier",
                    loc: "7:8-7:9",
                    name: "b",
                  },
                ],
              },
            },
          ],
        },
        right: {
          type: "Literal",
          loc: "7:14-7:15",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:0-9:15",
      kind: {
        type: "AssignmentExpression",
        loc: "9:0-9:14",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "9:0-9:10",
          elements: [
            {
              type: "Identifier",
              loc: "9:1-9:2",
              name: "a",
            },
            null,
            {
              type: "Identifier",
              loc: "9:4-9:5",
              name: "b",
            },
            null,
            {
              type: "Identifier",
              loc: "9:7-9:8",
              name: "c",
            },
          ],
        },
        right: {
          type: "Literal",
          loc: "9:13-9:14",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:0-11:10",
      kind: {
        type: "AssignmentExpression",
        loc: "11:0-11:9",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "11:0-11:5",
          elements: [
            {
              type: "Identifier",
              loc: "11:1-11:2",
              name: "a",
            },
            null,
          ],
        },
        right: {
          type: "Literal",
          loc: "11:8-11:9",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:0-13:22",
      kind: {
        type: "AssignmentExpression",
        loc: "13:0-13:21",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "13:0-13:17",
          elements: [
            {
              type: "AssignmentPattern",
              loc: "13:1-13:6",
              left: {
                type: "Identifier",
                loc: "13:1-13:2",
                name: "a",
              },
              right: {
                type: "Literal",
                loc: "13:5-13:6",
                value: 1,
              },
            },
            {
              type: "Identifier",
              loc: "13:8-13:9",
              name: "b",
            },
            {
              type: "AssignmentPattern",
              loc: "13:11-13:16",
              left: {
                type: "Identifier",
                loc: "13:11-13:12",
                name: "c",
              },
              right: {
                type: "Literal",
                loc: "13:15-13:16",
                value: 2,
              },
            },
          ],
        },
        right: {
          type: "Literal",
          loc: "13:20-13:21",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "15:0-15:17",
      kind: {
        type: "AssignmentExpression",
        loc: "15:0-15:16",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "15:0-15:12",
          elements: [
            {
              type: "AssignmentPattern",
              loc: "15:1-15:11",
              left: {
                type: "ArrayPattern",
                loc: "15:1-15:7",
                elements: [
                  {
                    type: "Identifier",
                    loc: "15:2-15:3",
                    name: "a",
                  },
                  {
                    type: "Identifier",
                    loc: "15:5-15:6",
                    name: "b",
                  },
                ],
              },
              right: {
                type: "Literal",
                loc: "15:10-15:11",
                value: 1,
              },
            },
          ],
        },
        right: {
          type: "Literal",
          loc: "15:15-15:16",
          value: 2,
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}