{
  type: "Program",
  loc: "1:1-17:118",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:6",
      kind: {
        type: "Literal",
        loc: "1:1-1:5",
        raw: "/a*/",
        value: {
          pattern: "a*",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 0,
                  max: null,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "2:1-2:6",
      kind: {
        type: "Literal",
        loc: "2:1-2:5",
        raw: "/a+/",
        value: {
          pattern: "a+",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: null,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:6",
      kind: {
        type: "Literal",
        loc: "3:1-3:5",
        raw: "/a?/",
        value: {
          pattern: "a?",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 0,
                  max: 1,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "4:1-4:8",
      kind: {
        type: "Literal",
        loc: "4:1-4:7",
        raw: "/a{1}/",
        value: {
          pattern: "a{1}",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: 1,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:11",
      kind: {
        type: "Literal",
        loc: "5:1-5:10",
        raw: "/a{123,}/",
        value: {
          pattern: "a{123,}",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 123,
                  max: null,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "6:1-6:10",
      kind: {
        type: "Literal",
        loc: "6:1-6:9",
        raw: "/a{1,2}/",
        value: {
          pattern: "a{1,2}",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: 2,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:7",
      kind: {
        type: "Literal",
        loc: "9:1-9:6",
        raw: "/a*?/",
        value: {
          pattern: "a*?",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 0,
                  max: null,
                  is_greedy: false,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "10:1-10:7",
      kind: {
        type: "Literal",
        loc: "10:1-10:6",
        raw: "/a+?/",
        value: {
          pattern: "a+?",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: null,
                  is_greedy: false,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:1-11:7",
      kind: {
        type: "Literal",
        loc: "11:1-11:6",
        raw: "/a??/",
        value: {
          pattern: "a??",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 0,
                  max: 1,
                  is_greedy: false,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "12:1-12:9",
      kind: {
        type: "Literal",
        loc: "12:1-12:8",
        raw: "/a{1}?/",
        value: {
          pattern: "a{1}?",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: 1,
                  is_greedy: false,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:1-13:10",
      kind: {
        type: "Literal",
        loc: "13:1-13:9",
        raw: "/a{1,}?/",
        value: {
          pattern: "a{1,}?",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: null,
                  is_greedy: false,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "14:1-14:11",
      kind: {
        type: "Literal",
        loc: "14:1-14:10",
        raw: "/a{1,2}?/",
        value: {
          pattern: "a{1,2}?",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: 2,
                  is_greedy: false,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:1-17:118",
      kind: {
        type: "Literal",
        loc: "17:1-17:117",
        raw: "/a{1,9876543219876543219876543219876543219876543219876543219876543219876543219876543219876543219876543219876543210}/",
        value: {
          pattern: "a{1,9876543219876543219876543219876543219876543219876543219876543219876543219876543219876543219876543219876543210}",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: null,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}