{
  type: "Program",
  loc: "1:1-23:48",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:6",
      kind: {
        type: "Literal",
        loc: "1:1-1:5",
        raw: "/a*/",
        value: {
          pattern: "a*",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 0,
                  max: null,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "2:1-2:6",
      kind: {
        type: "Literal",
        loc: "2:1-2:5",
        raw: "/a+/",
        value: {
          pattern: "a+",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: null,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:6",
      kind: {
        type: "Literal",
        loc: "3:1-3:5",
        raw: "/a?/",
        value: {
          pattern: "a?",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 0,
                  max: 1,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "4:1-4:8",
      kind: {
        type: "Literal",
        loc: "4:1-4:7",
        raw: "/a{1}/",
        value: {
          pattern: "a{1}",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: 1,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:11",
      kind: {
        type: "Literal",
        loc: "5:1-5:10",
        raw: "/a{123,}/",
        value: {
          pattern: "a{123,}",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 123,
                  max: null,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "6:1-6:10",
      kind: {
        type: "Literal",
        loc: "6:1-6:9",
        raw: "/a{1,2}/",
        value: {
          pattern: "a{1,2}",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: 2,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:7",
      kind: {
        type: "Literal",
        loc: "9:1-9:6",
        raw: "/a*?/",
        value: {
          pattern: "a*?",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 0,
                  max: null,
                  is_greedy: false,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "10:1-10:7",
      kind: {
        type: "Literal",
        loc: "10:1-10:6",
        raw: "/a+?/",
        value: {
          pattern: "a+?",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: null,
                  is_greedy: false,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:1-11:7",
      kind: {
        type: "Literal",
        loc: "11:1-11:6",
        raw: "/a??/",
        value: {
          pattern: "a??",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 0,
                  max: 1,
                  is_greedy: false,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "12:1-12:9",
      kind: {
        type: "Literal",
        loc: "12:1-12:8",
        raw: "/a{1}?/",
        value: {
          pattern: "a{1}?",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: 1,
                  is_greedy: false,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:1-13:10",
      kind: {
        type: "Literal",
        loc: "13:1-13:9",
        raw: "/a{1,}?/",
        value: {
          pattern: "a{1,}?",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: null,
                  is_greedy: false,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "14:1-14:11",
      kind: {
        type: "Literal",
        loc: "14:1-14:10",
        raw: "/a{1,2}?/",
        value: {
          pattern: "a{1,2}?",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: 2,
                  is_greedy: false,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:1-17:11",
      kind: {
        type: "Literal",
        loc: "17:1-17:10",
        raw: "/a\u{2}b/",
        value: {
          pattern: "a\u{2}b",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Literal",
                  value: "a",
                },
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "u",
                  },
                  min: 2,
                  max: 2,
                  is_greedy: true,
                },
                {
                  type: "Literal",
                  value: "b",
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "20:1-20:27",
      kind: {
        type: "Literal",
        loc: "20:1-20:26",
        raw: "/a{99999999999999999999}/",
        value: {
          pattern: "a{99999999999999999999}",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 18446744073709551615,
                  max: 18446744073709551615,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "21:1-21:28",
      kind: {
        type: "Literal",
        loc: "21:1-21:27",
        raw: "/a{99999999999999999999,}/",
        value: {
          pattern: "a{99999999999999999999,}",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 18446744073709551615,
                  max: null,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "22:1-22:29",
      kind: {
        type: "Literal",
        loc: "22:1-22:28",
        raw: "/a{1,99999999999999999999}/",
        value: {
          pattern: "a{1,99999999999999999999}",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 1,
                  max: 18446744073709551615,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "23:1-23:48",
      kind: {
        type: "Literal",
        loc: "23:1-23:47",
        raw: "/a{99999999999999999999,99999999999999999999}/",
        value: {
          pattern: "a{99999999999999999999,99999999999999999999}",
          flags: "",
        },
        regexp: {
          type: "RegExp",
          alternatives: [
            {
              type: "Alternative",
              terms: [
                {
                  type: "Quantifier",
                  term: {
                    type: "Literal",
                    value: "a",
                  },
                  min: 18446744073709551615,
                  max: 18446744073709551615,
                  is_greedy: true,
                },
              ],
            },
          ],
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}