{
  type: "Program",
  loc: "1:1-26:9",
  body: [
    {
      type: "ExpressionStatement",
      loc: "3:1-3:9",
      kind: {
        type: "Identifier",
        loc: "3:1-3:8",
        name: "marker1",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:9",
      kind: {
        type: "Identifier",
        loc: "7:1-7:8",
        name: "marker2",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "12:1-12:9",
      kind: {
        type: "Identifier",
        loc: "12:1-12:8",
        name: "marker3",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "16:1-16:9",
      kind: {
        type: "Identifier",
        loc: "16:1-16:8",
        name: "marker4",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "20:1-20:9",
      kind: {
        type: "Identifier",
        loc: "20:1-20:8",
        name: "marker5",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "26:1-26:9",
      kind: {
        type: "Identifier",
        loc: "26:1-26:8",
        name: "marker6",
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}