{
  type: "Program",
  loc: "1:1-25:33",
  body: [
    {
      type: "FunctionDeclaration",
      loc: "1:1-1:22",
      id: {
        type: "Identifier",
        loc: "1:10-1:13",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "1:16-1:22",
        body: [
          {
            type: "ExpressionStatement",
            loc: "1:18-1:20",
            kind: {
              type: "Identifier",
              loc: "1:18-1:19",
              name: "a",
            },
          },
        ],
      },
      async: false,
      generator: false,
      has_use_strict_directive: false,
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:25",
      kind: {
        type: "FunctionExpression",
        loc: "3:2-3:23",
        id: {
          type: "Identifier",
          loc: "3:11-3:14",
          name: "foo",
        },
        params: [],
        body: {
          type: "Block",
          loc: "3:17-3:23",
          body: [
            {
              type: "ExpressionStatement",
              loc: "3:19-3:21",
              kind: {
                type: "Identifier",
                loc: "3:19-3:20",
                name: "a",
              },
            },
          ],
        },
        async: false,
        generator: false,
        has_use_strict_directive: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:18",
      kind: {
        type: "FunctionExpression",
        loc: "5:2-5:16",
        id: null,
        params: [],
        body: {
          type: "Block",
          loc: "5:14-5:16",
          body: [],
        },
        async: false,
        generator: false,
        has_use_strict_directive: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:23",
      kind: {
        type: "FunctionExpression",
        loc: "7:2-7:21",
        id: null,
        params: [
          {
            type: "Identifier",
            loc: "7:12-7:17",
            name: "param",
          },
        ],
        body: {
          type: "Block",
          loc: "7:19-7:21",
          body: [],
        },
        async: false,
        generator: false,
        has_use_strict_directive: false,
      },
    },
    {
      type: "FunctionDeclaration",
      loc: "9:1-9:24",
      id: {
        type: "Identifier",
        loc: "9:16-9:19",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "9:22-9:24",
        body: [],
      },
      async: true,
      generator: false,
      has_use_strict_directive: false,
    },
    {
      type: "FunctionDeclaration",
      loc: "11:1-11:19",
      id: {
        type: "Identifier",
        loc: "11:11-11:14",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "11:17-11:19",
        body: [],
      },
      async: false,
      generator: true,
      has_use_strict_directive: false,
    },
    {
      type: "FunctionDeclaration",
      loc: "13:1-13:25",
      id: {
        type: "Identifier",
        loc: "13:17-13:20",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "13:23-13:25",
        body: [],
      },
      async: true,
      generator: true,
      has_use_strict_directive: false,
    },
    {
      type: "ExpressionStatement",
      loc: "15:1-15:28",
      kind: {
        type: "FunctionExpression",
        loc: "15:2-15:26",
        id: {
          type: "Identifier",
          loc: "15:18-15:21",
          name: "foo",
        },
        params: [],
        body: {
          type: "Block",
          loc: "15:24-15:26",
          body: [],
        },
        async: true,
        generator: true,
        has_use_strict_directive: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:1-17:25",
      kind: {
        type: "FunctionExpression",
        loc: "17:2-17:23",
        id: null,
        params: [],
        body: {
          type: "Block",
          loc: "17:21-17:23",
          body: [],
        },
        async: true,
        generator: true,
        has_use_strict_directive: false,
      },
    },
    {
      type: "FunctionDeclaration",
      loc: "19:1-19:25",
      id: {
        type: "Identifier",
        loc: "19:10-19:13",
        name: "foo",
      },
      params: [
        {
          type: "Identifier",
          loc: "19:14-19:15",
          name: "a",
        },
        {
          type: "Identifier",
          loc: "19:17-19:18",
          name: "b",
        },
        {
          type: "Identifier",
          loc: "19:20-19:21",
          name: "c",
        },
      ],
      body: {
        type: "Block",
        loc: "19:23-19:25",
        body: [],
      },
      async: false,
      generator: false,
      has_use_strict_directive: false,
    },
    {
      type: "FunctionDeclaration",
      loc: "21:1-21:26",
      id: {
        type: "Identifier",
        loc: "21:10-21:13",
        name: "foo",
      },
      params: [
        {
          type: "Identifier",
          loc: "21:14-21:15",
          name: "a",
        },
        {
          type: "Identifier",
          loc: "21:17-21:18",
          name: "b",
        },
        {
          type: "Identifier",
          loc: "21:20-21:21",
          name: "c",
        },
      ],
      body: {
        type: "Block",
        loc: "21:24-21:26",
        body: [],
      },
      async: false,
      generator: false,
      has_use_strict_directive: false,
    },
    {
      type: "FunctionDeclaration",
      loc: "23:1-23:28",
      id: {
        type: "Identifier",
        loc: "23:10-23:13",
        name: "foo",
      },
      params: [
        {
          type: "Identifier",
          loc: "23:14-23:15",
          name: "a",
        },
        {
          type: "Identifier",
          loc: "23:17-23:18",
          name: "b",
        },
        {
          type: "RestElement",
          loc: "23:20-23:24",
          argument: {
            type: "Identifier",
            loc: "23:23-23:24",
            name: "c",
          },
        },
      ],
      body: {
        type: "Block",
        loc: "23:26-23:28",
        body: [],
      },
      async: false,
      generator: false,
      has_use_strict_directive: false,
    },
    {
      type: "FunctionDeclaration",
      loc: "25:1-25:33",
      id: {
        type: "Identifier",
        loc: "25:10-25:13",
        name: "foo",
      },
      params: [
        {
          type: "Identifier",
          loc: "25:14-25:15",
          name: "a",
        },
        {
          type: "RestElement",
          loc: "25:17-25:29",
          argument: {
            type: "ArrayPattern",
            loc: "25:20-25:29",
            elements: [
              {
                type: "Identifier",
                loc: "25:21-25:22",
                name: "b",
              },
              {
                type: "RestElement",
                loc: "25:24-25:28",
                argument: {
                  type: "Identifier",
                  loc: "25:27-25:28",
                  name: "c",
                },
              },
            ],
          },
        },
      ],
      body: {
        type: "Block",
        loc: "25:31-25:33",
        body: [],
      },
      async: false,
      generator: false,
      has_use_strict_directive: false,
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}