{
  type: "Program",
  loc: "1:1-14:17",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:5",
      kind: {
        type: "Identifier",
        loc: "1:1-1:4",
        name: "abc",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:9",
      kind: {
        type: "Identifier",
        loc: "3:1-3:8",
        name: "ab",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:15",
      kind: {
        type: "Identifier",
        loc: "5:1-5:14",
        name: "abc",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "8:1-8:10",
      kind: {
        type: "Identifier",
        loc: "8:1-8:9",
        name: "aÿF",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "10:1-10:25",
      kind: {
        type: "Identifier",
        loc: "10:1-10:24",
        name: "abcჿ",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "12:1-12:8",
      kind: {
        type: "Identifier",
        loc: "12:1-12:7",
        name: "b",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "14:1-14:17",
      kind: {
        type: "Identifier",
        loc: "14:1-14:16",
        name: "bcd",
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}