[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: NewClosure r0, c11
    35: StoreGlobal r0, c12
    38: NewClosure r0, c13
    41: StoreGlobal r0, c14
    44: NewClosure r0, c15
    47: StoreGlobal r0, c16
    50: NewClosure r0, c17
    53: StoreGlobal r0, c18
    56: LoadUndefined r0
    58: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: notNeededDueToParameterName]
    2: [String: notNeededDueToParameterName]
    3: [BytecodeFunction: notNeededDueToLexicalName]
    4: [String: notNeededDueToLexicalName]
    5: [BytecodeFunction: notNeededDueToLexicalNameAndParameterExpressionsNoUse]
    6: [String: notNeededDueToLexicalNameAndParameterExpressionsNoUse]
    7: [BytecodeFunction: neededDueToLexicalNameAndParameterExpressionsWithUse]
    8: [String: neededDueToLexicalNameAndParameterExpressionsWithUse]
    9: [BytecodeFunction: neededWithVarName]
    10: [String: neededWithVarName]
    11: [BytecodeFunction: neededWithVarFunctionName]
    12: [String: neededWithVarFunctionName]
    13: [BytecodeFunction: notNeededSinceUseCaught]
    14: [String: notNeededSinceUseCaught]
    15: [BytecodeFunction: neededDueToDirectEval]
    16: [String: neededDueToDirectEval]
    17: [BytecodeFunction: notNeededDueToIndirectEval]
    18: [String: notNeededDueToIndirectEval]
}

[BytecodeFunction: notNeededDueToParameterName] {
  Parameters: 1, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: notNeededDueToLexicalName] {
  Parameters: 0, Registers: 2
    0: LoadImmediate r0, 1
    3: LoadUndefined r1
    5: Ret r1
}

[BytecodeFunction: notNeededDueToLexicalNameAndParameterExpressionsNoUse] {
  Parameters: 1, Registers: 2
     0: JumpNotUndefined a0, 6 (.L0)
     3: LoadImmediate a0, 1
  .L0:
     6: LoadEmpty r0
     8: CheckTdz r0, c0
    11: LoadImmediate r0, 1
    14: LoadUndefined r1
    16: Ret r1
  Constant Table:
    0: [String: arguments]
}

[BytecodeFunction: neededDueToLexicalNameAndParameterExpressionsWithUse] {
  Parameters: 1, Registers: 3
     0: NewUnmappedArguments r0
     2: JumpNotUndefined a0, 6 (.L0)
     5: Mov a0, r0
  .L0:
     8: LoadImmediate r1, 1
    11: LoadUndefined r2
    13: Ret r2
}

[BytecodeFunction: neededWithVarName] {
  Parameters: 0, Registers: 2
    0: NewMappedArguments r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: neededWithVarFunctionName] {
  Parameters: 0, Registers: 2
    0: NewClosure r0, c0
    3: NewMappedArguments r0
    5: LoadUndefined r1
    7: Ret r1
  Constant Table:
    0: [BytecodeFunction: arguments]
}

[BytecodeFunction: arguments] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: notNeededSinceUseCaught] {
  Parameters: 0, Registers: 2
    0: LoadImmediate r0, 1
    3: LoadUndefined r1
    5: Ret r1
}

[BytecodeFunction: neededDueToDirectEval] {
  Parameters: 0, Registers: 2
     0: PushFunctionScope c0
     2: StoreToScope <this>, 0, 0
     6: StoreToScope r0, 2, 0
    10: NewUnmappedArguments r0
    12: StoreToScope r0, 1, 0
    16: LoadGlobal r0, c1
    19: LoadConstant r1, c2
    22: CallMaybeEval r0, r0, r1, 1
    27: LoadUndefined r0
    29: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [String: eval]
    2: [String: ]
}

[BytecodeFunction: notNeededDueToIndirectEval] {
  Parameters: 0, Registers: 2
     0: LoadGlobal r0, c0
     3: JumpNullish r0, 13 (.L0)
     6: LoadConstant r1, c1
     9: Call r0, r0, r1, 1
    14: Jump 4 (.L1)
  .L0:
    16: LoadUndefined r0
  .L1:
    18: LoadUndefined r0
    20: Ret r0
  Constant Table:
    0: [String: eval]
    1: [String: ]
}
