[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: LoadUndefined r0
    44: Ret r0
  Constant Table:
    0: [BytecodeFunction: notNeededDueToParameterName]
    1: [String: notNeededDueToParameterName]
    2: [BytecodeFunction: notNeededDueToLexicalName]
    3: [String: notNeededDueToLexicalName]
    4: [BytecodeFunction: notNeededDueToLexicalNameAndParameterExpressionsNoUse]
    5: [String: notNeededDueToLexicalNameAndParameterExpressionsNoUse]
    6: [BytecodeFunction: neededDueToLexicalNameAndParameterExpressionsWithUse]
    7: [String: neededDueToLexicalNameAndParameterExpressionsWithUse]
    8: [BytecodeFunction: neededWithVarName]
    9: [String: neededWithVarName]
    10: [BytecodeFunction: neededWithVarFunctionName]
    11: [String: neededWithVarFunctionName]
    12: [BytecodeFunction: notNeededSinceUseCaught]
    13: [String: notNeededSinceUseCaught]
}

[BytecodeFunction: notNeededDueToParameterName] {
  Parameters: 1, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: notNeededDueToLexicalName] {
  Parameters: 0, Registers: 2
    0: LoadImmediate r0, 1
    3: LoadUndefined r1
    5: Ret r1
}

[BytecodeFunction: notNeededDueToLexicalNameAndParameterExpressionsNoUse] {
  Parameters: 1, Registers: 2
     0: JumpNotUndefined a0, 6 (.L0)
     3: LoadImmediate a0, 1
  .L0:
     6: LoadEmpty r0
     8: CheckTdz r0, c0
    11: LoadImmediate r0, 1
    14: LoadUndefined r1
    16: Ret r1
  Constant Table:
    0: [String: arguments]
}

[BytecodeFunction: neededDueToLexicalNameAndParameterExpressionsWithUse] {
  Parameters: 1, Registers: 3
     0: NewUnmappedArguments r0
     2: JumpNotUndefined a0, 6 (.L0)
     5: Mov a0, r0
  .L0:
     8: LoadImmediate r1, 1
    11: LoadUndefined r2
    13: Ret r2
}

[BytecodeFunction: neededWithVarName] {
  Parameters: 0, Registers: 2
    0: NewMappedArguments r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: neededWithVarFunctionName] {
  Parameters: 0, Registers: 2
    0: NewClosure r0, c0
    3: NewMappedArguments r0
    5: LoadUndefined r1
    7: Ret r1
  Constant Table:
    0: [BytecodeFunction: arguments]
}

[BytecodeFunction: arguments] {
  Parameters: 0, Registers: 1
    0: LoadUndefined r0
    2: Ret r0
}

[BytecodeFunction: notNeededSinceUseCaught] {
  Parameters: 0, Registers: 2
    0: LoadImmediate r0, 1
    3: LoadUndefined r1
    5: Ret r1
}
