[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: LoadUndefined r0
    16: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: bindingReferenced]
    2: [String: bindingReferenced]
    3: [BytecodeFunction: capturedByArrow]
    4: [String: capturedByArrow]
}

[BytecodeFunction: bindingReferenced] {
  Parameters: 0, Registers: 2
     0: NewUnmappedArguments r0
     2: LoadImmediate r1, 1
     5: Add r1, r0, r1
     9: LoadUndefined r1
    11: Ret r1
}

[BytecodeFunction: capturedByArrow] {
  Parameters: 0, Registers: 1
     0: PushFunctionScope c0
     2: NewUnmappedArguments r0
     4: StoreToScope r0, 0, 0
     8: NewClosure r0, c1
    11: LoadUndefined r0
    13: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: Ret r0
}
