[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: GlobalInit c0
     2: NewClosure r0, c1
     5: StoreGlobal r0, c2
     8: NewClosure r0, c3
    11: StoreGlobal r0, c4
    14: NewClosure r0, c5
    17: StoreGlobal r0, c6
    20: NewClosure r0, c7
    23: StoreGlobal r0, c8
    26: NewClosure r0, c9
    29: StoreGlobal r0, c10
    32: LoadUndefined r0
    34: Ret r0
  Constant Table:
    0: [GlobalNames]
    1: [BytecodeFunction: strictForcesUnmapped]
    2: [String: strictForcesUnmapped]
    3: [BytecodeFunction: defaultForcesUnmapped]
    4: [String: defaultForcesUnmapped]
    5: [BytecodeFunction: destructuringForcesUnmapped]
    6: [String: destructuringForcesUnmapped]
    7: [BytecodeFunction: restForcesUnmapped]
    8: [String: restForcesUnmapped]
    9: [BytecodeFunction: withArguments]
    10: [String: withArguments]
}

[BytecodeFunction: strictForcesUnmapped] {
  Parameters: 0, Registers: 2
    0: NewUnmappedArguments r0
    2: LoadUndefined r1
    4: Ret r1
}

[BytecodeFunction: defaultForcesUnmapped] {
  Parameters: 1, Registers: 2
     0: NewUnmappedArguments r0
     2: JumpNotUndefined a0, 6 (.L0)
     5: LoadImmediate a0, 1
  .L0:
     8: LoadUndefined r1
    10: Ret r1
}

[BytecodeFunction: destructuringForcesUnmapped] {
  Parameters: 1, Registers: 3
    0: NewUnmappedArguments r1
    2: GetNamedProperty r0, a0, c0
    6: LoadUndefined r2
    8: Ret r2
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: restForcesUnmapped] {
  Parameters: 0, Registers: 3
    0: NewUnmappedArguments r1
    2: RestParameter r0
    4: LoadUndefined r2
    6: Ret r2
}

[BytecodeFunction: withArguments] {
  Parameters: 3, Registers: 2
    0: NewUnmappedArguments r0
    2: LoadUndefined r1
    4: Ret r1
}
