[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: LoadImmediate r0, 0
    45: StoreGlobal r0, c14
    48: LoadUndefined r0
    50: Ret r0
  Constant Table:
    0: [BytecodeFunction: emptyObject]
    1: [String: emptyObject]
    2: [BytecodeFunction: shorthandProperties]
    3: [String: shorthandProperties]
    4: [BytecodeFunction: initializedProperties]
    5: [String: initializedProperties]
    6: [BytecodeFunction: stringPropertyKeys]
    7: [String: stringPropertyKeys]
    8: [BytecodeFunction: computedPropertyKeys]
    9: [String: computedPropertyKeys]
    10: [BytecodeFunction: spread]
    11: [String: spread]
    12: [BytecodeFunction: propertyNamesNotResolved]
    13: [String: propertyNamesNotResolved]
    14: [String: global]
}

[BytecodeFunction: emptyObject] {
  Parameters: 0, Registers: 1
    0: NewObject r0
    2: Ret r0
}

[BytecodeFunction: shorthandProperties] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 1
     3: NewObject r1
     5: LoadGlobal r2, c0
     8: DefineNamedProperty r1, c0, r2
    12: DefineNamedProperty r1, c1, r0
    16: DefineNamedProperty r1, c2, a0
    20: Ret r1
  Constant Table:
    0: [String: global]
    1: [String: local]
    2: [String: param]
}

[BytecodeFunction: initializedProperties] {
  Parameters: 0, Registers: 3
     0: NewObject r0
     2: LoadImmediate r1, 1
     5: DefineNamedProperty r0, c0, r1
     9: LoadImmediate r1, 2
    12: LoadImmediate r2, 3
    15: Add r1, r1, r2
    19: DefineNamedProperty r0, c1, r1
    23: Ret r0
  Constant Table:
    0: [String: a]
    1: [String: global]
}

[BytecodeFunction: stringPropertyKeys] {
  Parameters: 0, Registers: 2
     0: NewObject r0
     2: LoadImmediate r1, 1
     5: DefineNamedProperty r0, c0, r1
     9: LoadImmediate r1, 2
    12: DefineNamedProperty r0, c1, r1
    16: Ret r0
  Constant Table:
    0: [String: a]
    1: [String: b]
}

[BytecodeFunction: computedPropertyKeys] {
  Parameters: 0, Registers: 3
     0: NewObject r0
     2: LoadConstant r1, c0
     5: LoadImmediate r2, 1
     8: DefineProperty r0, r1, r2, 0
    13: LoadImmediate r1, 2
    16: LoadImmediate r2, 3
    19: DefineProperty r0, r1, r2, 0
    24: LoadImmediate r1, 4
    27: LoadImmediate r2, 5
    30: Add r1, r1, r2
    34: LoadImmediate r2, 6
    37: DefineProperty r0, r1, r2, 0
    42: Ret r0
  Constant Table:
    0: [String: a]
}

[BytecodeFunction: spread] {
  Parameters: 1, Registers: 3
     0: NewObject r0
     2: CopyDataProperties r0, a0, a0, 0
     7: LoadImmediate r1, 1
    10: LoadImmediate r2, 2
    13: Add r1, r1, r2
    17: CopyDataProperties r0, r1, r1, 0
    22: Ret r0
}

[BytecodeFunction: propertyNamesNotResolved] {
  Parameters: 0, Registers: 5
     0: LoadEmpty r1
     2: LoadEmpty r2
     4: NewObject r3
     6: LoadImmediate r4, 1
     9: DefineNamedProperty r3, c0, r4
    13: GetNamedProperty r0, r3, c0
    17: NewObject r3
    19: CheckTdz r1, c1
    22: DefineNamedProperty r3, c1, r1
    26: CheckTdz r2, c3
    29: DefineNamedProperty r3, c2, r2
    33: GetNamedProperty r1, r3, c1
    37: GetNamedProperty r2, r3, c3
    41: LoadUndefined r3
    43: Ret r3
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: d]
    3: [String: c]
}
