[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 0
     3: StoreGlobal r0, c0
     6: NewClosure r0, c1
     9: StoreGlobal r0, c2
    12: NewClosure r0, c3
    15: StoreGlobal r0, c4
    18: NewClosure r0, c5
    21: StoreGlobal r0, c6
    24: NewClosure r0, c7
    27: StoreGlobal r0, c8
    30: NewClosure r0, c9
    33: StoreGlobal r0, c10
    36: NewClosure r0, c11
    39: StoreGlobal r0, c12
    42: LoadUndefined r0
    44: Ret r0
  Constant Table:
    0: [String: global]
    1: [BytecodeFunction: emptyObject]
    2: [String: emptyObject]
    3: [BytecodeFunction: shorthandProperties]
    4: [String: shorthandProperties]
    5: [BytecodeFunction: initializedProperties]
    6: [String: initializedProperties]
    7: [BytecodeFunction: stringPropertyKeys]
    8: [String: stringPropertyKeys]
    9: [BytecodeFunction: computedPropertyKeys]
    10: [String: computedPropertyKeys]
    11: [BytecodeFunction: spread]
    12: [String: spread]
}

[BytecodeFunction: emptyObject] {
  Parameters: 0, Registers: 1
    0: NewObject r0
    2: Ret r0
}

[BytecodeFunction: shorthandProperties] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 1
     3: NewObject r1
     5: LoadGlobal r2, c0
     8: DefineNamedProperty r1, c0, r2
    12: DefineNamedProperty r1, c1, r0
    16: DefineNamedProperty r1, c2, a0
    20: Ret r1
  Constant Table:
    0: [String: global]
    1: [String: local]
    2: [String: param]
}

[BytecodeFunction: initializedProperties] {
  Parameters: 0, Registers: 3
     0: NewObject r0
     2: LoadImmediate r1, 1
     5: DefineNamedProperty r0, c0, r1
     9: LoadImmediate r1, 2
    12: LoadImmediate r2, 3
    15: Add r1, r1, r2
    19: DefineNamedProperty r0, c1, r1
    23: Ret r0
  Constant Table:
    0: [String: a]
    1: [String: global]
}

[BytecodeFunction: stringPropertyKeys] {
  Parameters: 0, Registers: 2
     0: NewObject r0
     2: LoadImmediate r1, 1
     5: DefineNamedProperty r0, c0, r1
     9: LoadImmediate r1, 2
    12: DefineNamedProperty r0, c1, r1
    16: Ret r0
  Constant Table:
    0: [String: a]
    1: [String: b]
}

[BytecodeFunction: computedPropertyKeys] {
  Parameters: 0, Registers: 3
     0: NewObject r0
     2: LoadConstant r1, c0
     5: LoadImmediate r2, 1
     8: DefineProperty r0, r1, r2, 0
    13: LoadImmediate r1, 2
    16: LoadImmediate r2, 3
    19: DefineProperty r0, r1, r2, 0
    24: LoadImmediate r1, 4
    27: LoadImmediate r2, 5
    30: Add r1, r1, r2
    34: LoadImmediate r2, 6
    37: DefineProperty r0, r1, r2, 0
    42: Ret r0
  Constant Table:
    0: [String: a]
}

[BytecodeFunction: spread] {
  Parameters: 1, Registers: 3
     0: NewObject r0
     2: CopyDataProperties r0, a0
     5: LoadImmediate r1, 1
     8: LoadImmediate r2, 2
    11: Add r1, r1, r2
    15: CopyDataProperties r0, r1
    18: Ret r0
}
