[CompiledRegExp: /aBc/] {
  Flags: "i"
  Match Start: Code Points("A", "a")
     0: MarkCapturePoint(0)
     2: CodePointSet("A", "a")
     4: CodePointSet("B", "b")
     6: CodePointSet("C", "c")
     8: MarkCapturePoint(1)
    10: Accept
}

[CompiledRegExp: /-/] {
  Flags: "i"
  Match Start: Code Points("-")
     0: MarkCapturePoint(0)
     2: CodePointLiteral(-)
     3: MarkCapturePoint(1)
     5: Accept
}
