[CompiledRegExp: /[\q{AB|Ab|aB|ab}]/] {
  Flags: "iv"
  Match Start: Code Points("A", "a")
     0: MarkCapturePoint(0)
     2: Branch(8, 14)
     5: MarkCapturePoint(1)
     7: Accept
     8: CodePointSet("A", "a")
    10: CodePointSet("B", "b")
    12: Jump(5)
    14: CodePointSet()
    16: Jump(5)
}

[CompiledRegExp: /[\q{AB}&&\q{ab}]/] {
  Flags: "iv"
  Match Start: Code Points("A", "a")
     0: MarkCapturePoint(0)
     2: Branch(8, 14)
     5: MarkCapturePoint(1)
     7: Accept
     8: CodePointSet("A", "a")
    10: CodePointSet("B", "b")
    12: Jump(5)
    14: CodePointSet()
    16: Jump(5)
}

[CompiledRegExp: /[\q{AB}--\q{ab}]/] {
  Flags: "iv"
  Match Start: Unknown
     0: MarkCapturePoint(0)
     2: CodePointSet()
     4: MarkCapturePoint(1)
     6: Accept
}
