[package]
name = "match_u32"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true
proc-macro2 = true

[dependencies]
syn = { version = "2.0.27", features = ["full", "visit-mut"] }
quote = "1.0.32"