[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: LoadUndefined r0
    20: Ret r0
  Constant Table:
    0: [BytecodeFunction: startScopeNoTDZInOuter]
    1: [String: startScopeNoTDZInOuter]
    2: [BytecodeFunction: startScopeTDZInOuter]
    3: [String: startScopeTDZInOuter]
    4: [BytecodeFunction: captures]
    5: [String: captures]
}

[BytecodeFunction: startScopeNoTDZInOuter] {
  Parameters: 0, Registers: 5
     0: LoadImmediate r2, 1
  .L0:
     3: LoadImmediate r4, 10
     6: LessThan r4, r2, r4, ic0
    11: JumpFalse r4, 26 (.L1)
    14: LoadEmpty r3
    16: CheckTdz r3, c0
    19: Add r4, r2, r3, ic1
    24: LoadImmediate r3, 0
    27: ToNumeric r2, r2
    30: Mov r4, r2
    33: Inc r2
    35: Jump -32 (.L0)
  .L1:
    37: LoadImmediate r0, 1
  .L2:
    40: LoadImmediate r4, 10
    43: LessThan r4, r0, r4, ic2
    48: JumpFalse r4, 26 (.L3)
    51: LoadEmpty r1
    53: CheckTdz r1, c0
    56: Add r4, r0, r1, ic3
    61: LoadImmediate r1, 0
    64: ToNumeric r0, r0
    67: Mov r4, r0
    70: Inc r0
    72: Jump -32 (.L2)
  .L3:
    74: LoadUndefined r4
    76: Ret r4
  Constant Table:
    0: [String: inner]
}

[BytecodeFunction: startScopeTDZInOuter] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r0
     2: CheckTdz r0, c0
  .L0:
     5: CheckTdz r0, c0
     8: LoadImmediate r2, 10
    11: LessThan r2, r0, r2, ic0
    16: JumpFalse r2, 33 (.L1)
    19: LoadEmpty r1
    21: LoadImmediate r2, 1
    24: CheckTdz r1, c1
    27: LoadImmediate r2, 2
    30: LoadImmediate r1, 0
    33: LoadImmediate r2, 3
    36: CheckTdz r0, c0
    39: ToNumeric r0, r0
    42: Mov r2, r0
    45: Inc r0
    47: Jump -42 (.L0)
  .L1:
    49: LoadUndefined r2
    51: Ret r2
  Constant Table:
    0: [String: x]
    1: [String: inner]
}

[BytecodeFunction: captures] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: LoadImmediate r1, 1
    11: StoreToScope r1, 0, 0
    15: DupScope 
  .L0:
    16: LoadFromScope r1, 0, 0
    20: CheckTdz r1, c1
    23: LoadImmediate r2, 10
    26: LessThan r1, r1, r2, ic0
    31: JumpFalse r1, 51 (.L1)
    34: PushLexicalScope c2
    36: LoadEmpty r1
    38: StoreToScope r1, 0, 0
    42: NewClosure r0, c3
    45: LoadImmediate r1, 2
    48: StoreToScope r1, 0, 0
    52: PopScope 
    53: DupScope 
    54: LoadFromScope r1, 0, 0
    58: CheckTdz r1, c1
    61: LoadImmediate r2, 1
    64: Add r1, r1, r2, ic1
    69: LoadFromScope r2, 0, 0
    73: CheckTdz r2, c1
    76: StoreToScope r1, 0, 0
    80: Jump -64 (.L0)
  .L1:
    82: PopScope 
    83: LoadUndefined r1
    85: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: x]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 1
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 0
    11: CheckTdz r1, c1
    14: Add r0, r0, r1, ic0
    19: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
}
