[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: LoadUndefined r0
    16: Ret r0
  Constant Table:
    0: [BytecodeFunction: breakToFinallyWithScopeRestore]
    1: [String: breakToFinallyWithScopeRestore]
    2: [BytecodeFunction: breakToFinallyNoScopeRestore]
    3: [String: breakToFinallyNoScopeRestore]
}

[BytecodeFunction: breakToFinallyWithScopeRestore] {
  Parameters: 0, Registers: 7
      0: PushLexicalScope c0
      2: LoadEmpty r1
      4: StoreToScope r1, 0, 0
      8: NewArray r3, 0
     11: GetIterator r1, r2, r3
     15: PopScope 
  .L0:
     16: PushLexicalScope c0
     18: LoadEmpty r3
     20: StoreToScope r3, 0, 0
     24: IteratorNext r3, r4, r1, r2
     29: JumpTrue r4, 112 (.L8)
     32: StoreToScope r3, 0, 0
     36: Mov r5, <scope>
     39: PushLexicalScope c1
     41: LoadEmpty r6
     43: StoreToScope r6, 0, 0
     47: LoadImmediate r6, 1
     50: StoreToScope r6, 0, 0
     54: LoadImmediate r6, 2
     57: JumpToBooleanFalse r6, 8 (.L1)
     60: LoadImmediate r3, 1
     63: Jump 38 (.L3)
  .L1:
     65: PushLexicalScope c2
     67: LoadEmpty r6
     69: StoreToScope r6, 0, 0
     73: NewClosure r0, c3
     76: LoadImmediate r6, 3
     79: StoreToScope r6, 0, 0
     83: LoadImmediate r6, 4
     86: JumpToBooleanFalse r6, 8 (.L2)
     89: LoadImmediate r3, 1
     92: Jump 9 (.L3)
  .L2:
     94: PopScope 
     95: PopScope 
     96: Jump 42 (.L7)
     98: LoadImmediate r3, 0
  .L3:
    101: Mov <scope>, r5
    104: IteratorClose r1
    106: Jump 17 (.L5)
    108: LoadImmediate r6, 0
    111: StrictEqual r6, r3, r6
    115: JumpFalse r6, 6 (.L4)
    118: Mov r5, r4
  .L4:
    121: Rethrow r5
  .L5:
    123: LoadImmediate r5, 0
    126: StrictEqual r5, r3, r5
    130: JumpFalse r5, 5 (.L6)
    133: Rethrow r4
  .L6:
    135: PopScope 
    136: Jump 6 (.L9)
  .L7:
    138: PopScope 
    139: Jump -123 (.L0)
  .L8:
    141: PopScope 
  .L9:
    142: LoadUndefined r1
    144: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
  Exception Handlers:
    32-96 -> 98 (r4)
    104-106 -> 108 (r5)
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 1
    11: CheckTdz r1, c1
    14: Add r0, r0, r1
    18: LoadFromScope r1, 0, 0
    22: CheckTdz r1, c2
    25: Add r0, r0, r1
    29: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
    2: [String: z]
}

[BytecodeFunction: breakToFinallyNoScopeRestore] {
  Parameters: 0, Registers: 7
      0: PushFunctionScope c0
      2: NewArray r3, 0
      5: GetIterator r1, r2, r3
  .L0:
      9: IteratorNext r3, r4, r1, r2
     14: JumpTrue r4, 110 (.L8)
     17: StoreToScope r3, 0, 0
     21: Mov r5, <scope>
     24: PushLexicalScope c1
     26: LoadEmpty r6
     28: StoreToScope r6, 0, 0
     32: LoadImmediate r6, 1
     35: StoreToScope r6, 0, 0
     39: LoadImmediate r6, 2
     42: JumpToBooleanFalse r6, 8 (.L1)
     45: LoadImmediate r3, 1
     48: Jump 38 (.L3)
  .L1:
     50: PushLexicalScope c2
     52: LoadEmpty r6
     54: StoreToScope r6, 0, 0
     58: NewClosure r0, c3
     61: LoadImmediate r6, 3
     64: StoreToScope r6, 0, 0
     68: LoadImmediate r6, 4
     71: JumpToBooleanFalse r6, 8 (.L2)
     74: LoadImmediate r3, 1
     77: Jump 9 (.L3)
  .L2:
     79: PopScope 
     80: PopScope 
     81: Jump 41 (.L7)
     83: LoadImmediate r3, 0
  .L3:
     86: Mov <scope>, r5
     89: IteratorClose r1
     91: Jump 17 (.L5)
     93: LoadImmediate r6, 0
     96: StrictEqual r6, r3, r6
    100: JumpFalse r6, 6 (.L4)
    103: Mov r5, r4
  .L4:
    106: Rethrow r5
  .L5:
    108: LoadImmediate r5, 0
    111: StrictEqual r5, r3, r5
    115: JumpFalse r5, 5 (.L6)
    118: Rethrow r4
  .L6:
    120: Jump 4 (.L8)
  .L7:
    122: Jump -113 (.L0)
  .L8:
    124: LoadUndefined r1
    126: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
  Exception Handlers:
    17-81 -> 83 (r4)
    89-91 -> 93 (r5)
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: LoadFromScope r1, 0, 1
     8: CheckTdz r1, c0
    11: Add r0, r0, r1
    15: LoadFromScope r1, 0, 0
    19: CheckTdz r1, c1
    22: Add r0, r0, r1
    26: Ret r0
  Constant Table:
    0: [String: y]
    1: [String: z]
}
