[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: LoadUndefined r0
    14: Ret r0
  Constant Table:
    0: [BytecodeFunction: cotinueToFinallyWithScopeRestore]
    1: [String: cotinueToFinallyWithScopeRestore]
    2: [BytecodeFunction: continueToFinallyNoScopeRestore]
    3: [String: continueToFinallyNoScopeRestore]
}

[BytecodeFunction: cotinueToFinallyWithScopeRestore] {
  Parameters: 0, Registers: 7
      0: PushLexicalScope c0
      2: LoadEmpty r1
      4: StoreToScope r1, 0, 0
      8: NewArray r3
     10: GetIterator r1, r2, r3
     14: PopScope 
  .L0:
     15: PushLexicalScope c0
     17: LoadEmpty r3
     19: StoreToScope r3, 0, 0
     23: IteratorNext r3, r4, r1, r2
     28: JumpTrue r4, 81 (.L4)
     31: StoreToScope r3, 0, 0
     35: Mov r5, <scope>
     38: PushLexicalScope c1
     40: LoadEmpty r6
     42: StoreToScope r6, 0, 0
     46: LoadImmediate r6, 1
     49: StoreToScope r6, 0, 0
     53: LoadImmediate r6, 2
     56: JumpToBooleanFalse r6, 7 (.L1)
     59: PopScope 
     60: PopScope 
     61: Jump -46 (.L0)
  .L1:
     63: PushLexicalScope c2
     65: LoadEmpty r6
     67: StoreToScope r6, 0, 0
     71: NewClosure r0, c3
     74: LoadImmediate r6, 3
     77: StoreToScope r6, 0, 0
     81: LoadImmediate r6, 4
     84: JumpToBooleanFalse r6, 8 (.L2)
     87: PopScope 
     88: PopScope 
     89: PopScope 
     90: Jump -75 (.L0)
  .L2:
     92: PopScope 
     93: PopScope 
     94: Jump 12 (.L3)
     96: LoadImmediate r3, 0
     99: Mov <scope>, r5
    102: IteratorClose r1
    104: Throw r4
  .L3:
    106: PopScope 
    107: Jump -92 (.L0)
  .L4:
    109: PopScope 
    110: LoadUndefined r1
    112: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
  Exception Handlers:
    31-94 -> 96 (r4)
    102-104 -> 104
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 1
    11: CheckTdz r1, c1
    14: Add r0, r0, r1
    18: LoadFromScope r1, 0, 0
    22: CheckTdz r1, c2
    25: Add r0, r0, r1
    29: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
    2: [String: z]
}

[BytecodeFunction: continueToFinallyNoScopeRestore] {
  Parameters: 0, Registers: 7
     0: PushFunctionScope c0
     2: NewArray r3
     4: GetIterator r1, r2, r3
  .L0:
     8: IteratorNext r3, r4, r1, r2
    13: JumpTrue r4, 78 (.L4)
    16: StoreToScope r3, 0, 0
    20: Mov r5, <scope>
    23: PushLexicalScope c1
    25: LoadEmpty r6
    27: StoreToScope r6, 0, 0
    31: LoadImmediate r6, 1
    34: StoreToScope r6, 0, 0
    38: LoadImmediate r6, 2
    41: JumpToBooleanFalse r6, 6 (.L1)
    44: PopScope 
    45: Jump -37 (.L0)
  .L1:
    47: PushLexicalScope c2
    49: LoadEmpty r6
    51: StoreToScope r6, 0, 0
    55: NewClosure r0, c3
    58: LoadImmediate r6, 3
    61: StoreToScope r6, 0, 0
    65: LoadImmediate r6, 4
    68: JumpToBooleanFalse r6, 7 (.L2)
    71: PopScope 
    72: PopScope 
    73: Jump -65 (.L0)
  .L2:
    75: PopScope 
    76: PopScope 
    77: Jump 12 (.L3)
    79: LoadImmediate r3, 0
    82: Mov <scope>, r5
    85: IteratorClose r1
    87: Throw r4
  .L3:
    89: Jump -81 (.L0)
  .L4:
    91: LoadUndefined r1
    93: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
  Exception Handlers:
    16-77 -> 79 (r4)
    85-87 -> 87
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: LoadFromScope r1, 0, 1
     8: CheckTdz r1, c0
    11: Add r0, r0, r1
    15: LoadFromScope r1, 0, 0
    19: CheckTdz r1, c1
    22: Add r0, r0, r1
    26: Ret r0
  Constant Table:
    0: [String: y]
    1: [String: z]
}
