[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: LoadUndefined r0
    30: Ret r0
  Constant Table:
    0: [BytecodeFunction: forCaptureAndInnerCaptureWithContinue]
    1: [String: forCaptureAndInnerCaptureWithContinue]
    2: [BytecodeFunction: forCaptureNoInnerCaptureWithContinue]
    3: [String: forCaptureNoInnerCaptureWithContinue]
    4: [BytecodeFunction: noForCaptureButInnerCaptureWithContinue]
    5: [String: noForCaptureButInnerCaptureWithContinue]
    6: [BytecodeFunction: noForCaptureOrInnerCaptureWithContinue]
    7: [String: noForCaptureOrInnerCaptureWithContinue]
}

[BytecodeFunction: forCaptureAndInnerCaptureWithContinue] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: NewObject r1, 4
    11: JumpNullish r1, 84 (.L3)
    14: NewForInIterator r1, r1
    17: PopScope 
  .L0:
    18: PushLexicalScope c0
    20: LoadEmpty r2
    22: StoreToScope r2, 0, 0
    26: ForInNext r2, r1
    29: JumpNullish r2, 66 (.L3)
    32: StoreToScope r2, 0, 0
    36: PushLexicalScope c1
    38: LoadEmpty r2
    40: StoreToScope r2, 0, 0
    44: LoadImmediate r2, 1
    47: StoreToScope r2, 0, 0
    51: LoadImmediate r2, 2
    54: JumpToBooleanFalse r2, 7 (.L1)
    57: PopScope 
    58: PopScope 
    59: Jump -41 (.L0)
  .L1:
    61: PushLexicalScope c2
    63: LoadEmpty r2
    65: StoreToScope r2, 0, 0
    69: NewClosure r0, c3
    72: LoadImmediate r2, 3
    75: StoreToScope r2, 0, 0
    79: LoadImmediate r2, 4
    82: JumpToBooleanFalse r2, 8 (.L2)
    85: PopScope 
    86: PopScope 
    87: PopScope 
    88: Jump -70 (.L0)
  .L2:
    90: PopScope 
    91: PopScope 
    92: PopScope 
    93: Jump -75 (.L0)
  .L3:
    95: PopScope 
    96: LoadUndefined r1
    98: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 1
    11: CheckTdz r1, c1
    14: Add r0, r0, r1
    18: LoadFromScope r1, 0, 0
    22: CheckTdz r1, c2
    25: Add r0, r0, r1
    29: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
    2: [String: z]
}

[BytecodeFunction: forCaptureNoInnerCaptureWithContinue] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: NewObject r1, 4
    11: JumpNullish r1, 66 (.L3)
    14: NewForInIterator r1, r1
    17: PopScope 
  .L0:
    18: PushLexicalScope c0
    20: LoadEmpty r2
    22: StoreToScope r2, 0, 0
    26: ForInNext r2, r1
    29: JumpNullish r2, 48 (.L3)
    32: StoreToScope r2, 0, 0
    36: LoadImmediate r2, 2
    39: JumpToBooleanFalse r2, 6 (.L1)
    42: PopScope 
    43: Jump -25 (.L0)
  .L1:
    45: PushLexicalScope c1
    47: LoadEmpty r2
    49: StoreToScope r2, 0, 0
    53: NewClosure r0, c2
    56: LoadImmediate r2, 3
    59: StoreToScope r2, 0, 0
    63: LoadImmediate r2, 4
    66: JumpToBooleanFalse r2, 7 (.L2)
    69: PopScope 
    70: PopScope 
    71: Jump -53 (.L0)
  .L2:
    73: PopScope 
    74: PopScope 
    75: Jump -57 (.L0)
  .L3:
    77: PopScope 
    78: LoadUndefined r1
    80: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 1
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 0
    11: CheckTdz r1, c1
    14: Add r0, r0, r1
    18: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: noForCaptureButInnerCaptureWithContinue] {
  Parameters: 0, Registers: 3
     0: PushFunctionScope c0
     2: NewObject r1, 4
     5: JumpNullish r1, 72 (.L3)
     8: NewForInIterator r1, r1
  .L0:
    11: ForInNext r2, r1
    14: JumpNullish r2, 63 (.L3)
    17: StoreToScope r2, 0, 0
    21: PushLexicalScope c1
    23: LoadEmpty r2
    25: StoreToScope r2, 0, 0
    29: LoadImmediate r2, 1
    32: StoreToScope r2, 0, 0
    36: LoadImmediate r2, 2
    39: JumpToBooleanFalse r2, 6 (.L1)
    42: PopScope 
    43: Jump -32 (.L0)
  .L1:
    45: PushLexicalScope c2
    47: LoadEmpty r2
    49: StoreToScope r2, 0, 0
    53: NewClosure r0, c3
    56: LoadImmediate r2, 3
    59: StoreToScope r2, 0, 0
    63: LoadImmediate r2, 4
    66: JumpToBooleanFalse r2, 7 (.L2)
    69: PopScope 
    70: PopScope 
    71: Jump -60 (.L0)
  .L2:
    73: PopScope 
    74: PopScope 
    75: Jump -64 (.L0)
  .L3:
    77: LoadUndefined r1
    79: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: LoadFromScope r1, 0, 1
     8: CheckTdz r1, c0
    11: Add r0, r0, r1
    15: LoadFromScope r1, 0, 0
    19: CheckTdz r1, c1
    22: Add r0, r0, r1
    26: Ret r0
  Constant Table:
    0: [String: y]
    1: [String: z]
}

[BytecodeFunction: noForCaptureOrInnerCaptureWithContinue] {
  Parameters: 0, Registers: 3
     0: PushFunctionScope c0
     2: NewObject r1, 4
     5: JumpNullish r1, 61 (.L3)
     8: NewForInIterator r1, r1
  .L0:
    11: ForInNext r2, r1
    14: JumpNullish r2, 52 (.L3)
    17: StoreToScope r2, 0, 0
    21: LoadImmediate r2, 1
    24: StoreToScope r2, 1, 0
    28: LoadImmediate r2, 2
    31: JumpToBooleanFalse r2, 5 (.L1)
    34: Jump -23 (.L0)
  .L1:
    36: PushLexicalScope c1
    38: LoadEmpty r2
    40: StoreToScope r2, 0, 0
    44: NewClosure r0, c2
    47: LoadImmediate r2, 3
    50: StoreToScope r2, 0, 0
    54: LoadImmediate r2, 4
    57: JumpToBooleanFalse r2, 6 (.L2)
    60: PopScope 
    61: Jump -50 (.L0)
  .L2:
    63: PopScope 
    64: Jump -53 (.L0)
  .L3:
    66: LoadUndefined r1
    68: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 1
     4: LoadFromScope r1, 1, 1
     8: Add r0, r0, r1
    12: LoadFromScope r1, 0, 0
    16: CheckTdz r1, c0
    19: Add r0, r0, r1
    23: Ret r0
  Constant Table:
    0: [String: z]
}
