[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: LoadUndefined r0
    16: Ret r0
  Constant Table:
    0: [BytecodeFunction: cotinueToFinallyWithScopeRestore]
    1: [String: cotinueToFinallyWithScopeRestore]
    2: [BytecodeFunction: continueToFinallyNoScopeRestore]
    3: [String: continueToFinallyNoScopeRestore]
}

[BytecodeFunction: cotinueToFinallyWithScopeRestore] {
  Parameters: 0, Registers: 7
      0: PushLexicalScope c0
      2: LoadEmpty r1
      4: StoreToScope r1, 0, 0
      8: NewArray r3, 0
     11: GetIterator r1, r2, r3
     15: PopScope 
  .L0:
     16: PushLexicalScope c0
     18: LoadEmpty r3
     20: StoreToScope r3, 0, 0
     24: IteratorNext r3, r4, r1, r2
     29: JumpTrue r4, 81 (.L4)
     32: StoreToScope r3, 0, 0
     36: Mov r5, <scope>
     39: PushLexicalScope c1
     41: LoadEmpty r6
     43: StoreToScope r6, 0, 0
     47: LoadImmediate r6, 1
     50: StoreToScope r6, 0, 0
     54: LoadImmediate r6, 2
     57: JumpToBooleanFalse r6, 7 (.L1)
     60: PopScope 
     61: PopScope 
     62: Jump -46 (.L0)
  .L1:
     64: PushLexicalScope c2
     66: LoadEmpty r6
     68: StoreToScope r6, 0, 0
     72: NewClosure r0, c3
     75: LoadImmediate r6, 3
     78: StoreToScope r6, 0, 0
     82: LoadImmediate r6, 4
     85: JumpToBooleanFalse r6, 8 (.L2)
     88: PopScope 
     89: PopScope 
     90: PopScope 
     91: Jump -75 (.L0)
  .L2:
     93: PopScope 
     94: PopScope 
     95: Jump 12 (.L3)
     97: LoadImmediate r3, 0
    100: Mov <scope>, r5
    103: IteratorClose r1
    105: Rethrow r4
  .L3:
    107: PopScope 
    108: Jump -92 (.L0)
  .L4:
    110: PopScope 
    111: LoadUndefined r1
    113: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
  Exception Handlers:
    32-95 -> 97 (r4)
    103-105 -> 105
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 1
    11: CheckTdz r1, c1
    14: Add r0, r0, r1
    18: LoadFromScope r1, 0, 0
    22: CheckTdz r1, c2
    25: Add r0, r0, r1
    29: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
    2: [String: z]
}

[BytecodeFunction: continueToFinallyNoScopeRestore] {
  Parameters: 0, Registers: 7
     0: PushFunctionScope c0
     2: NewArray r3, 0
     5: GetIterator r1, r2, r3
  .L0:
     9: IteratorNext r3, r4, r1, r2
    14: JumpTrue r4, 78 (.L4)
    17: StoreToScope r3, 0, 0
    21: Mov r5, <scope>
    24: PushLexicalScope c1
    26: LoadEmpty r6
    28: StoreToScope r6, 0, 0
    32: LoadImmediate r6, 1
    35: StoreToScope r6, 0, 0
    39: LoadImmediate r6, 2
    42: JumpToBooleanFalse r6, 6 (.L1)
    45: PopScope 
    46: Jump -37 (.L0)
  .L1:
    48: PushLexicalScope c2
    50: LoadEmpty r6
    52: StoreToScope r6, 0, 0
    56: NewClosure r0, c3
    59: LoadImmediate r6, 3
    62: StoreToScope r6, 0, 0
    66: LoadImmediate r6, 4
    69: JumpToBooleanFalse r6, 7 (.L2)
    72: PopScope 
    73: PopScope 
    74: Jump -65 (.L0)
  .L2:
    76: PopScope 
    77: PopScope 
    78: Jump 12 (.L3)
    80: LoadImmediate r3, 0
    83: Mov <scope>, r5
    86: IteratorClose r1
    88: Rethrow r4
  .L3:
    90: Jump -81 (.L0)
  .L4:
    92: LoadUndefined r1
    94: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
  Exception Handlers:
    17-78 -> 80 (r4)
    86-88 -> 88
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: LoadFromScope r1, 0, 1
     8: CheckTdz r1, c0
    11: Add r0, r0, r1
    15: LoadFromScope r1, 0, 0
    19: CheckTdz r1, c1
    22: Add r0, r0, r1
    26: Ret r0
  Constant Table:
    0: [String: y]
    1: [String: z]
}
