[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: LoadUndefined r0
    14: Ret r0
  Constant Table:
    0: [BytecodeFunction: breakToFinallyWithScopeRestore]
    1: [String: breakToFinallyWithScopeRestore]
    2: [BytecodeFunction: breakToFinallyNoScopeRestore]
    3: [String: breakToFinallyNoScopeRestore]
}

[BytecodeFunction: breakToFinallyWithScopeRestore] {
  Parameters: 0, Registers: 7
      0: PushLexicalScope c0
      2: LoadEmpty r1
      4: StoreToScope r1, 0, 0
      8: NewArray r3
     10: GetIterator r1, r2, r3
     14: PopScope 
  .L0:
     15: PushLexicalScope c0
     17: LoadEmpty r3
     19: StoreToScope r3, 0, 0
     23: IteratorNext r3, r4, r1, r2
     28: JumpTrue r4, 114 (.L8)
     31: StoreToScope r3, 0, 0
     35: Mov r5, <scope>
     38: PushLexicalScope c1
     40: LoadEmpty r6
     42: StoreToScope r6, 0, 0
     46: LoadImmediate r6, 1
     49: StoreToScope r6, 0, 0
     53: LoadImmediate r6, 2
     56: JumpToBooleanFalse r6, 8 (.L1)
     59: LoadImmediate r3, 1
     62: Jump 38 (.L3)
  .L1:
     64: PushLexicalScope c2
     66: LoadEmpty r6
     68: StoreToScope r6, 0, 0
     72: NewClosure r0, c3
     75: LoadImmediate r6, 3
     78: StoreToScope r6, 0, 0
     82: LoadImmediate r6, 4
     85: JumpToBooleanFalse r6, 8 (.L2)
     88: LoadImmediate r3, 1
     91: Jump 9 (.L3)
  .L2:
     93: PopScope 
     94: PopScope 
     95: Jump 44 (.L7)
     97: LoadImmediate r3, 0
  .L3:
    100: Mov <scope>, r5
    103: IteratorClose r1
    105: Jump 18 (.L5)
    107: LoadImmediate r6, 0
    110: StrictEqual r6, r3, r6, ic0
    115: JumpFalse r6, 6 (.L4)
    118: Mov r5, r4
  .L4:
    121: Throw r5
  .L5:
    123: LoadImmediate r5, 0
    126: StrictEqual r5, r3, r5, ic1
    131: JumpFalse r5, 5 (.L6)
    134: Throw r4
  .L6:
    136: PopScope 
    137: Jump 6 (.L9)
  .L7:
    139: PopScope 
    140: Jump -125 (.L0)
  .L8:
    142: PopScope 
  .L9:
    143: LoadUndefined r1
    145: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
  Exception Handlers:
    31-95 -> 97 (r4)
    103-105 -> 107 (r5)
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 1
    11: CheckTdz r1, c1
    14: Add r0, r0, r1, ic0
    19: LoadFromScope r1, 0, 0
    23: CheckTdz r1, c2
    26: Add r0, r0, r1, ic1
    31: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
    2: [String: z]
}

[BytecodeFunction: breakToFinallyNoScopeRestore] {
  Parameters: 0, Registers: 7
      0: PushFunctionScope c0
      2: NewArray r3
      4: GetIterator r1, r2, r3
  .L0:
      8: IteratorNext r3, r4, r1, r2
     13: JumpTrue r4, 112 (.L8)
     16: StoreToScope r3, 0, 0
     20: Mov r5, <scope>
     23: PushLexicalScope c1
     25: LoadEmpty r6
     27: StoreToScope r6, 0, 0
     31: LoadImmediate r6, 1
     34: StoreToScope r6, 0, 0
     38: LoadImmediate r6, 2
     41: JumpToBooleanFalse r6, 8 (.L1)
     44: LoadImmediate r3, 1
     47: Jump 38 (.L3)
  .L1:
     49: PushLexicalScope c2
     51: LoadEmpty r6
     53: StoreToScope r6, 0, 0
     57: NewClosure r0, c3
     60: LoadImmediate r6, 3
     63: StoreToScope r6, 0, 0
     67: LoadImmediate r6, 4
     70: JumpToBooleanFalse r6, 8 (.L2)
     73: LoadImmediate r3, 1
     76: Jump 9 (.L3)
  .L2:
     78: PopScope 
     79: PopScope 
     80: Jump 43 (.L7)
     82: LoadImmediate r3, 0
  .L3:
     85: Mov <scope>, r5
     88: IteratorClose r1
     90: Jump 18 (.L5)
     92: LoadImmediate r6, 0
     95: StrictEqual r6, r3, r6, ic0
    100: JumpFalse r6, 6 (.L4)
    103: Mov r5, r4
  .L4:
    106: Throw r5
  .L5:
    108: LoadImmediate r5, 0
    111: StrictEqual r5, r3, r5, ic1
    116: JumpFalse r5, 5 (.L6)
    119: Throw r4
  .L6:
    121: Jump 4 (.L8)
  .L7:
    123: Jump -115 (.L0)
  .L8:
    125: LoadUndefined r1
    127: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [ScopeNames]
    3: [BytecodeFunction: inner]
  Exception Handlers:
    16-80 -> 82 (r4)
    88-90 -> 92 (r5)
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 2
     4: LoadFromScope r1, 0, 1
     8: CheckTdz r1, c0
    11: Add r0, r0, r1, ic0
    16: LoadFromScope r1, 0, 0
    20: CheckTdz r1, c1
    23: Add r0, r0, r1, ic1
    28: Ret r0
  Constant Table:
    0: [String: y]
    1: [String: z]
}
