[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: LoadUndefined r0
    30: Ret r0
  Constant Table:
    0: [BytecodeFunction: startScope]
    1: [String: startScope]
    2: [BytecodeFunction: captures]
    3: [String: captures]
    4: [BytecodeFunction: captureRhsInTdz]
    5: [String: captureRhsInTdz]
    6: [BytecodeFunction: noCaptureRhsInTdz]
    7: [String: noCaptureRhsInTdz]
}

[BytecodeFunction: startScope] {
  Parameters: 0, Registers: 4
     0: NewObject r2, 0
     3: JumpNullish r2, 29 (.L1)
     6: NewForInIterator r2, r2
  .L0:
     9: ForInNext r3, r2
    12: JumpNullish r3, 20 (.L1)
    15: Mov r0, r3
    18: LoadEmpty r1
    20: CheckTdz r1, c0
    23: Add r3, r0, r1
    27: LoadImmediate r1, 0
    30: Jump -21 (.L0)
  .L1:
    32: LoadUndefined r2
    34: Ret r2
  Constant Table:
    0: [String: inner]
}

[BytecodeFunction: captures] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: NewObject r1, 0
    11: JumpNullish r1, 47 (.L1)
    14: NewForInIterator r1, r1
    17: PopScope 
  .L0:
    18: PushLexicalScope c0
    20: LoadEmpty r2
    22: StoreToScope r2, 0, 0
    26: ForInNext r2, r1
    29: JumpNullish r2, 29 (.L1)
    32: StoreToScope r2, 0, 0
    36: PushLexicalScope c1
    38: LoadEmpty r2
    40: StoreToScope r2, 0, 0
    44: NewClosure r0, c2
    47: LoadImmediate r2, 2
    50: StoreToScope r2, 0, 0
    54: PopScope 
    55: PopScope 
    56: Jump -38 (.L0)
  .L1:
    58: PopScope 
    59: LoadUndefined r1
    61: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 1
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 0
    11: CheckTdz r1, c1
    14: Add r0, r0, r1
    18: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: captureRhsInTdz] {
  Parameters: 0, Registers: 3
     0: PushLexicalScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: LoadFromScope r1, 0, 0
    12: CheckTdz r1, c1
    15: JumpNullish r1, 31 (.L1)
    18: NewForInIterator r1, r1
    21: PopScope 
  .L0:
    22: PushLexicalScope c0
    24: LoadEmpty r2
    26: StoreToScope r2, 0, 0
    30: ForInNext r2, r1
    33: JumpNullish r2, 13 (.L1)
    36: StoreToScope r2, 0, 0
    40: NewClosure r0, c2
    43: PopScope 
    44: Jump -22 (.L0)
  .L1:
    46: PopScope 
    47: LoadUndefined r1
    49: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: x]
    2: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: noCaptureRhsInTdz] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r0
     2: CheckTdz r0, c0
     5: JumpNullish r0, 22 (.L1)
     8: NewForInIterator r1, r0
  .L0:
    11: LoadEmpty r0
    13: ForInNext r2, r1
    16: JumpNullish r2, 11 (.L1)
    19: Mov r0, r2
    22: LoadImmediate r2, 1
    25: Jump -14 (.L0)
  .L1:
    27: LoadUndefined r1
    29: Ret r1
  Constant Table:
    0: [String: x]
}
