[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewClosure r0, c8
    31: StoreGlobal r0, c9, k4
    35: NewClosure r0, c10
    38: StoreGlobal r0, c11, k5
    42: LoadUndefined r0
    44: Ret r0
  Constant Table:
    0: [BytecodeFunction: startScope]
    1: [String: startScope]
    2: [BytecodeFunction: captures]
    3: [String: captures]
    4: [BytecodeFunction: capturedParameters]
    5: [String: capturedParameters]
    6: [BytecodeFunction: capturedParameterNeedsTdzCheck]
    7: [String: capturedParameterNeedsTdzCheck]
    8: [BytecodeFunction: capturedParameterBetweenInitializers]
    9: [String: capturedParameterBetweenInitializers]
    10: [BytecodeFunction: capturedParameterFromEvalInInitializers]
    11: [String: capturedParameterFromEvalInInitializers]
}

[BytecodeFunction: startScope] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r0
     2: LoadEmpty r1
     4: CheckTdz r0, c0
     7: CheckTdz r1, c1
    10: Add r2, r0, r1
    14: LoadImmediate r0, 1
    17: LoadImmediate r1, 2
    20: LoadUndefined r2
    22: Ret r2
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: captures] {
  Parameters: 0, Registers: 2
     0: PushFunctionScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 0, 0
     8: NewClosure r0, c1
    11: LoadImmediate r1, 1
    14: StoreToScope r1, 0, 0
    18: LoadUndefined r1
    20: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: capturedParameters] {
  Parameters: 3, Registers: 2
     0: PushFunctionScope c0
     2: StoreToScope a0, 0, 0
     6: GetNamedProperty r1, a1, c1, k0
    11: StoreToScope r1, 1, 0
    15: JumpNotUndefined a2, 6 (.L0)
    18: LoadImmediate a2, 2
  .L0:
    21: StoreToScope a2, 2, 0
    25: RestParameter r1
    27: StoreToScope r1, 3, 0
    31: NewClosure r0, c2
    34: LoadImmediate r1, 1
    37: StoreToScope r1, 0, 0
    41: LoadImmediate r1, 2
    44: StoreToScope r1, 1, 0
    48: LoadImmediate r1, 3
    51: StoreToScope r1, 2, 0
    55: LoadImmediate r1, 4
    58: StoreToScope r1, 3, 0
    62: LoadUndefined r1
    64: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [String: y]
    2: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 0
     4: LoadFromScope r1, 1, 0
     8: Add r0, r0, r1
    12: LoadFromScope r1, 2, 0
    16: Add r0, r0, r1
    20: LoadFromScope r1, 3, 0
    24: Add r0, r0, r1
    28: Ret r0
}

[BytecodeFunction: capturedParameterNeedsTdzCheck] {
  Parameters: 2, Registers: 1
     0: PushFunctionScope c0
     2: LoadEmpty r0
     4: StoreToScope r0, 0, 0
     8: LoadEmpty r0
    10: StoreToScope r0, 1, 0
    14: JumpNotUndefined a0, 11 (.L0)
    17: NewClosure r0, c1
    20: Call a0, r0, r0, 0
  .L0:
    25: StoreToScope a0, 0, 0
    29: JumpNotUndefined a1, 11 (.L1)
    32: NewClosure r0, c2
    35: Call a1, r0, r0, 0
  .L1:
    40: StoreToScope a1, 1, 0
    44: LoadUndefined r0
    46: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: <anonymous>]
    2: [BytecodeFunction: <anonymous>]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: a]
}

[BytecodeFunction: <anonymous>] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadFromScope r1, 1, 0
     7: CheckTdz r1, c0
    10: StoreToScope r0, 1, 0
    14: LoadUndefined r0
    16: Ret r0
  Constant Table:
    0: [String: b]
}

[BytecodeFunction: capturedParameterBetweenInitializers] {
  Parameters: 2, Registers: 1
     0: PushFunctionScope c0
     2: LoadEmpty r0
     4: StoreToScope r0, 1, 0
     8: JumpNotUndefined a0, 6 (.L0)
    11: NewClosure a0, c1
  .L0:
    14: StoreToScope a0, 0, 0
    18: JumpNotUndefined a1, 6 (.L1)
    21: NewClosure a1, c2
  .L1:
    24: StoreToScope a1, 1, 0
    28: LoadUndefined r0
    30: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: a]
    2: [BytecodeFunction: b]
}

[BytecodeFunction: a] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 1, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: b]
}

[BytecodeFunction: b] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: Ret r0
}

[BytecodeFunction: capturedParameterFromEvalInInitializers] {
  Parameters: 3, Registers: 2
     0: PushFunctionScope c0
     2: LoadEmpty r1
     4: StoreToScope r1, 1, 0
     8: LoadEmpty r1
    10: StoreToScope r1, 2, 0
    14: LoadEmpty r1
    16: StoreToScope r1, 3, 0
    20: StoreToScope <this>, 0, 0
    24: StoreToScope r0, 5, 0
    28: NewUnmappedArguments r0
    30: StoreToScope r0, 4, 0
    34: StoreToScope a0, 1, 0
    38: StoreToScope a1, 2, 0
    42: JumpNotUndefined a2, 15 (.L0)
    45: LoadDynamic r0, c1
    48: LoadConstant r1, c2
    51: CallMaybeEval a2, r0, r1, 1, 1
  .L0:
    57: StoreToScope a2, 3, 0
    61: PushFunctionScope c3
    63: LoadUndefined r0
    65: Ret r0
  Constant Table:
    0: [ScopeNames]
    1: [String: eval]
    2: [String: ]
    3: [ScopeNames]
}
