[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
     0: NewClosure r1, c0
     3: StoreGlobal r1, c1, k0
     7: LoadImmediate r1, 1
    10: StoreGlobal r1, c2, k1
    14: LoadImmediate r1, 2
    17: StoreToScope r1, 1, 0
    21: LoadImmediate r1, 3
    24: StoreToScope r1, 2, 0
    28: PushLexicalScope c3
    30: LoadEmpty r1
    32: StoreToScope r1, 0, 0
    36: NewClosure r0, c4
    39: LoadImmediate r1, 1
    42: StoreToScope r1, 0, 0
    46: PopScope 
    47: LoadUndefined r1
    49: Ret r1
  Constant Table:
    0: [BytecodeFunction: test1]
    1: [String: test1]
    2: [String: x]
    3: [ScopeNames]
    4: [BytecodeFunction: inner]
}

[BytecodeFunction: test1] {
  Parameters: 0, Registers: 1
     0: LoadGlobal r0, c0, k0
     4: LoadGlobal r0, c1, k1
     8: LoadGlobal r0, c2, k2
    12: LoadUndefined r0
    14: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: test1]
    2: [String: unresolved]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: c1]
}
