[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: LoadUndefined r0
    26: Ret r0
  Constant Table:
    0: [BytecodeFunction: startScope]
    1: [String: startScope]
    2: [BytecodeFunction: alwaysNeedTdzCheck]
    3: [String: alwaysNeedTdzCheck]
    4: [BytecodeFunction: captures]
    5: [String: captures]
    6: [BytecodeFunction: capturesWithBreak]
    7: [String: capturesWithBreak]
}

[BytecodeFunction: startScope] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 0
     3: LoadEmpty r0
     5: LoadEmpty r1
     7: LoadImmediate r3, 1
    10: StrictEqual r3, r2, r3, ic0
    15: JumpTrue r3, 27 (.L0)
    18: LoadImmediate r3, 2
    21: StrictEqual r3, r2, r3, ic1
    26: JumpTrue r3, 27 (.L1)
    29: LoadImmediate r3, 3
    32: StrictEqual r3, r2, r3, ic2
    37: JumpTrue r3, 18 (.L2)
    40: Jump 17 (.L3)
  .L0:
    42: CheckTdz r0, c0
    45: CheckTdz r1, c1
    48: Add r2, r0, r1, ic3
  .L1:
    53: LoadTrue r0
  .L2:
    55: LoadFalse r1
  .L3:
    57: LoadUndefined r2
    59: Ret r2
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: alwaysNeedTdzCheck] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 0
     3: LoadEmpty r1
     5: LoadImmediate r3, 1
     8: StrictEqual r3, r2, r3, ic0
    13: JumpTrue r3, 16 (.L0)
    16: LoadImmediate r3, 2
    19: StrictEqual r3, r2, r3, ic1
    24: JumpTrue r3, 10 (.L1)
    27: Jump 10 (.L2)
  .L0:
    29: LoadTrue r1
    31: CheckTdz r1, c0
  .L1:
    34: CheckTdz r1, c0
  .L2:
    37: LoadImmediate r2, 3
    40: LoadImmediate r3, 1
    43: StrictEqual r3, r2, r3, ic2
    48: JumpTrue r3, 5 (.L3)
    51: Jump 4 (.L4)
  .L3:
    53: LoadTrue r0
  .L4:
    55: LoadUndefined r2
    57: Ret r2
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: captures] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 0
     3: PushLexicalScope c0
     5: LoadEmpty r3
     7: StoreToScope r3, 0, 0
    11: NewClosure r0, c1
    14: LoadImmediate r3, 1
    17: StrictEqual r3, r2, r3, ic0
    22: JumpTrue r3, 27 (.L0)
    25: LoadImmediate r3, 2
    28: StrictEqual r3, r2, r3, ic1
    33: JumpTrue r3, 23 (.L1)
    36: LoadImmediate r3, 3
    39: StrictEqual r3, r2, r3, ic2
    44: JumpTrue r3, 12 (.L1)
    47: Jump 28 (.L2)
  .L0:
    49: LoadImmediate r2, 1
    52: StoreToScope r2, 0, 0
  .L1:
    56: PushLexicalScope c2
    58: LoadEmpty r2
    60: StoreToScope r2, 0, 0
    64: NewClosure r1, c3
    67: LoadImmediate r2, 1
    70: StoreToScope r2, 0, 0
    74: PopScope 
  .L2:
    75: PopScope 
    76: LoadUndefined r2
    78: Ret r2
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: inner1]
    2: [ScopeNames]
    3: [BytecodeFunction: inner2]
}

[BytecodeFunction: inner1] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: inner2] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r0, 0, 1
     4: CheckTdz r0, c0
     7: LoadFromScope r1, 0, 0
    11: CheckTdz r1, c1
    14: Add r0, r0, r1, ic0
    19: Ret r0
  Constant Table:
    0: [String: x]
    1: [String: y]
}

[BytecodeFunction: capturesWithBreak] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r1, 1
     3: PushLexicalScope c0
     5: LoadEmpty r2
     7: StoreToScope r2, 0, 0
    11: NewClosure r0, c1
    14: LoadImmediate r2, 1
    17: StrictEqual r2, r1, r2, ic0
    22: JumpTrue r2, 5 (.L0)
    25: Jump 12 (.L1)
  .L0:
    27: LoadImmediate r1, 1
    30: StoreToScope r1, 0, 0
    34: PopScope 
    35: Jump 3 (.L2)
  .L1:
    37: PopScope 
  .L2:
    38: LoadImmediate r1, 2
    41: LoadUndefined r1
    43: Ret r1
  Constant Table:
    0: [ScopeNames]
    1: [BytecodeFunction: captures]
}

[BytecodeFunction: captures] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: LoadUndefined r0
    9: Ret r0
  Constant Table:
    0: [String: x]
}
