{
  type: "Program",
  loc: "1:1-15:18",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:7",
      kind: {
        type: "AssignmentExpression",
        loc: "1:1-1:6",
        operator: "=",
        left: {
          type: "Identifier",
          loc: "1:1-1:2",
          name: "a",
        },
        right: {
          type: "Literal",
          loc: "1:5-1:6",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:9",
      kind: {
        type: "AssignmentExpression",
        loc: "3:1-3:8",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "3:1-3:4",
          elements: [
            {
              type: "Identifier",
              loc: "3:2-3:3",
              name: "a",
            },
          ],
        },
        right: {
          type: "Literal",
          loc: "3:7-3:8",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:15",
      kind: {
        type: "AssignmentExpression",
        loc: "5:1-5:14",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "5:1-5:10",
          elements: [
            {
              type: "Identifier",
              loc: "5:2-5:3",
              name: "a",
            },
            {
              type: "RestElement",
              loc: "5:5-5:9",
              argument: {
                type: "Identifier",
                loc: "5:8-5:9",
                name: "b",
              },
            },
          ],
        },
        right: {
          type: "Literal",
          loc: "5:13-5:14",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:17",
      kind: {
        type: "AssignmentExpression",
        loc: "7:1-7:16",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "7:1-7:12",
          elements: [
            {
              type: "Identifier",
              loc: "7:2-7:3",
              name: "a",
            },
            {
              type: "RestElement",
              loc: "7:5-7:11",
              argument: {
                type: "ArrayPattern",
                loc: "7:8-7:11",
                elements: [
                  {
                    type: "Identifier",
                    loc: "7:9-7:10",
                    name: "b",
                  },
                ],
              },
            },
          ],
        },
        right: {
          type: "Literal",
          loc: "7:15-7:16",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:16",
      kind: {
        type: "AssignmentExpression",
        loc: "9:1-9:15",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "9:1-9:11",
          elements: [
            {
              type: "Identifier",
              loc: "9:2-9:3",
              name: "a",
            },
            null,
            {
              type: "Identifier",
              loc: "9:5-9:6",
              name: "b",
            },
            null,
            {
              type: "Identifier",
              loc: "9:8-9:9",
              name: "c",
            },
          ],
        },
        right: {
          type: "Literal",
          loc: "9:14-9:15",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:1-11:11",
      kind: {
        type: "AssignmentExpression",
        loc: "11:1-11:10",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "11:1-11:6",
          elements: [
            {
              type: "Identifier",
              loc: "11:2-11:3",
              name: "a",
            },
            null,
          ],
        },
        right: {
          type: "Literal",
          loc: "11:9-11:10",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:1-13:23",
      kind: {
        type: "AssignmentExpression",
        loc: "13:1-13:22",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "13:1-13:18",
          elements: [
            {
              type: "AssignmentPattern",
              loc: "13:2-13:7",
              left: {
                type: "Identifier",
                loc: "13:2-13:3",
                name: "a",
              },
              right: {
                type: "Literal",
                loc: "13:6-13:7",
                value: 1,
              },
            },
            {
              type: "Identifier",
              loc: "13:9-13:10",
              name: "b",
            },
            {
              type: "AssignmentPattern",
              loc: "13:12-13:17",
              left: {
                type: "Identifier",
                loc: "13:12-13:13",
                name: "c",
              },
              right: {
                type: "Literal",
                loc: "13:16-13:17",
                value: 2,
              },
            },
          ],
        },
        right: {
          type: "Literal",
          loc: "13:21-13:22",
          value: 1,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "15:1-15:18",
      kind: {
        type: "AssignmentExpression",
        loc: "15:1-15:17",
        operator: "=",
        left: {
          type: "ArrayPattern",
          loc: "15:1-15:13",
          elements: [
            {
              type: "AssignmentPattern",
              loc: "15:2-15:12",
              left: {
                type: "ArrayPattern",
                loc: "15:2-15:8",
                elements: [
                  {
                    type: "Identifier",
                    loc: "15:3-15:4",
                    name: "a",
                  },
                  {
                    type: "Identifier",
                    loc: "15:6-15:7",
                    name: "b",
                  },
                ],
              },
              right: {
                type: "Literal",
                loc: "15:11-15:12",
                value: 1,
              },
            },
          ],
        },
        right: {
          type: "Literal",
          loc: "15:16-15:17",
          value: 2,
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}