{
  type: "Program",
  loc: "1:0-6:25",
  body: [
    {
      type: "FunctionDeclaration",
      loc: "1:0-4:1",
      id: {
        type: "Identifier",
        loc: "1:15-1:18",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "1:21-4:1",
        body: [
          {
            type: "ExpressionStatement",
            loc: "2:2-2:10",
            kind: {
              type: "AwaitExpression",
              loc: "2:2-2:9",
              argument: {
                type: "Literal",
                loc: "2:8-2:9",
                value: 1,
              },
            },
          },
          {
            type: "ExpressionStatement",
            loc: "3:2-3:16",
            kind: {
              type: "AwaitExpression",
              loc: "3:2-3:15",
              argument: {
                type: "AwaitExpression",
                loc: "3:8-3:15",
                argument: {
                  type: "Literal",
                  loc: "3:14-3:15",
                  value: 1,
                },
              },
            },
          },
        ],
      },
      async: true,
      generator: false,
      has_use_strict_directive: false,
    },
    {
      type: "FunctionDeclaration",
      loc: "6:0-6:25",
      id: {
        type: "Identifier",
        loc: "6:15-6:20",
        name: "await",
      },
      params: [],
      body: {
        type: "Block",
        loc: "6:23-6:25",
        body: [],
      },
      async: true,
      generator: false,
      has_use_strict_directive: false,
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}