{
  type: "Program",
  loc: "1:1-6:26",
  body: [
    {
      type: "FunctionDeclaration",
      loc: "1:1-4:2",
      id: {
        type: "Identifier",
        loc: "1:16-1:19",
        name: "foo",
      },
      params: [],
      body: {
        type: "Block",
        loc: "1:22-4:2",
        body: [
          {
            type: "ExpressionStatement",
            loc: "2:3-2:11",
            kind: {
              type: "AwaitExpression",
              loc: "2:3-2:10",
              argument: {
                type: "Literal",
                loc: "2:9-2:10",
                value: 1,
              },
            },
          },
          {
            type: "ExpressionStatement",
            loc: "3:3-3:17",
            kind: {
              type: "AwaitExpression",
              loc: "3:3-3:16",
              argument: {
                type: "AwaitExpression",
                loc: "3:9-3:16",
                argument: {
                  type: "Literal",
                  loc: "3:15-3:16",
                  value: 1,
                },
              },
            },
          },
        ],
      },
      async: true,
      generator: false,
      has_use_strict_directive: false,
    },
    {
      type: "FunctionDeclaration",
      loc: "6:1-6:26",
      id: {
        type: "Identifier",
        loc: "6:16-6:21",
        name: "await",
      },
      params: [],
      body: {
        type: "Block",
        loc: "6:24-6:26",
        body: [],
      },
      async: true,
      generator: false,
      has_use_strict_directive: false,
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}