{
  type: "Program",
  loc: "1:1-19:8",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:4",
      kind: {
        type: "Literal",
        loc: "1:1-1:3",
        value: null,
        bigint: "0",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:40",
      kind: {
        type: "Literal",
        loc: "3:1-3:39",
        value: null,
        bigint: "1002003004005006000700800900123456789",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:11",
      kind: {
        type: "Literal",
        loc: "5:1-5:10",
        value: null,
        bigint: "51",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:7",
      kind: {
        type: "Literal",
        loc: "7:1-7:6",
        value: null,
        bigint: "15",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:7",
      kind: {
        type: "Literal",
        loc: "9:1-9:6",
        value: null,
        bigint: "169",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:1-11:7",
      kind: {
        type: "Literal",
        loc: "11:1-11:6",
        value: null,
        bigint: "169",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:1-13:11",
      kind: {
        type: "Literal",
        loc: "13:1-13:10",
        value: null,
        bigint: "91234",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "15:1-15:14",
      kind: {
        type: "Literal",
        loc: "15:1-15:13",
        value: null,
        bigint: "51",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:1-17:8",
      kind: {
        type: "Literal",
        loc: "17:1-17:7",
        value: null,
        bigint: "15",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "19:1-19:8",
      kind: {
        type: "Literal",
        loc: "19:1-19:7",
        value: null,
        bigint: "169",
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}