{
  type: "Program",
  loc: "1:1-45:29",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:11",
      kind: {
        type: "BinaryExpression",
        loc: "1:1-1:10",
        operator: "+",
        left: {
          type: "BinaryExpression",
          loc: "1:1-1:6",
          operator: "+",
          left: {
            type: "Identifier",
            loc: "1:1-1:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "1:5-1:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "1:9-1:10",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:11",
      kind: {
        type: "BinaryExpression",
        loc: "3:1-3:10",
        operator: "-",
        left: {
          type: "BinaryExpression",
          loc: "3:1-3:6",
          operator: "-",
          left: {
            type: "Identifier",
            loc: "3:1-3:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "3:5-3:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "3:9-3:10",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:11",
      kind: {
        type: "BinaryExpression",
        loc: "5:1-5:10",
        operator: "*",
        left: {
          type: "BinaryExpression",
          loc: "5:1-5:6",
          operator: "*",
          left: {
            type: "Identifier",
            loc: "5:1-5:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "5:5-5:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "5:9-5:10",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:11",
      kind: {
        type: "BinaryExpression",
        loc: "7:1-7:10",
        operator: "/",
        left: {
          type: "BinaryExpression",
          loc: "7:1-7:6",
          operator: "/",
          left: {
            type: "Identifier",
            loc: "7:1-7:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "7:5-7:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "7:9-7:10",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:11",
      kind: {
        type: "BinaryExpression",
        loc: "9:1-9:10",
        operator: "%",
        left: {
          type: "BinaryExpression",
          loc: "9:1-9:6",
          operator: "%",
          left: {
            type: "Identifier",
            loc: "9:1-9:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "9:5-9:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "9:9-9:10",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:1-11:13",
      kind: {
        type: "BinaryExpression",
        loc: "11:1-11:12",
        operator: "**",
        left: {
          type: "Identifier",
          loc: "11:1-11:2",
          name: "a",
        },
        right: {
          type: "BinaryExpression",
          loc: "11:6-11:12",
          operator: "**",
          left: {
            type: "Identifier",
            loc: "11:6-11:7",
            name: "b",
          },
          right: {
            type: "Identifier",
            loc: "11:11-11:12",
            name: "c",
          },
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:1-13:11",
      kind: {
        type: "BinaryExpression",
        loc: "13:1-13:10",
        operator: "&",
        left: {
          type: "BinaryExpression",
          loc: "13:1-13:6",
          operator: "&",
          left: {
            type: "Identifier",
            loc: "13:1-13:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "13:5-13:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "13:9-13:10",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "15:1-15:11",
      kind: {
        type: "BinaryExpression",
        loc: "15:1-15:10",
        operator: "|",
        left: {
          type: "BinaryExpression",
          loc: "15:1-15:6",
          operator: "|",
          left: {
            type: "Identifier",
            loc: "15:1-15:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "15:5-15:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "15:9-15:10",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:1-17:11",
      kind: {
        type: "BinaryExpression",
        loc: "17:1-17:10",
        operator: "^",
        left: {
          type: "BinaryExpression",
          loc: "17:1-17:6",
          operator: "^",
          left: {
            type: "Identifier",
            loc: "17:1-17:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "17:5-17:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "17:9-17:10",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "19:1-19:13",
      kind: {
        type: "BinaryExpression",
        loc: "19:1-19:12",
        operator: "<<",
        left: {
          type: "BinaryExpression",
          loc: "19:1-19:7",
          operator: "<<",
          left: {
            type: "Identifier",
            loc: "19:1-19:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "19:6-19:7",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "19:11-19:12",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "21:1-21:13",
      kind: {
        type: "BinaryExpression",
        loc: "21:1-21:12",
        operator: ">>",
        left: {
          type: "BinaryExpression",
          loc: "21:1-21:7",
          operator: ">>",
          left: {
            type: "Identifier",
            loc: "21:1-21:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "21:6-21:7",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "21:11-21:12",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "23:1-23:15",
      kind: {
        type: "BinaryExpression",
        loc: "23:1-23:14",
        operator: ">>>",
        left: {
          type: "BinaryExpression",
          loc: "23:1-23:8",
          operator: ">>>",
          left: {
            type: "Identifier",
            loc: "23:1-23:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "23:7-23:8",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "23:13-23:14",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "25:1-25:13",
      kind: {
        type: "BinaryExpression",
        loc: "25:1-25:12",
        operator: "==",
        left: {
          type: "BinaryExpression",
          loc: "25:1-25:7",
          operator: "==",
          left: {
            type: "Identifier",
            loc: "25:1-25:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "25:6-25:7",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "25:11-25:12",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "27:1-27:13",
      kind: {
        type: "BinaryExpression",
        loc: "27:1-27:12",
        operator: "!=",
        left: {
          type: "BinaryExpression",
          loc: "27:1-27:7",
          operator: "!=",
          left: {
            type: "Identifier",
            loc: "27:1-27:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "27:6-27:7",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "27:11-27:12",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "29:1-29:15",
      kind: {
        type: "BinaryExpression",
        loc: "29:1-29:14",
        operator: "===",
        left: {
          type: "BinaryExpression",
          loc: "29:1-29:8",
          operator: "===",
          left: {
            type: "Identifier",
            loc: "29:1-29:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "29:7-29:8",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "29:13-29:14",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "31:1-31:15",
      kind: {
        type: "BinaryExpression",
        loc: "31:1-31:14",
        operator: "!==",
        left: {
          type: "BinaryExpression",
          loc: "31:1-31:8",
          operator: "!==",
          left: {
            type: "Identifier",
            loc: "31:1-31:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "31:7-31:8",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "31:13-31:14",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "33:1-33:11",
      kind: {
        type: "BinaryExpression",
        loc: "33:1-33:10",
        operator: "<",
        left: {
          type: "BinaryExpression",
          loc: "33:1-33:6",
          operator: "<",
          left: {
            type: "Identifier",
            loc: "33:1-33:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "33:5-33:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "33:9-33:10",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "35:1-35:13",
      kind: {
        type: "BinaryExpression",
        loc: "35:1-35:12",
        operator: "<=",
        left: {
          type: "BinaryExpression",
          loc: "35:1-35:7",
          operator: "<=",
          left: {
            type: "Identifier",
            loc: "35:1-35:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "35:6-35:7",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "35:11-35:12",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "37:1-37:11",
      kind: {
        type: "BinaryExpression",
        loc: "37:1-37:10",
        operator: ">",
        left: {
          type: "BinaryExpression",
          loc: "37:1-37:6",
          operator: ">",
          left: {
            type: "Identifier",
            loc: "37:1-37:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "37:5-37:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "37:9-37:10",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "39:1-39:13",
      kind: {
        type: "BinaryExpression",
        loc: "39:1-39:12",
        operator: ">=",
        left: {
          type: "BinaryExpression",
          loc: "39:1-39:7",
          operator: ">=",
          left: {
            type: "Identifier",
            loc: "39:1-39:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "39:6-39:7",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "39:11-39:12",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "41:1-41:13",
      kind: {
        type: "BinaryExpression",
        loc: "41:1-41:12",
        operator: "in",
        left: {
          type: "BinaryExpression",
          loc: "41:1-41:7",
          operator: "in",
          left: {
            type: "Identifier",
            loc: "41:1-41:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "41:6-41:7",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "41:11-41:12",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "43:1-43:9",
      kind: {
        type: "BinaryExpression",
        loc: "43:1-43:8",
        operator: "in",
        left: {
          type: "PrivateIdentifier",
          loc: "43:1-43:3",
          name: "#a",
        },
        right: {
          type: "Identifier",
          loc: "43:7-43:8",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "45:1-45:29",
      kind: {
        type: "BinaryExpression",
        loc: "45:1-45:28",
        operator: "instanceof",
        left: {
          type: "BinaryExpression",
          loc: "45:1-45:15",
          operator: "instanceof",
          left: {
            type: "Identifier",
            loc: "45:1-45:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "45:14-45:15",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "45:27-45:28",
          name: "c",
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}