{
  type: "Program",
  loc: "1:0-11:12",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:10",
      kind: {
        type: "BinaryExpression",
        loc: "1:0-1:9",
        operator: "+",
        left: {
          type: "BinaryExpression",
          loc: "1:0-1:5",
          operator: "+",
          left: {
            type: "Identifier",
            loc: "1:0-1:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "1:4-1:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "1:8-1:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:10",
      kind: {
        type: "BinaryExpression",
        loc: "3:0-3:9",
        operator: "-",
        left: {
          type: "BinaryExpression",
          loc: "3:0-3:5",
          operator: "-",
          left: {
            type: "Identifier",
            loc: "3:0-3:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "3:4-3:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "3:8-3:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:10",
      kind: {
        type: "BinaryExpression",
        loc: "5:0-5:9",
        operator: "*",
        left: {
          type: "BinaryExpression",
          loc: "5:0-5:5",
          operator: "*",
          left: {
            type: "Identifier",
            loc: "5:0-5:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "5:4-5:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "5:8-5:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:0-7:10",
      kind: {
        type: "BinaryExpression",
        loc: "7:0-7:9",
        operator: "/",
        left: {
          type: "BinaryExpression",
          loc: "7:0-7:5",
          operator: "/",
          left: {
            type: "Identifier",
            loc: "7:0-7:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "7:4-7:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "7:8-7:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:0-9:10",
      kind: {
        type: "BinaryExpression",
        loc: "9:0-9:9",
        operator: "%",
        left: {
          type: "BinaryExpression",
          loc: "9:0-9:5",
          operator: "%",
          left: {
            type: "Identifier",
            loc: "9:0-9:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "9:4-9:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "9:8-9:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:0-11:12",
      kind: {
        type: "BinaryExpression",
        loc: "11:0-11:11",
        operator: "**",
        left: {
          type: "Identifier",
          loc: "11:0-11:1",
          name: "a",
        },
        right: {
          type: "BinaryExpression",
          loc: "11:5-11:11",
          operator: "**",
          left: {
            type: "Identifier",
            loc: "11:5-11:6",
            name: "b",
          },
          right: {
            type: "Identifier",
            loc: "11:10-11:11",
            name: "c",
          },
        },
      },
    },
  ],
}