{
  type: "Program",
  loc: "1:0-45:28",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:10",
      kind: {
        type: "BinaryExpression",
        loc: "1:0-1:9",
        operator: "+",
        left: {
          type: "BinaryExpression",
          loc: "1:0-1:5",
          operator: "+",
          left: {
            type: "Identifier",
            loc: "1:0-1:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "1:4-1:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "1:8-1:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:10",
      kind: {
        type: "BinaryExpression",
        loc: "3:0-3:9",
        operator: "-",
        left: {
          type: "BinaryExpression",
          loc: "3:0-3:5",
          operator: "-",
          left: {
            type: "Identifier",
            loc: "3:0-3:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "3:4-3:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "3:8-3:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:10",
      kind: {
        type: "BinaryExpression",
        loc: "5:0-5:9",
        operator: "*",
        left: {
          type: "BinaryExpression",
          loc: "5:0-5:5",
          operator: "*",
          left: {
            type: "Identifier",
            loc: "5:0-5:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "5:4-5:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "5:8-5:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:0-7:10",
      kind: {
        type: "BinaryExpression",
        loc: "7:0-7:9",
        operator: "/",
        left: {
          type: "BinaryExpression",
          loc: "7:0-7:5",
          operator: "/",
          left: {
            type: "Identifier",
            loc: "7:0-7:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "7:4-7:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "7:8-7:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:0-9:10",
      kind: {
        type: "BinaryExpression",
        loc: "9:0-9:9",
        operator: "%",
        left: {
          type: "BinaryExpression",
          loc: "9:0-9:5",
          operator: "%",
          left: {
            type: "Identifier",
            loc: "9:0-9:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "9:4-9:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "9:8-9:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:0-11:12",
      kind: {
        type: "BinaryExpression",
        loc: "11:0-11:11",
        operator: "**",
        left: {
          type: "Identifier",
          loc: "11:0-11:1",
          name: "a",
        },
        right: {
          type: "BinaryExpression",
          loc: "11:5-11:11",
          operator: "**",
          left: {
            type: "Identifier",
            loc: "11:5-11:6",
            name: "b",
          },
          right: {
            type: "Identifier",
            loc: "11:10-11:11",
            name: "c",
          },
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:0-13:10",
      kind: {
        type: "BinaryExpression",
        loc: "13:0-13:9",
        operator: "&",
        left: {
          type: "BinaryExpression",
          loc: "13:0-13:5",
          operator: "&",
          left: {
            type: "Identifier",
            loc: "13:0-13:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "13:4-13:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "13:8-13:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "15:0-15:10",
      kind: {
        type: "BinaryExpression",
        loc: "15:0-15:9",
        operator: "|",
        left: {
          type: "BinaryExpression",
          loc: "15:0-15:5",
          operator: "|",
          left: {
            type: "Identifier",
            loc: "15:0-15:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "15:4-15:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "15:8-15:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:0-17:10",
      kind: {
        type: "BinaryExpression",
        loc: "17:0-17:9",
        operator: "^",
        left: {
          type: "BinaryExpression",
          loc: "17:0-17:5",
          operator: "^",
          left: {
            type: "Identifier",
            loc: "17:0-17:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "17:4-17:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "17:8-17:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "19:0-19:12",
      kind: {
        type: "BinaryExpression",
        loc: "19:0-19:11",
        operator: "<<",
        left: {
          type: "BinaryExpression",
          loc: "19:0-19:6",
          operator: "<<",
          left: {
            type: "Identifier",
            loc: "19:0-19:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "19:5-19:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "19:10-19:11",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "21:0-21:12",
      kind: {
        type: "BinaryExpression",
        loc: "21:0-21:11",
        operator: ">>",
        left: {
          type: "BinaryExpression",
          loc: "21:0-21:6",
          operator: ">>",
          left: {
            type: "Identifier",
            loc: "21:0-21:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "21:5-21:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "21:10-21:11",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "23:0-23:14",
      kind: {
        type: "BinaryExpression",
        loc: "23:0-23:13",
        operator: ">>>",
        left: {
          type: "BinaryExpression",
          loc: "23:0-23:7",
          operator: ">>>",
          left: {
            type: "Identifier",
            loc: "23:0-23:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "23:6-23:7",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "23:12-23:13",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "25:0-25:12",
      kind: {
        type: "BinaryExpression",
        loc: "25:0-25:11",
        operator: "==",
        left: {
          type: "BinaryExpression",
          loc: "25:0-25:6",
          operator: "==",
          left: {
            type: "Identifier",
            loc: "25:0-25:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "25:5-25:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "25:10-25:11",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "27:0-27:12",
      kind: {
        type: "BinaryExpression",
        loc: "27:0-27:11",
        operator: "!=",
        left: {
          type: "BinaryExpression",
          loc: "27:0-27:6",
          operator: "!=",
          left: {
            type: "Identifier",
            loc: "27:0-27:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "27:5-27:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "27:10-27:11",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "29:0-29:14",
      kind: {
        type: "BinaryExpression",
        loc: "29:0-29:13",
        operator: "===",
        left: {
          type: "BinaryExpression",
          loc: "29:0-29:7",
          operator: "===",
          left: {
            type: "Identifier",
            loc: "29:0-29:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "29:6-29:7",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "29:12-29:13",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "31:0-31:14",
      kind: {
        type: "BinaryExpression",
        loc: "31:0-31:13",
        operator: "!==",
        left: {
          type: "BinaryExpression",
          loc: "31:0-31:7",
          operator: "!==",
          left: {
            type: "Identifier",
            loc: "31:0-31:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "31:6-31:7",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "31:12-31:13",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "33:0-33:10",
      kind: {
        type: "BinaryExpression",
        loc: "33:0-33:9",
        operator: "<",
        left: {
          type: "BinaryExpression",
          loc: "33:0-33:5",
          operator: "<",
          left: {
            type: "Identifier",
            loc: "33:0-33:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "33:4-33:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "33:8-33:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "35:0-35:12",
      kind: {
        type: "BinaryExpression",
        loc: "35:0-35:11",
        operator: "<=",
        left: {
          type: "BinaryExpression",
          loc: "35:0-35:6",
          operator: "<=",
          left: {
            type: "Identifier",
            loc: "35:0-35:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "35:5-35:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "35:10-35:11",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "37:0-37:10",
      kind: {
        type: "BinaryExpression",
        loc: "37:0-37:9",
        operator: ">",
        left: {
          type: "BinaryExpression",
          loc: "37:0-37:5",
          operator: ">",
          left: {
            type: "Identifier",
            loc: "37:0-37:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "37:4-37:5",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "37:8-37:9",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "39:0-39:12",
      kind: {
        type: "BinaryExpression",
        loc: "39:0-39:11",
        operator: ">=",
        left: {
          type: "BinaryExpression",
          loc: "39:0-39:6",
          operator: ">=",
          left: {
            type: "Identifier",
            loc: "39:0-39:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "39:5-39:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "39:10-39:11",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "41:0-41:12",
      kind: {
        type: "BinaryExpression",
        loc: "41:0-41:11",
        operator: "in",
        left: {
          type: "BinaryExpression",
          loc: "41:0-41:6",
          operator: "in",
          left: {
            type: "Identifier",
            loc: "41:0-41:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "41:5-41:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "41:10-41:11",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "43:0-43:8",
      kind: {
        type: "BinaryExpression",
        loc: "43:0-43:7",
        operator: "in",
        left: {
          type: "PrivateIdentifier",
          loc: "43:1-43:2",
          name: "a",
        },
        right: {
          type: "Identifier",
          loc: "43:6-43:7",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "45:0-45:28",
      kind: {
        type: "BinaryExpression",
        loc: "45:0-45:27",
        operator: "instanceof",
        left: {
          type: "BinaryExpression",
          loc: "45:0-45:14",
          operator: "instanceof",
          left: {
            type: "Identifier",
            loc: "45:0-45:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "45:13-45:14",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "45:26-45:27",
          name: "c",
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}