{
  type: "Program",
  loc: "1:1-17:11",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:7",
      kind: {
        type: "CallExpression",
        loc: "1:1-1:6",
        callee: {
          type: "Identifier",
          loc: "1:1-1:4",
          name: "foo",
        },
        arguments: [],
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:9",
      kind: {
        type: "CallExpression",
        loc: "3:1-3:8",
        callee: {
          type: "CallExpression",
          loc: "3:1-3:6",
          callee: {
            type: "Identifier",
            loc: "3:1-3:4",
            name: "foo",
          },
          arguments: [],
          optional: false,
        },
        arguments: [],
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:8",
      kind: {
        type: "CallExpression",
        loc: "5:1-5:7",
        callee: {
          type: "Identifier",
          loc: "5:1-5:4",
          name: "foo",
        },
        arguments: [
          {
            type: "Identifier",
            loc: "5:5-5:6",
            name: "a",
          },
        ],
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:9",
      kind: {
        type: "CallExpression",
        loc: "7:1-7:8",
        callee: {
          type: "Identifier",
          loc: "7:1-7:4",
          name: "foo",
        },
        arguments: [
          {
            type: "Identifier",
            loc: "7:5-7:6",
            name: "a",
          },
        ],
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:14",
      kind: {
        type: "CallExpression",
        loc: "9:1-9:13",
        callee: {
          type: "Identifier",
          loc: "9:1-9:4",
          name: "foo",
        },
        arguments: [
          {
            type: "Identifier",
            loc: "9:5-9:6",
            name: "a",
          },
          {
            type: "Identifier",
            loc: "9:8-9:9",
            name: "b",
          },
          {
            type: "Identifier",
            loc: "9:11-9:12",
            name: "c",
          },
        ],
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:1-11:15",
      kind: {
        type: "CallExpression",
        loc: "11:1-11:14",
        callee: {
          type: "Identifier",
          loc: "11:1-11:4",
          name: "foo",
        },
        arguments: [
          {
            type: "Identifier",
            loc: "11:5-11:6",
            name: "a",
          },
          {
            type: "Identifier",
            loc: "11:8-11:9",
            name: "b",
          },
          {
            type: "Identifier",
            loc: "11:11-11:12",
            name: "c",
          },
        ],
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:1-13:20",
      kind: {
        type: "CallExpression",
        loc: "13:1-13:19",
        callee: {
          type: "Identifier",
          loc: "13:1-13:4",
          name: "foo",
        },
        arguments: [
          {
            type: "Identifier",
            loc: "13:5-13:6",
            name: "a",
          },
          {
            type: "SpreadElement",
            loc: "13:8-13:12",
            argument: {
              type: "Identifier",
              loc: "13:11-13:12",
              name: "b",
            },
          },
          {
            type: "SpreadElement",
            loc: "13:14-13:18",
            argument: {
              type: "Identifier",
              loc: "13:17-13:18",
              name: "c",
            },
          },
        ],
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "15:1-15:18",
      kind: {
        type: "CallExpression",
        loc: "15:1-15:17",
        callee: {
          type: "Identifier",
          loc: "15:1-15:4",
          name: "foo",
        },
        arguments: [
          {
            type: "SpreadElement",
            loc: "15:5-15:9",
            argument: {
              type: "Identifier",
              loc: "15:8-15:9",
              name: "a",
            },
          },
          {
            type: "SpreadElement",
            loc: "15:11-15:15",
            argument: {
              type: "Identifier",
              loc: "15:14-15:15",
              name: "b",
            },
          },
        ],
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:1-17:11",
      kind: {
        type: "CallExpression",
        loc: "17:1-17:10",
        callee: {
          type: "MemberExpression",
          loc: "17:1-17:8",
          object: {
            type: "CallExpression",
            loc: "17:1-17:6",
            callee: {
              type: "MemberExpression",
              loc: "17:1-17:4",
              object: {
                type: "Identifier",
                loc: "17:1-17:2",
                name: "a",
              },
              property: {
                type: "Identifier",
                loc: "17:3-17:4",
                name: "b",
              },
              computed: false,
              optional: false,
            },
            arguments: [],
            optional: false,
          },
          property: {
            type: "Identifier",
            loc: "17:7-17:8",
            name: "c",
          },
          computed: false,
          optional: false,
        },
        arguments: [],
        optional: false,
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}