{
  type: "Program",
  loc: "1:0-19:11",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:5",
      kind: {
        type: "ChainExpression",
        loc: "1:0-1:4",
        expression: {
          type: "MemberExpression",
          loc: "1:0-1:4",
          object: {
            type: "Identifier",
            loc: "1:0-1:1",
            name: "a",
          },
          property: {
            type: "Identifier",
            loc: "1:3-1:4",
            name: "b",
          },
          computed: false,
          optional: true,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:6",
      kind: {
        type: "ChainExpression",
        loc: "3:0-3:5",
        expression: {
          type: "CallExpression",
          loc: "3:0-3:5",
          callee: {
            type: "Identifier",
            loc: "3:0-3:1",
            name: "a",
          },
          arguments: [],
          optional: true,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "4:0-4:7",
      kind: {
        type: "ChainExpression",
        loc: "4:0-4:6",
        expression: {
          type: "CallExpression",
          loc: "4:0-4:6",
          callee: {
            type: "Identifier",
            loc: "4:0-4:1",
            name: "a",
          },
          arguments: [
            {
              type: "Identifier",
              loc: "4:4-4:5",
              name: "c",
            },
          ],
          optional: true,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:14",
      kind: {
        type: "ChainExpression",
        loc: "5:0-5:13",
        expression: {
          type: "CallExpression",
          loc: "5:0-5:13",
          callee: {
            type: "Identifier",
            loc: "5:0-5:1",
            name: "a",
          },
          arguments: [
            {
              type: "Identifier",
              loc: "5:4-5:5",
              name: "c",
            },
            {
              type: "Identifier",
              loc: "5:7-5:8",
              name: "d",
            },
            {
              type: "Identifier",
              loc: "5:10-5:11",
              name: "e",
            },
          ],
          optional: true,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:0-7:7",
      kind: {
        type: "ChainExpression",
        loc: "7:0-7:6",
        expression: {
          type: "MemberExpression",
          loc: "7:0-7:6",
          object: {
            type: "Identifier",
            loc: "7:0-7:1",
            name: "a",
          },
          property: {
            type: "Identifier",
            loc: "7:4-7:5",
            name: "b",
          },
          computed: true,
          optional: true,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:0-9:6",
      kind: {
        type: "ChainExpression",
        loc: "9:0-9:5",
        expression: {
          type: "MemberExpression",
          loc: "9:0-9:5",
          object: {
            type: "Identifier",
            loc: "9:0-9:1",
            name: "a",
          },
          property: {
            type: "PrivateIdentifier",
            loc: "9:4-9:5",
            name: "b",
          },
          computed: false,
          optional: true,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:0-11:11",
      kind: {
        type: "ChainExpression",
        loc: "11:0-11:10",
        expression: {
          type: "MemberExpression",
          loc: "11:0-11:10",
          object: {
            type: "CallExpression",
            loc: "11:0-11:8",
            callee: {
              type: "MemberExpression",
              loc: "11:0-11:6",
              object: {
                type: "MemberExpression",
                loc: "11:0-11:4",
                object: {
                  type: "Identifier",
                  loc: "11:0-11:1",
                  name: "a",
                },
                property: {
                  type: "Identifier",
                  loc: "11:3-11:4",
                  name: "b",
                },
                computed: false,
                optional: true,
              },
              property: {
                type: "Identifier",
                loc: "11:5-11:6",
                name: "c",
              },
              computed: false,
              optional: false,
            },
            arguments: [],
            optional: false,
          },
          property: {
            type: "Identifier",
            loc: "11:9-11:10",
            name: "d",
          },
          computed: false,
          optional: false,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:0-13:12",
      kind: {
        type: "ChainExpression",
        loc: "13:0-13:11",
        expression: {
          type: "MemberExpression",
          loc: "13:0-13:11",
          object: {
            type: "CallExpression",
            loc: "13:0-13:8",
            callee: {
              type: "MemberExpression",
              loc: "13:0-13:4",
              object: {
                type: "Identifier",
                loc: "13:0-13:1",
                name: "a",
              },
              property: {
                type: "Identifier",
                loc: "13:3-13:4",
                name: "b",
              },
              computed: false,
              optional: true,
            },
            arguments: [],
            optional: true,
          },
          property: {
            type: "Identifier",
            loc: "13:10-13:11",
            name: "c",
          },
          computed: false,
          optional: true,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "15:0-15:18",
      kind: {
        type: "ChainExpression",
        loc: "15:0-15:17",
        expression: {
          type: "CallExpression",
          loc: "15:0-15:17",
          callee: {
            type: "MemberExpression",
            loc: "15:0-15:15",
            object: {
              type: "CallExpression",
              loc: "15:0-15:13",
              callee: {
                type: "MemberExpression",
                loc: "15:0-15:9",
                object: {
                  type: "CallExpression",
                  loc: "15:0-15:6",
                  callee: {
                    type: "MemberExpression",
                    loc: "15:0-15:4",
                    object: {
                      type: "Identifier",
                      loc: "15:0-15:1",
                      name: "a",
                    },
                    property: {
                      type: "Identifier",
                      loc: "15:3-15:4",
                      name: "b",
                    },
                    computed: false,
                    optional: true,
                  },
                  arguments: [],
                  optional: false,
                },
                property: {
                  type: "Identifier",
                  loc: "15:8-15:9",
                  name: "c",
                },
                computed: false,
                optional: true,
              },
              arguments: [],
              optional: true,
            },
            property: {
              type: "Identifier",
              loc: "15:14-15:15",
              name: "d",
            },
            computed: false,
            optional: false,
          },
          arguments: [],
          optional: false,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:0-17:18",
      kind: {
        type: "BinaryExpression",
        loc: "17:0-17:17",
        operator: "+",
        left: {
          type: "ChainExpression",
          loc: "17:0-17:8",
          expression: {
            type: "MemberExpression",
            loc: "17:0-17:8",
            object: {
              type: "MemberExpression",
              loc: "17:0-17:6",
              object: {
                type: "MemberExpression",
                loc: "17:0-17:3",
                object: {
                  type: "Identifier",
                  loc: "17:0-17:1",
                  name: "a",
                },
                property: {
                  type: "Identifier",
                  loc: "17:2-17:3",
                  name: "b",
                },
                computed: false,
                optional: false,
              },
              property: {
                type: "Identifier",
                loc: "17:5-17:6",
                name: "c",
              },
              computed: false,
              optional: true,
            },
            property: {
              type: "Identifier",
              loc: "17:7-17:8",
              name: "d",
            },
            computed: false,
            optional: false,
          },
        },
        right: {
          type: "ChainExpression",
          loc: "17:11-17:17",
          expression: {
            type: "MemberExpression",
            loc: "17:11-17:17",
            object: {
              type: "MemberExpression",
              loc: "17:11-17:14",
              object: {
                type: "Identifier",
                loc: "17:11-17:12",
                name: "e",
              },
              property: {
                type: "Identifier",
                loc: "17:13-17:14",
                name: "f",
              },
              computed: false,
              optional: false,
            },
            property: {
              type: "Identifier",
              loc: "17:16-17:17",
              name: "f",
            },
            computed: false,
            optional: true,
          },
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "19:0-19:11",
      kind: {
        type: "MemberExpression",
        loc: "19:0-19:10",
        object: {
          type: "ChainExpression",
          loc: "19:1-19:7",
          expression: {
            type: "MemberExpression",
            loc: "19:1-19:7",
            object: {
              type: "MemberExpression",
              loc: "19:1-19:5",
              object: {
                type: "Identifier",
                loc: "19:1-19:2",
                name: "a",
              },
              property: {
                type: "Identifier",
                loc: "19:4-19:5",
                name: "b",
              },
              computed: false,
              optional: true,
            },
            property: {
              type: "Identifier",
              loc: "19:6-19:7",
              name: "c",
            },
            computed: false,
            optional: false,
          },
        },
        property: {
          type: "Identifier",
          loc: "19:9-19:10",
          name: "d",
        },
        computed: false,
        optional: false,
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}