{
  type: "Program",
  loc: "1:1-9:19",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:11",
      kind: {
        type: "ConditionalExpression",
        loc: "1:1-1:10",
        test: {
          type: "Identifier",
          loc: "1:1-1:2",
          name: "a",
        },
        consequent: {
          type: "Identifier",
          loc: "1:5-1:6",
          name: "b",
        },
        alternate: {
          type: "Identifier",
          loc: "1:9-1:10",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:19",
      kind: {
        type: "ConditionalExpression",
        loc: "3:1-3:18",
        test: {
          type: "Identifier",
          loc: "3:1-3:2",
          name: "a",
        },
        consequent: {
          type: "Identifier",
          loc: "3:5-3:6",
          name: "b",
        },
        alternate: {
          type: "ConditionalExpression",
          loc: "3:9-3:18",
          test: {
            type: "Identifier",
            loc: "3:9-3:10",
            name: "c",
          },
          consequent: {
            type: "Identifier",
            loc: "3:13-3:14",
            name: "d",
          },
          alternate: {
            type: "Identifier",
            loc: "3:17-3:18",
            name: "e",
          },
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:19",
      kind: {
        type: "ConditionalExpression",
        loc: "5:1-5:18",
        test: {
          type: "Identifier",
          loc: "5:1-5:2",
          name: "a",
        },
        consequent: {
          type: "ConditionalExpression",
          loc: "5:5-5:14",
          test: {
            type: "Identifier",
            loc: "5:5-5:6",
            name: "b",
          },
          consequent: {
            type: "Identifier",
            loc: "5:9-5:10",
            name: "c",
          },
          alternate: {
            type: "Identifier",
            loc: "5:13-5:14",
            name: "d",
          },
        },
        alternate: {
          type: "Identifier",
          loc: "5:17-5:18",
          name: "e",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:23",
      kind: {
        type: "ConditionalExpression",
        loc: "7:1-7:22",
        test: {
          type: "BinaryExpression",
          loc: "7:1-7:6",
          operator: "+",
          left: {
            type: "Identifier",
            loc: "7:1-7:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "7:5-7:6",
            name: "b",
          },
        },
        consequent: {
          type: "BinaryExpression",
          loc: "7:9-7:14",
          operator: "+",
          left: {
            type: "Identifier",
            loc: "7:9-7:10",
            name: "c",
          },
          right: {
            type: "Identifier",
            loc: "7:13-7:14",
            name: "d",
          },
        },
        alternate: {
          type: "BinaryExpression",
          loc: "7:17-7:22",
          operator: "+",
          left: {
            type: "Identifier",
            loc: "7:17-7:18",
            name: "e",
          },
          right: {
            type: "Identifier",
            loc: "7:21-7:22",
            name: "f",
          },
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:19",
      kind: {
        type: "SequenceExpression",
        loc: "9:1-9:18",
        expressions: [
          {
            type: "Identifier",
            loc: "9:1-9:2",
            name: "a",
          },
          {
            type: "ConditionalExpression",
            loc: "9:5-9:14",
            test: {
              type: "Identifier",
              loc: "9:5-9:6",
              name: "b",
            },
            consequent: {
              type: "Identifier",
              loc: "9:9-9:10",
              name: "c",
            },
            alternate: {
              type: "Identifier",
              loc: "9:13-9:14",
              name: "d",
            },
          },
          {
            type: "Identifier",
            loc: "9:17-9:18",
            name: "e",
          },
        ],
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}