{
  type: "Program",
  loc: "1:1-3:15",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:11",
      kind: {
        type: "ImportExpression",
        loc: "1:1-1:10",
        source: {
          type: "Identifier",
          loc: "1:8-1:9",
          name: "a",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:15",
      kind: {
        type: "ImportExpression",
        loc: "3:1-3:14",
        source: {
          type: "BinaryExpression",
          loc: "3:8-3:13",
          operator: "+",
          left: {
            type: "Identifier",
            loc: "3:8-3:9",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "3:12-3:13",
            name: "b",
          },
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}