{
  type: "Program",
  loc: "1:1-5:13",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:13",
      kind: {
        type: "LogicalExpression",
        loc: "1:1-1:12",
        operator: "&&",
        left: {
          type: "LogicalExpression",
          loc: "1:1-1:7",
          operator: "&&",
          left: {
            type: "Identifier",
            loc: "1:1-1:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "1:6-1:7",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "1:11-1:12",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:13",
      kind: {
        type: "LogicalExpression",
        loc: "3:1-3:12",
        operator: "||",
        left: {
          type: "LogicalExpression",
          loc: "3:1-3:7",
          operator: "||",
          left: {
            type: "Identifier",
            loc: "3:1-3:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "3:6-3:7",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "3:11-3:12",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:13",
      kind: {
        type: "LogicalExpression",
        loc: "5:1-5:12",
        operator: "??",
        left: {
          type: "LogicalExpression",
          loc: "5:1-5:7",
          operator: "??",
          left: {
            type: "Identifier",
            loc: "5:1-5:2",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "5:6-5:7",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "5:11-5:12",
          name: "c",
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}