{
  type: "Program",
  loc: "1:0-5:12",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:12",
      kind: {
        type: "LogicalExpression",
        loc: "1:0-1:11",
        operator: "&&",
        left: {
          type: "LogicalExpression",
          loc: "1:0-1:6",
          operator: "&&",
          left: {
            type: "Identifier",
            loc: "1:0-1:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "1:5-1:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "1:10-1:11",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:12",
      kind: {
        type: "LogicalExpression",
        loc: "3:0-3:11",
        operator: "||",
        left: {
          type: "LogicalExpression",
          loc: "3:0-3:6",
          operator: "||",
          left: {
            type: "Identifier",
            loc: "3:0-3:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "3:5-3:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "3:10-3:11",
          name: "c",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:12",
      kind: {
        type: "LogicalExpression",
        loc: "5:0-5:11",
        operator: "??",
        left: {
          type: "LogicalExpression",
          loc: "5:0-5:6",
          operator: "??",
          left: {
            type: "Identifier",
            loc: "5:0-5:1",
            name: "a",
          },
          right: {
            type: "Identifier",
            loc: "5:5-5:6",
            name: "b",
          },
        },
        right: {
          type: "Identifier",
          loc: "5:10-5:11",
          name: "c",
        },
      },
    },
  ],
  has_use_strict_directive: false,
}