{
  type: "Program",
  loc: "1:1-9:8",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:7",
      kind: {
        type: "MemberExpression",
        loc: "1:1-1:6",
        object: {
          type: "MemberExpression",
          loc: "1:1-1:4",
          object: {
            type: "Identifier",
            loc: "1:1-1:2",
            name: "a",
          },
          property: {
            type: "Identifier",
            loc: "1:3-1:4",
            name: "b",
          },
          computed: false,
          optional: false,
        },
        property: {
          type: "Identifier",
          loc: "1:5-1:6",
          name: "c",
        },
        computed: false,
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:9",
      kind: {
        type: "MemberExpression",
        loc: "3:1-3:8",
        object: {
          type: "MemberExpression",
          loc: "3:1-3:5",
          object: {
            type: "Identifier",
            loc: "3:1-3:2",
            name: "a",
          },
          property: {
            type: "Identifier",
            loc: "3:3-3:4",
            name: "b",
          },
          computed: true,
          optional: false,
        },
        property: {
          type: "Identifier",
          loc: "3:6-3:7",
          name: "c",
        },
        computed: true,
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:8",
      kind: {
        type: "MemberExpression",
        loc: "5:1-5:7",
        object: {
          type: "MemberExpression",
          loc: "5:1-5:4",
          object: {
            type: "Identifier",
            loc: "5:1-5:2",
            name: "a",
          },
          property: {
            type: "Identifier",
            loc: "5:3-5:4",
            name: "b",
          },
          computed: false,
          optional: false,
        },
        property: {
          type: "Identifier",
          loc: "5:5-5:6",
          name: "c",
        },
        computed: true,
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:8",
      kind: {
        type: "MemberExpression",
        loc: "7:1-7:7",
        object: {
          type: "Identifier",
          loc: "7:1-7:2",
          name: "a",
        },
        property: {
          type: "MemberExpression",
          loc: "7:3-7:6",
          object: {
            type: "Identifier",
            loc: "7:3-7:4",
            name: "b",
          },
          property: {
            type: "Identifier",
            loc: "7:5-7:6",
            name: "c",
          },
          computed: false,
          optional: false,
        },
        computed: true,
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:8",
      kind: {
        type: "MemberExpression",
        loc: "9:1-9:7",
        object: {
          type: "Identifier",
          loc: "9:1-9:2",
          name: "a",
        },
        property: {
          type: "PrivateIdentifier",
          loc: "9:3-9:7",
          name: "#foo",
        },
        computed: false,
        optional: false,
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}