{
  type: "Program",
  loc: "1:0-9:7",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:6",
      kind: {
        type: "MemberExpression",
        loc: "1:0-1:5",
        object: {
          type: "MemberExpression",
          loc: "1:0-1:3",
          object: {
            type: "Identifier",
            loc: "1:0-1:1",
            name: "a",
          },
          property: {
            type: "Identifier",
            loc: "1:2-1:3",
            name: "b",
          },
          computed: false,
          optional: false,
        },
        property: {
          type: "Identifier",
          loc: "1:4-1:5",
          name: "c",
        },
        computed: false,
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:8",
      kind: {
        type: "MemberExpression",
        loc: "3:0-3:7",
        object: {
          type: "MemberExpression",
          loc: "3:0-3:4",
          object: {
            type: "Identifier",
            loc: "3:0-3:1",
            name: "a",
          },
          property: {
            type: "Identifier",
            loc: "3:2-3:3",
            name: "b",
          },
          computed: true,
          optional: false,
        },
        property: {
          type: "Identifier",
          loc: "3:5-3:6",
          name: "c",
        },
        computed: true,
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:7",
      kind: {
        type: "MemberExpression",
        loc: "5:0-5:6",
        object: {
          type: "MemberExpression",
          loc: "5:0-5:3",
          object: {
            type: "Identifier",
            loc: "5:0-5:1",
            name: "a",
          },
          property: {
            type: "Identifier",
            loc: "5:2-5:3",
            name: "b",
          },
          computed: false,
          optional: false,
        },
        property: {
          type: "Identifier",
          loc: "5:4-5:5",
          name: "c",
        },
        computed: true,
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:0-7:7",
      kind: {
        type: "MemberExpression",
        loc: "7:0-7:6",
        object: {
          type: "Identifier",
          loc: "7:0-7:1",
          name: "a",
        },
        property: {
          type: "MemberExpression",
          loc: "7:2-7:5",
          object: {
            type: "Identifier",
            loc: "7:2-7:3",
            name: "b",
          },
          property: {
            type: "Identifier",
            loc: "7:4-7:5",
            name: "c",
          },
          computed: false,
          optional: false,
        },
        computed: true,
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:0-9:7",
      kind: {
        type: "MemberExpression",
        loc: "9:0-9:6",
        object: {
          type: "Identifier",
          loc: "9:0-9:1",
          name: "a",
        },
        property: {
          type: "PrivateIdentifier",
          loc: "9:3-9:6",
          name: "foo",
        },
        computed: false,
        optional: false,
      },
    },
  ],
  has_use_strict_directive: false,
}