{
  type: "Program",
  loc: "1:1-29:15",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:7",
      kind: {
        type: "NewExpression",
        loc: "1:1-1:6",
        callee: {
          type: "Identifier",
          loc: "1:5-1:6",
          name: "a",
        },
        arguments: [],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:9",
      kind: {
        type: "NewExpression",
        loc: "3:1-3:8",
        callee: {
          type: "Identifier",
          loc: "3:5-3:6",
          name: "a",
        },
        arguments: [],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:11",
      kind: {
        type: "NewExpression",
        loc: "5:1-5:10",
        callee: {
          type: "Identifier",
          loc: "5:5-5:6",
          name: "a",
        },
        arguments: [
          {
            type: "Identifier",
            loc: "5:7-5:8",
            name: "b",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:16",
      kind: {
        type: "NewExpression",
        loc: "7:1-7:15",
        callee: {
          type: "Identifier",
          loc: "7:5-7:6",
          name: "a",
        },
        arguments: [
          {
            type: "Identifier",
            loc: "7:7-7:8",
            name: "b",
          },
          {
            type: "Identifier",
            loc: "7:10-7:11",
            name: "c",
          },
          {
            type: "Identifier",
            loc: "7:13-7:14",
            name: "d",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:17",
      kind: {
        type: "NewExpression",
        loc: "9:1-9:16",
        callee: {
          type: "Identifier",
          loc: "9:5-9:6",
          name: "a",
        },
        arguments: [
          {
            type: "Identifier",
            loc: "9:7-9:8",
            name: "b",
          },
          {
            type: "Identifier",
            loc: "9:10-9:11",
            name: "c",
          },
          {
            type: "Identifier",
            loc: "9:13-9:14",
            name: "d",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:1-11:13",
      kind: {
        type: "NewExpression",
        loc: "11:1-11:12",
        callee: {
          type: "Identifier",
          loc: "11:5-11:6",
          name: "a",
        },
        arguments: [
          {
            type: "SpreadElement",
            loc: "11:7-11:11",
            argument: {
              type: "Identifier",
              loc: "11:10-11:11",
              name: "b",
            },
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:1-13:11",
      kind: {
        type: "BinaryExpression",
        loc: "13:1-13:10",
        operator: "+",
        left: {
          type: "NewExpression",
          loc: "13:1-13:6",
          callee: {
            type: "Identifier",
            loc: "13:5-13:6",
            name: "a",
          },
          arguments: [],
        },
        right: {
          type: "Identifier",
          loc: "13:9-13:10",
          name: "b",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "15:1-15:9",
      kind: {
        type: "NewExpression",
        loc: "15:1-15:8",
        callee: {
          type: "MemberExpression",
          loc: "15:5-15:8",
          object: {
            type: "Identifier",
            loc: "15:5-15:6",
            name: "a",
          },
          property: {
            type: "Identifier",
            loc: "15:7-15:8",
            name: "b",
          },
          computed: false,
          optional: false,
        },
        arguments: [],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:1-17:11",
      kind: {
        type: "NewExpression",
        loc: "17:1-17:10",
        callee: {
          type: "MemberExpression",
          loc: "17:5-17:8",
          object: {
            type: "Identifier",
            loc: "17:5-17:6",
            name: "a",
          },
          property: {
            type: "Identifier",
            loc: "17:7-17:8",
            name: "b",
          },
          computed: false,
          optional: false,
        },
        arguments: [],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "19:1-19:16",
      kind: {
        type: "CallExpression",
        loc: "19:1-19:15",
        callee: {
          type: "CallExpression",
          loc: "19:1-19:12",
          callee: {
            type: "NewExpression",
            loc: "19:1-19:9",
            callee: {
              type: "Identifier",
              loc: "19:5-19:6",
              name: "a",
            },
            arguments: [
              {
                type: "Identifier",
                loc: "19:7-19:8",
                name: "b",
              },
            ],
          },
          arguments: [
            {
              type: "Identifier",
              loc: "19:10-19:11",
              name: "c",
            },
          ],
          optional: false,
        },
        arguments: [
          {
            type: "Identifier",
            loc: "19:13-19:14",
            name: "d",
          },
        ],
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "21:1-21:11",
      kind: {
        type: "NewExpression",
        loc: "21:1-21:10",
        callee: {
          type: "NewExpression",
          loc: "21:5-21:10",
          callee: {
            type: "Identifier",
            loc: "21:9-21:10",
            name: "a",
          },
          arguments: [],
        },
        arguments: [],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "23:1-23:13",
      kind: {
        type: "NewExpression",
        loc: "23:1-23:12",
        callee: {
          type: "NewExpression",
          loc: "23:5-23:12",
          callee: {
            type: "Identifier",
            loc: "23:9-23:10",
            name: "a",
          },
          arguments: [],
        },
        arguments: [],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "25:1-25:11",
      kind: {
        type: "MemberExpression",
        loc: "25:1-25:10",
        object: {
          type: "NewExpression",
          loc: "25:1-25:8",
          callee: {
            type: "Identifier",
            loc: "25:5-25:6",
            name: "a",
          },
          arguments: [],
        },
        property: {
          type: "Identifier",
          loc: "25:9-25:10",
          name: "b",
        },
        computed: false,
        optional: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "28:1-28:16",
      kind: {
        type: "NewExpression",
        loc: "28:1-28:15",
        callee: {
          type: "MetaProperty",
          loc: "28:5-28:15",
          meta: {
            type: "Identifier",
            loc: "28:5-28:15",
            name: "new",
          },
          property: {
            type: "Identifier",
            loc: "28:5-28:15",
            name: "target",
          },
        },
        arguments: [],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "29:1-29:15",
      kind: {
        type: "NewExpression",
        loc: "29:1-29:14",
        callee: {
          type: "MemberExpression",
          loc: "29:5-29:14",
          object: {
            type: "Super",
            loc: "29:5-29:10",
          },
          property: {
            type: "Identifier",
            loc: "29:11-29:14",
            name: "foo",
          },
          computed: false,
        },
        arguments: [],
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}