{
  type: "Program",
  loc: "1:0-18:24",
  body: [
    {
      type: "Block",
      loc: "2:0-2:2",
      body: [],
    },
    {
      type: "EmptyStatement",
      loc: "2:2-2:3",
    },
    {
      type: "ExpressionStatement",
      loc: "4:0-4:5",
      kind: {
        type: "ObjectExpression",
        loc: "4:1-4:3",
        properties: [],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "6:0-6:11",
      kind: {
        type: "ObjectExpression",
        loc: "6:1-6:9",
        properties: [
          {
            type: "Property",
            loc: "6:3-6:7",
            key: {
              type: "Identifier",
              loc: "6:3-6:4",
              name: "a",
            },
            value: {
              type: "Identifier",
              loc: "6:6-6:7",
              name: "b",
            },
            is_computed: false,
            is_shorthand: false,
            is_method: false,
            kind: "init",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "8:0-8:11",
      kind: {
        type: "ObjectExpression",
        loc: "8:1-8:9",
        properties: [
          {
            type: "Property",
            loc: "8:3-8:7",
            key: {
              type: "Literal",
              loc: "8:3-8:4",
              value: 1,
            },
            value: {
              type: "Identifier",
              loc: "8:6-8:7",
              name: "b",
            },
            is_computed: false,
            is_shorthand: false,
            is_method: false,
            kind: "init",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "10:0-10:16",
      kind: {
        type: "ObjectExpression",
        loc: "10:1-10:14",
        properties: [
          {
            type: "Property",
            loc: "10:3-10:12",
            key: {
              type: "Literal",
              loc: "10:3-10:9",
              value: "prop",
            },
            value: {
              type: "Identifier",
              loc: "10:11-10:12",
              name: "b",
            },
            is_computed: false,
            is_shorthand: false,
            is_method: false,
            kind: "init",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "12:0-12:15",
      kind: {
        type: "ObjectExpression",
        loc: "12:1-12:13",
        properties: [
          {
            type: "Property",
            loc: "12:3-12:11",
            key: {
              type: "Identifier",
              loc: "12:4-12:7",
              name: "key",
            },
            value: {
              type: "Identifier",
              loc: "12:10-12:11",
              name: "b",
            },
            is_computed: true,
            is_shorthand: false,
            is_method: false,
            kind: "init",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "14:0-14:14",
      kind: {
        type: "ObjectExpression",
        loc: "14:1-14:12",
        properties: [
          {
            type: "Property",
            loc: "14:3-14:4",
            key: {
              type: "Identifier",
              loc: "14:3-14:4",
              name: "a",
            },
            value: null,
            is_computed: false,
            is_shorthand: true,
            is_method: false,
            kind: "init",
          },
          {
            type: "Property",
            loc: "14:6-14:7",
            key: {
              type: "Identifier",
              loc: "14:6-14:7",
              name: "b",
            },
            value: null,
            is_computed: false,
            is_shorthand: true,
            is_method: false,
            kind: "init",
          },
          {
            type: "Property",
            loc: "14:9-14:10",
            key: {
              type: "Identifier",
              loc: "14:9-14:10",
              name: "c",
            },
            value: null,
            is_computed: false,
            is_shorthand: true,
            is_method: false,
            kind: "init",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "16:0-16:23",
      kind: {
        type: "ObjectExpression",
        loc: "16:1-16:21",
        properties: [
          {
            type: "Property",
            loc: "16:3-16:7",
            key: {
              type: "Identifier",
              loc: "16:3-16:4",
              name: "a",
            },
            value: {
              type: "Identifier",
              loc: "16:6-16:7",
              name: "b",
            },
            is_computed: false,
            is_shorthand: false,
            is_method: false,
            kind: "init",
          },
          {
            type: "Property",
            loc: "16:9-16:13",
            key: {
              type: "Identifier",
              loc: "16:9-16:10",
              name: "c",
            },
            value: {
              type: "Identifier",
              loc: "16:12-16:13",
              name: "d",
            },
            is_computed: false,
            is_shorthand: false,
            is_method: false,
            kind: "init",
          },
          {
            type: "Property",
            loc: "16:15-16:19",
            key: {
              type: "Identifier",
              loc: "16:15-16:16",
              name: "e",
            },
            value: {
              type: "Identifier",
              loc: "16:18-16:19",
              name: "f",
            },
            is_computed: false,
            is_shorthand: false,
            is_method: false,
            kind: "init",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "18:0-18:24",
      kind: {
        type: "ObjectExpression",
        loc: "18:1-18:22",
        properties: [
          {
            type: "Property",
            loc: "18:3-18:7",
            key: {
              type: "Identifier",
              loc: "18:3-18:4",
              name: "a",
            },
            value: {
              type: "Identifier",
              loc: "18:6-18:7",
              name: "b",
            },
            is_computed: false,
            is_shorthand: false,
            is_method: false,
            kind: "init",
          },
          {
            type: "Property",
            loc: "18:9-18:13",
            key: {
              type: "Identifier",
              loc: "18:9-18:10",
              name: "c",
            },
            value: {
              type: "Identifier",
              loc: "18:12-18:13",
              name: "d",
            },
            is_computed: false,
            is_shorthand: false,
            is_method: false,
            kind: "init",
          },
          {
            type: "Property",
            loc: "18:15-18:19",
            key: {
              type: "Identifier",
              loc: "18:15-18:16",
              name: "e",
            },
            value: {
              type: "Identifier",
              loc: "18:18-18:19",
              name: "f",
            },
            is_computed: false,
            is_shorthand: false,
            is_method: false,
            kind: "init",
          },
        ],
      },
    },
  ],
}