{
  type: "Program",
  loc: "1:0-5:5",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:39",
      kind: {
        type: "BinaryExpression",
        loc: "1:0-1:38",
        operator: "|",
        left: {
          type: "Identifier",
          loc: "1:0-1:1",
          name: "a",
        },
        right: {
          type: "BinaryExpression",
          loc: "1:4-1:38",
          operator: "^",
          left: {
            type: "Identifier",
            loc: "1:4-1:5",
            name: "b",
          },
          right: {
            type: "BinaryExpression",
            loc: "1:8-1:38",
            operator: "&",
            left: {
              type: "Identifier",
              loc: "1:8-1:9",
              name: "c",
            },
            right: {
              type: "BinaryExpression",
              loc: "1:12-1:38",
              operator: "in",
              left: {
                type: "Identifier",
                loc: "1:12-1:13",
                name: "d",
              },
              right: {
                type: "BinaryExpression",
                loc: "1:17-1:38",
                operator: ">>",
                left: {
                  type: "Identifier",
                  loc: "1:17-1:18",
                  name: "e",
                },
                right: {
                  type: "BinaryExpression",
                  loc: "1:22-1:38",
                  operator: "+",
                  left: {
                    type: "Identifier",
                    loc: "1:22-1:23",
                    name: "f",
                  },
                  right: {
                    type: "BinaryExpression",
                    loc: "1:26-1:38",
                    operator: "*",
                    left: {
                      type: "Identifier",
                      loc: "1:26-1:27",
                      name: "g",
                    },
                    right: {
                      type: "BinaryExpression",
                      loc: "1:30-1:38",
                      operator: "**",
                      left: {
                        type: "Identifier",
                        loc: "1:30-1:31",
                        name: "h",
                      },
                      right: {
                        type: "UpdateExpression",
                        loc: "1:35-1:38",
                        operator: "++",
                        argument: {
                          type: "Identifier",
                          loc: "1:35-1:36",
                          name: "i",
                        },
                        prefix: false,
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:39",
      kind: {
        type: "BinaryExpression",
        loc: "3:0-3:38",
        operator: "|",
        left: {
          type: "BinaryExpression",
          loc: "3:0-3:34",
          operator: "^",
          left: {
            type: "BinaryExpression",
            loc: "3:0-3:30",
            operator: "&",
            left: {
              type: "BinaryExpression",
              loc: "3:0-3:26",
              operator: "in",
              left: {
                type: "BinaryExpression",
                loc: "3:0-3:21",
                operator: ">>",
                left: {
                  type: "BinaryExpression",
                  loc: "3:0-3:16",
                  operator: "+",
                  left: {
                    type: "BinaryExpression",
                    loc: "3:0-3:12",
                    operator: "*",
                    left: {
                      type: "BinaryExpression",
                      loc: "3:0-3:8",
                      operator: "**",
                      left: {
                        type: "UpdateExpression",
                        loc: "3:0-3:3",
                        operator: "++",
                        argument: {
                          type: "Identifier",
                          loc: "3:2-3:3",
                          name: "a",
                        },
                        prefix: true,
                      },
                      right: {
                        type: "Identifier",
                        loc: "3:7-3:8",
                        name: "b",
                      },
                    },
                    right: {
                      type: "Identifier",
                      loc: "3:11-3:12",
                      name: "c",
                    },
                  },
                  right: {
                    type: "Identifier",
                    loc: "3:15-3:16",
                    name: "d",
                  },
                },
                right: {
                  type: "Identifier",
                  loc: "3:20-3:21",
                  name: "e",
                },
              },
              right: {
                type: "Identifier",
                loc: "3:25-3:26",
                name: "f",
              },
            },
            right: {
              type: "Identifier",
              loc: "3:29-3:30",
              name: "g",
            },
          },
          right: {
            type: "Identifier",
            loc: "3:33-3:34",
            name: "h",
          },
        },
        right: {
          type: "Identifier",
          loc: "3:37-3:38",
          name: "i",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:5",
      kind: {
        type: "UnaryExpression",
        loc: "5:0-5:4",
        operator: "+",
        argument: {
          type: "UpdateExpression",
          loc: "5:1-5:4",
          operator: "++",
          argument: {
            type: "Identifier",
            loc: "5:1-5:2",
            name: "a",
          },
          prefix: false,
        },
      },
    },
  ],
}