{
  type: "Program",
  loc: "1:0-7:11",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:52",
      kind: {
        type: "SequenceExpression",
        loc: "1:0-1:51",
        expressions: [
          {
            type: "Identifier",
            loc: "1:0-1:1",
            name: "a",
          },
          {
            type: "LogicalExpression",
            loc: "1:4-1:51",
            operator: "&&",
            left: {
              type: "Identifier",
              loc: "1:4-1:5",
              name: "b",
            },
            right: {
              type: "BinaryExpression",
              loc: "1:9-1:51",
              operator: "|",
              left: {
                type: "Identifier",
                loc: "1:9-1:10",
                name: "c",
              },
              right: {
                type: "BinaryExpression",
                loc: "1:13-1:51",
                operator: "^",
                left: {
                  type: "Identifier",
                  loc: "1:13-1:14",
                  name: "d",
                },
                right: {
                  type: "BinaryExpression",
                  loc: "1:17-1:51",
                  operator: "&",
                  left: {
                    type: "Identifier",
                    loc: "1:17-1:18",
                    name: "e",
                  },
                  right: {
                    type: "BinaryExpression",
                    loc: "1:21-1:51",
                    operator: "==",
                    left: {
                      type: "Identifier",
                      loc: "1:21-1:22",
                      name: "f",
                    },
                    right: {
                      type: "BinaryExpression",
                      loc: "1:26-1:51",
                      operator: "<",
                      left: {
                        type: "Identifier",
                        loc: "1:26-1:27",
                        name: "g",
                      },
                      right: {
                        type: "BinaryExpression",
                        loc: "1:30-1:51",
                        operator: ">>",
                        left: {
                          type: "Identifier",
                          loc: "1:30-1:31",
                          name: "h",
                        },
                        right: {
                          type: "BinaryExpression",
                          loc: "1:35-1:51",
                          operator: "+",
                          left: {
                            type: "Identifier",
                            loc: "1:35-1:36",
                            name: "i",
                          },
                          right: {
                            type: "BinaryExpression",
                            loc: "1:39-1:51",
                            operator: "*",
                            left: {
                              type: "Identifier",
                              loc: "1:39-1:40",
                              name: "j",
                            },
                            right: {
                              type: "BinaryExpression",
                              loc: "1:43-1:51",
                              operator: "**",
                              left: {
                                type: "Identifier",
                                loc: "1:43-1:44",
                                name: "k",
                              },
                              right: {
                                type: "UpdateExpression",
                                loc: "1:48-1:51",
                                operator: "++",
                                argument: {
                                  type: "Identifier",
                                  loc: "1:48-1:49",
                                  name: "l",
                                },
                                prefix: false,
                              },
                            },
                          },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:52",
      kind: {
        type: "SequenceExpression",
        loc: "3:0-3:51",
        expressions: [
          {
            type: "LogicalExpression",
            loc: "3:0-3:47",
            operator: "&&",
            left: {
              type: "BinaryExpression",
              loc: "3:0-3:42",
              operator: "|",
              left: {
                type: "BinaryExpression",
                loc: "3:0-3:38",
                operator: "^",
                left: {
                  type: "BinaryExpression",
                  loc: "3:0-3:34",
                  operator: "&",
                  left: {
                    type: "BinaryExpression",
                    loc: "3:0-3:30",
                    operator: "==",
                    left: {
                      type: "BinaryExpression",
                      loc: "3:0-3:25",
                      operator: "<",
                      left: {
                        type: "BinaryExpression",
                        loc: "3:0-3:21",
                        operator: ">>",
                        left: {
                          type: "BinaryExpression",
                          loc: "3:0-3:16",
                          operator: "+",
                          left: {
                            type: "BinaryExpression",
                            loc: "3:0-3:12",
                            operator: "*",
                            left: {
                              type: "BinaryExpression",
                              loc: "3:0-3:8",
                              operator: "**",
                              left: {
                                type: "UpdateExpression",
                                loc: "3:0-3:3",
                                operator: "++",
                                argument: {
                                  type: "Identifier",
                                  loc: "3:2-3:3",
                                  name: "a",
                                },
                                prefix: true,
                              },
                              right: {
                                type: "Identifier",
                                loc: "3:7-3:8",
                                name: "b",
                              },
                            },
                            right: {
                              type: "Identifier",
                              loc: "3:11-3:12",
                              name: "c",
                            },
                          },
                          right: {
                            type: "Identifier",
                            loc: "3:15-3:16",
                            name: "d",
                          },
                        },
                        right: {
                          type: "Identifier",
                          loc: "3:20-3:21",
                          name: "e",
                        },
                      },
                      right: {
                        type: "Identifier",
                        loc: "3:24-3:25",
                        name: "f",
                      },
                    },
                    right: {
                      type: "Identifier",
                      loc: "3:29-3:30",
                      name: "g",
                    },
                  },
                  right: {
                    type: "Identifier",
                    loc: "3:33-3:34",
                    name: "h",
                  },
                },
                right: {
                  type: "Identifier",
                  loc: "3:37-3:38",
                  name: "i",
                },
              },
              right: {
                type: "Identifier",
                loc: "3:41-3:42",
                name: "j",
              },
            },
            right: {
              type: "Identifier",
              loc: "3:46-3:47",
              name: "k",
            },
          },
          {
            type: "Identifier",
            loc: "3:50-3:51",
            name: "l",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:5",
      kind: {
        type: "UnaryExpression",
        loc: "5:0-5:4",
        operator: "+",
        argument: {
          type: "UpdateExpression",
          loc: "5:1-5:4",
          operator: "++",
          argument: {
            type: "Identifier",
            loc: "5:1-5:2",
            name: "a",
          },
          prefix: false,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:0-7:11",
      kind: {
        type: "AssignmentExpression",
        loc: "7:0-7:10",
        operator: "=",
        left: {
          type: "Identifier",
          loc: "7:0-7:1",
          name: "a",
        },
        right: {
          type: "LogicalExpression",
          loc: "7:4-7:10",
          operator: "&&",
          left: {
            type: "Identifier",
            loc: "7:4-7:5",
            name: "b",
          },
          right: {
            type: "Identifier",
            loc: "7:9-7:10",
            name: "c",
          },
        },
      },
    },
  ],
  has_use_strict_directive: false,
}