{
  type: "Program",
  loc: "1:0-31:4",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:5",
      kind: {
        type: "ThisExpression",
        loc: "1:0-1:4",
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:5",
      kind: {
        type: "Literal",
        loc: "5:0-5:4",
        value: null,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:0-7:5",
      kind: {
        type: "Literal",
        loc: "7:0-7:4",
        value: true,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:0-9:6",
      kind: {
        type: "Literal",
        loc: "9:0-9:5",
        value: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:0-13:3",
      kind: {
        type: "ArrayExpression",
        loc: "13:0-13:2",
        elements: [],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "15:0-15:4",
      kind: {
        type: "ArrayExpression",
        loc: "15:0-15:3",
        elements: [
          null,
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:0-17:6",
      kind: {
        type: "ArrayExpression",
        loc: "17:0-17:5",
        elements: [
          null,
          null,
          null,
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "19:0-19:10",
      kind: {
        type: "ArrayExpression",
        loc: "19:0-19:9",
        elements: [
          {
            type: "Identifier",
            loc: "19:1-19:2",
            name: "a",
          },
          {
            type: "Identifier",
            loc: "19:4-19:5",
            name: "b",
          },
          {
            type: "Identifier",
            loc: "19:7-19:8",
            name: "c",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "21:0-21:11",
      kind: {
        type: "ArrayExpression",
        loc: "21:0-21:10",
        elements: [
          {
            type: "Identifier",
            loc: "21:1-21:2",
            name: "a",
          },
          {
            type: "Identifier",
            loc: "21:4-21:5",
            name: "b",
          },
          {
            type: "Identifier",
            loc: "21:7-21:8",
            name: "c",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "23:0-23:14",
      kind: {
        type: "ArrayExpression",
        loc: "23:0-23:13",
        elements: [
          null,
          {
            type: "Identifier",
            loc: "23:2-23:3",
            name: "a",
          },
          null,
          {
            type: "Identifier",
            loc: "23:6-23:7",
            name: "b",
          },
          {
            type: "Identifier",
            loc: "23:9-23:10",
            name: "c",
          },
          null,
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "25:0-25:17",
      kind: {
        type: "ArrayExpression",
        loc: "25:0-25:16",
        elements: [
          {
            type: "SpreadElement",
            loc: "25:1-25:5",
            argument: {
              type: "Identifier",
              loc: "25:4-25:5",
              name: "a",
            },
          },
          {
            type: "SpreadElement",
            loc: "25:6-25:10",
            argument: {
              type: "Identifier",
              loc: "25:9-25:10",
              name: "b",
            },
          },
          {
            type: "SpreadElement",
            loc: "25:11-25:15",
            argument: {
              type: "Identifier",
              loc: "25:14-25:15",
              name: "c",
            },
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "27:0-27:8",
      kind: {
        type: "ArrayExpression",
        loc: "27:0-27:7",
        elements: [
          {
            type: "SpreadElement",
            loc: "27:1-27:5",
            argument: {
              type: "Identifier",
              loc: "27:4-27:5",
              name: "a",
            },
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "31:0-31:4",
      kind: {
        type: "Identifier",
        loc: "31:0-31:3",
        name: "get",
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}