{
  type: "Program",
  loc: "1:0-3:11",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:5",
      kind: {
        type: "SequenceExpression",
        loc: "1:0-1:4",
        expressions: [
          {
            type: "Identifier",
            loc: "1:0-1:1",
            name: "a",
          },
          {
            type: "Identifier",
            loc: "1:3-1:4",
            name: "b",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:11",
      kind: {
        type: "SequenceExpression",
        loc: "3:0-3:10",
        expressions: [
          {
            type: "Identifier",
            loc: "3:0-3:1",
            name: "a",
          },
          {
            type: "Identifier",
            loc: "3:3-3:4",
            name: "b",
          },
          {
            type: "Identifier",
            loc: "3:6-3:7",
            name: "c",
          },
          {
            type: "Identifier",
            loc: "3:9-3:10",
            name: "d",
          },
        ],
      },
    },
  ],
  has_use_strict_directive: false,
}