{
  type: "Program",
  loc: "1:1-3:12",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:6",
      kind: {
        type: "SequenceExpression",
        loc: "1:1-1:5",
        expressions: [
          {
            type: "Identifier",
            loc: "1:1-1:2",
            name: "a",
          },
          {
            type: "Identifier",
            loc: "1:4-1:5",
            name: "b",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:12",
      kind: {
        type: "SequenceExpression",
        loc: "3:1-3:11",
        expressions: [
          {
            type: "Identifier",
            loc: "3:1-3:2",
            name: "a",
          },
          {
            type: "Identifier",
            loc: "3:4-3:5",
            name: "b",
          },
          {
            type: "Identifier",
            loc: "3:7-3:8",
            name: "c",
          },
          {
            type: "Identifier",
            loc: "3:10-3:11",
            name: "d",
          },
        ],
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}