{
  type: "Program",
  loc: "1:1-17:14",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:9",
      kind: {
        type: "CallExpression",
        loc: "1:1-1:8",
        callee: {
          type: "Super",
          loc: "1:1-1:6",
        },
        arguments: [],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:10",
      kind: {
        type: "CallExpression",
        loc: "3:1-3:9",
        callee: {
          type: "Super",
          loc: "3:1-3:6",
        },
        arguments: [
          {
            type: "Identifier",
            loc: "3:7-3:8",
            name: "a",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:16",
      kind: {
        type: "CallExpression",
        loc: "5:1-5:15",
        callee: {
          type: "Super",
          loc: "5:1-5:6",
        },
        arguments: [
          {
            type: "Identifier",
            loc: "5:7-5:8",
            name: "a",
          },
          {
            type: "Identifier",
            loc: "5:10-5:11",
            name: "b",
          },
          {
            type: "Identifier",
            loc: "5:13-5:14",
            name: "c",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:18",
      kind: {
        type: "CallExpression",
        loc: "7:1-7:17",
        callee: {
          type: "Super",
          loc: "7:1-7:6",
        },
        arguments: [
          {
            type: "Identifier",
            loc: "7:8-7:9",
            name: "a",
          },
          {
            type: "Identifier",
            loc: "7:11-7:12",
            name: "b",
          },
          {
            type: "Identifier",
            loc: "7:14-7:15",
            name: "c",
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:13",
      kind: {
        type: "CallExpression",
        loc: "9:1-9:12",
        callee: {
          type: "Super",
          loc: "9:1-9:6",
        },
        arguments: [
          {
            type: "SpreadElement",
            loc: "9:7-9:11",
            argument: {
              type: "Identifier",
              loc: "9:10-9:11",
              name: "a",
            },
          },
        ],
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:1-11:11",
      kind: {
        type: "MemberExpression",
        loc: "11:1-11:10",
        object: {
          type: "Super",
          loc: "11:1-11:6",
        },
        property: {
          type: "Identifier",
          loc: "11:7-11:10",
          name: "foo",
        },
        computed: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:1-13:13",
      kind: {
        type: "MemberExpression",
        loc: "13:1-13:12",
        object: {
          type: "Super",
          loc: "13:1-13:6",
        },
        property: {
          type: "Identifier",
          loc: "13:7-13:12",
          name: "super",
        },
        computed: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "15:1-15:12",
      kind: {
        type: "MemberExpression",
        loc: "15:1-15:11",
        object: {
          type: "Super",
          loc: "15:1-15:6",
        },
        property: {
          type: "Identifier",
          loc: "15:7-15:10",
          name: "foo",
        },
        computed: true,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:1-17:14",
      kind: {
        type: "MemberExpression",
        loc: "17:1-17:13",
        object: {
          type: "Super",
          loc: "17:1-17:6",
        },
        property: {
          type: "BinaryExpression",
          loc: "17:7-17:12",
          operator: "+",
          left: {
            type: "Literal",
            loc: "17:7-17:8",
            value: 1,
          },
          right: {
            type: "Literal",
            loc: "17:11-17:12",
            value: 2,
          },
        },
        computed: true,
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}