{
  type: "Program",
  loc: "1:1-13:10",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:4",
      kind: {
        type: "UnaryExpression",
        loc: "1:1-1:3",
        operator: "+",
        argument: {
          type: "Identifier",
          loc: "1:2-1:3",
          name: "a",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:4",
      kind: {
        type: "UnaryExpression",
        loc: "3:1-3:3",
        operator: "-",
        argument: {
          type: "Identifier",
          loc: "3:2-3:3",
          name: "a",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:4",
      kind: {
        type: "UnaryExpression",
        loc: "5:1-5:3",
        operator: "!",
        argument: {
          type: "Identifier",
          loc: "5:2-5:3",
          name: "a",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:4",
      kind: {
        type: "UnaryExpression",
        loc: "7:1-7:3",
        operator: "~",
        argument: {
          type: "Identifier",
          loc: "7:2-7:3",
          name: "a",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:10",
      kind: {
        type: "UnaryExpression",
        loc: "9:1-9:9",
        operator: "typeof",
        argument: {
          type: "Identifier",
          loc: "9:8-9:9",
          name: "a",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:1-11:8",
      kind: {
        type: "UnaryExpression",
        loc: "11:1-11:7",
        operator: "void",
        argument: {
          type: "Identifier",
          loc: "11:6-11:7",
          name: "a",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:1-13:10",
      kind: {
        type: "UnaryExpression",
        loc: "13:1-13:9",
        operator: "delete",
        argument: {
          type: "Identifier",
          loc: "13:8-13:9",
          name: "a",
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}