{
  type: "Program",
  loc: "1:0-13:9",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:3",
      kind: {
        type: "UnaryExpression",
        loc: "1:0-1:2",
        operator: "+",
        argument: {
          type: "Identifier",
          loc: "1:1-1:2",
          name: "a",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:3",
      kind: {
        type: "UnaryExpression",
        loc: "3:0-3:2",
        operator: "-",
        argument: {
          type: "Identifier",
          loc: "3:1-3:2",
          name: "a",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:3",
      kind: {
        type: "UnaryExpression",
        loc: "5:0-5:2",
        operator: "!",
        argument: {
          type: "Identifier",
          loc: "5:1-5:2",
          name: "a",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:0-7:3",
      kind: {
        type: "UnaryExpression",
        loc: "7:0-7:2",
        operator: "~",
        argument: {
          type: "Identifier",
          loc: "7:1-7:2",
          name: "a",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:0-9:9",
      kind: {
        type: "UnaryExpression",
        loc: "9:0-9:8",
        operator: "typeof",
        argument: {
          type: "Identifier",
          loc: "9:7-9:8",
          name: "a",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:0-11:7",
      kind: {
        type: "UnaryExpression",
        loc: "11:0-11:6",
        operator: "void",
        argument: {
          type: "Identifier",
          loc: "11:5-11:6",
          name: "a",
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:0-13:9",
      kind: {
        type: "UnaryExpression",
        loc: "13:0-13:8",
        operator: "delete",
        argument: {
          type: "Identifier",
          loc: "13:7-13:8",
          name: "a",
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}