{
  type: "Program",
  loc: "1:1-11:6",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:1-1:5",
      kind: {
        type: "UpdateExpression",
        loc: "1:1-1:4",
        operator: "++",
        argument: {
          type: "Identifier",
          loc: "1:3-1:4",
          name: "a",
        },
        prefix: true,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:1-3:5",
      kind: {
        type: "UpdateExpression",
        loc: "3:1-3:4",
        operator: "--",
        argument: {
          type: "Identifier",
          loc: "3:3-3:4",
          name: "a",
        },
        prefix: true,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:1-5:5",
      kind: {
        type: "UpdateExpression",
        loc: "5:1-5:4",
        operator: "++",
        argument: {
          type: "Identifier",
          loc: "5:1-5:2",
          name: "a",
        },
        prefix: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:1-7:5",
      kind: {
        type: "UpdateExpression",
        loc: "7:1-7:4",
        operator: "--",
        argument: {
          type: "Identifier",
          loc: "7:1-7:2",
          name: "a",
        },
        prefix: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:1-9:6",
      kind: {
        type: "UnaryExpression",
        loc: "9:1-9:5",
        operator: "!",
        argument: {
          type: "UpdateExpression",
          loc: "9:2-9:5",
          operator: "++",
          argument: {
            type: "Identifier",
            loc: "9:2-9:3",
            name: "a",
          },
          prefix: false,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:1-11:6",
      kind: {
        type: "UnaryExpression",
        loc: "11:1-11:5",
        operator: "!",
        argument: {
          type: "UpdateExpression",
          loc: "11:2-11:5",
          operator: "--",
          argument: {
            type: "Identifier",
            loc: "11:2-11:3",
            name: "a",
          },
          prefix: false,
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}