{
  type: "Program",
  loc: "1:0-17:6",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:4",
      kind: {
        type: "UpdateExpression",
        loc: "1:0-1:3",
        operator: "++",
        argument: {
          type: "Identifier",
          loc: "1:2-1:3",
          name: "a",
        },
        prefix: true,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:4",
      kind: {
        type: "UpdateExpression",
        loc: "3:0-3:3",
        operator: "--",
        argument: {
          type: "Identifier",
          loc: "3:2-3:3",
          name: "a",
        },
        prefix: true,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:4",
      kind: {
        type: "UpdateExpression",
        loc: "5:0-5:3",
        operator: "++",
        argument: {
          type: "Identifier",
          loc: "5:0-5:1",
          name: "a",
        },
        prefix: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:0-7:4",
      kind: {
        type: "UpdateExpression",
        loc: "7:0-7:3",
        operator: "--",
        argument: {
          type: "Identifier",
          loc: "7:0-7:1",
          name: "a",
        },
        prefix: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:0-9:6",
      kind: {
        type: "UpdateExpression",
        loc: "9:0-9:5",
        operator: "++",
        argument: {
          type: "UpdateExpression",
          loc: "9:2-9:5",
          operator: "++",
          argument: {
            type: "Identifier",
            loc: "9:4-9:5",
            name: "a",
          },
          prefix: true,
        },
        prefix: true,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:0-11:6",
      kind: {
        type: "UpdateExpression",
        loc: "11:0-11:5",
        operator: "--",
        argument: {
          type: "UpdateExpression",
          loc: "11:2-11:5",
          operator: "--",
          argument: {
            type: "Identifier",
            loc: "11:4-11:5",
            name: "a",
          },
          prefix: true,
        },
        prefix: true,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "13:0-13:6",
      kind: {
        type: "UpdateExpression",
        loc: "13:0-13:5",
        operator: "++",
        argument: {
          type: "UpdateExpression",
          loc: "13:0-13:3",
          operator: "++",
          argument: {
            type: "Identifier",
            loc: "13:0-13:1",
            name: "a",
          },
          prefix: false,
        },
        prefix: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "15:0-15:6",
      kind: {
        type: "UpdateExpression",
        loc: "15:0-15:5",
        operator: "--",
        argument: {
          type: "UpdateExpression",
          loc: "15:0-15:3",
          operator: "--",
          argument: {
            type: "Identifier",
            loc: "15:0-15:1",
            name: "a",
          },
          prefix: false,
        },
        prefix: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "17:0-17:6",
      kind: {
        type: "UpdateExpression",
        loc: "17:0-17:5",
        operator: "++",
        argument: {
          type: "UpdateExpression",
          loc: "17:2-17:5",
          operator: "++",
          argument: {
            type: "Identifier",
            loc: "17:2-17:3",
            name: "a",
          },
          prefix: false,
        },
        prefix: true,
      },
    },
  ],
  has_use_strict_directive: false,
}