{
  type: "Program",
  loc: "1:0-11:5",
  body: [
    {
      type: "ExpressionStatement",
      loc: "1:0-1:4",
      kind: {
        type: "UpdateExpression",
        loc: "1:0-1:3",
        operator: "++",
        argument: {
          type: "Identifier",
          loc: "1:2-1:3",
          name: "a",
        },
        prefix: true,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "3:0-3:4",
      kind: {
        type: "UpdateExpression",
        loc: "3:0-3:3",
        operator: "--",
        argument: {
          type: "Identifier",
          loc: "3:2-3:3",
          name: "a",
        },
        prefix: true,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "5:0-5:4",
      kind: {
        type: "UpdateExpression",
        loc: "5:0-5:3",
        operator: "++",
        argument: {
          type: "Identifier",
          loc: "5:0-5:1",
          name: "a",
        },
        prefix: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "7:0-7:4",
      kind: {
        type: "UpdateExpression",
        loc: "7:0-7:3",
        operator: "--",
        argument: {
          type: "Identifier",
          loc: "7:0-7:1",
          name: "a",
        },
        prefix: false,
      },
    },
    {
      type: "ExpressionStatement",
      loc: "9:0-9:5",
      kind: {
        type: "UnaryExpression",
        loc: "9:0-9:4",
        operator: "!",
        argument: {
          type: "UpdateExpression",
          loc: "9:1-9:4",
          operator: "++",
          argument: {
            type: "Identifier",
            loc: "9:1-9:2",
            name: "a",
          },
          prefix: false,
        },
      },
    },
    {
      type: "ExpressionStatement",
      loc: "11:0-11:5",
      kind: {
        type: "UnaryExpression",
        loc: "11:0-11:4",
        operator: "!",
        argument: {
          type: "UpdateExpression",
          loc: "11:1-11:4",
          operator: "--",
          argument: {
            type: "Identifier",
            loc: "11:1-11:2",
            name: "a",
          },
          prefix: false,
        },
      },
    },
  ],
  sourceType: "script",
  has_use_strict_directive: false,
}