name: brimstone

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Install toolchain components
        run: rustup component add rustfmt clippy

      - name: Check formatting
        run: cargo bfmt --install --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

  cargo-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Run tests
        run: cargo test

  # Run all integration tests for implemented features with debug build.
  integration-tests-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      
      - name: Checkout test262 repo
        run: ./tests/test262/install_test262.sh

      - name: Run integration tests
        run: cargo brimstone-test -- --reindex --ignore-unimplemented

  # Run all integration tests for implemented features with release build.
  integration-tests-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      
      - name: Checkout test262 repo
        run: ./tests/test262/install_test262.sh

      - name: Run integration tests
        run: cargo brimstone-test --release -- --reindex --ignore-unimplemented

  # Run all integration tests for implemented features with GC stress test mode on.
  integration-tests-gc-stress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      
      - name: Checkout test262 repo
        run: ./tests/test262/install_test262.sh

      - name: Run integration tests
        run: cargo brimstone-test --release --features gc_stress_test -- --reindex --ignore-unimplemented

  # Run all integration tests for implemented features with handle tracking mode on.
  integration-tests-handle-tracking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Checkout test262 repo
        run: ./tests/test262/install_test262.sh

      - name: Run integration tests
        run: cargo brimstone-test --release --features handle_stats -- --reindex --ignore-unimplemented

  integration-tests-panic-on-oom-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        run: rustup install nightly

      - name: Set nightly as default
        run: rustup override set nightly

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Checkout test262 repo
        run: ./tests/test262/install_test262.sh

      - name: Run integration tests on nightly without alloc_error feature enabled
        run: cargo brimstone-test --release --no-default-features --features nightly -- --reindex --ignore-unimplemented
    
  build-perf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Build performance test suite
        run: cargo build -p brimstone_perf

      - name: Build benchmarks tests
        run: cargo bench --no-run

  build-fuzzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Build fuzzer
        run: ./tests/fuzz/build.sh
