name: brimstone

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5

      - name: Install toolchain components
        run: rustup component add rustfmt clippy

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

  snapshot-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5

      - name: Run tests
        run: cargo test

  # Run all integration tests for implemented features with debug build.
  integration-tests-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      
      - name: Checkout test262 repo
        run: ./tests/test262/install_test262.sh

      - name: Run integration tests
        run: |
          cargo brimstone-test -- --reindex
          cargo brimstone-test -- --ignore-unimplemented

  # Run all integration tests for implemented features with release build.
  integration-tests-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      
      - name: Checkout test262 repo
        run: ./tests/test262/install_test262.sh

      - name: Run integration tests
        run: |
          cargo brimstone-test -- --reindex
          cargo brimstone-test --release -- --ignore-unimplemented

  # Run all integration tests for implemented features with GC stress test mode on.
  integration-tests-gc-stress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      
      - name: Checkout test262 repo
        run: ./tests/test262/install_test262.sh

      - name: Run integration tests
        run: |
          cargo brimstone-test -- --reindex
          cargo brimstone-test --release --features gc_stress_test -- --ignore-unimplemented

  # Run all integration tests for implemented features with handle tracking mode on.
  integration-tests-handle-tracking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5

      - name: Checkout test262 repo
        run: ./tests/test262/install_test262.sh

      - name: Run integration tests
        run: |
          cargo brimstone-test -- --reindex
          cargo brimstone-test --release --features handle_stats -- --ignore-unimplemented
