name: Build and Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Build and Test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: cargo test
