[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
    0: NewClosure r0, c0
    3: StoreGlobal r0, c1
    6: LoadUndefined r0
    8: Ret r0
  Constant Table:
    0: [BytecodeFunction: testAbruptMiddle]
    1: [String: testAbruptMiddle]
}

[BytecodeFunction: testAbruptMiddle] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 1
    3: LoadImmediate r0, 2
    6: LoadImmediate r0, 3
    9: Ret r0
}
