[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 2
      0: NewClosure r0, c0
      3: StoreGlobal r0, c1
      6: NewClosure r0, c2
      9: StoreGlobal r0, c3
     12: NewClosure r0, c4
     15: StoreGlobal r0, c5
     18: NewClosure r0, c6
     21: StoreGlobal r0, c7
     24: NewClosure r0, c8
     27: StoreGlobal r0, c9
     30: NewClosure r0, c10
     33: StoreGlobal r0, c11
     36: NewClosure r0, c12
     39: StoreGlobal r0, c13
     42: NewClosure r0, c14
     45: StoreGlobal r0, c15
     48: LoadImmediate r0, 1
     51: StoreToScope r0, 1, 0
     55: LoadImmediate r0, 1
     58: StoreToScope r0, 2, 0
     62: LoadImmediate r0, 2
     65: StoreToScope r0, 3, 0
     69: LoadImmediate r0, 3
     72: StoreToScope r0, 4, 0
     76: LoadImmediate r0, 1
     79: StoreToScope r0, 5, 0
     83: LoadImmediate r0, 1
     86: StoreToScope r0, 6, 0
     90: LoadImmediate r0, 2
     93: StoreToScope r0, 7, 0
     97: LoadImmediate r0, 3
    100: StoreToScope r0, 8, 0
    104: LoadFromScope r0, 1, 0
    108: CheckTdz r0, c16
    111: LoadFromScope r1, 5, 0
    115: CheckTdz r1, c17
    118: Add r0, r0, r1
    122: StoreToScope r0, 9, 0
    126: LoadFromScope r0, 11, 0
    130: CheckTdz r0, c18
    133: StoreToScope r0, 10, 0
    137: LoadImmediate r0, 1
    140: StoreToScope r0, 11, 0
    144: LoadUndefined r0
    146: Ret r0
  Constant Table:
    0: [BytecodeFunction: tdzGlobals]
    1: [String: tdzGlobals]
    2: [BytecodeFunction: noTdzLocals]
    3: [String: noTdzLocals]
    4: [BytecodeFunction: tdzLocals]
    5: [String: tdzLocals]
    6: [BytecodeFunction: tdzUseInInitializer]
    7: [String: tdzUseInInitializer]
    8: [BytecodeFunction: letNoInitializer]
    9: [String: letNoInitializer]
    10: [BytecodeFunction: assigningConst]
    11: [String: assigningConst]
    12: [BytecodeFunction: prefixUpdateConst]
    13: [String: prefixUpdateConst]
    14: [BytecodeFunction: postfixUpdateConst]
    15: [String: postfixUpdateConst]
    16: [String: c1]
    17: [String: l1]
    18: [String: c4]
}

[BytecodeFunction: tdzGlobals] {
  Parameters: 0, Registers: 2
     0: LoadFromScope r1, 1, 0
     4: CheckTdz r1, c0
     7: Neg r1, r1
    10: LoadFromScope r1, 5, 0
    14: CheckTdz r1, c1
    17: Neg r1, r1
    20: LoadFromScope r1, 1, 0
    24: CheckTdz r1, c0
    27: Mov r0, r1
    30: LoadUndefined r1
    32: Ret r1
  Constant Table:
    0: [String: c1]
    1: [String: l1]
}

[BytecodeFunction: noTdzLocals] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r2, 3
     3: LoadImmediate r0, 1
     6: LoadImmediate r1, 2
     9: Add r2, r0, r1
    13: Ret r2
}

[BytecodeFunction: tdzLocals] {
  Parameters: 0, Registers: 6
     0: LoadEmpty r1
     2: LoadEmpty r2
     4: LoadEmpty r4
     6: LoadImmediate r5, 3
     9: CheckTdz r1, c0
    12: CheckTdz r2, c1
    15: Add r0, r1, r2
    19: LoadImmediate r1, 1
    22: LoadImmediate r2, 1
    25: CheckTdz r4, c2
    28: Mov r3, r4
    31: LoadImmediate r4, 2
    34: CheckTdz r1, c0
    37: CheckTdz r2, c1
    40: Add r5, r1, r2
    44: Ret r5
  Constant Table:
    0: [String: c1]
    1: [String: l1]
    2: [String: c4]
}

[BytecodeFunction: tdzUseInInitializer] {
  Parameters: 0, Registers: 3
     0: LoadEmpty r0
     2: LoadEmpty r1
     4: LoadImmediate r2, 3
     7: CheckTdz r0, c0
    10: CheckTdz r1, c1
    13: LoadUndefined r2
    15: Ret r2
  Constant Table:
    0: [String: c1]
    1: [String: l1]
}

[BytecodeFunction: letNoInitializer] {
  Parameters: 0, Registers: 2
     0: LoadUndefined r0
     2: LoadImmediate r1, 2
     5: Add r1, r0, r1
     9: LoadUndefined r1
    11: Ret r1
}

[BytecodeFunction: assigningConst] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r0, 1
     3: LoadImmediate r1, 2
     6: ErrorConst c0
     8: LoadFromScope r2, 1, 0
    12: CheckTdz r2, c0
    15: StoreToScope r1, 1, 0
    19: LoadImmediate r1, 3
    22: ErrorConst c1
    24: Mov r0, r1
    27: LoadUndefined r1
    29: Ret r1
  Constant Table:
    0: [String: c1]
    1: [String: c2]
}

[BytecodeFunction: prefixUpdateConst] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: ErrorConst c0
     5: LoadFromScope r1, 1, 0
     9: CheckTdz r1, c0
    12: ToNumeric r1, r1
    15: Inc r1
    17: ErrorConst c0
    19: StoreToScope r1, 1, 0
    23: ErrorConst c1
    25: ToNumeric r0, r0
    28: Inc r0
    30: LoadUndefined r1
    32: Ret r1
  Constant Table:
    0: [String: c1]
    1: [String: c2]
}

[BytecodeFunction: postfixUpdateConst] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r0, 1
     3: ErrorConst c0
     5: LoadFromScope r2, 1, 0
     9: CheckTdz r2, c0
    12: ToNumeric r2, r2
    15: Mov r1, r2
    18: Inc r2
    20: ErrorConst c0
    22: StoreToScope r2, 1, 0
    26: ErrorConst c1
    28: ToNumeric r0, r0
    31: Mov r1, r0
    34: Inc r0
    36: ErrorConst c1
    38: LoadUndefined r1
    40: Ret r1
  Constant Table:
    0: [String: c1]
    1: [String: c2]
}
