[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: LoadUndefined r0
    32: Ret r0
  Constant Table:
    0: [BytecodeFunction: testSimple]
    1: [String: testSimple]
    2: [BytecodeFunction: testNestedUnlabeled]
    3: [String: testNestedUnlabeled]
    4: [BytecodeFunction: testLabeled]
    5: [String: testLabeled]
    6: [BytecodeFunction: continueSkipsLabeledStatement]
    7: [String: continueSkipsLabeledStatement]
    8: [BytecodeFunction: continueSkipsSwitch]
    9: [String: continueSkipsSwitch]
}

[BytecodeFunction: testSimple] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadTrue r0
     5: JumpFalse r0, 8 (.L1)
     8: LoadImmediate r0, 2
    11: Jump -8 (.L0)
  .L1:
    13: LoadUndefined r0
    15: Ret r0
}

[BytecodeFunction: testNestedUnlabeled] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadTrue r0
     5: JumpFalse r0, 26 (.L4)
     8: LoadImmediate r0, 2
  .L1:
    11: LoadFalse r0
    13: JumpFalse r0, 13 (.L3)
    16: LoadImmediate r0, 3
    19: JumpToBooleanFalse r0, 5 (.L2)
    22: Jump -11 (.L1)
  .L2:
    24: Jump -13 (.L1)
  .L3:
    26: LoadImmediate r0, 4
    29: Jump -26 (.L0)
  .L4:
    31: LoadImmediate r0, 5
    34: LoadUndefined r0
    36: Ret r0
}

[BytecodeFunction: testLabeled] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadTrue r0
     5: JumpFalse r0, 42 (.L6)
     8: LoadImmediate r0, 2
  .L1:
    11: LoadFalse r0
    13: JumpFalse r0, 29 (.L5)
    16: LoadImmediate r0, 3
    19: JumpToBooleanFalse r0, 5 (.L2)
    22: Jump -19 (.L0)
  .L2:
    24: LoadImmediate r0, 4
    27: JumpToBooleanFalse r0, 5 (.L3)
    30: Jump -27 (.L0)
  .L3:
    32: LoadImmediate r0, 5
    35: JumpToBooleanFalse r0, 5 (.L4)
    38: Jump -27 (.L1)
  .L4:
    40: Jump -29 (.L1)
  .L5:
    42: LoadImmediate r0, 6
    45: Jump -42 (.L0)
  .L6:
    47: LoadImmediate r0, 7
    50: LoadUndefined r0
    52: Ret r0
}

[BytecodeFunction: continueSkipsLabeledStatement] {
  Parameters: 0, Registers: 1
  .L0:
     0: LoadTrue r0
     2: JumpFalse r0, 16 (.L1)
     5: LoadImmediate r0, 1
     8: LoadImmediate r0, 2
    11: Jump -11 (.L0)
    13: LoadImmediate r0, 3
    16: Jump -16 (.L0)
  .L1:
    18: LoadUndefined r0
    20: Ret r0
}

[BytecodeFunction: continueSkipsSwitch] {
  Parameters: 0, Registers: 1
  .L0:
     0: LoadTrue r0
     2: JumpFalse r0, 20 (.L2)
     5: LoadImmediate r0, 1
     8: LoadFalse r0
    10: Jump 2 (.L1)
  .L1:
    12: LoadImmediate r0, 2
    15: Jump -15 (.L0)
    17: LoadImmediate r0, 3
    20: Jump -20 (.L0)
  .L2:
    22: LoadUndefined r0
    24: Ret r0
}
