[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: RetUndefined 
  Constant Table:
    0: [BytecodeFunction: testBasic]
    1: [String: testBasic]
    2: [BytecodeFunction: testBooleanTest]
    3: [String: testBooleanTest]
    4: [BytecodeFunction: testAbruptBody]
    5: [String: testAbruptBody]
    6: [BytecodeFunction: testBreakAndContinue]
    7: [String: testBreakAndContinue]
}

[BytecodeFunction: testBasic] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: LoadImmediate r0, 3
     9: JumpToBooleanTrue r0, -6 (.L0)
    12: LoadImmediate r0, 4
    15: RetUndefined 
}

[BytecodeFunction: testBooleanTest] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: LoadTrue r0
     8: JumpTrue r0, -5 (.L0)
    11: LoadImmediate r0, 3
    14: RetUndefined 
}

[BytecodeFunction: testAbruptBody] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: RetUndefined 
     7: LoadTrue r0
     9: JumpTrue r0, -6 (.L0)
    12: LoadImmediate r0, 4
    15: RetUndefined 
}

[BytecodeFunction: testBreakAndContinue] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: JumpToBooleanFalse r0, 5 (.L1)
     9: Jump 15 (.L3)
  .L1:
    11: LoadImmediate r0, 3
    14: JumpToBooleanFalse r0, 5 (.L2)
    17: Jump 2 (.L2)
  .L2:
    19: LoadTrue r0
    21: JumpTrue r0, -18 (.L0)
  .L3:
    24: LoadImmediate r0, 4
    27: RetUndefined 
}
