[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewClosure r0, c8
    31: StoreGlobal r0, c9, k4
    35: NewClosure r0, c10
    38: StoreGlobal r0, c11, k5
    42: NewClosure r0, c12
    45: StoreGlobal r0, c13, k6
    49: NewClosure r0, c14
    52: StoreGlobal r0, c15, k7
    56: NewClosure r0, c16
    59: StoreGlobal r0, c17, k8
    63: NewClosure r0, c18
    66: StoreGlobal r0, c19, k9
    70: NewClosure r0, c20
    73: StoreGlobal r0, c21, k10
    77: NewClosure r0, c22
    80: StoreGlobal r0, c23, k11
    84: NewClosure r0, c24
    87: StoreGlobal r0, c25, k12
    91: NewClosure r0, c26
    94: StoreGlobal r0, c27, k13
    98: RetUndefined 
  Constant Table:
    0: [BytecodeFunction: testNoInitTestOrUpdate]
    1: [String: testNoInitTestOrUpdate]
    2: [BytecodeFunction: testInitNoTestOrUpdate]
    3: [String: testInitNoTestOrUpdate]
    4: [BytecodeFunction: testNoInitTestNoUpdate]
    5: [String: testNoInitTestNoUpdate]
    6: [BytecodeFunction: testNoInitOrTestUpdate]
    7: [String: testNoInitOrTestUpdate]
    8: [BytecodeFunction: testInitTestNoUpdate]
    9: [String: testInitTestNoUpdate]
    10: [BytecodeFunction: testNoInitTestUpdate]
    11: [String: testNoInitTestUpdate]
    12: [BytecodeFunction: testInitNoTestUpdate]
    13: [String: testInitNoTestUpdate]
    14: [BytecodeFunction: testInitTestUpdate]
    15: [String: testInitTestUpdate]
    16: [BytecodeFunction: testVarDeclInit]
    17: [String: testVarDeclInit]
    18: [BytecodeFunction: testAbruptBody]
    19: [String: testAbruptBody]
    20: [BytecodeFunction: testBreakAndContinue]
    21: [String: testBreakAndContinue]
    22: [BytecodeFunction: testInitExprUnused]
    23: [String: testInitExprUnused]
    24: [BytecodeFunction: testTestExprUsed]
    25: [String: testTestExprUsed]
    26: [BytecodeFunction: testUpdateExprUnused]
    27: [String: testUpdateExprUnused]
}

[BytecodeFunction: testNoInitTestOrUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: Jump -3 (.L0)
     8: LoadImmediate r0, 3
    11: RetUndefined 
}

[BytecodeFunction: testInitNoTestOrUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: Jump -3 (.L0)
    11: LoadImmediate r0, 4
    14: RetUndefined 
}

[BytecodeFunction: testNoInitTestNoUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: JumpToBooleanFalse r0, 8 (.L1)
     9: LoadImmediate r0, 3
    12: Jump -9 (.L0)
  .L1:
    14: LoadImmediate r0, 4
    17: RetUndefined 
}

[BytecodeFunction: testNoInitOrTestUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 3
     6: LoadImmediate r0, 2
     9: Jump -6 (.L0)
    11: LoadImmediate r0, 4
    14: RetUndefined 
}

[BytecodeFunction: testInitTestNoUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: JumpToBooleanFalse r0, 8 (.L1)
    12: LoadImmediate r0, 4
    15: Jump -9 (.L0)
  .L1:
    17: LoadImmediate r0, 5
    20: RetUndefined 
}

[BytecodeFunction: testNoInitTestUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: JumpToBooleanFalse r0, 11 (.L1)
     9: LoadImmediate r0, 4
    12: LoadImmediate r0, 3
    15: Jump -12 (.L0)
  .L1:
    17: LoadImmediate r0, 5
    20: RetUndefined 
}

[BytecodeFunction: testInitNoTestUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 4
     9: LoadImmediate r0, 3
    12: Jump -6 (.L0)
    14: LoadImmediate r0, 5
    17: RetUndefined 
}

[BytecodeFunction: testInitTestUpdate] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: JumpToBooleanFalse r0, 11 (.L1)
    12: LoadImmediate r0, 5
    15: LoadImmediate r0, 4
    18: Jump -12 (.L0)
  .L1:
    20: LoadImmediate r0, 6
    23: RetUndefined 
}

[BytecodeFunction: testVarDeclInit] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r1, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r1, 3
     9: JumpToBooleanFalse r1, 11 (.L1)
    12: LoadImmediate r1, 5
    15: LoadImmediate r1, 4
    18: Jump -12 (.L0)
  .L1:
    20: LoadImmediate r1, 6
    23: RetUndefined 
}

[BytecodeFunction: testAbruptBody] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: JumpToBooleanFalse r0, 12 (.L1)
    12: LoadImmediate r0, 5
    15: RetUndefined 
    16: LoadImmediate r0, 4
    19: Jump -13 (.L0)
  .L1:
    21: LoadImmediate r0, 7
    24: RetUndefined 
}

[BytecodeFunction: testBreakAndContinue] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadImmediate r0, 2
  .L0:
     6: LoadImmediate r0, 3
     9: JumpToBooleanFalse r0, 30 (.L4)
    12: LoadImmediate r0, 5
    15: JumpToBooleanFalse r0, 5 (.L1)
    18: Jump 21 (.L4)
  .L1:
    20: LoadImmediate r0, 6
    23: LoadImmediate r0, 7
    26: JumpToBooleanFalse r0, 5 (.L2)
    29: Jump 5 (.L3)
  .L2:
    31: LoadImmediate r0, 8
  .L3:
    34: LoadImmediate r0, 4
    37: Jump -31 (.L0)
  .L4:
    39: LoadImmediate r0, 7
    42: RetUndefined 
}

[BytecodeFunction: testInitExprUnused] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 1
    3: Inc r0
  .L0:
    5: Jump 0 (.L0)
    7: RetUndefined 
}

[BytecodeFunction: testTestExprUsed] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
  .L0:
     3: ToNumeric r0, r0
     6: Mov r1, r0
     9: Inc r0
    11: JumpToBooleanFalse r1, 5 (.L1)
    14: Jump -11 (.L0)
  .L1:
    16: RetUndefined 
}

[BytecodeFunction: testUpdateExprUnused] {
  Parameters: 0, Registers: 1
    0: LoadImmediate r0, 1
  .L0:
    3: Inc r0
    5: Jump -2 (.L0)
    7: RetUndefined 
}
