[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewClosure r0, c8
    31: StoreGlobal r0, c9, k4
    35: NewClosure r0, c10
    38: StoreGlobal r0, c11, k5
    42: NewClosure r0, c12
    45: StoreGlobal r0, c13, k6
    49: LoadUndefined r0
    51: Ret r0
  Constant Table:
    0: [BytecodeFunction: basicVar]
    1: [String: basicVar]
    2: [BytecodeFunction: basicConstLet]
    3: [String: basicConstLet]
    4: [BytecodeFunction: testBreakAndContinue]
    5: [String: testBreakAndContinue]
    6: [BytecodeFunction: lhsIdentifier]
    7: [String: lhsIdentifier]
    8: [BytecodeFunction: lhsMember]
    9: [String: lhsMember]
    10: [BytecodeFunction: lhsDestructuring]
    11: [String: lhsDestructuring]
    12: [BytecodeFunction: lhsTdz]
    13: [String: lhsTdz]
}

[BytecodeFunction: basicVar] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r1, 1
     3: NewObject r1, 4
     6: JumpNullish r1, 20 (.L1)
     9: NewForInIterator r1, r1
  .L0:
    12: ForInNext r2, r1
    15: JumpNullish r2, 11 (.L1)
    18: Mov r0, r2
    21: LoadImmediate r2, 2
    24: Jump -12 (.L0)
  .L1:
    26: LoadImmediate r1, 3
    29: LoadUndefined r1
    31: Ret r1
}

[BytecodeFunction: basicConstLet] {
  Parameters: 0, Registers: 4
     0: LoadImmediate r2, 1
     3: NewObject r2, 4
     6: JumpNullish r2, 20 (.L1)
     9: NewForInIterator r2, r2
  .L0:
    12: ForInNext r3, r2
    15: JumpNullish r3, 11 (.L1)
    18: Mov r1, r3
    21: LoadImmediate r3, 2
    24: Jump -12 (.L0)
  .L1:
    26: LoadImmediate r2, 3
    29: NewObject r2, 4
    32: JumpNullish r2, 20 (.L3)
    35: NewForInIterator r2, r2
  .L2:
    38: ForInNext r3, r2
    41: JumpNullish r3, 11 (.L3)
    44: Mov r0, r3
    47: LoadImmediate r3, 3
    50: Jump -12 (.L2)
  .L3:
    52: LoadImmediate r2, 4
    55: LoadUndefined r2
    57: Ret r2
}

[BytecodeFunction: testBreakAndContinue] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r1, 1
     3: NewObject r1, 4
     6: JumpNullish r1, 33 (.L3)
     9: NewForInIterator r1, r1
  .L0:
    12: ForInNext r2, r1
    15: JumpNullish r2, 24 (.L3)
    18: Mov r0, r2
    21: LoadImmediate r2, 2
    24: JumpToBooleanFalse r2, 5 (.L1)
    27: Jump 12 (.L3)
  .L1:
    29: LoadImmediate r2, 3
    32: JumpToBooleanFalse r2, 5 (.L2)
    35: Jump -23 (.L0)
  .L2:
    37: Jump -25 (.L0)
  .L3:
    39: LoadImmediate r1, 4
    42: LoadUndefined r1
    44: Ret r1
}

[BytecodeFunction: lhsIdentifier] {
  Parameters: 1, Registers: 2
     0: LoadImmediate r0, 1
     3: NewObject r0, 4
     6: JumpNullish r0, 17 (.L1)
     9: NewForInIterator r0, r0
  .L0:
    12: ForInNext r1, r0
    15: JumpNullish r1, 8 (.L1)
    18: Mov a0, r1
    21: Jump -9 (.L0)
  .L1:
    23: LoadImmediate r0, 2
    26: LoadUndefined r0
    28: Ret r0
}

[BytecodeFunction: lhsMember] {
  Parameters: 1, Registers: 3
     0: LoadImmediate r0, 1
     3: NewObject r0, 4
     6: JumpNullish r0, 22 (.L1)
     9: NewForInIterator r0, r0
  .L0:
    12: ForInNext r1, r0
    15: JumpNullish r1, 13 (.L1)
    18: SetNamedProperty a0, c0, r1, k0
    23: LoadImmediate r1, 2
    26: Jump -14 (.L0)
  .L1:
    28: LoadImmediate r0, 3
    31: NewObject r0, 4
    34: JumpNullish r0, 24 (.L3)
    37: NewForInIterator r0, r0
  .L2:
    40: ForInNext r1, r0
    43: JumpNullish r1, 15 (.L3)
    46: LoadImmediate r2, 1
    49: SetProperty a0, r2, r1
    53: LoadImmediate r1, 4
    56: Jump -16 (.L2)
  .L3:
    58: LoadImmediate r0, 5
    61: LoadUndefined r0
    63: Ret r0
  Constant Table:
    0: [String: foo]
}

[BytecodeFunction: lhsDestructuring] {
  Parameters: 1, Registers: 6
     0: LoadImmediate r3, 1
     3: NewObject r3, 4
     6: JumpNullish r3, 41 (.L2)
     9: NewForInIterator r3, r3
  .L0:
    12: ForInNext r4, r3
    15: JumpNullish r4, 32 (.L2)
    18: GetNamedProperty r0, r4, c0, k0
    23: GetNamedProperty r1, r4, c1, k1
    28: GetNamedProperty r5, r4, c2, k2
    33: JumpNotUndefined r5, 6 (.L1)
    36: LoadImmediate r5, 1
  .L1:
    39: Mov r2, r5
    42: LoadImmediate r4, 2
    45: Jump -33 (.L0)
  .L2:
    47: LoadImmediate r3, 3
    50: NewObject r3, 4
    53: JumpNullish r3, 41 (.L5)
    56: NewForInIterator r3, r3
  .L3:
    59: ForInNext r4, r3
    62: JumpNullish r4, 32 (.L5)
    65: GetNamedProperty r0, r4, c0, k3
    70: GetNamedProperty r1, r4, c1, k4
    75: GetNamedProperty r5, r4, c2, k5
    80: JumpNotUndefined r5, 6 (.L4)
    83: LoadImmediate r5, 1
  .L4:
    86: Mov r2, r5
    89: LoadImmediate r4, 4
    92: Jump -33 (.L3)
  .L5:
    94: LoadImmediate r3, 5
    97: LoadUndefined r3
    99: Ret r3
  Constant Table:
    0: [String: a]
    1: [String: b]
    2: [String: d]
}

[BytecodeFunction: lhsTdz] {
  Parameters: 0, Registers: 5
     0: PushFunctionScope c0
     2: LoadEmpty r2
     4: StoreToScope r2, 0, 0
     8: PushLexicalScope c1
    10: LoadEmpty r2
    12: StoreToScope r2, 0, 0
    16: NewObject r2, 4
    19: JumpNullish r2, 31 (.L1)
    22: NewForInIterator r2, r2
    25: PopScope 
  .L0:
    26: PushLexicalScope c1
    28: LoadEmpty r3
    30: StoreToScope r3, 0, 0
    34: ForInNext r3, r2
    37: JumpNullish r3, 13 (.L1)
    40: StoreToScope r3, 0, 0
    44: NewClosure r1, c2
    47: PopScope 
    48: Jump -22 (.L0)
  .L1:
    50: PopScope 
    51: LoadImmediate r2, 1
    54: StoreToScope r2, 0, 0
    58: NewObject r2, 4
    61: JumpNullish r2, 28 (.L3)
    64: NewForInIterator r2, r2
  .L2:
    67: ForInNext r3, r2
    70: JumpNullish r3, 19 (.L3)
    73: LoadFromScope r4, 0, 0
    77: CheckTdz r4, c3
    80: StoreToScope r3, 0, 0
    84: NewClosure r0, c4
    87: Jump -20 (.L2)
  .L3:
    89: LoadUndefined r2
    91: Ret r2
  Constant Table:
    0: [ScopeNames]
    1: [ScopeNames]
    2: [BytecodeFunction: inner]
    3: [String: y]
    4: [BytecodeFunction: inner]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: x]
}

[BytecodeFunction: inner] {
  Parameters: 0, Registers: 1
    0: LoadFromScope r0, 0, 0
    4: CheckTdz r0, c0
    7: Ret r0
  Constant Table:
    0: [String: y]
}
