[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: NewClosure r0, c8
    31: StoreGlobal r0, c9, k4
    35: NewClosure r0, c10
    38: StoreGlobal r0, c11, k5
    42: LoadUndefined r0
    44: Ret r0
  Constant Table:
    0: [BytecodeFunction: testNoAlternate]
    1: [String: testNoAlternate]
    2: [BytecodeFunction: testAlternate]
    3: [String: testAlternate]
    4: [BytecodeFunction: testNested]
    5: [String: testNested]
    6: [BytecodeFunction: testIfElse]
    7: [String: testIfElse]
    8: [BytecodeFunction: testIfElseNoCatchAll]
    9: [String: testIfElseNoCatchAll]
    10: [BytecodeFunction: testIfNoToBoolean]
    11: [String: testIfNoToBoolean]
}

[BytecodeFunction: testNoAlternate] {
  Parameters: 1, Registers: 1
     0: JumpToBooleanFalse a0, 8 (.L0)
     3: LoadImmediate r0, 1
     6: Ret r0
  .L0:
     8: LoadImmediate r0, 2
    11: Ret r0
}

[BytecodeFunction: testAlternate] {
  Parameters: 1, Registers: 1
     0: JumpToBooleanFalse a0, 8 (.L0)
     3: LoadImmediate r0, 1
     6: Ret r0
  .L0:
     8: LoadImmediate r0, 2
    11: Ret r0
}

[BytecodeFunction: testNested] {
  Parameters: 2, Registers: 1
     0: JumpToBooleanFalse a0, 16 (.L1)
     3: JumpToBooleanFalse a1, 8 (.L0)
     6: LoadImmediate r0, 1
     9: Ret r0
  .L0:
    11: LoadImmediate r0, 2
    14: Ret r0
  .L1:
    16: JumpToBooleanFalse a1, 8 (.L2)
    19: LoadImmediate r0, 3
    22: Ret r0
  .L2:
    24: LoadImmediate r0, 4
    27: Ret r0
}

[BytecodeFunction: testIfElse] {
  Parameters: 3, Registers: 1
     0: JumpToBooleanFalse a0, 8 (.L0)
     3: LoadImmediate r0, 1
     6: Ret r0
  .L0:
     8: JumpToBooleanFalse a1, 8 (.L1)
    11: LoadImmediate r0, 2
    14: Ret r0
  .L1:
    16: JumpToBooleanFalse a2, 8 (.L2)
    19: LoadImmediate r0, 3
    22: Ret r0
  .L2:
    24: LoadImmediate r0, 4
    27: Ret r0
}

[BytecodeFunction: testIfElseNoCatchAll] {
  Parameters: 2, Registers: 1
     0: JumpToBooleanFalse a0, 8 (.L0)
     3: LoadImmediate r0, 1
     6: Ret r0
  .L0:
     8: JumpToBooleanFalse a1, 8 (.L1)
    11: LoadImmediate r0, 2
    14: Ret r0
  .L1:
    16: LoadImmediate r0, 3
    19: Ret r0
}

[BytecodeFunction: testIfNoToBoolean] {
  Parameters: 1, Registers: 1
     0: LessThan r0, a0, a0
     4: JumpFalse r0, 8 (.L0)
     7: LoadImmediate r0, 1
    10: Ret r0
  .L0:
    12: LessThan r0, a0, a0
    16: JumpFalse r0, 8 (.L1)
    19: LoadImmediate r0, 2
    22: Ret r0
  .L1:
    24: LoadImmediate r0, 3
    27: Ret r0
}
