[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: NewClosure r0, c6
    21: StoreGlobal r0, c7
    24: NewClosure r0, c8
    27: StoreGlobal r0, c9
    30: NewClosure r0, c10
    33: StoreGlobal r0, c11
    36: NewClosure r0, c12
    39: StoreGlobal r0, c13
    42: NewClosure r0, c14
    45: StoreGlobal r0, c15
    48: LoadUndefined r0
    50: Ret r0
  Constant Table:
    0: [BytecodeFunction: empty]
    1: [String: empty]
    2: [BytecodeFunction: singleCaseWithFallthrough]
    3: [String: singleCaseWithFallthrough]
    4: [BytecodeFunction: singleCaseWithBreak]
    5: [String: singleCaseWithBreak]
    6: [BytecodeFunction: multipleCases]
    7: [String: multipleCases]
    8: [BytecodeFunction: singleDefaultCase]
    9: [String: singleDefaultCase]
    10: [BytecodeFunction: multipleCasesWithDefault]
    11: [String: multipleCasesWithDefault]
    12: [BytecodeFunction: multipleCasesWithDefaultInMiddle]
    13: [String: multipleCasesWithDefaultInMiddle]
    14: [BytecodeFunction: multipleCasesWithDefaultInMiddleFallthrough]
    15: [String: multipleCasesWithDefaultInMiddleFallthrough]
}

[BytecodeFunction: empty] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: Jump 2 (.L0)
  .L0:
     7: LoadImmediate r0, 2
    10: LoadUndefined r0
    12: Ret r0
}

[BytecodeFunction: singleCaseWithFallthrough] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r1, 2
     8: StrictEqual r1, r0, r1, ic0
    13: JumpTrue r1, 5 (.L0)
    16: Jump 5 (.L1)
  .L0:
    18: LoadImmediate r0, 3
  .L1:
    21: LoadImmediate r0, 4
    24: LoadUndefined r0
    26: Ret r0
}

[BytecodeFunction: singleCaseWithBreak] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r1, 2
     8: StrictEqual r1, r0, r1, ic0
    13: JumpTrue r1, 5 (.L0)
    16: Jump 7 (.L1)
  .L0:
    18: LoadImmediate r0, 3
    21: Jump 2 (.L1)
  .L1:
    23: LoadImmediate r0, 4
    26: LoadUndefined r0
    28: Ret r0
}

[BytecodeFunction: multipleCases] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r1, 2
     8: StrictEqual r1, r0, r1, ic0
    13: JumpTrue r1, 27 (.L0)
    16: LoadImmediate r1, 4
    19: StrictEqual r1, r0, r1, ic1
    24: JumpTrue r1, 21 (.L1)
    27: LoadImmediate r1, 6
    30: StrictEqual r1, r0, r1, ic2
    35: JumpTrue r1, 13 (.L2)
    38: Jump 15 (.L3)
  .L0:
    40: LoadImmediate r0, 3
    43: Jump 10 (.L3)
  .L1:
    45: LoadImmediate r0, 5
  .L2:
    48: LoadImmediate r0, 7
    51: Jump 2 (.L3)
  .L3:
    53: LoadImmediate r0, 3
    56: LoadUndefined r0
    58: Ret r0
}

[BytecodeFunction: singleDefaultCase] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: Jump 2 (.L0)
  .L0:
     7: LoadImmediate r0, 2
    10: LoadImmediate r0, 3
    13: LoadUndefined r0
    15: Ret r0
}

[BytecodeFunction: multipleCasesWithDefault] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r1, 2
     8: StrictEqual r1, r0, r1, ic0
    13: JumpTrue r1, 16 (.L0)
    16: LoadImmediate r1, 4
    19: StrictEqual r1, r0, r1, ic1
    24: JumpTrue r1, 10 (.L1)
    27: Jump 12 (.L2)
  .L0:
    29: LoadImmediate r0, 3
    32: Jump 12 (.L3)
  .L1:
    34: LoadImmediate r0, 5
    37: Jump 7 (.L3)
  .L2:
    39: LoadImmediate r0, 6
    42: Jump 2 (.L3)
  .L3:
    44: LoadImmediate r0, 7
    47: LoadUndefined r0
    49: Ret r0
}

[BytecodeFunction: multipleCasesWithDefaultInMiddle] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r1, 2
     8: StrictEqual r1, r0, r1, ic0
    13: JumpTrue r1, 16 (.L0)
    16: LoadImmediate r1, 5
    19: StrictEqual r1, r0, r1, ic1
    24: JumpTrue r1, 15 (.L2)
    27: Jump 7 (.L1)
  .L0:
    29: LoadImmediate r0, 3
    32: Jump 12 (.L3)
  .L1:
    34: LoadImmediate r0, 4
    37: Jump 7 (.L3)
  .L2:
    39: LoadImmediate r0, 6
    42: Jump 2 (.L3)
  .L3:
    44: LoadImmediate r0, 7
    47: LoadUndefined r0
    49: Ret r0
}

[BytecodeFunction: multipleCasesWithDefaultInMiddleFallthrough] {
  Parameters: 0, Registers: 2
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: LoadImmediate r1, 2
     8: StrictEqual r1, r0, r1, ic0
    13: JumpTrue r1, 16 (.L0)
    16: LoadImmediate r1, 5
    19: StrictEqual r1, r0, r1, ic1
    24: JumpTrue r1, 11 (.L2)
    27: Jump 5 (.L1)
  .L0:
    29: LoadImmediate r0, 3
  .L1:
    32: LoadImmediate r0, 4
  .L2:
    35: LoadImmediate r0, 6
    38: LoadImmediate r0, 7
    41: LoadUndefined r0
    43: Ret r0
}
