[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1
     6: NewClosure r0, c2
     9: StoreGlobal r0, c3
    12: NewClosure r0, c4
    15: StoreGlobal r0, c5
    18: LoadImmediate r0, 1
    21: StoreGlobal r0, c6
    24: LoadImmediate r0, 1
    27: StoreGlobal r0, c6
    30: LoadImmediate r0, 2
    33: StoreGlobal r0, c7
    36: LoadImmediate r0, 3
    39: StoreGlobal r0, c8
    42: LoadUndefined r0
    44: Ret r0
  Constant Table:
    0: [BytecodeFunction: testLocals]
    1: [String: testLocals]
    2: [BytecodeFunction: testDuplicates]
    3: [String: testDuplicates]
    4: [BytecodeFunction: testLoadFrom]
    5: [String: testLoadFrom]
    6: [String: x]
    7: [String: y]
    8: [String: z]
}

[BytecodeFunction: testLocals] {
  Parameters: 0, Registers: 3
     0: LoadImmediate r2, 3
     3: LoadImmediate r0, 1
     6: LoadImmediate r1, 2
     9: Add r2, r0, r1
    13: Ret r2
}

[BytecodeFunction: testDuplicates] {
  Parameters: 0, Registers: 2
    0: LoadImmediate r1, 3
    3: LoadImmediate r0, 1
    6: LoadImmediate r0, 2
    9: Ret r0
}

[BytecodeFunction: testLoadFrom] {
  Parameters: 1, Registers: 6
     0: LoadImmediate r0, 1
     3: LoadImmediate r4, 1
     6: LoadImmediate r5, 2
     9: Add r4, r4, r5
    13: LoadImmediate r5, 3
    16: Add r1, r4, r5
    20: Mov r2, a0
    23: LoadGlobal r3, c0
    26: LoadUndefined r4
    28: Ret r4
  Constant Table:
    0: [String: y]
}
