[BytecodeFunction: <global>] {
  Parameters: 0, Registers: 1
     0: NewClosure r0, c0
     3: StoreGlobal r0, c1, k0
     7: NewClosure r0, c2
    10: StoreGlobal r0, c3, k1
    14: NewClosure r0, c4
    17: StoreGlobal r0, c5, k2
    21: NewClosure r0, c6
    24: StoreGlobal r0, c7, k3
    28: RetUndefined 
  Constant Table:
    0: [BytecodeFunction: testBasic]
    1: [String: testBasic]
    2: [BytecodeFunction: testBooleanTest]
    3: [String: testBooleanTest]
    4: [BytecodeFunction: testAbruptBody]
    5: [String: testAbruptBody]
    6: [BytecodeFunction: testBreakAndContinue]
    7: [String: testBreakAndContinue]
}

[BytecodeFunction: testBasic] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadImmediate r0, 2
     6: JumpToBooleanFalse r0, 8 (.L1)
     9: LoadImmediate r0, 3
    12: Jump -9 (.L0)
  .L1:
    14: LoadImmediate r0, 4
    17: RetUndefined 
}

[BytecodeFunction: testBooleanTest] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadTrue r0
     5: JumpFalse r0, 8 (.L1)
     8: LoadImmediate r0, 2
    11: Jump -8 (.L0)
  .L1:
    13: LoadImmediate r0, 3
    16: RetUndefined 
}

[BytecodeFunction: testAbruptBody] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
     3: LoadTrue r0
     5: JumpFalse r0, 7 (.L0)
     8: LoadImmediate r0, 2
    11: RetUndefined 
  .L0:
    12: LoadImmediate r0, 4
    15: RetUndefined 
}

[BytecodeFunction: testBreakAndContinue] {
  Parameters: 0, Registers: 1
     0: LoadImmediate r0, 1
  .L0:
     3: LoadTrue r0
     5: JumpFalse r0, 21 (.L3)
     8: LoadImmediate r0, 2
    11: JumpToBooleanFalse r0, 5 (.L1)
    14: Jump 12 (.L3)
  .L1:
    16: LoadImmediate r0, 3
    19: JumpToBooleanFalse r0, 5 (.L2)
    22: Jump -19 (.L0)
  .L2:
    24: Jump -21 (.L0)
  .L3:
    26: LoadImmediate r0, 4
    29: RetUndefined 
}
